### ISSUE TITLE
Add languages: Eastern Punjabi (pan)

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#10]
* Name: Punjabi (Eastern)
* Requested by: sabretou
* ISO code: pan
* icon: http://goo.gl/QgFcfo

TODO
* Also change string for pnb from "Punjabi" to "Punjabi (Western)". 
* icon for pnb: http://goo.gl/F3rBNK

Read http://tatoeba.org/eng/wall/show_message/17381#message_17381
The changes mentioned in that thread involve splitting the existing Punjabi language sentences into two, each with a different script:"(pan) is Eastern, or Indian Punjabi, predominantly written in Gurmukhi and spoken in India, while (pnb) is Western, or Pakistani punjabi, written in Shahmukhi and spoken in Pakistan."

Once I get two lists from sabretou (one for Eastern, one for Western), I'll add a link to this ticket.

**Comment by trang** [comment]
@alanfgh I'm assigning you this.

Initially I was planning to change the code to include only Easter Punjabi (pan), but I figured it'd make more sense to add it as a new language, and then change the language of the existing Punjabi sentences from Western to Eastern, except the ones that are actually in Western Punjabi.

**Comment by alanfgh** [comment]
I updated add_lang.sh and ran it to update files, which I committed. Trang pulled them onto the server and executed the part that needed to be run there. After this, I added an option to the script that allows the user to choose whether to update files, execute existing updated files, or both.
