### ISSUE TITLE
Duplicate Merging Script Isn't Working.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1002]
https://tatoeba.org/eng/sentence_comments/of_user/Horus

This apparently hasn't been running since yesterday.
If you have set it to only run once a day, then maybe there is no problem.

I noticed this has still not been merged.

Are you busy?
https://tatoeba.org/eng/sentences/show/4895520  (contributed 9 hours ago)

Are you busy?
https://tatoeba.org/eng/sentences/show/68948

**Comment by loolmeh** [comment]
should be good now, looks like the lang_id update broke it
