### ISSUE TITLE
Audio doesn't play in Safari - Computer & iPad

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1010]
I sent the following URL to a new audio contributor, but it didn't work on her iPad, so I checked in on both my iPad and my Mac using Safari.

https://tatoeba.org/eng/sentences/search?query=%22%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82%24%22%7C%22%E3%81%A7%E3%81%99%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%99%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%9B%E3%82%93%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82%22&from=jpn&to=und&orphans=no&unapproved=no&user=tommy_san&tags=&has_audio=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=modified

**Comment by sacredceltic** [comment]
on iOS, it doesn't work on Chrome either. It's an OS issue, not a browser issue, I think.

**Comment by jiru** [comment]
Related/duplicate: #941

**Comment by RyckRichards** [comment]
cueyayotl says that  the "speaker icon" doesn't work on iPhone.

**Comment by ckjpn** [comment]
Perhaps the bugs related to Safari should have a priority upgrade.

I was just looking at Google Analytics. Safari is the 2nd-most used browser by visitors to tatoeba.org.

Chrome 59%; Safari 16%, Firefox 8%, Android Browser 5%, Internet Explorer 4%, ....

See the related issues.
https://github.com/Tatoeba/tatoeba2/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+safari

**Comment by ckjpn** [comment]
## On my Desktop Mac, Safari has quit playing the audio on tatoeba.org

I usually use Chrome or Firefox to access tatoebe.org, so it doesn't really bother me personally, but as a web designer, I'd like to see websites work on as many platforms as possible.

![screen shot 2016-10-29 at 12 42 59](https://cloud.githubusercontent.com/assets/7934273/19827003/e68c4d52-9dd5-11e6-8fdb-eda39d624731.png)

## The 3 different audio players I have on the following pages still work.

Perhaps tatoeba.org should consider using one of these.

http://www.manythings.org//bilingual/afr/14.html

http://www.manythings.org/sentences/words/you/1.html

http://www.manythings.org/audiosentences/fra/98.html


The small player at the top of the following page is the same as the /words/ one above, just with a different set of images.  This might be the one to consider for tatoeba.org.

http://study.aitech.ac.jp/browse/audio-2016-07-26/116996.html

**Comment by sacredceltic** [comment]
I used Chrome but I'm fed up with it because it doesn't apply OSX/iOS text shortcuts and provides no alternative solution to write shortcuts. Besides, it eats up too much memory.

**Comment by RyckRichards** [comment]
Since members have reported that this bug is fixed, I'm closing it.
