### ISSUE TITLE
Put a link to https://tatoeba.org/stats/sentences_by_language on the "settings" page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1012]
Someone on the IRC today was asking about the ISO 639-3 codes needed for the "Languages" setting.
It might be useful to have a link there, so people can easily find the codes we use.

![screen shot 2016-02-21 at 17 06 34](https://cloud.githubusercontent.com/assets/7934273/13201638/edc47a64-d8bd-11e5-97e8-dac309c2cb5d.png)

https://tatoeba.org/user/settings
https://tatoeba.org/stats/sentences_by_language

**Comment by damascene** [comment]
exactly thank you for taking a screen shot and explaining it
