### ISSUE TITLE
Morisyen (mfe)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1021]
* Language name: Morisyen 
* Language info: https://en.wikipedia.org/wiki/Mauritian_Creole
* ISO 639-3 code: mfe
* Public List: https://tatoeba.org/eng/sentences_lists/show/5768
* Icon: https://en.wikipedia.org/wiki/Mauritius#/media/File:Flag_of_Mauritius.svg
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

================
[for dev.tatoeba.org]
CALL add_new_language('mfe', 4220);

[for tatoeba.org]
CALL add_new_language('mfe', 5768);

http://dev.tatoeba.org/eng/sentences_lists/show/4220

**Comment by jiru** [comment]
@RyckRichards I fixed the code name in your comment (it was mve instead of mfe)
