### ISSUE TITLE
"Currently contributing" members = 0

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1026]
On members > list of all members, it doesn't show the members who participated in the last contributions.

It happens in all the browsers I tested (Mozilla, Google Chrome, IE, Opera)

![owezjtz](https://cloud.githubusercontent.com/assets/7658430/13380104/ae632310-de18-11e5-91b8-e931847b647b.png)

**Comment by trang** [comment]
Fixed in d8fb3a1197f09ca723afacf8eb6d441411204934.
