### ISSUE TITLE
"Show translations in:" in lists is not working

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1027]
Lists displays sentences in all the languages, no matter if you selected a specific language or even none.

List: https://tatoeba.org/eng/sentences_lists/show/4065/

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/13380963/f7b4315c-de2d-11e5-8992-3ddd2d664381.png)

Selected: None: https://tatoeba.org/eng/sentences_lists/show/4065/none

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/13380973/430aaaaa-de2e-11e5-986d-da28db2ecf1a.png)

Selected: German - https://tatoeba.org/eng/sentences_lists/show/4065/deu

![screenshot_3](https://cloud.githubusercontent.com/assets/7658430/13380984/ac2132e8-de2e-11e5-8693-e97b317307ff.png)

**Comment by jiru** [comment]
Thanks for letting us know, RyckRichards. It’s now fixed in production.
