### ISSUE TITLE
Delete ratings from a sentence when it is changed.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1034]
Possibly, also send a message to the person who rated the sentence.

https://tatoeba.org/eng/wall/show_message/25624#message_25624

Wezel
47 minutes ago

** Notify users when a rated sentence is changed **

I have no idea if that’s feasible at all, but I think it would be nice if a user who had rated a sentence (OK/unsure/not OK) received a notification after the sentence is changed. Now we have a situation when bad sentences are eventually corrected, but old ratings remain (#443293, #412659).
hide replies

CK
35 minutes ago

It might also be a good idea to delete ratings from a sentence when a sentence is changed.

There will be some members who have rated sentences who perhaps leave the project and will not respond to being notified.

There are other currently-active members who have email notifications turned off in their settings.

**Comment by trang** [comment]
I'm closing this because there is already a related issue: #747

Also I wouldn't delete the rating. Cf. https://tatoeba.org/eng/wall/show_message/24031#message_24031

> Rather than removing the rating, there will be a page where users can see their ratings that are outdated (i.e. ratings on sentences that have been modified).

> I think this is better than simply removing the rating because you don't lose the information that you have marked the sentence. Otherwise, some sentences will disappear from your collection and you won't know it.
