### ISSUE TITLE
Setting to restrict languages of translations is broken

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1037]
I broke the user setting “Languages” during #1007. Now, all the languages of translations are displayed regardless of the setting.

**Comment by achaitanyasai** [comment]
I would like to work on this issue.

**Comment by RyckRichards** [comment]
By [Raizin](https://tatoeba.org/eng/user/profile/Raizin) on the [Wall](https://tatoeba.org/eng/user/profile/Raizin):

> If you link or unlink a sentence (be it by clicking the (un)link icon next to the sentence, or by manually entering the sentence number) the list resets, and it correctly displays the Languages preferences.

**Comment by trang** [comment]
@RyckRichards, your link to the Wall is linking to Raizin's profile.

@achaitanyasai, do you have enough information to work on this?

**Comment by RyckRichards** [comment]
@trang I've just fixed that. Thank you!

**Comment by jiru** [comment]
@achaitanyasai Since I’m the one who broke the setting, I’ll take care of it.
