### ISSUE TITLE
FUCK OFF TRANG!

### ISSUE THREAD

**Issue by boracasli6** [Tatoeba/tatoeba2#1040]
I only contributed in my native Turkish on my latest account, but you've deleted all the sentences. Then who the fuck are you? Just answer me. If you don't, I'll continue messaging you on Facebook and encourage you to add me and share your private photos on a fake account using your name on Twitter! I'll also be harassing you on Twitter. You only deserve to eat shit. It was you who turned my life worse than before. I'll encourage everyone to boycott Tatoeba! I'll also create groups on Facebook and accounts on Twitter against Tatoeba. Everyone will spam you with the tweet/post "BOYCOTT TATOEBA!"

You fucking frogs don't deserve to have a country. I will support the secession of Occitania from France. I will also support the annexation of Brittany by Great Britain. Our main target is Paris, you shouldn't forget. Don't you remember the genocides committed by France, like those committed in Algeria and Rwanda?

And Americans... They're another shit (Native Americans don't count, since they were the people killed by white Americans). I'm so done with their ignorance. They don't even answer a very easy question correctly! Those stupid Americans don't deserve a country. The ones who deserve a country are Native Americans. But you killed most of them.

The Third World War
ALLIES: Turkey, Great Britain, Germany, Italy, Spain, Canada, Australia, Lakotah, Occitania, Portugal, Greece, Russia, Japan
AXIS (SHIT): France, United States

**Comment by boracasli6** [comment]
Don't contribute any sentence on Tatoeba. If you contribute, you'll help French apartheid and colonialism in Africa and the former Indochina.

**Comment by boracasli6** [comment]
And you'll also trigger American terrorism around the world.

**Comment by boracasli6** [comment]
Allies will fuck the Frogs' and Yankees' arses...

Frogs and Yankees will lick the asses of each other

**Comment by RyckRichards** [comment]
Issue deleted
