### ISSUE TITLE
Create a home page that is more useful for logged-in members.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1045]
Assuming that the result of Issue #947 (Home Page for First-time Visitors) is that we also need a new page for logged-in members, I would like to present an idea.

In addition to the ideas I presented on the #947 page, here is another idea.

Make it possible for members to fine-tune their own "home" page, somewhat like Moodle has a "My home / Dashboard" (https://docs.moodle.org/30/en/Dashboard).

Here is a quick mock-up for the member "CK" whose native language is "English" and who often translates from "Japanese."  Other members would have different settings, of course.

Features:
- At the top of the page are 2 things that are likely useful for members.
- Regular members can easily monitor incoming sentences in their own native languages.
- Members can easily monitor new comments on their own sentences.

![screen shot 2016-03-06 at 10 38 48](https://cloud.githubusercontent.com/assets/7934273/13551777/48f521f6-e389-11e5-9632-23af3b2744ed.png)

There is a working version here.
http://www.manythings.org/tatoeba/personal.php
(This grabs parts of pages on tatoeba.org, so it may take a while for it to load.)

**Comment by ckjpn** [comment]
Here is an updated version, showing "Personal Stats" (not generated in real time for the mock-up demo).

![screen shot 2016-03-06 at 11 38 44](https://cloud.githubusercontent.com/assets/7934273/13551978/59f05b54-e390-11e5-883b-3267fd2c7d0d.png)

There is a working version here, which is the same as above.
http://www.manythings.org/tatoeba/personal.php
(This grabs parts of pages on tatoeba.org, so it may take a while for it to load.)

**Comment by billoliver** [comment]
As I said before I've been working on a home page for logged-in members. Here is what have done so far:
![wip](https://cloud.githubusercontent.com/assets/17387379/13552024/0eba253c-e32e-11e5-83b5-64973611f064.png)

**Comment by ckjpn** [comment]
Trang, if you wanted to make the menu bar a little less crowded, you could use a member's avatar instead of text in the menubar.

Here's an example.   I assume you'd rather put it on the right, but it was easier for me to add it in this location, which is the only reason it's there.

![idea-for-profile](https://cloud.githubusercontent.com/assets/7934273/13552467/4b10d5f6-e3a8-11e5-8348-ea8c67824afe.png)

**Comment by ckjpn** [comment]
On the bottom of the page. I'd suggest the following change.

FROM:
If you love this content, please consider a donation.
TO:
If you love this content, please consider making a donation.

**Comment by billoliver** [comment]
Sneak peek. I'm going to explain everything when I finish the wireframe. And don't worry will add the other sections later.
![homepage-for-nonlogged-in-users](https://cloud.githubusercontent.com/assets/17387379/13798871/012a8fec-eaf9-11e5-8c8e-4ad623920a09.png)

**Comment by RyckRichards** [comment]
Perhaps ...

► " Before adding new sentences, **please / you** should remember" 

►Tell why we want those kind of sentences. Maybe "As far as Tatoeba is a website which students, teachers and many other people use it to study or work, we do need natural sentences./ useful, good and trustful sentences."

► Maybe add a section "you can also translate existing sentences by following this link" (and add a link which would redirect members to the Advanced Search page that would be listed the languages that the user speaks (except his/her native sentence)

► Add a "If you have any question, you can write on the Wall, email us or PM (some users that are willing to help new members).

Awesome job, @billoliver !

**Comment by trang** [comment]
​@billoliver, before you continue in this direction, I personally don't think the homepage should be about adding sentences. To me the homepage should be more like a dashboard that summarizes useful and interesting information for members.

What you designed there can be useful, but I don't think it fits on the homepage.

**Comment by billoliver** [comment]
@trang Got it! I'll get back to this issue when I finish the style guide.

**Comment by trang** [comment]
Issue is to vague to do something out of it. Problems are not clearly defined. Closing.

@ckjpn I know you have been suggesting many things about the homepage but they are mostly based on your personal preferences. Instead I would suggest that you try to conduct some UX tests, [like gillux did](https://tatoeba.org/eng/wall/show_message/34072#message_34072), and send it to us. From there we will have more concrete information to work with in order to really improve the homepage.
