### ISSUE TITLE
Improve language recognition of short sentences

### ISSUE THREAD

**Issue by sacredceltic** [Tatoeba/tatoeba2#1049]
Short sentences languages are often mis-identified. The identification system, through its statistical scheme based on the ever-increasing number of sentences, was meant to improve over time, but it seems that it doesn't.

a recent example : "Vas-y ! Saute !" has been identified as German. This is ridiculous, because "y" doesn't exist as a word in German. I suppose, based on this example and others, that symbols such as "-" are deleted from the analysed sequence. It's a mistake, according to me.

**Comment by trang** [comment]
Has been solved with #1731.
