### ISSUE TITLE
Sentences with slashes appear empty in search results

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1050]
[Original post](https://tatoeba.org/jpn/wall/show_message/25753#message_25753).

> I reported the bug below as a comment for sentence #4202165 but it might have been missed by the developers. Here it is again:

> This Turkish sentence #4202165 is obviously not empty. But if you search: https://tatoeba.org/eng/sentenc...tur&to=eng it shows an empty string for this sentence in the results. Similarly the Portuguese sentence #4795676 is not empty. But if you search:https://tatoeba.org/eng/sentenc...por&to=eng it shows an empty string for the said Portuguese sentence in the results.
 My guess is that there's a bug in the code which doesn't like the presence of the slash ("/") in the sentence.

**Comment by ckjpn** [comment]
This should be reopened, perhaps.

https://dev.tatoeba.org/eng/sentences/search?query=24%2F7

![screen shot 2016-03-12 at 01 22 15](https://cloud.githubusercontent.com/assets/7934273/13708262/f1c91a4c-e7f0-11e5-9844-f8d8231cb2d4.png)

It does however, work on the dev site, if the item is quoted, even though it doesn't always give an exact match.

https://dev.tatoeba.org/eng/sentences/search?query="24%2F7"&

![screen shot 2016-03-12 at 01 24 56](https://cloud.githubusercontent.com/assets/7934273/13708320/4b901fda-e7f1-11e5-854f-85c8c1ebfd3f.png)

**Comment by jiru** [comment]
I suspect this is because the slash, when not surrounded by spaces, is interpreted as part of the [NEAR operator](http://sphinxsearch.com/docs/current.html#extended-syntax).

**Comment by ventice** [comment]
When / without quotes is searched, the following error occurs:

> Notice (1024): Search query failed: index abk_delta_index,..., ,zza_main_index: syntax error, unexpected '/' near '/7' [APP\models\behaviors\sphinx.php, line 123]

So, definitely this bug is related to translation of search query to sphinx query.
Taking it.

**Comment by RyckRichards** [comment]
Working pretty well :D Thanks **a lot** for that!

**Comment by ventice** [comment]
You are welcome (:
