### ISSUE TITLE
The tag "proverb" has 2 different ID numbers.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1051]
https://tatoeba.org/eng/tags/show_sentences_with_tag/407
https://tatoeba.org/eng/tags/show_sentences_with_tag/2151

I got fewer results than I expected when using the advanced search for the tag "proverb".
https://tatoeba.org/eng/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=&tags=proverb&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

![screen shot 2016-03-09 at 06 18 21](https://cloud.githubusercontent.com/assets/7934273/13616957/a179fed6-e5bf-11e5-8338-58f9336af1bf.png)

**Comment by jiru** [comment]
Interestingly, there are actually 13 duplicated tags like this one:
```
mysql> select count(name) as count, name from tags group by name having count > 1;
+-------+------------------------------+
| count | name                         |
+-------+------------------------------+
|     2 | advertisement                |
|     2 | by Henry David Thoreau       |
|     2 | by Karl Marx                 |
|     2 | by Ralph Waldo Emerson       |
|     2 | by Samuel Johnson            |
|     2 | by Winston Churchill         |
|     2 | comment on sentence          |
|     2 | dated                        |
|     2 | français du Canada           |
|     2 | from La civilité française   |
|     2 | masculine                    |
|     2 | proverb                      |
|     2 | translated quote             |
+-------+------------------------------+
```

I have no idea how they got it. A quick and efficient way to prevent the creation of these is to add an SQL duplicate constraint on the name. That said, the most recent duplicate within these was created on 2013-10-11, so it may be an old bug that eventually got fixed. We may consider this issue as a duplicate #961.

**Comment by ckjpn** [comment]
Perhaps someone with direct access to the database can merge items from the higher-numbered lists into the lower-numbered lists of tags and then delete the higher-numbered list.

That would take care of the problem for now.  We could just wait to see if this happens again, before spending time trying to debug something that may not still be a bug.

**Comment by sacredceltic** [comment]
it probably happened as the result of tags reviews that took place a couple of time. It must have been renamed from something else.

**Comment by alanfgh** [comment]
> Perhaps someone with direct access to the database can merge items from the higher-numbered lists into the lower-numbered lists of tags and then delete the higher-numbered list.

I did this, so I consider this particular issue closed. However, I wrote issue #1064 to address the possibility of adding duplicate constraints and/or merging the `name` and `internal_name` fields within the `tags` table.
