### ISSUE TITLE
Change pt flag

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1054]
Suggested by [alexmarcelo](https://tatoeba.org/eng/user/profile/alexmarcelo) on the [Wall](https://tatoeba.org/eng/wall/show_message/25717#message_25717).

![pt-br2](https://cloud.githubusercontent.com/assets/7658430/13656660/7fa3ff2c-e647-11e5-9fdc-9c0f61007451.png)

**Comment by RyckRichards** [comment]
I'm going to ask about that on the Wall and by private message before implementing (or not implementing).

**Comment by sacredceltic** [comment]
keep in mind that, some day, somebody will ask about Angola, Mozambique, Timor...

**Comment by RyckRichards** [comment]
Yes...

**Comment by RyckRichards** [comment]
I waited for 2 days before changing it and also I both left private messages to users who contribute by posting sentences in Portuguese or that translate sentences from this language and I also posted on the [Wall](https://tatoeba.org/eng/wall/show_message/25785#message_25785).
