### ISSUE TITLE
Change both flag and name for Hmong Njua

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1059]
According to cueyayotl, the actual flag doesn't represent this language. Also, he asked me to change its name from "Hmong Njua" to "Hmong Njua (Green)"

**Comment by RyckRichards** [comment]
#935

**Comment by trang** [comment]
Please add an explanation about the following:
- Why did the name have to be changed to "Hmong Njua (Green)"? 
- Why was the previous icon not suitable?
- Why does the new icon represent better the language?
Thanks.

**Comment by RyckRichards** [comment]
According to cueyayotl

==> Hmong Njua is also known as Green Hmong while Hmong Daw is also known as White Hmong. There would be some people that wouldn't recognize Hmong Njua, but would recognize Hmong Njua (Green) or Green Hmong. As far that we have both "Hmongs" now, I chose to add "(Green)". 
"we should change "Hmong Njua" to "Hmong Njua (Green)" as it is very often refered to as "Green Hmong"."

> Why was the previous icon not suitable?
According to him, the previous icon doesn't represent that language and many of his friends/acquitances/co-workers were complaining about it

> Why does the new icon represent better the language?
As far as this language is spoken in Laos, he has chosen the flag of Laos ( "SIL lists MWW as a language of China, though I would rather use the Lao flag as well..." )

https://en.wikipedia.org/wiki/Hmong_language#Varieties_in_Laos

Native to 	China, Vietnam, Laos, Thailand, USA, and French Guiana.

Waiting for a more detailed explanation from cueyayotl .

**Comment by RyckRichards** [comment]
By cueyayotl:

>> Why did the name have to be changed to "Hmong Njua (Green)"?

It's not an absolute necessity, but this language is almost ALWAYS called Green Hmong. A native speaker will recognize Hmong Njua as their "Hmoob Ntsuab", but people less familiar with the language, including tourists who want to learn as much of the language they can before their travel to Laos, may not understand what is Hmong Njua, as even the guidebooks refer to this language as Green Hmong.

>> Why was the previous icon not suitable?

I chose it because it was the only "flag" I could find that could represent Hmong, but I realize now how unknown the image is to Hmong speakers. I asked on online Hmong Communities and virtually all responses were negative to that flag.

>> Why does the new icon represent better the language?

I'm not sure that it really does. That's just what we have done with languages without a flag representing it; we use a national flag (which the Ethnologue claims is the country of the language) with the three-letter ISO 639-3 code on the side.

If we really are OK using non-flags, the Hmong Community would strongly prefer using "Elephant foot embroidery" or "Paj Ntaub" to represent their language. I could design a language icon using one of the two designs above with the ISO 639-3 code on the side. Depends on which one TRANG prefers.

**Comment by trang** [comment]
> If we really are OK using non-flags

Yes, we really are OK.

> Depends on which one TRANG prefers.

I don't contribute in Green Hmong, it doesn't matter what I prefer.
