### ISSUE TITLE
Display the number of contributions per week on the homepage.

### ISSUE THREAD

**Issue by ghost** [Tatoeba/tatoeba2#1066]
**Problem:**
Let's say you're visiting Tatoeba for the first time when there isn't many users online. You will see a small number of contributions on the homepage and think that the community isn't very active (which isn't true).

**Solution:**
Display the the number of contributions per week on the homepage.

**Comment by agrodet** [comment]
@trang With the recent discussion on #2085 and your comment there https://github.com/Tatoeba/tatoeba2/issues/2085#issuecomment-583554352 , is there any reason to keep this issue out-of-scope instead of closing it?

**Comment by trang** [comment]
Nope, we can close.
