### ISSUE TITLE
"Activity Timeline" doesn't make sense under "Contribute"

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1068]
- I'd suggest moving "Activity Timeline" to the "Community" menu, or to the bottom of the page.

The "timeline" is not really a "contribute" item, I think.  It maybe is more appropriate in the "Community" menu, since it shows what the community is doing.  Or, if you think many members don't often access it, maybe it should go on the bottom of the page in the "About" column.
- Perhaps the "quick start guide", "FAQ", "guidelines", etc. could also be put at the bottom of the "Contribute" menu.  These are related somewhat, and maybe should be more easily accessible.

**Comment by ckjpn** [comment]
A better option, would likely be just one "Help" item in the "Contribute" menu, and then redo the existing "help" page (https://tatoeba.org/eng/help) to make it more concise and easy to understand.

Maybe the "help" page could include just a few quick links like the following, and maybe a few others.

 ▪ Quick Start Guide:
 http://en.wiki.tatoeba.org/articles/show/quick-start
 
 ▪ What You Can Do and How to Do It:
 http://en.wiki.tatoeba.org/articles/show/what-you-can-do-and-how-to-do-it

 ▪ Rules and Guidelines:
 http://en.wiki.tatoeba.org/articles/show/guidelines

 ▪ FAQ:
 http://en.wiki.tatoeba.org/articles/show/faq

**Comment by billoliver** [comment]
> I'd suggest moving "Activity Timeline" to the "Community" menu, or to the bottom of the page.

@ckjpn We should move it to the "Community" menu. I think we might have changed that by mistake.

> The "timeline" is not really a "contribute" item, I think. It maybe is more appropriate in the "Community" menu, since it shows what the community is doing. Or, if you think many members don't often access it, maybe it should go on the bottom of the page in the "About" column.

+1

**Comment by trang** [comment]
I changed the title of this issue to limit it only to the "Activity timeline".

For the **Quick Start** and other documentation, it would be better to mention them upon registration (#2112). @jiru gave a good argument for why it's not really useful to have it in the top menu (cf. https://github.com/Tatoeba/tatoeba2/issues/2144#issuecomment-587381228):

> I don’t think the quick start guide should go inside the menu because it’s mostly useless to people who know it. The purpose of the menu is to give access to the most important/used pages. However, while the quick start guide is an important page to look at when you’re discovering the website, after you got it, there is no need to check it again.

So we're not going to deal with the quick start here.

-----

For the **Activity timeline**, it was suggested in #2144 to move the link to the "Stats" block on the homepage and I agree it would be the best solution. Except we have to rework this "Stats" block a bit.

I had a similar thought as what @jiru wrote in https://github.com/Tatoeba/tatoeba2/issues/2144#issuecomment-587381228 and I think @agrodet's screenshot is on the right track (cf. https://github.com/Tatoeba/tatoeba2/issues/2144#issuecomment-588074169).

My only issue is that it feels a bit strange to have two stats (number of sentences + number of languages) associated to one page. It would feel less broken to have each stat followed by a link to some related page.

For the `{x} sentences`, I have two ideas of related page:
- the [random sentence](https://tatoeba.org/eng/sentences/show/random)
- or the [advanced search](https://tatoeba.org/eng/sentences/advanced_search)

Not sure which one is best...

```
{n} sentences
Random sentence >
```
or
```
{n} sentences
Search sentences >
```

**Comment by trang** [comment]
I'll close this issue actually otherwise we have separate threads for a same topiac and it can get confusing. We can consider the rework of the Stats block as part of #2144.
