### ISSUE TITLE
Duplicate tags are displayed at first and then disappear

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1070]
Step to reproduce the problem on dev.tatoeba.org:
1. Go to the page of a sentence that has tags. For instance: http://dev.tatoeba.org/eng/sentences/show/171808
2. We want to add again an existing tag. In our example, we can try to add again the tag "weather".
3. After we submit, the tag appears twice in the list of tags.
4. But if we reload the page, the duplicate tag has disappeared. There's only one tag "weather" listed.

This can be confusing for users: they just added a tag and it appears as added, but if they come back later to the page, it will have disappeared.

The reason why it disappears is because there's no need to display several times the same tag on a sentence. If there are several identical tags added on a sentence, only one tag will be displayed: the oldest one.

**Comment by AndiPersti** [comment]
I can't add tags on dev but on my local copy I can't reproduce this problem any more. Adding the same tag again works as expected (i.e. the addition is ignored).

**Comment by trang** [comment]
Indeed, it's been fixed during the migration to CakePHP 3. Thanks :)
