### ISSUE TITLE
Move scripts to the bottom of the page.

### ISSUE THREAD

**Issue by ghost** [Tatoeba/tatoeba2#1071]
This way the page will load faster and render before loading and executing JavaScript.
![scripts](https://cloud.githubusercontent.com/assets/17387379/13899581/b2a959c2-edd0-11e5-8349-633325648ae8.jpg)

**Source**: [PageSpeed Insights](https://goo.gl/X3yfTk)

**Comment by trang** [comment]
Done in #1184.
