### ISSUE TITLE
Misalignment of "Help", "Advanced Search" with "From" and "To"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1072]
As this screenshot shows, the "Help" and "Advanced Search" captions are slightly misaligned with the "From" and "To" captions. I understand that they're conceptually different, but I still think it would look better if they were aligned. It would also be nice to move the search button below the fields so that it's not right up against them. Naturally, when the display is wide enough to show the search button to the right, this is not a problem.

This screenshot is from Firefox, but it looks the same on Chrome. I'm using a Windows 7 machine.

![misalignment](https://cloud.githubusercontent.com/assets/1213027/13900202/c2754234-edd6-11e5-931e-0444d8fceba2.png)

**Comment by billoliver** [comment]
These changes is going to solve the issue:

Someone just need to add this div in the HTML:
![print](https://cloud.githubusercontent.com/assets/17387379/13974212/8ede0640-f088-11e5-91aa-6548e0fd3865.png)



Changes in the CSS:
```
html, body {
 box-sizing: border-box;
}

#top_menu_container {
    background-color: #414141;
    margin: 0 auto;
}

#top_menu {
    background: #414141;
    width: 960px;
    margin: 0 auto;
    overflow: hidden;
    padding: 10px;
}

#search_container {
    background-color: #6A0;
    margin: 0 auto;
}

.search_bar {
    color: #FFF;
    background-color: #6A0;
    position: relative;
    width: 960px;
    padding: 0 10px;
    margin: 0 auto;
}
```
