### ISSUE TITLE
Using "limit to" and "exclude" simultaneously in search options

### ISSUE THREAD

**Issue by aleksandraeska** [Tatoeba/tatoeba2#1074]
When I'm learning another language what I do is search for English -> X language sentences, translate them on paper and then check the translation with the one on Tatoeba. But I could use this to provide my contributions as well. Since I already focus on a given sentence, if would take me 5 seconds to add a translation in my native language. Thus, if I could use limit to and exclude together, I could see all the sentences that are translated from English to X, but not translated to my native language. 
The only way I can do it now is by displaying all the translations available and checking if the Polish one is already there, but it's very distractive and takes a lot of time.

**Comment by trang** [comment]
Based on the [discussion on the Wall](https://tatoeba.org/eng/wall/show_message/26023#message_26023), I believe this issue is no longer needed. I'm closing it.
