### ISSUE TITLE
Searching for lists has quit working.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1081]
https://tatoeba.org/eng/sentences_lists/of_user?username=CK&search=audio

If you try to search in "my lists", it now gets a "There's no user called" error.

**Comment by ventice** [comment]
I take this

**Comment by ventice** [comment]
Looks like the search URL is formed incorrectly. Instead of:
/eng/sentences_lists/of_user**?username={username}&search={list-name}**
it should be
/eng/sentences_lists/of_user**/{username}/{list-name>}**

**Comment by ckjpn** [comment]
Yeah,  that one works.

https://tatoeba.org/eng/sentences_lists/of_user/CK/audio

**Comment by ventice** [comment]
Fixed by pull request #[1098](https://github.com/Tatoeba/tatoeba2/pull/1098)
