### ISSUE TITLE
make Latin sentence search macron- and breve-insensitive

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1088]
alexmarcelo, on the Wall ( https://tatoeba.org/eng/wall/show_message/26122#message_26122 ):

> Is there a way to make Tatoeba treat breve-marked vowels (ă, ĕ, ĭ, ŏ, ŭ) as unmarked vowels for indexation purposes? I'd like to use them to indicate accent. The problem is that "edere" and "edĕre" are treated as different words, and one wouldn't be able to find "edĕre" by typing "edere" in the search field.

I told him that this was certainly possible, since I had made a similar change for Hebrew, but asked him to make sure that other Latin contributors/searchers would want that. His reply:

> I'll try to contact some users who used to write in Latin. Currently, CarpeLanam and I are the only ones translating into Latin. It would be great if we could standardize all Latin sentences, but this is nearly impossible. Out of the 15950 sentences we have in this language, 11745 are owned by me. Even if some users decide not to use diacritics, I think it's worth programming Tatoeba to take both breves and macrons ((ă, ĕ, ĭ, ŏ, ŭ, y̆); (ā, ē, ī, ō, ū, ȳ)), cause some people do use them by default.

As I wrote on the Wall, it's possible to make such a change globally or just for specific languages. I'm wondering whether there are any languages for which we wouldn't want breves and macrons to be ignored during searches.

**Comment by alanfgh** [comment]
This is what I found:

(1) There is only 1 existing sentence that contains "combining macron" (U+0304), and it's not Latin.
(2) There are only 5 existing sentences that contain "combining breve" (U+0306), none of them Latin.
(3) There are some existing sentences (in Latin and other languages) that used precomposed characters with macron and breve.
(4) Combining macron and combining breve are in the "combining diacritical mark" range that we accept, and do not ignore, for all languages.
(5) Here are the relevant Unicode values for the composed characters with macron and breve:
'LATIN CAPITAL LETTER A WITH BREVE' (U+0102)
'LATIN SMALL LETTER A WITH BREVE' (U+0103)
'LATIN CAPITAL LETTER E WITH BREVE' (U+0114)
'LATIN SMALL LETTER E WITH BREVE' (U+0115)
'LATIN CAPITAL LETTER I WITH BREVE'  (U+012C)
'LATIN SMALL LETTER I WITH BREVE' (U+012D)
'LATIN CAPITAL LETTER O WITH BREVE' (U+014E)
'LATIN SMALL LETTER O WITH BREVE' (U+014F)
'LATIN CAPITAL LETTER U WITH BREVE' (U+016C)
'LATIN SMALL LETTER U WITH BREVE' (U+016D)
'LATIN CAPITAL LETTER A WITH MACRON' (U+0100)
'LATIN SMALL LETTER A WITH MACRON' (U+0101)
'LATIN CAPITAL LETTER E WITH MACRON' (U+0112)
'LATIN SMALL LETTER E WITH MACRON' (U+0113)
'LATIN CAPITAL LETTER I WITH MACRON' (U+012A)
'LATIN SMALL LETTER I WITH MACRON' (U+012B)
'LATIN CAPITAL LETTER O WITH MACRON' (U+014C)
'LATIN SMALL LETTER O WITH MACRON' (U+014D)
'LATIN CAPITAL LETTER U WITH MACRON' (U+016A)
'LATIN SMALL LETTER U WITH MACRON' (U+016B)
'LATIN CAPITAL LETTER AE WITH MACRON' (U+01E2)
'LATIN SMALL LETTER AE WITH MACRON' (U+01E3)

**Comment by alanfgh** [comment]
The file app/vendors/shells/sphinx_conf.php contains this code, which affects Russian only:

        /* Russian uses diacritics only to stress words and it's easier
         * to search if they are ignored. Since all the Russian diacritics
         * are not single characters but combining characters (e.g. и + ´ = и́)
         * we simply ignore the *´* combining char (U+301) so that characters
         * are considered not having a diacritic. */
        $this->indexExtraOptions['rus'] =
            "
        charset_table = ".implode(', ', array_merge(
            array('U+300', 'U+302..U+36F'),
            array_filter(
                $this->charsetTable,
                function($v) { return $v != 'U+300..U+36F'; }
            )
        ))."
        ignore_chars = U+AD, U+301\n";

I think we want to do something similar. We probably want to map capital and small "a", both with and without breve and/or macron, to the same character (probably small "a" without breve or macron), and the same for all other such letters.

**Comment by alanfgh** [comment]
One thing worth noting is that, as far as I can tell, once you fold characters together, you cannot search for them separately in Sphinx. For instance, in English, "=Polish" finds both "Polish" and "polish", and in Hebrew, where we expressly ignore vowels, there is no way to find words containing vowels from the identical words without vowels. If you need to find one version specifically, or if, for instance, you want to find all sentences containing a specific Hebrew vowel, you need to do a SQL query on the server.

**Comment by alexmarcelo** [comment]
Thanks for collecting this information, Alan. After having contacted every user owning 25 sentences or more in Latin, and having heard their thoughts on the use of macrons and breves, there is something worth proposing. First, I quote some of them (after having asked for permission):

My message was as follows:

> This message is being sent to every user who have contributed 25 sentences or more in Latin. I'd be very glad if you could read it and share your opinion with us.
> 
> Since you're one of the few people who own several sentences in Latin, we'd like to know if you have any objections to the use of macrons and breves by some users (including me) when writing in Latin. My suggestion is not exactly indicating quantity, but accent (which is obviously related to quantity, but looks way clearer).

===

CarpeLanam, by private message:

> My only real concern is that I wouldn't feel comfortable contributing if I had to use the diacritical marks myself, as I know I would make many mistakes. [...] And in my teaching life, I try not to overemphasize macrons because it can discourage my young students. If I'm reading your correspondence in the github thread correctly, this will only add more flexibility to the database and leave the question of standardization for a later time. 

===

Impersonator, idem:

> ego plērumque litterīs longīs omnibus apicēs appōnō, nam hunc modum scrībendī ūtilissimum esse putō. eōs, quī litterās longās nōn appellant, apicēs nōn impediunt; sed eīs, quī litterās longās vetere cōnsuētūdine legere volunt, notās hās percommodās esse crēdō.

I translate:
I always put "apices" (macrons) on long letters, because I think this way of writing is very useful. "Apices" (macrons) don't disturb those who do not mark their vowels, but to those who want to read long letters the old way, I think these marks are very convenient.

===

Hans07, idem:

> non repugno.

===

bandeirante, idem:

> I have absolutely no objection to macrons and breves, In fact, when I started Latin, we used them routinely, although after the first year they were omitted. But I do not mind at all.

===

pullnosemans, idem:

> as with so many things on this site, as long as it stays as open as it is right now, you will have different people doing different things. therefore, I would suggest programming tatoeba to correctly associate as many different spelling styles as possible. if that is possible, I see no reason why using diacritics should be objected to.

===
sicerabibax, idem:

> Ma petite expérience d'éditeur du site Forvo et ma pratique personnelle du latin m'amènent à faire les remarques suivantes :
> - L'écriture normale du latin a toujours été faite sans macra ni brèves ni accents.
> - Dans ce cadre, l'usage occasionnel des signes diacritiques sert à lever des doutes.
> - Un équivalent de notre macron, l'apex a été utilisé dans des inscriptions impériales (mais pas de manière rigoureusement systématique), comme le macron est utilisé dans le dictionnaire d'Oxford ou dans les livres de H. Ørberg. Cette pratique, assez partielle, a été abandonnée à cause de l'évolution phonétique du latin. Elle reste néanmoins très utile aujourd'hui (à condition d'être rigoureuse) à titre pédagogique.
> (Graphiquement, je ne suis pas partisan de l'apex, malgrés son authenticité, car sa forme interfère avec l'accent aigu, et je préfère donc le macron).
> - Je suis inquiet de la façon dont vous compter représenter l'accent à l'aide des macra et des brèves : voulez-vous inventer un nouveau procédé ou utiliser seulement le « calcul » classique de l'accent à partir des quantités ?
> - Je ne pense pas utile d'imposer sur Tatoeba une norme d'utilisation systématique des macra et des brèves (et quelle norme choisir : les macra seuls comme Oxford et Ørberg [ce qui suffit], ou les macra ET les brèves? ).
> Je pense qu'il faut laisser la liberté d'écrire le latin de manière graphiquement légère, comme cela s'est presque toujours fait, et de mettre les signes diacritiques en cas de nécessité seulement.
> L'usage systématique des accents ne se justifie pratiquement que dans le Missel, et celui des macra (et accessoirement des brèves) est indiqué dans les ouvrages pédagogiques et devrait y être obligatoire ; mais pas sur Tatoeba.

===

My reply to all of them was as follows:

> Considering the feedback I've received from Latin-writing users, I think our best solution would be to implement a system where users, like in Japanese, would be able to add transcriptions just like they can add sentences. Since accent is ruled by quantity, this would fulfill my original needs. I don't like the idea of marking every sentence because most of them are in New or Modern Latin, where quantity doesn't play as much of a role in Latin pronunciation as it once did.

So, the question is: how difficult would it be to create a transcription system for Latin, where people would be able to mark vowels without having to edit the sentence itself? Is Tatoeba ready for this? Are we ready to take this step forward, and make Tatoeba more useful to those who are interested in Latin?

If the answer is yes, we'll have to come up with a standardization on transcribing sentences: should we use only macrons, or both macrons and breves? Should we mark vowels that are long by nature? How about vowels that can be both short and long (i.e. "common")?

Independently of creating such a transcription system or not, I think making Tatoeba macron and breve-insensitive for Latin is a necessity. See Wezel's recent Latin contributions, for example. Some words in his sentences can't be searched, because they contain macrons (https://tatoeba.org/eng/sentences/of_user/Wezel/lat).

**Comment by lipao** [comment]
Hello everybody and sorry I join this discussion so late. I just want to say that I'd love something like a transcription system, where the sentence would be normally displayed with no diacritics (as in normal Latin text in most redactions), but you could get to see the macrons if you wanted to. I actually made a suggestion about this some time ago, however it didn't get much attention:
https://tatoeba.org/eng/wall/show_message/23219#message_23219
Valēte.

**Comment by trang** [comment]
> So, the question is: how difficult would it be to create a transcription system for Latin, where people would be able to mark vowels without having to edit the sentence itself? Is Tatoeba ready for this?

On the technical side, it shouldn't be too difficult. Or at least, I can say there's already the infrastructure for it, thanks to the work that gillux did on transcriptions (cf. #77).

Are there any rules (or even some existing scripts?) that we can can use to automatically generate macrons and breves? Even if it's not 100% accurate it's fine. The way gillux implemented the transcriptions allows users to know when a transcription is automatically generated, and to edit the transcriptions that are not correct.

I won't personally have time to work on this issue, but if you can:

1. Confirm that the community has agreed on a standard.
2. Describe as precisely as possible the transcription rules.

then I can mark this issue as "accepted". and maybe another developer who is interested in Latin will be happy to work on this.

**Comment by jiru** [comment]
This issue is about making the Latin search macron- and breve- insensitive, not providing alternative script for Latin. Alternative scripts, if made indexed by the search engine (which is yet to be implemented), can also solve the problem of having to look up for every script variants of a word, but I don’t think it’s necessary for Latin, because the variations are trivial enough to be handled by the indexer, as alanfgh pointed out. I’m not saying that we don’t want alternative scripts; only that they are not relevant to solve this issue. If you’d like to have automated alternative scripts, you’d better open a new issue.

After reading lipao’s Wall message, I can see that macron and breves are not the only thing that differs between the different scripts of Latin. V is substituted with U. which is easy to handle. I gets replaced by J, but only at the beginning of a word. This, too, can be handled by Sphinx using [regexp filters](http://sphinxsearch.com/docs/current.html#conf-regexp-filter).

**Comment by alanfgh** [comment]
I'll look at regexp filters. Thanks for the tip, @jiru.

**Comment by alanfgh** [comment]
I've taken care of making the search macron- and breve-insensitive. It also maps J to I, and U and W to V. (I realize that W was not used in classical Latin, but I added it for good measure.) I'll send the file (which also addresses #1296) to Trang by e-mail.

**Comment by alanfgh** [comment]
In addition to making the Latin index insensitive to macrons and breves, I also made it insensitive to acute accents, which actually look more like the original apex accents than macrons do.

You can add these "sentences" to a corpus in order to test the behavior:

Group 1:
macron-cap-a ĀĀĀĀ
macron-small-a āāāā
breve-cap-a ĂĂĂĂ
breve-small-a ăăăă
acute-cap-a ÁÁÁÁ
acute-small-a áááá
cap-a AAAA
small-a aaaa

Searching for any of these (e.g., "ĂĂĂĂ", "aaaa") should find all of them.

Group 2

macron-cap-e ĒĒĒĒ
macron-small-e ēēēē
breve-cap-e ĔĔĔĔ
breve-small-e ĕĕĕĕ
acute-cap-e ÉÉÉÉ
acute-small-e éééé
cap-e EEEE
small-e eeee

Searching for any of these (e.g., "éééé", "EEEE") should find all of them.

Group 3

macron-cap-i ĪĪĪĪ
macron-small-i īīīī
breve-cap-i ĬĬĬĬ
breve-small-i ĭĭĭĭ
acute-cap-i ÍÍÍÍ
acute-small-i íííí
cap-i IIII
small-i iiii
cap-j JJJJ
small-j jjjj

Searching for any of these (e.g., "ĬĬĬĬ", "íííí") should find all of them.

Group 4

macron-cap-o ŌŌŌŌ
macron-small-o ōōōō
breve-cap-o ŎŎŎŎ
breve-small-o ŏŏŏŏ
acute-cap-o ÓÓÓÓ
acute-small-o óóóó
cap-o OOOO
small-o oooo

Searching for any of these (e.g., "OOOO", "ŏŏŏŏ") should find all of them.

Group 5

macron-cap-u ŪŪŪŪ
macron-small-u ūūūū
breve-cap-u ŬŬŬŬ
breve-small-u ŭŭŭŭ
acute-cap-u ÚÚÚÚ
acute-small-u úúúú
cap-u UUUU
small-u uuuu
cap-v VVVV
small-v vvvv
cap-w WWWW
small-w wwww

Searching for any of these (e.g., "ūūūū", "ÚÚÚÚ") should find all of them.

Group 6

macron-cap-ae ǢǢǢǢ
macron-small-ae ǣǣǣǣ
cap-ae ÆÆÆÆ
small-ae ææææ

Searching for any of these (e.g., "ææææ", "ǢǢǢǢ") should find all of them.
