### ISSUE TITLE
(IMPORTANT) Some issues

### ISSUE THREAD

**Issue by boracasli9** [Tatoeba/tatoeba2#1094]
**--Please do not delete this issue.--**

First of all, I'm sorry for being hostile to you all before and I'd be happy if you forgave me. I'll just add and translate sentences and not do bad stuff. I'd be glad if you allowed me to add sentences in Turkish, Greek, English, Georgian, Swedish and Irish. These languages are my strongest languages. I never use machine translation when translating full sentences. (I only use machine translation to look up words, but not sentences)

Direct people to the normal site, not the dev site. I don't want to have my first account back, that means that I don't want you to reactivate my first account. I would just like to continue my contributions on a new account which I'll create later. I won't create it before this issue gets answered (or after it gets answered, if the answer will be negative)

And banning people from a site for many years is not fine at all. One may have acted badly, but that doesn't mean you should ban them for lots of years. I would understand if the ban lasted for maximum two or three years for the biggest fault, but not four or six. Because of that, I become mad almost every day. Of course you have to punish people who don't agree to the Terms of Service, but not in an extremely harsh way.

Thank you for your understanding.

--- Edit ---
My previous issue was closed. I'm trying to open another issue for the same thing. I just would like to know why you don't want to have me again on Tatoeba.org. I would no longer like to do my work on the dev site. I don't want to have my first account reactivated and please don't be so hostile to me and other people. I just would like to have an answer for this and I feel so sorry for what I had done in the past. I'm no longer the me of 2010. I hope you will understand what I've said just now. Thank you.

**Comment by trang** [comment]
@boracasli9, for such issues, write to community-admins@tatoeba.org.
This kind of issues is not accepted in our GitHub and will be closed systematically.
https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-issues
