### ISSUE TITLE
Flag is the wrong size = https://tatoeba.org/img/flags/max.png

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1096]
https://tatoeba.org/img/flags/max.png

30x23 instead of 30x20 like the other flags.

Here it is resized. You could just download this and upload it.

![max](https://cloud.githubusercontent.com/assets/7934273/14587958/d54cb67a-04f7-11e6-9283-ae7423dc9f82.png)

**Comment by ventice** [comment]
I'm taking this
