### ISSUE TITLE
Blue Announcement Thing Reappears

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1097]
## The Problem

Just in case you didn't know, even though that blue announcement was dismissed by me a while back, it reappeared again today.

It's only a minor irritation, but if this happens multiple times for all members, people might get a little irritated by it.

## Possible Solution

Set the cookies, or however you control this, to a longer expiration time.

Also, note that it should be "interested in contributing to".

![screen shot 2016-04-18 at 09 33 22](https://cloud.githubusercontent.com/assets/7934273/14591265/2940303a-0549-11e6-9ba4-e6da1bf8f217.png)

**Comment by ventice** [comment]
According to JavaScript the cookie is set for 7 days:
`
    $('.announcement .close').click(function() {
        $('.announcement').hide();
        $.cookie(announcementId, 'done', {'expires' : 7, 'path' : '/'});
    });
`
What is the expected behavior? Should the cookie be set forever?

**Comment by trang** [comment]
I don't consider this to be an actual problem. If an information needs to remain displayed for several weeks, I think it's fine that it reappears every week, as some sort of reminder.

Obviously it depends on the nature of the announcement. If an announcement is really not so important, then we could set the cookie to never expire. For some announcements, maybe 1 month is more appropriate. But I think 7 days is an okay value regarding the current announcement.

I'm closing this.
