### ISSUE TITLE
Links such as https://en.wikipedia.org/wiki/Classical_period_(music) aren't clickable (in comments, at least)

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1103]
https://tatoeba.org/eng/sentences/show/5075211#comment-830601

My assumption is that the parentheses are causing the problem.
![screen shot 2016-04-21 at 07 00 00](https://cloud.githubusercontent.com/assets/7934273/14691951/04a07efe-078f-11e6-896e-ae0929296371.png)

**Comment by ventice** [comment]
I'm taking this.
