### ISSUE TITLE
Display a drop down icon next to the flag.

### ISSUE THREAD

**Issue by ghost** [Tatoeba/tatoeba2#1104]
I noticed that some users don't know how to change the flag/language of their sentences. And I think this would solve the problem:

![change-language](https://cloud.githubusercontent.com/assets/17387379/14720896/09d30496-07da-11e6-86fa-85e577f3edbb.png)

**Comment by billoliver** [comment]
This has been happening **a lot** recently. I wonder when the solution will be implemented.

**Comment by trang** [comment]
I'm thinking that it might be more intuitive if clicking on the "edit" icon would make not only the text editable, but also the language.

Did you get to ask the users who didn't know how to change the language of their sentences, what they tried to do?

**Comment by billoliver** [comment]
You're right, they are clicking on the edit icon.

**Comment by billoliver** [comment]
> I'm thinking that it might be more intuitive if clicking on the "edit" icon would make not only the text editable, but also the language.

Great idea, Trang. You're totally right.

> Did you get to ask the users who didn't know how to change the language of their sentences, what they tried to do?

Yes, I did. They clicked on the edit icon.

**I've update the design**:

![select_language](https://cloud.githubusercontent.com/assets/17387379/15724880/83456994-281f-11e6-8cd8-71b8506e20f9.png)

**Comment by alexmarcelo** [comment]
I like this idea, as long as it can be turned off by users who are used to the current design. Personally, I'd find this quite boring as an admin, as I often have to use the "edit" button.

**Comment by billoliver** [comment]
It would be nice to see how the page looks for admins. Could you send me a screenshot, @alexmarcelo?

**Comment by Guybrush88** [comment]
This issue has been requested also by odexed (https://tatoeba.org/ita/user/profile/odexed) here:
https://tatoeba.org/ita/wall/show_message/29285#message_29285

**Comment by trang** [comment]
Implemented in #2077 in the new sentence design, although not exactly with the suggested design above, but the same concept of editing the language after clicking the edit button.

I'm closing this as we will not implement this in the old sentence design.
