### ISSUE TITLE
Gothic (got)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1105]
* Language name: Gothic
* Language info: https://en.wikipedia.org/wiki/Gothic_language
* ISO 639-3 code: got
* Public List: https://tatoeba.org/eng/sentences_lists/show/6016
* Icon: http://imgur.com/ljH5tzz
* Requested by: https://tatoeba.org/eng/user/profile/WahahaDrills

=========================================

[for dev.tatoeba.org]
CALL add_new_language('got', 4243);

[for tatoeba.org]
CALL add_new_language('got', 6016);

**Comment by RyckRichards** [comment]
List on devtatoeba - http://dev.tatoeba.org/eng/sentences_lists/show/4243
