### ISSUE TITLE
sentence with dollar sign looks incorrect from search results page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1119]
I did a search for the word "ransom" in English, and came up with a page with 9 results. One of the results looked strange:

![search_results](https://cloud.githubusercontent.com/assets/1213027/14872960/4b7baa58-0cbf-11e6-9c0b-3cf4c3937cb2.png)

but when I went to the sentence page, it looked normal:

![sentence](https://cloud.githubusercontent.com/assets/1213027/14872971/5e635e54-0cbf-11e6-9b67-eb8757114703.png)

**Comment by ventice** [comment]
Taking this

**Comment by trang** [comment]
@ventice, you may have to install Sphinx (http://sphinxsearch.com/) to be able to test this one, but it seems like the website is down... Also we currently don't have up-to-date instructions for running Sphinx. I have to go out soon, but we can check this together tomorrow during Tatoeba Day.

Just in case you somehow manage to download and install it, you'll have to generate a conf file. This can be done with the cake console:
```
./cake/console/cake -app app sphinx_conf > sphinx.conf
```
The code that generates this file is here: https://github.com/Tatoeba/tatoeba2/blob/dev/app/vendors/shells/sphinx_conf.php

Then you'll need to index the sentences using that conf file.
```
indexer -c sphinx.conf --rotate --all
```

**Comment by ventice** [comment]
Thanks for the instructions about config part. I have taken this issue exactly in order to get introduction to search and sphinx. I managed to download Sphinx from here http://fossies.org/windows/www/sphinx-2.2.10-release-win64.zip/

Now I am installing it and will try to get local search up and running.

**Comment by ventice** [comment]
I was able to get Sphinx running and even reproduced the bug locally. Thanks.
