### ISSUE TITLE
Unable to search in any of the new languages in the Advanced search

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1130]
Wanting to search through the Naga (Tangshang) sentences in random order I used the URL:
https://tatoeba.org/eng/sentenc...mp;sort=random

But to my surprise, it came back as a search error. The same is true replacing "nst" with the ISO 639-3 codes of all other languages recently added.

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/14972847/0753010e-10b7-11e6-87b4-6382a84e59dd.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/14972848/0c91824e-10b7-11e6-8f81-33a79322aceb.png)

**Comment by RyckRichards** [comment]
Chinese Jin - https://tatoeba.org/eng/sentences/search?query=&from=cjy&to=und&orphans=no&unapproved=no&user=&tags=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

Gothic - https://tatoeba.org/eng/sentences/search?query=&from=got&to=und&orphans=no&unapproved=no&user=&tags=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

Madurese - https://tatoeba.org/eng/sentences/search?query=&from=mad&to=und&orphans=no&unapproved=no&user=&tags=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

**Comment by RyckRichards** [comment]
Those were the languages recently added - > Malay (Vernacular) - zlm
> Naga (Tangshang) - nst
> K'iche' - quc
> Arabic (Gulf) - afb
> Minangkabau - min
> Temuan - tmw
> Chinese (Jin) - cjy
> Maithili - mai
> Madurese - mad
> Banjar -bjn

**Comment by trang** [comment]
Note that this is not related to the advanced search. It won't work in a normal search either.

This is simply because the config file for the search engine has not yet been updated on the server. I'll take care of it this weekend.

**Comment by trang** [comment]
Should be working now.
