### ISSUE TITLE
Bavarian (bar)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1137]
* Language name: Bavarian
* Language info: https://en.wikipedia.org/wiki/Bavarian_language
* ISO 639-3 code: bar
* Public List: https://tatoeba.org/eng/sentences_lists/show/6126
* Icon: http://imgur.com/eE0a9Tp
* Requested by: https://tatoeba.org/eng/user/profile/legume

=========================================

[for dev.tatoeba.org]
CALL add_new_language('bar', 4246);

[for tatoeba.org]
CALL add_new_language('bar', 6126);

**Comment by RyckRichards** [comment]
Perhaps we could either use this one - https://en.wikipedia.org/wiki/File:Flag_of_Bavaria_(striped).svg or https://en.wikipedia.org/wiki/File:Coat_of_arms_of_Bavaria.svg

Option 1 - Flag of Bavaria
![800px-flag_of_bavaria_ striped svg](https://cloud.githubusercontent.com/assets/7658430/15071588/1aedc38a-1363-11e6-8a7d-97ff56277ffd.png)

Option 2 - Coat of arms of Bavaria
![712px-coat_of_arms_of_bavaria svg](https://cloud.githubusercontent.com/assets/7658430/15071599/296a1c42-1363-11e6-8587-aa6c0d04a362.png)
