### ISSUE TITLE
Add "Back to my lists" to the "Actions" links available on the page for downloading a list

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1144]
The other day, I was downloading a number of my sentence lists. Each time I went to the download page for a new list, I wanted to go back to my list of lists. But there's no easy way to do that, since the "Actions" links in the right-hand sidebar only include "Back to all lists" and "Back to this list", not "Back to my lists". 

![back_to_my_list](https://cloud.githubusercontent.com/assets/1213027/15230571/4e5d1a44-1864-11e6-9ddc-8bcf63c67593.png)

My workaround was to keep a separate browser window open to "My lists":

![my_lists](https://cloud.githubusercontent.com/assets/1213027/15230594/74f34354-1864-11e6-8e5a-b42823289cba.png)

and to open the download window for each list I opened in a new window. However, it would be nice not to have to do that.

**Comment by trang** [comment]
To make the "Download list" page consistent with the other list pages, we should simply add the "Lists" block that contains the navigation links. 
And we can remove the "Back to all lists" link in the "Actions" block it is duplicated with the "All lists" link in the "Lists" block.

![download-list](https://cloud.githubusercontent.com/assets/221850/15270554/1e3389ea-1a24-11e6-91c5-b63e3e46b55d.png)

**Comment by alanfgh** [comment]
Yes, that would be better.
