### ISSUE TITLE
Warning on synchronous use of AJAX during posting of translations

### ISSUE THREAD

**Issue by ventice** [Tatoeba/tatoeba2#1151]
**Environment:** Chrome for Windows (any other Chrome will do).
**Prerequisites:**
Open developer console by entering **F12**.
**Steps to reproduce:**
1. Open any sentence by clicking on it
2. Click on translation button
3. Input any translation
4. Submit the translation
**Result:**
In **Console** view you can see the following message:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

![image](https://cloud.githubusercontent.com/assets/3504880/15362789/84ea1d92-1d27-11e6-9498-243db4502cff.png)

**Expected result:**
No warning in console.
**Possible troubles:**
Because the API is deprecated, its support may be dropped in some future version.

**Comment by ventice** [comment]
Taking this.

**Comment by ventice** [comment]
Looks like this happens because of `<script>` tags returned as part of response from AJAX request. For instance, this happens in `SentencesController::save_translation()` + `app/views/sentences/save_translation.ctp`. As a side effect we get set of `<script>` tags bound to each translation. So, this is fixed by removing `<script>`s from AJAX response.

**Comment by ventice** [comment]
This is the list of all JavaScript files I found in sources:

1. announcement.js
2. chosen.jquery.min.js
3. generic_functions.js
4. jquery.cookie.js
5. jquery.jeditable.js
6. jquery.scrollTo.min.js
7. sentences.change_language.js
8. sentences.contribute.js
9. sentences.copy.js
10. sentences.edit_in_place.js
11. sentences.logs.js
12. sentences.show_another.js
13. sentences_lists.edit_name.js
14. sentences_lists.remove_sentence_from_list.js
15. sinograms.search.js
16. svg4everybody.min.js
17. transcriptions.js
18. users.check_registration.js
19. wall.reply.js
20. wall.show_and_hide_replies.js

The files are sprayed all over view and controller files, so it is a little bit difficult to understand the final set of scripts sent with each page. Anyhow, for the case described in this issue, it looks like only transcriptions.js is to be included in upper level script set and scripts can be removed from views/sentences/save_translation.ctp

**Comment by ventice** [comment]
Looks like currently the fours scripts are sent with translation and added to `document` just in order to be executed and bind their events and handlers to newly added objects. Looks like a hack. Although when all of its scripts are already embedded in the document, they aren't synchronously requested from the server and the mentioned warning isn't emitted, I think makes sense to fix this hack too.

**Comment by ventice** [comment]
I think, that the correct way to ensure JavaScript invariants (the script run once via `$(document).ready(` is supposed to attach the same logic to every newly added piece of HTML) is to make a registry of invariants and run them on every newly added nodes (and not entire documents as now, since this logic is applied to the entire document as many times as many times the script is reloaded resulting in multiple handlers of the same event).
Whenever new code is added to the document, it is processed by invariant registry to attach all the required handlers matching selection criteria. At this point I will only do this for 4 scripts used in translation saving and little by little the rest of `$(document).ready(` scripts can be moved into this registry.

**Comment by trang** [comment]
This is outside of my field of expertise so all I can do is confirm that this:

> Looks like currently the fours scripts are sent with translation and added to document just in order to be executed and bind their events and handlers to newly added objects. Looks like a hack. 

is a correct interpretation.

I can't visualize exactly how your invariant registry solution looks like but I'll wait to see you PR :)
