### ISSUE TITLE
suggestions for random sentence feature

### ISSUE THREAD

**Issue by declanmalone** [Tatoeba/tatoeba2#1155]
I have a few suggestions:

1. Include an option somewhere to limit the number of languages shown.

There can be a lot of scrolling involved to skip past the translations and languages that you're not interested in. If we had a way of suppressing those languages in the results, that would eliminate much of it.

This could be done with an option like "only display profile languages in results". That might also encourage users to fill in their profile languages.

Other, more fine-grained systems could work, too, though. For example, you could let users divide languages into three "piles"---core languages (ie, profile languages), languages that you have an interest in, and languages that you're not interested in. The first group would always appear, the second would only appear if the user wants them to (via a global option or local options relevant to where they are), while the last group would never be displayed (user would have to move them from the "uninteresting" category into the "core/profile" or "interesting" category), except, perhaps as a summary ("+results in 25 other languages")

2. Make translations invisible by default

This would be especially useful for the random sentence feature since it would let users test their reading comprehension without being tempted to take a peek at the translation.

This would be an option that could be turned on or off. It could be called "hide translations initially" (or something along the lines of "make translations invisible ..." as above) or it could be given a name like "reading practice mode" or "flashcard mode" or something like that.

The way it would would, I think, would be to have a horizontal "flag bar" immediately below the sentence. It would show a flag for each available translation. Then pressing on one of the flags would toggle visibility of that particular translation. There might also need to be an icon (or text button) to toggle visibility of all translations. Newly-visible translations would appear beneath the flag bar in the same way that they do now.

A simpler alternative to the flag bar would be to keep translations where they are and just have a single toggle button beside them to control visibility. That still wastes a lot of space, though, and wouldn't look very good.

3. Make random selection feature work within "collections" or "favourites"

I'm not sure what the difference between these two is, but it's not that important. The idea I have here is, again, to make the interface more useful for someone wanting to use collections of sentences as a study/revision aid. In other words, for "collections" to work more like independent stacks of flashcards, to continue the analogy from the last point.

The whole area of collections/favourites (or simply lists/sets of sentences) doesn't seem to be too well developed on the site. I don't see any way of easily sharing collections/favourites beyond trawling user profiles. A simple feature to show a random selection from a particular collection should be a very easy thing to implement and it would, in my opinion, improve the utility of the site no end.

**Closing Remarks**

I haven't looked at the code, but it seems that points 1 and 2 could be done on the client side, so it should be pretty easy. Point 3 probably needs a lot of server-side work, though.

**Comment by trang** [comment]
Hi @declanmalone, welcome to our GitHub repository :) Please take a moment to read our [guidelines for submitting issues](https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-issues).

To ensure that our issues stay organized and manageable, it would be better if you post this message on [our Wall](https://tatoeba.org/eng/wall/index) rather than here on GitHub. 

I will close this issue and will answer to your suggestions on the Wall, once you have posted your message over there. This will allow other members of Tatoeba to participate to the discussion as well.
