### ISSUE TITLE
Add a Toggle Button to Show-Hide for Translations

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1157]
## The Problem / Request

This was requested on the Wall.
https://tatoeba.org/eng/wall/show_message/26447#message_26447
(Item ##2)
## The Solution

I think it would be better to show by default, and to give members the option to hide.
Maybe you could add the possibility of reversing this in a member's settings.

This is the related CSS necessary.  You can put this into Stylish as a style called "Hide Translations" and hide or show translations by enabling or disabling the style.

.translations{display:none}

Creating a "Toggle (Hide / Unhide)" button is easy using jQuery which is already being used by tatoeba.org.

For examples on how to do this, see the 2 "Toggle (Hide / Unhide)" buttons at the top of this page.

Tatoeba.org Native Speakers
http://bit.ly/nativespeakers

Here is a page you can use to test the above CSS in Stylish.

https://tatoeba.org/sentences/search?query=&from=fra&to=eng&has_audio=yes&trans_to=eng&sort=random
### Screenshots

Shown
![screen shot 2016-05-22 at 09 09 23](https://cloud.githubusercontent.com/assets/7934273/15451432/23266948-1ffd-11e6-873e-edaf1288710c.png)

Hidden
![screen shot 2016-05-22 at 09 10 50](https://cloud.githubusercontent.com/assets/7934273/15451433/2929a5c6-1ffd-11e6-908d-1ea28ba4ce6b.png)

**Comment by declanmalone** [comment]
Yes, I thought it would be easy enough to do with CSS or a bit of Javascript, but what you're describing seems to be a global style. Could each different result be assigned a unique class ID and be given individual controls for hiding/showing?

Actually, thinking about it again, a page-wide CSS style wouldn't be so bad. It would just mean that the person looking at results would have to look at 5 (or whatever) results in a batch, figure out if they knew the translation, and then display all of them at once to check their comprehension.

One last thing: can that CSS style (and associated scripting) all be done client-side as things stand now? If so, I'm fine with closing this request.

**Comment by ckjpn** [comment]
For your own personal use, you can do what I suggested above with Stylish.  If you don't know what Stylish is, google it.

This is the related CSS necessary. You can put this into Stylish as a style called "Hide Translations" and hide or show translations by enabling or disabling the style.

.translations{display:none}


It's not as convenient as a button, but it works.

**Comment by ckjpn** [comment]
This could be done with individual sentences, but would be more involved coding.

Each sentence has its own ID.

```
<div id="_74627_translations" class="translations">
```

**Comment by trang** [comment]
I'm closing this because it is a bit out of scope.

The use case described in the [Wall post](https://tatoeba.org/eng/wall/show_message/26447#message_26447) was:

> This would be especially useful for the random sentence feature since it would let users test their reading comprehension without being tempted to take a peek at the translation.

This use case would be best fulfilled if implemented as part an exercise in a language learning app that uses the Tatoeba corpus.

Having such a feature would be fine if we would create a learning section in Tatoeba. Having this feature on every sentence component would not be appropriate.

**Comment by ckjpn** [comment]
This issue is closed, but perhaps using the idea on this page ...
https://www.w3schools.com/howto/howto_js_toggle_class.asp
... and
.translations{display:none}

Someone could create a button that could be added somewhere on search results, or perhaps only on random order search results, which is maybe the way someone would use this "flascard-like" feature.

You could make it an optional user setting of keep the clutter off the page for those who don't want it.

**Comment by trang** [comment]
The search page is already bearing too many responsibilities. We won't add another button. 

Making it an option in the settings is also against our design strategy. We want to keep settings options to a minimum.
