### ISSUE TITLE
Link to "Tools" page

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1160]
When we redesigned the homepage, we dropped the link to the "Tools" page: https://github.com/Tatoeba/tatoeba2/issues/947#issuecomment-192709166.

The page still exists though (https://tatoeba.org/eng/tools/index) and we're not really planning to delete these features, since they are still of use for some people. Someone did point out to me that the Tools "disappeared". It would therefore be nice to find a place where we could add back this "Tools" link.

I currently have no idea where.

**Comment by halfdan** [comment]
How about in the bottom menu "Developers"? It's not necessarily developer content - but the tools are rather raw in their UI.

**Comment by trang** [comment]
Closing this.

We will never be able to invest efforts into these tools. Even if we did, we should implement them independently from Tatoeba.

The Tools page shall remain hidden for now, and one day shall be completely removed.
