### ISSUE TITLE
Veps (vep)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1182]
* Language name: Veps
* Language info: https://en.wikipedia.org/wiki/Veps_language
* ISO 639-3 code: vep
* Public List: https://tatoeba.org/eng/sentences_lists/show/6247
* Icon: imgur.com/DL4AgH6
* Requested by: https://tatoeba.org/eng/user/profile/sikmir

=========================================

[for dev.tatoeba.org]
CALL add_new_language('vep', 4255);

[for tatoeba.org]
CALL add_new_language('vep', 6247);

**Comment by RyckRichards** [comment]
@trang   Is that language implemented? I didn't asked to merge it as far there isn't a PR for that yet... Also, it seems that's not related to any branch...

**Comment by trang** [comment]
It's not implemented. You probably commited this in your `dev` branch by mistake, and it got erased when you did a `git reset`.
