### ISSUE TITLE
Private message labels/avatars in Trash folder dont follow convention

### ISSUE THREAD

**Issue by zachleigh** [Tatoeba/tatoeba2#1196]
If a user sends a message, a copy of the sent message appears in the user's Sent folder. In the folder this message uses the recipient's avatar and the label says 'to recipient'. If this message is deleted, it goes to the trash box and uses the senders avatar and says 'from sender'. Messages in Trash should follow the same conventions as they do in other folders.    
    
Should be an easy fix. The logic to determine the correct avatar/label already exists in the private_message_controller's restore method. This logic should be extracted and used in the folder method to set a view variable. This would also clean up the folder view a little.   

@trang If you accept this issue, please assign it to me :)

**Comment by trang** [comment]
@zachleigh, there you go, it's assigned to you :)
