### ISSUE TITLE
Invalid user name in private message deletes message

### ISSUE THREAD

**Issue by zachleigh** [Tatoeba/tatoeba2#1197]
When writing a private message, if the username is invalid, an alert pops up telling the user that it is invalid. When this happens, the private message content is deleted. Clicking back restores the message, but it would be nice if the message was present in the refreshed window. Could be done in a few ways, easiest would be one of these probably:
  - Validate the username with an ajax call and dont refresh the window
  - If invalid, return the message content with the message and fill in the form

**Comment by trang** [comment]
For now let's go for solution 2: return the message content with the message and fill in the form.

Later on, when we get to the stage where we redesign the private messages, we'll implement something with auto-completion on the username(s).

**Comment by zachleigh** [comment]
Ok. Ill take this one if you want me to. Should be pretty simple.
