### ISSUE TITLE
Create special tags that indentify if a sentence should/could be studied by beginners, intermediate students, and so on

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1199]
_The problem_

For now, any student / user (new or old) browse for sentences and sometimes they see a sentence like "I have a dog" while s/he is looking for more complex sentences such as "If I were you, I wouldn't go there." or even a sentence that has a phrasal verb like "You gotta do what you gotta do" and vice versa which makes it difficult for learners - and maybe for translators - to find certain sentences that they are looking for

_Possible solution_

Create a new category of tag with a different color that indentify, according to European Framework (A1,A2,B1,B2,C1 and C2), which "level" the sentence is most appropriated for. That way, even translators would study them and provide more awesome translations.

**Comment by trang** [comment]
I think lists are more appropriate for this.

Even if we would use tags, there is no need to make a new category of tags. Having a normal tag is enough.

Closing this.
