### ISSUE TITLE
Create a new category for members which last log was 3, 4 months ago.

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1202]
**Problem**

Many members posted sentences on Tatoeba but never logged in again in years. Sometimes it's possible to find sentences that were not corrected in years or active members leave comments on sentence which owners won't even read.

**Possible solution**

Create a new category for them or even set their accounts as "inactive". Also, add a symbol like " ! "  next to the username which owns an incorrect sentences. This way, we don't wait two weeks two correct them but we leave a comment telling that the sentence has been correct and why. (Final dot missing, wrong capitalization, typos, article missing, etc).

**Comment by trang** [comment]
Unless the contributor contacts us to ask for account deletion, or write in their profile that they no longer participate to the project and we can do whatever we want with their sentences, we cannot and should not treat their sentences different from sentences of active contributors.
