### ISSUE TITLE
Some elements are not rendered until the whole page is loaded

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1209]
## The Problem

The text on the page can be misleading until the whole page gets loaded in.
As the page is loading, there is an imperative sentence telling the user to delete the list.

https://tatoeba.org/eng/sentences_lists/show/6258/eng
Here are 2 screenshots -- one as the page is loading, the other after the page has loaded.

### Before the page is completely loaded
![screen shot 2016-06-18 at 08 24 34](https://cloud.githubusercontent.com/assets/7934273/16167320/7f567ad2-352e-11e6-8f2b-466fc033516f.png)

### After the page is completely loaded
![screen shot 2016-06-18 at 08 24 46](https://cloud.githubusercontent.com/assets/7934273/16167319/7f533b6a-352e-11e6-9e2a-17212b21f5bd.png)

## The Solution

Put all CSS in the header, or if that is not possible, create additional temporary CSS that goes into the header so that this text has an obvious button-like appearance until the red button CSS changes it to the final look.

**Comment by trang** [comment]
This is not caused by the CSS but the Javascript.

**Comment by ckjpn** [comment]
I guess the only solutions is "create additional temporary CSS that goes into the header so that this text has an obvious button-like appearance until the red button CSS changes it to the final look."

**Comment by ckjpn** [comment]
This is related, I think.

![screen shot 2016-06-18 at 22 23 55](https://cloud.githubusercontent.com/assets/7934273/16171191/a279aa8c-35a3-11e6-9e6e-5f1770a3bf5e.png)

**Comment by trang** [comment]
Yes it is related. 

Adding temporary CSS is not the only solution. Other things that can be done are:
* using `ng-cloak` on Angular Material elements: https://docs.angularjs.org/api/ng/directive/ngCloak
* re-adapting the HTML structure so that button labels don't get mixed with information text

**Comment by ckjpn** [comment]
I suppose you could move the .js file responsible for layout into the header of the page.

At this point, many things on the page aren't functional until the whole page is loaded in, so some of the advantage of having the .js files loading at the end of the page are lost.

**Comment by trang** [comment]
Solution currently chosen is to use `ng-cloak`. This doesn't make the page render faster, but the page will stay completely blank until everything is rendered. This probably will reduce the impression of lag, and will avoid the problem where the search bar appears late and is shifting the scroll position of the page.
