### ISSUE TITLE
Perhaps consider changing the order of items in the drop-down menu under the username.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1210]
## Problem (What could possibly be improved.)

As the menu grows longer, perhaps it would be a good idea to alphabetize the items.  I don't know if this is possible to do in all languages or not.  (Also, maybe the item "settings" should be "My settings" to make things consistent, but I don't really care.)

![screen shot 2016-06-19 at 11 54 48](https://cloud.githubusercontent.com/assets/7934273/16174988/84b35e88-3618-11e6-8a3c-79d69e9a8a40.png)

This is just an idea for a possible improvement that may put the items in a more logical order.  Feel free to close this issue if you don't think it's a good idea or it's not possible to do.

**Comment by halfdan** [comment]
Alphabetically sorting items in a menu is generally a bad idea. The menu can use some reorganization but it's advisable to sort items in a way that most often used items appear on top.

**Comment by ckjpn** [comment]
Good point.

On looking at this again, perhaps "My collection" could be changed to "My ratings" to be more accurate.

I also wonder if this is the best order to list items.

This may not be ideal for everyone, but this is basically the order I would put them in based on how I used the links. I actually don't use the top 2 the most often, but I think they should be at the top of the list.

My settings
My profile
Comments on my sentences
My lists
My comments
My sentences
My Wall messages

My ratings (collection)
My vocabulary
My sentence logs
My favorites

**Comment by ckjpn** [comment]
It's not a big deal, but perhaps the dropdown menu and the menu on the side of the page should match.

Currently, the wording is different, at least in English.

## Screenshot of https://tatoeba.org/eng/users/show/1396
![screen shot 2016-12-28 at 14 48 20](https://cloud.githubusercontent.com/assets/7934273/21514827/f66d7d34-cd0c-11e6-80eb-6ef84ec09df3.png)

**Comment by trang** [comment]
I wouldn't change anything since we don't have evidence that people have trouble with the current order. We could try to conduct a study to figure out what would be the optimal order, but I wouldn't make that a priority.

Same for the wording.
