### ISSUE TITLE
The "hide" string associated with comments on the Wall should be translatable

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1211]
Note that the string is only visible to admins, which is why it might have been overlooked.

![hide](https://cloud.githubusercontent.com/assets/1213027/16178395/7e7e6890-3614-11e6-8202-93ec179e54b1.png)

Note also that the corresponding string associated with comments on sentences **is** translated:

![sentence_comment](https://cloud.githubusercontent.com/assets/1213027/16178411/eb3d1012-3614-11e6-89a5-0fea9b03a132.png)

**Comment by Guybrush88** [comment]
This also applies for the page to import sentences from a file, which is available only to admins. In this page, all related strings are untranslated and untranslatable from Transifex

**Comment by trang** [comment]
Strings that are visible only for admins were separated into to another POT file, but this file has never been uploaded to Transifex. That's why admin strings are not translated.

I've uploaded the POT file now. These strings can be translated on Transifex.
