### ISSUE TITLE
Rusyn (rue)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1212]
*    Language name: Rusyn
*    Language info: https://en.wikipedia.org/wiki/Rusyn_language
*   ISO 639-3 code: rue
*   Public List: https://tatoeba.org/eng/sentences_lists/show/6282
*   Icon: http://imgur.com/D5LYY2H
*   Requested by: http://tatoeba.org/eng/user/profile/solejar

-------------
[for dev.tatoeba.org]
CALL add_new_language('rue', 4258);

[for tatoeba.org]
CALL add_new_language('rue', 6282);

http://dev.tatoeba.org/eng/sentences_lists/show/4258

**Comment by trang** [comment]
@RyckRichards, I need a validation from @cueyayotl before I merge the pull request. You also have mistakes in your description (language info link, language code in the SQL commands).

**Comment by cueyayotl** [comment]
After reviewing the users submissions, I am convinced that this is truly Rusyn and that the sentences have not been copied from any on-line source. You have my validation.

I wonder who chose the language icon? I would have gone with the one on Wikipedia: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Carpathian_Ruthenia.svg/2000px-Flag_of_Carpathian_Ruthenia.svg.png
Let me know and I can format it to our specifications.

**Comment by cueyayotl** [comment]
@RyckRichards, I haven't been able to contact him, but could you please have solejar write on his profile which dialect of Rusyn he speaks? A lot of the words he uses differ from Omniglot's "Useful phrases in Carpatho-Rusyn", and since he appears to speak Serbian and Croatian as well, I presume he speaks Pannonian Rusyn or perhaps even Bačka Rusyn. It would be great to have this information on his profile.

**Comment by RyckRichards** [comment]
Actually, I have sent those sentences as "unknown" ((?) Flag) since those
sentences are in Rusyn, a language not yet supported on Tatoeba. He had
chosen the language icon that will represent this language. I will send you
a copy of the email.

**Comment by cueyayotl** [comment]
I upload both potential versions of the language icon
Flag: http://imgur.com/D7MDQiG
Crest (with transparent background): http://imgur.com/NxsKUEP
Flag (original size): https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Carpathian_Ruthenia.svg/2000px-Flag_of_Carpathian_Ruthenia.svg.png
Crest (original size): https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Karpatska_Ukraina-2_COA.svg/2000px-Karpatska_Ukraina-2_COA.svg.png

I would prefer the flag, but ask him personally which would be better.

**Comment by RyckRichards** [comment]
Fixed. He already told me that he wants to keep the language ícone he suggested.

**Comment by cueyayotl** [comment]
Really!?
Well, just make sure to use the crest with TRANSPARENT background above.

**Comment by RyckRichards** [comment]
That was the one I've uploaded before- https://github.com/RyckRichards/tatoeba2/blob/3724b8b47a610139e94eb05e7db067e7a51f7658/app/webroot/img/flags/rue.png

**Comment by cueyayotl** [comment]
Right, except that your version has a WHITE background, not a TRANSPARENT background, it is different :)

**Comment by RyckRichards** [comment]
That's weird...I triple checked that ... Thanks for letting me know. I am
going to try to find one with a *transparent* background :)

**Comment by cueyayotl** [comment]
The one I uploaded above is 30x20 and has a transparent background.
http://imgur.com/NxsKUEP

**Comment by RyckRichards** [comment]
Perfect! Thank you :)

**Comment by RyckRichards** [comment]
Done! 
--> https://github.com/RyckRichards/tatoeba2/commit/d2953c056a0e80c7ff2e1c8e938ae9be6eed6fa3
