### ISSUE TITLE
"Save" button for profile sometimes not clickable

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1233]
On the dev website, I tried to edit my profile, but no valid "Save" button was shown. Here's a screenshot:

![profile_bad](https://cloud.githubusercontent.com/assets/1213027/16541845/6b5a631e-405e-11e6-8abc-d8ff3778e531.png)

Then I tried to edit it from a different browser tab. This time it looked fine:

![profile_good](https://cloud.githubusercontent.com/assets/1213027/16541846/7bf6b664-405e-11e6-8ada-79e187376e5d.png)

**Comment by trang** [comment]
Related (maybe duplicate of) issue: https://github.com/Tatoeba/tatoeba2/issues/1209

**Comment by alanfgh** [comment]
I believe that the issue you mentioned involves page elements that take a long time to load, but eventually do. However, I don't think these buttons ever loaded in the browser tab where I saw them. At least they didn't within two minutes or so.

**Comment by alanfgh** [comment]
In fact, they didn't load even after several hours.

**Comment by trang** [comment]
@alanfgh, I think this is not an issue anymore. Can you confirm?

**Comment by alanfgh** [comment]
Yes, we can close it.
