### ISSUE TITLE
"birthday" field lets me set an invalid date: February 31, 1916

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1234]
On the dev site, I was able to set my birthday to February 31, 1916. It was then displayed as "0001-11-30".

![invalid_bday](https://cloud.githubusercontent.com/assets/1213027/16541856/e4a3d746-405e-11e6-98c7-6a668b43de23.png)

**Comment by RyckRichards** [comment]
I set it to November 09,1999 and it worked fine for me 

http://prntscr.com/bnyr43

**Comment by RyckRichards** [comment]
The same to November 9, **1916**

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/16541880/32c85164-4068-11e6-8563-3e8b964da898.png)
