### ISSUE TITLE
More detailed error message with empty Japanese transcription

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1236]
I was exploring the Japanese transcription on dev in order to better translate some interface strings, and I saw that submitting an empty transcription provides a very unclear error message: http://i.imgur.com/aMXgEU7.png

My suggestion would be to add a message like "the transcription should not be empty" or something like this, it would be a much clearer message

**Comment by trang** [comment]
This is no longer relevant. Now, when submitting an empty transcription, it just won't save.
