### ISSUE TITLE
I would suggest not requiring members to enter their birthdays when editing their profiles.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1249]
Members are now required to enter a birthday in order to edit their profiles.  Was this intentional?

## Problem

This is an unneeded invasion of privacy, requiring members to lie if they don't want to give this information.

This is not information that we need.

![screen shot 2016-07-10 at 23 41 22](https://cloud.githubusercontent.com/assets/7934273/16714265/54b23308-46f8-11e6-848f-99849c4d4a3f.png)

**Comment by trang** [comment]
No it wasn't intentional.

@zachleigh, I'm assign this to you. It's a regression that I failed to notice when merging your pull request for #1234.

**Comment by zachleigh** [comment]
Ok. Ill get on it now.

**Comment by trang** [comment]
@ckjpn this should be corrected on the main website now. I let you test it and close this issue if it's good.

**Comment by ckjpn** [comment]
I was able to remove the date from my profile.
https://tatoeba.org/eng/user/profile/CK
