### ISSUE TITLE
Pashto and Sindhi are listed as LTR languages, they should be RTL

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1252]
This is my first issue here, so I hope I'm doing this right.

I noticed that Pashto and Sindhi sentences are aligned left and have their punctuation to the right of the sentence. Like other languages that use the Arabic script, Pashto and Sindhi are written from right-to-left, and have their punctuations to the left of the sentence. This needs to be fixed.

**Comment by RyckRichards** [comment]
I am on it!

**Comment by sabretou** [comment]
@RyckRichards Don't forget Sindhi!
