### ISSUE TITLE
Multiple bad linked translations likely caused by a troll.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1254]
## Problem & Suggested Course of Action

Various usernames, all likely suspended Boracasli accounts, seemed to have purposely added a incorrect translations to various sentences causing a problem with incorrect translations which was recently reported on the Wall.

Perhaps there is a chance that there are other similar cases.

Perhaps it would be possible to create a list of all possible problem sentences for someone to manually go through and verify that there are no further problems.

Would it be possible to create a list of Turkish sentences that have merged English (or other language) translations by any of Boracasli's aliases?
(See http://bit.ly/nativespeakers#tur  at the bottom of the Turkish members, you can find all the suspended Turkish accounts in gray.)
Perhaps these could be sorted by number of merged-translations, since it's quite likely any sentence with a large number of merged translations will more likely be problems than those with few merged translations.

If this is possible, perhaps DostKaplan or one of our active Turkish members would be willing to help ensure Bora hasn't caused any further problems with our database.

Possibly, just checking all the sentences merged on 2016-02-05 would be enough.
### Wall URL

http://tatoeba.org/eng/wall/show_message/26783#message_26783
### Turkish Sentence URL

https://tatoeba.org/eng/sentences/show/3263373
### Duplicate-merging Script Mentions in the Logs

Horus 2016-02-05 19:30
linked to #958875
Horus 2016-02-05 19:30
linked to #1055510
Horus 2016-02-05 19:30
linked to #1202410
Horus 2016-02-05 19:30
linked to #2879545
Horus 2016-02-05 19:30
linked to #3417709
Horus 2016-02-05 19:30
linked to #3418992
Horus 2016-02-05 19:30
linked to #3464326
Horus 2016-02-05 19:30
linked to #4459994
Horus 2016-02-05 19:30
linked to #4566795
Horus 2016-02-05 19:30
linked to #274733
Horus 2016-02-05 19:30
linked to #4403456
Horus 2016-02-05 19:30
linked to #276982
Horus 2016-02-05 19:30
linked to #4448200
### Screenshot of the sentence before Alan unlinked the bad translations.

![screen shot 2016-07-13 at 17 15 36](https://cloud.githubusercontent.com/assets/7934273/16804404/9d78d736-4946-11e6-9cd1-52a9c2cc91d3.png)

**Comment by boracasli10** [comment]
No. I don't have the right to link sentences as I am a contributor. I'll only contribute in my native language, but you don't even tolerate it! I won't contribute in any other language than my native one!

**Comment by boracasli10** [comment]
And I didn't cause any problems to the database. I am not the one who linked them. Please stop calling me evil and chill.

**Comment by boracasli10** [comment]
I would like to get in your site again. I don't want my old account to be reactivated again, I just want to have a new account.

**Comment by boracasli10** [comment]
I'm not a heartless person and I don't like to harass anyone or to be harassed by anyone. I'd just like to learn why I'm always ignored on your community.

**Comment by boracasli10** [comment]
I'll only take care of the Turkish corpus on the site!

**Comment by trang** [comment]
This was from a long time ago and it seems the issue has been solved manually. Closing.
