### ISSUE TITLE
The rotating "loading circle" looks weird.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1260]
## Problem

Each time a sentence is added, the rotating circle that tells members to wait is displayed differently.  Sometimes, it is hardly anything other than one small dot.

I assume that perhaps this is supposed to be some kind of spinning circle in which progress is shown by the circle getting completed.  However, that doesn't happen in Chrome on a Mac (and maybe other browsers, too).  The portion that rotates doesn't change once the partial circle appears.

Here is an image of various ways it has looked for me recently.

![loader-looks-wierd](https://cloud.githubusercontent.com/assets/7934273/16891908/2ad8687e-4b3d-11e6-851f-63b12a544224.png)
## URL

https://tatoeba.org/sentences/add
## Possible solution

Revert to the animated GIF image that was being used before.  It was pretty lightweight, I think, and also is something people on the Web are accustomed to seeing.

**Comment by sabretou** [comment]
This is happening to me too, Windows 10 and Firefox. I like this loading circle, but it's implementation is definitely bugged at the moment.

**Comment by jiru** [comment]
Can you elaborate about the weirdness of the circle?

> I assume that perhaps this is supposed to be some kind of spinning circle in which progress is shown by the circle getting completed.

No, that circle isn’t showing any kind of progress, it’s just endlessly spinning in a fancy way until the sentence is added. For comparison, what you’re supposed to see is what is displayed under the Indeterminate section of [this page](https://material.angularjs.org/latest/demo/progressCircular). You can also see it at the beginning of [this video](https://www.youtube.com/watch?v=hSfN_aYKkzo) (the thing the commentator defines as an "indeterminate spinner").

**Comment by jiru** [comment]
Any updates on this?

**Comment by ckjpn** [comment]
> No, that circle isn’t showing any kind of progress ...

Why does it change size?

If you could make it a standard size, then it wouldn't look so strange.
(Perhaps a 75% complete circle would work.)

**Comment by trang** [comment]
Could you make a video of what it looks like for you? Or could you confirm that the animation is the same way as in the videos of the Material Design spec on the [circular progress indicator](https://material.io/design/components/progress-indicators.html#circular-progress-indicators). 

From the initial description, it sounds like the partial circle has a fixed size while rotating, but the size changes from a sentence to another. It shouldn't be like that and if that's what you see, then we have to figure out why the animation doesn't work properly on your side.

But if what you saw was similar to the video in the Material Design spec, and you find the "bouncing" size effect strange, then I'm not in a position to explain why they made the size change. I can only assume they decided it was fitting better in their design principles.

I do not find the circular animation particularly disturbing, but I would have no objection replacing it by the [linear progress indicator](https://material.angularjs.org/latest/demo/progressLinear)., which could be placed at the top of the "Sentences added" block.

**Comment by ckjpn** [comment]
At the time I first mentioned this, it didn't look like it does now.  Sometimes, it was hardly visible, and other times it just displayed a small part of the circle.  Now, it spins with a progress-bar like change.
