### ISSUE TITLE
Messages sent to self arent restored from trash correctly

### ISSUE THREAD

**Issue by zachleigh** [Tatoeba/tatoeba2#1275]
If a user sends a message to themselves, a copy of the message is saved in the users sent box. If this copy is deleted, the logic used to determine the message's original folder fails. The message is displayed in the trash folder as an inbox message rather than a sent message and when restored, goes to the inbox instead of the sent box.    

A very minor issue, but something that may be annoying to some users.

**Comment by trang** [comment]
This is a valid bug, but I will close this nonetheless. The impact and probability of this happening are too low. We won't need to fix this bug ever.
