### ISSUE TITLE
"remember me" doesn't seem to work for everyone.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1279]
http://tatoeba.org/eng/users/login

A new member wrote and mentioned this to team@tatoeba.org.

Also, it doesn't "remember me" on Firefox on my MacBook Pro, running MacOS 10.9.5.

**Comment by ckjpn** [comment]
For a long time, recently, this hasn't been a problem for me, but today, again, I had to sign in twice using Firefox.  Chrome doesn't seem to have this problem.  (I often use both of these browsers.)

**Comment by NM-30** [comment]
+1

Windows 7 - Mozilla Firefox 49
Windows 8 - Chrome

**Comment by ckjpn** [comment]
I just got logged out of Chrome, too.

**Comment by ckjpn** [comment]
I've had to log in twice already today with Firefox, so this is definitely a reoccurring problem.

**Comment by ckjpn** [comment]
I've had to log in several times today, too, using Firefox.

Is there some additional setting I can make in Firefox to prevent this from happening, or is this a problem with tatoeba.org.

**Comment by trang** [comment]
It's unclear whether it's a problem with your settings or with tatoeba.org. We haven't changed anything regarding the login and "remember me" feature. The problem hasn't occured to me. Until we identify more precisely in which context the "remember me" fails, there is not much we can do.

**Comment by halfdan** [comment]
Nope, this problem is Angular related. It is broken in production - only however when logging in through the central login form (the one on the top right works). The rememberMe field is not correctly set even though it is displayed as checked. 

I will investigate this after the CakePHP upgrade.

**Comment by halfdan** [comment]
As a side note: The cookie is currently not encrypted which is terrifying. The password/user are just stored in plain text on the client side.

**Comment by halfdan** [comment]
Figured out what the issue was. Checkboxes are weird! The `value=1` is only submitted if at the same time the checkbox is also `checked="checked"`.  Fix in my cakephp29 branch.

**Comment by NM-30** [comment]
Hi there! 
I wanted to tell you that I'm really enjoying using italki for my online language learning.  I want to invite you to learn (or even teach) a language as well!

You can easily meet other language learners, find a teacher, and schedule lessons, all on italki.  AND, once you join, we can follow each other's progress!


Hope to see you soon. Please click on my referral link and sign up and connect with me:
https://www.italki.com/?ref=3984727
