### ISSUE TITLE
Mi'kmaq (mic)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1302]
* Language name: Mi'kmaq
* Language info: https://en.wikipedia.org/wiki/Mi%27kmaq_language
* ISO 639-3 code: mic
* Public List: https://tatoeba.org/eng/sentences_lists/show/6424
* Icon: https://s14.postimg.org/67aqj2cy9/MIC.png
* Requested by: https://tatoeba.org/eng/user/profile/milo

=========================================

[for dev.tatoeba.org]
CALL add_new_language('mic', 4264);

[for tatoeba.org]
CALL add_new_language('mic', 6424);

**Comment by RyckRichards** [comment]
taking this.
