### ISSUE TITLE
Extremaduran (ext)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1307]
* Language name: Extremaduran
* Language info: https://en.wikipedia.org/wiki/Extremaduran_language
* ISO 639-3 code: ext
* Public List: https://tatoeba.org/eng/sentences_lists/show/6443
* Icon: https://s12.postimg.org/dz124nxn1/EXT.png
* Requested by: https://tatoeba.org/eng/user/profile/TORRES

=========================================

[for dev.tatoeba.org]
CALL add_new_language('ext', 4265);

[for tatoeba.org]
CALL add_new_language('ext', 6443);

**Comment by RyckRichards** [comment]
taking this
