### ISSUE TITLE
Swabian (swg)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1314]
* Language name: Swabian
* Language info: https://en.wikipedia.org/wiki/Swabian_German
* ISO 639-3 code: swg
* Public List: https://tatoeba.org/eng/sentences_lists/show/6453
* Icon: https://s4.postimg.org/i2mm35e31/SWG.png
* Requested by: https://tatoeba.org/eng/user/profile/Esperantostern

=========================================

[for dev.tatoeba.org]
CALL add_new_language('swg', 4266);

[for tatoeba.org]
CALL add_new_language('swg', 6453);

**Comment by RyckRichards** [comment]
Taking this
