### ISSUE TITLE
Some submissions are being added multiple times.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1317]
https://tatoeba.org/eng/sentences/show/5450937

![screen shot 2016-09-19 at 12 43 33](https://cloud.githubusercontent.com/assets/7934273/18622113/dd06f464-7e66-11e6-8589-e24a75fd1971.png)

https://tatoeba.org/eng/sentence_comments/of_user/Dejo

![screen shot 2016-09-19 at 12 45 23](https://cloud.githubusercontent.com/assets/7934273/18622185/fab9338c-7e66-11e6-931a-03bfdac4a4f6.png)

**Comment by jiru** [comment]
I am pretty confident this problem has been fixed in #1284. One can reopen a ticket if this happens again.
