### ISSUE TITLE
Links ending with a quotation mark get an extra semi-colon added on the surface of the page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1318]
This is only a cosmetic problem.
The link still works correctly.

Here's the URL that is in the screenshot.
https://www.google.com/search?q="Let+well+enough+alone."
(Note that the link doesn't work properly from github since the final quotation mark isn't included.)

![screen shot 2016-09-22 at 19 46 55](https://cloud.githubusercontent.com/assets/7934273/18745652/f54cf174-80fd-11e6-95a1-1ae7794b05b9.png)

**Comment by jiru** [comment]
It looks like this bug is [solved](https://tatoeba.org/sentences/show/30213#comment-918530). @ckjpn, can you confirm it’s solved?
