### ISSUE TITLE
Indirect translation shows when there are no shared direct links

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1325]
## Problem

This page shows an indirect English translation that doesn't seem to match at all.
When looking at both English sentences, you can see that they do not share any direct translations.

https://tatoeba.org/eng/sentences/show/3983663

![screen shot 2016-09-30 at 06 51 50](https://cloud.githubusercontent.com/assets/7934273/18973891/e4045b5e-86da-11e6-9a76-ed4d081ea0f0.png)

## The Direct Translations of the English sentences.

eng
[#2358800] I have a right to defend myself.
 epo
Mi rajtas defendi min.
 rus
У меня есть право защищать себя.
 tur
Kendimi savunma hakkım var
 tur
Kendimi savunmaya hakkım var.
 tur
Kendimi savunma hakkına sahibim.
 tur
Kendimi savunma hakkım var.

eng
[#304620] He is slow of understanding.
 deu
Er ist schwer von Begriff.
 epo
Li estas nekomprenema.
 epo
Li havas nebonan komprenkapablon.
 fra
Il est un peu lent.
 hun
Lassú felfogású.
 jpn
彼は理解力がのろい。
rus
Он непонятлив.

**Comment by alanfgh** [comment]
This is not a problem with the Tatoeba code. It's a problem with the fact that the Esperanto sentence "Li estas nekomprenema" ("He is slow of understanding") was incorrectly linked to the Turkish sentences "Kendimi savunma hakkım var" and "Kendimi savunma hakkım var." (Note that those sentences differ only in the fact that the first one is missing a period.) I unlinked them. I believe the issue can now be closed.
