### ISSUE TITLE
Cron job for updating the auto-detection of the language of sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1330]
Currently the auto-detection of the languages tends to fail sometimes, quite often for shorter sentences, and, if I remember correctly, the algorithm was updated like a couple of years ago. Updating it now, and maybe weekly with a cron job (since many new sentences are added every week), would greatly improve it, since it will be constantly more accurate in detecting languages

**Comment by jiru** [comment]
It is updated weekly now.
