### ISSUE TITLE
Wrong sentence is linked instead of adding a new translation

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1336]
As reported by odexed on the wall:

> Bug.
> When I'm trying to translate #3307344 into Russian, my translation disappears but #5483277 appears as a link. I belive it's the only sentence with this problem so far.

https://tatoeba.org/ita/wall/show_message/27428#message_27428

**Comment by Guybrush88** [comment]
I just reproduced this with another sentence. As I wrote on the wall:

I wanted to add a translation to #5448863 (a translation that isn't present in the database, I checked), but #2990793 gets linked instead

**Comment by trang** [comment]
1. What is the text of the sentence you tried to add.
2. Were you on "Auto-detect" for the language?

**Comment by trang** [comment]
I tested with odexed's sentence. 

It turns out that there's a collision between:
* `rus` + `Я начинаю понимать, почему тебе так нравится эта игра.`
* `ell` + `Ποιο είναι το καλύτερο πανεπιστήμιο στη Γερμανία;`

They are both converted into: `3tsnqit`.

```
mysql> select lang, text, hash, LOWER(CONV(murmur_hash_v3(CONCAT(lang, text), 0), 10, 32)) as murmurhash from sentences where id in (3843344, 3843345);
+------+----------------------------------------------------------------------------------------------------+------------------+------------+
| lang | text                                                                                               | hash             | murmurhash |
+------+----------------------------------------------------------------------------------------------------+------------------+------------+
| rus  | Я начинаю понимать, почему тебе так нравится эта игра.                                             | 3tsnqit          | 3tsnqit    |
| ell  | Ποιο είναι το καλύτερο πανεπιστήμιο στη Γερμανία;                                                  | 3tsnqit          | 3tsnqit    |
+------+----------------------------------------------------------------------------------------------------+------------------+------------+
```

Since Guybrush also ran into the problem, it seems collision can happen fairly often, from human generated sentences.

-----

I think the best approach here is that when duplicate candidates are detected, we make an additional check on the text of the sentences before determining if it's a real duplicate. So we use the hash to quickly find duplicate candidates, but we always need in the end to check against the actual text to decide if there's really a duplicate.

The only consequence I can think of is that we can never put a UNIQUE constraint on the `hash` column, but I don't think it is a problem.

We could also look for another hash function that ensures no collision, but that means time investing which hash we could use, and it would require to shut down again Tatoeba to update the hash of the sentences. It wouldn't be worth it.

@zachleigh, what do you think? Should I assign this issue to you?

**Comment by zachleigh** [comment]
I think your fix sounds good. If there is a hash collision, a second check on the text will be performed. Only if the text is an exact match will the sentence be marked as a duplicate.    

Yes, I will take this one.

**Comment by trang** [comment]
Great, thanks! =)

**Comment by Guybrush88** [comment]
sorry for my late reply, but I was/am using the auto-detect feature, and the text I wanted to add was "Sono quasi sicuro che Tom è a Boston.", instead of "Are you sure we have enough money to buy everything?"

**Comment by ckjpn** [comment]
Perhaps you could also check that the the languages were the same before identifying a sentence as a duplicate. This might help prevent a potential problem.

There are cases where there would be exact matches of the text, but the languages would be different.

I might also perhaps speed things up, if you only searched for potential matches within the language, which it seemed to be doing on the dev site, I thought.  However, the reported problems so far seem to be matches to sentences in languages other than the one being submitted.

Here are several existing examples.  (There are more.)

4882526	tur	"Marco!" "Polo!"	dursun
2454365	eng	"Marco!" "Polo!"	Hybrid
1078452	por	"Tom!" "Mary!"	alexmarcelo
3928854	tur	"Tom!" "Mary!"	duran
4136594	ind	"Tom!" "Mary!"	Bilmanda
1076718	epo	"Tom!" "Mary!"	sacredceltic
4422730	hun	Ah!	bandeirante
4556915	ind	Ah!	dbahasa
4560254	ita	Ah!	Guybrush88
4882428	tur	Ah!	dursun
1381613	por	Ah!	tulio
4244704	hun	Aha.	maaster
2526063	ber	Aha.	Amastan
2723823	ita	Ave Maria.	Guybrush88
1648598	eng	Ave Maria.	Spamster
4755902	ita	Bah!	Guybrush88
1381665	por	Bah!	tulio
1980710	nno	Begge to er i live.	Combine988
1141522	dan	Begge to er i live.	danepo
3334514	dan	Bilen er blå.	cimmic
1394281	nob	Bilen er blå.	Combine988
3224612	ita	Bravo!	Guybrush88
3368502	eng	Bravo!	Jesse
3626846	tur	Bravo!	vvv123
4829278	ron	Bravo!	elenacristina260
1381735	por	Bravo!	tulio
5370537	bos	Čestitam!	iwasinabadway
1057639	hrv	Čestitam!	akvo
4566941	ita	Chapeau!	Guybrush88
628227	eng	Chapeau!	Eldad
4215983	nld	Cool!	megamanenm
635079	deu	Cool!	Manfredo
5165639	spa	Corra.	cueyayotl
1301435	ita	Corra.	Guybrush88
509765	ron	Da.	Ricardo14
5008033	cor	Da.	Kevre
478741	bos	Da.	FeuDRenais
905140	nds	Echt?	slomox
378761	nld	Echt?	Dorenda
4461163	ita	Entra.	Guybrush88
2115152	por	Entra.	alexmarcelo
1501220	spa	Entre.	marcelostockle
406487	por	Entre.	brauliobezerra

**Comment by zachleigh** [comment]
@ckjpn I thought so too. The pull request checks for exact matches between both the text and the language.

**Comment by Guybrush88** [comment]
Marafon reported that this issue happened also without the auto-detection. As a translation of #1785185, the translation should have been "Выгляни в окно! Похоже, скоро дождь будет", but it was replaced by #2556144 ("Viaggio molto.")

cfr.: https://tatoeba.org/ita/wall/show_message/27438#message_27438
