### ISSUE TITLE
After adding a translation, which is a duplicate, so the duplicate gets linked, clicking the list icon doesn't show the lists.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1338]
I knew that the matching sentence with a contraction existed, so I just typed in the sentence, and it linked the 2 together.  However, when I wanted to add the sentence to a list, I couldn't.

After reloading the page, it worked.

https://tatoeba.org/eng/sentences/show/5512022
![screen shot 2016-10-12 at 17 29 50](https://cloud.githubusercontent.com/assets/7934273/19302982/b0a1096c-90a1-11e6-9992-2e3a05406706.png)

**Comment by trang** [comment]
@ckjpn Please confirm whether or not you can still reproduce this problem.

**Comment by agrodet** [comment]
Ping? :)

**Comment by trang** [comment]
Well I guess I'm closing this. With the new sentence design on its way, I don't think we need to hunt for this bug.
