### ISSUE TITLE
Wrong duplicate sentence is linked

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1340]
As reported by odexed on the wall:

> I don't know how this system works exactly ( https://github.com/Tatoeba/tatoeba2/pull/1327 ) but there are some more problems I see about it. For example, when I tried to translate #1544158 as "Постарайся успокоиться." (this sentence already existed in Tatoeba), "Постарайтесь успокоиться." appeared as the translation. It's similar but doesn't match since there are two different forms for "you" in Russian and Spanish. This means that the first result was taken instead of the second https://tatoeba.org/eng/sentenc...und&to=und

https://tatoeba.org/ita/wall/show_message/27452#message_27452

**Comment by zachleigh** [comment]
This is a known issue being addressed by pull request #1337
