### ISSUE TITLE
Confirm hash duplicates in vocabulary

### ISSUE THREAD

**Issue by zachleigh** [Tatoeba/tatoeba2#1342]
Since we're having some issues with sentence hash collisions, it would probably be a good idea to also detect vocabulary hash collisions and then confirm them by comparing the vocabulary item language and text. We could probably extract the confirmation logic out to the Hashable behavior to minimize code duplication.    

@trang Ill take this one.

**Comment by zachleigh** [comment]
@trang So, this isnt going to work. There are two main problems:
  - On the vocabulary table, the hash is the primary key and so must be unique. So even if we go through the trouble of filtering out false positives, we still cant add a vocabulary item that has a hash collision.  
  - Because the users_vocabulary table does not contain the text or lang of the vocabulary item, it is impossible to verify the true identity of an item. So items with hash collisions can be added, but because we are treating the vocabulary_id field as if it were unique, it could create a very bad situation if a user had two user_vocabulary items with the same hash. 

Not quite sure how to proceed. The only thing I can think of is to change the vocabulary table to use a standard primary key instead of the hash. That would probably require rewriting a lot of code.

**Comment by trang** [comment]
There's no other solution that I can think of either. I don't think it would be too much of code rewriting.

The todo would be:

- Rename current `id` column to `hash` in `vocabulary` table.
- Create `id` as primary key with auto increment.
- Update `vocabulary_id` in `users_vocabulary` table to be equal to the new `id`.
- Change the code in the models, controller and views to take into account that the new `id` is just a regular id:
  - In `Vocabulary` model, readapt functions `addItem()` and `incrementNumSentences()`.
  - In `UserVocabulary` model, readapt function `add()`.
  - In `VocabularyController`, readapt functions `save()` and `remove()`.
  - In the vocabulary views, remove any conversion `bin2hex()` on the id.

That's more or less it.

**Comment by ckjpn** [comment]
##Errors I see.
1. at the top of the page is an error message.
2. also the layout of the right column is strange.

https://dev.tatoeba.org/eng/vocabulary/of/CK
![screen shot 2016-11-20 at 00 06 47](https://cloud.githubusercontent.com/assets/7934273/20456227/60c33e1a-aeb5-11e6-9006-b6fbaf9637dc.png)


This page looks OK, though.
https://dev.tatoeba.org/eng/vocabulary/add_sentences

**Comment by trang** [comment]
@ckjpn the error at the top can be ignored. It can appear when the website is on debug mode (which I just switched off).

I cannot reproduce the problem you have with the side column.

**Comment by ckjpn** [comment]
The screen shot above is on a Macintosh, using Chrome, with Stylish disalbled.

I also can't submit a new word.
The incomplete rotating circle just keeps going around.

See video.
http://sendvid.com/2bs0l7ae

**Comment by trang** [comment]
Do you have this problem on other browsers? On my side I have no problem adding new vocabulary.

**Comment by ckjpn** [comment]
Safari works OK.

Chrome is displaying this page properly now.
https://dev.tatoeba.org/eng/vocabulary/add

However, I still can't add a word.
https://dev.tatoeba.org/eng/vocabulary/add

**Comment by ckjpn** [comment]
https://dev.tatoeba.org/eng/vocabulary/add
Firefox on a Mac works OK.

**Comment by trang** [comment]
There was maybe some inconsistencies in the database, regarding your vocabulary. I've just cleaned that up, can you try again on Chrome and confirm it's OK now.

**Comment by ckjpn** [comment]
> confirm it's OK now.

Confirmed.
