### ISSUE TITLE
SELECT COUNT(*) is very slow in big tables

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1345]
https://dev.tatoeba.org/eng/
This page has 50 queries, which took in total 1442 ms.

```
SELECT COUNT(*) AS `count` FROM `sentences` AS `Sentence` WHERE 1 = 1 
// took 840 ms 
```

---

https://dev.tatoeba.org/eng/sentences/show_all_in/eng/none/none/indifferent
This page has 135 queries, which took in total 699 ms.

```
SELECT COUNT(*) AS `count` FROM `sentences` AS `Sentence` WHERE `Sentence`.`lang` = 'eng' 
// took 492 ms
```

---

https://dev.tatoeba.org/eng/sentence_comments/index
This page has 186 queries, which took in total 648 ms.

```
SELECT COUNT(*) AS `count` FROM `sentence_comments` AS `SentenceComment` 
WHERE `SentenceComment`.`user_id` != 63758 
// took 315 ms
```

---

Everytime, the count takes 50% or more of the total time. Ideally the count should not take more than a few milliseconds.

**Comment by trang** [comment]
Actually this is not a problem (for now) for the `sentence_comments`. I added an index which was missing on `user_id` (5907b19e40d4d34c4be7ec358ceeea39d6a2c3b0) and the response time is a little bit better.
```
SELECT COUNT(*) AS `count` FROM `sentence_comments` AS `SentenceComment` 
WHERE `SentenceComment`.`user_id` != 63758 
// took 90 ms (vs. 315 ms previously)
```

The problem still remains for the `sentences`.

**Comment by halfdan** [comment]
This is also an issue for large lists, e.g. CK's List 907 (https://tatoeba.org/eng/tags/show_sentences_with_tag/7770/eng). The COUNT(*) here takes 17 seconds locally.

```
SELECT COUNT(Tag.id) AS `count` FROM `tags_sentences` AS `TagsSentences` LEFT JOIN `sentences` AS `Sentence` ON (`TagsSentences`.`sentence_id` = `Sentence`.`id`) LEFT JOIN `tags` AS `Tag` ON (`TagsSentences`.`tag_id` = `Tag`.`id`)  WHERE `Tag`.`id` = 7770 AND `Sentence`.`lang` = 'eng';
+--------+
| count  |
+--------+
| 410562 |
+--------+
1 row in set (17.46 sec)
```

The nbrSentences cache on the tag model doesn't help here as soon as there's a filter applied (here: lang=eng)

**Comment by trang** [comment]
Closing.

We'll implement a separate counting table wherever necessary and we'll have to stop retrieving big sets. We'll create separate more specific issues as we stumble upon specific cases that need optimization.
