### ISSUE TITLE
Remove "not directly translated" option in "Browse by language" page

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1348]
## Problem

Currently, the list of sentences in language X not translated into language Y is calculated via a SQL query. Example for English sentences not translated into French:

```
SELECT `Sentence`.`id`, `Sentence`.`text`, `Sentence`.`lang`, `Sentence`.`user_id`, 
`Sentence`.`hasaudio`, `Sentence`.`correctness`, `Sentence`.`script`, `User`.`id`, 
`User`.`username`, `User`.`group_id`, `User`.`level`
FROM `sentences` AS `Sentence` 
LEFT JOIN `users` AS `User` ON (`Sentence`.`user_id` = `User`.`id`) 
WHERE `Sentence`.`lang` = 'eng' AND Sentence.id NOT IN (SELECT Link.sentence_id 
FROM sentences_translations AS `Link` WHERE `Link`.`sentence_lang` = 'eng' 
AND `Link`.`translation_lang` = 'fra' ) 
ORDER BY `Sentence`.`id` DESC LIMIT 10
```

This query can take up to 20-30 seconds to complete (with our ~5 million sentences), depending on the number of sentences in each language. Considering that the server is regularly experiencing high load average, we need to remove this option from the "Browse by language" page.

## Suggested solution

The search engine provides a similar feature, but is much faster, with the difference that the results are limited to 1000 sentences. This limitation shouldn't be too much of an issue since the main use case of this option is for contributors to find sentences to translate.

We can provide this option via the "Contribute" > "Translate sentences" page, by adding a form:
```
Find sentences in [ language_dropdown ] not translated into [ language_dropdown ]
[ Search ]
```

And we can temporarily add the following information on the "Browse by language" page, instead of the language dropdown: `This option been removed from this page. Please use the "Translate sentences" page to find untranslated sentences.`

**Comment by jiru** [comment]
Another important difference between the search results and the “Browse by language” page is that sentences without language are not indexed. I think we also use the “Browse by language” as a reliable reference for the total number of sentences in a given language.

**Comment by trang** [comment]
@jiru the plan was only to remove the "not translated into" option, not to remove the whole page. The functionalities you mention are not affected by this.

**Comment by trang** [comment]
As it turns out, I didn't have to create another form on the "Translate sentences" page, because there was already a form that did the job. It was redirecting to the "Browse by language" page, so I just changed it to redirect to the search page.

The main inconvenience left is that the title on the "Browse by language" page was more explicit (`Sentences in {language} with audio not translated into {translationLanguage}`). 
Now the user will be redirected to the search page, so the title they will see is something like `Advanced search (1000 results out of 25897 occurrences)`, which is less intuitive.

**Comment by ckjpn** [comment]
On the "Translate Sentences" page, I'd suggest the following.
https://dev.tatoeba.org/eng/activities/translate_sentences

1. 
Add the 3 sort options, instead of only having "modified".  This would be easy to add and would likely be useful.

&sort=modified
&sort=random
&sort=shortest

https://dev.tatoeba.org/eng/sentences/search?from=eng&to=none&trans_filter=exclude&trans_to=jpn&sort=modified


2. Remove the "Display random sentences"

This is likely one reason new members add translations to the wrong languages.

Also, you can sort of get this if you add the 3 sort options to the "search" as mentioned above.

**Comment by ckjpn** [comment]
I would also suggest adding 2 messages to the "Translate Sentences" form.


Message 1 = A foreign language you know

Message 2 = Your native language

You may want to use a different wording, but these 2 are short and understandable, I think.

## Screenshot of https://dev.tatoeba.org/eng/activities/translate_sentences

![screen shot 2016-10-28 at 10 50 46](https://cloud.githubusercontent.com/assets/7934273/19791708/962b9782-9cfe-11e6-8a01-8364ebd3cfe8.png)

## Screenshot of http://tatoeba.ueuo.com/

This is an example of what I mean.

![screen shot 2016-10-28 at 10 54 44](https://cloud.githubusercontent.com/assets/7934273/19791707/96282390-9cfe-11e6-8fae-9326b02e3355.png)

**Comment by trang** [comment]
@ckjpn your suggestions are out of scope for this issue. They should be part of an issue that is about reworking the "Translate sentences" page. If there isn't already one, you may create one, or you can wait until I create one, when it is in my plans to rework that page.
