### ISSUE TITLE
Improve the "Translate Sentences" Page

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1351]
# Improve the "Translate Sentences" Page

https://tatoeba.org/eng/activities/translate_sentences
## Change to  this:

![screen shot 2016-10-30 at 11 12 41](https://cloud.githubusercontent.com/assets/7934273/19834041/47e34296-9e93-11e6-9e39-69753bbe7a5e.png)
## From  this.

![screen shot 2016-10-30 at 11 01 16](https://cloud.githubusercontent.com/assets/7934273/19834038/349af7c4-9e93-11e6-87fc-7ad0446d7180.png)
## Improvement 1

Add the 3 sort options, instead of only having "&sort=modified".  This would be easy to add and would likely be useful.

&sort=modified
&sort=random
&sort=shortest
## Improvement 2

I would also suggest adding 2 messages to the "Translate Sentences" form.

This would encourage members to contribute sentences in their own native languages, thus improve the quality of the Tatoeba Corpus.

Message 1 = A foreign language you know

Message 2 = Your native language

You may want to use a different wording, but these 2 are short and understandable, I think.
## Improvement 3

Remove the "Display random sentences"

This is likely one reason new members add translations to the wrong languages.

Also, you can sort of get this if you add the 3 sort options to the "search" as mentioned above.
## Raw Code

I think CakePHP may require this to be done differently.

```
<br /><input type="radio" checked name="sort" value="random"> random order
<input type="radio" name="sort" value="words"> shortest first
<input type="radio" name="sort" value="created"> recent first
```

```
</select>
<br /><i>(A foreign language you know.)</i>
</fieldset>
```

```
</select>
<br /><i>(Your native langauge or strongest language.)</i>
</fieldset>
```
## Related:

https://github.com/Tatoeba/tatoeba2/issues/1348#issuecomment-256816705

https://github.com/Tatoeba/tatoeba2/issues/1348#issuecomment-256818997
## You can try something very similar already set up here.

http://tatoeba.ueuo.com/

What's being suggested is something like what is on the left.

![screen shot 2016-10-30 at 11 29 21](https://cloud.githubusercontent.com/assets/7934273/19834081/51da61ac-9e94-11e6-983b-a82c619a9480.png)

Perhaps it would also be useful to have what's on the right added to the "Translate Sentences" page, too.  Members may want to search for sentences to translate, for example "I like " or "Do you", or even just one word such as "where" or "why".

**Comment by ckjpn** [comment]
This is also related.

http://tatoeba.ueuo.com/search/untranslated.html
Find Proofread English Sentences That Are Not Yet Translated

Something like this would be helpful on tatoeba.org, but perhaps since it only works with English would not yet be appropriate.

As far as I know, no native speaker members of other languages have compiled "white lists" of proofread good sentences in their languages, with the possible exception of tommy_san who has a short list of good Japanese sentences, I think.

**Comment by ckjpn** [comment]
Here is a recent example of a new member who has linked a translation to the wrong sentence.

https://tatoeba.org/eng/sentences/show/5585135

This may not be because of the "random sentence" thing on the "Translate Sentences" page, but it perhaps is.

Refer to "improvement 3" above.

###  Improvement 3

Remove the "Display random sentences"

This is likely one reason new members add translations to the wrong languages.

Also, you can sort of get this if you add the 3 sort options to the "search" as mentioned above.

**Comment by ckjpn** [comment]
I would still like to see something like this done.  I think it would help improve the website.

Here is a working demo of what I'd like to see.
http://tatoeba.byethost3.com/translate_sentences.html

The "audio" part could be taken out if you don't think it's appropriate.


## Screenshot
![screen shot 2016-12-22 at 15 15 30](https://cloud.githubusercontent.com/assets/7934273/21416840/90149214-c859-11e6-94a0-4dade7073d8a.png)

**Comment by ckjpn** [comment]
https://tatoeba.org/eng/activities/translate_sentences

Perhaps "last created first" shouldn't be the default.
These are likely to contain the most errors.

Random might be better.
Possibly also add the option for "oldest first" and make that the default.

**Comment by trang** [comment]
> Perhaps "last created first" shouldn't be the default.
> These are likely to contain the most errors.

Why would we want to show by default sentences that are likely to contain errors? Shouldn't we prioritize translations of error-free sentences?

I think by last modified is fine for now. We don't really have any data to make a decision regarding what's the best order.

**Comment by ckjpn** [comment]
>Why would we want to show by default sentences that are likely to contain errors? Shouldn't we prioritize translations of error-free sentences?

That's my point.  Currently, you have the default set to "last created" which are the ones more likely to contain errors than sentences that have been in the database for a while.

Setting this to random as the default would more likely avoid these newest sentences.

Another idea would be to an an "oldest first" option and set it as the default, using &sort=created&sort_reverse=yes as the default.  I'm not sure that this is the best option, but members who didn't like this option could easily change from the default to one of the other choices.

It might also be useful to add the following options.  I don't think these would add unwanted clutter to the page and would likely be options that some members would choose.

"limited to self-proclaimed native speakers", using &native=yes
"limited to sentences with audio", using &has_audio=yes

These could be added as checkbox options (on or off) as additional search options for your radio options.

**Comment by trang** [comment]
My bad, I misread "shouldn't be default" as "should be default".

I actually had in mind that the default was on "Last modified first" but I realize it's not. I must have forgotten to set it properly in the form. I wanted to keep the same order as previously. I'll fix that.

I think unless we notice some specific cases where this order is a problem, we don't really have a reason to change it.

**Comment by ckjpn** [comment]
One advantage of random being the default is that it would be very unlikely that 2 members would be translating the same group of sentences at the same time.

At this time, we probably don't have many members who would be translating to and from the same languages at the same time, so it's not a big deal, but it might be important in the future.

**Comment by trang** [comment]
> One advantage of random being the default is that it would be very unlikely that 2 members would be translating the same group of sentences at the same time.

It's a good point. But I guess by the time we encounter this problem, we should be working on implementing a proper translation workspace rather than redirecting the contributor to the advanced search results.

**Comment by alanfgh** [comment]
I agree that having the most recently modified sentences show up first by default could be problematic. I like the idea of random being the default because it keeps the search results more diverse and hence more interesting to translate. Other sorting criteria don't have that advantage. For instance, sorting by modification date favors sentences modified/added at a particular time, often by a single contributor, and often following a pattern ("I love ice cream", "You love ice cream", etc.).

**Comment by trang** [comment]
> I like the idea of random being the default because it keeps the search results more diverse and hence more interesting to translate.

That's a good point too. A more convincing one as well. The only drawback is that the random option has an awkward behavior (#1667) where pagination is basically useless. I'd like to see first if we can figure out an easy enough solution for it and if so, when we fix it we can switch the default selection to "Random" on the "Translate sentences" page.

If not, we should perhaps bring back the "Several random sentences" and re-adapt it to work with the "Not directly translated into" parameter. We can still keep everything into one single block on the UI, just that if the "Random" radio button is selected, we don't redirect to the advanced search but to the "Several random sentences" page.

Or we should start working on improving further the "Translate sentences" page by displaying the sentences to translate directly on that page rather than redirecting to the advanced search.

**Comment by ckjpn** [comment]
> The only drawback is that the random option has an awkward behavior (#1667) where pagination is basically useless.

Is there any way to eliminate the pagination of the "random" results and only show the first page of results?
If so, then it would just be a "random 10" or a "random 100", etc., depending on a member's settings.

Or possibly, maybe you could add something like "&results=20" to the URL to direct the search to only deliver 20 random results.

**Comment by trang** [comment]
> Is there any way to eliminate the pagination of the "random" results and only show the first page of results?

Yes, this is of course possible. This is why I had the suggestions to either bring back the "several random sentences" or to display the sentences directly on the translate page.

**Comment by ckjpn** [comment]
I would still suggest changing the default from "Last modified first" to something else, since "last modified first" includes "last created first" which are often not yet proofread by other members and are likely to contain errors.

I'd suggest "random" would be a good default. Even if the pagination isn't exactly correct, it shouldn't really matter.

"Fewest words first" might work, but often the very shortest sentences are not the easiest to translate.

Remember that many people, especially first-time visitors, will use the default, since they would assume that the default was chosen for some specific reason.

https://tatoeba.org/eng/activities/translate_sentences

**Comment by trang** [comment]
I went ahead and changed the default option to random.
