### ISSUE TITLE
Sentence counts are wrong on ORPHAN sentences and USER'S SENTENCES in a given language.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1354]
## https://tatoeba.org/eng/wall/show_message/27557#message_27557

Bug.
https://tatoeba.org/eng/activit...of/marafon/rus
Translate Russian sentences that belong to marafon (452823 results)

That number is definitely wrong.

## https://tatoeba.org/eng/wall/show_message/27575#message_27575

Bug (??)

Whenever I click to choose a page I'd like to adopt sentences from, It doesn't return any sentence

http://prntscr.com/d2d7qt

https://tatoeba.org/eng/activit...ces/por/page:5

Orphan sentences in Portuguese (227966 results)

Steps to reproduce:

► Go to https://tatoeba.org/eng/activit..._sentences/por 
► Click over each or just another page you want or just click on "next page" https://tatoeba.org/eng/activit...ces/por/page:2

**Comment by trang** [comment]
Should be fixed.

This was due to some changes I made regarding #1345. I deployed the changes on the main website when the server was suffering high load average, in order to figure out if the high load was possible due to the way sentences are counted.
