### ISSUE TITLE
In "advanced search", allow limiting output to only sentences with "indirect translations".

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1360]
While doing a PM exchange with a Portuguese native speaker, I wondered if this would be possible.

In "advanced search", allow limiting output to only sentences with "indirect translations".

It's already possible to show both direct and indirect translations at the same time, limited to sentences that have at least one indirect translation.

https://tatoeba.org/eng/sentences/search?from=eng&tags=List+907&to=por&trans_filter=limit&trans_to=por&trans_link=indirect&sort=random

If it were possible to further limit the output to only show sentences with indirect translations, but no direct translations, it would likely help us get more bilingual pairs.

We often have cases in which there are already direct translations, and the all the indirect translations cannot be linked.

However, I think we also have many cases in which there is no direct translations and the indirect translations very likely match.  If we could allow this kind of searching, then it would be less tedious to link such sentences.

**Comment by Poulpisator** [comment]
I think this was duplicated by the recent #2031
