### ISSUE TITLE
Suggested Improvements for a Page Only Admins Can See

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1361]
Suggested Improvements for a Page Only Admins Can See

## Note

This is a low priority enhancement, since only admins can see this page.

However, it should likely be easy to do, I think, for anyone who knows CakePHP.

https://tatoeba.org/eng/users/index/page:1/sort:since/direction:desc

## 1. The links to the usernames.

Making the following change would likely make this more useful.

### Instead of this
https://tatoeba.org/eng/users/edit/1396
### Have it go to this.
https://tatoeba.org/eng/users/show/1396

## 2. The "Since" date

Always include the full date and time, rather than having the "... ago" type of date.

Doing so, would mean that I wouldn't have to go through the pain of converting "yesterday" into just the date, and all the "hours ago" ones into today's date, and then also converting all the "days ago" ones into the correct dates.

Additionally, even doing this, I lose all the exact times of day. However, that doesn't really matter so much.

Alternatively, a 5-field weekly export of members would work for me.

user ID + tab + username + tab + since (date joined) + tab + level + tab + group

(The email addresses should be left out, obviously.)

## 3. Pagination Layout

Either change this to what is currently used elsewhere on the website, or add the old CSS back in to the code, so this looks OK.

## Screenshot
![screen shot 2016-11-18 at 12 27 27](https://cloud.githubusercontent.com/assets/7934273/20417807/66123a90-ad8b-11e6-82c3-6b38ccadefe4.png)

**Comment by trang** [comment]
This page is no longer available since bd155fee3ffb7d156d1d256dfa6b22a23cabb2fa.
