### ISSUE TITLE
Show a sentence in "red" when the correctness level is -1 everywhere you see the sentence on the website.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1362]
## The Problem

Many times on the website, if the correctness level is -1, members don't know it.

You can see it's red on the page.
https://tatoeba.org/eng/sentences/show/3684750
![screen shot 2016-11-19 at 04 39 02](https://cloud.githubusercontent.com/assets/7934273/20443878/2c4f7db8-ae12-11e6-8509-c2eef178cb58.png)

You can't see it's red on the home page.

![screen shot 2016-11-19 at 04 29 17](https://cloud.githubusercontent.com/assets/7934273/20443741/72d2a626-ae11-11e6-9e8c-a5ffc43b8497.png)

## Note

If this is not too difficult to change, it would likely be helpful to display such sentence in red all the time.

**Comment by trang** [comment]
I'm not really convinced it's necessary to have the warnings on the sentence displayed above comments.

The main purpose of the sentence block is to give a bit of context about the comment. For that, it is in my opinion enough to have the sentence text, the language and the owner. Other information (such as tags, audio, "correctness" or license) are superfluous. 

If the absence of indicator on the correctness of sentences displayed above comments impacts your workflow, please describe your workflow. There's certainly another solution to make the workflow more efficient and I will create a new issue accordingly.

Closing this one now.
