### ISSUE TITLE
Increase clarity of "link" and "unlink" icons

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1365]
This thread:

https://tatoeba.org/eng/wall/show_message/27476#message_27476

suggests modifying the UI to make it more clear that the "scissors" and "chain link" icons represent desired actions rather than current states. In other words, the "scissors" icon could be misinterpreted as saying "Currently, there is no link".

The suggestion is made that hovering over the scissors icon bring up a tooltip. Currently, at least in Firefox and Chrome, hovering already shows a URL of the form ```https://tatoeba.org/<lang>/links/delete/<sentence1>/<sentence2>```. However, the display is in the lower left-hand corner of the screen and is easy to miss. By contrast, hovering over the list icon, for example, shows a tooltip directly at the cursor that says "Add to list".

It's worth noting that the font color already provides a visual clue: black for direct links, gray for indirect ones. There is an additional visual clue: a blue arrow for direct links, a light gray one for indirect ones.

Personally speaking, I have in the past looked at a scissors icon and tried to remember whether it indicates a desired action or a current state. However, the additional visual clues ("delete" URL, black font, and blue arrow) were always sufficient to remind me. So I'm not going to advocate for or against the proposal.

**Comment by ckjpn** [comment]
At the same time you are adding a tool tip to these icons, perhaps you might want to consider adding tooltips to other icons that don't yet have them.

I think the "i" icon that means to go the the sentence's page doesn't yet have a tooltip.  Perhaps there are others.

**Comment by trang** [comment]
This is a regression. The icons used to show tooltips.

- For the scissors: `Unlink this translation.`
- For the chains: `Make into direct translation.`

Inspecting the HTML code shows that these tooltip are still set, but they are set on the `<svg>` element, where the attribute `title` is probably not supported.
