### ISSUE TITLE
Ingrian (izh)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1366]
- Language name: Ingrian
- Language info: https://en.wikipedia.org/wiki/Ingrian_language
- ISO 639-3 code: izh
- Public List: https://tatoeba.org/eng/sentences_lists/show/6460
- Icon: https://s15.postimg.org/jflueg18b/IZH.png
- Requested by: https://tatoeba.org/eng/user/profile/sikmir
# 

[for dev.tatoeba.org]
CALL add_new_language('izh', 4267);

[for tatoeba.org]
CALL add_new_language('izh', 6460);

**Comment by NM-30** [comment]
Taking this.
