### ISSUE TITLE
Southern Sami (sma)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1370]
- Language name: Southern Sami
- Language info: https://en.wikipedia.org/wiki/Southern_Sami_language
- ISO 639-3 code: sma
- Public List: https://tatoeba.org/eng/sentences_lists/show/6713
- Icon: https://s17.postimg.org/7c2lmw7nj/SMA.png
- Requested by: https://tatoeba.org/eng/user/profile/protondonor
# 

[for dev.tatoeba.org]
CALL add_new_language('sma', 4268);

[for tatoeba.org]
CALL add_new_language('sma', 6713);

**Comment by NM-30** [comment]
taking this
