### ISSUE TITLE
Tag "ambiguous" got renamed into "5 syllable"

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1375]
Reported by [marafon on the Wall](https://tatoeba.org/eng/wall/show_message/27774#message_27774)

> bug
>
> The tag "ambiguous" is now called "5 syllable":
> https://tatoeba.org/rus/tags/show_sentences_with_tag/ambiguous/
>
> https://tatoeba.org/rus/sentences/show/7110
> https://tatoeba.org/rus/sentences/show/358404
> and so on.

No idea how this happened...

**Comment by trang** [comment]
I fixed manually the name directly in the database last week.

I noticed that the values of `user_id` and `created` for this tag have changed.

**prod database**

```
mysql> select * from tags where id = 5;
+----+---------------+-----------+-------------+---------+---------------------+----------------+
| id | internal_name | name      | description | user_id | created             | nbrOfSentences |
+----+---------------+-----------+-------------+---------+---------------------+----------------+
|  5 | ambiguous     | ambiguous | NULL        |    1396 | 2016-11-19 07:12:52 |            931 |
+----+---------------+-----------+-------------+---------+---------------------+----------------+
```

**dev database**

```
mysql> select * from tags where id = 5;
+----+---------------+-----------+-------------+---------+---------------------+----------------+
| id | internal_name | name      | description | user_id | created             | nbrOfSentences |
+----+---------------+-----------+-------------+---------+---------------------+----------------+
|  5 | ambiguous     | ambiguous | NULL        |       6 | 2010-06-13 00:49:24 |            586 |
+----+---------------+-----------+-------------+---------+---------------------+----------------+
```

I quickly checked the code of the Tag model, but I currently cannot pinpoint the source of the bug.

@ckjpn you are user 1396. It seems you did something on November 19th that changed the name of the tag. In case you remember what it was, please let me know.

**Comment by ckjpn** [comment]
I don't think I did anything out of the ordinary.
I don't have direct access too the database, so I shouldn't have been able to change that, I think.
Perhaps that change was done by User 6.
