### ISSUE TITLE
"More search options" link is not displayed properly in advanced search

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1376]
Reported by [odexed on the Wall](https://tatoeba.org/eng/wall/show_message/27785#message_27785):

> This is how I see the advanced search page in my Chrome at 100% scale from the Russian interface. Am I the only one? However it looks fine at 90%.
> 
> http://i.imgur.com/cFUuda4.png?1

The link to the wiki help page is displayed in between the two columns.

**Comment by halfdan** [comment]
Fixed in the CakePHP 2.9.4 branch. Will auto-close once the branch gets merged.
