### ISSUE TITLE
Unable to delete vocabulary item right after adding it

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1377]
Steps to reproduce:
1. Go to the [page to add vocabulary](https://tatoeba.org/vocabulary/add)
2. Add a new vocabulary item. It appears below.
3. Click on the delete button (bin icon) next to it. Nothing happens.

**Comment by NM-30** [comment]
I was able to delete from the "Vocabulary" section on Profile. I added the
word "wooden" and I tried to delete. That's what happened

**Comment by jiru** [comment]
@NM-30 Do you mean deleting from [your My vocabulary items page](https://tatoeba.org/vocabulary/of/NM30) or the [Add vocabulary items page](https://tatoeba.org/vocabulary/add)? Only the latter doesn’t work.

**Comment by halfdan** [comment]
This seems to work fine for me now.
