### ISSUE TITLE
Can't delete items on the "Add vocabulary items" page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1386]
## The Problem
Clicking the trash icon on this page doesn't delete the item.

https://tatoeba.org/eng/vocabulary/add
![1](https://cloud.githubusercontent.com/assets/7934273/21547778/8598017c-ce2b-11e6-995e-1d69c325b198.png)

## However, it does work on this page.

https://tatoeba.org/eng/vocabulary/of/CK
![2](https://cloud.githubusercontent.com/assets/7934273/21547781/8adeb5f4-ce2b-11e6-8594-7bab5794d7fb.png)

**Comment by halfdan** [comment]
Duplicate of #1377

**Comment by halfdan** [comment]
This time I can however replicate the issue.

**Comment by halfdan** [comment]
I believe this is fixed in dev - can you try to reproduce this on http://dev.tatoeba.org/?

**Comment by ckjpn** [comment]
Works OK on dev.
