### ISSUE TITLE
It takes too long to add several lists 

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1394]
I work so much with lists as far I'm both a language teacher and a student and them are **really** useful for me - I have about 70 lists (due my absence. I'd have about 200+ lists) - since I can ask people to translate sentences, I pick up some I'm going to study/teach and add in a list - español: nationalities, Français: musique, etc, and also I ask to **few** students of mine to translate some sentences into their native languages to check if they got what we had learned

The problem is that whenever I have to add several lists, I have to click over "All public  lists" from the sentence page I'm on - https://tatoeba.org/eng/sentences_lists/show/6842 - whenever I want to add a list or rename it. In order words, if I want to add 30 lists, I have to 

1- create a sentence from [Browse > Browse by list](https://tatoeba.org/eng/sentences_lists/index)
2-from there, type the name of the new list and press enter
![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/21959356/31038440-daa3-11e6-911e-ab7849a7ce59.png)
3-choose who will be able to see/edit the list 
4-click over "All public lists"
![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/21959346/e181664e-daa2-11e6-9cfc-131265219b23.png)
5 - repeat the steps 1,2,3 and 4 29 times more.

Wouldn't that be easy - and/or possible - if we have something like

![screenshot_3](https://cloud.githubusercontent.com/assets/7658430/21959398/3779943a-daa4-11e6-99e0-84d6ae7f84e6.png) 

?

Thanks so really much!

**Comment by ckjpn** [comment]
@RyckRichards 

All you have to do is hold down the correct key to force the resulting list to open in a new tab.

On a Macintosh, it's the "command" key.

Once you edit the list, just close the new tab, and you'll be back on the "create list" page.

Note that if you just copy the URL, and give that to your students, you don't need to set the list to "public", I think.  The list doesn't have to be publicly listed for your students to see the list if they have the URL.

**Comment by RyckRichards** [comment]
@ckjpn 

Thanks for your comment.

The point is that on this way, I'd have to that even 29 times ( 29 holding down the correct key to force the resulting list to open in a new tab) and worse: I could create a duplicate list.

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/21967777/05b95872-db6c-11e6-8c32-cb5e4ffb1f34.png)

but if I had the "Create a new list button" on the page lust I've just created, I wouldn't have to open multiple times and it would be very unlikely to add a list I added before since I would had saved :

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/21967833/cc8491d8-db6c-11e6-8e01-28f45a01aa60.png)

**Comment by ckjpn** [comment]
You can always rename any list to a unique name if you accidentally create a list with a duplicate name.

I personally would consider this a non-issue for the programmers and think this is a problem that you can solve yourself by being careful. Creating multiple lists at one time is not likely something that many members, including yourself, would do very often.  However, if some programmer thinks this is more important to solve than some of the other issues here, then I have no problem with them doing coming up with some system that helps you.

.

**Comment by trang** [comment]
@RyckRichards I think the implementation of the list feature in the new sentence design (#2154) addresses the problem you described here: you don't have anymore to go to the lists section to create lists, it will be possible to create lists directly from the sentence.

Could you try out the new list feature on the dev website and confirm that it solves your problem?

**Comment by RyckRichards** [comment]
From "Add by sentences page", it's not possible

![image](https://user-images.githubusercontent.com/7658430/75079815-dae7ed80-54e8-11ea-9830-9705a7758664.png)

I clicked on the sentence I've created but it didn't allow me to create a new list either

![image](https://user-images.githubusercontent.com/7658430/75079872-184c7b00-54e9-11ea-9cc4-4663ee817a4c.png)

I've also tested it on a sentence another user created. Same problem :/


>> Displaying sentences with the new design were active all the time
![image](https://user-images.githubusercontent.com/7658430/75079978-606b9d80-54e9-11ea-8e2e-2ab051ab9c43.png)

**Comment by trang** [comment]
@RyckRichards The new sentence design was not yet implemented on every page. For now you can only have it on the search results and the "Browse by language" page.

**Comment by RyckRichards** [comment]
Oh got it. My apologies -__- (kinda numb). Testing again.

**Comment by RyckRichards** [comment]
Search results - that work (Yaaaaay)

![image](https://user-images.githubusercontent.com/7658430/75080480-d91f2980-54ea-11ea-9e86-4193da1873af.png)

Browse by language too :D

![image](https://user-images.githubusercontent.com/7658430/75080544-0966c800-54eb-11ea-9026-1e1455fc59b9.png)
 
What a great news!!!!
