### ISSUE TITLE
Use better password hashing algorithm

### ISSUE THREAD

**Issue by halfdan** [Tatoeba/tatoeba2#1396]
Tatoeba currently uses md5 password hashing: https://github.com/Tatoeba/tatoeba2/blob/260358cfb080ba3976c442a5bd70b0f3c81a76b6/app/app_controller.php#L120

This is widely considered very insecure. We should update to bcrypt as soon as possible.

It's obviously not possible to change the password hashing without some kind of migration path as we can't rehash existing passwords (since we don't have them in plain text). The solution is as follows:

- We change the default hashing to bcrypt
- When a user logs in
  - we compute the bcrypt hash of their PW and compare it with the one in the DB. If it doesn't match...
  - we compute the MD5 hash of their PW and compare it with the one in the DB. If it matches
  - we log the user in and store the bcrypt hash in the DB. Which will then be used by default the next time the user logs in.

The password field is currently a VARCHAR(50) and will likely have to be changed to a CHAR(60). See [for reference](http://stackoverflow.com/questions/5881169/what-column-type-length-should-i-use-for-storing-a-bcrypt-hashed-password-in-a-d)

**Comment by jiru** [comment]
Cc @linkmauve

I am implementing what @Ppjet6 said. I’m using blowfish/bcrypt as new hashing method. It allows you to set a 'cost' value, which defaults to 10. Basically the higher the cost, the longer it takes to hash a password. Increasing the cost by one doubles the computing time. 

I’m wondering if we want to set this cost higher.

I ran a few tests on the VMs with a cost of 10.
```txt
dev.tatoeba.org   about 3.32 s / 50 hashs = 66 ms / hash
tatoeba.org       about 4.95 s / 50 hashs = 99 ms / hash
```

**Comment by Ppjet6** [comment]
Do we want to prevent timing attacks and compute both hashes every time? So that people can't differenciate between users with a `$NEW_HASH` and one with an `$OLD_HASH`.

We would keep this until the day everybody has switched, but that day will probably never come.
