### ISSUE TITLE
Replace Flash player with native audio controls

### ISSUE THREAD

**Issue by halfdan** [Tatoeba/tatoeba2#1397]
Chrome is removing Flash and soon people won't be able to listen to the audios on tatoeba. html5 has a native audio element that we can use to play audio.

**Comment by halfdan** [comment]
Source: https://blog.google/products/chrome/flash-and-chrome/

Commit above replaces the Flash player in favour of the native audio API that every modern browser has. This should also solve https://github.com/Tatoeba/tatoeba2/issues/1374.

**Comment by ckjpn** [comment]
If would be good to have code that has Flash fallback, so we don't leave some visitors with no access.

I think I've suggested a couple of possibilities for this in earlier issues.

**Comment by trang** [comment]
At this point, I don't think it would be worth the effort to implement a Flash fallback. The HTML5 audio element is supported broadly enough.

http://caniuse.com/#feat=audio

**Comment by ckjpn** [comment]
It's up to you, I guess.

It's relatively easy to do, especially since there are several free-to-use, already tested and debugged ways to do this. You can just adapt, or almost use someone else's code just the way it is.

Think of people who are using older computers who may not be able to use the latest browsers.   How would you feel is you were one of the few people that were left behind?

In my opinion, which may not matter much here, it's sort of like not offering wheel chair access since only a very small percentage of people in the world use wheel chairs.

**Comment by trang** [comment]
You are free to submit a pull request if this is something that you feel strongly about. For me, this is not an easy five-minute implementation, and it is not a high priority compared to many other things in my todo stack.

**Comment by ckjpn** [comment]
I'll wait until the CakePHP update is completed, then I'll install everything.
I haven't had a working installation of tatoeba for a few years.

**Comment by ckjpn** [comment]
Here are 2 ways it could be done with flash fallback.

Here is one way.
http://www.manythings.org/bilingual/jpn/210.html

This is another way.
These both use the same basic code.
http://www.manythings.org/sentences/audio/4853.html
http://www.manythings.org/ipad/listen/americanbritish.html

**Comment by halfdan** [comment]
I think this is a wasted effort. Flash is literally being phased out
everywhere and there are barely any browsers around that don't support
HTML5 audio.

If users start to complain we can do something about it - until then I
suggest focusing on more pressing issues.

**Comment by ckjpn** [comment]
That's OK with me.  It's easy enough to do, but likely this won't affect any regular visitors.

We've already had a number of reports from visitors saying that the current audio player doesn't work for them, so perhaps if a new method doesn't work for some visitors, it's not a big problem.

Visitors who can't use HTML5 audio and who want to listen can always visit my website, I guess.

**Comment by ckjpn** [comment]
At the same time you convert over to using the audio tag, it might be worth considering speed controls.
Having the option to slow the audio down might be a useful feature for some members, I think.
HTML5's <audio> makes this easy to do.
Maybe a setting could be made members' profiles to set a cookie for this.

See the bottom of this page for an example of speed control.
http://www.manythings.org/audio/news/
I don't think you would need to add in this many options, though.
Also, perhaps it would also not be necessary to have any of the faster than normal speed options.

**Comment by halfdan** [comment]
> It's easy enough to do, but likely this won't affect any regular visitors.

It may be easy to do now, but it will mean that we need to support it and keep it up to date. 

> Visitors who can't use HTML5 audio and who want to listen can always visit my website, I guess.

That's not the goal. While it's fine that people can do that, it shouldn't be a requirement to leave Tatoeba. Again, if the issue arises that the HTML5 player doesn't work, we can reconsider this.

> At the same time you convert over to using the audio tag, it might be worth considering speed controls.

This is a separate issue. Can you please raise it if you feel strongly about it? Please also try to keep feature requests to being actual requests and not provide a solution (unless you're going to implement it). Chucking more things onto the settings page might not be best solution here.
