### ISSUE TITLE
"So if you want" -> "If you want" in the new "About adoption" text

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1400]
The "About adoption" text box on the production site contains two paragraphs, the second one leading from the first with the connecting phrase "So if..." The text box on the dev site condenses the text into a single paragraph. Making the text more concise is good, but the initial "So if" now needs to become simply "If".

**Comment by trang** [comment]
This was a bug actually, the first paragraph was not being displayed due to a missing `echo`. The text for the "Tips" was also missing, I fixed that too.
