### ISSUE TITLE
code is printed at the top of the "@needs native check" page on the dev site

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1402]
Here's the URL:

http://dev.tatoeba.org/eng/tags/show_sentences_with_tag/1207

Here's the output:

:::
array(1) { ["TagsSentences"]=> array(4) { ["limit"]=> string(2) "10" ["fields"]=> array(2) { [0]=> string(7) "user_id" [1]=> string(11) "sentence_id" } ["conditions"]=> array(1) { ["Tag.id"]=> string(4) "1207" } ["contain"]=> array(2) { ["Tag"]=> array(1) { ["fields"]=> array(1) { [0]=> string(2) "id" } } ["Sentence"]=> array(7) { ["Favorites_users"]=> array(1) { ["fields"]=> array(0) { } } ["User"]=> array(1) { ["fields"]=> array(4) { [0]=> string(2) "id" [1]=> string(8) "username" [2]=> string(8) "group_id" [3]=> string(5) "level" } } ["SentencesList"]=> array(1) { ["fields"]=> array(1) { [0]=> string(2) "id" } } ["Transcription"]=> array(1) { ["User"]=> array(1) { ["fields"]=> array(1) { [0]=> string(8) "username" } } } ["Translation"]=> array(2) { ["Transcription"]=> array(1) { ["User"]=> array(1) { ["fields"]=> array(1) { [0]=> string(8) "username" } } } ["Audio"]=> array(2) { ["User"]=> array(1) { ["fields"]=> array(1) { [0]=> string(8) "username" } } ["fields"]=> array(2) { [0]=> string(7) "user_id" [1]=> string(8) "external" } } } ["Audio"]=> array(2) { ["User"]=> array(1) { ["fields"]=> array(3) { [0]=> string(8) "username" [1]=> string(13) "audio_license" [2]=> string(21) "audio_attribution_url" } } ["fields"]=> array(2) { [0]=> string(7) "user_id" [1]=> string(8) "external" } } ["fields"]=> array(6) { [0]=> string(2) "id" [1]=> string(4) "text" [2]=> string(4) "lang" [3]=> string(7) "user_id" [4]=> string(11) "correctness" [5]=> string(6) "script" } } } } }
:::

I see the same kind of output for the pages for other tags, such as \@change and \@check.

This behavior may be revealed by some development settings on my machine that regular users wouldn't have. If you need to look at anything in particular, just let me know.

**Comment by trang** [comment]
This is nothing to worry about. It's not an error, there's just somewhere in the code where we print the content of a variable. This output is indeed visible only if the debug level is set to higher than 0 (which is currently the case on the dev website). We should remove it, but it's not harmful.

**Comment by alanfgh** [comment]
Got it. Thanks for fixing it.

**Comment by trang** [comment]
Actually I was wrong, the output was not just debug information. It was printed out even on non-debug mode.

In any case, thanks for reporting it.
