### ISSUE TITLE
Mnong, Central (cmo)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1404]
- Language name: Mnong, Central
- Language info: https://en.wikipedia.org/wiki/Mnong_language
- ISO 639-3 code: cmo
- Public List: https://tatoeba.org/eng/sentences_lists/show/6868
- Icon: https://s30.postimg.org/69do2rgc1/CMO.png
- Requested by: https://tatoeba.org/eng/user/profile/Nobeuchan
# 

[for dev.tatoeba.org]
CALL add_new_language('cmo', 4273);

[for tatoeba.org]
CALL add_new_language('cmo', 6868);

**Comment by RyckRichards** [comment]
taking this!
