### ISSUE TITLE
double-quote in vocabulary item causes it to be displayed with "SENTENCE" (not "0 SENTENCES")

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1405]
If you include one or more double-quotes in a vocabulary item that you add, the item is displayed with "SENTENCE" rather than "0 SENTENCES".

The third item in the list looks like it contains a double-quote, but it's actually a Hebrew character ("gershayim"), used to indicate the missing letters in an abbreviation, that looks similar. In fact, in our corpus, an ASCII double-quote character is always substituted for the gershayim (with the exception of one sentence, namely 3198896). Thus, while double-quotes may be undesirable in most vocabulary items in other languages, simply stripping the quotes when the item is added or preventing addition of items that contain them is probably not a good thing to do.

![add_vocab_missing_count](https://cloud.githubusercontent.com/assets/1213027/22855556/7e221288-f050-11e6-961d-4116fa5742e4.png)

**Comment by jiru** [comment]
@alanfgh The bug should be fixed on dev.tatoeba.org now. Please give it a try.

**Comment by alanfgh** [comment]
I then added the word

ordinary

without quotation marks and saw that it also was listed as belonging to 6418602 sentences. So as long as we ignore the sentence count, it seems to work.

**Comment by jiru** [comment]
My bad. It’s because the counting of sentences rely on Sphinx, which is not set up yet on dev.tatoeba.org. I updated the code so that it handles properly the case when the search is disabled, showing "unknown number of sentences". So it’s not possible to test it on dev.tatoeba.org right now, but it’s working for me locally.
