### ISSUE TITLE
Chavacano (cbk)

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#141]
- Language name: Chavacano
- Language info: http://en.wikipedia.org/wiki/Chavacano_language
- ISO 639-3 code: cbk
- Public List: http://tatoeba.org/eng/sentences_lists/show/3128
- Icon: http://a4esl.com/temporary/tatoeba/flags/cbk.html
- Requested by: http://tatoeba.org/eng/user/profile/mervert1

**Comment by RyckRichards** [comment]
Duplicate of  #149
