### ISSUE TITLE
Pages created for moderators are "empty"

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1411]
https://tatoeba.org/eng/wall/show_message/28028#message_28028 by[marafon](https://tatoeba.org/eng/user/profile/marafon)

Bug.

These pages are empty:
https://tatoeba.org/eng/tags/for_moderators/561
https://tatoeba.org/eng/tags/for_moderators/370

by Ricardo14

http://prntscr.com/e8429z

**Comment by trang** [comment]
Note that as a workaround, corpus maintainers can use the regular tags page and order by date of tag.

For instance, these are the sentences in Esperanto tagged `@change`, order by date of tag descending (i.e. latest date first):
https://tatoeba.org/eng/tags/show_sentences_with_tag/561/epo/sort:added_time/direction:desc

**Comment by trang** [comment]
Some corpus maintainers reported that they still find the page to be useful even if it doesn't show the sentence text. They can still click on the `#` link to go to the sentence. The page basically helps them to have quick access to sentences that are tagged `@change` for longer than 2 weeks.

I've asked them to try and use the `show_sentences_with_tag` page instead for a little while and see if they can still do their corpus maintenance tasks fairly efficiently. I'll check their feedback in a couple of weeks.

The plan is in any case to delete the "Tags for moderators" page at some point. It is broken and outdated (it contains the term "moderator" which we've replaced by "corpus maintainer" long ago). We just have to see what we can/should do to compensate for this removal.
