### ISSUE TITLE
Leaving comments on sentences is not possible anymore

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1412]
https://tatoeba.org/eng/wall/show_message/28026#message_28026 

"Whenever I leave a comment on a sentence, the following unlocalised message is displayed. However, the comment is posted properly.

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred."

**Comment by trang** [comment]
The title is incorrect. It IS possible to leave comments. The problem was that posting a comment would show an error.

Closing this as this is related to #1413.
