### ISSUE TITLE
Autocompletion of tags is not working

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1415]
https://tatoeba.org/eng/wall/show_message/28016#message_28016

[Guybrush88](https://tatoeba.org/eng/user/profile/Guybrush88)
> the autocompletion of tags when adding them isn't present anymore after the update.

[Ricardo14](https://tatoeba.org/eng/user/profile/Ricardo14)

>+1
>I can confirm that. 
>I used Chrome and Mozilla.

**Comment by alanfgh** [comment]
wallebot also complained about this in a private message.
