### ISSUE TITLE
Komi-Permyak (koi)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1417]
- Language name: Komi-Permyak
- Language info: https://en.wikipedia.org/wiki/Komi-Permyak_language
- ISO 639-3 code: koi
- Public List: https://tatoeba.org/eng/sentences_lists/show/6874
- Icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Komi-Permyak_Okrug.svg/30px-Flag_of_Komi-Permyak_Okrug.svg.png
- Requested by: https://tatoeba.org/eng/user/profile/astru
# 

[for dev.tatoeba.org]
CALL add_new_language('koi', 4275);

[for tatoeba.org]
CALL add_new_language('koi', 6874);

**Comment by RyckRichards** [comment]
taking this!
