### ISSUE TITLE
Komi-Zyrian (kpv)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1418]
- Language name: Komi-Zyrian
- Language info: https://en.wikipedia.org/wiki/Komi-Zyrian_language
- ISO 639-3 code: kpv
- Public List: https://tatoeba.org/eng/sentences_lists/show/6873
- Icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Komi.svg/30px-Flag_of_Komi.svg.png
- Requested by: https://tatoeba.org/eng/user/profile/astru
# 

[for dev.tatoeba.org]
CALL add_new_language('kpv', 4276);

[for tatoeba.org]
CALL add_new_language('kpv', 6873);

**Comment by RyckRichards** [comment]
taking this
