### ISSUE TITLE
Mirandese (mwl)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1420]
- Language name: Mirandese
- Language info: https://en.wikipedia.org/wiki/Mirandese_language
- ISO 639-3 code: mwl
- Public List: https://tatoeba.org/eng/sentences_lists/show/6875
- Icon: https://s16.postimg.org/s3kgafl9x/MWL.png
- Requested by: https://tatoeba.org/eng/user/profile/Balamax
# 

[for dev.tatoeba.org]
CALL add_new_language('mwl', 4277);

[for tatoeba.org]
CALL add_new_language('mwl', 6875);

**Comment by RyckRichards** [comment]
taking this
