### ISSUE TITLE
Chinese pinyin and alternative script are not working

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1424]
For some reason, it works fine on the dev website.
https://dev.tatoeba.org/eng/sentences/show/2394779

![screenshot_86](https://cloud.githubusercontent.com/assets/221850/22990848/c13b97d4-f3ba-11e6-9131-ef6cd5d660a1.png)

But not on the prod website.
https://tatoeba.org/eng/sentences/show/2394779

![screenshot_87](https://cloud.githubusercontent.com/assets/221850/22990852/c2804162-f3ba-11e6-8872-2788b494c549.png)

I have no idea.

**Comment by jiru** [comment]
I can’t reproduce this bug. @trang can you confirm it is still happening?

**Comment by trang** [comment]
No longer happening. That was before our crash as well. I guess I'll close.
