### ISSUE TITLE
Strings for audio feature that need fixing

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1426]
1) [Reported by Wesel](https://tatoeba.org/eng/wall/show_message/28065#message_28065)

> The message on the "Audio" page of users who have not contributed audio records says "X does not have contributed any audio". I guess it should be changed to something more grammatical.
> https://tatoeba.org/rus/audio/of/Wezel

2) [Reported by CK](https://tatoeba.org/eng/wall/show_message/28027#message_28027)

> While this may not be considered a programming bug, it seems wrong to say "attributed to" in this case, since that makes it sound like we aren't really sure if these audio recordings were by the contributor.
> 
> I'd suggest this change.
> 
> FROM:
> The following audio recordings, attributed to CK, are licensed under the CC BY-NC-ND 3.0 license.
> FROM:
> The following audio recordings by CK are licensed under the CC BY-NC-ND 3.0 license.

3) [Reported by CK](https://tatoeba.org/eng/wall/show_message/28025#message_28025)
 
> While this perhaps wouldn't be considered a programming bug, it's an error.
> 
> The "Licensed under:" says "unknown".
> 
> In actuality, we do know that this member has not chosen to license her files for use outside of tatoeba.org.
> 
> Screenshot: http://prnt.sc/e7z51e
> 
> URL: https://tatoeba.org/eng/sentences/show/3068344

**Comment by alanfgh** [comment]
Regarding issue 1, it should be changed from "X does not have contributed any audio" to "X has not contributed any audio", as Wezel says.

Regarding issue 2, I agree with CK's proposed wording.

Regarding issue 3, there are at least two ways to resolve the issue, but they involve more work than simply changing the string that currently says "unknown". I'll call them A and B.

A: Come up with a license covering audio whose creator doesn't want to license its beyond use by Tatoeba. Call it something like TAT-AUD-TAT-ONLY. Create a page with an explanation of what this means, the same way the CC BY-NC-ND 3.0 page explains what that license means. In this case, the page would explain that the content is not available to use outside Tatoeba. Then for audio that is not licensed for use outside Tatoeba, show the string TAT-AUD-TAT-ONLY (where the string CC BY-NC-ND 3.0 is in CK's screenshot). When users click on TAT-AUD-TAT-ONLY, they should be taken to the page for the corresponding license.

B: Merge the string that says "Licensed under" together with the existing license names. Then you could have options "Licensed under CC BY-NC-ND 3.0" and "Licensed for use on Tatoeba only".

**Comment by trang** [comment]
Would it be okay to have `License` instead of `Licensed under`?

Example:
- `License: CC BY-NC-ND 3.0`
- `License: none` or `License: for Tatoeba only`

**Comment by alanfgh** [comment]
Yes, "License:" is fine. I strongly prefer "for Tatoeba only" over "none".  The latter suggests no restriction on use. Actually, I prefer "for use by Tatoeba only" even more, since "for Tatoeba only" could suggest that only Tatoeba needs a license for that audio, and otherwise it's free for the taking.
