### ISSUE TITLE
for each tag displayed with autocompletion, show number of sentences with the tag

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1429]
When we get tag autocompletion working again (see issue #1415), we could think about implementing a suggestion by wallebot that we display next to each possible tag the number of sentences that have that tag. (We currently do this from the "Browse all tags" page.) This would help people make sure that they're not misspelling the name of a common tag.

**Comment by jiru** [comment]
Setting the 'good first issue' label because the sentence number is already there but unused. The value could be displayed by editing `webroot/js/autocompletion.js`.

**Comment by Ynue** [comment]
I'd like to work on this issue!

**Comment by AndiPersti** [comment]
> Setting the 'good first issue' label because the sentence number is already there but unused.

Even if we [fix the bug](https://github.com/Tatoeba/tatoeba2/pull/2332) I've introduced a few weeks ago, the numbers we get from `suggestd` aren't really useful unless we restart it after each tagging event. The number of sentences is only current at the time of initialization but will not get updated later on. So the longer `suggestd` is running more and more tags will have a wrong count.

Here's how one tag looks like on my dev machine:
````
vagrant@stretch:~/Tatoeba$ echo 'select t.name, t.nbrOfSentences, count(ts.id) from tags t join tags_sentences ts where t.id = ts.tag_id and t.id = 30;' | mysql tatoeba
name    nbrOfSentences  count(ts.id)
foo     6       6
````
After restarting `suggestd` I get the expected result back:
````
vagrant@stretch:~/Tatoeba$ sudo systemctl restart suggestd
vagrant@stretch:~/Tatoeba$ wget -q -O - 'http://127.0.0.1:8080/suggest?str=foo&sort=1&size=10'
<?xml version="1.0" encoding="utf8"?>
<items>
        <item value="6">foo</item>
</items>
````
But after simulating adding a tag, i.e. use the API call from `SuggestdListener` the value doesn't change:
````
vagrant@stretch:~/Tatoeba$ wget -q -O - 'http://127.0.0.1:8080/add?str=foo&value=1'
OK
vagrant@stretch:~/Tatoeba$ wget -q -O - 'http://127.0.0.1:8080/suggest?str=foo&sort=1&size=10'
<?xml version="1.0" encoding="utf8"?>
<items>
        <item value="6">foo</item>
</items>
````

Looking at the source code for `suggestd` that's no surprise:
https://github.com/Tatoeba/suggestd/blob/2829988fe980fee860e115fd007f0a01ed9c1714/src/tree.c#L22-L35
`tree_add` gets called after parsing the request to the `add` endpoint. It looks for an existing node/tag and only sets the passed value if the node/tag is new. So it lacks an update feature. And even if it had one we would need to send the new sentence count and not `1` as we do now.

**Comment by Ynue** [comment]
Because I noticed this incoherence, I decided not to rely on `suggestd` anymore, and use roughly the same function as the `view_all` function that is used to render the whole list of tags and the corresponding number of sentences. Is it a better solution?

**Comment by jiru** [comment]
Yes, I think getting rid of suggestd altogether would be a smart move. It’s not maintained and it’s source of a few other bugs. But the replacement solution should have good enough performance so that many people typing in at the same time doesn’t affect the server load. All things considered, this is not so simple so I’m removing the "good first issue" label.

**Comment by ckjpn** [comment]
Instead of adding numbers, which isn't really necessary to do the job and clutters up the interface with unneeded information, why not just sort these with the most commonly-used ones at the top?

That would accomplish the feature of hiding the seldom-used misspellings at the bottom of the list.

**Comment by AndiPersti** [comment]
> why not just sort these with the most commonly-used ones at the top?

They are already sorted by the number of sentences tagged.

**Comment by ckjpn** [comment]
I like it better without the numbers.
It definitely looks better without the numbers.
I wonder how many people think adding this geeky-looking complexity helps them tag sentences.

https://user-images.githubusercontent.com/7934273/83383559-53cbdf00-a420-11ea-8fe0-bfa32a7edac0.png

**Comment by trang** [comment]
@ckjpn The solution isn't necessarily to remove the numbers. The problem happens even without the number because some tags have a longer name and the autocomplete dropdown list is very narrow. We could make it a bit larger and we could as well introduce some visual way to more easily distinguish between each item.

**Comment by ckjpn** [comment]
The question remains whether having numbers really helps people with tagging, or does it just clutter up the interface with unneeded data.

It doesn't matter a great deal to me, but clutter is clutter.

**Comment by trang** [comment]
We won't really know if it helps until people have at least some time to try it. You can ask on the Wall after a couple of weeks and see what people say.

The data is not always needed, but it's not completely unneeded. The general use case for this number is that if you get to choose between `tag1` and  `tag2` and in your mind both would have been appropriate tags, seeing the number could help you choose the most appropriate one.

Keep in mind that clutter for you is not always clutter for someone else. I can point out many things on the UI that I feel is clutter but that other contributors find necessary.

**Comment by ckjpn** [comment]
Like I said, it doesn't matter to me a great deal.  If it helps people do the job more efficiently, then it's not clutter.

In much the same way colorful icons help people more quickly identify icons, especially on reuse, but you felt that for you, converting these all gray looked better. Maybe, at this time, you might re-consider going back to having color on the tool icons.  (Keep in mind that ... for you is not always ...)

**Comment by jiru** [comment]
The list is currently the same width as the input field. I think it could be more readable if it were larger, be it with or without numbers.
