### ISSUE TITLE
"Translations" caption from list page now reads "Actions"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1432]
It should say "Show translations".

![actions2](https://cloud.githubusercontent.com/assets/1213027/23067578/f9d1dff2-f4ed-11e6-8019-c0bb460876a3.png)

**Comment by trang** [comment]
Similarly to #1400, there was a string not displayed. The title was always "Action" but above the dropdown, there should be a text "Show translations".
