### ISSUE TITLE
Cannot add Chinese sentences when 'AutoTranscriptions.enable' is 'true'

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1434]
Reported by [verdastelo9604 on the Wall](https://tatoeba.org/eng/wall/show_message/28128#message_28128):

> A problem appears, my sentence can't be uploaded when I click "submit translation", the page is just like nothing has happened. I'm using Windows 10, browsers are Firefox and Opera.

...

> I wanted to translate English to Chinese, and when I tried to translate Esperanto to Chinese, the problem also appears.

----

I tested on the dev website and couldn't add a translation or a new sentence in Chinese. I changed the config in `core.php`, and set `AutoTranscriptions.enabled` to `false`. I was then able to add Chinese sentences.

Currently the config for AutoTranscriptions both on dev and prod is set to false.

**Comment by jiru** [comment]
I tried to set AutoTranscriptions to true on dev and I can’t reproduce the problem. It just works fine.

**Comment by jiru** [comment]
However I think I can reproduce the problem if I shut down sinoparserd while AutoTranscriptions is set to true.

**Comment by jiru** [comment]
I turned on `AutoTranscriptions.enabled` on prod and it’s working fine (as long as sinoparserd doesn’t stop).
