### ISSUE TITLE
Flags missing on "someone's contributions" or "latest contributions

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1440]
Steps to reproduce:

1- Visit anybody's profile and click over "contributions" - https://tatoeba.org/eng/contributions/of_user/Berkay 
2- A list of sentences will be displayed, but not some flags will appear as "?" (unknown language).
3- Click over a sentence. It will display the language of the sentence.

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/23166529/bb3378f2-f81f-11e6-8b3e-0f77f9973789.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/23166530/bb36aab8-f81f-11e6-87a5-f87b8af2a5e3.png)

--
Edit
--

I've also find this bug while browsing [https://tatoeba.org/eng/contributions/index] . It seems that if there are different languages, it display some as they are and others as [?] (Unknown sentence)

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/23180704/05f7f74c-f851-11e6-97b8-939bab91d7c0.png)

**Comment by trang** [comment]
There shouldn't be a flag at all, actually.

We could consider adding flags for logs of type "link", but that would be an enhancement.

**Comment by Guybrush88** [comment]
Aiji proposed this solution on the wall:

> Following my previous message on super important interface improvements, I was looking at the contributions page. When the contribution is an addition, a modification or a deletion (green, yellow, red), the sentence and the flag of the language are displayed. But for linking and unlinking (blue and orange), the unknown flag is displayed, showing an interrogation point, suggesting that something is unclear or unknown.
> Here are two other alternatives:
> display the flags of the concerned sentences, for example if a German sentence is linked to a Japanese sentence, display GermanFlag => JapaneseFlag
> simply delete this flag for blue and orange contributions.

https://tatoeba.org/ita/wall/show_message/29570#message_29570

**Comment by trang** [comment]
To clarify: the solution we're going for is to simply delete this flag for blue and orange contributions.
