### ISSUE TITLE
Search engine doesn't index all the sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1443]
This seems to be a problem mostly for English. I have not seen this problem for other languages but it's possible other languages also have this problem.

CK reported a sentence that was added 14 days ago but cannot be found:
- [sentence #5837903](https://tatoeba.org/eng/sentences/show/5837903)
- [search for "I thought Tom wouldn't be here"](https://tatoeba.org/eng/sentences/search?query=%28I+thought+Tom+wouldn%27t+be+here%29&from=eng&to=und) (note: there is one result, but it's not the same sentence)

OsoHombre reported that his older sentences cannot be found:
https://tatoeba.org/eng/wall/show_message/28216#message_28216
I tried to search some of the first English sentences he added and they indeed cannot be found.
There is no problem with his Arabic sentences.

When [searching for all sentences in English](https://tatoeba.org/eng/sentences/search?query=&from=eng&to=und&orphans=&unapproved=&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words) the count says "out of 646447 sentences". But [the stats](https://tatoeba.org/eng/stats/sentences_by_language) say there are 665744 sentences in English. That's around 20k sentences missing.

**Comment by trang** [comment]
Following errors are happening during the indexation:
```
ERROR: index 'eng_main_index': sql_range_query: Incorrect key file for table '/tmp/#sql_aa6_2.MYI'; try to repair it (DSN=mysql://tatouser:***@localhost:3306/tatoeba_prod).
total 0 docs, 0 bytes
total 339.932 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'jpn_main_index'...
ERROR: index 'jpn_main_index': sql_range_query: Incorrect key file for table '/tmp/#sql_aa6_5.MYI'; try to repair it (DSN=mysql://tatouser:***@localhost:3306/tatoeba_prod).
total 0 docs, 0 bytes
total 150.060 sec, 0 bytes/sec, 0.00 docs/sec
```

So the Japanese sentences are affected too, but it's not really noticeable since there's not much activity in Japanese.

**Comment by trang** [comment]
* http://stackoverflow.com/questions/4746636/thinking-sphinx-error-while-indexing
* http://stackoverflow.com/questions/19003106/mysql-error-126-incorrect-key-file-for-table

**Comment by jiru** [comment]
Maybe try decreasing [`sql_range_step`](http://sphinxsearch.com/docs/current.html#conf-sql-range-step) a bit in the sphinx config file. It should reduce the size of MySQL temporary tables during indexation.

**Comment by trang** [comment]
Thanks @jiru, it works for `sql_range_step = 100000`.

For some reason it doesn't work for Japanese, but works for English at 200000.
