### ISSUE TITLE
Search keywords are not highlighted with the new design of the sentence components

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1444]
## The problem

Search keywords are not highlighted when not logged in.

### Not Logged In
![not logged in](https://cloud.githubusercontent.com/assets/7934273/23287241/80464f5a-fa7f-11e6-97b7-cb2e7775dd1b.png)

### Logged In
![logged in](https://cloud.githubusercontent.com/assets/7934273/23287243/8427d972-fa7f-11e6-8e8e-f77198687a7c.png)

### URL

https://tatoeba.org/eng/sentences/search?query=%22%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%80%82%22+&from=jpn&to=und&orphans=no&unapproved=no&user=&tags=&list=650&has_audio=&trans_filter=limit&trans_to=und&trans_link=direct&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

**Comment by ckjpn** [comment]
Perhaps this is not a "logged in" and "not logged in" problem.

Logged-in members with the following setting might be getting the same results.

"Display a link to expand/collapse translations when there are too many translations."

**Comment by trang** [comment]
It has to do with the new design of the sentence components, the new design doesn't handle the highlight.

**Comment by Guybrush88** [comment]
![highlight bug](https://user-images.githubusercontent.com/1702194/47609528-a7a26500-da40-11e8-823c-7f8291e33aae.png)

I'm still reproducing it under Ubuntu 18.10 with Firefox 63.0

**Comment by trang** [comment]
This problem may be an issue specific to the dev website. I've searched for `=Halloween` on both dev and main website:
- on the dev website, there is no highlight with the old design
- on the main website, the highlight works fine with the old design

It seems that for some searches, Sphinx crashes. This error appears at the top of the page for `=Halloween`:

> Notice (1024): Search query failed: connection to localhost:9312 failed (errno=111, msg=Connection refused) [APP/Model/Behavior/SphinxBehavior.php, line 116]

It doesn't appear when searching `random` or `word`.

I'll assume things will work fine on the main website.
