### ISSUE TITLE
English text on audio/of/ needs to be corrected.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1448]
Reported on the Wall 22 days ago.

https://tatoeba.org/eng/wall/show_message/28071#message_28071

![screen shot 2017-03-09 at 09 09 35](https://cloud.githubusercontent.com/assets/7934273/23729991/52b8e722-04a8-11e7-80bd-105d0faf87bc.png)

**Comment by alanfgh** [comment]
This has already been reported in #1426 (first item).

**Comment by ckjpn** [comment]
OK.  I'll delete my Wall comment since it's not needed anymore.
