### ISSUE TITLE
Changing Ratings Requires a Page Reload

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1449]
## The Problem.

This didn't used to be the case, but now in order to change ratings, one needs to click to remove the old rating, then reload the page, then click to add the new rating.

Reported on the Wall.

https://tatoeba.org/eng/wall/show_message/28175#message_28175

![screen shot 2017-03-09 at 23 17 20](https://cloud.githubusercontent.com/assets/7934273/23754035/e7763362-051e-11e7-94f7-19ad95007802.png)

**Comment by ckjpn** [comment]
Reported again ....

https://tatoeba.org/eng/wall/show_message/28354#message_28354

![screen shot 2017-03-09 at 23 21 15](https://cloud.githubusercontent.com/assets/7934273/23754108/32896216-051f-11e7-8e24-c529170ae6c2.png)

**Comment by trang** [comment]
Duplicate: #1543
