### ISSUE TITLE
Change flag for Ingrian (izh)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1454]
**The problem**
People tend to associate [Izhorians](https://en.wikipedia.org/wiki/Izhorians) and [Ingrians](https://en.wikipedia.org/wiki/Ingrian_Finns) peoples. However, Izhorians speak Ingrian (also called Izhorian) language, but Ingrians speak Finnish. That makes the actual icon wrong.

The correct icon would be https://s24.postimg.org/afp05mo6d/IZH.png

![izh](https://cloud.githubusercontent.com/assets/7658430/23988320/7a4158e2-0a0c-11e7-838d-429331d8afd7.png)

**Comment by trang** [comment]
@RyckRichards, before I merge this, is there any discussion on the Wall related to this issue? Or was this a request by private message? 

It'd be nice to know who requested/reported the problem :)

**Comment by RyckRichards** [comment]
@trang by private message. @cueyayotl has reported what the user [Sikmir](https://tatoeba.org/eng/user/profile/sikmir) noticed - which he agrees on.
