### ISSUE TITLE
typing "tatoeba.org" into browser URL bar brings user to http login address, not https

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1457]
See [Wall thread started by Hybrid](https://tatoeba.org/eng/wall/show_message/28353#message_28353).

I was able to reproduce this but no longer can. I suspect that there was an instance of the old http://tatoeba.org/eng/users/login URL in the list of recently visited sites that Firefox was keeping, and after I visited the https site enough times, it drove out the old one. However, I was able to get a screenshot on one of the occasions that I did reproduce it.

Reproduction steps, on Firefox:
(1) Log out of Tatoeba.
(2) Type "tatoeba.org" into the URL bar.
(3) You are brought to a login screen. If you click on the warning lock icon, you see a dialog that looks like this:

![login_not_secure](https://cloud.githubusercontent.com/assets/1213027/24197200/2380b320-0ed7-11e7-8159-1f54c8c405f5.png)

Perhaps we can add a mapping from the http login URL to the https login URL to avoid this.

**Comment by trang** [comment]
This shouldn't be happening anymore with our current setup.

```
ppjet@caska ~ % curl -IL http://tatoeba.org
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3
Date: Sun, 27 May 2018 12:19:15 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://tatoeba.org/

HTTP/2 301 
server: nginx/1.10.3
date: Sun, 27 May 2018 12:19:15 GMT
content-type: text/html; charset=UTF-8
location: https://tatoeba.org/eng/
strict-transport-security: max-age=15768000

HTTP/2 200 
server: nginx/1.10.3
date: Sun, 27 May 2018 12:19:16 GMT
content-type: text/html; charset=UTF-8
content-length: 47900
set-cookie: CAKEPHP=0osgh7c4f21kmtj13cqbrtb4h1; expires=Sun, 27-May-2018 14:19:16 GMT; Max-Age=7200; path=/; secure; HttpOnly
set-cookie: CakeCookie[interfaceLanguage]=eng; expires=Wed, 27-Jun-2018 12:19:16 GMT; Max-Age=2678400; path=/; domain=tatoeba.org
strict-transport-security: max-age=15768000
```
