### ISSUE TITLE
Make it possible to rate sentences OK and add to a list when browsing "my comments."

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1459]
## The Problem

When browsing ["my commets"!](https://tatoeba.org/eng/sentence_comments/of_user/CK/page:8) it's not possible to easily add OK ratings or add sentences to a list, without clicking to each sentence's page.  It would be nice if browsing "my comments" had the same or similar user interface as ["browse by language"](https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/indifferent).

Perhaps others don't go back and check to see if sentences have been corrected after leaving comments.  If that's the case, then this enhancement would perhaps be a low priority.

## Screenshots

![screen shot 2017-03-22 at 22 52 35](https://cloud.githubusercontent.com/assets/7934273/24201643/05a0f72a-0f54-11e7-8c32-24918b94afe5.png)

**Comment by trang** [comment]
Note that we have the "Outdated ratings" feature. I don't think it's worth cluttering the comments just to be able to fix a rating. A better approach would be to make it easy to change the ratings in the "Outdated ratings" page.

**Comment by agrodet** [comment]
I wonder if something like the following would help people to update their outdated reviews. It could be displayed only on the "outdated reviews" page, or more generally on all category pages, although I don't see the use case where one user would modify an up-to-date review from these pages.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/42261966/78977560-45192800-7b53-11ea-965c-95323cef8d16.png">

**Comment by ckjpn** [comment]
That would be great.

My work around has been to go to the outdated page(s) download them all, then filter the HTML to get the sentence numbers.  After that, using the downloaded sentences, I grab every sentence in that file that matches the sentences, and proofread them again, then send the proper URL to the website to update my rating to OK or remove the sentence from my List 907.

It would be less time-consuming to do it that way agrodet suggests.  It would be easier to just change them all directly as he suggests.

**Comment by agrodet** [comment]
Among other redesign on the review pages, I'm working on implementing my screenshot above. However, I'm facing a technical difficulty. @trang I've read your recent code and commits about reviews but I can't figure out why the sentence's `current_user_review` is not set to its correct value on the review page. It's always null. `$this->users_sentences` of the `_getCurrentUserReview` method is null. It works properly on other page so I guess I'm missing some elementary thing here. I'd be very happy if you could give me a hand :)

**Comment by AndiPersti** [comment]
Why do you need the `current_user_review` property from a `Sentence` entity when you have already the `correctness` property of a `UsersSentences` entity?

`$this->users_sentences` is `null` because `$this` refers to a `Sentence` entity and thus will only have a `users_sentences` property if you use the `Sentences` model with a `UsersSentences` association.
But on the review pages your main model is `UsersSentences` and `Sentences` is associated with it (i.e. it's the other way around). So a `UsersSentences` entity will have a `sentence` property instead.

**Comment by agrodet** [comment]
I don't need it. I asked because I didn't get it. Thanks for your explanation, I'll check later :)

**Comment by AndiPersti** [comment]
@ckjpn We have implemented [agrodet's suggestion](https://github.com/Tatoeba/tatoeba2/issues/1459#issuecomment-611944347) on the Reviews page so can this issue be closed?

**Comment by trang** [comment]
I'll go ahead and close this. CK had agreed with the design in reply to the design suggestion. And we're anyway not going to add the review buttons in the comments. If there's another use case that needs to be addressed, then a new issue should be opened 🙂
