### ISSUE TITLE
It's hard to proofread long sentences on page to add sentences

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1462]
The problem

Whenever we want to post a new sentence on https://tatoeba.org/eng/sentences/add, the corresponding field "gets" too small which makes kinda hard and kinda troublesome to proofread it since we'd have to move the cursor

How the sentence likes before posting

![hard to proofread before posting](https://cloud.githubusercontent.com/assets/7658430/24333005/11a63e4c-1227-11e7-88d6-59bc4ca1d57b.png)

How the sentence likes after posting

![hard to proofread posted](https://cloud.githubusercontent.com/assets/7658430/24333007/23568818-1227-11e7-9b5b-bee7d688c9f9.png)

The same field to translate sentences works perfectly since it fits to the "sentence's size":

![translating](https://cloud.githubusercontent.com/assets/7658430/24333040/924398ba-1227-11e7-9e0b-0f9979ce6303.png)

**Comment by RyckRichards** [comment]
I'd like to work on this :)

**Comment by trang** [comment]
@RyckRichards This requires only to change an `<input>` into a `<textarea>`. I'll leave it to you to explore Tatoeba's code and figure out where exactly to change this. If you feel lost in the code, don't hesitate to let us know.

**Comment by RyckRichards** [comment]
Thank you so really much, Trang!
