### ISSUE TITLE
Too much information unnecessary on the screen

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1463]
[Reported by Aiji on the Wall](https://tatoeba.org/eng/wall/show_message/28478#message_28478) 

The problem

> Whenever we browse for pages using the advanced search or clean a search, we see the entire link + the message "was not found on the server". (eg.: '/eng/sentences/search/page:2?query=&from=und&to=und&orphans=no&unapproved=no&user=Alain&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words' was not found on this server.)

A possible solution would to be redirected to the last page we've visited

**Comment by trang** [comment]
This issue a bit unclear. It seems to be about going to a page that is off-limit in the search results but the title says something completely different.

The link to the Wall post is incorrect, so I'm not sure if there was more information about this issue that was not reported here.

Worst case, the problem can be reported again in a new issue. Closing this one.
