### ISSUE TITLE
develop means for editing vocabulary items

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1468]
[Zumley, from the Wall](https://tatoeba.org/eng/wall/show_message/28505#message_28505):

> I've noticed when looking through the 'Vocabulary that needs sentences' list, there are a couple of items that are misspellings (e.g. "euphenism" and "time-consciuos"). What can be done about these?

I've wondered the same thing myself.

**Comment by trang** [comment]
Duplicate #1468
