### ISSUE TITLE
When using "Add a sentence to this list", it is not possible to then use the buttons (icons) above the sentence to edit.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1474]
These don't work.
* translate
* edit
* add to favorites
* link
* rating

The trash can icon seems to work.

This is the list I am currently using.

https://tatoeba.org/eng/sentences_lists/show/7073

**Comment by jiru** [comment]
I think this issue has been solved already. Can you confirm it’s working for you as well?

**Comment by ckjpn** [comment]
None of the buttons above the sentence work, after submitting a new sentence directly to a list.

<img width="718" alt="screen shot 2018-07-05 at 7 54 00" src="https://user-images.githubusercontent.com/7934273/42295790-f4b94cea-8028-11e8-9aae-7fd689127401.png">

**Comment by ckjpn** [comment]
Follow up....

None of the buttons works for the first sentence added, but after adding one sentence, I could use the buttons on both of the sentences.

<img width="715" alt="screen shot 2018-07-05 at 7 58 33" src="https://user-images.githubusercontent.com/7934273/42295819-5b20a550-8029-11e8-84eb-4e1732fc945f.png">

**Comment by jiru** [comment]
Thank you for reporting this bug. It’s should be fixed on dev.tatoeba.org already.
