### ISSUE TITLE
Adding vocabulary items is not possible

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1476]
As reported by sundown (https://tatoeba.org/ita/user/profile/sundown) on the Wall:

> I'm unable to add vocabulary (endlessly spinning page-load icon). Anyone else, just me?

https://tatoeba.org/ita/wall/show_message/28284#message_28284

I was able to reproduce this.

This is the related URL: https://tatoeba.org/ita/vocabulary/add

**Comment by trang** [comment]
Can't reproduce this anymore.

**Comment by Guybrush88** [comment]
this feature now works
