### ISSUE TITLE
Autodetection of languages stopped working

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1479]
When adding a sentence using the autodetection of languages feature, the sentence appears flagged as "unknown language", instead of the proper language, since the autodetection doesn't work anymore.

**Comment by jiru** [comment]
I fixed the problem by running `mv /etc/ngram.db /etc/ngrams.db` and restarting the daemon.

**Comment by trang** [comment]
Oh nice :D I wanted to look into regenerating the ngrams, but they were already generated... Just not with the right name.
