### ISSUE TITLE
Autocompletion of tags not working anymore

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1481]
When trying to type a tag to a sentence, you don't get the autocompletion anymore, so you have to type the whole tag without any suggestion appearing.

Probably related to #1480

**Comment by jiru** [comment]
I can’t reproduce this problem.
Guybrush88, can you confirm the problem is solved for you?

**Comment by Guybrush88** [comment]
yes, it is solved for me now
