### ISSUE TITLE
Adding sentences to lists is not possible

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1482]
I just tried to add this sentence: https://tatoeba.org/ita/sentences/show/6163181 to this newly created list: https://tatoeba.org/ita/sentences_lists/show/7149 because I wanted to try to reproduce bug #1474, but this wasn't possible, because it wasn't possible to add the sentence to the list.
When choosing the list where to add the sentence (it is possible to choose a list from a drop-down menu with all the possible lists where to add a sentence), the rotating loading icon appears, but it keeps on rotating and it doesn't appear, and the sentence isn't added to the list.
I also refreshed the sentence's page and opened the list's page to check if the sentence was actually added to the list, but it wasn't there, so the list was still empty.

**Comment by trang** [comment]
@Guybrush88 I'm not able to reproduce this. Is this still a problem?

**Comment by Guybrush88** [comment]
this feature now works
