### ISSUE TITLE
Strange behavior with the "List of all members"

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1485]
1) [nimfeo](https://tatoeba.org/eng/user/profile/nimfeo) who is a corpus maintainer in Tatoeba, doesn't appear in the [list of members](https://tatoeba.org/eng/users/all).

2) Swift, duran, Silja (maybe others) appear on the first page, and again on the second page.

**Comment by ckjpn** [comment]
I don't know if this is related, but at one time the default sort for this list was status and then by date joined (or perhaps member's ID).

It's not that way now.  Sysko is at the bottom of the admins, but previously was 2nd after TRANG.

https://tatoeba.org/eng/users/all
