### ISSUE TITLE
Don't show the duplicate-merging scripts comments on "comments on my sentences" and on the "latest comments" feed.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1488]
Regression.

I'm fairly certain that before the crash we didn't have to see all the comments by Horus on our "comments on my sentences" and on "latest comments".

https://tatoeba.org/eng/sentence_comments/on_sentences_of_user/CK

https://tatoeba.org/eng/sentence_comments/index

Current Screenshot....

<img width="699" alt="screen shot 2017-07-30 at 3 18 47 pm" src="https://user-images.githubusercontent.com/7934273/28751157-4700ea66-753b-11e7-82b9-398434532946.png">

**Comment by Ppjet6** [comment]
Duplicate/Related to #1483.

**Comment by ckjpn** [comment]
What this report is about is not specifically about the duplicate comments, but the fact that comments of Horus show up on our "comments on my sentences" and on "latest comments" feeds.  At one time, I fairly certain those comments were eliminated from both of those feeds to remove the unneeded "clutter."

**Comment by trang** [comment]
This is fixed by setting the `Bots.userIds` in Config/core.php file:
https://github.com/Tatoeba/tatoeba2/blob/dev/app/Config/core.php.template#L504
