### ISSUE TITLE
The code preventing submissions of duplicates isn't working properly

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1495]
## The Problem

It's now possible to contribute the exact same text more than once.  This didn't use to be the case.

## Screenshot

Here's a screenshot taken about 04:00 UTC of https://tatoeba.org/eng/contributions/latest

<img width="721" alt="screen shot 2017-08-27 at 1 08 06 pm" src="https://user-images.githubusercontent.com/7934273/29747108-84d93574-8b29-11e7-99d9-84774a70b2eb.png">

## Note

I also noticed the problem a couple of weeks ago.

## Some more examples
Perhaps some of these have been edited since, so this might be related to the bug report about the duplicate-merging script.

6203012 -- Who else knows about this? -- Hybrid
3370677 -- Who else knows about this? -- CK

6173350 -- The situation is worse than we thought. -- sundown
6015599 -- The situation is worse than we thought. -- AlanF_US

6176234 -- That's enough. -- sundown
433680 -- That's enough. -- CK

6176226 -- Thanks to you. -- sundown
5988830 -- Thanks to you. -- Amgaray

6014706 -- She was wearing a red bathing suit. -- AlanF_US
1442116 -- She was wearing a red bathing suit. -- CK

6174648 -- Is it safe in there? -- OsoHombre
3238961 -- Is it safe in there? -- CK

6195795 -- I'm tired. -- ksolina
1705 -- I'm tired. -- brauliobezerra

6195893 -- I'm out of ideas. -- maaster
2549307 -- I'm out of ideas. -- CK

6195807 -- I'd rather be poor than rich. -- ksolina
708202 -- I'd rather be poor than rich. -- papabear

6177777 -- I won't leave you. -- SofiaDomingues
2271973 -- I won't leave you. -- CK

6171137 -- He gave blood in order to save his sister. -- RobinvanderVliet
5893861 -- He gave blood in order to save his sister. -- zorgzikhnit

6195797 -- Empty your pockets! -- ksolina
1911882 -- Empty your pockets! -- Spamster

6207494 -- Do you have a computer? -- sundown
5961963 -- Do you have a computer? -- stagos

5853896 -- Apes are intelligent. -- Open
325998 -- Apes are intelligent. -- CK

**Comment by trang** [comment]
This should be fixed now. 

The problem was that we rely on the `hash` column of the `sentences` table to detect duplicates, and the value was empty for many sentences (sentence that were lost and recovered from the CSV files).

I ran these queries to update the has value:
```
UPDATE sentences SET hash=LOWER(CONV(murmur_hash_v3(CONCAT(lang, text), 0), 10, 32));
UPDATE sentences SET hash=LOWER(CONV(murmur_hash_v3(text, 0), 10, 32)) WHERE lang is NULL;
```
Taken from https://github.com/Tatoeba/tatoeba2/blob/5edbe2b2b95fd944504beeff4d97cec45fcb0203/docs/database/updates/2016-09-11.sql

**Comment by ckjpn** [comment]
It doesn't seem to be fixed.

Someone just contributed a duplicate of an existing sentence.
I linked them together.

https://tatoeba.org/eng/sentences/show/6368958

![screen shot 2017-10-07 at 11 06 55](https://user-images.githubusercontent.com/7934273/31303844-d85b4868-ab4f-11e7-9263-45be47e97afe.png)

**Comment by ckjpn** [comment]
Here's another recent example of this not working.

https://tatoeba.org/eng/sentences/show/6367084
![screen shot 2017-10-07 at 13 02 53](https://user-images.githubusercontent.com/7934273/31304611-0972a0a8-ab60-11e7-974d-84637f759baf.png)

**Comment by ckjpn** [comment]
And another recent example.....

https://tatoeba.org/eng/sentences/show/6365959
![screen shot 2017-10-07 at 13 19 17](https://user-images.githubusercontent.com/7934273/31304690-3582593e-ab62-11e7-86f8-75d083f90b2e.png)

**Comment by trang** [comment]
@ckjpn The cases you mentioned were sentences that were modified (the text was modified, or the language was modified).

The duplicate detection will work only on sentence creation.

**Comment by ckjpn** [comment]
I wonder about that.  Hybrid doesn't usually contribute sentences with the wrong flag.
The logs show now change after he added this one.


https://tatoeba.org/eng/sentences/show/6375070



![screen shot 2017-10-11 at 10 56 30](https://user-images.githubusercontent.com/7934273/31418793-1b3590fa-ae73-11e7-87cf-1835ceebe3d6.png)

**Comment by ckjpn** [comment]
I suggest re-opening this issue.

Hybrid just contributed the same sentence twice.

https://tatoeba.org/eng/sentences/show/6377786

![screen shot 2017-10-12 at 11 28 32](https://user-images.githubusercontent.com/7934273/31476338-ddb0d8a6-af40-11e7-94b6-dcf444269b89.png)

**Comment by trang** [comment]
Indeed the second sentence shouldn't have been added.

I couldn't re-submit this sentence though: https://screenshots.firefoxusercontent.com/images/379c3b38-c4f6-4930-b217-cbb586668e52.png

It's properly detected as duplicate... So not sure what's happening.

**Comment by halfdan** [comment]
It's submitted by the same person. I'm guessing the timestamps are almost the same and this is a race condition. Transactions or unique constraints on the right datatables would probably help here.

**Comment by ckjpn** [comment]
These are duplicates since the last export in the sentences.csv file 2017-10-21 06:01

6381184	rus	Таможенное управление Татарстана закупит имитатор запаха долларов США.
6381185	rus	Таможенное управление Татарстана закупит имитатор запаха долларов США.
6381209	eng	Get out of the parking lot or I'll call the police for you.
6381210	eng	Please stop screaming.
6381211	eng	Get out of the parking lot or I'll call the police for you.
6381212	eng	Please stop screaming.
6381213	eng	Please stop screaming.
6381235	tur	Tom bana hasta hissettiğini söyledi.
6381236	tur	Tom bana hasta hissettiğini söyledi.
6381250	eng	Police had reasons to suspect Sami.
6381252	eng	Police had reasons to suspect Sami.
6381253	eng	Police arrested Layla for prostitution several times.
6381255	eng	Police arrested Layla for prostitution several times.
6381256	eng	Police had reasons to suspect Sami.
6381300	eng	There was a romantic relationship between Sami and Layla.
6381302	eng	There was a romantic relationship between Sami and Layla.
6381569	eng	No homework, no computer tonight.
6381571	eng	No homework, no computer tonight.
6381572	eng	Sami kept guard.
6381574	eng	Sami kept guard.
6381576	eng	Sami kept guard.
6381577	eng	If you don't finish your soup, there will be no TV tonight.
6381580	eng	If you don't finish your soup, there will be no TV tonight.
6384989	eng	Safety first!
6384994	eng	Safety first!
6385485	eng	I'm sick and tired of this house.
6385486	eng	I'm sick and tired of this house.
6385682	ita	Non ci vediamo da cinque anni.
6385683	ita	Non ci vediamo da cinque anni.
6386191	eng	Sami built a shopping mall in Cairo.
6386193	eng	Sami built a shopping mall in Cairo.
6386194	eng	Sami built a shopping mall in Cairo.
6386195	eng	Sami built a shopping mall in Cairo.
6386372	tur	Tom'un köpeği dostça görünüyordu.
6386373	tur	Tom'un köpeği dostça görünüyordu.
6388831	ita	Mi sono alzato tardi.
6388926	ita	MI sono alzato tardi.
6389310	swe	Jag har ingen aning.
6389311	swe	Jag har ingen aning.
6389406	swe	Det går ett rykte att Mary gillar Tom.
6389407	swe	Det går ett rykte att Mary gillar Tom.
6389757	war	Pruybahi pagkanhi hin isakto nga oras buwas.
6389758	war	Pruybahi pagkanhi hin isakto nga oras buwas.

**Comment by trang** [comment]
Re-closing this. Doesn't happen so often that we need to spend more time on it.
