### ISSUE TITLE
Sentences are not indexed

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1496]
After the migration to the new server, I just noticed a regression: some sentences are not indexed anymore, even if they were added around a week ago, for example: https://tatoeba.org/ita/sentences/show/6203685

I noticed this issue from this custom advanced search: https://tatoeba.org/ita/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=ch&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

where sentences with Italian translations (both direct and indirect) are excluded, but, in fact, sentences translated into Italian last week re-appeared in the query because they are not indexed anymore (I'm pretty sure they were indexed before the migration to the new server).

Update: I just saw that also sentences from around 25 days ago are not indexed, like this one: https://tatoeba.org/ita/sentences/show/6172631

**Comment by Ppjet6** [comment]
The scripts were failing, I installed the missing package and they seem to be working now, can you confirm?

**Comment by Guybrush88** [comment]
This is now fixed. I'm closing this ticket.
