### ISSUE TITLE
Sometimes the advanced search gives an error

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1497]
Occasionally, when using a custom query, I get this error message even if the requested page exists: `Error: The requested address '/ita/sentences/search/page:2?query=&from=eng&to=und&orphans=no&unapproved=no&user=ch&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random' was not found on this server.`

A quick fix for this (at least for me) is to wait a few seconds and then reload the page.

This is the custom query I wanted to open: https://tatoeba.org/ita/sentences/search/page:2?query=&from=eng&to=und&orphans=no&unapproved=no&user=ch&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

Also other pages of the same query give the same error sometimes, and the error message shows the relative page number.

**Comment by Guybrush88** [comment]
as it is reported also by other people on the Wall (https://tatoeba.org/ita/wall/show_message/28391#message_28391), also this error message appears: "An error occurred while performing the search. If the problem persists, please let us know.". I'm getting this error message too

**Comment by Ppjet6** [comment]
I've updated the package, does this still happen?

**Comment by Guybrush88** [comment]
it doesn't happen anymore

**Comment by Ppjet6** [comment]
Thanks, closing for now, will reopen if it reappears.
