### ISSUE TITLE
Search terms reappear after a page refresh when cleared

### ISSUE THREAD

**Issue by Ppjet6** [Tatoeba/tatoeba2#1498]
### Steps to reproduce

- Search something and submit
- Clear the search with the "X" icon
- Refresh the page (or go somewhere else on the website)

### What happens

The searched words reappear in the input field.

### What do you expect?

The input field shouldn't be repopulated.

Probably what contains the data is never cleared.

**Comment by jiru** [comment]
It’s not a bug, it’s a [feature](https://github.com/Tatoeba/tatoeba2/blob/1e5435a3a5f91376fd4d4a19189adb4d80a2382c/app/Controller/SentencesController.php#L621).

**Comment by Ppjet6** [comment]
Sarcasm? :-°

When I click on a "clear" button I would expect a field to be cleared. If we don't want to clear it maybe we can remove that button instead?

**Comment by trang** [comment]
I think perhaps @jiru missed out on the part where you click on "X".

If you search something and just refresh the page, the search string should stay there indeed.
If you reset the input by clicking on the "X", I agree the search should remain empty.

From my tests though, the search does remain empty after refreshing. It reappears only when navigating to another page.

**Comment by trang** [comment]
I remember the topic as well. I can't find the Wall thread either but let's go ahead and remove this feature.

**Comment by jiru** [comment]
Whoops, now the search query is cleared on the results page too.
