### ISSUE TITLE
It is not possible to reply to comments

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1499]
As reported by artoska on the Wall:

> The request has been black-holed
> 
> Error: The requested address '/eng/sentence_comments/save' was not found on this server.
> 
> This page comes up when I try to answer to the comment on my sentences. It is possible that you already know about it as I haven't been active here on Tatoeba.

https://tatoeba.org/ita/wall/show_message/28412#message_28412

**Comment by trang** [comment]
@Guybrush88 Can you find me a specific sentence where this problem happens? Can't reproduce for now. I tried to post comments on two of my sentences, and it worked fine.

**Comment by Guybrush88** [comment]
I wasn't able to reproduce it either

**Comment by trang** [comment]
I'm going to close this then.
