### ISSUE TITLE
Request for Gujarati/English IPA converter

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#15]
Initially requested asked by "ken p" via e-mail to Team Tatoeba. He included the following example:
what is your name?...............English
तुम्हारा नाम क्या है?......................Translation into Hindi
Tumhārā nāma kyā hai?........Transliteration of Hindi
તમારું નામ શું છે?...........................Translation into Gujarati
Tamāruṁ nāma śuṁ chē?....Transliteration of Gujarati

**Comment by jiru** [comment]
Closing because it doesn’t provide enough transcription/sentence pairs for testing. Anyone is welcome to open a new issues as long as he or she follow [this guide](http://en.wiki.tatoeba.org/articles/show/new-transcription-request).
