### ISSUE TITLE
The number of sentences per language is wrong

### ISSUE THREAD

**Issue by denikoTatoeba** [Tatoeba/tatoeba2#1505]
As of now, according to this stat:

https://tatoeba.org/eng/stats/sentences_by_language

there are supposedly about 727,000 English sentences, but if you actually click on "English":

https://tatoeba.org/eng/sentences/show_all_in/eng/none/none/indifferent

you can  see there are more than 768,000 sentences.

This is true for any fairly active language. A few more examples. Turkish has about 536,000 sentences according to the main statistics, but in reality there are more then 573,000.

Ukrainian has about 54,000 sentences according to the main statistics, but in reality there are more then 74,000 sentences.

This discrepancy appeared after the recent crash in spring.

**Comment by trang** [comment]
@denikoTatoeba Should be good now :)
