### ISSUE TITLE
Missing activity timelines after the last crash

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1507]
I noticed that, after the last crash, the activity timelines from February 20 to June 25 2017 (dates included) are completely missing.
The related URLs with missing data:
https://tatoeba.org/ita/contributions/activity_timeline/2017/02
https://tatoeba.org/ita/contributions/activity_timeline/2017/03
https://tatoeba.org/ita/contributions/activity_timeline/2017/04
https://tatoeba.org/ita/contributions/activity_timeline/2017/05
https://tatoeba.org/ita/contributions/activity_timeline/2017/06

**Comment by ckjpn** [comment]
If that data isn't available on tatoeba.org, I have the complete timeline here.

http://tatoeba.ueuo.com/timeline/

**Comment by trang** [comment]
Should fine now.
