### ISSUE TITLE
A few Help pages are missing on tatoeba.org

### ISSUE THREAD

**Issue by mikehenrty** [Tatoeba/tatoeba2#1508]
I'm sorry if this is not the right place to report this.

I notice 3 pages from the help links in the footer return 404 on the main site.
1. Quick Start Guide
1. Tatoeba Wiki
1. FAQ

The error message is something like:
`Error: The requested address '/eng/articles/show/quick-start' was not found on this server.`

Amazing project, btw. Thanks for your work!

**Comment by ckjpn** [comment]
Perhaps until the Tatoeba Wiki is up and running again, someone could grab static copies of the Wiki pages from here.

http://web.archive.org/web/*/http://en.wiki.tatoeba.org/articles/show/main

It looks like they did a grab of the pages on June 6, 2017, which is less than one week before the crash.

And then, upload the pages to tatoeba.org.

If that's too much trouble, minimally it should be easy to replace the current links on tatoeba.org to direct links to web.archive.org's copies of the 3 wiki pages mentioned above.

**Comment by ckjpn** [comment]
This can now be closed.
