### ISSUE TITLE
filter by country

### ISSUE THREAD

**Issue by Troyciv** [Tatoeba/tatoeba2#1511]
I ran into this issue lately because I wanted to play with Brazilian Portuguesse sentences only. I'm sure this issue also applies to other languages.

I couldn't find a satisfying way to filter by country. Brazilian and European Portuguese can differ quite a lot, so I wanted to make sure I only work with Brazilian sentences.

Tags are too inconsistently applied, so this option didn't work.

The sentences themselves don't seem to have a country or region field, at least I couldn't find any

Finally I found out that a lot of contributers add a country to their profile (unfortunately not all). Although this doesn't guarantee that they only add sentences in Brazilian Portuguese, at least it was an option I thought I could work with.

Sadly the website doesn't offer any possibility to filter by owner's country, only by owner.

The offline files were no help either. the detailed_sentences.csv only include the owner but not the owner's country. ~~Also they don't include their proficiency level (I'd like to only use sentences by native speakers).~~

So here I am asking for a way to filter by country. Since Tatoeba doesn't seem to offer an api I'd prefer an offline solution, because I need to batch process the sentences later on.

**Comment by trang** [comment]
The "country" on the user profile is not something that everyone fills up, and is not necessarily a reliable information for linguistic purpose. Someone could be living in Brazil and still add European Portuguese sentences.

Additionally, it is a personal information. I would not be comfortable including it as part of a searchable criteria without the user's consent.

Hence closing this.
