### ISSUE TITLE
Link audio files already on the server to the sentences.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1512]
I've double-checked that these are all online by downloading them.

These are all files that were not shown in the sentences_with_audio.tar.bz2 file last Saturday.

**Comment by ckjpn** [comment]
These were contributed by Tatjana

6091105 - Я регулярно бегаю в парке..mp3
6090552 - У мальчика есть велосипед..mp3
6090542 - У меня есть синий, новый велосипед..mp3
5898015 - Поймайте Тома..mp3
5898014 - Лови Тома..mp3
5898013 - Ловите Тома..mp3
5897716 - Женитесь на мне..mp3
5897162 - Мы поедем..mp3
5897131 - Идите сюда..mp3
5895802 - Приезжайте..mp3
5895801 - Приезжай..mp3
5895797 - Остыньте..mp3
5672436 - Я могу поесть_.mp3
5371208 - Ловите его..mp3
4974080 - Мы попытались..mp3
4974079 - Мы попробовали..mp3
4465130 - Поймай Тома..mp3
4465113 - Кто плавал_.mp3
4356123 - Поднимайтесь!.mp3
4356121 - Поднимайся!.mp3
4311511 - Заходи как-нибудь..mp3
4287059 - Спасите Тома..mp3
4287058 - Спаси Тома..mp3
4214624 - Приходи домой..mp3
3851853 - Встаньте..mp3
3835972 - Сделайте это сейчас..mp3
3297899 - Встань..mp3
3293126 - Приходи скорей!.mp3
3291014 - Пишите мне..mp3
3291009 - Напишите мне!.mp3
3291007 - Напиши мне!.mp3
3257715 - Возвращайтесь!.mp3
3257714 - Возвращайся!.mp3
3255142 - Садитесь здесь..mp3
3224199 - Мы в порядке..mp3
3034396 - Отвечай мне..mp3
3034388 - Отвечайте мне..mp3
3034387 - Ответьте мне..mp3
2973544 - Сядь..mp3
2795780 - Сначала ты..mp3
2787133 - Сядьте здесь..mp3
2787132 - Садитесь сюда..mp3
2787131 - Садись сюда..mp3
2787129 - Сядь здесь..mp3
2779460 - Позвоните домой..mp3
2779459 - Позвони домой..mp3
2512322 - Предупредите Тома..mp3
2501509 - Успокойтесь!.mp3
2497874 - Мы можем идти_.mp3
2465330 - Мне можно идти_.mp3
2437572 - Лови его..mp3
2407636 - Приходите скорее!.mp3
2389114 - Только после Вас..mp3
2060650 - Женись на мне..mp3
2060648 - Воспользуйся этим..mp3
1997565 - Предупреди Тома..mp3
1775429 - Собаки лают..mp3
1564750 - Я могу есть_.mp3
1276168 - Мы согласны..mp3
1259071 - Успокойтесь..mp3
1017101 - Будь здоров!.mp3
804016 - Не спрашивай..mp3
658411 - Кто пришёл_.mp3
630893 - Ответь мне..mp3
576509 - Птицы летают..mp3
444135 - Для чего_.mp3
430575 - Возвращайся домой..mp3
421340 - Выкладывай..mp3


6116925	- An Esperanto sentence.

**Comment by ckjpn** [comment]
[audio contributed by Oblomov.txt](https://github.com/Tatoeba/tatoeba2/files/1386817/audio.contributed.by.Oblomov.txt)

**Comment by ckjpn** [comment]
Audio contributed by bretsky 

5939862 - My new primary care provider is a great doctor!.mp3
5939859 - Bringing up politics can be a conversation stopper..mp3
5939851 - The citizens uprose against the dictatorship..mp3
5939848 - Restrictive practices can be damaging for industries..mp3

**Comment by ckjpn** [comment]
Audio contributed by Ricardo14

4888822 - Estamos cansados..mp3
4626649 - Seja breve..mp3

**Comment by ckjpn** [comment]
Audio contributed by CK

Approximately 19,000.
I'm downloading them now to verify that they are actually on the server.
I'll upload a text file here when I get back to my computer tomorrow.

**Comment by ckjpn** [comment]
Is this terribly difficult to do?
If not, could you please prioritize this issue?

**Comment by ckjpn** [comment]
Is there anything I can do to expedite this issue?

I just checked one of the sentence and notice that it still doesn't have a linked audio file.
https://tatoeba.org/eng/sentences/show/5757460

It there a URL I can send the the server that would allow me to change the "hasaudio" in the database?
If so, I can write a script to send such URLs (download the pages of such URLs).

You can send me the URL in an email message if you don't want to publicly announce such a URL.

ck  --  at -- tatoeba.org

**Comment by trang** [comment]
If this is very urgent for you, as admin, from the UI, you can use the "Audio" section in the sidebar. 

While you may not be able to call a URL like you would usually do for tags for instance, there's surely some browser tools which you can use to automatically go to a list of URL's and fill up a form on each of the pages.

Not ideal, but I won't have time to take care of this before at least next weekend.

**Comment by ckjpn** [comment]
I tried creating post forms as follows, but this doesn't seem to work with all sentence IDs.
I assume the the "token" values have to also be changed, but I have no idea what kind of changes would be required.

I get this error message.
The request has been black-holed
Error: The requested address '/eng/sentences/edit_audio' was not found on this server.

```
<base href="https://tatoeba.org" />

<form action="/eng/sentences/edit_audio" id="SentenceEditAudioForm" method="post" accept-charset="utf-8">
    <div style="display:none;">
        <input type="hidden" name="_method" value="POST" />
        <input type="hidden" name="data[_Token][key]" value="06d3812122dcba220d0526035f0a61a653d1cf08cc2d0a89f0725fc2f662d52089895ac04ee140e2c6e9722210bc5d4fb8ced48b6043ade931f54dd9f1cc9860" id="Token1568280228" /></div>
         
    <input type="hidden" name="data[Sentence][id]" value="29009" id="SentenceId" />

    <div class="input radio">
        <input type="radio" name="data[Sentence][hasaudio]" checked="checked" id="SentenceHasaudio1" value="1" /><label for="SentenceHasaudio1">yes</label>
        <input type="radio" name="data[Sentence][hasaudio]" id="SentenceHasaudio0" value="0"  /><label for="SentenceHasaudio0">no</label></div>
    <div class="input text"><label for="SentenceOwnerName">Owner Name</label>
        <input name="data[Sentence][ownerName]" value="CK" type="text" id="SentenceOwnerName" /></div>
    <div class="submit">
        <input type="submit" value="Submit" /></div>
    <div style="display:none;">
        <input type="hidden" name="data[_Token][fields]" value="776b0e257373f05adfe14c80e78d9f4f18f16ebc%3ASentence.id" id="TokenFields839890894" />
        <input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked2060452364" /></div>
</form>
```

**Comment by ckjpn** [comment]
It seems the only way I can mass change all of these via the web interface is to re-upload all the files and use the page designed for adding new files.  Would you like me to do it that way?

It would be a lot less time consuming and use a lost less bandwidth for someone with direct access to the database to do this.

These files have been online since before June 10th without links to them since the crash.

 It would be nice if they could be made accessible by those on tatoeba.org sometime in the near future.

**Comment by ckjpn** [comment]
Please make sure this gets done before Horus is run again.
Otherwise, we might lose some links to audio files.
Remember that Horus will prefer the sentence with a linked audio file and delete the other one if the text is exactly the same.

**Comment by alanfgh** [comment]
When does Horus run these days?

**Comment by ckjpn** [comment]
You can see the last time it rain with this link.

https://tatoeba.org/eng/sentence_comments/of_user/Horus

**Comment by trang** [comment]
@ckjpn Can you provide a CSV file with the list of non-linked audio, formatted this way:

**sentence_id** [tab] **user_id** [tab] **created_date** [tab] **modified_date**

`created_date` and `modified_date` should be the same value, and should be the date when the audio has been uploaded. It doesn't have to be accurate though, you can set it to today's date if you cannot know anymore when the audio was uploaded.

**Comment by ckjpn** [comment]
Can you send me directory listings along with date stamps for the directories involved?

I can grab the dates from there and create such a CSV files for you.

Or, just set all the dates to today's date.  In the future, if people need to know the dates, they can check the directories.

**Comment by trang** [comment]
In this case you can simply provide: **sentence_id** [tab] **user_id**.

**Comment by ckjpn** [comment]
I've generated the files for you.

I generated 2 versions with the same sentence numbers.

sentence numbers. [tab] username

[audio by username.zip](https://github.com/Tatoeba/tatoeba2/files/1465475/audio.by.username.zip)

sentence numbers. [tab] user number

[audio by user number.zip](https://github.com/Tatoeba/tatoeba2/files/1465477/audio.by.user.number.zip)

**Comment by ckjpn** [comment]
ARH just wrote to me that many of his audio files are also unlinked.

I've zipped 2 files together, one has his username in the 2nd field, and the other has his user number in the 2nd field.

[arh-by-username-and-by-usernumber.zip](https://github.com/Tatoeba/tatoeba2/files/1469153/arh-by-username-and-by-usernumber.zip)

There are 3,365 lines in each file.

**Comment by trang** [comment]
@ckjpn this should be fixed now. I'll close this issue after you've confirmed that it's okay.
