### ISSUE TITLE
Transcripts are not available for download.

### ISSUE THREAD

**Issue by Lemmih** [Tatoeba/tatoeba2#1515]
I'm interested in the user-edited transcripts for Chinese sentences but they are not available for download.

Ideally they would be available in the format of: Id [tab] Senence id [tab] Script [tab] Text.

Making this data available would only require a change to 'scripts/weekly_exports.sql' and 'cron/export.sh'. May I go ahead and create a PR for this?

**Comment by trang** [comment]
I'm not sure we actually have a lot of user-edited content there... For Japanese we surely have a bit, for Chinese I'm afraid we won't have anything. But that's just a guess.

Feel free to make a PR for it :)

**Comment by Lemmih** [comment]
Not many transcriptions yet but they'll come. I've shown lots of sentences to people and they're quite good at spotting when the automatic transcription falls short.

I'll get cracking on that PR.
