### ISSUE TITLE
Sporadic search errors

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1517]
Reported by Alan on the Wall:
https://tatoeba.org/eng/wall/show_message/28689#message_28689

And by by email:

> (1) Just now: a search for "saucer" in English sentences translated to Russian resulted in "The request has been black-holed."
>
> The request has been black-holed
>
> Error: The requested address '/eng/sentences/search?query=saucer&from=eng&to=rus&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=rus&trans_link=direct&trans_user=&trans_orphan=no&trans_unapproved=no&trans_has_audio=&sort=random' was not found on this server.
>
> (2) A few hours ago: Trying to go to the second page of a search that produced four pages of results resulted in a different kind of error. (Sorry, I don't remember what it was.)

DostKaplan also mentioned experiencing many search errors some time ago:
https://tatoeba.org/eng/wall/show_message/28676#message_28676

**Comment by alanfgh** [comment]
Another black-holed request just now:

Error: The requested address '/eng/sentences/search?query=bud&from=eng&to=rus&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=rus&trans_link=direct&trans_user=&trans_orphan=no&trans_unapproved=no&trans_has_audio=&sort=random' was not found on this server.

**Comment by ckjpn** [comment]
My gut-feeling is that this is a "time out" error of some sort.
The only time I've been getting this is when the website is slow.

**Comment by trang** [comment]
I think the search has been more stable since we upgraded to Manticore. I will close this. We anyway don't have much info to figure out what went wrong back then.
