### ISSUE TITLE
Switch from Sphinx to Manticore

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1518]
We were informed some time ago that there's a fork of Sphinx, due to Sphinx not being actively maintained anymore. The fork is called Manticore (https://github.com/manticoresoftware/manticore).

We should switch at some point:
https://manticoresearch.com/2017/10/17/manticore-search-2-4-1-ga-release/

**Comment by manticoresearch** [comment]
Hi. We have made few releases since then adding more functionality and fixing most known bugs. Feel free to contact us via email, our community slack or github in case you have any issue.

Best wishes,
Manticoresearch team

**Comment by jiru** [comment]
Manticore is now running on tatoeba.org and dev.tatoeba.org.

It looks like Manticore is opening even more files than Sphinx and it reaches the 4096 hard limit. So I had to increase the hard limit for the manticore user. We should consider merging some indexes with a lang attribute or something.

I also had to rewrite the ngram_chars and charset_table values and reindex everything.

Some notes about the installation:

```
crontab -e
=> Comment out delta & merge indexation

wget https://github.com/manticoresoftware/manticoresearch/releases/download/2.8.2/manticore_2.8.2-190402-4e81114d-release-stemmer.stretch_amd64-bin.deb

dpkg -i ./manticore_2.8.2-190402-4e81114d-release-stemmer.stretch_amd64-bin.deb

=> Answer N

echo "manticore - nofile 6144" > /etc/security/limits.d/manticore.conf

=> logout and login (disconnect and reconnect with ssh)

mv /etc/sphinxsearch/sphinx.conf /etc/sphinxsearch/sphinx.conf.bak
/var/www-prod/bin/cake sphinx_conf > /etc/sphinxsearch/sphinx.conf

/var/www-prod/bin/cake sphinx_indexes update main
/var/www-prod/bin/cake sphinx_indexes update delta

=> Disable search in /var/www-prod/config/app_local.php

systemctl reload php7.0-fpm

systemctl stop sphinxsearch

chown -R manticore:manticore /var/sphinx/
mv /var/sphinx /var/manticore
sed -i 's,/var/sphinx/indices,/var/manticore/indices,g' /var/www-prod/config/app_local.php
php -l /var/www-prod/config/app_local.php

sed -i 's,/var/sphinx/log,/var/log/manticore,g' /var/www-prod/config/app_local.php
php -l /var/www-prod/config/app_local.php
rm -r /var/sphinx/log/

sed -i 's,/var/run/sphinxsearch/searchd.pid,/var/run/manticore/searchd.pid,g' /var/www-prod/config/app_local.php
php -l /var/www-prod/config/app_local.php
rm -r /var/run/sphinxsearch/

sed -i 's,/var/lib/sphinxsearch/data,/var/lib/manticore/data,' /var/www-prod/config/app_local.php
php -l /var/www-prod/config/app_local.php
mv /var/lib/sphinxsearch/data/* /var/lib/manticore/data/
chown manticore:manticore /var/lib/manticore/data/*

systemctl start manticore

=> if it doesn’t start, check error with:
sudo -u manticore /usr/bin/searchd --config /etc/sphinxsearch/sphinx.conf --console
=> problem solved with:
rm /var/lib/manticore/data/*

=> Enable search in /var/www-prod/config/app_local.php

systemctl reload php7.0-fpm

crontab -e
=> Re-enable indexation in crontab

rm ./manticore_2.8.2-190402-4e81114d-release-stemmer.stretch_amd64-bin.deb
rm /etc/sphinxsearch/sphinx.conf.bak
rm /etc/systemd/system/sphinxsearch.service
apt-get remove sphinxsearch
```

**Comment by manticoresearch** [comment]
@jiru Hi. May we put a link to your site on our site? May I also ask you to provide a short case study? If you're ok with that can you please contact me @ sergey@manticoresearch.com or in our public slack (https://slack.manticoresearch.com/ , my nick is snikolaev.manticore) so we can discuss it in more details?

**Comment by trang** [comment]
@manticoresearch Yes feel free to put a link to Tatoeba on your site :) Regarding the case study, I've sent you an email.
