### ISSUE TITLE
The number of total sentences with audio displayed on the /audio/index page is wrong.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1523]
## Problem 1
The number of total sentences with audio displayed on this page is wrong.
https://tatoeba.org/eng/audio/index
Sentences with audio (total 367036)

## Problem 2 (This is related, I think.)

The sentences_with_audio.csv has 367036 lines, but only 367012 unique lines.

These are the lines that are duplicated.

6071550	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6091105	Tatjana	\N	\N
6097586	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6097588	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098735	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098737	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098739	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098741	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098743	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098747	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098747	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098751	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098751	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098753	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098753	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098755	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6098761	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099023	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099024	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099025	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099027	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099031	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099037	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
6099039	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba

**Comment by ckjpn** [comment]
##Problem 3 (This is related, too.)

https://tatoeba.org/eng/audio/of/CK
Audio contributed by CK (total 304751) 
(on 2017-12-09)

The exported file has 304729 unique lines for CK.

**Comment by trang** [comment]
I thought this problem was related to #1547 but it's actually not.

There are actually several audio entries for the same sentence in the database. For sentence 6098747, there are 3 entries, created within 30 sec of each other.

```
MariaDB [tatoeba]> select * from audios where sentence_id = 6098747;
+--------+-------------+---------+----------+---------------------+---------------------+
| id     | sentence_id | user_id | external | created             | modified            |
+--------+-------------+---------+----------+---------------------+---------------------+
| 350692 |     6098747 |    1396 | NULL     | 2017-10-14 08:35:36 | 2017-10-14 08:35:36 |
| 350693 |     6098747 |    1396 | NULL     | 2017-10-14 08:35:57 | 2017-10-14 08:35:57 |
| 350694 |     6098747 |    1396 | NULL     | 2017-10-14 08:36:37 | 2017-10-14 08:36:37 |
+--------+-------------+---------+----------+---------------------+---------------------+
```

I'm not entirely sure how this happens, but I suppose re-uploading audio for a sentence that already has audio will create a new entry?
