### ISSUE TITLE
Deleted sentences can't be removed from Favorites

### ISSUE THREAD

**Issue by denikoTatoeba** [Tatoeba/tatoeba2#1526]
It's easy to reproduce.

1. Contribute a sentence to tatoeba.
2. Add it to your favorites
3. Delete it.

Looks like there's no way to remove it from your favorites after that.

I think creating a permanent solution might  take some time, but in the meantime can someone please remove deleted sentence #6673494 from my favorites?

https://tatoeba.org/eng/favorites/of_user/deniko

**Comment by RobinvanderVliet** [comment]
https://tatoeba.org/eng/favorites/of_user/RobinvanderVliet
I have the same problem.

**Comment by RyckRichards** [comment]
It's a known issue, though.
