### ISSUE TITLE
Kabyle (kab)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1530]
* Language name: https://en.wikipedia.org/wiki/Kabyle_language
* Language info: https://en.wikipedia.org/wiki/Kabyle_language
* ISO 639-3 code: kab
* Public List:https://tatoeba.org/eng/sentences_lists/show/7550
* Icon: https://user-images.githubusercontent.com/7934273/36825712-4e3262ce-1d4c-11e8-9693-73b514aa6359.png
* Requested by: https://tatoeba.org/eng/user/profile/amazigh84

[for tatoeba.org]
CALL add_new_language('kab', 7550);

**Comment by RyckRichards** [comment]
Taking it.

**Comment by trang** [comment]
The addition of this language triggered some passionate discussions so just for the record, related Wall thread here:
https://tatoeba.org/eng/wall/show_message/29440#message_29440
