### ISSUE TITLE
Uab Meto (aoz)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1533]
- Language name: Uab Meto
- Language info: https://en.wikipedia.org/wiki/Uab_Meto_language
- ISO 639-3 code: aoz
- Public List: https://tatoeba.org/eng/sentences_lists/show/7609
- Icon: (Pending)
- Requested by: https://tatoeba.org/eng/user/profile/Rodriguez

[for tatoeba.org]
CALL add_new_language('aoz', 7609);

**Comment by RyckRichards** [comment]
taking it

**Comment by RyckRichards** [comment]
Wouldn't this be a good "language icon"?

> https://en.wikipedia.org/wiki/E...East_Timor.svg

**Comment by cueyayotl** [comment]
I don't think so, as the native language of East Timor is Tetun (tet). Uab Meto is classified as a language of West Timor (which is considered a part of Indonesia). A couple of choices would be either the Indonesian flag with ISO 639-3 code (aoz) or the flag of the province of East Nusa Tenggara (which includes the land of West Timor), with the same "aoz":
https://en.wikipedia.org/wiki/East_Nusa_Tenggara#/media/File:Flag_of_East_Nusa_Tenggara.svg
If none of these are acceptable, then maybe a white flag, with "aoz" written in the color of user Rodriguez's choosing.
Other possible flags include those of independence movements of West Timor, including:
https://orig00.deviantart.net/f0f5/f/2016/059/5/7/flag_of_the_west_timor_independence_movement_by_revinchristianhatol-d9tekul.png
But, I personally don't think it is a good idea to use those flags, as I believe the Tatoeba Project should not involve itself in political issues.

**Comment by RyckRichards** [comment]
Rodriguez asked me to put a white flag with "aoz" written in blue.

**Comment by cueyayotl** [comment]
Very well, I assume this font and this color of blue is OK?
https://i.imgur.com/jRYkSsk.png

**Comment by RyckRichards** [comment]
Perfect!
