### ISSUE TITLE
Old Turkish (otk)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1535]
- Language name: Old Turkish
- Language info: https://en.wikipedia.org/wiki/Old_Turkic_language
- ISO 639-3 code: otk
- Public List: https://tatoeba.org/eng/sentences_lists/show/7679
- Icon: https://i.imgur.com/U1eHghw.png
- Requested by: https://tatoeba.org/eng/user/profile/OsmanliPadisahi

[for tatoeba.org]
CALL add_new_language('otk', 7679);

**Comment by cueyayotl** [comment]
Language icon is from an actual inscription of the word for "Turk" in the Old Turkish script (read from right to left)

**Comment by RyckRichards** [comment]
Taking this.
