### ISSUE TITLE
Manchu (mnc)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1537]
- Language name: Manchu
- Language info: https://en.wikipedia.org/wiki/Manchu_language
- ISO 639-3 code: mnc
- Public List: https://tatoeba.org/eng/sentences_lists/show/7687
- Icon: https://i.imgur.com/aNPubSY.png
- Requested by: https://tatoeba.org/eng/user/profile/Balamax

[for tatoeba.org]
CALL add_new_language('mnc', 7687);

**Comment by RyckRichards** [comment]
taking this.
