### ISSUE TITLE
Kashmiri (kas)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1538]
- Language name: Kashmiri
- Language info: https://en.wikipedia.org/wiki/Kashmiri_language
- ISO 639-3 code: kas
- Public List: https://tatoeba.org/eng/sentences_lists/show/7681
- Icon: https://i.imgur.com/8p3htcb.png
- Requested by: https://tatoeba.org/eng/user/profile/haziqmir

[for tatoeba.org]
CALL add_new_language('kas', 7681);

**Comment by RyckRichards** [comment]
Taking this.

**Comment by sabretou** [comment]
While I am always supportive of languages added to Taoteba, I have a couple of objections in the manner this language was added.

1. The flag used for this language is that of Azad Kashmir, which is the flag of an illegitimate occupation of Indian territory by Pakistan. I cannot in good conscience accept this flag as representing the Kashmiri language. On the contrary, I do not condone using the flag of Jammu & Kashmir either, as it might see similar objections. I believe it would be best to have a neutral flag, or a 'combination' flag like Portuguese does.

2. Why are all the Kashmiri sentences in Roman script? Kashmiri is not officially taught in the Roman script, but in Perso-Arabic and Devanagari scripts.

**Comment by cueyayotl** [comment]
As for #1, we will have to use either a combination flag, or maybe a white flag with the ISO 639-3 code KAS. This will have to be discussed with user haziqmir; maybe send him a message with these concerns, which I find to be very legitimate.

As for #2, I asked him this very question, and this was his reply:

_Hey
Thanks for the reply
The problem with Devanagari is that it’s not used at all in Kashmir, Sharada is unknown although there is an active Unicode proposal for it, and Perso-Arabic, although taught, is not used by any native speakers online. Plus, there is no layout for it so I couldn’t even type it. 
Kashmiri speakers use Latin characters when they need to type Kashmiri online.
Moreover, quite a few minority languages on tatoeba use a particular script when there’s no unified script. I think adding Kashmiri would be a great help, since there’s virtually no work being done to preserve the language online or to even make sure it is used in official contexts by its speakers. 
Thanks._

**Comment by sabretou** [comment]
I will get in touch with haziqmir regarding both of these, thank you for looking into it.

**Comment by sabretou** [comment]
@cueyayotl haziqmir does not seem to be responding to my PM, so I suggest we move forward with a neutral white flag with the ISO code on it.

As for the Roman script, I will concede to the native speaker for now. We'll wait and see what another native speaker of the language has to say about it.
