### ISSUE TITLE
The tag @change may remain for years

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1541]
**The Problem**

There are some sentences that were tagged as @change more than 2 weeks ago (sometimes they were tagged years ago) and they weren't changed or "untagged" even they are correct.

**Possible solution**

Notify the AC, CM or admin who tagged these sentences if they keep tagged more than 2 weeks.

The same for @delete @unlink

**Comment by alanfgh** [comment]
This is not a problem with the code or the database, which is what tickets are generally meant to address. Also, there will always be at least some sentences in that category, and given the size of the backlog, and the limited number of people who can address them, there will often be quite a few. I myself have been going through the English sentences in some of these categories, but it takes a long time.

As you say, you can always feel free to notify someone (the owners of the sentences, or someone who can modify them, or delete tags) to get them to take action. I suggest that we close the ticket.

**Comment by trang** [comment]
There's actually a hidden page for corpus maintainers where they can see sentences that have been tagged `@change` or `@delete` more than two weeks ago.

I'm noticing however that something's broken...
https://tatoeba.org/eng/tags/for_moderators/561/eng

In any case I agree with Alan, this is not an issue we can fix on the technical side. I'm closing this.
