### ISSUE TITLE
Wording on "Audio contributed by ...." page needs changed.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1545]
FROM:

You may not reuse the following audio recordings outside the Tatoeba project, because USERNAME  did not chose any license for them yet.

TO:

You may not reuse the following audio recordings outside the Tatoeba project, because USERNAME has not chosen any license for them yet.

Here's an example URL:  https://tatoeba.org/eng/audio/of/Sean_Benward

**Comment by trang** [comment]
@alanfgh It's been a while there hasn't been changes in the code of Tatoeba so there hasn't been a lot of strings to review. But I remember agreeing with you that you would take care of validating changes in the UI strings. So I'll wait for your validation before making the change requested by CK here :)

**Comment by alanfgh** [comment]
I basically agree. I'd just remove the comma and the word "yet":

You may not reuse the following audio recordings outside the Tatoeba project because USERNAME has not chosen any license for them.
