### ISSUE TITLE
Missing text on https://tatoeba.org/eng/activities/translate_sentences

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1549]
There seems to be something missing under the heading "Multiple translations" on this page.

https://tatoeba.org/eng/activities/translate_sentences

<img width="296" alt="screen shot 2018-05-26 at 10 42 42" src="https://user-images.githubusercontent.com/7934273/40571322-b3a71d2a-60d1-11e8-8093-bd313826edef.png">

**Comment by trang** [comment]
This will be fixed when de9850a is deployed.
