### ISSUE TITLE
Editing a Japanese sentence with （）doesn't work as expected. - You get furigana.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1550]
Here are screenshots to demonstrate the problem.

https://tatoeba.org/eng/sentences/show/6860304
私はいい先生（女）です。

<img width="722" alt="screen shot 2018-05-26 at 11 22 51" src="https://user-images.githubusercontent.com/7934273/40571631-6b77bc7a-60d7-11e8-8768-2271245986f3.png">
<img width="719" alt="screen shot 2018-05-26 at 11 23 10" src="https://user-images.githubusercontent.com/7934273/40571632-6cc5a83a-60d7-11e8-9a70-f4bc8161beb2.png">

**Comment by jiru** [comment]
I’m working on this.
