### ISSUE TITLE
"An Internal Error Has Occurred." happened when trying to unlink an audio file.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1551]
https://tatoeba.org/eng/sentences/show/1441013

I got the following message when trying to unlink the audio for this sentence.
(This is the first time I've had this problem.)

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

I'm referring to this function.

<img width="306" alt="screen shot 2018-05-29 at 16 14 39" src="https://user-images.githubusercontent.com/7934273/40643550-78e7c1b2-635b-11e8-9c7c-e776ef279739.png">

**Comment by trang** [comment]
@ckjpn This is fixed now and I have also unlinked the audio for the sentence you mentioned.
