### ISSUE TITLE
Updating the license of an existing sentence

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1554]
On the sentence details page, we will need a new section in the sidebar where the owner of the sentence can edit the license. Admins should be able to edit the license as well.

<img width="737" alt="license-existing-sentence" src="https://user-images.githubusercontent.com/221850/40888849-97b4f5a0-675d-11e8-942a-7996452e762c.png">

It is however not as simple as that because we cannot update from and to any license.

1) The licenses of the translations will depend on the license of the original sentence. If `Sentence A` is under CC-BY, and someone translated it into `Sentence B`, then `Sentence B` cannot be CC0 unless `Sentence A` is changed to CC0.
2) A sentence cannot be moved to a more restrictive license, only to a less restrictive one. If `Sentence A` is initially under CC-BY, it cannot be changed to CC-BY-SA, but it can be changed to CC0.

We will need to think this through a lot before we allow users to change the license of their sentences. Probably this feature should be accessible to all contributors but limited to only some specific users at first.

**Comment by jiru** [comment]
> The licenses of the translations will depend on the license of the original sentence. If Sentence A is under CC-BY, and someone translated it into Sentence B, then Sentence B cannot be CC0 unless Sentence A is changed to CC0.

Does the same apply for audio recordings too? If Sentence A is under CC-BY, and someone recorded it into Recording A, then Recording A cannot be CC0 unless Sentence A is changed to CC0. If this is true, it means we may have a problem for recordings that are currently licensed under Public domain.

> A sentence cannot be moved to a more restrictive license, only to a less restrictive one.

May I ask why?

**Comment by trang** [comment]
> Does the same apply for audio recordings too? If Sentence A is under CC-BY, and someone recorded it into Recording A, then Recording A cannot be CC0 unless Sentence A is changed to CC0. If this is true, it means we may have a problem for recordings that are currently licensed under Public domain.

Yes, the same applies to audio. This is why Common Voice cannot just take our sentences and record them under CC0.

Do we actually have any recording licensed under Public domain?

>> A sentence cannot be moved to a more restrictive license, only to a less restrictive one.
>
> May I ask why?

Well assuming you publish something as public domain today. Then I start reusing your work in my project. One year later you decide to change it to CC-BY-NC. What happens to my project? What if published my work as public domain? It would be conflicting.

On the other other hand, if today you publish something under CC-BY-NC and one year later you decide to change it to public domain, it doesn't impact projects that have been already reusing your work.

**Comment by jiru** [comment]
> Do we actually have any recording licensed under Public domain?

Yes. First, we have two audio recordings that don’t belong to Tatoeba members:
```sql
> select * from audios where external like '%Public domain%';
+--------+-------------+---------+----------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| id     | sentence_id | user_id | external                                                                                                                         | created             | modified            |
+--------+-------------+---------+----------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| 240220 |     3924471 |    NULL | {"username":"Barack Obama","license":"Public domain","attribution_url":"http://www.whitehouse.gov/briefing-room/weekly-address"} | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
| 302621 |     5761669 |    NULL | {"username":"Barack Obama","license":"Public domain","attribution_url":"http://www.whitehouse.gov/briefing-room/weekly-address"} | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
+--------+-------------+---------+----------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
```

Second, we have a four users who chose "Public domain" for their audio, and one of them actually published audio. You can get this data by running this query:
```sql
select username, a.sentence_id from users u left join audios a on a.user_id = u.id where audio_license = 'Public domain';
```

**Comment by jiru** [comment]
How about the following scenario:

1. User A creates an original sentence A (not a translation).
2. User A "let go" (abandon the ownership of) sentence A.
3. User B adopts sentence A.

Can user B change the license of sentence A (let’s say to a less restrictive license), just like he would be the original author?

**Comment by trang** [comment]
Another case we need to think about: what if a user chooses a wrong license initially? They didn't pay attention and chose let's say CC0, but they wanted to have the sentence as CC-BY-NC. We should probably allow some period of time where they can fix their mistake.

**Comment by trang** [comment]
Thanks for the input @Ppjet6. It makes sense actually.

We don't need to restrict the change of license but we must track it.

I guess as a first iteration it's then fine to just let users change the license in whatever way they want, as long as we have #1556 implemented.

Then later on we can consider adding some warnings for specific cases.

**Comment by jiru** [comment]
> How about the following scenario:
>
>    User A creates an original sentence A (not a translation).
>    User A "let go" (abandon the ownership of) sentence A.
>    User B adopts sentence A.
>
> Can user B change the license of sentence A (let’s say to a less restrictive license), just like he would be the original author?

Note to self: it looks difficult to find out the original creator of sentences that have been imported by admins. For example, sentence [#5904509](https://tatoeba.org/sentences/show/5904509) is from deniko but has been imported by CK. So just looking at the "sentence created" log entry isn’t enough to find out the original creator. And since we don’t log ownership change, I can’t see any way to distinguish sentences which ownership changed from sentences imported by admins.
