### ISSUE TITLE
[possible enhancement] Possibility to mass tag sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1560]
I have a suggestion: I (and probably someone else, too) would find it pretty useful to have a page where a user who can tag tons of sentences with a specified tag (for example, I tag sentences with their related verb tenses, and I saw this also for other languages along with Italian), and it would be a much better experience (at least for me) to have a page where I can choose a specific tag and add it to many sentences at once.

**Comment by trang** [comment]
@Guybrush88 Already an issue for it #785. You even commented on it :P

By the way, no need to add tags (like `[possible enhancement]`) in titles of issues :) We have labels, and I label issues as I go through them.

**Comment by Guybrush88** [comment]
whops, I had completely forgot about that, sorry :P I added a tag in the title to specify it wasn't a bug or a regression
