### ISSUE TITLE
Remove code duplication in database scripts

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1564]
The scripts in `docs/database/import/`, used to setup a local database, contain instructions to both create and fill tables, while the ones in `docs/database/tables/` only contains instructions to create tables. This unnecessarily duplicates table creation code.

In addition, the code in `docs/database/acl/` duplicates `docs/database/import/{acos,aros_acos,aros}.sql`.

In addition, I think the code in `docs/database/tables/{acos,aros_acos,aros}.sql` can be removed and `cake schema create DbAcl` can be used instead.

CakePHP provides a [plugin](https://github.com/cakephp/migrations) that allows defining the database in a CakePHP way, as well as defining database schema upgrades/downgrades. We should use that.

Finally, Imouto needs to be updated according to the above change.

**Comment by trang** [comment]
Closing this since we no longer use the ACL (#1903), and the import scripts have been cleaned up in 5ba981795a0f9a4fb619a418428217e76a9db593.
