### ISSUE TITLE
Sometimes it loads forever to add a translation

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1566]
I'm trying to translate sentences from https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/only-with-audio/page:7 but sometimes it loads forever to add a translation.

http://prntscr.com/jszfh6

https://youtu.be/KqM_njwKo08

**Comment by RyckRichards** [comment]
more

https://youtu.be/X7SuhZ4ojl0

**Comment by RyckRichards** [comment]
Sometimes it occurs the same for linking

https://youtu.be/9TNFzC8xXAQ

**Comment by jiru** [comment]
I can’t tell the reason it loads forever: it could be a network problem, or the server unable to handle the load, or something else.

But we can improve things by not loosing the translation you just submitted. That’s the goal of issue #458. However I am not sure about how to handle the situation when it occurs while linking sentences.

**Comment by trang** [comment]
Closing this. We'll look into it if there are more users reporting the problem, but at the moment without more information there is not much we can do.
