### ISSUE TITLE
Log out doesn't work now.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1568]
If you click the log out button in Chrome and Safari on a Macintosh, you won't get logged out.
Likely, the same happens on other browsers and computers.

**Comment by trang** [comment]
@ckjpn Clearing your cookies should fix the problem.

**Comment by jiru** [comment]
@ckjpn Can you confirm this issue is fixed after clearing your cookies?

**Comment by ckjpn** [comment]
I've been able to log out and log back in for a while now.
I'm not sure why it was a problem 18 days ago.

I usually always remained logged in, but at that time I needed to make a few logged-out screenshots for a presentation I was doing.
