### ISSUE TITLE
Possibility to have the tags sorted by length in the autocompletion

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1569]
Hi, I have a suggestion about the order of tags that are shown in the autocompletion: I think it would be a nice improvement to have the dropdown list sorted by length, with the shortest tag appearing first, since, if there are many tags (an example of this could be with quotes, when someone starts typing "by"), the shortest ones could be easily overlooked. I'm attaching a screenshot showing that currently tags aren't sorted by length.
![tags screenshot](https://user-images.githubusercontent.com/1702194/41318777-bb1e89d2-6e99-11e8-938d-0cfd422bc58d.png)

**Comment by jiru** [comment]
The tags are currently supposed to be sorted by number of sentences (the more a tag has been assigned, the higher it appears on the list). But I just found out that there is a problem on the production server now that prevents the tags from being sorted correctly. The order is pretty random at the moment.

Are you suggesting to add a setting to allow users to switch to a length-based sort, or to change the sorting for everybody?

**Comment by Guybrush88** [comment]
well, it could be a nice option to have the possibility to switch to a length-based sort (so as an optional feature), so people can have the opportunity to have different ways of sorting of tags (as it can be for sentences with the advanced search feature) for different needs or uses of tags

**Comment by Guybrush88** [comment]
> Yes, but the more the settings, the more complicated the site becomes, and I would like to avoid this.
I see.

> Do you think sorting by length is better that number of sentence?
Then, if it gets too complicated with more settings, sorting tags according to their frequency would be a good solution, at least for me

**Comment by jiru** [comment]
> Then, if it gets too complicated with more settings, sorting tags according to their frequency would be a good solution, at least for me

Alright, then I’m closing this issue in favour of #1578
