### ISSUE TITLE
Searching for a sentence containing 講ずる doesn’t give any result

### ISSUE THREAD

**Issue by linkmauve** [Tatoeba/tatoeba2#1570]
Here is the search URL: https://tatoeba.org/fra/sentences/search?query=%E8%AC%9B%E3%81%9A%E3%82%8B

Since https://tatoeba.org/fra/sentences/show/125289 exists, I would expect it to be present in the search results.

**Comment by jiru** [comment]
It’s because orphan sentences are excluded from the search results by default, and sentence 125289 is currently orphan. [Searching with orphans included](https://tatoeba.org/sentences/search?query=講ずる&from=und&to=und&orphans=) yields the expected sentence.
