### ISSUE TITLE
Possibility to search for sentences containing a given word with translations with a given word

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1575]
As asked by cojiluc and with an interest by deniko:

> Is there a way to search a sentence from the language A whose translation in the language B contains some particular word?
> 
> For example how to search all German sentences containing "bestehen" whose English translation contain "insist". Note that the German verb "bestehen" has several meanings, one of them is "to insist".
> 
> Hence, the general motivation is to search all sentences in which a given word has a particular meaning.

https://tatoeba.org/ita/wall/show_message/29315#message_29315

**Comment by jiru** [comment]
Thanks @Guybrush88, I also opened an issue for that, #1576, so I’m closing this one.
