### ISSUE TITLE
When adding a tag fails, it looks like it has been added

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1577]
Steps to reproduce:
1. Find a sentence that has a tag
2. Try to add the same tag

Result: the yellow tag icon gets added to the end of the list, showing a list with the same tag two times. After refreshing the page, one can see that the tag wasn’t actually added.
Expected: show some error, or at least do not append the tag icon to the end of the tag list.

**Comment by AndiPersti** [comment]
Duplicate of #1070?

**Comment by trang** [comment]
Yes, duplicate. And this bug no longer exists so I'm closing this issue.
