### ISSUE TITLE
Tags autocompletion list is unsorted

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1578]
See #1569 for an image.

The problem can be showed by running this command:
```xml
$ curl 'https://tatoeba.org/jpn/autocompletions/request/present'
<?xml version="1.0" encoding="utf8"?>
<items>
	<item value="1">present continuous</item>
	<item value="1">present continuous passive</item>
	<item value="1">present perfect</item>
	<item value="1">present perfect continuous</item>
	<item value="1">present perfect passive</item>
	<item value="1">present simple</item>
	<item value="1">present simple passive</item>
	<item value="1">presente</item>
	<item value="1">presente do indicativo</item>
	<item value="1">presentew</item>
</items>
```
All the items here have a `value="1"` attribute. This value is supposed to be the number of sentences tagged with that tag. It’s supposed to be read from the query specified in `/etc/suggestd.xml`, that is to say `select name, nbrOfSentences from tags;`.

This is a bug specific to the production server. If I run this command on my VM, all the items have a proper `value` attribute.

**Comment by Guybrush88** [comment]
maybe issue #301 should be kept into consideration. Considering this line "<item value="1">presentew</item>", the tag called "presentew" should not be there, since I made a typo when adding that tag and then deleted it, so now no sentences at all contain that tag

**Comment by jiru** [comment]
I accidentally solved this bug by restarting suggestd on tatoeba.org.

**Comment by jiru** [comment]
Closing this issue as the bug haven’t been noticed for more than a year. This is very likely an issue with suggestd anyways.
