### ISSUE TITLE
Some gui strings that are visible to admins are not translated/translatable

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1579]
Hello, I'd like to report that the strings related to audio that are visible just to admins on any sentence page aren't translated and aren't translatable on Transifex. I'm attaching a screenshot of a sentence page to show this.
![schermata del 2018-06-19 14-24-08](https://user-images.githubusercontent.com/1702194/41597077-b1ac87ea-73cc-11e8-8671-8af69e7d5120.png)

**Comment by trang** [comment]
To clarify, the strings in question are in the "Audio" block:
- yes
- no
- Owner Name

**Comment by agrodet** [comment]
Wouldn't it be better to be the following?

- Yes
- No
- Owner name

**Comment by trang** [comment]
Yes.
