### ISSUE TITLE
On dev.tatoeba.org when adding a tag = Warning (2): fopen(http://127.0.0.1:8080/ ....

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1581]
I got this warning when trying to add a tag  to https://dev.tatoeba.org/eng/sentences/show/6779108

Warning (2): fopen(http://127.0.0.1:8080/add?str=strange&amp;value=1): failed to open stream: Connection refused [APP/Model/Tag.php, line 141]strangeX  +View all tags Logs fdweasdfghjgfds added by deniko, 13 minutes ago  ➜ #6779107 linked by deniko, 13 minutes ago  ➜ #6779109 linked by NewMemberTester, 7 minutes ago  Sentence #6779108 deniko     

The tag did get added, though.

<img width="337" alt="screen shot 2018-06-22 at 19 22 57" src="https://user-images.githubusercontent.com/7934273/41772037-1078b118-7652-11e8-88a7-9723d46beca7.png">

**Comment by jiru** [comment]
Thank you for reporting this. It’s a known problem that only affects dev.tatoeba.org. We need to install the suggestd daemon on it.

**Comment by jiru** [comment]
Problem solved.
