### ISSUE TITLE
Some pages for contributors are accessible by non-authenticated users

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1582]
Hi, I would find it a nice feature for not logged users to see, for pages that are only for members, a message telling that the page they want to see is only for registered members, I find that maybe it would be clearer to see.

**Comment by Guybrush88** [comment]
Also, I would find it useful for certain pages to have a message shown to registered users saying "this page is visible only to advanced users/corpus maintainers/admins", if the user doesn't have the right permissions to see the page.

**Comment by trang** [comment]
@Guybrush88 Can you point out some specific pages where you'd like to see this message?

**Comment by trang** [comment]
Never mind, I guess the "Add sentences" page is one of them.

And the "Translate sentences", even though it is accessible to non-authenticated users, it is probably more confusing. We should probably put that page behind authentication.

**Comment by Guybrush88** [comment]
@trang maybe some pages that are visible only to admins

**Comment by Poulpisator** [comment]
Note that it is a very common way to simply display the "login" form on page whose access is reserved to logged in users.   
About the "this page is visible only to advanced users/corpus maintainers/admins" message, I don't think it is necessary from the UI/UX point of view. Links to such pages would/should not be provided to users that shouldn't access these pages. Only possible access is by direct access (via URL) and that would mean the user knows the URL of such a page, has entered, or guessed it, and he/she will see its access denied. Therefore, I cannot think of a case where more than an "Access denied" error message would be needed. 

@trang You mentioned the "Translate sentences", but the "Adopt sentences" is also accessible and I was even able to click on the adopt icons (resulting on all the loading circles spinning forever). Also, the "List of all members" page is accessible, hence everybody's profile (although I don't know if it is supposed to be publicly accessible or not).

**Comment by jiru** [comment]
@Guybrush88 Just like Poulpisator said, if I am being showed a login form, I find it clear enough that I need an account to access the page. I don’t think we need any extra message.

So the only thing we need to do here is to make the pages "Translate sentences" and "Adopt sentences" redirect to the login form, just like "Add sentences" currently does. Is that correct?

**Comment by Guybrush88** [comment]
> Also, the "List of all members" page is accessible, hence everybody's profile (although I don't know if it is supposed to be publicly accessible or not).

not everyone chose to have his/her profile as public.

> So the only thing we need to do here is to make the pages "Translate sentences" and "Adopt sentences" redirect to the login form, just like "Add sentences" currently does. Is that correct?

Maybe also profiles of users who set them as private.

**Comment by jiru** [comment]
>> Also, the "List of all members" page is accessible, hence everybody's profile (although I don't know if it is supposed to be publicly accessible or not).

> not everyone chose to have his/her profile as public.

Well, "public" and "listed on the list of members" are two different things. Tatoeba has been designed in a way that non public profiles are still displayed but without personal information and description:
> Access to this profile is RESTRICTED. Only Tatoeba members can see the personal information and the description.

The profile picture, the username and the "member since" date are displayed regardless of the "public profile" setting, be it on the profile page or on the list of members. Besides, the username and the profile picture are visible from any Wall message or sentence comment the member may have posted. This looks all very logical to me as it follows the above definition of public and restricted.

@Guybrush88 If you think it’s a problem that non public profiles are being listed on the "list of members" page, feel free to open a new issue.

**Comment by trang** [comment]
To clarify, the scope of this issue just to redirect to the login page if a non-authenticated user tries to go to "Contribute" > "Translate sentences" or "Contribute" > "Adopt sentences".

**Comment by danail-georgiev** [comment]
@trang  In your opinion - is it better to redirect to the homepage or to the loginPage in aforementioned cases?

**Comment by trang** [comment]
We should redirect to the login page.
