### ISSUE TITLE
Wrong sentences showing up during search

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1588]
As reported by BRW on the wall:

> Maybe this issue has long been discussed (then please give me a hint where to look for an answer), but I have just discovered an annoying behaviour in Tatoeba.
> If you enter an English "you"-sentence which then is (correctly) translated into three individual German sentences with "du", "ihr" and "Sie" respectively, and each German sentence gets in turn translated into a French sentence (all three different with "tu", "vous" and "Vous"),
> then there should only be three linked pairs of German-French translations, i.e. "du"-"tu", "ihr"-"vous" and "Sie"-"Vous". However, when I look up one of the German sentences, all three French translations are listed and if I look up one of the French sentences, all three German translations are listed. This is apparently not correct, since the wrong translations are only linked over the English sentence node and should therefore not show up. Any remedy?

https://tatoeba.org/ita/wall/show_message/29367#message_29367

**Comment by alanfgh** [comment]
BRW is probably unaware of the distinction between direct and indirect links.

**Comment by Guybrush88** [comment]
ok, then I can close this
