### ISSUE TITLE
It is not possible to copy, paste and cut

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1593]
As reported by Hybrid on the wall

> Hi, copy-paste no longer seems to work in the search bar or in the "Add new sentences" text box.
https://tatoeba.org/ita/wall/show_message/29389#message_29389

**Comment by Guybrush88** [comment]
I can confirm this bug, and I can reproduce it also with the tags field

**Comment by Poulpisator** [comment]
The copy function of the "copy the sentence" buttons when sentences are displayed is also broken for me.

**Comment by jiru** [comment]
@Poulpisator what browser (name and version) are you using? And which OS (name and version)?

**Comment by Poulpisator** [comment]
Firefox on Windows 8.1

**Comment by jiru** [comment]
Which version of Firefox ? You can find it by going to Help > About Firefox.

**Comment by Guybrush88** [comment]
@jiru I can confirm this also with Firefox 60.0.2 (64 bit) under Ubuntu 18.04

**Comment by sabretou** [comment]
@jiru I can confirm this happening with Waterfox 56.2.1 (64-bit) on Windows 10 Version 1803.

**Comment by jiru** [comment]
I fixed the bug on dev.tatoeba.org, and I hotfixed the bug on tatoeba.org. Copy button and regular copy-paste should be working now.
