### ISSUE TITLE
Search engine should ignore devanagari punctuation 'danda'

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1596]
I've found that Tatoeba's search engine treats the danda as searchable characters. Therefore, searching the Hindi word 'करो' ignores all instances of the word appearing at the end of the sentence ('करो।').

To analogise this to English, imagine if the full stop was counted as a character. If you searched 'Tatoeba', the search engine would ignore all instances of 'Tatoeba.' because of the full stop.

This is the only punctuation mark present in devanagari languages (apart from regular Western punctuation), so all we need is for the search engine to ignore this character: ।

For more information on the danda, see here: https://en.wikipedia.org/wiki/Danda

**Comment by alanfgh** [comment]
For reference, the danda is U+0964 (as mentioned on the Wikipedia page).

**Comment by jiru** [comment]
What about the double-danda "[॥](https://www.fileformat.info/info/unicode/char/0965/index.htm)" that is also mentioned on that Wikipedia page as a marker for "the end of a full verse"?

**Comment by sabretou** [comment]
I wasn't aware the double-danda had its own Unicode point. On Tatoeba, we have been using the regular danda twice.

Regardless, do ignore the double-danda as well. It functions more or less the same as a single danda, only it is used at the end of a (usually Sanskrit) verse.
