### ISSUE TITLE
Aklanon (akl)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1601]
- Language name: Aklanon
- Language info: https://en.wikipedia.org/wiki/Aklanon_language
- ISO 639-3 code: akl
- Public List: https://tatoeba.org/eng/sentences_lists/show/7908
- Icon: https://i.imgur.com/l4r79lD.png
- Requested by: https://tatoeba.org/eng/user/profile/HP

[for tatoeba.org]
CALL add_new_language('akl', 7908);

**Comment by RyckRichards** [comment]
Taking it
