### ISSUE TITLE
Possibility to have an error message when pressing enter/plus icon when the tags field is empty

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1605]
When you click on the tags field in a sentence page (so you're ready to type a tag) and, then, you click on the plus icon next to it or you press enter, the rotating circle icon appears - like it happens when adding an actual tag -, but nothing actually happens. This behavior should not happen, in my opinion, and I think that the user should be, instead, warned that the tags field should not be empty when trying to add a tag.
Steps to reproduce this behavior:
- go to any sentence page;
- click on the tags field;
- don't type anything;
- press enter or click on the plus icon next to the tags field.

**Comment by Poulpisator** [comment]
If we consider it obvious that a unique field cannot be submitted while empty, another alternative would be to simply deactivate submission when the input field is empty.
