### ISSUE TITLE
Allow more export options on the download page

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1609]
Currently, we export data to CSV that are created daily using cron jobs and served as static files. This method prevents us from offering custom dumps, like options to filter the exported data. As a result, people are forced to download large dumps presumably containing a lot of unnecessary data, or they just don’t have access to the data they want because we don’t export it.

We can overcome this limitation using the following method:
* Generate exports on demand by creating CSV files in the background using [this plugin](https://github.com/dereuromark/cakephp-queue/tree/2.x).
* Make these exports showing up on the download page when they are done.

Since the CSV files would be still served statically, downloading can still be stopped and resumed for as long as we keep the file served. If we ever want to have better control over the download, we can serve the files using [x-accel](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/).

If we manage to implement this, it will ease or affect the implementation of #1788, #1687, #1557, #1515, #1358, #1283, #1168, #927, #768, #351, #283.

**Comment by trang** [comment]
Another related issue: #1788

**Comment by trang** [comment]
I will start reporting in this issue cases of people in need of a more customized subset of the corpus.

The latest question we received on this topic was if it's possible to download only sentences from native speakers in a certain language. The person who contacted us had some programming skills and ended up writing a Python script for this purpose. They have agreed that I publish the script. Might be useful for other people who wish to do the same.

https://gist.github.com/trang/f1a3ff4f6d00eab7171125cd857b8148
