### ISSUE TITLE
Advanced Search Might Be Faster Than "Browse by Language", So This Might Be A Way to Improve the User Experience

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1616]
## Possible Enhancement

The Advanced search might be faster than "Browse by language".
If so, then you may want to consider changing the link the the drop-down menu.

### With Audio

Search
https://tatoeba.org/eng/sentences/search?from=eng&to=und&has_audio=yes&sort=created
11 seconds
13 seconds

Browse
https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/only-with-audio
25 seconds
33 seconds

### Without Audio

Search
https://tatoeba.org/eng/sentences/search?from=eng&to=und&sort=created
14 seconds
12 seconds

Browse
https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/indifferent
10 seconds
12 seconds

## Things to Consider

* Currently, I think a cookie is set for the last "browse" selection.
* You don't get all the sentences with "search", but likely people don't really browse more than 1,000 sentences.
* Advanced search allows more options, too. (... not yet translated, etc.)
* With the search, you wouldn't see sentence not yet indexed, I think.

## Screenshot
<img width="995" alt="screen shot 2018-07-21 at 10 53 07" src="https://user-images.githubusercontent.com/7934273/43031135-7b6ad9c0-8cd6-11e8-94e0-151ea5ae7878.png">

**Comment by trang** [comment]
Not relevant anymore. Closing.
