### ISSUE TITLE
Audio doesn't work for kab

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1619]
https://tatoeba.org/eng/audio/index/kab

I assume that this is because these files were uploaded to the /ber/ folder.

**Comment by jiru** [comment]
Yes. I moved the files to the kab/ directory and audio now plays fine.

Is there any way we can avoid this problem in the future? Do you know how come those files were in the wrong directory?

**Comment by ckjpn** [comment]
Those files were originally contributed as Berber.
Apparently, "kab" is a sub-language of "ber", or something like that.
