### ISSUE TITLE
Kirundi (run)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1621]
- Language name: Kirundi
- Language info: https://en.wikipedia.org/wiki/Kirundi
- ISO 639-3 code: run
- Public List: https://tatoeba.org/eng/sentences_lists/show/7980
- Icon: https://i.imgur.com/yvKZs6G.png
- Requested by: https://tatoeba.org/eng/user/profile/driini

[for tatoeba.org]
CALL add_new_language('run', 7980);

**Comment by RyckRichards** [comment]
taking this
