### ISSUE TITLE
Probably Horus overlooked some sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1624]
I was browsing some sentences, and I found out that this sentence https://tatoeba.org/ita/sentences/show/6945917 was kept in the database even if it's the exact duplicate of https://tatoeba.org/ita/sentences/show/967194, which is much earlier, so I guess Horus skipped some sentences.

**Comment by jiru** [comment]
There is an unbreakable space (U+00A0) between the words "swim" and "almost" in sentence 6945917, while sentence 967194 has a normal space. That’s why Horus see them as different sentences.

**Comment by trang** [comment]
I'm closing this. Horus has by the way his own repository. 

You may want to report issues over there: https://github.com/Tatoeba/horus
