### ISSUE TITLE
The script for mass importing sentences should prevent the upload if something goes wrong

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1629]
I was playing around on dev with the mass import of sentences to test some things, and, with a file containing sentences that were already in the database, I got as a result the addition of empty sentences, such as:
https://dev.tatoeba.org/ita/sentences/show/6779657
https://dev.tatoeba.org/ita/sentences/show/6779578
https://dev.tatoeba.org/ita/sentences/show/6779579
https://dev.tatoeba.org/ita/sentences/show/6779580

EDIT:
If it helps, I got this bug under Windows 10

**Comment by agrodet** [comment]
With #1762 around, is that issue still relevant?
