### ISSUE TITLE
Errors are shown on dev when searching for words

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1635]
While performing this query: https://dev.tatoeba.org/ita/sentences/search?query=Tom+ha+bisogno+di+riposare.&from=und&to=und , I get some results, but I also get this error message repeated twice:

Notice (1024): Search query warning: index 'jbo_main_index': query word(s) mismatch: 'a [APP/Model/Behavior/SphinxBehavior.php, line 120]

With another query made putting words between " (https://dev.tatoeba.org/ita/sentences/search?query=%22tom+ha%22&from=und&to=und), I got the same error message as above, and also this new error message, although I still got some results:

Notice (1024): Search query failed: connection to localhost:9312 failed (errno=111, msg=Connection refused) [APP/Model/Behavior/SphinxBehavior.php, line 116]

**Comment by trang** [comment]
Can no longer be reproduced. Closing.

**Comment by jiru** [comment]
On August 3, 2019 12:47:42 PM UTC, Trang <notifications@github.com> wrote:
>Can no longer be reproduced. Closing.

I believe the errors show if you enable debug in app_local.php. We used to have debug enabled on dev.tatoeba.org, but it's no longer the case.

That said, if I remember correctly it's a problem in Manticore and the warning is harmless. So it's probably okay to keep this issue closed.
