### ISSUE TITLE
how to add a new language? 

### ISSUE THREAD

**Issue by tulakalbeyo** [Tatoeba/tatoeba2#1644]
language request: yucatec maya.

i'm a linguistics bachelor's student centered on its study. i'm far from fluent, but i can translate a few things, and i know a lot of native speakers who can contribute well on here, since we have all been looking for a site like this for a long time. a "neologism" tag would be awesome, too. thanks!!

**Comment by trang** [comment]
Aiji replied to you on the Wall: https://tatoeba.org/eng/wall/show_message/29592#message_29592

I will close this.
