### ISSUE TITLE
Add Kabyle to the language po file

### ISSUE THREAD

**Issue by belkacem77** [Tatoeba/tatoeba2#1646]
Kabyle is not available yet in the language po file. So on Tatoeba web site, we still have "kabyle" instead of "taqbaylit" (native name of the language)

**Comment by jiru** [comment]
I think it is available in the [languages.pot file on Transifex](https://www.transifex.com/tatoeba/tatoeba_website/translate/#kab/tatoeba-languages/150683923?q=translated%3Ano) but not yet translated.

**Comment by S-Amiri** [comment]
I translated kabyle into Taqbaylit into the given file,

**Comment by belkacem77** [comment]
@jiru thanks

**Comment by belkacem77** [comment]
thanks @S-Amiri
