### ISSUE TITLE
Language of flag dropdown is not preselected for admins and corpus maintainers

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1648]
Steps to reproduce:
1. Log in as an admin or corpus maintainer.
2. Add a sentence of a language that you have in your profile.
3. Click on the flag of the sentence.
4. Problem: the preselected option of the drop down is not the current language of the sentence.

Relevant code: https://github.com/Tatoeba/tatoeba2/blob/f3b4c4ca56fca213185f4dec1490c0bb3f3e2529/app/View/Helper/SentenceButtonsHelper.php#L232-L243

**Comment by AndiPersti** [comment]
That part changed:
https://github.com/Tatoeba/tatoeba2/blob/089e3ab5fe6e6c712aae21b67bedf99efc5efd5b/src/View/Helper/SentenceButtonsHelper.php#L230-L254
and I cannot reproduce this problem on my local copy anymore so I think this issue can be closed.

**Comment by trang** [comment]
Indeed. Thanks, @AndiPersti!
