### ISSUE TITLE
Lists page overlaps with sidebar

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1656]
Under Ubuntu 18.04 and using Firefox 61.0.1 (64 bit), the pagination of the lists page https://tatoeba.org/ita/sentences_lists/index is wrong. I'm attaching a screenshot to show how it looks.
![wrong pagination](https://user-images.githubusercontent.com/1702194/44721350-ead86a00-aac9-11e8-9dcb-eb92a78a4b59.png)

**Comment by jiru** [comment]
I can reproduce the problem when setting the website locale to Italian. The last column title _ultimo aggiornamento_ stretches the column, which makes the table spread out over the right pane.
