### ISSUE TITLE
Reconsider name of 'Low Saxon'

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1669]
According to SIL, the language referred to by the ISO 639-3 code 'nds' is known as both 'Low Saxon' and 'Low German'. There does not seem to be a preference for either. 

For accuracy, and to aid any potential users who might search for the language that way, perhaps we should rename the language to either "Low Saxon (Low German)" or "Low German (Low Saxon)".

Sources: 
https://iso639-3.sil.org/code/nds
https://en.wikipedia.org/wiki/ISO_639:n

**Comment by RyckRichards** [comment]
@sabretou should we go ahead on this?

**Comment by sabretou** [comment]
Yes, let us go ahead with this. We will rename the language to "Low German (Low Saxon)".

**Comment by RyckRichards** [comment]
Alright!
