### ISSUE TITLE
Profile picture is not updated

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1680]
I have updated my profile picture but both the main page and the latest contribution page shows my old picture:

![image](https://user-images.githubusercontent.com/7658430/46240433-c4824480-c37d-11e8-9675-b6ead1bf79b6.png)

![image](https://user-images.githubusercontent.com/7658430/46240437-d8c64180-c37d-11e8-8da8-4dc346fd9253.png)

**Comment by jiru** [comment]
Hmm, it looks like the profile picture on the [latest contributions page](https://tatoeba.org/contributions/latest) is not timestamped (URL is `https://tatoeba.org/img/profiles_36/927a3c89571b418db91809571b6ef851.png)` while the picture on the profile page is timestamped (URL is `https://tatoeba.org/img/profiles_128/927a3c89571b418db91809571b6ef851.png?1538183396`). That may explain why your were seeing the old picture on the latest contributions page. However, if this is true, it means you were able to see the new picture on [your profile page](https://tatoeba.org/user/profile/Ricardo14). Was that the case?

**Comment by RyckRichards** [comment]
@jiru yes, I can see everywhere except on the [latest contributions page](https://tatoeba.org/contributions/latest)
