### ISSUE TITLE
Language icon changes (NOT KABYLE)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1692]
Here are some language icons we need to change, either because the original icon was suggested by non-natives and may pose problems along the way, or because of cropping issues or aspect ratios incorrect according to official standards. Others that may need to be changed, such as Kapampangan, Malayalam, Mohawk, Tamil, Telugu were proposed by natives, though we currently do not have any active users, I'd like to wait until we do have active natives to ask for their opinions.
Still others, such as Ancient Greek, Latin, Old Turkish have propositions for change that haven't been decided upon.

Bodo - BRX - https://i.imgur.com/GDxUo1L.png
Maithili - MAI - https://i.imgur.com/DIE0Lp6.png
Hawaiian - HAW - https://i.imgur.com/Ladzuvg.png
Guaraní - GRN - https://i.imgur.com/HCbL3kA.png
Amharic - AMH - https://i.imgur.com/sngJVnN.png

**Comment by trang** [comment]
For the record, related Wall thread:
https://tatoeba.org/eng/wall/show_message/30332#message_30332

**Comment by trang** [comment]
@cueyayotl I'm noticing that the images you linked for some of the languages do not fit the standard size that we use in Tatoeba (30x20 pixels) and do not match the ones that sabretou suggested, even though you said you would use his icons.

1. Hawaiian - HAW - https://i.imgur.com/Ladzuvg.png
2. Guaraní - GRN - https://i.imgur.com/HCbL3kA.png
3. Amharic - AMH - https://i.imgur.com/sngJVnN.png

I suspect this is a mistake? The icons from sabretou are:

1. https://image.ibb.co/kR7qB9/hawaiian.jpg
2. https://image.ibb.co/nuCRJp/guarani.jpg
3. https://image.ibb.co/frYBjU/amharic.jpg

**Comment by trang** [comment]
@sabretou We would need the final icons in PNG format. Can you take care of making the icons for the languages mentioned in the description and send the final versions to Ricardo?

Similarly to the issue about Tachawit, I'd like to merge the related pull request this week if possible.
