### ISSUE TITLE
Users are translating from the wrong language

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1700]
## Problem

Reported by CK by email.

Some users add translations to sentences in languages they don't know, which can cause inaccurate translations.

For instance: https://tatoeba.org/eng/sentences_lists/show/8407/und
We can see that Igider has added Kabyle translations to Turkish, Russian or Italian sentences. He hasn't listed any of these languages to his profile so it is very likely that he actually wanted to translate from English.

## Possible solution

As a temporary solution, we could disable the translate button when the original sentence is in a language that the user hasn't listed in their profile.

Or we could replace the translation form by a warning message like:
> Please make sure to translate only sentences in languages that you understand. You are not allowed to translate this sentence because you have not added {language} to your profile languages so we assume that you do not understand {language}.

A longer term solution would be to design a proper translation workspace for our contributors.

**Comment by Amazigh-bedar** [comment]
Hi,
I have just checked Igider's sentences, he only translates into Kabyle. he did not add phrases in Turkish, Russian and Italian as you said.
we must check if there is an error somewhere because Igider adds only Kabyle sentences.
Thanks

**Comment by trang** [comment]
@Amazigh-bedar I realize my description was ambiguous (I reworded it). The problem is not at all his translations, he is indeed adding only translations in Kabyle.

The problem is that the sentence he is translating from is not in the correct language. He wants to translate English sentences, but he ends up adding translations to Turkish, Russian or Italian sentences.

This is not his fault. It's a recurring problem we've had due to how our data is structured.

**Comment by Poulpisator** [comment]
Could you detail how it is possible for a user to mistake in such a way?

**Comment by trang** [comment]
To some users it is not clear that when they add a translation, it is linked to the first sentence in the group of sentences. 

What I assume most likely happens is that typically they see a random sentence on the homepage, the main sentence might be in some language they don't understand but it has a translation in a sentence they do understand. Most likely it's an easy sentence to translate, they memorize the translation, click on the translate button, add their translation and save.

Because everything is a list of items displayed in the same box, it gives the idea that everything in this box means the same thing. They see their translation in that box, it doesn't necessarily occur to them that the translation they added may not match every other sentences in the box. As long as it matches the sentences they understand, everything looks fine to them.

**Comment by Poulpisator** [comment]
Hmm, that's an interesting behavior. 
Then, maybe it is time to reverse the "Display sentences with the new design. Note that you will not have all the features from the old design" to "Display sentences with the old design." 
If then "listen to audio" button is added, I think, there would be no issue doing so, no? 

Speaking of which, when I choose this option or log out (should be same, right?), I see no difference in display anymore on the sentence page. Is it because of the audio button? So the old design is always displayed on sentence pages?

**Comment by trang** [comment]
> Then, maybe it is time to reverse the "Display sentences with the new design. Note that you will not have all the features from the old design" to "Display sentences with the old design."

Applying the new design by default could make it more difficult for new users to figure out how to translate sentences efficiently. But it's not a bad idea: we could use a "restricted mode" (new design) by default for new users and have them switch to the "advanced mode" (old design) when they are ready to start contributing. During the transition we somehow try to make sure they understand how Tatoeba works.

> Speaking of which, when I choose this option or log out (should be same, right?), I see no difference in display anymore on the sentence page. Is it because of the audio button? So the old design is always displayed on sentence pages?

Yes it's because of the audio, but also of any other feature. If you use the new design, you basically can't do anything (can't translate, can't favorite, can't add to list...). Leaving the old design on the sentence's page was a way for you to still be able to do these actions without having to switch back and forth between old and new design.

**Comment by trang** [comment]
Duplicated by #2132.

Note: the new sentence design now has the "Translate" feature implemented so the suggestion of using it on the homepage no longer applies.
