### ISSUE TITLE
add audio plugin to your website

### ISSUE THREAD

**Issue by adals** [Tatoeba/tatoeba2#1706]
hello everyone

i like your website very much. but I think in my mind that its lack of good audio system because for the learner the text will be not so good if there is no audio for its words to support it. and at the same time to pronounce a complete sentence in one file is not good

so I have an idea about it.

1- every user on your web site can contribute with audios for WORDS not for sentences and must be native speaker.

2- it will show with sentence automatically.

for example : 

User1 us native
User2 gb native
User3 us native

sentence 1:
Word1 Word2 Word3
U1-----U1-----++
++-----++-----U2
U3-----U3-----U3

word1 is spoken by U1 & U3
word2 is spoken by U1 & U3
word3 is spoken by U2 & U3

 so the viewer can change in its profile 
1- sentence must pronounce by one native speaker as in U3 which W1,W2,W3 
2- sentence can pronounce be any native speaker if available like W1 U1 W2 U3 W3 U2 (gb or us can solve it)

also the contributor if he/she want/s to contribute with audios
will see  sentences that were not pronounced by one native speaker(missing 1 word or more) and let them to complete all the sentence with one native speaker and also complete audio system in your website

i hope you like my idea 
thanks

**Comment by adals** [comment]
I wanted something like 2 because : 
1- in arabic(as a native speaker) language every word is isolated and pronounce will be the same for every word.
2- in english as I think also be be the same (correct me if I am wrong).

and I think your sentences must accompany with voices to be at learning level because texts without voices mean nothing

and if you want to record voice per each sentence it will be so hard

**Comment by jiru** [comment]
I think that, for learning, providing a word by word recording of a whole sentence is as bad as providing a word for word translation. I may help at a word-level, but not at a sentence level. It just doesn’t reflect the way someone normally speaks. In many languages, including English, [intonation plays a very important role to convey the message](https://en.wikipedia.org/wiki/Intonation_(linguistics)#Functions). Besides, [in English homographs may be pronounced differently](https://en.wikipedia.org/wiki/English_language#Stress,_rhythm_and_intonation). And as I said some languages don’t have word boundaries.

Learning how to pronounce correctly isn’t just about converting words into sounds. Each language have a specific rhythm and intonation, that you need to learn if you want to speak properly and understand what people are saying.

That’s why I think it’s a bad idea for learners.

**Comment by trang** [comment]
Closing this. Considering that there are other people already building a database of audio for words and considering that we're more focused on sentences, this is out of our scope.

I can see some benefits in being able to click on a word and hear the audio for that word, but such a feature does not have to be implemented by us within Tatoeba. It could be an addon to the browser, done by anybody.
