### ISSUE TITLE
Focusing the language drop-down field unsets its value

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1708]
Prior to the change to the language drop-down menus that made it possible to type language names into them, typing text into the word search field at the top of the page and then pressing Enter left the contents of the "From" and "To" language fields untouched. This was the right behavior, since the user had not shown any sign of wanting to change these fields. However, after the change, on Android, typing text and then pressing Enter in the word search field clears the "From" field, puts the focus in it, and demands input. This is a pain because I then have to go through the effort of specifying a language, even though it was already set from the last search I did. On Windows, the behavior is still fine.

**Comment by jiru** [comment]
I suspect that pressing Enter from the "word" field on Android makes it jump to the next form element, just like TAB is doing on computers. If so, it means that even though the "From" field appears to be unset, it actually isn’t. It’s "just" that when the language dropdown gets focus, it hides the selected language and prompts for a new one. But as soon as you move the focus away from the dropdown, the selected language reappears. I can see this behaviour from a computer when stepping from the "word" field up to the "submit" button by pressing TAB multiple times.

So it looks to me that the real problem is that the new language dropdown hides its selected item when getting focus. @alanfgh can you confirm?

**Comment by alanfgh** [comment]
@jiru, no, that's not the case on an Android device. The "From" field is actually erased. I can see this by pressing the search button, which results in a search error because the "from" value in the URL is empty (not "und", and not the value from the previous search).

**Comment by jiru** [comment]
@alanfgh I published a fix on dev.tatoeba.org, can you try it out?

**Comment by alanfgh** [comment]
@jiru, thanks for addressing this. I tried it out on the dev site. Indeed, your change does fix the behavior that was bothering me, but at the cost of introducing another quirk. On Android, on the dev site, once you press Enter in the word field, you are taken to the "From" field, and the "From" and "To" fields go into "text-only" mode. That is, you can no longer bring up the drop-down by touching either field. Thus, you don't have access to the languages in your profile that appear at the top of such a drop-down unless you fully delete the language string. However, by pressing Enter twice (once in the word field and once in the "From" field to which you are automatically taken), the word search is performed. I can live with that, but it would be nice to still have the ability to change the languages in the "From" and "To" fields by touching them, even after pressing Enter in the word field.

**Comment by trang** [comment]
@alanfgh Is the behavior with the enter button happening if you would use another browser than Chrome?

I found some complaints on this issue:
* https://productforums.google.com/forum/#!topic/chrome/ssAL94glWMU
* https://stackoverflow.com/questions/47624996/how-to-stop-go-button-being-replaced-with-next-chrome-android-browser-app

Basically, it seems that on Chrome, the "enter" button will be converted into "next" when it detects that there's another input after the currently focused input. So the real solution would be to figure out how to prevent the "enter" button from turning into "next" when the focus is on the query input.

**Comment by alanfgh** [comment]
@trang, indeed, the behavior where typing Enter into the word field brings you to the next field seems to be limited to Chrome. I verified this by trying both the Samsung Internet browser and Chrome on my Android phone.

@jiru, it's true that pressing the ✘ button brings back the list, but that didn't occur to me.

**Comment by trang** [comment]
I am looking to see how to get rid of the "next" behavior on Android Chrome. I feel it would be best to revert the changes to keep the opening of the list when clicking on the input.

There is a slight difference between opening the list via 'x' and opening the list via clicking on the input: 
- When clicking on 'x', the value is reset. Clicking outside will not bring back the previously selected value. As a result, you have no way to just open the list to see what languages are available. If you want to see what languages are in the list, the trade off is that you must erase the current value.
- With the opening of the list on click, the value was only temporarily reset. Clicking outside would bring back the previously selected value. The behavior was meant to mimic as much as possible the HTML `<select>`.

When implementing the language dropdown, it did occur to me that the user could just click 'x' to show the list. But from my personal usage, it didn't feel intuitive nor practical to keep that way. For most users it will not be obvious at all that they should click on 'x'.

**Comment by trang** [comment]
I found a solution which was simple after all: by setting `type="search"` on the query input, the keyboard in Chrome understands that pressing "enter" on that field should execute the search.

@alanfgh You can test it on dev.tatoeba.org.

**Comment by alanfgh** [comment]
@trang, it works perfectly! I'm looking forward to that change reaching the production site. Thank you!
