### ISSUE TITLE
In Chrome you can select the sentences on a page copy and copy the selection, but in Firefox, you can't.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1710]
I don't know if this is a big deal, but on a Macintosh, you can easily select the main sentences and their translations, and copy them.  This doesn't work in Firefox.

In Firefox, I needed to select all the text on a page, then copy and paste it into a text editor, and then do another select and copy from the text editor.

If I'm the only one who does this kind of thing, it's likely not something that needs to be corrected, but I thought you'd like to know.

I'm referring to pages like these.

https://tatoeba.org/eng/sentences/show/6873252

**Comment by jiru** [comment]
> This doesn't work in Firefox.

Does it use to work before?

**Comment by ckjpn** [comment]
I don't know.  I almost always use Chrome.  I just happened to be using Firefox and noticed the problem.

**Comment by jiru** [comment]
The problem comes from the `<svg>` element used to display the blue arrows in front of each translation. If you remove this element with the DOM inspector, selection works.

I’m closing this issue as it’s a [known bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1223203).
