### ISSUE TITLE
Corrupted UI after editing sentence already owned by someone else

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#1714]
A picture says more than 1000 words:
![corruption](https://user-images.githubusercontent.com/6555947/47943571-e760c500-def6-11e8-9e56-2f288b59a935.png)

What I did to arrive at that state:
1. Translate "I thought Tom was dead." as "Ich dachte, Tom wäre tot."
2. Click on the added sentence, entering edit mode.
3. Exit edit mode by pressing enter.
Then the sentence was replaced by what you see above.

What I guess happened:
Because the sentence I wrote already existed as [#3034455](https://tatoeba.org/sentences/show/3034455), it was not added as a new sentence, but only a link was created. Because the sentence was owned by someone else, the edit action was rejected and some random HTML was returned instead.

I guess some error-handling needs to be added somewhere. Alternatively, the sentence could be created separately at first, straining Horus a bit more. (That would also help if someone wrote a different sentence than they intended and it ended up linked, impossible to correct.)

**Comment by trang** [comment]
With ef5e750b57626064736e8566bc54924ac5fbebb5, editing the sentence will return the old sentence text if the user cannot edit. This is still probably a bit confusing but we'll work on a better error handling when migrating to the new sentence UI.

**Comment by Yorwba** [comment]
That was a quick fix ;) Sorry for not trying to repro on master first.
