### ISSUE TITLE
An easier way to reach the user who left a comment on a sentence I posted

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1718]
**The problem**

For now, if I want to send a private message - maybe to ask something that I don't want other users to read what I'm going to ask / I'm going to talk about something unrelated to the sentence - to the user who left a comment on my sentence, I have to

1. Click on his username;
2. Click on "Contact <user>"
3. Type the message
4. Proofread and hit "send"

**Suggestion**

Add a button "Message" which would redirect me to https://tatoeba.org/eng/private_messages/write/*** 

*** = user

![screenshot_1](https://user-images.githubusercontent.com/7658430/48307015-f533cd00-e52a-11e8-9b9d-f64bd349d684.png)

**Comment by danail-georgiev** [comment]
Hi, 

I created a draft pull request for this one, can someone please have a look and advise on the issues I have detailed in the MR description. I will appreciate your input on this. Thank!
