### ISSUE TITLE
Presence of error messages when mass importing sentences with translations on dev

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1719]
When mass importing sentences with translations on dev from files, I got these error messages:

Notice (8): Undefined index: Import [APP/Controller/ImportsController.php, line 102]

Notice (8): Undefined index: Import [APP/Controller/ImportsController.php, line 103]

Notice (8): Undefined index: Import [APP/Controller/ImportsController.php, line 104]

Notice (8): Undefined index: Import [APP/Controller/ImportsController.php, line 105]

Notice (8): Undefined offset: 1 [APP/Controller/ImportsController.php, line 123]

The sentences are actually imported properly, though.
These error messages don't appear on prod, mass importing works generally fine

**Comment by jiru** [comment]
Could you provide us with the complete file you’re importing?

**Comment by Guybrush88** [comment]
Notice (8): Undefined offset: 1 [APP/Controller/ImportsController.php, line 123] was triggered by
[frasi di prova.txt](https://github.com/Tatoeba/tatoeba2/files/2569633/frasi.di.prova.txt)

**Comment by Guybrush88** [comment]
about Notice (8): Undefined index: Import [APP/Controller/ImportsController.php, line 104], I can't trigger it anymore, and I overwrote the same csv file to test different things, and, changing various things to retrigger it, I'm not able to do so, I only get the undefined offset message, and I can't remember the conditions that got the undefined index

**Comment by ckjpn** [comment]
I experimented a bit.

I did several imports with no problems, but I imported a set of Kabyle sentences.

Tom, tagi d Mary.
Tom ẓẓay ugar n Mary.
Tom yura i Mary.
Tom yumen Mary.
Tom yezzi ar Mary.
Tom yezzi ar Mary.
Tom yexdem d Mary tama ar tama.
Tom yettmuqul Mary.
Tom yettaru deg unasiw xir n Mary.
Tom yettamen Mary.
etc.
etc.


and go error message like the ones at the bottom of this message.

However, the sentences did seem to get imported.
https://dev.tatoeba.org/eng/sentences/of_user/belkacem77



Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): searchd error: index kab_delta_index,kab_main_index: index not available [APP/Model/Behavior/SphinxBehavior.php, line 303]
etc.

**Comment by Guybrush88** [comment]
I managed to reproduce the "Notice (8): Undefined offset: 1 [APP/Controller/ImportsController.php, line 123]" error message. I simply uploaded this file, which was actually imported, choosing Berber as the first language and English as the second language. I added it in a .zip archive because github doesn't accept .csv files
[frasi in berbero da importare.zip](https://github.com/Tatoeba/tatoeba2/files/2598800/frasi.in.berbero.da.importare.zip)

**Comment by ckjpn** [comment]
This isn't exactly the correct format.
Some of these are only Berber, some of these are Berber + TAB + Berber

Anda ay t-id-yufa Yidir?	
Anda ay t-id-tufa Taninna?	Where did Taninna find it?
Anda ay t-id-tufam?	
Anda ay t-id-tufamt?	
Anda ay t-id-ufan?	
Anda ay t-id-ufant?	
Anda ay tt-id-yufa?	
Anda ay tt-id-tufa?	
Anda ay tt-id-yufa Yidir?	
Anda ay tt-id-tufa Taninna?	
Anda ay tt-id-tufam?	
Anda ay tt-id-tufamt?	
Anda ay tt-id-ufan?	
Anda ay tt-id-ufant?	
Anda ay ten-yeẓra?	
Anda ay ten-teẓra?	Where did she see them?
Anda ay ten-yeẓra Yidir?	
Anda ay ten-teẓra Taninna?	
Anda ay ten-teẓram?	
Anda ay ten-teẓramt?	

etc.

**Comment by agrodet** [comment]
With #1762 around, is that issue still relevant?

**Comment by trang** [comment]
No, it's not. As mentioned in #1762 we won't fix the mass import feature. Closing.

Thanks for helping tidying up our issues, @agrodet.
