### ISSUE TITLE
Some fields need a fix when writing a new message in the Russian interface

### ISSUE THREAD

**Issue by explanacion** [Tatoeba/tatoeba2#1720]
If we open this page in the Russian interface
https://tatoeba.org/rus/private_messages/write
we can see this
https://i.imgur.com/jWkpXdS.png

The fields seem to be misplaced but that's not the only problem. The field "To" is rendered as "язык перевода" which would be correct in case of translation from one language to another but here it should be "Кому".

**Comment by trang** [comment]
I fixed it in Transifex. If you notice more translation mistakes, feel free to join the Tatoeba translators team on Transifex so you can correct the mistakes yourself. More info here: https://en.wiki.tatoeba.org/articles/show/interface-translation
