### ISSUE TITLE
Guadeloupean Creole French (gcf)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1725]
- Language name: Guadeloupean Creole French
- Language info: https://en.wikipedia.org/wiki/Guadeloupean_Creole_French
- ISO 639-3 code: gcf
- Public List: https://tatoeba.org/eng/sentences_lists/show/8517
- Icon: [we may have to use default, as only other viable option is the unofficial Guadeloupean flag; person requesting the language is not sure either]
- Requested by: https://tatoeba.org/eng/user/profile/theachaean

[for tatoeba.org]
CALL add_new_language('gcf', 8517);

**Comment by RyckRichards** [comment]
@cueyayotl any position about the language icon?

**Comment by sabretou** [comment]
@RyckRichards I've created a fresh issue for this language with the new list and a confirmed icon. This issue can be closed safely.

**Comment by jiru** [comment]
Closing as duplicate of #1824.
