### ISSUE TITLE
Add "x" to word field for advanced as well as regular search

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1728]
On the Wall, user cojiluc [writes](https://tatoeba.org/eng/wall/show_message/30995#message_30995) the following:

> ln the search box, there is a small sign x which can be used to delete the content at once. It could be helpful if one has the same thing in the advanced search boxes, specially when using touch devices.

I agree. Note, however, that the advanced search word field is narrower than the regular search field, so the x will be smaller and harder to press.

**Comment by gioele-santi** [comment]
I'd like to work on this. I will check the code this weekend

**Comment by RyckRichards** [comment]
Thanks a lot, @gioele-santi !

**Comment by alanfgh** [comment]
Yes, thanks for fixing this, @gioele-santi. Replacing the contents of the field is easier now.
