### ISSUE TITLE
Language detection is less reliable than it used to

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1731]
Reported by [sacredceltic on the Wall](https://tatoeba.org/eng/wall/show_message/31050#message_31050):

> La reconnaissance automatique de langue est polluée par des langues dont le nombre de phrases est faible.
> Je pense qu'il faudrait exclure de la reconnaissance les langues qui n'ont pas encore atteint une certaine masse de phrases, de manière à ce que l'algorithme d'identification puisse s'appuyer sur des échantillons plus significatifs de segments.

> A peu près toutes les dernières phrases courtes en français que j'ai créées ont été mal identifiées comme des langues improbables : chavanaco, bavarois,...

> Bon, là c’est de pire en pire : des phrases françaises assez longues sont reconnues comme de l’anglais (!) ou de l’interlingua.

**Comment by trang** [comment]
Latest thread on the topic: https://tatoeba.org/eng/wall/show_message/31626#message_31626

**Comment by jiru** [comment]
I improved Tatodetect and installed the new version on tatoeba.org. The problem should be solved now.
