### ISSUE TITLE
Sentences can be added/removed even when "Who can add/remove sentences" is set to "No one"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1732]
If I set the "Who can add/remove sentences" option for a list to "No one (list inactive)", I would expect that if I click the red "X" above a sentence, the UI will stop me from deleting it (or better yet, will not display a red "X" in the first place). But that's not true. Either the wording of the GUI elements relating to this option should be changed or the UI should prevent me from deleting sentences from this list. (The UI already prevents me from adding sentences to it by stripping the name of the list from the drop-down list above the sentence.) 

Note that this is true on the production site as well as on the dev site.

**Comment by agrodet** [comment]
I'll check this.

**Comment by agrodet** [comment]
@trang I'm not 100% percent sure of how sql files in the tables folder and the updates folder are supposed to interact with each other. I was expecting the usual migration stuff, but in the `CREATE TABLE` we have 
https://github.com/Tatoeba/tatoeba2/blob/22e4865521475996b3e00b64f7b7639e5420982a/docs/database/tables/sentences_lists.sql#L30

And we have two updates on this table, one is 
https://github.com/Tatoeba/tatoeba2/blob/22e4865521475996b3e00b64f7b7639e5420982a/docs/database/updates/2016-01-03.sql#L1-L5
the other is 
https://github.com/Tatoeba/tatoeba2/blob/22e4865521475996b3e00b64f7b7639e5420982a/docs/database/updates/2016-05-22.sql#L1

Aside my surprise that the CREATE TABLE code has the same column definition than the first update, looking at the second update, I was expecting the `editable_by` column definition to be `enum('creator', 'anyone', 'no_one')`. However, looking at the table in my dev environment, the column definition is `enum('creator', 'anyone')` so it's not surprising that the setting doesn't work there (although I think there are other logic issues). Is the problem in my dev environment? Maybe the table was not updated when I created the environment? Does the prod table has the correct column definition?

PS: I looked at the history of the files and the `CREATE TABLE` was modified at the same time than the first update file.

**Comment by trang** [comment]
We forgot indeed to update the sentences_lists.sql. The prod database has the value `no_one`. In your dev environment it is normal that you won't have it, because Imouto will use the database/table scripts to create the database.

```
MariaDB [tatoeba]> describe sentences_lists;
+-------------------+-------------------------------------+------+-----+----------+----------------+
| Field             | Type                                | Null | Key | Default  | Extra          |
+-------------------+-------------------------------------+------+-----+----------+----------------+
| id                | int(11)                             | NO   | PRI | NULL     | auto_increment |
| is_public         | tinyint(1)                          | NO   |     | 0        |                |
| name              | varchar(450)                        | NO   |     | NULL     |                |
| user_id           | int(11)                             | YES  |     | NULL     |                |
| numberOfSentences | mediumint(8) unsigned               | NO   |     | 0        |                |
| created           | datetime                            | YES  |     | NULL     |                |
| modified          | datetime                            | YES  |     | NULL     |                |
| visibility        | enum('private','unlisted','public') | NO   |     | unlisted |                |
| editable_by       | enum('creator','anyone','no_one')   | NO   |     | creator  |                |
+-------------------+-------------------------------------+------+-----+----------+----------------+
9 rows in set (0.00 sec)
```

**Comment by agrodet** [comment]
I see, so if I update the table creation script and update my environment I should be able to solve the issue. Thank you for your quick answer :)

**Comment by agrodet** [comment]
I corrected the behavior for deletion. However while testing, I realized that if a list is unlisted and editable_by anyone, its name appears in the "Add to list" drop-down list as a collaborative list. Is that intended behavior? 

I must admit than I use only personal lists so I'm not very well aware of how the function is supposed to work. I thought I could access the list only via the URL. But then, yes, cannot add sentences to it... Makes sense... Or unlisted and editable_by anyone aren't supposed to be used together?

**Comment by AndiPersti** [comment]
> However while testing, I realized that if a list is unlisted and editable_by anyone, its name appears in the "Add to list" drop-down list as a collaborative list. Is that intended behavior?

I think it is. From https://github.com/Tatoeba/tatoeba2/issues/677#issuecomment-169474282:
> In addition to this, there is an option to make the list editable by anyone.
Whether a list is public, unlisted or private, it can be made editable by anyone. When a list is editable by anyone, it appears in the dropdown of the sentence's menu (the one that lets you choose which list you want to add the sentence to).

**Comment by agrodet** [comment]
Are we okay with this? @jiru

**Comment by jiru** [comment]
Yes, thanks for the reminder.
