### ISSUE TITLE
Cayuga (cay)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1734]
- Language name: Cayuga
- Language info: https://en.wikipedia.org/wiki/Cayuga_language
- ISO 639-3 code: cay
- Public List: https://tatoeba.org/eng/sentences_lists/show/8646
- Icon: pending (possibly: https://i.imgur.com/GkkSIpU.png)
- Requested by: https://tatoeba.org/eng/user/profile/robot_fury

[for tatoeba.org]
CALL add_new_language('cay', 8646);

**Comment by RyckRichards** [comment]
Updated flag from png to svg

**Comment by trang** [comment]
@sabretou Can you confirm the icon to be used for this language? Currently @RyckRichards made a pull request with ![cay-icon](https://i.imgur.com/GkkSIpU.png)

**Comment by sabretou** [comment]
I think it's a good icon idea, but I've created a better version. @RyckRichards Please use this one.

https://i.imgur.com/BVRSD6t.png

The template can be used for other Iroquois languages as well.

**Comment by RyckRichards** [comment]
Sure

**Comment by RyckRichards** [comment]
https://github.com/RyckRichards/tatoeba2/commit/5b44fe27b772dab4247a45ca85fcb758a863744e?short_path=c4427a5#diff-c4427a5135a885eeb2473f42bf7b4704
