### ISSUE TITLE
Advanced Search Layout is Wrong, or at least Different

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1738]
https://tatoeba.org/eng/sentences/advanced_search

<img width="1115" alt="screen shot 2019-01-20 at 11 28 42" src="https://user-images.githubusercontent.com/7934273/51434555-b9de1900-1ca6-11e9-805e-ff17c66bcbed.png">

**Comment by alanfgh** [comment]
I saw the behavior ("Translations" group box not aligned with "Sentences" group box) in Chrome on my Android tablet. Then I saw it in Firefox on Windows on the prod site (not on dev). However, I didn't see it in Chrome on Windows on either prod or dev. Then I refreshed my Firefox window and no longer saw it.

**Comment by ckjpn** [comment]
The screenshot was on the Macintosh Chrome.
However, I just cleared my cache and it fixed the problem.
I assume the CSS files are slightly different now.
Perhaps putting a blue announcement on the site suggesting that regular visitors clear their browser caches (if they see strange layout) would be a good idea.

**Comment by trang** [comment]
Displaying a blue announcement is a bit overkill. There are other ways to prevent these cache issues but here I think we'll just let time fix it. It hasn't impacted any of the main features.
