### ISSUE TITLE
Github article "Contributing as a developer" isn't updated

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1748]
The Github article called "Contributing as a developer" (https://github.com/Tatoeba/tatoeba2/wiki/Contributing-as-a-developer) isn't currently updated. The article says that Tatoeba uses CakePHP 2.9, but the latter has been updated to the 3 series, so it would be a useful information for developers to see the updated version.

**Comment by trang** [comment]
I've updated it.
