### ISSUE TITLE
Idea for Twitter Feed - Add, perhaps an automated, weekly announcement with a few stats.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1752]
I noticed there is a link to a Twitter account, but there hasn't been much activity on the account.

https://twitter.com/tatoeba_org

Perhaps, something like the following, once a week, or once a month might be interesting to those following the feed.

There are now currently 00000000 sentences in the Tatoeba Corpus.
0000 of these have audio files.
0000 of these are translated into other languages.
0000 of these sentences are "owned" by native speakers.

Perhaps only the first line, and not other stats would be enough, or perhaps add a few more states.

Maybe this could even be automated, so once a week, shortly after the weekly downloads are created, an announcement would be sent to Twitter.

**Comment by jiru** [comment]
I am not sure that publishing the same message over and over with just numbers changing is very valuable. People might get bored, especially if it’s automated. At least, I think publishing a "now currently x sentences" when x reaches a round number is a better approach.

Speaking of which, @ckjpn you are often reporting news on the Wall, like newly added audio. @trang you sometimes talk about the updates on the Wall. I think that Twitter followers might be more interested into that kind of content. Maybe we could give access to the Twitter account to somebody in charge of publishing news about the project. Trang and I could give that person information about what we’re working on, etc. It’s just about delegating the publishing of news to somebody and deciding on some workflow.

**Comment by ckjpn** [comment]
I guess it doesn't really matter to me.  I was just trying to think of some reason to use/keep the twitter account.  The only time I used to look at it was when I'd get the time-out error, saying check Twitter and the Blog, but I soon realized there never was anything useful or related written there.

It does seem like if Twitter and Facebook are promoted on the website, they should be used.

**Comment by jiru** [comment]
I started a new Wall thread: https://tatoeba.org/wall/show_message/31453
