### ISSUE TITLE
Advanced Search of English with Audio gets an " An Internal Error Has Occurred" Message

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1755]
Advanced Search of English with Audio gets an " An Internal Error Has Occurred"  Message

https://tatoeba.org/eng/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=&tags=&list=&has_audio=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

<img width="1205" alt="screen shot 2019-01-26 at 8 45 51" src="https://user-images.githubusercontent.com/7934273/51778774-eb436280-2146-11e9-883b-6a9bc422ff9e.png">

**Comment by ckjpn** [comment]
Note that this search doesn't get an error.

English with the word "French", audio, sorted by last created.
https://tatoeba.org/eng/sentences/search?from=eng&has_audio=yes&sort=created&query=French

Or this one.
English audio, sorted by last created.  from=eng&has_audio=yes&sort=created
https://tatoeba.org/eng/sentences/search?from=eng&has_audio=yes&sort=created

But this one does.
With only these 2 variables: from=eng&has_audio=yes
https://tatoeba.org/eng/sentences/search?from=eng&has_audio=yes

**Comment by trang** [comment]
Same problem as #1737.

On the [dev website](https://dev.tatoeba.org/eng/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=&tags=&list=&has_audio=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words), where debug is enabled, we can see the root error.

> Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4206592 bytes)
> File /srv/tatoeba.org/www/src/View/Helper/SentencesHelper.php
> Line: 414
