### ISSUE TITLE
Translation is not cached when clicking on "Cancel"

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1759]
Reported by [GrizaLeono on the Wall](https://tatoeba.org/eng/wall/show_message/31223#message_31223).

Steps to reproduce:
- Click on the translation icon of a sentence.
- Write something then click "Cancel".
- Click again on the translation icon.
- The text input is empty.

Expected behavior: the text previously entered should be still there.

**Comment by jiru** [comment]
Fixed by 6e441c384314f65364c8c3d4d2648217ae636e60. Thanks @robbertbrak !
