### ISSUE TITLE
Transcriptions

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1761]
Has not been fully migrated yet (#1733).

Has been reported by [fjay69 on the Wall](https://tatoeba.org/eng/wall/show_message/31201#message_31201):

> Adding alternative script to japanese sentenses causes error : The requested address '/eng/transcriptions/save/4561996/Hrkt' was not found on this server.

**Comment by jiru** [comment]
I think I fixed all the problems related to transcriptions.

**Comment by trang** [comment]
Thank you @jiru! 

I did some tests on the dev and it looks fine.

I ran the command to generate the missing transcriptions (on dev only).
```
bin/cake transcriptions autogen jpn
```
Will have to remember to run it on prod when this is deployed.
