### ISSUE TITLE
Tags not filtered by language

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1764]
Before the CakePHP update, when a user clicked on a tag within a sentence's page, he/she would have been redirected to the tag's page containing all the tags attributed to a sentence only with the language of the original sentence (i.e.: I open a tag attached to an Italian sentence, then I get redirected to a page with just Italian sentences containing that tag, no other languages).

Now, if i try to do that, I see sentences in all languages containing that tag, not only in the language of the first sentence I opened.

**Comment by jiru** [comment]
This only happens on the tag link that is displayed right after adding a new tag. Reloading the page solves the problem. It has nothing to do with the CakePHP update, this bug has always been there.
