### ISSUE TITLE
Regression? Comments that get merged are showing on the home page's comment feed.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1766]
If I remember correctly, the comments that get merged to existing sentences weren't shown on the home page.

<img width="832" alt="screen shot 2019-01-31 at 11 39 17" src="https://user-images.githubusercontent.com/7934273/52026921-ee768e00-254c-11e9-9232-ef06728b161e.png">

**Comment by ckjpn** [comment]
I'm quite certain that the "Sentences Deleted" by Horus didn't show up here before, and they also show up on the home page's comment feed.

**Comment by trang** [comment]
Not a regression. Only Horus' comments are not shown on the homepage. You never noticed before probably because it doesn't happen very often that Horus copies a comment that is a latest comment.
