### ISSUE TITLE
Sentence Counts are Wrong (=0) on List of Lists page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1769]
Using this URL.
https://tatoeba.org/eng/sentences_lists/of_user/CK/audio%20-/page:1/sort:modified/direction:desc

<img width="710" alt="list of list" src="https://user-images.githubusercontent.com/7934273/52158599-27de0380-26dd-11e9-9b9f-c04bb873a36c.png">

However on the actual list's page a non-zero number is shown.

List 4000
<img width="981" alt="list4000page" src="https://user-images.githubusercontent.com/7934273/52158603-39bfa680-26dd-11e9-9c85-8d2fa4167868.png">

**Comment by alanfgh** [comment]
Indeed, yesterday I temporarily turned off the audio for one of nava's sentences so that I could fix the text.

**Comment by trang** [comment]
Steps to reproduce:
- Remove a sentence from a list.
- The count is reset to zero.
