### ISSUE TITLE
Browse sentences with audio is missing now.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1770]
https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/only-with-audio
Note that the "with audio" option is missing.

**Comment by trang** [comment]
It was removed on purpose: 84ffe2ec28932fb8a2e2cda1a7c05c3100b154d6

Is there something you need to do but are no longer able to do now that the page is removed?

**Comment by ckjpn** [comment]
I just felt that it likely was faster and put less of a load on the server than doing looking for the latest sentences with audio with the advanced search.

If that's not the case, then it doesn't really matter to me that the function was removed.

The only thing it would really affect would be a member who wants to start with the newest sentence with audio and browse all of them, but I doubt many members would do that.

**Comment by ckjpn** [comment]
Perhaps it would be a good idea to add a link to the appropriate advanced search that replaces the "browse by audio."

https://tatoeba.org/sentences/search?sort=created&has_audio=yes&from=eng

All you would have to do is replace the "eng" variable in the above URL to match the language being browsed.

**Comment by trang** [comment]
This link would make more sense in the "Browse audio" page. But until there's actually more demand for this, I'll skip it.
