### ISSUE TITLE
Wrong direction while using the Latin script within Ottoman Turkish

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1780]
As reported by soliloquist on the wall:

> I have problems adding Ottoman Turkish sentences written in Latin script. The punctuation order gets corrupted and it looks weird. The system only works properly when using Arabic script with Ottoman Turkish.
> 
> Some languages are written in more than one script. Like Azerbaijani (Latin, Arabic and Cyrillic), Kurdish (Latin and Arabic) or Serbian (Latin and Cyrillic).
> 
> I guess there are Serbian sentences written in both Latin and Cyrillic scripts on Tatoeba. It isn't a problem when the script direction is same as in Serbian, but if the direction is different, it becomes difficult to use the script other than the 'default' one.
> 
> Can't something be done about it?

https://tatoeba.org/ita/wall/show_message/31315#message_31315

**Comment by Guybrush88** [comment]
examples of this are on dev

**Comment by soliloquist-tatoeba** [comment]
Thanks for carrying the issue I mentioned on the Wall to Github.

Actually, this problem isn't limited to Ottoman Turkish. It affects all languages that can be written in both left-to-right and right-to-left scripts. Sentences written in the non-default script gets visually corrupted. Languages using Latin & Cyrillic scripts are not affected from this as they're both left-to-right, but others using Latin & Arabic scripts do.

**Comment by soliloquist-tatoeba** [comment]
Some affected languages

Ottoman Turkish
Ottoman Turkish is a historical language written in the Arabic script, but today, many Turks write Ottoman Turkish expressions in the Latin script. There are many transliterated Ottoman Turkish examples in literature textbooks. It's easier to read and learn the old language this way.

Kurdish 
https://en.wikipedia.org/wiki/Kurdish_alphabets

Uyghur
https://en.wikipedia.org/wiki/Uyghur_alphabets
https://en.wikipedia.org/wiki/Uyghur_Latin_alphabet

Azerbaijani
https://en.wikipedia.org/wiki/Azerbaijani_alphabet

**Comment by trang** [comment]
Currently we define the direction based on the language:
https://github.com/Tatoeba/tatoeba2/blob/dev/src/Lib/LanguagesLib.php#L605

We will need to base it on the script instead.

**Comment by jiru** [comment]
We could just set the direction to "auto". I believe an easy and non-harmful way to solve the problem.

**Comment by soliloquist-tatoeba** [comment]
The other issue reported on the same thread about Chinese is fixed. If a simple and nonharmful solution is possible with a few code changes as jiru suggested, can we give it a try? You can revert back if something goes wrong or apply it to other languages in the future if it works fine.

**Comment by trang** [comment]
Yes, we can definitely use `dir="auto"` for Ottoman Turkish. I think as well that it's an appropriate solution.

**Comment by soliloquist-tatoeba** [comment]
Thank you. Please inform me when it's implemented, so I can test it report back to you.

**Comment by trang** [comment]
@soliloquist-tatoeba It's implemented and deployed on our dev website. I added the same two sentences you added on the main website and set the language to Ottoman Turkish: https://dev.tatoeba.org/eng/sentences/show/6784589.

Feel free to test further and close this issue if it looks fine for you.

It will be deployed to the main website this weekend.

**Comment by soliloquist-tatoeba** [comment]
I have just tested and it works great. Both RTL and LTR sentences are shown correctly. The cosmetic issue seems to be resolved. Thank you very much. I also thank jiru for the idea and Guybrush for opening the issue.

If a similar request comes from Uyghur or Kurdish speakers in the future, you can just apply the same thing on those languages, too. They're in a similar situation.
