### ISSUE TITLE
When linking sentences in the advanced search, more languages appear, even if they're not selected in the user's profile

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1783]
as reported by Aiji on the wall:

> Advanced search:
> English, display translations in French
> Limit to sentences having French indirect translations.
> 
> Only English and French are displayed.
> 
> Link one French => All translations are now displayed.
> 
> Is it intended behavior?
> (I do not think so, and that is quite a bother when doing some linking work)

second post:

> If I link one French sentence, then all translations will appear.
> The problem will not happen if you restrict the langages to be displayed in your profile. That's usually how I do it, but this time I forgot so I faced this situation (maybe I, or somebody else, already mentioned it in the past).

https://tatoeba.org/ita/wall/show_message/31332#message_31332

**Comment by ckjpn** [comment]
The same thing happened before the update to the latest CakePHP, so it's not a change in the way the website works.

It never really bothered me.  However, I can see how it might be irritating on a smart phone.

**Comment by ckjpn** [comment]
Actually, this is very irritating when trying to do something like that following.

1. Find all English sentences with audio that have an indirect link to a Japanese sentence.

https://tatoeba.org/eng/sentences/search?query=&from=und&to=jpn&orphans=no&unapproved=no&user=&tags=&list=4000&has_audio=&trans_filter=limit&trans_to=jpn&trans_link=indirect&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

2. Link the indirectly-linked Japanese that match.

What happens is that all the other translations appear at this point, and you have to scroll past them all.


If this behavior could be changed, it would be a lot faster to get matching indirectly-linked sentences linked.

**Comment by jiru** [comment]
I think this regression has been introduced by 5be6155f1ac3de8e06c124f72ac233db5a81b67b.
