### ISSUE TITLE
Sentences with tags are not sorted anymore by sentence's contribution date

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1785]
Before the CakePHP update, when browsing the page containing all the sentences with a given tag (i.e. https://tatoeba.org/ita/tags/show_sentences_with_tag/5616), the user had the possibility to sort the sentences according to the date when the tag was added or when the sentence itself was added (more details on how this worked in this ticket: #1604).
Now, sentences are sorted only according to the date when the tag was added. The default order is older tags first, and in the next pages there are the newer tags; when clicking on the "date of tag" link, it's the other way round (newer tags first, and in the next pages there are the older tags).

**Comment by trang** [comment]
There was never the option to order by sentence contribution date for the tags. It was only for the lists.

I think the description in #1604 was mixing up certain things. It seems that you used the "date of tag" link sorting to sort both by date of tag and date of contribution. Click once: it sorts by date of tag, click again: it sorts by date of contribution.

I don't think it was the behavior though. I think it was probably just a coincidence that the reversed order kind of matched the date of contributions. But in fact it was always sorted by date of tag.

**Comment by Guybrush88** [comment]
I somehow remember that they were sorted more likely also by ID, rather than the date of the sentence
