### ISSUE TITLE
Can't change sentence from Korean into Japanese

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1787]
Related by https://tatoeba.org/eng/user/profile/Leolaaziano on https://tatoeba.org/eng/sentences/show/7780160

> I was not able to save the sentence in Japanese, so I decided to save it firstly as a Manchu sentence, then Japanese. But then I realized that it still cannot be switched to Japanese. (Sorry for the tautology) Can you please explain it?

As a CM I tried to change this sentence into Japanese but I couldn't. It kept spinning forever. I cleaned my cache. I was using Chrome for Windows 7

**Comment by LiSongcheng** [comment]
Same problem here, I was using Safari (12.0.1) on MacOS Mojave. This happened to me when I was adding, translating sentences to Japanese.

**Comment by ckjpn** [comment]
Google Chrome JavaScript console gives this error message.

/eng/sentences/change_language/:1 Failed to load resource: the server responded with a status of 500 ()

**Comment by trang** [comment]
I was able to change the language. Perhaps this was fixed with 15809624141a97b765c9f496b1fdf81aedf00cb7.

**Comment by jiru** [comment]
@trang I think so too. The commit you mentioned makes the bug only happen when transcriptions are enabled, so it’s part of #1761.
