### ISSUE TITLE
Sentence is duplicated after pressing the "translate" button

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1792]
Steps to reproduce

- Add a sentence in https://tatoeba.org/eng/sentences/add

- Click on the "translate" button. The same sentence will appear again

![tatoeba issue](https://user-images.githubusercontent.com/7658430/53038228-f4c89d80-345a-11e9-8d46-9e3d17abcb18.png)

We'd expect the field be in blank.

Note: It doesn't happen when after you add a 2nd translation.

**Comment by ckjpn** [comment]
Duplicate

https://github.com/Tatoeba/tatoeba2/issues/1778
