### ISSUE TITLE
Different behavior now with adding "OK rating and adding to Lists on https://tatoeba.org/eng/sentences/show_all_in/eng/und

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1793]
Before I used to be able to add both the OK rating and add a sentence to List 907 from this page.

https://tatoeba.org/eng/sentences/show_all_in/eng/und

I can still do that, but only if the sentence is added to the list first, and the OK rating added second.
Before, the order this was done didn't matter and I usually did it in the reverse order.

As long as I remember to do things in this order, this doesn't matter so much to me, but I thought you would like to know that this doesn't work like it used to.

**Comment by AndiPersti** [comment]
I cannot reproduce this problem. Rating a sentence and adding it to a list works in both orders for me.

**Comment by trang** [comment]
@ckjpn, is this bug still happening for you?

**Comment by ckjpn** [comment]
>@ckjpn, is this bug still happening for you?

No.
