### ISSUE TITLE
Error message on top of a page

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1794]
I just opened a custom query within the advanced search on prod (this one: https://tatoeba.org/ita/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=ck&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&page=2&sort=created&direction=asc) and I got these error messages: 

Warning (2): session_start(): Unable to clear session lock record [CORE/src/Http/Session.php, line 356]

Warning: mkdir() [function.mkdir]: Permission denied in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 93

Warning: mkdir() [function.mkdir]: Permission denied in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 93

Warning: mkdir() [function.mkdir]: Permission denied in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 93

Warning: file_put_contents(/var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/logs/error.log) [function.file-put-contents]: failed to open stream: No such file or directory in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 133

the page works properly, though

**Comment by Guybrush88** [comment]
I just got these error messages while adding a new translation:

Notice (8): Undefined offset: 1 [APP/Lib/SphinxClient.php, line 621]


Warning: mkdir() [function.mkdir]: Permission denied in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 93

Warning: mkdir() [function.mkdir]: Permission denied in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 93

Warning: mkdir() [function.mkdir]: Permission denied in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 93

Warning: file_put_contents(/var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/logs/debug.log) [function.file-put-contents]: failed to open stream: No such file or directory in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 133

Notice (1024): Unable to update Sphinx attribute(s) (user_id, ucorrectness): expected searchd protocol version 1+, got version '0' [APP/Model/Behavior/SphinxBehavior.php, line 290]


Warning: file_put_contents(/var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/logs/debug.log) [function.file-put-contents]: failed to open stream: No such file or directory in /var/www-prod-1b4af999c67e86ace8690b507306fdeb1ef5db29/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 133

**Comment by trang** [comment]
So, the prod website had debug enabled, that's why you're seeing these errors. Aside of seeing errors, do you have any unwanted behavior?

**Comment by Guybrush88** [comment]
apart from these errors, everything was a bit slower than usual
