### ISSUE TITLE
Error on a specific page

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1807]
Accessing the page https://tatoeba.org/fra/users/for_language brings up a 500 error:

> An Internal Error Has Occurred
> Error: An Internal Error Has Occurred.

**Comment by AndiPersti** [comment]
I currently don't get that error.

@jiru: Out of curiosity, why do you think that's a good first issue?

**Comment by jiru** [comment]
You are right. It turns out I fixed it in 86f492897d17eb22cca470c009ded3f41e6529bf. I put the good first issue label because I thought it was trivial to fix.

**Comment by AndiPersti** [comment]
> You are right. It turns out I fixed it in [86f4928](https://github.com/Tatoeba/tatoeba2/commit/86f492897d17eb22cca470c009ded3f41e6529bf).

I see. Since I couldn't reproduce it easily and there weren't no more details available it didn't look like an easy bug to me.
But it was indeed trivial to fix. :-)
