### ISSUE TITLE
Error message when posting a comment on a sentence

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1809]
I was trying to post a comment on a sentence, and, instead of the actual result (the comment being actually posted), I got this error message:

> The request has been black-holed
> 
> Errore: The requested address '/ita/sentence_comments/save' was not found on this server.

After the page was refreshed, the comment was properly posted, so I guess it's not a frequent error.

**Comment by jiru** [comment]
Maybe the CSRF protection kicked in. Did you open the sentence page as a guest, log in from another tab or window and then post the comment from the initial tab or window? If not, was the sentence page opened for a long time before you posted your comment?

**Comment by Guybrush88** [comment]
I wasn't logged out. I don't think it was opened for a long time, I'm pretty sure it was less than a minute.

**Comment by Yorwba** [comment]
I hit this bug today. I had the tab open overnight and had opened at least one other Tatoeba tab in the meantime. I was logged in the whole time and have "remember me" enabled.

I was able to make Firefox repeat the request and have it fail again, so I could record the request and compare it to a subsequent successful request. The `_csrfToken` and other parameters were identical, except for the `_Token[fields]` parameter. It looks like `random_hexadecimals%3Asentence_id` and the random hexadecimal part differed between requests.

**Comment by agrodet** [comment]
I hit that bug several times recently, not only in comments. For example, when I wrote the weekly recap. It takes a long time, because I do everything inside the textarea. When I finally sent the message, maybe one hour later or so, boum, black-holed. I thought about reproducing the problem and look for the problem but since Yorwba did it :P
