### ISSUE TITLE
Cannot add sentences to collaborative list

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1811]
Steps to reproduce:
- Go to any sentence's page.
- Click the list button on the sentence's menu.
- Select a list in the group "Add to a collaborative list" and click "OK".
- Go the the list's page, the sentence is not there.

**Comment by ckjpn** [comment]
Also, note that you can delete sentences from collaborative lists either.

I tried to delete a couple on this list.
https://tatoeba.org/eng/sentences_lists/show/992

**Comment by ckjpn** [comment]
Note that I could add sentences to a collaborative list that I made, so apparently the owner of the list can add sentences.

https://tatoeba.org/eng/sentences_lists/show/9012
