### ISSUE TITLE
Make it possible to listen to audio on comment feed.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1812]
https://tatoeba.org/eng/sentence_comments/of_user/xorgy

I think we had the audio player on comments before the "new look".
It would be nice to have the audio icon showing on comments.

<img width="735" alt="Screen Shot 2019-03-09 at 13 52 47" src="https://user-images.githubusercontent.com/7934273/54066442-2a4ef280-4273-11e9-88ad-d1aeea515e25.png">

**Comment by jiru** [comment]
> It would be nice

Any reason other than being nice? From your screenshot, it looks like your use-case is when the comment is about audio. However, if comment is true, the audio doesn’t match, so you want to go to the sentence page to fix it. If the comment is not true, the audio does match, so you want to go to the sentence page to answer the comment. Either way, you need to go to the sentence page.

Maybe I’m wrong, I’m just trying to understand your use-case. :smile: 

Related: #1592.

**Comment by ckjpn** [comment]
You're right that I have to go to the page anyway if a change needs to be made.
It's nice to be able to verify things without going to the page, but not necessary.
Perhaps when you fix  #1592, the comments will look the same, so maybe this one can be closed.

**Comment by trang** [comment]
Note that with #1592, the audio button will be added to the sentence block but not to the comments.

The present use-case is not strong enough to justify adding audio in the comments. Closing.
