### ISSUE TITLE
Colors of changed sentences aren't updated anymore in the "latest contributions" page

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1813]
I just noticed a trivial regression: before the CakePHP update, when a sentence was immediately changed, the color of the original version went from green to grey, while showing the new version had yellow. After the update, the new version is still yellow, but the original version remains green, and not grey anymore, as it was before the update.

Steps to reproduce this regression:
1. Add a new sentence;
2. Change it;
3. Open https://tatoeba.org/eng/contributions/latest to see what was logged.

**Comment by trang** [comment]
Wasn't the grey color just for modifications, in case there are several modifications in row, to indicate that it is not the latest modification?

**Comment by trang** [comment]
Nope it wasn't. It's indeed a regression. Screenshots of the feature: #1301.
