### ISSUE TITLE
An easier way to split long lists but keep them "linked" to the original list

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1814]
Following what [Alan wisely posted on the Wall](https://tatoeba.org/eng/wall/show_message/31486#message_31486)

> As for your second question, you mentioned a list of 280 sentences, many of which are already translated into various languages. I'm not sure I understand your request. Are you asking for volunteers to go through the entire list and fill in the gaps? In which languages? In my experience, such requests are more likely to be fulfilled if you can (a) explain what makes these sentences more worthy of being translated than others (for instance, "These sentences contain vocabulary that isn't translated in existing sentences" or "These sentences contain grammatical constructions that I want to learn"), (b) limit the length of the list (280 is very long), (c) choose a particular language that you want them translated into, and (d) make it easy for people to measure their progress by distinguishing between the sentences that have already been translated and the ones that haven't.

I've been creating lists with sentences I really liked and sentences I want to study (grammar, vocabulary, etc) and I ask people to translate them. However, some sentences are already translated into German for example. Isn't there a way to split the list to filter sentences that wasn't translated into German if I request? Also, filtering them according another criteria I'd have?

**Comment by ckjpn** [comment]
> Isn't there a way to split the list to filter sentences that wasn't translated into German if I request?

You can use the advanced search to do this.

Sentences on the list of your audio recordings that don't yet have direct German translations.

https://tatoeba.org/eng/sentences/search?query=&from=por&to=deu&orphans=no&unapproved=no&user=&tags=&list=7039&has_audio=&trans_filter=exclude&trans_to=deu&trans_link=direct&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

Just choose the list you want on the right side of these results. 
"Belongs to list"

**Comment by trang** [comment]
@RyckRichards I think the solution, suggested by CK, of using the advanced search is good enough for what you wanted to do. Please confirm and close this issue if that's the case.

**Comment by RyckRichards** [comment]
Yes, I can confirm that. Closing this and sorry for the inconvenience :
