### ISSUE TITLE
Tigre (tig)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1815]
* Language name: Tigre
* Language info: https://en.wikipedia.org/wiki/Tigre_language
* ISO 639-3 code: tig
* Public List: https://tatoeba.org/eng/sentences_lists/show/8734
* Icon: https://i.imgur.com/oPvLYtd.png
* Requested by: https://tatoeba.org/eng/user/profile/dagnaq

[for tatoeba.org]
CALL add_new_language('tig', 8734);

**Comment by sabretou** [comment]
Additionally, the icon for Tigrinya needs to be changed. This is because Eritrea does not accord any special status to Tigrinya, and so the language will use a 'code' icon similar to Tigre.

ISO code: tir
Icon: https://i.imgur.com/PQIR6rW.png

**Comment by jiru** [comment]
Note that one of the sentence of the list (6018317) is in Tigrinya already. Should this sentence be switched to Tigre or kept in Tigrinya?

**Comment by sabretou** [comment]
@jiru This sentence appears to be by a different user who does not identify as a Tigre speaker. It is best we leave that sentence as a Tigrinya sentence and only change the other two sentences.
