### ISSUE TITLE
Ligurian (lij)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1820]
* Language name: Ligurian
* Language info: https://en.wikipedia.org/wiki/Ligurian_(Romance_language)
* ISO 639-3 code: lij
* Public List: https://tatoeba.org/eng/sentences_lists/show/8784
* Icon: https://i.imgur.com/1EBUgiP.png
* Requested by: https://tatoeba.org/eng/user/profile/JeanM

[for tatoeba.org]
CALL add_new_language('lij', 8784);

**Comment by RyckRichards** [comment]
Created a PR using a .svg language icon
