### ISSUE TITLE
New icon for Middle English (enm)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1821]
The icon we will be using for Ligurian (lij) is the Flag of Genoa, which is almost indistinguishable from the flag of England (used for the icon of Middle English). To distinguish the two flags, we should use language codes affixed to the icons.

Therefore, the flag of Middle English should be this: https://i.imgur.com/f2WILtB.png

**Comment by RyckRichards** [comment]
Hope I did everything correctly :+1:
