### ISSUE TITLE
New icon for Tigrinya (tir)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1822]
The icon we are currently using for Tigrinya is the flag of Eritrea. However, we are adding another Eritrean language to Tatoeba: Tigre.

According to the Eritrean Ministry of Information, all Eritrean languages are considered equal. (http://www.shabait.com/about-eritrea/eritrea-at-a-glance/49-eritrea-at-a-glance)

Therefore, we should change the icon of Tigrinya so that it uses the language code, similar to Tigre. Here is the icon that Tigrinya should use: https://i.imgur.com/owKMvQm.png

**Comment by tigrinya** [comment]
This sounds good to me. As a contributor to both Tigre and Tigrinya, it makes sense to indicate the language code along with the flag.
