### ISSUE TITLE
CSS for Edited Sentences Isn't Working Correctly.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1829]
The one that is supposed to turn gray, is green.

<img width="755" alt="Screen Shot 2019-03-15 at 16 29 25" src="https://user-images.githubusercontent.com/7934273/54415511-d09d6b00-473f-11e9-9a66-f8ea1f88227a.png">

**Comment by Guybrush88** [comment]
this was already fixed: https://github.com/Tatoeba/tatoeba2/issues/1813
