### ISSUE TITLE
allow multiple audio files per sentence

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#183]
This would of course require changes to the database schema and UI, but it would help users, who repeatedly request this feature. Assuming we have a working duplicate merging script (see #182) by the time we made this change, we'd need to make sure that we preserve the links to the various audio files for each merged sentence.

**Comment by ckjpn** [comment]
While maybe not a high priority, this is something that definitely be done eventually.

1. Members with different dialects or accents could contribute audio for the same sentence.

2. Sentences with the same spelling, but different meanings could be contributed.

Example:
I read my horoscope every day.
https://tatoeba.org/eng/sentences/show/4563313
(habitual vs. past tense)

3. Even members with the same dialect could contribute alternate recordings.  Perhaps not as necessary, but this could also be helpful.

**Comment by jiru** [comment]
To whoever will implement this: read commit 61e9e43933bfaee4f3eb0ef49620f90681f6754d.

**Comment by ckjpn** [comment]
Here are 2 mp3 files of the same sentence with intonation differences.
I've uploaded them here in case my links above ever become "not found."
It's a different sentence, but I uploaded one of these today. It would have been nice to be able to upload both of them.

You don't think I'm going to do that, do you?
[6236802-2 files with different intonation.zip](https://github.com/Tatoeba/tatoeba2/files/5026761/6236802-2.files.with.different.intonation.zip)
Uploaded as a zip, since MP3 files can't be directly added here.

**Comment by jiru** [comment]
@ckjpn Thanks! I think you could as well upload these yet-to-be-imported recordings to our server pretty much the same way you upload regular audio. I just set up a new directory called `github_issue_183` for you. You can upload them here. Choose any naming convention as long as it’s consistent.

**Comment by ckjpn** [comment]
I created a folder in that folder named "eng."

These seem to be the situations in for different recordings.

1. The same voice, different intonations, or other differences, possibly no difference in meaning.
2. The same voice, different intonations or other differences, with different meanings. 

3. The same voice, a duplicate recording, but basically the same.
4. A different voice.
5. Another different voice.

At this point, 3, 4, 5 are only accidental duplications, since I try to make sure that I don't record the same sentence again, and that others aren't duplicating each other's work.

**Comment by ckjpn** [comment]
To get an idea of audio files in different dialects, you can use this advanced search.
This is sort of a preview of what would be possible.

Search for English with audio for a number of words with UK spelling, or vocabulary, linked to other English sentences with audio.  A number of these are the same sentence with more than one dialect.

One possible query:

favourite|colour|centre|cinema|neighbour|behaviour|postman|tyres|favour|mum|lorry|apologise|=maths|motorcar|=travelling|=travelled|"the lift"|practise|licence|telly

https://tatoeba.org/en/sentences/advanced_search?from=eng&has_audio=yes&native=&orphans=no&query=favourite%7Ccolour%7Ccentre%7Ccinema%7Cneighbour%7Cbehaviour%7Cpostman%7Ctyres%7Cfavour%7Cmum%7Clorry%7Capologise%7C%3Dmaths%7Cmotorcar%7C%3Dtravelling%7C%3Dtravelled%7C%22the+lift%22%7Cpractise%7Clicence%7Ctelly&sort=relevance&sort_reverse=&tags=&to=eng&trans_filter=limit&trans_has_audio=yes&trans_link=&trans_orphan=&trans_to=eng&trans_unapproved=&trans_user=&unapproved=no&user=

**Comment by jiru** [comment]
I implemented this.

**Comment by ckjpn** [comment]
Maybe it's not a problem, but the number of total audio files went down by 4.

Yesterday, when I finished uploading files it was this.
Sentences with audio (total 998,888)

This morning (my time), it was this.
Sentences with audio (total 998,884)

Perhaps an admin unlinked 4 audio files overnight. That might be the reason.


URL: https://tatoeba.org/en/audio/index

**Comment by ckjpn** [comment]
This may be a problem.

I've only tried it a few times, but the following page took a very long time to load.

https://tatoeba.org/en/audio/index

Two times I tried it, I got the error message that gets displayed when we have time-out errors. 

> Tatoeba is currently unavailable. We are sorry for the inconvenience. You can check our blog or Twitter for more information.

(Not really a time-out error message, but a message saying that tatoeba.org is offline.)

**Comment by ckjpn** [comment]
Note that it's implied that one audio file can be disabled, leaving the other one enabled.
However, the save button doesn't actually save the setting.

https://tatoeba.org/en/sentences/show/2958714
<img width="322" alt="Screen Shot 2022-05-30 at 9 53 54" src="https://user-images.githubusercontent.com/7934273/170899348-4b5a6e56-bd11-4e72-a02a-e1ba08fc66b5.png">

**Comment by ckjpn** [comment]
Note that it is possible to have one audio file disabled and another one enabled.
To do so, I had to uncheck "is enabled" and save the early audio file before importing the new file.

https://tatoeba.org/en/sentences/show/10869364
Temporarily, I left this online for you, but I plan to delete the first one in the near future.

**Comment by ckjpn** [comment]
Here is one example with 5 audio files.

https://tatoeba.org/en/sentences/show/280288
Birds of a feather flock together.

**Comment by ckjpn** [comment]
This seems to be a bug.
I can't disable this one to edit the text.

https://tatoeba.org/en/sentences/show/3991877
