### ISSUE TITLE
/audio/import showed an error message, but there was no problem

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1834]
This is only an alert to let you know that this has happened.

All the listed files were actually imported, and the import directory is actually empty.

<img width="760" alt="Screen Shot 2019-03-22 at 14 34 42" src="https://user-images.githubusercontent.com/7934273/54802756-00082680-4cb0-11e9-9ee3-2698e8a53f49.png">

If this is not a symptom of another problem, you can close this issue, I think.

**Comment by jiru** [comment]
Closing because I’m unable to reproduce and it’s temporary error.
