### ISSUE TITLE
Dhivehi (div)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1851]
* Language name: Dhivehi
* Language info: https://en.wikipedia.org/wiki/Maldivian_language
* ISO 639-3 code: div
* Public List: https://tatoeba.org/eng/sentences_lists/show/8830
* Icon: https://i.imgur.com/XKA1rVR.png
* Requested by: https://tatoeba.org/eng/user/profile/evenxzero

[for tatoeba.org]
CALL add_new_language('div', 8830);

**Comment by jiru** [comment]
Note: this language uses the [Thaana script](https://en.wikipedia.org/wiki/Thaana). We need to add it to the Sphinx charset table.

**Comment by RyckRichards** [comment]
Is there a reason for this language not being implemented? :/

**Comment by trang** [comment]
@RyckRichards It requires to update the sphinx config. See comment: https://github.com/Tatoeba/tatoeba2/pull/1855#issuecomment-480477645

Although it's not a blocking issue to merge the request itself. But without it, the sentences in this language would not be searchable.
