### ISSUE TITLE
Sudanese Flag isn't .png like the others.  It's sun.svg

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1859]
It think this should be changed to .png, so it matches our other flags.

https://tatoeba.org/img/flags/sun.svg

For me personally, it makes a difference on the set of useful links I created for members.

http://study.aitech.ac.jp/tatoeba/translate/links.php?f=eng&t=sun&u=qsanta

**Comment by jiru** [comment]
All the flags are now SVG (see #1806). Sorry for the inconvenience, but you will have to update your links.
