### ISSUE TITLE
"Show translations in" doesn't work from a list page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1860]
When I choose "Show translations: English" from this list page:

https://tatoeba.org/eng/sentences_lists/show/8795/eng

translations are shown in all languages. This was not the case in the past, so I think it's a regression.

![non-English_translations](https://user-images.githubusercontent.com/1213027/55684049-c45a9700-5914-11e9-9306-07ebeff9f827.png)

**Comment by trang** [comment]
It is very likely the same root cause as #1798.
