### ISSUE TITLE
The "has audio" tag is obsolete and is unneeded.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1864]
The "has audio" tag is obsolete and is unneeded.
I would suggest deleting them all.

https://tatoeba.org/eng/tags/show_sentences_with_tag/2448

1. While on a sentence, it's easy to see the audio player icon.
2. We can browse audio.
3. We can limit searches to audio.

While the "has audio" tag doesn't really interfere with the way the website works, the implication to a new visitor who lists all sentences with this tag is that we only have very few sentences with audio, so it is a bit confusing.

This should be fairly simple to do for anyone with direct access to the database.

**Comment by trang** [comment]
There is an issue about having the possibility to delete tags from the UI: #330. I suggest closing this issue and report any obsolete/unneeded tags in #330. Then we can clean up the tags once #330 is implemented.

**Comment by ckjpn** [comment]
You will have to delete it. I can't.
