### ISSUE TITLE
Wrong dates while using the Turkish UI

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1866]
As reported by Gulo_Luscus on the Wall:

> The dates on several pages are incorrect when the interface is in Turkish.
> 
> I tried this with several interface translations, and the bug seems to exist only with the Turkish language.
> 
> I tested it with a desktop and laptop (Windows 10) (Chrome and Opera) and an iPhone (Safari). The result is the same.
> 
> 
> Screenshot of the Wall (latest messages):
> 
> [https://app.box.com/s/pelpabapy...4luncky1ssbkxx](https://app.box.com/s/pelpabapykqapt6e3x4luncky1ssbkxx)
> 
> (1 saat önce = 1 hour ago)
> 
> 
> Screenshot of a comment on a random sentence:
> 
> [https://app.box.com/s/59rt4exrw...13kuvb9nqxfgnm](https://app.box.com/s/59rt4exrw2gfkxyodm13kuvb9nqxfgnm)
> 
> (dün = yesterday)

https://tatoeba.org/ita/wall/show_message/31690#message_31690

**Comment by soliloquist-tatoeba** [comment]
Turkey changed its time zone in 2016. 

https://en.wikipedia.org/wiki/Time_in_Turkey

I don't know if it has anything to do with this bug, but perhaps there might be some codes that need to be updated.

**Comment by jiru** [comment]
The problem comes from a bug in CakePHP, it assumes that Turkish has no plurals.

@soliloquist-tatoeba In order to fix the problem in CakePHP, I need to ask you a question about Turkish. Does Turkish use plural or singular when the number is zero? For example, [English uses plural](https://english.stackexchange.com/questions/38293/why-is-zero-followed-by-a-plural-noun): "I have zero tomatoes" . In French, we use singular: j’ai zéro tomate. What about Turkish?

[Unicode.org](https://unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html) says zero is plural, [launchpad.net](https://translations.launchpad.net/+languages/tr) too, but [this localization guide](https://localization-guide.readthedocs.io/en/latest/l10n/pluralforms.html) says it’s singular. I’m confused so I’m asking you to be sure.

**Comment by soliloquist-tatoeba** [comment]
>Does Turkish use plural or singular when the number is zero? 

It uses singular, if a number is given (no matter what the number is). 

I have zero tomatoes = Sıfır domatesim var (it's singular)

**Comment by jiru** [comment]
I see. If I look at the example sentences from the [unicode.org table](https://unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html), it shows some differences, but these differences are not on the countable object:

> 1: Sepetinizde 1 X var. (Google translate: You have 1 X in your cart.)
> 2: Sepetinizde 2 X var. (Google translate: You have 2 X in your cart.)

> 1: Bunu almak istiyor musunuz? (Google translate: Do you want to get this?)
> 2: Bunları almak istiyor musunuz? (Google translate: Do you want to take these?)

This suggests we need to handle plural forms in Turkish even though the countable object does inflect.

@soliloquist-tatoeba I compiled a list of sentence pairs from our PO files in which having plural does seem to change the translation in Turkish:

> Contains 1 sentence
> 1 cümle içerir

> Contains 2 sentences
> 2 cümle var

> Please fix the following error or press the Cancel button.
> Lütfen belirtilen hatayı düzeltin veya Vazgeç tuşuna basın.

> Please fix the following errors or press the Cancel button.
> Lütfen belirtilen hataları düzeltin veya Vazgeç tuşuna basın.

> Wall (one thread)
> Duvar (bir başlık)

> Wall (2 threads)
> Duvar (2 konu)

In these pairs, can you confirm that the plural version needs to be different than the singular? If yes, can you tell what would be the translation if the number is zero?

**Comment by soliloquist-tatoeba** [comment]
>Contains 1 sentence
>1 cümle içerir

>Contains 2 sentences
>2 cümle var

>Wall (one thread)
>Duvar (bir başlık)

>Wall (2 threads)
>Duvar (2 konu)

The differences in these translations ('içerir-var' and 'konu-başlık') have nothing to do with singularity or plurality. They are all singular just translated with different words. This isn't necessary. I think it would be better if both forms were same.

0 cümle içerir
1 cümle içerir
2 cümle içerir

0 konu
1 konu
2 konu

(They are all singular)


>1: Bunu almak istiyor musunuz? (Google translate: Do you want to get this?)
>2: **Bunları** almak istiyor musunuz? (Google translate: Do you want to take these?)

>Please fix the following error or press the Cancel button.
>Lütfen belirtilen hatayı düzeltin veya Vazgeç tuşuna basın.

>Please fix the following errors or press the Cancel button.
>Lütfen belirtilen **hataları** düzeltin veya Vazgeç tuşuna basın.

There is no specific number given in these strings so Turkish uses both singular and plural forms just as English does. I bolded the words in plural form.

**Comment by jiru** [comment]
I see. This suggests that even though we don’t have pluralized strings that are to be translated differently in Turkish, it may happen in the future, or it may already be the case for some strings that are still untranslated. So we do need pluralized translations for Turkish. I [opened a PR at CakePHP](https://github.com/cakephp/cakephp/pull/13209) to fix the original problem. Once it is merged and we update our version of CakePHP, the problem with the dates should be solved.

**Comment by soliloquist-tatoeba** [comment]
So, this is a problem beyond Tatoeba, and fixing it will positively affect the Turkish UIs of other projects, too. Thanks for your concern.

**Comment by jiru** [comment]
Yes, exactly! :smiley: Now we need to wait until the [next version of CakePHP (3.7.8)](https://github.com/cakephp/cakephp/milestone/197) is released.

**Comment by Guybrush88** [comment]
CakePHP 3.7.8 has been released: https://bakery.cakephp.org/2019/05/29/cakephp_378_released.html
