### ISSUE TITLE
Chinese Pidgin English (cpi)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1867]
* Language name: Chinese Pidgin English
* Language info: https://en.wikipedia.org/wiki/Chinese_Pidgin_English and https://en.wikipedia.org/wiki/Nauruan_Pidgin_English
* ISO 639-3 code: cpi
* Public List: https://tatoeba.org/eng/sentences_lists/show/8945
* Icon: https://imgur.com/a/nBG8eDd
* Requested by: https://tatoeba.org/eng/user/profile/naurugott

[for tatoeba.org]
CALL add_new_language('cpi', 8945);

**Comment by RyckRichards** [comment]
Is there a reason for this language not being implemented? :/

**Comment by trang** [comment]
No particular reason, I actually forgot about it.

**Comment by trang** [comment]
Actually, the name should be Chinese Pidgin English, right? "Pidgin" and "English" have been swapped here (@sabretou).

**Comment by sabretou** [comment]
@trang That is correct, the name is Chinese Pidgin English. I'm sorry for the mistake!

**Comment by trang** [comment]
No worries :)
