### ISSUE TITLE
Ngeq (ngt)

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#187]
* Language name: Ngeq (however, it's called Ta'Oi - tth)
* Language info: https://en.wikipedia.org/w/index.php?title=Ta%E2%80%99Oi_language&redirect=no // * https://en.wikipedia.org/w/index.php?title=Ta%E2%80%99Oi_language&redirect=no
* ISO 639-3 code: ngt http://www-01.sil.org/iso639-3/documentation.asp?id=ngt
* Public List: http://tatoeba.org/eng/sentences_lists/show/3386
* Icon: Maybe this one? http://joshuaproject.net/assets/media/profiles/maps/m15260_vm.png
* Requested by: **cueyayotl** - https://tatoeba.org/eng/user/profile/cueyayotl

> More info> http://www-01.sil.org/iso639-3/documentation.asp?id=ngt

> Previously called "Ngeq" and now, "Ta'Oi"
-https://en.wikipedia.org/w/index.php?title=Ngeq_language&redirect=no

![1](https://cloud.githubusercontent.com/assets/7658430/10393451/5f9d6852-6e66-11e5-8ef8-80cfefae3291.PNG)

TODO
`CALL add_new_language('ngt', 3386);`

**Comment by RyckRichards** [comment]
I pm cueyayotl to ask more information about this language.

**Comment by RyckRichards** [comment]
That's what cueyayotl said:

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/10429179/2174a482-70cd-11e5-83f9-c9ebbcd9ac30.png)
