### ISSUE TITLE
Wall posts sometimes disappear

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1870]
I found that when I tried to post a reply to this comment on the Wall:

https://tatoeba.org/eng/wall/show_message/31695#message_31695

my first and second attempts disappeared without a trace, and my third attempt seemed to disappear. However, when I refreshed the page, the third attempt showed up. This was frustrating because I had to rewrite my comment from scratch before I realized that it was safer to write it in a text editor and copy it over.

**Comment by jiru** [comment]
I experienced this bug too.

**Comment by trang** [comment]
Me too actually. I tend to always write my posts in a text editor first because of that (at least when I know I'll be writing a fairly long message).

**Comment by jiru** [comment]
Related: #293, #458

**Comment by trang** [comment]
With the Wall redesign, the issue of Wall replies disappearing should no longer be an issue.
