### ISSUE TITLE
Use arrow-like character rather than "<=" sequence

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1871]
From Ricardo's message on the [Wall](https://tatoeba.org/eng/wall/show_message/31646#message_31646):

Wouldn't it better if we replace "<=" by "◄" (alt+17) or "←"(alt 27) in pages like https://tatoeba.org/eng/sentences/show/7844818 ?

http://prntscr.com/na41e1

**Comment by trang** [comment]
In the longer term, we really want to rework the sentence navigation block. I'm not very happy about how this block is organized.

But meanwhile, it doesn't cost much to replace the ugly "<=" by a prettier symbol. I have a preference for "←" but it doesn't matter too much in the end.

**Comment by trang** [comment]
The navigation block was redesigned (e9623f424723554478fbd340d647e48c8e9770af), the text is now in a tooltip.
