### ISSUE TITLE
We used to be able to click a sentence in the logs on the side of a sentence's page, and we could jump to that sentence on the page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1873]
We used to be able to click a sentence in the logs on the side of a sentence's page, and we could jump to that sentence on the page.

I didn't miss that function until today, so maybe it's not that important to fix.

**Comment by AndiPersti** [comment]
I'm not sure if I understand your problem. If I click on a sentence's id (red circled in the screenshot) I get to that sentence's page. But I guess that's not what you want, is it?
![screenshot](https://user-images.githubusercontent.com/6566321/67703013-07648080-f9b3-11e9-9cbc-d6a89e884258.png)

**Comment by ckjpn** [comment]
We used to be able to click, not the link there but the whole area there, and it would jump up to the text of that sentence on the same page, so we could easily know which one of the above sentences the number referred to.

**Comment by trang** [comment]
Related code: https://github.com/Tatoeba/tatoeba2/blob/dev/webroot/js/sentences.logs.js

**Comment by AndiPersti** [comment]
Ok, I understand. 

Was it still possible to click on the number and get to a new page?

**Comment by trang** [comment]
Yes, it was still possible to click on the number and go to a new page.
