### ISSUE TITLE
No Page = https://github.com/Tatoeba/tatoeba2/wiki/How-to-install-Tatoeba

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1875]
There is no page here.

https://github.com/Tatoeba/tatoeba2/wiki/How-to-install-Tatoeba

It's this link.

If for some reason you prefer to install manually or if Imouto doesn't work for you, you can follow our wiki article about installing Tatoeba.

.... on this page.
https://github.com/Tatoeba/tatoeba2

**Comment by trang** [comment]
Thank you, I updated the link.
