### ISSUE TITLE
POT files on Transifex not up-to-date

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1876]
To make new UI strings available on Transifex for translation, someone (usually me) has to run the `/tools/generate_pot.sh` script then manually upload the generated files to Transifex.

First problem: I sometimes forget about uploading the files, even though I generated them with the script.

Second problem: most of the time I upload the POT files at the same time as deploying on production (because procrastination and laziness) so the strings cannot be translated ahead of time.

I think the best solution would be to have a script for deploying on dev and include in this script the generation and upload of the POT files.

We could also consider generating and uploading the POT files on each commit, but I think that might be too frequent. And anyway, until the dev website is updated, the translators cannot check where the strings are on the UI.

**Comment by AndiPersti** [comment]
> I think the best solution would be to have a script for deploying on dev and include in this script the generation and upload of the POT files.

How do you currently deploy on dev?

**Comment by trang** [comment]
I created a wiki page about [deployment](https://github.com/Tatoeba/tatoeba2/wiki/Deployment).

For the first problem that I mentioned int his issue, it's less of a problem now because the "Auto update resource" feature on Transifex is now working fine. I remember having issues with getting this feature to work, or I was never patient enough (from my attempts, after one day, it was still doing nothing). But I tried it again a couple of months ago and it worked.

For the second problem, I'm having second thoughts about uploading the POT files when updating the dev website. Sometimes the strings are not stable and having them on the dev website is an occasion for people to suggest better phrasing. And sometimes we don't even update the dev website before deploying on prod, because there's nothing critical to test.

I think it would make more sense to generate the POT files and send them to Transifex upon merging a pull request. Because part of the process of merging a pull request is to review the strings and reword them if needed.

**Comment by jiru** [comment]
> First problem: I sometimes forget about uploading the files, even though I generated them with the script.

Note that this is not a problem since Transifex automatically pulls new POT files. The Transifex interface says so and I just saw that actually happening after updating the POT files yesterday.

**Comment by jiru** [comment]
I think it’s fine to close this issue because I am taking care of the second problem as part of the release cycle. I update the production server on Sundays (or Mondays). I update the POT files on Thursdays (or Fridays) so that translators can translate ahead of time. I also adopt a string freeze policy during that period. If a pull request includes new or modified translatable strings, I only merge it between Mondays and Thursdays (or I wait until the next Monday).

**Comment by trang** [comment]
Agreed, we can close.
