### ISSUE TITLE
Make the search engine treat the letters U+06D5 as U+0647 and U+06AD as U+0643 when searching in Ottoman Turkish

### ISSUE THREAD

**Issue by soliloquist-tatoeba** [Tatoeba/tatoeba2#1880]
https://www.fileformat.info/info/unicode/char/06d5/index.htm

https://www.fileformat.info/info/unicode/char/0647/index.htm

I tried to explain the reason on #1872.

https://github.com/Tatoeba/tatoeba2/issues/1872#issuecomment-488438111

@alanfgh said this might be possible so I'm opening the issue.

**Comment by jiru** [comment]
Yes, it’s possible.

**Comment by soliloquist-tatoeba** [comment]
I have some more requests:

ڭ (U+06AD) ⟶ ك (U+0643)

ڭ is a rarely used accented letter. ك is usually used instead of it.

It would be better if the search engine treated ڭ as ك.

https://www.fileformat.info/info/unicode/char/06ad/index.htm

https://www.fileformat.info/info/unicode/char/0643/index.htm


I also noticed that the Arabic diacritics aren't ignored in searches. I think they should be.

https://tatoeba.org/eng/sentences/search?query=%22%D8%B3%D9%8F%D9%88%D9%8A%D8%B3%D9%92%D8%B1%D9%8E%D8%A7%22&from=und&to=und

https://tatoeba.org/eng/sentences/search?query=%22%D8%B3%D9%88%D9%8A%D8%B3%D8%B1%D8%A7%22&from=und&to=und

Both searches above are "Switzerland" in Arabic. Wouldn't it be better if both results were combined? I'm not an Arabic speaker so I can't speak for sure about it, but for Ottoman Turkish, it would be better if the following diacritics were ignored in searches.

https://www.fileformat.info/info/unicode/char/0650/index.htm
https://www.fileformat.info/info/unicode/char/0651/index.htm
https://www.fileformat.info/info/unicode/char/0652/index.htm
https://www.fileformat.info/info/unicode/char/064e/index.htm
https://www.fileformat.info/info/unicode/char/064f/index.htm
https://www.fileformat.info/info/unicode/char/064b/index.htm
https://www.fileformat.info/info/unicode/char/064c/index.htm
https://www.fileformat.info/info/unicode/char/064d/index.htm

**Comment by jiru** [comment]
@soliloquist-tatoeba The things you requested in this issue have been applied on the production server. You can try on https://tatoeba.org/.

**Comment by soliloquist-tatoeba** [comment]
Sorry for the late response.

The diacritics seem to be ignored for Arabic now. Thank you. However, the letters I mentioned still aren't ignored when searching for Ottoman Turkish sentences.

https://github.com/Tatoeba/tatoeba2/issues/1872#issuecomment-488438111
https://github.com/Tatoeba/tatoeba2/issues/1880#issuecomment-490138950

The search should treat the following as same and merge the results.

ە (U+06D5) ⟶ ه (U+0647) 

https://tatoeba.org/eng/sentences/search?query=%D9%85%D8%B3%D8%A6%D9%84%DB%95*&from=ota&to=und
https://tatoeba.org/eng/sentences/search?query=%D9%85%D8%B3%D8%A6%D9%84%D9%87*&from=ota&to=und

and

ڭ (U+06AD) ⟶ ك (U+0643)

https://tatoeba.org/eng/sentences/search?query=+%D8%A7%D9%88%D9%86%DA%AD+&from=ota&to=und
https://tatoeba.org/eng/sentences/search?query=+%D8%A7%D9%88%D9%86%D9%83+&from=ota&to=und

**Comment by jiru** [comment]
@soliloquist-tatoeba Thanks for your valuable feedback. The last issues you mentioned should be fixed now, please give it a try on https://tatoeba.org/.

**Comment by soliloquist-tatoeba** [comment]
Works great. Thank you very much.
