### ISSUE TITLE
Large numbers sometimes have commas, and sometimes they don't.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1884]
This is a low priority thing, I think, but this should probably be standardized throughout the website.

Here are 2 examples.  There are others.

<img width="596" alt="Screen Shot 2019-05-06 at 10 20 07" src="https://user-images.githubusercontent.com/7934273/57203174-bfa70280-6fe8-11e9-9677-e6dcd418788e.png">

<img width="691" alt="Screen Shot 2019-05-06 at 10 19 44" src="https://user-images.githubusercontent.com/7934273/57203175-bfa70280-6fe8-11e9-9e88-6e00a091fd44.png">

**Comment by jiru** [comment]
Closing because it’s similar to #1472.
