### ISSUE TITLE
Unauthorized error is not translatable

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1890]
As guest, when accessing a members-only page (like the [add sentences page](https://tatoeba.org/sentences/add)), you’re redirected to the login page and a flash message says "You are not authorized to access that location." Currently, that message cannot be translated because it’s part of the CakePHP Auth component.

We may as well replace it with our own, more friendly message such as "You need to login." @alanfgh propositions are welcome.

Similar issue: #1431.

**Comment by alanfgh** [comment]
If you're going to have a message at all, I would suggest "Please log in." But you do have the option of using no message. After all, you are taking them to a login page.

Note 1:  "Login" is a noun, while "log in" is a phrasal verb. Many native English speakers confuse the two.

Note 2: My thinking is influenced by a post by Joel Spolsky that I happened to read last week, [Designing for People Who Have Better Things To Do With Their Lives](https://www.joelonsoftware.com/2000/04/26/designing-for-people-who-have-better-things-to-do-with-their-lives/). (He argues against using "please" in general, but I think that a bare "Log in" would be too abrupt.)

**Comment by jiru** [comment]
It turns out we used to have a translatable message, "You need to be logged in." That message was lost and replaced by the default CakePHP message during the migration to CakePHP 3. I’m in favour of having no message at all.

**Comment by alanfgh** [comment]
I agree.
