### ISSUE TITLE
The advanced search sometimes ignores the search criteria

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1894]
I was searching for Italian sentences with direct links to other Italian sentences with a random sorting (the URL of my query: https://tatoeba.org/ita/sentences/search?query=&from=ita&to=und&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=ita&trans_link=direct&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random) and I noticed that also a sentence with only indirect links to other Italian sentences appeared within the results: https://tatoeba.org/ita/sentences/show/967833

So I guess the advanced search might ignore the custom elements for the query, sometimes

**Comment by jiru** [comment]
I confirm the sentence 967833 shows up in the results. You just need to add it as keywords.

[Search link](https://tatoeba.org/eng/sentences/search?query=Vieni+dentro+Insisto&from=ita&to=und&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=ita&trans_link=direct&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random)

![Screenshot_2019-05-24 Advanced search - Tatoeba](https://user-images.githubusercontent.com/5107734/58302298-02f0d600-7e1d-11e9-9d20-8616ffa25d6c.png)

**Comment by Guybrush88** [comment]
could it be related to the fact that once it had direct links to Italian sentences and in 2017 I unlinked them?

**Comment by trang** [comment]
It is related to #1724. Some links were present in the database while they shouldn't be. 

Looking at the file provide by Yorwba of [links that should be deleted](https://raw.githubusercontent.com/Yorwba/tatoeba-ghost-links/master/data/output/replayed_links_to_delete.csv), we can find links from sentence 967833:
```
967833	967830
967833	967831
967833	967832
967833	967834
967833	967836
```

I removed those links two weeks ago, but did not re-index the affected sentences so the search engine still thinks that sentence 967833 is linked to those other sentences.

**Comment by jiru** [comment]
Can this issue be closed now?

**Comment by trang** [comment]
Yes, it can be closed. Since you re-created the main indexes (in #1929), I suppose those manually deleted links are also removed from the search indexes.
