### ISSUE TITLE
"added by a former member" is not an accurate description for sentences from the Tanaka Corpus

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1896]
https://tatoeba.org/eng/sentences/show/200076

Instead of "added by a former member", why not just clearly say "imported from the Tanaka Corpus?"

<img width="298" alt="Screen Shot 2019-05-27 at 3 07 43 PM" src="https://user-images.githubusercontent.com/7934273/58398925-6edb7480-8091-11e9-813d-93208c1d1bed.png">

**Comment by jiru** [comment]
This string is displayed when we just don’t know who added it. It can be a member which account has been deleted, or, like in the case of Takana Corpus, the member who added it was not recorded for some reason. Maybe we can adjust the logs to say that it has been added by JimBreen, sysko, trang or whoever did it at that time.

**Comment by ckjpn** [comment]
If you just need a default, perhaps "unknown" instead of "a former member" would work.
It would match the "date unknown" that way.
