### ISSUE TITLE
Please close this, or delete it.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1900]
Please close this.

**Comment by jiru** [comment]
You can click the "close issue" button on the bottom of the page to close it by yourself. We always appreciate a comment to explain why you want to close the issue.

**Comment by ckjpn** [comment]
My account apparently doesn't have that right assigned to it.  At least, I can't see a "close the issue" button my any of the issues I've submitted.

**Comment by trang** [comment]
@ckjpn The "Close issue" button should be next to the "Comment" button. You should be able to close issues you have opened yourself, there is no setting in GitHub that prevents users from closing their own issues as far as I know.
