### ISSUE TITLE
Add pie chart statistics to the users' profile

### ISSUE THREAD

**Issue by BaksiLi** [Tatoeba/tatoeba2#1904]
This is a **feature request**.

I wish we could have a Pie Chart showing a user's contribution of sentences, e.g. the languages they've contributed.

Regards.

**Comment by alanfgh** [comment]
I think you're asking for a pie chart consisting of the relative number of sentences contributed in each of the user's languages. Is that right? I suggest that you request this in a comment on the Wall. For instance, sharptoothed might be interested in adding this to the graphs he already produces. To get it done by the Tatoeba development team, you'd need to persuade a larger number of people that it was worthwhile in terms of user interface space and developer effort.

When you make that request, I also recommend that you specify more exactly why you want this.

**Comment by jiru** [comment]
@BaksiLi I also encourage you explain why you want this.

Personally, I would like to see such a graph, or more generally to be able to quickly understand how a given user contributes, such as "X mostly translates sentences in language A into B" or "X mostly contributes original sentences in language X" or something else.
