### ISSUE TITLE
Ask search engines not to index the "dev.tatoeba.org" site.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1906]
## The Problem

The following search showed me a link to the dev site as the first link in this google search today.

https://www.google.com/search?q="More+Search+Criteria"+tatoeba.org

## Suggestion

I'd suggest excluding search engines from indexing this "dev" site.

## Solution

User-agent: *
Disallow: /

More info, if you don't already know how to do this.

https://www.robotstxt.org/robotstxt.html

**Comment by trang** [comment]
Thank you, I added the robots.txt. I guess somewhere along the way we forgot to create it for the dev website (or it got deleted somehow).

On a side note, what you described in "The problem" is not a problem in itself. It's just a fact. The problem would have been for instance "Finding Google results that lead to the dev website is irrelevant to me" or "I'm afraid it will lead some new users to use the dev website as if it was the main website".

In this case here, there are several problems that can be derived from this fact, and we don't really need to think twice about what we should do. But in other cases, it can be more tricky to choose a path of action and if you only give us facts, you leave us trying to interpret what's the problem for you. So to ensure we don't make wrong assumptions, make sure to describe how it impacts you, not just what is happening. Even if it is obvious to you what is wrong, it might not always be obvious to us.

**Comment by ckjpn** [comment]
Sorry.  I thought it would be obvious that the problem is that others searching for specific things on tatoeba.org would be going to the dev site instead of where we want them to go.

I'll try to be more careful in the future to fully explain things.
