### ISSUE TITLE
"Google group" link in footer gives error

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/tatoeba2#1914]
Clicking on "Google group" in the footer gives me "This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access."

So is this group still active?

**Comment by trang** [comment]
It's still alive, although not highly used. There has been apparently some changes made by Google and it affected the permissions. I fixed and you should be able to view the topics now.
