### ISSUE TITLE
Add possibility to include "assinature" on PMs

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1915]
**The problem**

Some of us (users) want to include an assinature (our first name, maybe) in the PMs. However, each time we want to do so, we gotta add it manually unlike emails which we can set up it do it always.

**Solution**

Add a checkbox (?) and a field which we can include an assinuture to be used always we send a message, It could save us some time.

**Comment by trang** [comment]
Unfortunately, I have to mark this as `out of scope`. In general, any feature request related to the private messages is going to be out of scope. 

Whether it's supporting rich text, or inline images, or attached files, or signatures, we cannot really afford to develop a private message system that provides the same kind of features as standard email clients.

The current features of the private messages are all we can offer. If our users need more, then they have to exchange their contact info and move onto other communication channels that fulfill better their needs (emails, Skype, Whatsapp, Slack, whatever it is).

**Comment by trang** [comment]
Closing since there hasn't been any objection for almost a month.
