### ISSUE TITLE
Adding a language already listed on your profile generates "Internal error"

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1917]
Steps to reproduce

1 - Go to your profile
2 - Click on "Add language"
3 - Choose a language already listed on your profile.

You'll get this

![image](https://user-images.githubusercontent.com/7658430/60780950-d10aa900-a116-11e9-8047-e29ccfe32d65.png)

**Comment by riverxside** [comment]
Hi, I solved this issue. Please check this https://github.com/Tatoeba/tatoeba2/pull/2011
