### ISSUE TITLE
Problem with "Translations" and "Translations of translations" in the "new design" which is the default for non-logged-in members.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1919]
## The Problem
"Translations" sometimes needs to be "Translation"

"Translations of translations" sometimes needs to be "Translation of the translation" and possibly sometimes "Translations of the translation."

## Screenshot
This is from the non-logged-in main page.
https://tatoeba.org/eng
<img width="675" alt="Screen Shot 2019-07-13 at 10 15 47" src="https://user-images.githubusercontent.com/7934273/61165184-f143c900-a557-11e9-9ff7-850fe8f1f631.png">

## The text in the settings for members, who might also be seeing this problem
Display sentences with the new design. Note that you will not have all the features from the old design.

**Comment by jiru** [comment]
Can you elaborate on why is it a problem? I believe that "translations" is introducing a list, as in "one or more items", while "translation" suggests there can be only one translation. Similarly, are we going to change titles like "Search results", "X’s sentences", "X’s comments", "Logs" etc.

**Comment by trang** [comment]
I'm closing this since this is a common UI pattern to have a label/title in the plural form even if the related content only has one element or no element.
