### ISSUE TITLE
On the Downloads page "9:00 GMT" needs to be "6:00"

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1920]
## The Problem

The wrong time is listed on this page: https://tatoeba.org/eng/downloads
"The files provided here are updated every Saturday at 9 a.m. (GMT). "

## Correction Needed

6:00 a.m. (GMT) or possibly 06:00 UTC

## Notes 

Perhaps you might want to change GMT to UTC, too.

The Difference Between GMT and UTC
https://www.timeanddate.com/time/gmt-utc-time.html

See the timestamps on files here.
https://downloads.tatoeba.org/exports/

I usually start my downloads at 6:25 UTC since it takes time for the files to be created.
You may want to compensate for this in what's written on the page by just saying 6:30 or something like that.

## Request

Please don't change the time the files are created.  This is a very convenient time for me  to download and process files.   I wouldn't mind an hour or two earlier, but please don't make this later.

**Comment by trang** [comment]
I confirm the exports are triggered at 6:00 UTC on Saturdays. Our cron job for the export says:
```
1 6 * * sat /home/cron/runner.sh /home/cron/export.sh # export
```

We have no reason to change the time of the cron job. We chose this time because we had low traffic on Saturday early morning, and that's still the case.

Might be a detail, but how should we write the time (@alanfgh)?
- 6 a.m. (UTC)
- 6 am (UTC)
- 6 A.M. (UTC)
- 6 AM (UTC)
- 06:00 (UTC)
- ... something else?

**Comment by ckjpn** [comment]
I like these best out of your choices. However, I think any of these would be acceptable.

6 a.m. (UTC)
06:00 (UTC)

Perhaps this...
6:00 a.m. UTC

Perhaps the message could read as follows.

The exports are trigged at 6:00 a.m. UTC on Saturdays and usually ready to download by 6:25 a.m.

**Comment by agrodet** [comment]
I'm not sure there is added value to tell the user about when the exports are "triggered". The interesting information is at what time we can download the files. Taking a long enough insurance, shall we go with the following?
```
The files provided here are updated every Saturday at 6:30 a.m. (UTC). 
```

**Comment by ckjpn** [comment]
> The files provided here are updated every Saturday at 6:30 a.m. (UTC). 
This sounds good to me.  However, at least one time, the downloads weren't available until about an hour later.  I think TRANG said someone was exporting a large list at that time which slowed down the exports.

**Comment by jiru** [comment]
I may as well also adjust the time at which the files are generated so that it matches what the Downloads page says. This way, we don’t have to update the string as well as its translations.

**Comment by agrodet** [comment]
I'd be happy with that solution as well, but I dug up the issue to decide a string because trang said


> We have no reason to change the time of the cron job. We chose this time because we had low traffic on Saturday early morning, and that's still the case.

Up to you :)

**Comment by ckjpn** [comment]
> I may as well adjust the time at which the files are generated so that it matches what the Downloads page says. This way, we don’t have to update the string as well as its translations.

This would definitely inconvenience me a bit, since in my time-zone, I can download the files and have the new English sentences proofread and on List 907 before I leave my office.

However, there are plenty of proofread sentences on List 907, so a delay of a few days isn't that big a deal, I guess.  It's just that on Saturdays I usually have a bit more free time.

**Comment by ckjpn** [comment]
If you are going to change this setting anyway, perhaps you would consider 1:00 a.m. France time, making it 9:00 a.m. Japan time, for this. My preference would be Monday or Tuesday.


This only shows users and not pages being accessed, but perhaps almost any day between 12:00 a.m. and  2:00 a.m. French Time would be good.

<img width="285" alt="Screen Shot 2020-02-22 at 12 36 48" src="https://user-images.githubusercontent.com/7934273/75085908-44abda00-5571-11ea-8787-be23e9510b34.png">


(GMT+01:00) France Time is what it says this is set for in the "admin" settings.
I can't change settings, but I can see the settings.

**Comment by ckjpn** [comment]
If you are going to change this setting anyway, perhaps you would consider 1:00 a.m. France time, making it 9:00 a.m. Japan time, for this. My preference would be Monday or Tuesday.

Google analytics shows that for the past 90 days, 12:00 a.m. to 2:00 a.m. (GMT+01:00)  French Time has few visitors.

**Comment by jiru** [comment]
@ckjpn Your personal preference is not relevant to this issue.

> The interesting information is at what time we can download the files.

@agrodet You have a point. So if we are to rephrase the whole sentence, we may as well fix the time.

To sum up: this issue can be solved by changing the relevant string into:

> The files provided here are updated every Saturday at 6:30 a.m. (UTC).

PRs welcome.

**Comment by ckjpn** [comment]
> Your personal preference is not relevant to this issue.

I know that, but if nobody else had any specific preference and you were going to change the time anyway, I thought you might consider my preference.  That's all I meant.
