### ISSUE TITLE
sentence_derivation shell no longer works

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1936]
Steps to reproduce (this assumes you have installed Tatoeba with [Imouto](https://github.com/Tatoeba/imouto)):

- Go to http://localhost:8080 and add some sentences and translations.
- From the terman, SSH to the VM: `vagrant ssh`
- Connect to mysql: `mysql tatoeba`
- Set the `based_on_id` to null for all sentences: `update sentences set based_on_id = null;`.
- Exit mysql and execute the sentence_derivation shell:
  - `cd Tatoeba`
  - `bin/cake sentence_derivation`
- The output says "0 sentences proceeded" and the `based_on_id` values are indeed still set to null.

Expected result: when a sentence is a translation, it should have `based_on_id` set to the ID of the sentence it has been translated from.

The code for this shell can be found in: https://github.com/Tatoeba/tatoeba2/blob/dev/src/Shell/SentenceDerivationShell.php

**Comment by AndiPersti** [comment]
> Steps to reproduce (this assumes you have installed Tatoeba with [Imouto](https://github.com/Tatoeba/imouto)):
> 
>     * Go to http://localhost:8080 and add some sentences and translations.

As I understand it, you add the sentences to an empty database, don't you? (The database in the Imouto VM is empty).

In that case the script won't work because 7848385aa1a61ac6d5473be4f58f8d38476386af added the variable `$linkEraFirstId` so that the processing starts with the 330930th sentence in the database.

It seems to work if you set `$linkEraFirstId` to `1`:

```
vagrant@stretch:~/Tatoeba$ echo "select id, text, based_on_id from sentences;" | mysql tatoeba
id      text    based_on_id
1       One     0
2       Two     0
3       Three   2
4       Four    3
5       Five    1
vagrant@stretch:~/Tatoeba$ echo "update sentences set based_on_id = null;" | mysql tatoeba
vagrant@stretch:~/Tatoeba$ echo "select id, text, based_on_id from sentences;" | mysql tatoeba
id      text    based_on_id
1       One     NULL
2       Two     NULL
3       Three   NULL
4       Four    NULL
5       Five    NULL
vagrant@stretch:~/Tatoeba$ sed -i -e 's/330930/1/' /src/Shell/SentenceDerivationShell.php
vagrant@stretch:~/Tatoeba$ cake sentence_derivation
Finding duplicate creation records... done (0 sentences affected)
Setting 'based_on_id' field for all sentences.
5 sentences proceeded.
vagrant@stretch:~/Tatoeba$ echo "select id, text, based_on_id from sentences;" | mysql tatoeba
id      text    based_on_id
1       One     0
2       Two     0
3       Three   2
4       Four    3
5       Five    1
```

**Comment by jiru** [comment]
@AndiPersti Yes that’s the expected behaviour. And the reason is explained in the commit message.

I think the sentence_derivation shell has quite good unit test coverage, so expect the tests to fail if someone breaks it.

**Comment by trang** [comment]
My bad, false alert. I forgot about this "link era" id.

I had memories of it not working locally for me some months ago, but probably it's a Windows thing... I just ran the shell on the dev server and it went fine.

Closing.
