### ISSUE TITLE
Outdated section about PHP CodeSniffer on "Code style" Github wiki page

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/tatoeba2#1937]
The section about PHP CodeSniffer on [Code style](https://github.com/Tatoeba/tatoeba2/wiki/Code-style) is pretty outdated (wrong path to script and old example file). I wanted to update the section and ran PHP CodeSniffer on the given example code:

```
vagrant@stretch:~/Tatoeba$ phpcs example.php

FILE: /home/vagrant/Tatoeba/example.php
----------------------------------------------------------------------
FOUND 7 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
  2 | ERROR | [ ] Missing file doc comment
  2 | ERROR | [ ] Missing class doc comment
 14 | ERROR | [ ] Public method name
    |       |     "MyController::controller_actions_have_underscores"
    |       |     is not in camel caps format
 34 | ERROR | [ ] Private method name
    |       |     "MyController::_some_private_controller_function"
    |       |     is not in camel caps format
 48 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found
    |       |     12
 51 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found
    |       |     12
 54 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found
    |       |     12
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 30ms; Memory: 6Mb
```
So the default coding standard ruleset (PEAR) isn't very useful IMHO because it contradicts Tatoeba's coding style.

I would try to create a proper coding standard ruleset for Tatoeba, but before investing some time in it I would like to ask if anybody actually uses PHP CodeSniffer for checking their contributions to Tatoeba?

**Comment by jiru** [comment]
On August 4, 2019 7:21:47 PM UTC, Andreas Perstinger <notifications@github.com> wrote:
>anybody
>actually uses PHP CodeSniffer for checking their contributions to
>Tatoeba?

I don't and I never did. I just try to keep my code style consistent within the file I modify.

My opinion is that it's good enough like that. Even though our style is not consistent through the whole codebase (newline before opening brackets, camel case vs. underscores, underscore prefix for private functions, tabs vs. spaces...), I don't feel like the benefits of a stricter consistency worth the effort of initial harmonization.

**Comment by AndiPersti** [comment]
Well, if nobody uses PHP CodeSniffer, shouldn't it be removed as a dev requirement?

**Comment by trang** [comment]
I was wondering where you saw it was a dev requirement, but I realized it's in our [composer.json](https://github.com/Tatoeba/tatoeba2/blob/dev/composer.json#L14).

I have no objection for removing it and if no one else does, then I will remove it in a couple of weeks. Meanwhile, I'll update the wiki page to explain that we don't have a strict code style.
