### ISSUE TITLE
Transcriptions are no longer being generated automatically

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#1938]
Starting with [#7818567](https://tatoeba.org/eng/sentences/show/7818567), no Japanese sentence has furigana. Starting with [#7885785](https://tatoeba.org/eng/sentences/show/7885785), no Chinese sentence has transcriptions into simplified/traditional script or pinyin. I don't know whether there are any other languages with the automatic transcription feature, but they might be affected as well.

**Comment by Yorwba** [comment]
I tried to reproduce this with a local installation. 

I discovered that if automatic transcriptions are enabled but generating the transcription fails (I killed nihongoparserd to make sure it doesn't work), it becomes impossible to add Japanese sentences. But people keep adding more sentences in Japanese. Therefore I highly suspect that the `AutomaticTranscriptions` option is disabled in `config/app_local.php`. This can happen due to interference between the Ansible roles `update_code` and `setup_nihongoparserd`, which both modify this file.

Could you check the config file on the server to see whether automatic transcriptions are enabled? It would also be good to know whether the daemon processes are running (`ps -ef | grep parserd`).

**Comment by trang** [comment]
I confirm that the option is disabled currently in production. Perhaps we forgot to re-enabled it this whole time...

It was disabled for some time because the transcription features were not migrated right away during the CakePHP migration (#1761).

I have re-enabled it now and will be running the autogen shell for Japanese and Chinese.

**Comment by trang** [comment]
Missing transcriptions have been generated. I'll wait until someone creates some sentences in Japanese or Chinese before I close this.

**Comment by Yorwba** [comment]
The most recent Japanese sentence was added 15 hours ago and has a transcription: https://tatoeba.org/eng/sentences/show/8160498

**Comment by trang** [comment]
Thanks :)
