### ISSUE TITLE
Downloading big lists with translations slows down server

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1939]
People [reported on the Wall](https://tatoeba.org/eng/wall/show_message/32451#message_32451) that Tatoeba has been very slow. It seems to be caused by the download of list 907 with translations in Esperanto.

Output for `show full processlist`:
https://gist.github.com/trang/000f1b047210f9b3894fdb349a43e1

Load average was at ~50. I killed the processes that were selecting sentences from list 907 with translations in Esperanto. Load average is back to normal now (~4).

The longest query (below) had been running for close to 30 hours.

```
SELECT
  `SentencesTranslations`.`sentence_id` AS `id`, 
  `SentencesTranslations`.`translation_id` AS `tid`, 
  `Sentences`.`lang` AS `Sentences__lang`, 
  `Sentences`.`text` AS `Sentences__text`, 
  `Translations`.`text` AS `Translations__text` 
FROM `sentences_sentences_lists` `SentencesSentencesLists` 
  INNER JOIN `sentences` `Sentences` ON `Sentences`.`id` = (`SentencesSentencesLists`.`sentence_id`) 
  INNER JOIN `sentences_translations` `SentencesTranslations` ON `Sentences`.`id` = (`SentencesTranslations`.`sentence_id`) 
  INNER JOIN `sentences` `Translations` ON (`SentencesTranslations`.`translation_lang` = 'epo' AND `Translations`.`id` = (`SentencesTranslations`.`translation_id`)) 
WHERE (`SentencesSentencesLists`.`sentences_list_id` = 907 
  AND (`SentencesTranslations`.`sentence_id` >= 7075801 
  AND (`SentencesTranslations`.`sentence_id` > 7075801 OR (`SentencesTranslations`.`sentence_id` = 7075801 
  AND `SentencesTranslations`.`translation_id` > 7322114)))) 
ORDER BY `SentencesTranslations`.`sentence_id`, `SentencesTranslations`.`translation_id` 
LIMIT 1000
```

**Comment by jiru** [comment]
That fix should improve export performance greatly. I pushed it on dev.tatoeba.org and it works fine. I let you push it on tatoeba.org when you want.

**Comment by trang** [comment]
Thanks a lot, @jiru.
