### ISSUE TITLE
No audio on the VM

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#194]
There's no audio on the VM, so it's not possible to test functionality that relates to it. Fixing #132 (hard-coded audio links) might be a good thing to address at the same time.

**Comment by trang** [comment]
I'm closing this. It's not exactly necessary to have audio on the VM itself to test the audio.

To be able to play audio, you need to:
1) Set the path of your choice in the config/core.php: https://github.com/Tatoeba/tatoeba2/blob/dev/app/config/core.php.template#L330
2) Make sure that in the database, the 'hasaudio' field of the sentence is set to 'shtooka'.
3) Make sure that there's an audio file with the correct name, in the correct folder, at the location you have specified in the config/core.php.

So for instance, you could set the `Path.audio` to be http://audio.tatoeba.org/sentences/, and you would read the audio from Tatoeba's server, as long as the corresponding sentences in your local database have the field 'hasaudio' set to 'shtooka'.
