### ISSUE TITLE
Typos in jpn_indices

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1942]
Reported by Takoboto in e-mail:

:::

I found a few typos in the file jpn_indices.csv. I'm not sure how to report it so here is the concerned 3 lines:

117073\t286593\t彼(かれ)[01]{彼の} 車 は|1 青 で 彼女[01] の は|1 赤[01 だ{だった}
189854\t27011\t羽根(はね)[02]{羽}~ に 深い(ふかい) 傷(きず) を 負う(おう){負った 小鳥 を 見つける{見つけました}
217009\t54316\tご迷惑 ~ を 掛ける[08]{おかけ} 為る(する)[12]{しまして} 申し訳ありません[01]

First one is missing closing ] after 赤[01, should be 赤[01].
Second one is missing closing } after 負う(おう){負った, should be 負う(おう){負った}.
Third one has a space before ~ which should not be there I think ("ご迷惑 ~" should be "ご迷惑~")

**Comment by Yorwba** [comment]
Seems like https://tatoeba.org/eng/sentence_annotations/index should be easier to find for people interested in the indices. I don't know whether it's linked on the website at all. I found it by grepping the source code. A link in the description of `jpn_indices.csv` on the download page would probably be helpful.

**Comment by trang** [comment]
I have already notified Jim Breen about the typos. Fixing them is a manual process and can be done with "sentence annotations" feature.

The "sentence annotations" are somewhat of a legacy, they are not an official feature of Tatoeba. Therefore, making this feature easier to find is not really part of the plan.

The feature was developed specifically for the folks at WWWJDIC a long time ago (this enabled Tatoeba to become the [new home for the Tanaka Corpus](https://blog.tatoeba.org/2009/12/tatoeba-update-dec-12th-2009.html)) and remained in Tatoeba until now. One day I hope these indices can be maintained completely independently from Tatoeba and the feature can be removed.

I will close this issue as there is nothing more to do.
