### ISSUE TITLE
Rethink what tags are auto-suggested

### ISSUE THREAD

**Issue by Poulpisator** [Tatoeba/tatoeba2#1947]
I know a lot have been discussed about tags, but I'm not sure about this point. 

I'm guessing that currently, every tag that has been used up to now is suggested in the tag text input.  
However, several (many?) of these tags are erroneous. For example there is a @no tag, or there are some @chamge @change' @chaneg tags, which were simply a typo in the @change tag.  
I corrected the involved sentences, thus removing the tags, but they still appear. That's how I realized the problem. Looking for the @no tag in "Browse by tags" page gives no results. 

I wonder if it would be desirable to suggest only tags with at least one sentence, plus the "@ maintenance tags". Or maybe that's already the case, and that's why I only realized @no, @chaneg, etc. and in this case, another way of thinking is required. 

Although my personal opinion is that @-tags that are not currently in used need not be suggested. As long as we know that maintenance tags start with @, any name is okay (and the common ones definitely have more than one sentence). So it would really be only about displaying tags who are currently in use.

**Comment by Guybrush88** [comment]
I believe that what you suggest is pretty similar to this ticket: https://github.com/Tatoeba/tatoeba2/issues/301

**Comment by Poulpisator** [comment]
Oh, indeed. I missed it.

**Comment by trang** [comment]
There's also #330, #305, #961 which are all about trying to solve the issue that some tags are useless (because of typo or whatever else).

And the idea of keeping the `@` tags even when they reach zero sentences is mentioned in #305.

Will close this issue.
