### ISSUE TITLE
State up front what a username can contain

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#195]
When someone is registering, and types bad characters into the username field, a message is displayed: "Username can only contain letters, numbers, or underscore". It would be more helpful if this information, as well as the minimum length, were displayed from the beginning.

**Comment by RyckRichards** [comment]
Requested by [Guybrush88](https://tatoeba.org/eng/user/profile/Guybrush88) on [Tatoeba Day #12](https://tatoeba.org/eng/wall/show_message/24986#message_24986).
