### ISSUE TITLE
Possible to remove all text from a Wall message

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#196]
It's possible to remove all the text from a Wall message and save it, whereas it's not possible to submit an empty Wall message in the first place. It would be nice to tell the user to either delete the message entirely or leave in some text.

**Comment by trang** [comment]
**Solution:**
When a user tries to save an empty message, we will display an error message saying `You cannot save an empty message.`.
This error message would be displayed in our standard "flash" message (here's an example of a flash message: http://prntscr.com/ahne5s).

**Comment by theblindspring** [comment]
I can take a shot at working on this.
