### ISSUE TITLE
Advanced search for excluding sentences with links isn't working.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1960]
## Problem.

This search shows sentences with links that were made several days ago, so it's not just that the indexing has not yet occurred, unless automatic indexing is not currently working.

Search: All English sentences on CK's audio list that do not yet have links to sentences in any language.

https://tatoeba.org/eng/sentences/search?from=eng&to=und&list=4000&trans_to=und&trans_link=direct&trans_filter=exclude&sort=created

Here's one of the links that show.
https://tatoeba.org/eng/sentences/show/8194313
linked by Pfirsichbaeumchen, 6 days ago

**Comment by jiru** [comment]
Automatic indexing was disabled. Thanks for reporting the problem! :yum:
