### ISSUE TITLE
New icons for Berber (ber) and Kabyle (kab)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#1967]
Here are the new proposed language icons for Berber and Kabyle, both of which use the same template, but different ISO code identifications.

![ber](https://user-images.githubusercontent.com/7028559/66060748-d03db380-e55b-11e9-89c6-b4b126b8b919.png)
![kab](https://user-images.githubusercontent.com/7028559/66060751-d03db380-e55b-11e9-8d2d-cecf13d9d98d.png)

I have also uploaded them to Imgur:

https://i.imgur.com/Mc3e5Xe.png (ber)
https://i.imgur.com/s6mcyXz.png (kab)

**Comment by trang** [comment]
Related Wall thread: https://tatoeba.org/eng/wall/show_message/32995#message_32995
