### ISSUE TITLE
Komi-Zyrian and Komi-Permyak missing from stats/sentences_by_language

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#1974]
There are 45 sentences in Komi-Zyrian (kpv), e.g. [#6359852](https://tatoeba.org/eng/sentences/show/6359852) and 43 sentences in Komi-Permyak (koi), e.g. [#5966583](https://tatoeba.org/eng/sentences/show/5966583), but neither of those languages shows up on https://tatoeba.org/eng/stats/sentences_by_language

**Comment by AndiPersti** [comment]
Two other languages missing on the stats page are [Inuktitut](https://tatoeba.org/eng/sentences/show_all_in/ike/none) and [Mirandese](https://tatoeba.org/eng/sentences/show_all_in/mwl/none).

It looks like [step 3](https://github.com/Tatoeba/tatoeba2/wiki/Adding-a-new-language#3-run-the-mysql-add_new_language-procedure) was forgotten when these languages were added.
