### ISSUE TITLE
I can't remove deleted sentences from the favorites

### ISSUE THREAD

**Issue by denikoTatoeba** [Tatoeba/tatoeba2#1976]
This issue was already dealt with in the past:

https://github.com/Tatoeba/tatoeba2/issues/1526

But it seems to have re-emerged. This time there is a "remove" X icon next to your deleted sentences, but it stopped working.

![image](https://user-images.githubusercontent.com/25774177/66295889-3d4aa380-e8e4-11e9-9e10-04d1a1232610.png)

So you press X, and nothing happens.

**Comment by denikoTatoeba** [comment]
Easy to reproduce: Contribute a new sentence, add it to your favorites, delete it, go to your favorites and try to remove it from the list.

**Comment by denikoTatoeba** [comment]
Further testing showed that the X icon from the page above doesn't work for all sentences, not only deleted.

**Comment by trang** [comment]
Fixed in 08be14bd8a35da874385142035e86f92b200b8e4.
