### ISSUE TITLE
More languages than expected are shown when linking sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1977]
As reported by MisterTrouser on the wall:

> Bug report for linking sentences:
> Reproduce:
> (1) The following link shows Japanese sentences with indirect German links: https://tatoeba.org/eng/sentenc...io=&sort=words
> Open it.
> (2) Link an indirectly linked sentence.
> (3) < sentence gets linked >
> (4)
> Expected: < Except of the fact, that the sentence is now linked nothing should've changed. >
> Actual: < All other languages for that sentence also get shown >

https://tatoeba.org/ita/wall/show_message/33127#message_33127

**Comment by conlangbecca** [comment]
Is this the same issue? #1783

**Comment by Guybrush88** [comment]
it seems so, I'm closing this one, thanks
