### ISSUE TITLE
Outdated CakePHP link in webroot's test

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1984]
Currently, in webroot's test (https://github.com/Tatoeba/tatoeba2/blob/dev/webroot/test.php) there's still a link to a reference guide for the 2 series in line 5 (http://book.cakephp.org/2.0/en/development/testing.html), which is now outdated, since now the 3 series is currently used.

I guess the proper CakePHP's page to be linked there should be, instead, https://book.cakephp.org/3.0/en/development/testing.html , so that there would be a reference to more accurate information

**Comment by trang** [comment]
I don't think that page is even used anymore...

**Comment by jiru** [comment]
I confirm `/test.php` (the web frontend to run the test suite) has been dropped from version 3 of CakePHP. It is safe to remove that file.
