### ISSUE TITLE
Wrong title in given tags' pages

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1987]
Generally, the page containing all the sentences with a given tag (i.e.: https://tatoeba.org/ita/tags/show_sentences_with_tag/7) had, as the general title, the actual name of the tag. Now, every page related to any tag has "tagName" instead of the proper name of the tag.

**Comment by AndiPersti** [comment]
Sorry, that was my mistake.

**Comment by Guybrush88** [comment]
no problem, and thanks for the very quick fix :D
