### ISSUE TITLE
Ladino flag is too easily confused with Spanish flag

### ISSUE THREAD

**Issue by conlangbecca** [Tatoeba/tatoeba2#1989]
The Ladino flag is currently too easily confused with the Spanish flag, to the extent that Ladino sentences sometimes mistakenly receive corrections from Spanish-speaking users.

As a solution, I am proposing a flag that features a yellow hamsa (which is a common symbol of Judaism but especially of Sephardic Judaism) on a red background.
![Ladino Flag tiny](https://user-images.githubusercontent.com/19203983/66932755-9ecaea80-f027-11e9-90a1-8c2039fe4d08.png)

FTR, I have this flag as an SVG already and could upload it or send it to someone else. But I couldn't attach it here.

**Comment by trang** [comment]
@soliloquist-tatoeba @sabretou, please confirm if this change request is okay :)

**Comment by soliloquist-tatoeba** [comment]
This was previously discussed on the Wall.

https://tatoeba.org/eng/wall/show_message/24926

I have no objection as long as the users contributing in Ladino are okay with replacing the Star of David with the Hamsa.

https://www.myjewishlearning.com/article/hamsa/

It's also popular in Turkey and used as a talisman of good luck.

Cueyayotl's suggestion that has the same symbol and colors with the current flag can also be considered if there are objections to changing the Star of David.

https://i.pinimg.com/736x/95/8b/5a/958b5aecf8acb578be3ec92a1dad1c8a.jpg

**Comment by sabretou** [comment]
I apologise for the very late response.

This change sounds good, and Ladino has no 'official' or otherwise widely recognised flag anyway.

Let's go for it.

**Comment by RyckRichards** [comment]
I'm going to change the current Ladino flag to this one uploaded by conlangbecca

![image](https://user-images.githubusercontent.com/7658430/71544656-2787d000-2961-11ea-9198-3e85fe43bc30.png)
