### ISSUE TITLE
Give visual indication of current sort criterion and order for list of sentences with a given tag

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1991]
When you choose to show all sentences with a given tag, such as "@change", the top of the list says this:

Sort by: _date created_ | _date of tag_

However, it's not possible to determine which critierion (date created or date of tag) is currently in force. Nor is it possible to determine which order (ascending or descending) is being used. 

For "Browse by list", by contrast, it's easy to tell because:
(1) the attributes of each sentence (list name, date created, number of sentences, and list updated) are displayed, and these correspond to the sorting criteria, and
(2) the lists are displayed in a relatively dense format, so it's easy to see the trend that lets you determine which criterion is in force.

It may or may not be possible to display the attributes of sentences in the tag list view, so the same approach may or may not work. But if it doesn't, there should be some way to indicate which criterion is in effect (perhaps by changing the font weight or color in which the name of the criterion is displayed at the top of the page), and also the order (perhaps by adding an arrow to the display that points either up or down).

**Comment by AndiPersti** [comment]
Something like this?
![sort1](https://user-images.githubusercontent.com/6566321/72555944-ee76b780-389d-11ea-92df-460f374e5552.png)
![sort2](https://user-images.githubusercontent.com/6566321/72555954-f3d40200-389d-11ea-96f0-f8cd871eaeaa.png)
