### ISSUE TITLE
Special Links for Corpus Maintainers No Longer Work = https://en.wiki.tatoeba.org/articles/show/special-links-for-corpus-maintainers

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1992]
See the links on this page.

https://en.wiki.tatoeba.org/articles/show/special-links-for-corpus-maintainers

**Comment by trang** [comment]
I have added a message to mention that the information on that wiki page is outdated.

The page "moderators" page has been removed more than one year ago: #1411.

Corpus maintainers can visit directly the `@change` and `@delete` tag pages. It offers the same functionality with the only difference that the list of sentences is not limited to the last 2 weeks.

**Comment by ckjpn** [comment]
Would this functionality be difficult to add back in?
At least one member mentioned that it made it more difficult to do things without the dates.

See this wall message by AlanF_US.

https://tatoeba.org/eng/wall/show_message/33277#message_33277

**Comment by alanfgh** [comment]
Actually, using the dates of the tags doesn't help much. It's really the dates of the last comments that matters more, and I don't need to have a page of the UI whose purpose is to provide such a search.
