### ISSUE TITLE
Georgian flag was replaced for Kamba

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2002]
https://github.com/Tatoeba/tatoeba2/pull/1998#issuecomment-549270020

"the icon of the Kamba language (kam) began to appear on Georgian (kat) sentences, too." -     (related by Solloquist)

**Comment by trang** [comment]
@RyckRichards You don't need to open an issue if you are going to open at the same time a pull request. Opening an issue is only useful if you want to keep it a reminder for something you want to do later (in a few weeks or in a few months), or if it is an issue you are not able to solve by yourself, or if there are some points that you think should be discussed before implementing anything.

If you're aware of an issue and you can fix it right away, the pull request alone is enough.

**Comment by RyckRichards** [comment]
Oh, that's OK. Thanks, @trang
