### ISSUE TITLE
Paste link from clipboard on click on "link to another sentence"

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2017]
Posted by Inego - https://tatoeba.org/eng/wall/show_message/33545#!#message_33545

It would be really convenient if pressing the "link to another sentence" button also automatically pasted the text from the clipboard to the text field, provided it satisfies the regular expression used to validate it.

**Comment by Inego** [comment]
I'd change the title to "Paste link from clipboard on click on "link to another sentence"", though :)

**Comment by ckjpn** [comment]
I think this should be an opt-in setting if implemented.

I can imagine there would be times when people might have something in the clipboard that they wouldn't want pasted.

**Comment by Inego** [comment]
That's why the regex check. Namely, the text in the clipboard either has to be a number, or a Tatoeba sentence URL. Otherwise, it doesn't get pasted.

**Comment by Inego** [comment]
Also, the pasted text could also be selected, so as to quickly deleted if it's still not what the user wants.

**Comment by Inego** [comment]
[Off-topic] @trang I wanted to ask some questions on deploying a dev Tatoeba locally, as per https://github.com/Tatoeba/tatoeba2#need-help, but to no avail:
* Gitter has the last message dated April;
* XMPP doesn't seem to be working (I see an empty chat and no way to type anything)
* The Google group's last post dated 10/2018.

**Comment by linkmauve** [comment]
Hi, maintainer of the XMPP chat here.

I had deployed a non-working update the other day which is why it was failing, this should be fixed now. :)

**Comment by trang** [comment]
As for Gitter and the Google group, they have not been used intensively because we're a small project with not so many developers. I am still reading messages in these communication channels, but if no one asks anything, there will of course not be much activity :)

**Comment by Inego** [comment]
I'm now trying to implement this feature, but it seems that letting the site to access the clipboard using the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) requires a special permission. A permission popup may seem a bit ugly / scary, but it appears only once, and, besides, this behavior will only affect advanced contributors and admins (and is intended to improve their quality of life anyway).
