### ISSUE TITLE
Internal error on page listing sentences in Kirundi, Yiddish and other languages

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2024]
Reported by [driini on the Wall](https://tatoeba.org/eng/wall/show_message/33586#!#message_33586):

> Wenn ich auf der Seite
> https://tatoeba.org/deu/stats/sentences_by_language
> auf kirundi klicke, kommt eine Fehlermeldung:
> "an internal error has occurred"
> (https://tatoeba.org/deu/sentences/show_all_in/run/none/none/indifferent)

**Comment by AndiPersti** [comment]
Yiddish also results in an internal error. All other languages are fine.

Do you have any logs?

**Comment by trang** [comment]
For [Kirundi](https://tatoeba.org/deu/sentences/show_all_in/run/none/none/indifferent):

> 2019-11-27 11:05:27 Error: Fatal Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) in [/var/www-prod-a079f71bef8b6b93a2d7137906db99b76a15a113/vendor/cakephp/cakephp/src/Database/Statement/BufferedStatement.php, line 218]
>
> Trace:
> Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 229
> Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 109
> [main] - [internal], line ??

For [Yiddish](https://tatoeba.org/eng/sentences/show_all_in/yid/none/none/indifferent):

> 2019-11-27 11:06:26 Error: Fatal Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in [/var/www-prod-a079f71bef8b6b93a2d7137906db99b76a15a113/vendor/cakephp/cakephp/src/Database/Type/IntegerType.php, line 119]
> 
> Trace:
> Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 229
> Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 109
> [main] - [internal], line ??

I'm also noticing that on the dev website, there is no error when *not* authenticated:
https://dev.tatoeba.org/eng/sentences/show_all_in/run/none/none/indifferent

**Comment by alanfgh** [comment]
On the Wall, user Luiaard wrote the following (see [thread](https://tatoeba.org/eng/wall/show_message/34029#message_34029)):

> https://tatoeba.org/eng/stats/sentences_by_language
> 
> https://tatoeba.org/eng/sentences/show_all_in/ltz/none/none/indifferent
> 
> I keep getting an error message when I click on Luxembourgish.
> 
> "An Internal Error Has Occurred
> Error: An Internal Error Has Occurred."
>

**Comment by AndiPersti** [comment]
I think I may have found the problem:
https://github.com/Tatoeba/tatoeba2/blob/ce583b6ab6cc11f9934444ac92cd702bce2bed75/src/Controller/AppController.php#L340
If you comment out this line in `AppController.php` on dev, does it fix the bug?

**Comment by trang** [comment]
This is fixed! Thanks @AndiPersti!
