### ISSUE TITLE
Rating shows "(outdated)" when no change has been made to a sentence.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2042]
### The Problem

I added an OK rating to this sentence yesterday.
https://tatoeba.org/eng/sentences/show/8394145

It now says "outdated."

This shouldn't happen unless a sentence has been edited since the rating was added.

## Screenshot of the rating
<img width="920" alt="Screen Shot 2019-12-22 at 11 28 54" src="https://user-images.githubusercontent.com/7934273/71316162-d3877200-24ae-11ea-92cd-89a7e878bcd3.png">

## Screenshot of the logs
<img width="312" alt="Screen Shot 2019-12-22 at 11 29 03" src="https://user-images.githubusercontent.com/7934273/71316160-cec2be00-24ae-11ea-8971-7ba63fc222c4.png">

**Comment by trang** [comment]
There was a modification though, because the modified date is different from the created date in the database. Perhaps the language was quickly changed.

```
MariaDB [tatoeba]> select created, modified from sentences where id = 8394145;
+---------------------+---------------------+
| created             | modified            |
+---------------------+---------------------+
| 2019-12-21 04:14:15 | 2019-12-21 04:15:46 |
+---------------------+---------------------+
```

**Comment by ckjpn** [comment]
Since there was more than a minute difference, shouldn't there be a "modified" statement in the logs?

I also wonder if I really added the OK rating between those 2 times. However, I know that it might have been possible.

**Comment by AndiPersti** [comment]
> Since there was more than a minute difference, shouldn't there be a "modified" statement in the logs?

We currently don't log flag changes in the contributions table and the logs only show entries from this table.

> I also wonder if I really added the OK rating between those 2 times. However, I know that it might have been possible.

You have indeed rated this sentence between this two times (`users_sentences.csv` is the export from January 4, 2020):

    $ grep -F 8394145 users_sentences.csv
    CK      8394145 1       2019-12-21 04:15:34     2019-12-21 04:15:34

**Comment by agrodet** [comment]
So I guess it is less a bug than a lack of feedback. I think we should display changes of flag in the log corner. That is actually a more general observation, as I think every modification history should be available.

**Comment by AndiPersti** [comment]
> I think we should display changes of flag in the log corner. That is actually a more general observation, as I think every modification history should be available.

Related issue: #533

**Comment by ckjpn** [comment]
>  I think every modification history should be available.

I'm not sure these are needed, but here are some other changes that are not logged.

audio file additions, removing the link to the audio file, and audio file replacements.

releasing ownership and adopting sentences.
