### ISSUE TITLE
Replace CSS property "box-shadow" under language icons with "filter: drop-shadow"

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#2046]
Currently, we use the CSS rule box-shadow to create the shadows under language icons. This is good enough for most icons, which are rectangular in shape. However, this ends up misrepresenting non-rectangular icons, such as the flags of Marathi, Nepali, Awadhi, Old Saxon, and so on.

For eg. this is our current implementation:
![box-shadow example](https://i.imgur.com/AVdk3By.png)

On the other hand, if we used the "filter: drop-shadow" property, we can have the shadow adapt to the actual shape of the icon.

This is how it can look with filter: drop-shadow:
![filter: drop-shadow example](https://i.imgur.com/nq2W7HB.png)

The exact parameters I used for the above effect are:
`filter: drop-shadow(2px 2px 1px #737373);`

These can of course be adjusted as necessary, especially the colour. I only chose these parameters to throw together a quick mock-up.

**Comment by sabretou** [comment]
@trang Just pinging to see if there's a hold up regarding this. I've personally been using a Stylish script for some time now to achieve this effect, but I see this hasn't been implemented yet on the site itself.

**Comment by trang** [comment]
No there's no hold up (not on my side at least). There just needs to be someone to volunteer for this.

As you can see it has been marked as "good first issue" meaning that it's easy to solve and would be perfect as a first task for a new developer.

**Comment by sabretou** [comment]
Ahh, I assumed good first issue was for the ones starting the issue. It left me quite perplexed, to say the least. Thank you for clarifying!

**Comment by trang** [comment]
In case you are puzzled by other labels, know that you can read the description of a label if you hover over it.

You can also find the descriptions on the "Labels" page: https://github.com/Tatoeba/tatoeba2/labels

And even more information on our wiki page: https://github.com/Tatoeba/tatoeba2/wiki/Labels

🙂

**Comment by speedysera** [comment]
I'm going to work on this
