### ISSUE TITLE
Audio contributor's name missing

### ISSUE THREAD

**Issue by Poulpisator** [Tatoeba/tatoeba2#2049]
Sorry if there's already an issue about this, but while playing with Tatoeba data, I realized that some audio contribution don't have any author.   
For example, hovering the audio icon on [#379188](https://tatoeba.org/eng/sentences/show/379188), it says only "Play audio". Therefore I guess that the situation is expected, but I wonder how this situation occurs, and if it's really okay to provide audio data without the author's name. 

I found 1369 audio having author "\N".

**Comment by ckjpn** [comment]
We couldn't identify this member.
However, all the audio files by the same person are on this list.

https://tatoeba.org/eng/sentences_lists/show/4148

In the early years of the project, this information wasn't kept, I think.
