### ISSUE TITLE
Stop storing IP of contributors in the logs

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#205]
I tried to access a local tatoeba installation via IPv6. While going on the login page, the debug showed the following error. The IPv6 network Tatoeba is running on is `fd01:2345:6789:abcd::/64`.

```
Warning (512): SQL Error: 1062: Duplicate entry 'fd01:2345:6789:' for key 'ip' [CORE/cake/libs/model/datasources/dbo_source.php, line 526]
Query: INSERT INTO `visitors` (`timestamp`, `ip`) VALUES (1397479495, 'fd01:2345:6789:abcd:XXXX:XXXX:XXXX:XXXX') 
```

Analysis : The length of the field `visitors.ip` in the database is too short to hold an IPv6, resulting in truncation while insterting values. The length of the fields holding IPs should be extended to at least 39 characters to fit the maximum size of an IPv6. This include : `visitors.ip`, `contributions.ip` and `last_contributions.ip`

**Comment by jiru** [comment]
Note: HTTP_X_FORWARDED_FOR may contain a comma-separated list of IPs. In this case, because we use it as-is to fill the field *ip*, we end up having the same duplicate error.

**Comment by halfdan** [comment]
What's the status of this? As it stands today tatoeba.org is not reachable via IPv6

```
✗ host -t AAAA tatoeba.org
tatoeba.org has no AAAA record
```

**Comment by jiru** [comment]
Hello halfdan, nice to meet you and welcome to the project. Note that I opened this ticket to make Tatoeba work with IPv6, while enabling IPv6 on the machine that currently hosts tatoeba.org is another problem. Since you’re mentioning it, it seems that [our host](firstheberg.com) is [providing IPv6 on their VPSes](https://twitter.com/FirstHeberg/status/673893054819016705) while I don’t know about dedicated servers like us. I asked them and I’m waiting for their reply.

Another option is to get an IPv6 connectivity using a tunnel.

**Comment by jiru** [comment]
We got IPv6 connectivity from our host and the production server now has IPv6 connectivity. Once this issue is fixed (among with other similar ones), we can enable IPv6 on tatoeba.org.

**Comment by halfdan** [comment]
Just revisiting this: IP addresses should not be stored in a VARCHAR field anyway. They should be converted with `inet_pton` and stored in a VARBINARY field (see also http://stackoverflow.com/questions/6964143/storing-ipv6-addresses-in-mysql). 

That said, I can't figure out how, if at all, this table is still used? There is a stray controller returning the visitors in the last 5 minutes, but nothing seems to ever write to the table or actually call that Controller/Model.

IP addresses are also stored in the contributions table where what I said above definitely applies.

**Comment by trang** [comment]
No indeed, the `visitors` table is no longer used.

**Comment by Ppjet6** [comment]
Out of curiosity, why do we have ip fields on these tables?

I understand we might need logs of people coming and going, required per the french law, but these we already have in the webserver logs. If for some other reasons we need them, I would argue that a hash would be sufficient.

**Comment by jiru** [comment]
We used to have a [current visitors count at the bottom of the page](https://web.archive.org/web/20151115044746/tatoeba.org/eng/), but it’s not on the new home page anymore.

**Comment by jiru** [comment]
@Ppjet6 I agree, however such a hash is rather to break because the number of possible IPv4 is only 2^32.

@trang Do we need/want to keep the `contributions.ip` field? Is is actually used by anybody?

**Comment by trang** [comment]
We can remove `contributions.ip`. We have not done anything useful with this information for as far as I can remember. Some people might argue that we can block troublesome users by IP, but we know that's not a reliable way to handle them.

**Comment by jpear1** [comment]
I'm going to work on removing `contributions.ip` from the database.

**Comment by jiru** [comment]
@jpear1 Nice! You want to add a new [migration](https://book.cakephp.org/migrations/2/en/index.html) to remove the field from the schema.

**Comment by jpear1** [comment]
[PR](https://github.com/Tatoeba/tatoeba2/pull/2401) submitted.
