### ISSUE TITLE
Konkani (knn)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#2054]
- Language name: Konkani
- Language info: https://en.wikipedia.org/wiki/Konkani_language
- ISO 639-3 code: knn
- Public List: https://tatoeba.org/eng/sentences_lists/show/9577
- Icon: https://i.imgur.com/v1lY0VV.png
- Requested by: https://tatoeba.org/eng/user/profile/thak123

[for tatoeba.org]
CALL add_new_language('knn', 9577);

**Comment by jiru** [comment]
Note that we may have a problem with the name "Konkani", because it can refer to both kak and knn.

The SIL classifies Konkani (kak) as a macro language that includes Goan Konkani (gom) and Konkani (knn). About Konani (knn), the English Wikipedia says:

> Maharashtrian Konkani more commonly spelt as Maharashtri Kokani is a group of dialects spoken in the Konkan region. It is often mistakenly extended to cover Goan Konkani, which is a member of a distinct and different set of dialects, because speakers of both refer to their language as simply "Konkani".
-- gillux

**Comment by sabretou** [comment]
If I am not mistaken, we no longer accept macrolanguages for inclusion on Tatoeba, so kak is not an issue.

'gom' can be added as Goan Konkani when required, while 'knn' will be Konkani, as it is specified on SIL's website: https://iso639-3.sil.org/code/knn and on Ethnologue: https://www.ethnologue.com/language/KNN

**Comment by jiru** [comment]
Yes, we no longer accept macro languages. But users don't know about macro languages, ISO codes and SIL definitions; they only understand the language name we display.

The problem I'm pointing out is that if we add knn and name it Konkani, we may have people starting to add both knn and gom sentences inside that new corpus because "Konkani" alone is an ambiguous name, according to the quote from Wikipedia. This would be a problem since knn and gom are not mutually intelligible. And if later we add gom, it will be a mess to sort out gom sentences from knn.

**Comment by sabretou** [comment]
Ah yes, that's a good point that I did not consider.

Wikipedia labels knn as Maharashtri Konkani, but I'm not seeing that name in most other linguistic literature.

Still, I think we can use the same solution as we did for Punjabi. We could list the languages as Konkani (Maharashtrian) and Konkani (Goan).

What I am also concerned about is that we may need to create a transliteration engine for one or both of the Konkani languages. Although they are officially written in devanagari, they also have a very robust usage of Roman script, including a specific alphabet.

I will have to discuss both of these issues with the requester. I will see if I can have them post here on Github.

**Comment by thak123** [comment]
Hi Guys,

I am the requester of the langauge and indeed (Maharashtrian) and Konkani (Goan) are two variants and hence it would be wise to split them. 

I am Goan so I would be comfortable for me to contribute to Goan Konkani.
We also have two variant Romi and Devanagiri 

This does the transliteration for Romi to Devanagiri and vice versa
http://konkanverter.com/konkanverter-ver-2-0/

**Comment by sabretou** [comment]
Hello @thak123 , and thank you so much for contributing to this discussion.

As you will be contributing in 'gom' and not 'knn', I think we can close this issue and create a new one for 'gom' instead.

**Comment by thak123** [comment]
Kindly do the needful.
Thanks
