### ISSUE TITLE
Implement a sentiment annotater for sentences being fed in

### ISSUE THREAD

**Issue by thak123** [Tatoeba/tatoeba2#2055]
Hi

I was wondering if we could capture the sentiment of the sentence being added into the system.

Like for example the sentence "I like coffee" could be tagged as positive and "I didnt like coffee" could be tagged as negative. This can help tatoeba users in learning the sentence usage in proper context.

For example in Hindi "Bahut" vs "Beinteha" have different intensification effect on the following noun.

Kindly provide you feedback on this.

**Comment by trang** [comment]
Hi @thak123, I see that you posted this on the Wall as well:
https://tatoeba.org/eng/wall/show_message/33885#message_33885

Additionally to what has been replied over there (that we have tags for this purpose), there is also the option to add a comment.

I will close this issue now but if the tags and comment features are not sufficient to your needs, feel free to re-open this with more details.
