### ISSUE TITLE
Konkani (Goan) (gom)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#2059]
- Language name: Konkani (Goan)
- Language info: https://en.wikipedia.org/wiki/Konkani_language
- ISO 639-3 code: gom
- Public List: https://tatoeba.org/eng/sentences_lists/show/9577
- Icon: https://i.imgur.com/xoPxhYB.png
- Requested by: https://tatoeba.org/eng/user/profile/thak123

[for tatoeba.org]
CALL add_new_language('gom', 9577);

**Comment by trang** [comment]
Just for the record, this issue derived from #2054.
