### ISSUE TITLE
Add "Sort by" bottom

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2071]
Whenever I want to translate sentences using the "Look for sentences' bar", I get the same results

Example: Looking for words containing "professor" in Portuguese

![image](https://user-images.githubusercontent.com/7658430/72585427-d8342000-38cc-11ea-9108-fad0989de136.png)

This the result I get

https://tatoeba.org/eng/sentences/search?query=professor&from=por&to=und

![image](https://user-images.githubusercontent.com/7658430/72585485-192c3480-38cd-11ea-9c08-bdfdc345e95a.png)

Just from this page I can choose what sort of sentences I want

![image](https://user-images.githubusercontent.com/7658430/72585519-319c4f00-38cd-11ea-843f-fe6eda96b9de.png)

Maybe it'd be interesting to have this in the "Look for sentences' bar" as well

![image](https://user-images.githubusercontent.com/7658430/72585658-a1123e80-38cd-11ea-93b6-5b6c2d1cef5c.png)

**Comment by AndiPersti** [comment]
I agree that having easier access to the sorting options is useful. But I would rather put them above the pagination as we do it on other pages like the page for [lists](https://tatoeba.org/eng/sentences_lists/index) or [tags](https://tatoeba.org/eng/tags/view_all).

**Comment by ckjpn** [comment]
### There is an "unclear" label, so ...

I think what he's requesting is to have the sort options from the advanced search included as an option in the simple search.

I know that he doesn't exactly mean something like this image, but it's something I already had online.

<img width="394" alt="Screen Shot 2020-02-04 at 12 32 36" src="https://user-images.githubusercontent.com/7934273/73711577-ae8f4b80-474a-11ea-89b9-169d8ca08bb2.png">

http://tatoeba.ueuo.com/

**Comment by trang** [comment]
I can say it is very unlikely that we add more options to the search bar, at least not in its current default form. It would clutter it too much.

We could consider an "extended form" for the search, where (after clicking on some button) it shows more options. But it doesn't add much value compared to going to the advanced search.

I'll close this but if someone wants to defend further the case of including the sort as an additional default option of the simple search, feel free to share your thoughts. I'm not completely closed to the idea but as of now, I don't see how the sort option is being used often enough to be worth adding as an additional option in the simple search.
