### ISSUE TITLE
Internal errors when displaying sentence lists for certain languages

### ISSUE THREAD

**Issue by conlangbecca** [Tatoeba/tatoeba2#2082]
As far as I'm aware this effects:

Kurdish: https://tatoeba.org/eng/Sentences/show_all_in/kur/none
Ladino: https://tatoeba.org/eng/Sentences/show_all_in/lad/none
Yiddish: https://tatoeba.org/eng/Sentences/show_all_in/yid/none

It likely also effects other languages, though.

**Comment by AndiPersti** [comment]
Thanks for your report. We are already aware of this problem with Yiddish and Kurundi: #2024 

I've just tested your links and while Kurdish breaks, Ladino works for me.

**Comment by trang** [comment]
I will close this as it is duplicates #2024. If you notice other languages where the error happens, please report it in #2024.
