### ISSUE TITLE
Chagatai (chg)

### ISSUE THREAD

**Issue by soliloquist-tatoeba** [Tatoeba/tatoeba2#2092]
- Language name: Chagatai
- Language info: https://en.wikipedia.org/wiki/Chagatai_language
- ISO 639-3 code: chg
- Public List: https://tatoeba.org/eng/sentences_lists/show/9614
- Icon: https://i.imgur.com/PTiur5p.png
- Requested by: https://tatoeba.org/eng/user/profile/soliloquist

[for tatoeba.org]
CALL add_new_language('chg', 9614);

**Comment by soliloquist-tatoeba** [comment]
@trang

Please consider applying the same tweak (dir="auto") you previously did for Ottoman Turkish. 

https://github.com/Tatoeba/tatoeba2/issues/1780#issuecomment-471606563

It perfectly fixes the issues with writing direction.

**Comment by RyckRichards** [comment]
@sabretou :) 

@soliloquist-tatoeba  0 working on it right now
