### ISSUE TITLE
Enabling left-to-right/right-to-left detection for Ladino

### ISSUE THREAD

**Issue by conlangbecca** [Tatoeba/tatoeba2#2096]
Ladino has LTR and RTL alphabets in use; the traditional is RTL but the LTR Aki Yerushalayim orthography has become very popular in recent decades. Since you have a way of detecting left-to-right/right-to-left in use for North Levantine Arabic and Ottoman Turkish, would you be able to enable this for Ladino as well? Thank you.

**Comment by jiru** [comment]
Yes, it’s perfectly possible.

**Comment by conlangbecca** [comment]
That would be great, thanks.
