### ISSUE TITLE
Old Spanish (osp)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2099]
- Language name: Old Spanish
- Language info: https://en.wikipedia.org/wiki/Old_Spanish_language
- ISO 639-3 code: osp
- Public List: https://tatoeba.org/eng/sentences_lists/show/9616
- Icon: https://commons.wikimedia.org/wiki/File:Royal_Banner_of_the_Crown_of_Castile_(Early_Style)-Variant.svg
- Requested by: https://tatoeba.org/eng/user/profile/shekitten

**Comment by conlangbecca** [comment]
FYI, the icon is at https://commons.wikimedia.org/wiki/File:Royal_Banner_of_the_Crown_of_Castile_(Early_Style)-Variant.svg . The URL in the ticket isn't working for me.

**Comment by RyckRichards** [comment]
Thanks, @conlangbecca ! I've updated the ticket.
