### ISSUE TITLE
Daily backup disturbs service for minutes

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2127]
We have a cronjob performing a backup of the entire database on a daily basis. When this happens, any write operation takes forever while reading operations (browsing the website) works. Looking at the backup file timestamps, it looks like the backup is taking 6 minutes to complete.

A possible solution to this problem is to install a secondary slave mysql database that replicates the current one (which would be the master), and to perform the backup from the slave database. Such slave database may also be useful to update dev.tatoeba.org more easily.

**Comment by jiru** [comment]
This is actually more serious than I thought because it makes the web server unavailable (error 502 returned for all clients) because too many requests are bloating the fpm pool. The backup starts at 23:01 and I can observe the following errors in nginx log:

```
[26-Apr-2020 23:05:55] WARNING: [pool tatoeba] server reached pm.max_children setting (64), consider raising it
[27-Apr-2020 23:04:37] WARNING: [pool tatoeba] server reached pm.max_children setting (64), consider raising it
[28-Apr-2020 23:03:21] WARNING: [pool tatoeba] server reached pm.max_children setting (64), consider raising it
[29-Apr-2020 23:04:08] WARNING: [pool tatoeba] server reached pm.max_children setting (64), consider raising it
```

**Comment by jiru** [comment]
Okay I tried to add `--single-transaction --quick` to the mysqldump command, it should help greatly. Wait and see.

**Comment by AndiPersti** [comment]
While it probably doesn't hurt, the `--quick` option should already be in use because it is set in `/etc/mysql/conf.d/mysqldump.cnf`:
````
root@sloth:~# ls -l /etc/mysql/conf.d/mysqldump.cnf
-rw-r--r-- 1 root root 55 Jul  9  2016 /etc/mysql/conf.d/mysqldump.cnf
root@sloth:~# cat /etc/mysql/conf.d/mysqldump.cnf
[mysqldump]
quick
quote-names
max_allowed_packet      = 16M
root@sloth:~# mysqldump --print-defaults
mysqldump would have been started with the following arguments:
--quick --quote-names --max_allowed_packet=16M --default-character-set=utf8mb4
````
