### ISSUE TITLE
No icon is displayed properly on Edge

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2129]
![image](https://user-images.githubusercontent.com/42261966/73998561-5bfd9b80-49a5-11ea-9f83-2321348b65e3.png)

I tried on somebody else's computer because I don't have Edge myself, so please don't ask me to provide more details :D I'm just almost sure that it is an "untuned" version of Edge, as it is never use on that computer.

**Comment by AndiPersti** [comment]
Duplicate of #761?

**Comment by Guybrush88** [comment]
@AndiPersti I think so, and maybe it might be related to #1520

**Comment by trang** [comment]
Yes, it's a duplicate.
