### ISSUE TITLE
no check before attempting to unlink

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#213]
In app/controllers/links_controller.php, in delete(), there is no check to see whether a link exists before attempting to delete. The same message is displayed in any case, namely that there is no longer a link between the sentences. To test, try a URL like this, designed to break the (nonexistent) link between the sentence and itself:

http://127.0.0.1:8080/deu/links/delete/417225/417225

or this one:

http://127.0.0.1:8080/deu/links/delete/417225/1

**Comment by RyckRichards** [comment]
Requested by Guybrush88 during on Tatoeba Day # 7

https://tatoeba.org/eng/wall/show_message/24184#message_24184
