### ISSUE TITLE
Language on orphan sentences page is incorrect

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2133]
Probably following #2121 ?

Steps to reproduce: Contribute -> Adopt sentences -> The selected language is Kirundi

**Comment by jiru** [comment]
I don’t think this is a bug. The selected language for the "Adopt sentences" menu entry is preselected to be the same as what has been selected for the "Browse by language" page, which in turn defaults to the UI language.

**Comment by agrodet** [comment]
Ugh, I was tricked by the fact that my "Brose by language" language had been set to Kirundi (why, though?)

I did try to change the language from the orphan sentences page and come back, just to see that my change was not remembered, so I thought there was a bug. I felt that would be the logical thing to do. I guess that's a different discussion. 

I'm still curious though to know when and why Kirundi became my "browse by language" language xD

**Comment by trang** [comment]
> I'm still curious, though, to know when and why Kirundi became my "browse by language" language xD

Probably when you tried to reproduce #2024 for yourself?

**Comment by agrodet** [comment]
I see. Probably, yes. I'll close this issue myself, sorry for taking your time.

**Comment by trang** [comment]
You probably wouldn't have been confused if the preselected language was handled with a different cookie in "Adopt sentences" and "Browse by language".

Related issue: #419
