### ISSUE TITLE
Consider using translations from Wikidata for language names

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2136]
One of the problems in [the latest UX test performed by Gillux]( https://en.wiki.tatoeba.org/articles/show/ux-test-3) was that some language names were not translated in the Japanese version of the website. 

This probably affects other languages as well. I guess translating the more obscure languages would require even native speakers to look them up somewhere.

I wrote a [Wikidata query](https://query.wikidata.org/#%23%20English%20and%20Japanese%20names%20of%20languages%20supported%20by%20Tatoeba%0ASELECT%20DISTINCT%20%3Fiso_639%20%3Fsource_name%20%3Ftarget_name%0AWHERE%20%7B%0A%20%20%3Flanguage%20wdt%3AP220%20%3Fiso_639%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%3Fsource_name%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%3Ftarget_name.%0A%20%20FILTER%28lang%28%3Fsource_name%29%20%3D%20%27en%27%29%0A%20%20FILTER%28lang%28%3Ftarget_name%29%20%3D%20%27ja%27%29%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%96%B2%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Change%20this%20to%20the%20language%20you%20want%20to%20translate%20into.%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20The%20Japanese%20Wikipedia%20is%20at%20https%3A%2F%2Fja.wikipedia.org%2F%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20So%20%22ja%22%20is%20the%20correct%20code%20to%20use%20here.%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20To%20see%20the%20translations%2C%20scroll%20down%20and%20press%20the%20play%20button%20in%20the%20bottom%20left%20corner.%0A%20%20%23%0A%20%20VALUES%20%3Fiso_639%20%7B%20%23%20Below%20are%20the%20ISO%20639-3%20codes%20of%20all%20languages%20in%20Tatoeba.%20You%20can%20ignore%20them.%0A%20%20%20%20%27abk%27%20%27acm%27%20%27ady%27%20%27afb%27%20%27afh%27%20%27afr%27%20%27aii%27%20%27ain%27%20%27akl%27%20%27aln%27%20%27alt%27%20%27amh%27%20%27ang%27%20%27aoz%27%20%27apc%27%20%27ara%27%20%27arg%27%20%27arq%27%20%27ary%27%20%27arz%27%20%27asm%27%20%27ast%27%20%27avk%27%20%27awa%27%20%27aym%27%20%27aze%27%0A%20%20%20%20%20%20%20%20%20%20%27bak%27%20%27bam%27%20%27ban%27%20%27bar%27%20%27bcl%27%20%27bel%27%20%27ben%27%20%27ber%27%20%27bho%27%20%27bjn%27%20%27bod%27%20%27bos%27%20%27bre%27%20%27brx%27%20%27bua%27%20%27bul%27%20%27bvy%27%20%27bzt%27%0A%20%20%20%20%20%20%20%20%20%20%27cat%27%20%27cay%27%20%27cbk%27%20%27ceb%27%20%27ces%27%20%27cha%27%20%27che%27%20%27chg%27%20%27cho%27%20%27chr%27%20%27chv%27%20%27cjy%27%20%27ckt%27%20%27cmn%27%20%27cmo%27%20%27cor%27%20%27cos%27%20%27cpi%27%20%27crh%27%20%27crs%27%20%27csb%27%20%27cycl%27%20%27cym%27%20%27cyo%27%0A%20%20%20%20%20%20%20%20%20%20%27dan%27%20%27deu%27%20%27div%27%20%27dng%27%20%27dsb%27%20%27dtp%27%20%27dws%27%0A%20%20%20%20%20%20%20%20%20%20%27egl%27%20%27ell%27%20%27emx%27%20%27eng%27%20%27enm%27%20%27epo%27%20%27est%27%20%27eus%27%20%27ewe%27%20%27ext%27%0A%20%20%20%20%20%20%20%20%20%20%27fao%27%20%27fij%27%20%27fin%27%20%27fkv%27%20%27fra%27%20%27frm%27%20%27fry%27%20%27fuc%27%20%27fur%27%20%27fuv%27%0A%20%20%20%20%20%20%20%20%20%20%27gaa%27%20%27gag%27%20%27gan%27%20%27gbm%27%20%27gcf%27%20%27gil%27%20%27gla%27%20%27gle%27%20%27glg%27%20%27glv%27%20%27gom%27%20%27gos%27%20%27got%27%20%27grc%27%20%27grn%27%20%27gsw%27%20%27guj%27%0A%20%20%20%20%20%20%20%20%20%20%27hak%27%20%27hat%27%20%27hau%27%20%27haw%27%20%27heb%27%20%27hif%27%20%27hil%27%20%27hin%27%20%27hnj%27%20%27hoc%27%20%27hrv%27%20%27hrx%27%20%27hsb%27%20%27hsn%27%20%27hun%27%20%27hye%27%0A%20%20%20%20%20%20%20%20%20%20%27iba%27%20%27ibo%27%20%27ido%27%20%27ike%27%20%27ile%27%20%27ilo%27%20%27ina%27%20%27ind%27%20%27isl%27%20%27ita%27%20%27izh%27%0A%20%20%20%20%20%20%20%20%20%20%27jam%27%20%27jav%27%20%27jbo%27%20%27jdt%27%20%27jpn%27%0A%20%20%20%20%20%20%20%20%20%20%27kaa%27%20%27kab%27%20%27kal%27%20%27kam%27%20%27kan%27%20%27kas%27%20%27kat%27%20%27kaz%27%20%27kek%27%20%27kha%27%20%27khm%27%20%27kin%27%20%27kir%27%20%27kjh%27%20%27koi%27%20%27kor%27%20%27kpv%27%20%27krc%27%20%27krl%27%20%27ksh%27%20%27kum%27%20%27kur%27%20%27kxi%27%20%27kzj%27%0A%20%20%20%20%20%20%20%20%20%20%27lad%27%20%27lao%27%20%27lat%27%20%27ldn%27%20%27lfn%27%20%27lij%27%20%27lin%27%20%27lit%27%20%27liv%27%20%27lkt%27%20%27lld%27%20%27lmo%27%20%27lou%27%20%27ltg%27%20%27ltz%27%20%27lug%27%20%27lvs%27%20%27lzh%27%20%27lzz%27%0A%20%20%20%20%20%20%20%20%20%20%27mad%27%20%27mah%27%20%27mai%27%20%27mal%27%20%27mar%27%20%27max%27%20%27mdf%27%20%27mfe%27%20%27mgm%27%20%27mhr%27%20%27mic%27%20%27min%27%20%27mkd%27%20%27mlg%27%20%27mlt%27%20%27mnc%27%20%27mnw%27%20%27moh%27%20%27mon%27%20%27mri%27%20%27mrj%27%20%27mvv%27%20%27mwl%27%20%27mww%27%20%27mya%27%20%27myv%27%0A%20%20%20%20%20%20%20%20%20%20%27nah%27%20%27nan%27%20%27nau%27%20%27nav%27%20%27nch%27%20%27nds%27%20%27ngt%27%20%27ngu%27%20%27niu%27%20%27nld%27%20%27nlv%27%20%27nno%27%20%27nob%27%20%27nog%27%20%27non%27%20%27nov%27%20%27npi%27%20%27nst%27%20%27nya%27%0A%20%20%20%20%20%20%20%20%20%20%27oar%27%20%27oci%27%20%27oji%27%20%27ori%27%20%27orv%27%20%27osp%27%20%27oss%27%20%27osx%27%20%27ota%27%20%27otk%27%0A%20%20%20%20%20%20%20%20%20%20%27pag%27%20%27pam%27%20%27pan%27%20%27pap%27%20%27pau%27%20%27pcd%27%20%27pdc%27%20%27pes%27%20%27pfl%27%20%27pms%27%20%27pnb%27%20%27pol%27%20%27por%27%20%27ppl%27%20%27prg%27%20%27pus%27%0A%20%20%20%20%20%20%20%20%20%20%27quc%27%20%27que%27%20%27qya%27%0A%20%20%20%20%20%20%20%20%20%20%27rap%27%20%27rif%27%20%27roh%27%20%27rom%27%20%27ron%27%20%27rue%27%20%27run%27%20%27rus%27%0A%20%20%20%20%20%20%20%20%20%20%27sag%27%20%27sah%27%20%27san%27%20%27scn%27%20%27sco%27%20%27sgs%27%20%27shs%27%20%27shy%27%20%27sin%27%20%27sjn%27%20%27slk%27%20%27slv%27%20%27sma%27%20%27sme%27%20%27smo%27%20%27sna%27%20%27snd%27%20%27som%27%20%27sot%27%20%27spa%27%20%27sqi%27%20%27srd%27%20%27srp%27%20%27ssw%27%20%27sun%27%20%27sux%27%20%27swe%27%20%27swg%27%20%27swh%27%0A%20%20%20%20%20%20%20%20%20%20%27tah%27%20%27tam%27%20%27tat%27%20%27tel%27%20%27tet%27%20%27tgk%27%20%27tgl%27%20%27tha%27%20%27thv%27%20%27tig%27%20%27tir%27%20%27tkl%27%20%27tlh%27%20%27tly%27%20%27tmw%27%20%27toki%27%20%27ton%27%20%27tpi%27%20%27tpw%27%20%27tsn%27%20%27tso%27%20%27tuk%27%20%27tur%27%20%27tvl%27%20%27tyv%27%20%27tzl%27%0A%20%20%20%20%20%20%20%20%20%20%27udm%27%20%27uig%27%20%27ukr%27%20%27umb%27%20%27urd%27%20%27urh%27%20%27uzb%27%0A%20%20%20%20%20%20%20%20%20%20%27vec%27%20%27vep%27%20%27vie%27%20%27vol%27%20%27vro%27%0A%20%20%20%20%20%20%20%20%20%20%27war%27%20%27wln%27%20%27wol%27%20%27wuu%27%0A%20%20%20%20%20%20%20%20%20%20%27xal%27%20%27xho%27%20%27xmf%27%0A%20%20%20%20%20%20%20%20%20%20%27yid%27%20%27yor%27%20%27yue%27%0A%20%20%20%20%20%20%20%20%20%20%27zlm%27%20%27zsm%27%20%27zul%27%20%27zza%27%0A%20%20%7D%0A%7D%0AORDER%20BY%20%3Fsource_name) that collects translated names for all Tatoeba languages. 

I'm not sure whether all of those translations will be appropriate for Tatoeba, because at least in some cases, the English Wikidata name differs from that on Tatoeba (some are trivial differences like "Chinese (Jin)" vs "Jin Chinese", others are more clearly different, like "Shanghainese" vs "Wu Chinese").

However, it might be a good idea to use the translations from Wikidata in those cases where no translation is currently available.

If you agree, I'd like to know whether changing the translated strings in git is enough to also add them to Transifex, and which files need to be changed. (What's the relation between the .po and .mo files?)

**Comment by AndiPersti** [comment]
> (What's the relation between the .po and .mo files?)

.po are the human-editable files
.mo are generated from the .po files 

See https://www.gnu.org/software/gettext/manual/html_node/Files.html#Files

**Comment by jiru** [comment]
@Yorwba I think it’s a good idea. Note that I had the same idea before but I used data from CLDR instead of Wikidata. Back in the days, I wrote a script that gets language name translations from the CLDR project, and inserts them into .po files. The script is still there at src/Shell/CLDRLanguageNamesShell.php but it doesn’t work any more because it hasn’t been updated for a while (it’s from before we migrated to CakePHP 3).

> If you agree, I'd like to know whether changing the translated strings in git is enough to also add them to Transifex, and which files need to be changed. (What's the relation between the .po and .mo files?)

The process goes like:

1. POT files gets uploaded to Transifex.
2. Translators translate on the Transifex website (PO files).
3. At some point, we pull PO files.
4. We generate MO files from the PO files.
5. We commit PO and MO files in a "Update translations" commit.
6. When we update tatoeba.org, the translations show up online.

So I think the easiest way is to first edit the PO files locally, but then, instead of committing your changes into git, you upload them to Transifex. This should be easy to do with their command line tool `tx`. I suggest that you setup `tx` with a different account name so that it’s more obvious that names have been updated by a machine.

Feel free update the CLDR script or to adapt it to use Wikidata instead.

**Comment by Yorwba** [comment]
Thanks for the pointers. I didn't think of the Unicode CLDR when I was looking for a way to automate translating the language names, but it's kind of obvious in retrospect. IIRC, we are already using ICU for date formatting, so downloading the data files as the CLDR script does wouldn't even be necessary, because ICU comes with [a handy function for getting the name of any language in any language](https://www.php.net/manual/en/locale.getdisplaylanguage.php). On the other hand, when I searched the repo for "ICU" just now, I found [AndiPersti's comment](https://github.com/Tatoeba/tatoeba2/pull/2037#issuecomment-566567786) pointing out that the UI languages Lojban, Latin and Occitan are not in the CLDR. Wikidata does have at least some language names in these languages, so it looks like the more complete solution to me right now.

**Comment by agrodet** [comment]
Although I cannot judge of the quality of the names used, that actually looks very great! :) Just one small thing for next improvements: It would be better to use capital letters for languages that use them, in order to be consistent with how languages are displayed (i.e. in the language select-box)
