### ISSUE TITLE
Some sentences start with \x{A0}

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2138]
## These sentences all start with the non-letter character \x{A0}

2896968	cmn	 我不可能对女人说话。	migl
4551790	epo	 La ĉielarka flago estas la simbolo de respekto de seksa diverseco.	ianna
4615462	epo	 La brazilaj floro kaj faŭno estas karakterizataj de granda diverseco kaj alta grado de endemismo.	ianna
4768609	epo	 Mi respektas ĉiun pensmanieron.	ianna
4932897	ita	 La luce viaggia più veloce del suono.	ianna
4951806	ita	 Le prefiche erano donne pagate per piangere ai funerali.	ianna
5001815	epo	 La dirigento jam staras antau la orkestro.	ianna
5115420	ita	 Mi piace viaggiare in treno, sedere accanto al finestrino e guardare il paesaggio.	ianna
5417126	epo	 Manjo filtras la kafon per papera filtrilo. 	ianna
5435244	epo	 Tomo estas talenta pianludisto ekde sia infanaĝo.	ianna
5463438	epo	 En la suda hemisfero, kie Brazilo situas, hodiaŭ komenciĝas printempo.	ianna
5463492	epo	 La norda stelo ne estas videbla en la suda hemisfero.	ianna

## Suggestions

1. Someone with access to the database should fix these.
2. Perhaps this can be filtered out in future submissions.

**Comment by AndiPersti** [comment]
Related to #2131

**Comment by trang** [comment]
Cf. https://github.com/Tatoeba/tatoeba2/issues/2131#issuecomment-590102420
