### ISSUE TITLE
It's possible to add a duplicate in a different but canonical equivalent form

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/tatoeba2#2139]
Examples on dev:
https://dev.tatoeba.org/deu/sentences/show/4367051
https://dev.tatoeba.org/deu/sentences/show/7841131

![duplicate](https://user-images.githubusercontent.com/6566321/74216240-09bdc280-4ca4-11ea-9136-d1cca80bb91f.png)

I guess we should normalize the text of a sentence, shouldn't we?

I've found [2961 sentences](https://gist.github.com/AndiPersti/b000faf011ddc1611a9eca8b4a7b18e3) which are not in NFC form. (Format of data: id [tab] text as stored in database [tab] text in NFC form)

**Comment by trang** [comment]
For people like me who don't (didn't) know what is this "NFC form":
https://en.wikipedia.org/wiki/Unicode_equivalence

**Comment by agrodet** [comment]
I have faced this several times in the past with Japanese but that's the first time I see it with a European language, that's interesting! :) 
PHP, as many other languages, has its normalizer: https://www.php.net/manual/en/class.normalizer.php 

Also, you can get rid of half-width katakanas by using KC instead of C. See this fiddle https://dotnetfiddle.net/SjIMnk It's in C# but the normalization is (should be) the same. I don't know if you want to get rid of half-width katakanas but I don't see any case where we would want to keep them since we're not cashiers :D (just joking...)

**Comment by AndiPersti** [comment]
> PHP, as many other languages, has its normalizer: https://www.php.net/manual/en/class.normalizer.php

Yes, that's what I want to use.

> Also, you can get rid of half-width katakanas by using KC instead of C. See this fiddle https://dotnetfiddle.net/SjIMnk It's in C# but the normalization is (should be) the same. I don't know if you want to get rid of half-width katakanas but I don't see any case where we would want to keep them since we're not cashiers :D (just joking...)

I don't know anything about half-width katakanas so I'm no help here. But looking at some [normalization charts](http://www.unicode.org/charts/normalization/) this would also influence other languages/scripts so maybe use NFKC only for Japanese?

**Comment by jiru** [comment]
Also note that NFKC [normalizes all kind of spaces into a regular space](https://www.unicode.org/charts/normalization/chart_Separator-Space.html).

**Comment by AndiPersti** [comment]
There are currently only a few sentences in the database which contain characters in the Unicode range `U+FF61 - U+FFEE` (see https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)) and all of these just use the punctuation characters `U+FF61 - U+FF65`:

https://tatoeba.org/eng/sentences/show/76687
https://tatoeba.org/eng/sentences/show/391868
https://tatoeba.org/eng/sentences/show/945909
https://tatoeba.org/eng/sentences/show/1073674
https://tatoeba.org/eng/sentences/show/1077130
https://tatoeba.org/eng/sentences/show/1513031
https://tatoeba.org/eng/sentences/show/3395410
https://tatoeba.org/eng/sentences/show/3605299
https://tatoeba.org/eng/sentences/show/3957783
https://tatoeba.org/eng/sentences/show/5650422
https://tatoeba.org/eng/sentences/show/6070320
https://tatoeba.org/eng/sentences/show/6403017
https://tatoeba.org/eng/sentences/show/8504821
https://tatoeba.org/eng/sentences/show/8504823

**Comment by agrodet** [comment]
I saw some comments on Tatoeba today, about a recommendation to normalize Japanese numbers to half-width or full-width, and I remembered that KC also transforms full-width numbers to half-width numbers. So please forget my suggestion of using KC for Japanese! (full-width numbers life matters :P )
