### ISSUE TITLE
Copy-paste stopped working on Internet Explorer

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2142]
LanguageExpert [reported](https://tatoeba.org/wall/show_message/34146) that copy-pasting broke on Internet Explorer. I am pretty sure that #2123 is causing the problem because I reverted these changes on dev.tatoeba.org and asked LanguageExpert to try again and confirmed that the problem disappeared.

**Comment by Yorwba** [comment]
This is because the event that gets fired is actually a `DragEvent` that doesn't have `clipboardData`. I think I have a fix, but I haven't tested it yet.
