### ISSUE TITLE
The new sentence design is broken in IE 11

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2145]
The homepage for a logged-out user in IE 11:
![homepage](https://user-images.githubusercontent.com/6555947/74591385-dff3fb00-5017-11ea-8fcf-d19f53fbabd2.png)

The homepage for a logged-in user in IE 11:
![homepage_login](https://user-images.githubusercontent.com/6555947/74591413-192c6b00-5018-11ea-8b64-de854ada4659.png)

This is likely because of a [template literal](https://github.com/Tatoeba/tatoeba2/blob/dc4f12f767f3b35f2b6b556c754dd11108f358ad/webroot/js/directives/sentence-and-translations.dir.js#L64), which IE doesn't support.

**Comment by trang** [comment]
Thank you for testing on IE. I pushed a fix and deployed on the [dev website](https://dev.tatoeba.org) in case you want to test some more.

**Comment by Yorwba** [comment]
It's been months since I've last booted my PC into Windows, so I decided to let it install security updates once I was done playing with IE. Let's see whether it's done by tomorrow so I can do some more testing.
