### ISSUE TITLE
Capital letters in Pinyin transcriptions don't get tone marks

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2153]
I'm not sure whether capital letters and spaces in Pinyin even make sense, since there's not really a standardized orthography. However, given that we do have them, "A1" should be displayed as "Ā", just like "a1" is displayed as "ā".
This is what it looks like right now:
![Screenshot](https://user-images.githubusercontent.com/6555947/74753392-5d19ad00-5270-11ea-9fcb-081cb51c11ff.png)

**Comment by jiru** [comment]
I updated the transcriptions on tatoeba.org, it [looks like the problem is solved now](https://tatoeba.org/jpn/sentences/search?query=^阿&from=cmn&to=none).

**Comment by Yorwba** [comment]
Thanks. Some of the sentences starting with 阿 are pretty interesting.
