### ISSUE TITLE
The stats block on the logged-in home page hasn't yet updated. (March 1, 2020 0:41 UTC)

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2172]
https://tatoeba.org/eng
<img width="807" alt="Screen Shot 2020-03-01 at 9 40 40" src="https://user-images.githubusercontent.com/7934273/75617336-28c3bc00-5ba1-11ea-9cb0-63a16b7fecaf.png">

The timeline page is OK, though.

https://tatoeba.org/eng/contributions/activity_timeline
<img width="563" alt="Screen Shot 2020-03-01 at 9 41 02" src="https://user-images.githubusercontent.com/7934273/75617343-2f523380-5ba1-11ea-9ba3-790412672d4f.png">

**Comment by ckjpn** [comment]
UTC 0:53

It's OK now.  However, usually it changes as expected at 0:00 UTC.

<img width="827" alt="Screen Shot 2020-03-01 at 9 53 38" src="https://user-images.githubusercontent.com/7934273/75617453-99b7a380-5ba2-11ea-8465-bb4be3634976.png">

**Comment by ckjpn** [comment]
1:00 UTC 

Note the the "contributions today" number isn't changing.

<img width="803" alt="Screen Shot 2020-03-01 at 10 00 36" src="https://user-images.githubusercontent.com/7934273/75617521-9375f700-5ba3-11ea-94da-be9a346d4c80.png">

**Comment by ckjpn** [comment]
## 2:36 UTC

I would assume that this is some kind of caching problem.

<img width="575" alt="Screen Shot 2020-03-01 at 11 36 24" src="https://user-images.githubusercontent.com/7934273/75618401-181b4200-5bb1-11ea-8ad5-047b26341289.png">

<img width="806" alt="Screen Shot 2020-03-01 at 11 36 10" src="https://user-images.githubusercontent.com/7934273/75618402-19e50580-5bb1-11ea-962c-5439b1b2da2a.png">

## 2:13 UTC
<img width="793" alt="Screen Shot 2020-03-01 at 11 13 12" src="https://user-images.githubusercontent.com/7934273/75618404-1b163280-5bb1-11ea-835a-d4724b7de2e1.png">

**Comment by jiru** [comment]
Yes, the stats block is now cached so the information doesn’t get updated as soon as it used to.
