### ISSUE TITLE
Change the target of the "Need some help?" wiki links to match the language interface of Tatoeba

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2177]
**Problem**
My interface on Tatoeba is in French, the footer says "Need help ?" in French, the links are in French, but their targets are set to the English version of the wiki articles, although French versions exist.

**Expected behavior**
When the corresponding articles have a translation in the current interface language, set it as a target of the link. If not, keep the English.

**Comment by jiru** [comment]
This problem also applies to a number of links to the wiki, like the "no audio available link".

**Comment by jiru** [comment]
I discovered something interesting today. Tatowiki has some redirection mechanism based on the browser language (Accept-language HTTP header), for example:

* https://wiki.tatoeba.org/articles/show/faq
    * redirects to http://fr.wiki.tatoeba.org/articles/show/faq if browser asks for French
    * redirects to http://en.wiki.tatoeba.org/articles/show/faq if browser asks for English

However:

* https://wiki.tatoeba.org/articles/show/quick-start
    * redirects to http://en.wiki.tatoeba.org/articles/show/quick-start if browser asks for English
    * redirects to http://fr.wiki.tatoeba.org/articles/show/quick-start if browser asks for French (page doesn’t exist because the correct slug is premiers-pas)

So we could fix Tatowiki to make it redirect to the correct page (and change http with https), or rename all the page slugs.

**Comment by agrodet** [comment]
I think that in general it would be better to have the same slugs for all languages. Above all, it will avoid contributors choosing the URL. We could then remove the "URL name of this article's translation" field.

**Comment by jiru** [comment]
> I think that in general it would be better to have the same slugs for all languages.

While I agree it would be easier to implement, it’s not very inclusive to assign an English slug for all languages.

> We could then remove the "URL name of this article's translation" field.

We could also autogenerate the slug from the initial article title.

**Comment by jiru** [comment]
This issue was fixed long ago, in #2628.
