### ISSUE TITLE
Insert a comma when sent or messages in inbox > 1,000

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2199]
It occurs to me that on https://tatoeba.org/eng/private_messages/folder/Sent (and on the Inbox folder too) a comma is not inserted when it's > 1,000.

https://prnt.sc/rg12j8

![image](https://user-images.githubusercontent.com/7658430/76673924-dca54e00-6588-11ea-9e54-38e07b012255.png)

The same happened with the advanced search too not long ago.

**Comment by jiru** [comment]
As always, thanks for reporting the problem, Ricardo. :last_quarter_moon_with_face: 

To anyone who wants to solve this issue: check Andrea’s recent pull request #1979.

**Comment by alanfgh** [comment]
Not only is It quite common for a thousands separator to be omitted for numbers less than 10,000, various manuals of style prefer it. From Wikipedia:

https://en.wikipedia.org/wiki/Decimal_separator#Exceptions_to_digit_grouping

> Likewise, some manuals of style state that thousands separators should not be used in normal text for numbers from 1,000 to 9,999 inclusive where no decimal fractional part is shown (in other words, for four-digit whole numbers), whereas others use thousands separators, and others use both. For example, [APA style](https://en.wikipedia.org/wiki/APA_style) stipulates a thousands separator for "most figures of 1,000 or more" except for page numbers, binary digits, temperatures, etc.

I myself prefer omission of a thousands separator in four-digit numbers.

**Comment by AndiPersti** [comment]
`$this->Number->format()` is a function which takes a number like so `$formattedNumber = $this->Number->format(12345);`. But in this case we don't write the number literally but it is stored in `$newMessages` so you need to put that variable inside the function instead of `123` and assign the result back to `$newMessages`.
