### ISSUE TITLE
Order of buttons is not consistent between comment menu and wall menu

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2201]
The comment menu is PM, Hide, Delete, Edit, Reply while the wall menu is PM, Hide, Edit, Delete, Reply.

The comment menu should be modify to have the same order of the wall menu (this order is more logical).

That's a trivial task, I just need the green light :) 

Note: The PM option of the wall menu will be added by #2200

**Comment by jiru** [comment]
Yeah here is the green light :vertical_traffic_light:, feel free to do that in #2200.
