### ISSUE TITLE
sentence added in an RTL language still appears in RTL after changing to an LTR language

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2204]
This sentence:

https://tatoeba.org/eng/sentences/show/7546797

was marked as Algerian Arabic and displayed right-to-left even though the contents were English. When I changed the flag to English, the sentence was still displayed right-to-left.

**Comment by alanfgh** [comment]
I've tagged various such sentences "@change text direction":

https://tatoeba.org/eng/tags/show_sentences_with_tag/10951/arq

**Comment by alanfgh** [comment]
Interestingly, when a sentence was incorrectly marked as Afrikaans (an LTR language), then changed to Persian (an RTL language), the text display correctly changed to RTL.

https://tatoeba.org/eng/sentences/show/1406743

**Comment by jiru** [comment]
Thanks for reporting the problem, Alan.

This is a duplicate of the good old #33, which has been closed because this problem doesn’t exist in the new design. Since we have plans to switch to the new design soon (in a matter of months), I’m going to close this issue as well.

**Comment by alanfgh** [comment]
That's good to hear.
