### ISSUE TITLE
"reply" and "close" (above each Wall message) are not i18n-ized

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#221]
The words "reply" and "close" above each Wall message are not i18n-ized, as opposed to the other options ("hide", "edit", "delete"). The reason seems to be that the strings are hard-coded in app/webroot/js/wall.reply.js. I'm not sure how to internationalize strings in our JavaScript code.

**Comment by jiru** [comment]
This appears to have been fixed already. @alanfgh can you confirm?

**Comment by trang** [comment]
It's not fixed yet: http://prntscr.com/6yuvdz
