### ISSUE TITLE
Displaying only 5 translations is not enough for some users

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2210]
## Problem

Reported initially by [deniko on the Wall](https://tatoeba.org/eng/wall/show_message/34487#message_34487):

> By default, some translations are hidden in the new design and I need to click "Show N more translations" every time in my search results:
> 
> https://i.imgur.com/YyBRn8s.png
> 
> It is very annoying and very counterproductive.

Several others users felt the same frustration at having to expand the translations in the new sentence design.

## Possible solutions

The solution advocated by the users was to implement the option to have all translations displayed in the new sentence design. This option exists in the old sentence design, but in reverse: by default all translations are shown and there is an option `Display a link to expand/collapse translations when there are too many translations`.

The problem with that is that we cannot display an infinite amount of translations. There's a point where having too many translations is counterproductive so having an option to display all translations would not be a long-term solution. We have to set a limit, but a limit of 5 translations is too low for the more "hardcore" users.

So my preferred solution would be to introduce a new option `Number of translations displayed by default`, with the values: 5, 10, 20, 50. The default would be 5. This mimics the option `Number of sentences per page`.

**Comment by agrodet** [comment]
I think the solution you mentioned is only solving a part of the problem you described. In my opinion, that problem can be broken down to three pieces (at least).

Besides your "preferred solution", that is letting the choice to the user to display a different amount of translations, I think the problem won't be solved as long as the two following points aren't solved either.  

- Add a setting or another way to decide "my preferred languages for translations", that would decide what languages should be on top of the translations list. In my opinion, that is the most important point. Basically, that is solving #1907.
- Add the possibility to display all translations for a particular sentence. That is, solving #1157.

**Comment by trang** [comment]
#1907 is more about the default order of indirect translations (which we can extend to direct translations as well). What if a user is not authenticated or has yet not indicated their language preferences, what should be the default order of our translations? The way they are currently ordered is a bit questionable. We order them by language name but there's really no reason for it besides the fact that it was easy and quick to order them that way. I think that's the issue that #1907 should address.

Having a "preferred languages for translations" is the next step. It's basically addressing the issue of users not being satisfied with the defaults. I agree it's also a must have to solve the problem expressed by our users in the Wall thread but I'll create a separate issue for it because it can be implemented completely independently.
