### ISSUE TITLE
Can't copy text from Safari on iPhone

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2211]
Reported by cueyayotl via PM (He allowed me to post it here):

> Also, when using Safari on my iPhone, I noticed that I can't copy text from this site. I can highlight words, and then click on 'copy' but it doesn't put the words on the clipboard, so I am able to paste them elsewhere. On the other hand, I CAN copy text when I click on 'Edit this sentence' (which is only accessible because of my 'Corpus Maintainer' status here)... I assume normal users are unable to copy text at all. However, this isn't an issue with Google Chrome on my PC at all.

**Comment by Yorwba** [comment]
This is probably related to the copy-paste hack to remove furigana from the selection. I've been the last to touch that code (#2123, #2147), so I'd like to fix this problem, but unfortunately I don't have any Apple devices to test this. [CanIUse lists support for clipboard data access on iOS Safari as "unknown"](https://www.caniuse.com/#feat=mdn-api_window_copy_event_clipboarddata), so maybe it's related to that.

@cueyayotl Does the copy button at the right-hand side of each sentence work? It would at least allow you to copy entire sentences.

**Comment by cueyayotl** [comment]
Ah, I didn't realize there was a copy button at the right-hand side of each sentence. But yes, the button does work; I'm just not able to copy individual words right now.

**Comment by trang** [comment]
@cueyayotl Is it a problem on the new sentence design?

**Comment by jiru** [comment]
@cueyayotl Could you try if you can copy text from Safari on https://dev.tatoeba.org/ now?

**Comment by jiru** [comment]
I assume the problem is solved. Feel free to re-open this issue if it isn’t.
