### ISSUE TITLE
[New design] Owner name disappears after editing

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2221]
- Add a sentence, or go to a sentence page. The owner name is displayed on the right of "Sentence #n".
- Edit the sentence.
- The part containing the owner name disappears, leaving only "Sentence #n".

**Comment by trang** [comment]
I can't reproduce this anymore.

**Comment by agrodet** [comment]
Indeed, it seems that the problem doesn't occur anymore.
