### ISSUE TITLE
deleting a sentence from a list page should not take me to the sentence's page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2227]
When I'm on a page that lists sentences, and I make a change to one of the listed sentences, I would like to stay on the list page and have its content preserved except for reflecting whatever change I've made. For instance, when I'm on a page that lists all sentences with a given tag, and I delete a sentence, I would ideally like the page to list all the sentences it did previously, with the exception of the one I deleted. Second-best would be for it to continue to list all the sentences it did previously, including the one I deleted. That wouldn't let me keep track of my progress, but at least it would let me continue to work through the page. But what happens currently is that when I delete a sentence from a list page, I am taken to the sentence page, which now says that the sentence is deleted. This is not useful information to me, and it breaks the flow of my work. I can use the browser's "Back" button, but now the content has to reload. 

Currently, my way of working around this is to right-click on the link to each sentence that I want to work on and open it in a new tab (or window). I'd rather not have to do this.

**Comment by trang** [comment]
In the title you mention "_changing_/deleting".

Are there actually unwanted redirections for other actions than deleting?

If not then I think we can close this ticket since we already have #1831.

**Comment by alanfgh** [comment]
Good question. I changed it to "deleting".

**Comment by trang** [comment]
I will close this issue then since it duplicates #1831.
