### ISSUE TITLE
Wrong warning message when searching for existing tag

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/tatoeba2#2231]
[Tag 7468](https://tatoeba.org/eng/tags/show_sentences_with_tag/7468) has the rather unusual name `'-' it is used for linking two different parts of`.

After [searching for this tag](https://tatoeba.org/eng/sentences/search?query=&from=und&to=und&user=&orphans=no&unapproved=no&has_audio=&tags=%27-%27+it+is+used+for+linking+two+different+parts+of&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance&sort_reverse=) a warning message is shown (`the following criteria have been ignored ... because it's an invalid tag name`) although the correct result is displayed.

**Comment by AndiPersti** [comment]
Steps to reproduce:
1) Go to some sentence
2) Add the following tag: `1234567890123456789012345678901234567890123456789 content after space gets trimmed`
3) Searching for the part before the space will produce a warning and the correct result

A tag name's length is [restricted to 50 bytes](https://github.com/Tatoeba/tatoeba2/blob/d39ecb565a894a661c137302bedbc2eb527e16a0/src/Model/Table/TagsTable.php#L86-L89). If the 50th byte happens to be a space character we will still get the correct result because [MariaDB ignores trailing spaces in VARCHAR comparisons](https://mariadb.com/kb/en/varchar/#description):

    MariaDB [tatoeba]> select 'ab ' in ('ab');
    +-----------------+
    | 'ab ' in ('ab') |
    +-----------------+
    |               1 |
    +-----------------+
    1 row in set (0.00 sec)

But since we [removed trailing spaces from the tag query parameter](https://github.com/Tatoeba/tatoeba2/blob/d39ecb565a894a661c137302bedbc2eb527e16a0/src/Controller/SentencesController.php#L642) we don't find these tags in the result set later on [when we create the list for the warning message](https://github.com/Tatoeba/tatoeba2/blob/d39ecb565a894a661c137302bedbc2eb527e16a0/src/Controller/SentencesController.php#L653-L660).

There is [another tag in the database](https://tatoeba.org/eng/tags/show_sentences_with_tag/7084) which has the same problem.

IMHO there is also a problem with the UI because if someone adds a tag which gets cut down to 50 bytes, she will still see the full name immediately after submitting. Only after a page reload/going to the tag's page the trimmed down tag name is displayed.

**Comment by AndiPersti** [comment]
In order to close this issue after my fix was merged, someone with access to the database still needs to change the two tag names manually in the database:

````sql
update tags set name = 'the famous first sentence of "The Pillow Book" of' where id = 7084;
update tags set name = "'-' it is used for linking two different parts of" where id = 7468;
````

**Comment by jiru** [comment]
Done.
