### ISSUE TITLE
Sentence buttons cluttered in list view (new design)

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2235]
When looking at a sentence in a list, there is less space than usual (because of the (-) removal icon on the right) and the menu buttons (if expanded) span on two lines:
![image](https://user-images.githubusercontent.com/5107734/77874189-d0a2d700-727e-11ea-9230-5fc987d5044e.png)

**Comment by trang** [comment]
Since the "link" button has been removed, this is no longer an issue.

![Screenshot_2020-05-17 Test - Tatoeba](https://user-images.githubusercontent.com/221850/82138948-b1f3a200-9824-11ea-9a06-fbafad52937a.png)
