### ISSUE TITLE
Now this doesn't work:   search?from=spa&to=none. doesn't show none

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2236]
This kind of search is now showing all translations.

https://tatoeba.org/eng/sentences/search?from=spa&to=none&user=herchx

**Comment by AndiPersti** [comment]
Sorry, my mistake.

I've just pushed a fix and it should work again soon.

**Comment by jiru** [comment]
The problem is fixed now.
Thanks for reporting the problem, @ckjpn.
Thanks for the fix, @AndiPersti.

**Comment by ckjpn** [comment]
Thanks.  I do this kind of search and then filter out HTML to create lists of sentences like the following for members recording sentences with the Shtooka Recorder.

8646060 - Se aclarará pronto.
8646069 - Te arrepentirás muchísimo.
8646085 - Cometimos demasiados errores.
8646122 - Comprendemos la situación.
8646124 - Comprendemos los problemas.
8646129 - Comprendo los problemas.
8646130 - Comprendo la situación.
8646146 - Tom tiene problemas.
8646165 - Solamente estamos hablando.
8646079 - Nadie sospechaba de mí.
8646089 - ¿Vas a comprar eso?
8646131 - Estos son problemas complicados.
8646132 - Estos son problemas serios.

It would be cool if someday, I could just add a variable in the search URL like "&shtooka=yes" to get this kind of output.  However, I already have a script that can merge multiple downloaded pages, then output this kind of text file with up to 1000 lines.
