### ISSUE TITLE
Show the most-recently tagged sentences at the top the "/tags/show_sentences_with_tag/" pages

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2237]
## I'd like to see this be the default sort for tags.

Show the most-recently tagged sentences at the top.

https://tatoeba.org/eng/tags/show_sentences_with_tag/276/eng?sort=added_time&direction=desc

## The Reason

This is a good way to monitor which sentences are getting added to the "tag" lists.

If I remember correctly, this is also how it used to be.

## This now takes 3 clicks, plus the time it takes to load in the pages.

I would assume this also puts an extra unnecessary load on the server.

1. Go to the Proverb tags

https://tatoeba.org/eng/tags/show_sentences_with_tag/407

2. Click "date of tag"

https://tatoeba.org/eng/tags/show_sentences_with_tag/407?sort=added_time&direction=asc

3. Click "date of tag" again to reverse the sort

https://tatoeba.org/eng/tags/show_sentences_with_tag/407?sort=added_time&direction=desc

## I don't think this is just my own preference.

Should I or someone else put a Wall post about this to solicit other members' opinions?

**Comment by agrodet** [comment]
It seems indeed logical that on a page focused on tags, the default order should relates to tags. 

In a more general level, #2161 will redesign the sort options.

**Comment by AndiPersti** [comment]
Fixed in #2367.
