### ISSUE TITLE
Sentence block on Reviews page doesn't scale down correctly

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2254]
My reviews, with my browser set to 90% display. 

![image](https://user-images.githubusercontent.com/42261966/78487252-61e3e300-7782-11ea-9903-90c05c998f06.png)

This issue doesn't occur on a list page. Although the div have the same `sentence mainSentence` class attribute, the CSS for `sentence` on the reviews page forces `width:600px`. I think that's the cause.

**Comment by agrodet** [comment]
I will take care of design issues on this page. See the following 

![image](https://user-images.githubusercontent.com/42261966/81265302-d1990680-907d-11ea-9354-789114af46fa.png)

@trang What do you think of the review marks being displayed in the middle while the copy icon is at the top?

**Comment by trang** [comment]
@agrodet I think the icons should be aligned with each other. Best is probably to have them both at aligned at the top because that also fits the alignment with the  `#` and language icons.
