### ISSUE TITLE
Create a third label on sentences' pages:  "Same language equivalent"

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2262]
## What to do

Create a third label on sentences' pages - "Same language equivalent"

In addition to ...

* Translations
* Translations of translations

## Why?

This would solve this issue.
https://github.com/Tatoeba/tatoeba2/issues/2107
It's innacurate to label same language sentences as "Translations

## One possible approach

```
IF code_of_linked_sentence == code_of_main_sentence
THEN put the_linked_sentence(s) in a category called "Same language equivalent".
```
Said a different way...
> In the programming, if the language of the main sentence is the same as the language of a linked sentence, put the linked sentence in a new category called something like "Same Language Equivalents" and list these under the main sentence.

These could be listed in one of these 3 places.

1. Just under the main sentence.
2. Just before "translations of translations"
3. Just after "translations of translations"

I think it would make the most sense to put these (or it) just under the main sentence, but perhaps others would think one of the other positions would make more sense.

Related: https://github.com/Tatoeba/tatoeba2/issues/2107#issuecomment-594273857

## Is it useful to have interchangeable sentences in the same language linked?

Yes.

1. This allows translators to add the same translation to both at the same time, thus saving time.
2. This allows those studying a language to see several ways to say the same thing even if there are no translations.

**Comment by jiru** [comment]
Thanks for your suggestion, CK, but there is no need to open a new issue. Please comment in #2107 instead so that the discussion is easier to follow.
