### ISSUE TITLE
The button to add translations stopped working in user's page with sentences to translate

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2272]
I wanted to translate some sentences through this page https://tatoeba.org/ita/activities/translate_sentences_of/ajje , and I noticed that the button used to open a form where you can add a translation doesn't work anymore, so, as a workaround, I have to open the single sentence, where the button works. I tried with Firefox 75.0 both on Ubuntu 19.10 and Windows 10.

Steps to reproduce the bug:
1) open any profile
2) go to the "Translate user's sentences" page
3) from there, try to open the form where you can add the translation you want to submit

**Comment by Guybrush88** [comment]
I've just been told that this bug happens also here: https://tatoeba.org/ita/sentences/add

**Comment by AndiPersti** [comment]
I've just pushed a fix and as soon as the new version is deployed it should work again.
As a workaround you could also use the new design where this bug doesn't exist.

**Comment by jiru** [comment]
I’ve deployed the fix on production.

@Guybrush88 Thanks for letting us know.
@AndiPersti Thanks for the fix.

**Comment by Guybrush88** [comment]
@jiru you're welcome :)
and thanks @AndiPersti for the very quick fix
