### ISSUE TITLE
Blank page no vocabulary items are found

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2273]
## Problem

When filtering by language, often the page is blank with no idication why it is blank.

https://tatoeba.org/eng/vocabulary/add_sentences/kor

![screen shot 2016-07-06 at 08 21 39](https://cloud.githubusercontent.com/assets/7934273/16602954/3866dd82-4353-11e6-9bf6-0eb29fbd71fa.png)

## Possible Solution

Put a message saying something like the following.

There are no requests for Korean.
There are no requests for this language.

There are no requests for Korean that do not already have at least 10 sentences.
There are no requests for this language that do not already have at least 10 sentences.

_Originally posted by @ckjpn in https://github.com/Tatoeba/tatoeba2/issues/1148#issuecomment-230632296_

**Comment by speedysera** [comment]
Hi! Regarding the styling, would something like this be acceptable?

![tatoeba-message-no-requests](https://user-images.githubusercontent.com/43659877/85184506-fdd5b300-b2ca-11ea-8ae7-15896c4ea052.png)

**Comment by ckjpn** [comment]
If you are referring to the thin light green text on a block of darker green, I find that a lot more difficult to read than the current black font on a white background as shown in the screenshot in the first post in this discussion.

I suspect this goes against accessibility guidelines that a lot of websites follow to help those with vision problems.

**Comment by speedysera** [comment]
Thanks for the insight @ckjpn ! It's good to consider accessibility.

It seems the green header also exists in the case where there are sentences to display:

![tatoeba-message-header](https://user-images.githubusercontent.com/43659877/85186480-329a3800-b2d4-11ea-896c-1e8dbffd3aa1.png)

@trang are we going to change the display header anytime soon for accessibility? 


Regarding the styling question, I was wondering about this section in particular: 

![Screen Shot 2020-06-20 at 9 00 42](https://user-images.githubusercontent.com/43659877/85186528-8d339400-b2d4-11ea-9841-1a039c2647c1.png)

Do we want to display "There are no requests for this language that do not already have at least 10 sentences." along with the existing header as shown in the screenshots, or as a separate entry with different styling? 

I am open to suggestions :)

**Comment by AndiPersti** [comment]
> Also, is there a function that would allow us to query the current language being featured, so that we can display "There are no requests for that do not already have at least 10 sentences."

In the controller we pass already `langFilter` which contains the 3-letter-code for the language and is currently not used in the template:
https://github.com/Tatoeba/tatoeba2/blob/119c63774b3e9ee62eec77c02f8d7b442d8d35f6/src/Controller/VocabularyController.php#L130

We have a helper function [`codeToNameAlone`](https://github.com/Tatoeba/tatoeba2/blob/119c63774b3e9ee62eec77c02f8d7b442d8d35f6/src/Model/Entity/LanguageNameTrait.php#L69-L71) which you can use to get the full language name. The trait is [included in the `Languages` helper](https://github.com/Tatoeba/tatoeba2/blob/119c63774b3e9ee62eec77c02f8d7b442d8d35f6/src/View/Helper/LanguagesHelper.php#L48) so you can use the helper function in the template, e.g.
````php
$language = $this->Languages->codeToNameAlone($langFilter)
````
(you should handle the case where `$langFilter` is not set, i.e. vocabulary items in all languages are displayed.)

**Comment by AndiPersti** [comment]
> Do we want to display "There are no requests for this language that do not already have at least 10 sentences." along with the existing header as shown in the screenshots, or as a separate entry with different styling? I am open to suggestions :)

We currently don't have a distinct design/style that determines how to display an empty result page (see also #2074, third bullet point).

I personally prefer having just a simple explanation without any header like we do for example with searches: https://tatoeba.org/eng/sentences/search?query=&from=abk&to=afh

**Comment by trang** [comment]
@speedysera There's indeed no default style yet for "no results" pages but I started to introduce something for the lists when they're empty.

![Screenshot_2020-06-20 Test list - Tatoeba](https://user-images.githubusercontent.com/221850/85201532-80c53080-b300-11ea-8f04-a7ed868aada4.png)

You can do something that looks similar here for the vocabulary and a create CSS class in the `default.css` that could be reused in general for empty pages. 

```
.empty-info-text {
    text-align: center;
    font-size: 2em;
    color: #666666;
}
```

As for the language information, you could add it in the title rather than the "no requests" text.

![Screenshot_2020-06-20 Sentences to switch to CC0 - Tatoeba(2)](https://user-images.githubusercontent.com/221850/85201738-11504080-b302-11ea-9a32-73d04cb05890.png)

This would follow the pattern on other pages.
- [Sentences in Korean](https://tatoeba.org/eng/sentences/show_all_in/kor/none)
- [Orphan sentences in Korean](https://tatoeba.org/eng/activities/adopt_sentences/kor)
- [{user}'s sentences in Korean](https://tatoeba.org/eng/Sentences/of_user/TRANG/kor)

**Comment by speedysera** [comment]
Thank you, the above looks much clearer, let me implement that.

**Comment by speedysera** [comment]
@AndiPersti hi! I tried to reflect all the comments above, hope it's alright

**Comment by speedysera** [comment]
hi! I would like to ask if the following is alright:

if langFilter is empty, 
![Screen Shot 2020-08-13 at 5 02 18](https://user-images.githubusercontent.com/43659877/90062151-353c6b00-dd22-11ea-9b93-77930b5d6c60.png)

if not,
![Screen Shot 2020-08-13 at 5 01 02](https://user-images.githubusercontent.com/43659877/90062089-1b028d00-dd22-11ea-9293-309fb4263568.png)

if the above is ok, I will push the commit and create a new pull request

**Comment by jiru** [comment]
@speedysera It looks good. Please show us the code! :slightly_smiling_face:

**Comment by speedysera** [comment]
hi! please take a look at the code if it's alright. I can create the new PR afterwards

**Comment by jiru** [comment]
@speedysera Thanks! The code looks good.

Note that it’s better if you create the PR first and then we look at the code. Don’t worry, you don’t have to get it perfect beforehand. We are all here to learn. :+1:

**Comment by speedysera** [comment]
hi @jiru ! Thanks and sorry about that, please refer to the branch above.

**Comment by speedysera** [comment]
hi @jiru and @AndiPersti ! thanks for the awesome comments, I will work on them.
