### ISSUE TITLE
It's not possible to change flag in the new design

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2276]
Steps to reproduce

1 - Go to sentence https://tatoeba.org/eng/sentences/show/5893065  
2 - Change the flag to Bislama
3 - Click on the pencil and so, click on Save

Nothing happens. The flag is displayed but whenever I press F5, the language is set to "unknown".

![image](https://user-images.githubusercontent.com/7658430/79129999-9eb06b00-7d7c-11ea-80e9-1ac02b27eadf.png)

![image](https://user-images.githubusercontent.com/7658430/79130027-acfe8700-7d7c-11ea-89ba-72ed3e3e7b04.png)

**Comment by AndiPersti** [comment]
I've just pushed a fix. It should work again soon.

**Comment by RyckRichards** [comment]
Thanks a lot, @AndiPersti !

**Comment by jiru** [comment]
@RyckRichards I pushed Andreas’ fix. Can you confirm it solves the problem?

**Comment by RyckRichards** [comment]
That works now! Thank you so much, everyone! Closing this
