### ISSUE TITLE
Updated flags

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2292]
Related Wall post: https://tatoeba.org/eng/wall/show_message/34867 (By sabretou)

He suggested improvements for the following flags:

* Gulf Arabic (afb)
* Arabic (ara)
* Cayuga (cay)
* Lower Sorbian (dsp)
* Dutton World Speedwords (dws)
* Scots (sco)
* Scottish Gaelic (gla)
* Kamba (kam)
* Naga (Tangshang) (nst)
* Old Spanish (osp)
* Sanskrit (san)
* Tahaggart Tamahaq (thv)
* Old Turkic (otk)

Gallery: https://imgur.com/a/zV2MnQp

Copying and pasting the message he posted on the Wall here:

== Gulf Arabic ==

>This is a minor update to bring this flag in line with the other flags having similar language-code design. The only real change is the font of the language code.

== Arabic ==

> The current Arabic flag has strong aliasing, which makes the edges of the font look very rough. I also thought that the shade of green used was too bright to properly contrast with the white text.

> My proposed flag uses a darker shade of green for greater contrast and smoother text.

== Cayuga ==

The flag now uses the same color as that of the Iroquois Confederacy flag, which is where we got the symbol from.

== Lower Sorbian ==

> The symbol on the flag has been centered to be in view, in keeping with similar flags that use a symbol flag and a language code together.

== Dutton World Speedwords ==

> The current flag uses gradient colors of indeterminate origin. My updated flag uses a yellow-on-black design that is in line with the cover of Reginald J. G. Dutton's seminal book "Teach Yourself Dutton Speedwords".

== Scots and Scottish Gaelic ==

> The Scottish flag has been compressed to be more obvious.

== Kamba ==

> Fixed the language code font.

== Naga (Tangshang) ==

> Switched to a neutral language code flag. The original flag belonged to a militant group named National Socialist Council of Nagaland, that designated as a terrorist organization by India. It may not be in our best interest to use such a flag.

== Old Spanish ==

> This is a minor fix. I have only moved the flag to be left-aligned (as if on a flag pole), rather than center-aligned. This brings it in line with the flag of Nepali and Old Norse, which are both also non-rectangular flags.

== Sanskrit ==

> The present flag uses the Devanagari and Kannada letters of mismatched size. I cannot determine why the Kannada letter 'ka' is being used here, as Sanskrit is used far more frequently in other scripts. Besides, we seem to stick to using the Devanagari script for Sanskrit on Tatoeba anyway. // Used a better display font.

> The new flag uses the Devanagari letter 'सं', which I chose over writing out the name of the language, as the latter option was a lot more illegible. The field colour of the flag has been updated to use the saffron colour found in the flag of India (which is the only country to recognise Sanskrit in an official capacity). The letter सं uses a shade of grey for contrast and aesthetic purposes.

== Tahaggart Tamahaq ==

> Fixed the language code font.

== Old Turkic == (by @soliloquist-tatoeba )

>It was discussed on the Wall in 2018. https://tatoeba.org/eng/wall/show_message/30380#!#message_30380 I removed the white space on the right and bottom edges. I guess we don't add it anymore.

**Comment by soliloquist-tatoeba** [comment]
Can we change the icon of Old Turkic (otk) along with the others? It was discussed on the Wall in 2018.

https://tatoeba.org/eng/wall/show_message/30380#!#message_30380

You could use this one. 

https://i.imgur.com/lVJd7PP.png

I removed the white space on the right and bottom edges. I guess we don't add it anymore.

**Comment by sabretou** [comment]
@soliloquist-tatoeba Definitely! I was keen on having that one changed, but I didn't know what colours or text would be appropriate.

Also, here's the updated list of proposals: https://imgur.com/a/zV2MnQp

**Comment by RyckRichards** [comment]
@soliloquist-tatoeba @sabretou I'm going to update the ticket to include Old Turkic (otk) then.
