### ISSUE TITLE
How to import all the database to a local environment?

### ISSUE THREAD

**Issue by antyol** [Tatoeba/tatoeba2#2298]
I'm new to vagrant and VM world, i just installed everything locally and got it up and running but i have an empty database. i read some of the yaml config files but didn't know how to use them in order to fetch/download the database locally.

I've read all the readme files but didn't get anywhere.

Any help or guidance will be much appreciated, thanks.

**Comment by trang** [comment]
I'll close this issue since there's already Tatoeba/imouto#59 which has been answered :)
