### ISSUE TITLE
Logs are not displayed on the Spanish interface

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2307]
Shishir has found out that bug

Steps to reproduce

Take, for example, the sentence https://tatoeba.org/spa/sentences/show/8742131

If you choose any language except Spanish, you'll get something like this:

![image](https://user-images.githubusercontent.com/7658430/81220582-eca14300-8fb7-11ea-927c-72da44825f3b.png)

Select Spanish as the UI interface. You'll get this.

![image](https://user-images.githubusercontent.com/7658430/81220719-296d3a00-8fb8-11ea-8446-6bb4f04a4536.png)

**Comment by Yorwba** [comment]
That's because the string [`{info}, {date}`](https://www.transifex.com/tatoeba/tatoeba_website/viewstrings/#es/tatoebaResource/96619207?q=text%3A{info}%2C) is translated as `{información}, {fecha}`. Because the text inside the curly braces was changed, the missing information can't be filled in.

**Comment by jiru** [comment]
Thanks, Yorwba. I can see that this string was translated by arh 3 months ago. A few weeks ago I noticed that arh translated placeholders and I sent a PM already to explain. So I’m gonna fix that one Spanish string and there is no need to tell arh again. Besides, we have now configured Transifex to make it harder to translate placeholders, so it’s very unlikely to happen again.
