### ISSUE TITLE
Phoenician (phn)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2309]
* Language name: Phoenician
* Language info: https://en.wikipedia.org/wiki/Phoenician_language
* ISO 639-3 code: PHN
* Public List: https://tatoeba.org/eng/sentences_lists/show/128723
* Icon: https://commons.wikimedia.org/wiki/File:Phoenician_Language_Flag.svg
* Requested by: https://tatoeba.org/eng/user/profile/shekitten

**Comment by jiru** [comment]
Note to self: add the Phoenician alphabet to Manticore config: `U+10900..U+1091B`
