### ISSUE TITLE
"Chinese (Jin)" is confusingly named

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2318]
A few days ago, I noticed that someone had started to add a lot of sentences in "Chinese (Jin)" (`cjy`) but they looked no different than the Mandarin I'm used to. So I wrote them a private message asking about those sentences, to which the user replied that they do speak Jin at home, but usually write in Mandarin, and they didn't pay attention to the "Jin" in parentheses at first.

The problem here is that "Chinese (Jin)" is the first result if you enter "Chinese" into the language selector field and there is no other language named "Chinese (X)", so the meaning of the parentheses is not self-explanatory.

I think it would be better if the naming were consistent, i.e. either rename "Chinese (Jin)" to "Jin Chinese" or rename the others to follow the "Chinese (X)" pattern.

**Comment by trang** [comment]
As far as I can tell, the decision to name the language `Chinese (Jin)` rather than `Jin Chinese` (#1089) came before we implemented the searchable language selector (#1651). Now that we have the searchable language selector, the rationale to name the language `Chinese (Jin)` is no longer relevant.

We renamed the `Chinese (X)` languages at some point (#1590) but it seems `Chinese (Jin)` was forgotten? @Tatoeba/language-team Could you confirm this was not intentional?

**Comment by sabretou** [comment]
It was definitely not intentional, and it was likely an oversight when the languages were renamed.

I agree that we should change the name to "Jin Chinese".

**Comment by soliloquist-tatoeba** [comment]
On Transifex, I had already changed the Turkish translation of that string to the unparenthesized version (it sounds better in Turkish) and ignored the warning message "The translation does not contain the same number of opening parentheses". It's good to see them matching exactly now.

https://www.transifex.com/tatoeba/tatoeba_website/translate/#tr/tatoeba-languages/89015325

Note that the strings 'Punjabi (Western)' and 'Punjabi (Eastern)' are possibly in a similar position.

**Comment by jiru** [comment]
@soliloquist-tatoeba Don’t hesitate to report us any other English string that you think could be better rephrased. Translators are often in the best position to judge about the relevance of the original text.
