### ISSUE TITLE
Add "UTC" to tooltip displayed when hovering over a time

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2319]
I was unsure as to whether the times displayed for my contributions corresponded to UTC or to my own time zone. The only way I could figure it out was to add comments on the dev site (for instance, "I wrote this comment at 7:23 p.m. on Saturday, 2020-03-14, my time"), and then come back after enough time had passed that they were no longer displayed as "36 minutes ago" but rather as "March 14, 2020 at 11:23 PM". By matching the time that I wrote in the comment with the time as displayed, I could see that the times corresponded to UTC, not to my time zone. It would probably be overkill for the actual text for times to include "UTC" at the end to indicate that all times correspond to Universal Coordinated Time, but it would be nice if the hover text included this.

**Comment by trang** [comment]
> It would probably be overkill for the actual text for times to include "UTC" at the end to indicate that all times correspond to Universal Coordinated Time, but it would be nice if the hover text included this.

+1. This is the way GitHub does it and I think it makes sense.

Related: #1125

**Comment by polkadotazn** [comment]
Got it! Looks like it's in this page here? https://github.com/Tatoeba/tatoeba2/blob/49ea1514135aeeaddb6290cbb22b54e4b6f15c38/src/Template/Element/sentence_comments/comment.ctp

**Comment by jiru** [comment]
@polkadotazn Yes, that’s a good starting point! If you look closely, you’ll see that `$dateLabel` is created from `$this->Date->getDateLabel()`, which is located in the DateHelper under `src/View/Helper/DateHelper.php`.

**Comment by polkadotazn** [comment]
I have just made this PR: https://github.com/Tatoeba/tatoeba2/pull/2368

**Comment by jiru** [comment]
@polkadotazn Your enhancement  is now running on tatoeba.org. Thanks @polkadotazn and @alanfgh. :smile_cat:
