### ISSUE TITLE
Is there any exposed API?

### ISSUE THREAD

**Issue by YousufAzadSami** [Tatoeba/tatoeba2#2320]
For example, for a specific word, I want to get 5 sentences. So, this with the most common used words can be a effective learning tool.

**Comment by AndiPersti** [comment]
No, there is no API (yet).
Since I don't expect that there will be one in the near future, you could [download the sentences](https://tatoeba.org/eng/downloads) for the language you are interested in and process them yourself.

**Comment by trang** [comment]
See our [FAQ](https://en.wiki.tatoeba.org/articles/show/faq#does-tatoeba-provide-an-api?) as well.

I'm closing this issue. If you have other questions don't hesitate to ask.
