### ISSUE TITLE
In the new design, when the menu is expanded, the username is no longer visible

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2326]
Reported by [AlanF_US and CK on the Wall](https://tatoeba.org/eng/wall/show_message/35160#message_35160):

> the user name disappears in "display more" mode, and I don't want to have to keep switching modes. 

> While we see the the owner's name in the "show less" version, when browsing while showing all the things we need using the "show more" version, we don't see the owners' names, which means we still need to constantly toggle between the two.

**Comment by Yorwba** [comment]
This was fixed in #2855.

**Comment by trang** [comment]
Yes, thanks for the reminder :)
