### ISSUE TITLE
The language selection dropdown on some pages is not searchable

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2328]
The source and target languages in the search bar can be selected by typing part of the language's name and choosing from a filtered list. However that is not the case for the advanced search and a few other pages I checked (e.g. the "browse by language" page), so it's necessary to scroll through the full list to find a language that's not part of the profile languages.

**Comment by Guybrush88** [comment]
another page where this selection doesn't appear is the page containing orphan sentence (to help with a list of pages without this behavior): https://tatoeba.org/ita/Activities/adopt_sentences/
