### ISSUE TITLE
Color of review icons is inconsistent

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2333]
Reported by [AlanF_US on the Wall](https://tatoeba.org/eng/wall/show_message/35153#message_35153):

> When I look at the sentences I've reviewed:
> 
> https://dev.tatoeba.org/eng/reviews/of/AlanF_US
> 
> there's a box "Filter" in the upper right-hand corner. Within that box, the items "Sentences marked as 'OK'", "Sentences marked as 'unsure'", and "Sentences marked as 'not OK'" are preceded by the checkmark, question mark, and exclamation mark icons. However, the icons are in gray. It would make more sense for them to be in green, orange, and red, as they are next to the sentences.

**Comment by agrodet** [comment]
I'm working on #2254 and some other things so I can take care of this at the same time

**Comment by trang** [comment]
Go for it, @agrodet :)
