### ISSUE TITLE
Fix wrong license of some sentences

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2335]
Some sentences have been affected a wrong license, as described in #2322.
TODO: write a cake shell that allows to massively fix the license of a selectable subset of sentences (with the creation of a "license changed" in the contributions log).
TODO2: make the script so that we can use it to set the license to any value, such as "licensing problem", too.

**Comment by AndiPersti** [comment]
All wrong licenses should be fixed.
