### ISSUE TITLE
wording: "generated by a piece of software"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2352]
On the dev site, when I look at sentence number 16491, I see two Japanese translations. The first has another version under it with a red triangle icon next to it. When I hover over that, I see the text "This alternative script may contain errors because it has been generated by a piece of software that is not perfect."

![automatic_not_perfect](https://user-images.githubusercontent.com/1213027/83200186-c8490a00-a110-11ea-982f-ac94834553ff.png)

When I hover over a second one, I see the text "This alternative script was generated by a piece of software."

![piece_of_software](https://user-images.githubusercontent.com/1213027/83200223-deef6100-a110-11ea-8065-b5ee8968a0e6.png)

There are a couple of issues with this.

(1) The first message feels a bit alarmist.

(2) The wording seems a little awkward.

(3) It's not clear to me what the difference is between the two sentences. Is it that one was not reviewed, while the other was?

I prefer this text:

"This transcription was generated automatically."

If you want to stress that the transcription has not been reviewed, you can say:

"This transcription was generated automatically and has not been reviewed."

**Comment by trang** [comment]
Thanks for the wording suggestions, @alanfgh.

To summarize, we have the following cases:

1) The transcription was automatically generated and we know that the software is 100% accurate. It therefore doesn't need to be reviewed.
→ The tooltip would be `This transcription was generated automatically.` or `This alternative script was generated automatically.`

2) The transcription was automatically generated and we know that the software is not always accurate. It needs to be reviewed.
→ The tooltip would be `This transcription was generated automatically and has not been reviewed.` or `This alternative script was generated automatically and has not been reviewed.`

3) The transcription has been reviewed.
→ The tooltip would indicate who reviewed it and when, as it does now.

**Comment by alanfgh** [comment]
That makes sense.

I think of "script" as referring to a system of writing and "transcription" as referring to (a) a process or (b) a single piece of text. (Case b is the relevant one here.) Therefore, I prefer "transcription" to "alternative script".

**Comment by trang** [comment]
We actually have different wordings for alternative scripts and transcriptions.

For instance, pinyin will be referred as to "transcription". But simplified/traditional Chinese will be referred to as "alternative script".

The various tooltip texts are defined here:
https://github.com/Tatoeba/tatoeba2/blob/dev/src/Model/Entity/Transcription.php#L193

Unless we decide to merge the tooltips and refer to everything as "transcription", we would need to adapt the strings for both cases.

I guess better would be to use the specific name of the transcription whenever we can:
  - This pinyin was automatically generated...
  - This simplified Chinese script was automatically generated...
  - This traditional Chinese script was automatically generated...

**Comment by alanfgh** [comment]
Yes, I like that idea.

**Comment by RyckRichards** [comment]
Please, could you enlight this for me? I would have to remove  "This alternative script may contain errors because it has been generated by a piece of software that is not perfect." and add the 3 new strings pointed before? If so, what would be the workaround? Thank you!

> Thanks for the wording suggestions, @alanfgh.
> 
> To summarize, we have the following cases:
> 
> 1. The transcription was automatically generated and we know that the software is 100% accurate. It therefore doesn't need to be reviewed.
>    → The tooltip would be `This transcription was generated automatically.` or `This alternative script was generated automatically.`
> 2. The transcription was automatically generated and we know that the software is not always accurate. It needs to be reviewed.
>    → The tooltip would be `This transcription was generated automatically and has not been reviewed.` or `This alternative script was generated automatically and has not been reviewed.`
> 3. The transcription has been reviewed.
>    → The tooltip would indicate who reviewed it and when, as it does now.

**Comment by alanfgh** [comment]
Yes, exactly.
