### ISSUE TITLE
The option "Always show transcriptions..." is confusing

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2353]
On both the product site:

![transcriptions_prod](https://user-images.githubusercontent.com/1213027/83201689-0e539d00-a114-11ea-9860-af34fe9d1acc.png)

and the dev site:

![transcriptions](https://user-images.githubusercontent.com/1213027/83201693-11e72400-a114-11ea-87a4-295be4463222.png)

I see transcriptions even though I've deselected "Always show transcriptions and alternative scripts" in both cases:

![always_show_transcriptions](https://user-images.githubusercontent.com/1213027/83201967-a0f43c00-a114-11ea-8a69-7184e9524cf2.png)

I'm a little confused about the interaction between deselection and the use of the word "always". If the wording were simply "Show transcriptions and alternative scripts", I would expect them to be displayed when it's checked, and hidden when it's unchecked. But "always" makes me wonder whether some condition I don't know about affects whether they're shown when the option is deselected. In other words, does "not always" == "never" for this option?

**Comment by alanfgh** [comment]
> The option should maybe be reworded to "Always show unreviewed transcriptions and alternative scripts."

That does sound clearer to me.

**Comment by RyckRichards** [comment]
I'd like to work on it :)
