### ISSUE TITLE
Tag autocomplete has quit working as usual since the insertion of the number of tags was added.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2366]
You can partially type in the tag name, then click on the tag, but it doesn't result in the tag being put where it should be.  Is there a reason these numbers need to be there?  They sort of clutter up things and aren't needed in order to add tags.

<img width="198" alt="Screen Shot 2020-06-01 at 15 52 55" src="https://user-images.githubusercontent.com/7934273/83383559-53cbdf00-a420-11ea-8fe0-bfa32a7edac0.png">

**Comment by trang** [comment]
>  Is there a reason these numbers need to be there?

See #1429.

**Comment by AndiPersti** [comment]
> You can partially type in the tag name, then click on the tag, but it doesn't result in the tag being put where it should be.

Where should it be put?

**Comment by trang** [comment]
I think the expected result is: if I click on "imperative (10524)", the tag is added to the sentence.

I'm not 100% sure though. It could also be: if I click on "imperative (10524)", the input value is set as "imperative" and I have to click the `+` button or press enter in order to add it to the sentence.

**Comment by AndiPersti** [comment]
> I'm not 100% sure though. It could also be: if I click on "imperative (10524)", the input value is set as "imperative" and I have to click the `+` button or press enter in order to add it to the sentence.

I've just noticed there was a [last minute change](https://github.com/Tatoeba/tatoeba2/commit/b5dcd1ea9dfef3e824a17d67f3fafbdbedde1752) that apparently broke this feature. Will look into it.

**Comment by AndiPersti** [comment]
Should be fixed in https://github.com/Tatoeba/tatoeba2/commit/3c68b27a2ff283e7c8f00c740398a304c0c85d96.

**Comment by jiru** [comment]
Sorry about this! :roll_eyes:
