### ISSUE TITLE
Recently, I've been getting a lot of "An Internal Server Error Occurred" messages.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2385]
Recently, I've been getting a lot of "An Internal Server Error Occurred" messages.  (Just a one sentence message in the upper-left corner of an all white page.)

I would assume that I'm not the only one.

**Comment by ckjpn** [comment]
Today, I've had this message displayed, both as just one line on a white page and wrapped in the tatoeba html page.

<img width="403" alt="Screen Shot 2020-06-15 at 14 35 36" src="https://user-images.githubusercontent.com/7934273/84621530-c4412880-af15-11ea-946f-3f52796667c8.png">

**Comment by jiru** [comment]
What was the URL that produced the error?

**Comment by ckjpn** [comment]
The one with the tatoeba.org header was a search.

**Comment by jiru** [comment]
There can be many, many different things that produce such error. Unless you provide an exact URL of the error page, I can’t help.

**Comment by ckjpn** [comment]
My assumption is that it's actually a time-out error with the wrong error message.
Whenever it happens, all I have to do it reload the page.

**Comment by jiru** [comment]
I don’t think it’s a timeout error. A timeout error would show you the "Tatoeba is currently unavailable" page. I’m going to close this issue for now; feel free to re-open it if you can provide a URL.

**Comment by ckjpn** [comment]
Here's one URL

I got this error when posting this message to the Wall. 
 Even with the error, the Wall post completed.

https://dev.tatoeba.org/eng/wall/index#!#message_31706

<img width="685" alt="Screen Shot 2020-06-22 at 18 30 48" src="https://user-images.githubusercontent.com/7934273/85272187-cb88a900-b4b6-11ea-93c9-f0c16f079f1b.png">

**Comment by jiru** [comment]
> https://dev.tatoeba.org/eng/wall/index#!#message_31706

@ckjpn This is the URL of a message posted by me, not you. Are you sure it’s the correct URL?

**Comment by jiru** [comment]
I think you mean this one: https://dev.tatoeba.org/eng/wall/show_message/31707#message_31707

If so, I’m unable to trace back the request in the logs, because the server logs have been truncated. I think it’s because the server ran out of disk space a few days ago. The lack of disk space might be the the actual problem that caused the "internal server error".

**Comment by ckjpn** [comment]
Perhaps.
