### ISSUE TITLE
Some flags in table sentences_translations are wrong

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2387]
The bug fixed in 04c05cc7e3f81822aefd03e36a9e87b49fad2f9b resulted in some wrong values in the `sentences_translations`. Specifically, if a sentence flag was changed after creation, then, the matching fields `sentence_lang` and `translation_lang` did not change in `sentences_translations`.

It is interesting to note that the only code that depends on these fields I could find is rather recent: `src/Model/Table/ExportsTable.php`. Do we really need these fields after all?

**Comment by AndiPersti** [comment]
> It is interesting to note that the only code that depends on these fields I could find is rather recent: src/Model/Table/ExportsTable.php. Do we really need these fields after all?

They would be necessary for an efficient splitting of the links export as suggested in https://github.com/Tatoeba/tatoeba2/pull/2360.

Otherwise I'm afraid there is no scalable solution for creating all possible pairings on the prod server.

**Comment by jiru** [comment]
> Otherwise I'm afraid there is no scalable solution for creating all possible pairings on the prod server.

Right.

Also, as you mentioned in #2386, we still need to make the new design update the flag too.

**Comment by jiru** [comment]
So I fixed the bug and I wrote a command to fix incorrect languages in the links table.

I am trying to run the command on dev. It works fine, but it takes longer than expected because for some reason a lot of links have a null language there (479970 links are affected). On the other hand, on the production server, only 11407 sentences are affected at the moment so it should be quick to execute once the fix is deployed next week.

**Comment by jiru** [comment]
I executed the command on the production server. All languages in the links table should now be correct. The command took 11 minutes to execute and the output was:
```
Processing field sentence_lang...
sentence_lang: found 11444 sentence(s) having incorrect language.
sentence_lang: fixed 13433 row(s) in links table.
Processing field translation_lang...
translation_lang: found 11444 sentence(s) having incorrect language.
translation_lang: fixed 13433 row(s) in links table.
```
