### ISSUE TITLE
Allow users to jump more easily between two distant pages

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#24]
Add "-20" and "+20" to the existing targets for a long list ("<<", "<", x, x+1, ... x+5, ">", ">>").

[algoviano, Wall](http://tatoeba.org/eng/wall/show_message/17899#message_17899)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/416

**Comment by trang** [comment]
I've changed the title.

Having `-20` and `+20` would probably still not be optimal. Maybe the user only wants to jump 10 page, or maybe 100 pages away.

I suggest we implement instead the possibility for users to choose which page they want to jump to.

**Comment by billoliver** [comment]
Here it is. You guys just need to choose one:
![pagination](https://cloud.githubusercontent.com/assets/17387379/13917755/779bf98a-ef41-11e5-8640-d34d9ccc70c1.png)

**Comment by alanfgh** [comment]
Currently, we have the following:

![page_select](https://cloud.githubusercontent.com/assets/1213027/14037165/192e9a96-f217-11e5-90c7-c24e1145a5b1.png)

This lets people do the following:

(1) go to a specific page within a set of 7
(2) go forwards by one
(3) go backwards by one
(4) go forwards to the end
(5) go backwards to the beginning

Your proposals seem to decrease option (1) from a set of 7 to a set of 5. I suppose that's okay if we need the extra space. I don't know whether your "right-pointing triangle plus vertical line" maps to the existing (2) or (4), but in any case, it drops one of them. I would rather not have us drop this functionality if we don't have to.

I do like the option of a box in which you can type a number. In terms of choosing between the top set, where the right-pointing icon is outside the "Go to page x" box, or the bottom set, where it's inside, I prefer the bottom set.

**Comment by billoliver** [comment]
@alanfgh Thanks for your feedback!

> I do like the option of a box in which you can type a number.

This was Trang's idea, and I also like it a lot.

**Comment by billoliver** [comment]
Yesterday Google released the icons I was looking for. So, here they are:
![pagination](https://cloud.githubusercontent.com/assets/17387379/14042296/68b1d9bc-f257-11e5-9526-686c666c6e95.png)

**Comment by trang** [comment]
One problem I see with the last mockup is that it may not be intuitive for users that they should press enter to go to page 30. I think they will want to click on the `>|` but will then be redirected to the last page.

@billoliver, since your mockup includes redesign of the pagination elements, I'm going to create a separate issue for it. We should take care of the redesign before we take care of the "go to page".

**Comment by ckjpn** [comment]
The original idea of -20 or +20 might actually be better than inputting a specific page number.
https://github.com/Tatoeba/tatoeba2/issues/24#issue-27745191

With material often being added to tatoeba.org, things are seldom on the same page number as the last time you visited the website, so people don't really know what specific page number they are looking for.

I'm just brainstorming here, but perhaps if we are going to have  5 page numbers displayed, then -5 and +5 might be better "jumps."

Doing this would mean that they are all "buttons" and none of them would require a user to press "Enter".

**Comment by trang** [comment]
After one year reflecting upon this issue, my conclusion is that it's best to close it. I can somewhat guess the underlying problem that the original feature request tries to solve, but I prefer that we start on a fresh mind. We have to think about pagination on each page separately.

In many cases, allowing to jump to distant pages is not the most practical solution. For instance on a page where items are ordered by date, what the user might really want is to jump to the items that were from 10 days ago. But with pagination, they have to mentally calculate and guess on which page they should jump to, to find items from 10 days ago.

Also, jumping to distant pages assumes that there are many, many pages. But pagination doesn't make sense anymore when there are too many pages. Users reported that they usually don't need to navigate through more than 1000 items (cf. [Wall post](https://tatoeba.org/eng/wall/show_message/31548#message_31548)). So having hundreds of pages isn't really useful.

It's important to allow easy navigation to every piece content in a large pool of data, but pagination is not the answer. It's fine for a small pool, maybe up until 1000 items, but past that we need other tools (basically search and filters).

On a side note, I've found question on [UX stackexchange](https://ux.stackexchange.com/questions/111854/why-is-pagination-not-covered-by-material-design-specs) regarding why pagination is not mentioned in the Material Design spec. That's also something to take into account, if we ever decide to evolve our pagination component.
