### ISSUE TITLE
Baluchi (bal)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2418]
* Language name: Baluchi 
* Language info: https://en.wikipedia.org/wiki/Balochi_language
* ISO 639-3 code: BAL
* Public List: https://tatoeba.org/eng/sentences_lists/show/166707/eng
* Icon: https://junaidqadir.com/baluchi-icon/bal.svg
* Requested by: https://tatoeba.org/eng/user/profile/junaidqadir

**Comment by jiru** [comment]
Is it *Baluchi* or *Balochi*?

**Comment by sabretou** [comment]
It can be transliterated either way, and the requester requested it as "Baluchi". However, I find that it is spelled "Balochi" in most instances in English. Perhaps we should use "Balochi" instead.

**Comment by JunaidQadirB** [comment]
Since the ISO spells it as Baluchi I'd request please stick to that.

Balochi and Baluchi both are correct otherwise.

Thanks.

**Comment by jiru** [comment]
I’m reopening this because I need to fix the flag.
