### ISSUE TITLE
Horus hasn't done anything in the past 5 days.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2424]
**Title**
Horus hasn't done anything in the past 5 days.

**To Reproduce**
See Horus's comments

**Expected behavior**
*Example: The tag should be added to the sentence when I click on it.*

**Screenshots (if applicable)**

**Additional information (if relevant)**
- O.S., if possible with version *(Windows 10, iOS8.1, Linux distribution, etc.)*
- Browser, if possible with version *(Firefox 76.0.1, Safari 13.1, etc.)*
- Any other information related to your problem.

**Comment by jiru** [comment]
This issue is caused by #2401. Horus error is:
```
django.db.utils.OperationalError: (1054, "Unknown column 'ip' in 'field list'")
```
