### ISSUE TITLE
Haida (hai)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2427]
* Language name: Haida
* Language info: https://en.wikipedia.org/wiki/Haida_language
* ISO 639-3 code: HAI
* Public List: https://tatoeba.org/eng/sentences_lists/show/166718
* Icon: https://en.wikipedia.org/wiki/File:Flag_of_Haida.svg
* Requested by: https://tatoeba.org/eng/user/profile/nonong

**Comment by jiru** [comment]
We probably shouldn’t add `hai` because it’s a [macrolanguage](https://iso639-3.sil.org/code/hai). The individual codes are:
* `hdn` – Northern Haida
* `hax` – Southern Haida

@RyckRichards Can you ask nonong which variety would sentences of list 166718 be?

**Comment by RyckRichards** [comment]
@jiru Sure

**Comment by RyckRichards** [comment]
@jiru That's what I got:

"Hi, Ricardo!

I am doing all right. Thanks. I found a webpage, which explains Northern and Southern Haida dialects.

“While nearly everyone agrees that there is only a single Haida language, there are some noticeable dialectal differences between communities. In modern times, the greatest difference is between Southern Haida, as spoken in Skidegate, and Northern Haida, spoken in Masset and Hydaburg. Speakers of one dialect will often have some trouble understanding the other dialect at first, until they have had time to adjust to it.“

http://www.haidalanguage.org/

So, it means that only phrase [#8889779](https://tatoeba.org/sentences/show/8889779) is Southern Haida (at Skidegate, BC) and the rest of list 166718 are Northern Haida (in Masset, BC, and in Alaska). (Hydaburg is in Alaska.)

(I was hoping that we could keep the Haida dialects together, because in my language Tagalog tgl, we do keep the dialects together. I know two dialects of Tagalog, of Manila and of Batangas. The topic is, of course, under your team’s discretion. In John Enrico’s massive two-volume _Haida Syntax_, he deals with both dialects, as if they were really just one language.)"

**Comment by jiru** [comment]
Thanks for the info.
Sorry but the policy of Tatoeba is to stick to the standard, so you will have to open separate pull requests for Northern and Southern Haida (and create separate flags). We may be able to group them into "Haida" when we implement a solution for #1673.
