### ISSUE TITLE
Search Error when searching "any language"

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2433]
**Title**
Search Error when searching "any language"

**To Reproduce**
Search: We all knew gold was heavier than silver.

Error: to any language
https://tatoeba.org/eng/sentences/search?query=We+all+knew+gold+was+heavier+than+silver.&from=und&to=und

<img width="747" alt="Screen Shot 2020-07-06 at 17 51 23" src="https://user-images.githubusercontent.com/7934273/86575199-da408700-bfb1-11ea-8e44-bca663af49d6.png">

No Error: to English
https://tatoeba.org/eng/sentences/search?query=We+all+knew+gold+was+heavier+than+silver.&from=eng&to=und

<img width="686" alt="Screen Shot 2020-07-06 at 17 52 05" src="https://user-images.githubusercontent.com/7934273/86575245-e9273980-bfb1-11ea-8824-b520867c740b.png">

**Comment by jiru** [comment]
Thanks. That was a temporary error happening when I was adding new languages to Manticore.
