### ISSUE TITLE
JSify dynamic nocache marked parts of pages 

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#246]
This would involve:
-Adding get endpoints to provide the needed dynamic data, for example /dynamic/num_visitors/ would return a plain text response with the number of visitors
-Pulling in the data in the pages with ajax requests to these endpoints

The benefit of this is that html responses will be effectively the same for people who are logged in and those who aren't, allowing efficient caching of pages by nginx.

Elements to be jsified:
https://github.com/Tatoeba/tatoeba2/commit/b126b3c5acd8c736b1eead357fe538c8bd437f11

**Comment by trang** [comment]
I'm not sure this is still relevant... Either way, closing this.
