### ISSUE TITLE
It's not possible to change the language flag of newly added sentences using the new design

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2461]
**To Reproduce**
1. Add a new translation of an existing sentence using the new design (I experienced this with the example sentences that appear in the main page in order to show how the new design is)
2. Try to click on the flag of the language in order to change it
3. Nothing happens
4. You need to open the sentence in a new page using the old design in order to be able to change the flag of your newly added sentence

**Expected behavior**
You should be able to change the flag of the language of your new sentence without having to open it into a new page with the old design, in order to match the current behavior of the old design.

**Comment by AndiPersti** [comment]
> 2. Try to click on the flag of the language in order to change it

In the new design clicking on the flag doesn't work any more. You need to click on the pencil icon next to the sentence in order to edit it (text and/or language):
![edit_language](https://user-images.githubusercontent.com/6566321/87933237-2cdb7200-ca8d-11ea-885a-e7b38d053afe.png)

**Comment by Guybrush88** [comment]
I see, thanks @AndiPersti, I guess I wasn't really aware of that feature, sorry about that
