### ISSUE TITLE
The button to copy sentences copies also some code

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2465]
**To Reproduce**
1. Search for a word in a given language
2. Click on the button to copy the button
3. Paste it somewhere
*Example: *
*1. Search for "=olives"
*2. Go here: https://tatoeba.org/ita/sentences/search?query=%22%3Dolives%22&from=eng&to=und&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort_reverse=&page=2&sort=words
*3. Copy the sentence using the copy button
*4. Paste the sentence somewhere
*5. The pasted sentence is I like every type of `<span class="match">olives</span>.
`
**Expected behavior**
The copied sentence should be "I like every type of olives.", so the code to highlight the match of my search (`<span class="match">olives</span>`.) shouldn't appear.

**Comment by AndiPersti** [comment]
I cannot reproduce that on Linux with Firefox 78/Chromium 83.
What browser do you use?

**Comment by Guybrush88** [comment]
Latest Firefox version on Xubuntu 20.04

**Comment by trang** [comment]
The bug only happens in the old sentence design.

**Comment by jiru** [comment]
This regression was introduced by f9abc4cbb052cda51c1361bfd57ea8c3b1d353b2. Reverting commits f9abc4cbb052cda51c1361bfd57ea8c3b1d353b2 and dcdab7f041fd7369bd8244b08b50903a884ad543 solves the problem.
