### ISSUE TITLE
Audio player quit working on this page: https://tatoeba.org/eng/audio/index

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2468]
I tried this.  I also cleared my cache and tried it again.

https://tatoeba.org/eng/audio/index
<img width="705" alt="Screen Shot 2020-07-22 at 15 02 04" src="https://user-images.githubusercontent.com/7934273/88140494-d5740800-cc2c-11ea-81b9-d59f340d678a.png">

The audio player doesn't play the audio.

However, if I go to the sentence's page, it plays.

<img width="709" alt="Screen Shot 2020-07-22 at 15 02 14" src="https://user-images.githubusercontent.com/7934273/88140478-ce4cfa00-cc2c-11ea-9a8e-538b80b000a8.png">

**Comment by ckjpn** [comment]
I assume that the problem is the same for this page and once your new code is put on the site, this page will work, too.

https://tatoeba.org/eng/audio/of/lowteq

However, if that is not the case, I thought that you might like to know that this page has the same problem.

**Comment by AndiPersti** [comment]
Yes, that page uses the same broken JS file.
