### ISSUE TITLE
Add caching config to nginx

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#247]
Once  #246 is taken care of, the following pages should be cached:
-All browse pages, possibly cached for weeks except for the first page which would be cached for a day or so.
-Comment pages, cached for a few days or so except for the first page which should be cached for an hour or less or maybe not cached at all
-All contributions statistics pages should be cached for weeks or months except for the new ones, cached for days
-Language statistics page should be cached for days
-All contribute pages, FAQ, and other static pages should be cached for months
-All wall pages should be cached for a few weeks except for the first 2 pages
-The list of members pages should be cached possibly for weeks

Also a post endpoint for invalidating caches accessible only by admins should be added, for example /cache/invalidate data:$someurl

**Comment by trang** [comment]
Doesn't seem relevant anymore. Closing.
