### ISSUE TITLE
Menu items hidden behind Private Message folder

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2472]
1. Go to https://tatoeba.org/eng/private_messages/folder/Inbox
2. Click on any suspended menu 

You'll get this:

https://prnt.sc/to26uh
https://prnt.sc/to27ag

I'm experiencing this on my Google Chrome for W7.

**Comment by AndiPersti** [comment]
It looks like one of the commits of #2473 fixes this issue. I can't reproduce it anymore on that branch.

**Comment by jiru** [comment]
I confirm the problem is solved already. Thanks for reporting it anyway, Ricardo! :slightly_smiling_face:

**Comment by RyckRichards** [comment]
I still can reproduce it. Should I wait for the update?

![image](https://user-images.githubusercontent.com/7658430/88481289-d8267400-cf30-11ea-8aa3-a6b471e6165f.png)

**Comment by jiru** [comment]
Yes please. :smile:

**Comment by jiru** [comment]
It turned out this is still a problem after updating. :confused:
