### ISSUE TITLE
Problem with the Blue Alert Message to accept the new Terms of Use

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2474]
Here is a screenshot with the current version of SeaMonkey.
Perhaps this affects other web browsers, too.

<img width="889" alt="Screen Shot 2020-07-25 at 18 17 34" src="https://user-images.githubusercontent.com/7934273/88453590-62c09200-cea3-11ea-8ace-c0f76f701e00.png">

**Comment by ckjpn** [comment]
It looks this way on Safari, too.

**Comment by AndiPersti** [comment]
The problem is independent of the browser and only affects the announcement for the new Terms of Use. It is caused by the removal of the CSS rule for the close button in 7d752b4.

@trang Do you want to redesign this announcement too or should we just re-add the CSS rule?

**Comment by trang** [comment]
Should be redesigned. I'll take care of it. I completely forgot about it when I redesigned/migrated the other announcement boxes.
