### ISSUE TITLE
Audio player quit working on this page: https://tatoeba.org/eng/sentences/add

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2476]
** Problem **

When contributing a sentence that already exists that also has audio, we used to be able to click the audio player button to listen to the audio file.

You can test is with this sentence.
Tell me a little more about that.

https://tatoeba.org/eng/sentences/add
<img width="748" alt="Screen Shot 2020-07-27 at 14 50 29" src="https://user-images.githubusercontent.com/7934273/88508222-37f84a00-d019-11ea-94ec-59f5c0d13dff.png">

** Likely Related **

https://github.com/Tatoeba/tatoeba2/issues/2468

**Comment by jiru** [comment]
Commit 1df8c35c61a42757abfdc80cee92c1d7e1cf8f7f is causing this bug.

**Comment by jiru** [comment]
This issue reminds me of #2465.
We do want to get rid of jquery, however the old design is entirely tied to it. Is it worth trying to rewrite the Javascript implementation of the old design now, giving that we have plans to remove the old design entirely at some point?

**Comment by AndiPersti** [comment]
I've just proposed a fix which requires only minimal pure Javascript code in order to play audio everywhere in the old design.

But I've also thought about simply adding the old `sentences.play_audio.js` to `sentences-block-for-members.js` as you've done for the copy button.
