### ISSUE TITLE
On dev branch, sentence delete button gives column 'ip' not found error

### ISSUE THREAD

**Issue by jpear1** [Tatoeba/tatoeba2#2480]
**Title**
On dev branch, sentence delete button gives column 'ip' not found error

**To Reproduce**
1. Log in as contributor
2. Click on the sentence info button next to the Japanese sentence under "Latest Contributions"
3. Above the sentence, click the "delete" button
4. Click ok
5. Observe `Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ip' in 'NEW'`

**Additional information**
This happens on my local version of the dev branch. I can't find the live test server, so I can't verify that this isn't a problem with my machine.

However, I'm almost positive this was caused by #2401.

**Comment by jpear1** [comment]
I'll start working on this and open a PR when I figure it out (I caused the problem in the first place), I just wanted to log this before #2401 got merged into master.

**Comment by AndiPersti** [comment]
Our test server is https://dev.tatoeba.org.

Did you run the migration on your local machine? What's the output of `bin/cake migrations status`?
See the docs for [information about the available commands](https://book.cakephp.org/migrations/2/en/index.html#the-commands).

**Comment by jpear1** [comment]
I got a fresh install, with the migration down. I was able to add and delete a sentence.

Then I ran `bin/cake migrations migrate`, and was unable to even add a sentence. The button did nothing except start a loading animation under "Sentences Added".

**Comment by jiru** [comment]
@jpear1: this happens when the ajax query fails. Inspect the query with the network tool to see what it says.

Also try removing the cached models: `rm tmp/cache/models/myapp_cake_model_default_*`

**Comment by AndiPersti** [comment]
>     5. Observe `Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ip' in 'NEW'`

I've just installed a fresh imouto instance myself and remember now what the problem is: After merging your PR gillux also had to update a database trigger which used the `ip` column (see 5491fb88c3dff2f37870f2c3380577a4c9823024). Since the current VM version is older than this change you need to update that trigger manually:
`mariadb tatoeba < /home/vagrant/Tatoeba/docs/database/triggers/last_contributions_triggers.sql`.

**Comment by jpear1** [comment]
Yup, this seems to have fixed it. Thanks!

**Comment by jiru** [comment]
Okay I’m going to release a new version of the VM…
