### ISSUE TITLE
Difficult to find long sentences using advanced search

### ISSUE THREAD

**Issue by jpear1** [Tatoeba/tatoeba2#2484]
**Story**
I encountered a new word in Japanese that had a lot of different meanings and I was having a hard time understanding all of them from just the dictionary definitions. The word is また and from an example in the dictionary, it seemed like one usage was very similar to the English "and", as a word that appears before the last element in a list. However, I wanted to know if it was grammatical to place it between elements in a list, as と would be used. So, I searched for "また". I found plenty of sentences containing また, but they were all very short. Since the usage I was looking for would only appear in fairly long sentences, I needed to navigate to page 30 or so to get sentences that were long enough to get to sentences where I might encounter this usage.

**Idea**
I'd like the ability to filter by sentence length under advanced search. So there would be one extra row under "Sentences" labelled "Has length between X and Y characters".

**Title**
Difficult to find long sentences using advanced search

**Comment by jiru** [comment]
Duplicate/related: #1954.
