### ISSUE TITLE
"Show translations" button is not working

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2488]
1. Go to https://tatoeba.org/eng/sentences_lists/show/3547
2. On "Show translations", choose any language like Portuguese (por)
3. Translations are not displayed

**Expected behavior**
Display translations in Portuguese

**Additional information (if relevant)**
If I add "/por" in https://tatoeba.org/eng/sentences_lists/show/3547 manually, it displays the translations in Portuguese.

https://tatoeba.org/eng/sentences_lists/show/3547/por

**Comment by AndiPersti** [comment]
Thanks for the report.

Fixed in b9e7fbcf0c35f0dcac97a92f69b161001726b5ec and will work again after the next update.
