### ISSUE TITLE
Lists that could likely be deleted

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2490]
** How did you came up with that idea? What made you think about it? **

I sorted all of last week's exported list names by length.
These are the longest, apparently Chinese list names, similar to a past "spammer."
I know that a number of lists by this spammer have already been deleted, but there are some more.

Here are a couple of lines, so you can see what's in the file. (Total 99 lines)
ID + owner + list name + "creator"

10009	sdfgsd87	槐腾陈褪惫烁浇父招嚷每旱诶涨丛统瞪坛植独啃刹埠葱磕歉话系桓傅裙崭赶夜品匝促毫卵滩节侵痹岳徽纺源泄收纸	creator
164843	zrz270303	银猪登录开户【Q溦:632144】_mk确戎腹靥姓奖掣喝晌骋攀簧墩移偌找虾丈庞美附崭氏钦得琅撇母靥静苑砍脊崭恐骋苑驴止迅谐却庞盐咸反匀涌囊谖..wfgz	creator

[Lists-that-could-likely-be-deleted.zip](https://github.com/Tatoeba/tatoeba2/files/5026167/Lists-that-could-likely-be-deleted.zip)

**Comment by AndiPersti** [comment]
> I know that a number of lists by this spammer have already been deleted, but there are some more.

Well, you only see the lists that get exported, but there are a lot more still in the database:
```
MariaDB [tatoeba]> select count(*) from sentences_lists where created > '2020-04-01' and visibility = 'private';
+----------+
| count(*) |
+----------+
|   158214 |
+----------+
1 row in set (0.115 sec)
```
(This is just a rough estimation because not all of these were created by the spammer, but I'm pretty sure only a handful of them are false positives.)

@trang @jiru Do we still want to keep them?

**Comment by trang** [comment]
No, we don't want to keep them. If the spammers have indeed stopped, it's safe to delete now. We were keeping them mostly so that they don't notice that we have put measures to mitigate their spam and don't go spam elsewhere on the website.

**Comment by AndiPersti** [comment]
I've cleaned up the `sentences_lists` table:

Before:
```
MariaDB [tatoeba]> select count(*) from sentences_lists;
+----------+
| count(*) |
+----------+
|   164523 |
+----------+
1 row in set (0.061 sec)
```

After:
```
MariaDB [tatoeba]> select count(*) from sentences_lists;
+----------+
| count(*) |
+----------+
|     6232 |
+----------+
1 row in set (0.004 sec)
```
