### ISSUE TITLE
On Android, the "X" that clears the search string for the right-hand advanced search causes the focus to be lost

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2499]
**To Reproduce**
1. Do an advanced search.
2. On the right-hand side of the screen, press "X". The contents of the search string will be cleared, which is fine, but the focus is not put into the field that was just cleared. This forces the user to reposition the cursor in the field.

**Expected behavior**
The "X" should clear the field but leave the focus in it so that you can immediately type a new search string. This is the way that the "X" in the regular search field works, either on Firefox+Windows, or on Chrome+Android. It's also the way that the "X" in the right-hand search field works on Firefox+Windows.

**Comment by AndiPersti** [comment]
@alanfgh Can you still reproduce this? If yes, what browser do you use on Android?

We've updated the UI framework in the meantime and I can't reproduce this anymore with the stock Android browser (6.0.1) and Firefox Preview (4.2.1).

**Comment by alanfgh** [comment]
@AndiPersti , no, I can't reproduce it now.
