### ISSUE TITLE
Some pages look ugly on mobile

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2504]
I noticed some pages wrap text or icons uglily on mobile. I assume a similar fix is required so I’m grouping them in a single issue.

* [Private message inbox](https://dev.tatoeba.org/fra/private_messages/folder/Inbox) (totally unusable since the list of messages can’t be seen):
  ![inbox](https://user-images.githubusercontent.com/5107734/89737325-5e35d500-da70-11ea-95cd-256721487ad4.png)

* [Advanced search](https://dev.tatoeba.org/fra/sentences/advanced_search) (field labels read vertically):
![Advanced search](https://user-images.githubusercontent.com/5107734/89737352-81608480-da70-11ea-9704-9553c3b1c58f.png)

* [User profile](https://dev.tatoeba.org/fra/user/profile/gillux) (the "member since" date reads vertically):
![profile](https://user-images.githubusercontent.com/5107734/89737381-c8e71080-da70-11ea-97a2-80f268fd71e4.png)

* [List of revisions](https://dev.tatoeba.org/fra/reviews/of/gillux) (the red icon is pushed down):
![revisions](https://user-images.githubusercontent.com/5107734/89737397-efa54700-da70-11ea-813e-6a36792263f5.png)

* [Sentence page](https://dev.tatoeba.org/fra/sentences/show/4148911):
![sentence page](https://user-images.githubusercontent.com/5107734/89737429-414dd180-da71-11ea-8ede-65a531246cf4.png)

* [Show all in](https://dev.tatoeba.org/fra/sentences/show_all_in/fra/none)
* Probably many more...

**Comment by trang** [comment]
If you confirm that having `<meta name="viewport" content="width=970">` renders the page as if it was a scaled-down version of the desktop (cf. https://github.com/Tatoeba/tatoeba2/pull/2473#issuecomment-671388501), then this will be fixed after merging #2473, where I will push a commit to force the viewport width.

**Comment by jiru** [comment]
Closing because I was using an outdated/buggy browser and I can’t reproduce it with a recent browser.
