### ISSUE TITLE
Lushootseed (lut)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2527]
* Language name: Lushootseed 
* Language info: https://en.wikipedia.org/wiki/Lushootseed
* ISO 639-3 code: LUT
* Public List: https://tatoeba.org/eng/sentences_lists/show/168659
* Icon: https://imgur.com/a/PWiZ0o4
* Requested by: https://tatoeba.org/eng/user/profile/EricYarnell

**Comment by jiru** [comment]
@RyckRichards A lot of sentences from the list are incorrectly flagged. Could you change these flags to "unknown"?

**Comment by RyckRichards** [comment]
Sure!
