### ISSUE TITLE
Kurdish (Kurmanji) (kmr)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2529]
* Language name:  Kurdish (Kurmanji) 
* Language info: https://en.wikipedia.org/wiki/Kurmanji
* ISO 639-3 code: KMR
* Public List: https://tatoeba.org/eng/sentences_lists/show/168672
* Icon: https://imgur.com/a/aYPRlaz
* Requested by: https://tatoeba.org/eng/user/profile/Sarchia

Note: We're checking which members have posted sentences in this language.

**Comment by RyckRichards** [comment]
Users who posted sentences in Kurdish (Kurmanji):

Bikarhener
ajje
Adelpa
juanitux.

**Comment by trang** [comment]
@sabretou, @RyckRichards,

For the name here, why did we choose `Kurdish (Kurmanji)` instead of just `Kurmanji`? Also, on the SIL website, the name is `Northern Kurdish` (https://iso639-3.sil.org/code/kmr). If we go for a different name than what has been defined in the ISO 639-3, I'd just like to keep a trace of why :)

**Comment by sabretou** [comment]
@trang The names were based on suggestion by the contributor who requested the language be split into 3. They mentioned the languages as: Kurdish (Kurmanji), Kurdish (Sorani), and Kurdish (Xwarin).

It is possible that these endonyms may be more familiar to Kurdish speakers than the more academic names used by ISO.

**Comment by trang** [comment]
@sabretou To be more accurate, we could use the academic name outside of the parenthesis:
- Northern Kurdish (Kurmanji)
- Central Kurdish (Sorani)
- Southern Kurdish (Xwarin)

Or the reverse:
- Kurmanji (Northern Kurdish)
- Sorani (Central Kurdish)
- Xwarin (Southern Kurdish)

What do you think?

**Comment by sabretou** [comment]
@trang The first set of names sounds good to me, i.e. "Northern Kurdish (Kurmanji)" and so on. This way, we will use the academic name first, which will also include the "Kurdish" designation.
