### ISSUE TITLE
Some translations are wrongly licensed as CC0

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2533]
**To Reproduce**

A user who recently got granted the permissions to use the license CC0 reported that their translations were set with the license CC0.

Example: https://tatoeba.org/eng/sentences/show/9004276

I haven't checked the exact steps to reproduce but I suspect this is happening only with the new sentence design.

**Expected behavior**

In principle, a translation of a CC BY sentence should not be licensed as CC0. But also, we have not yet enabled CC0 on translations so every translation should be created under CC BY.

**Additional information (if relevant)**

Related bug: #2322.

It seems we have 5700+ translations that shouldn't be CC0.
```
MariaDB [tatoeba]> select count(*) from sentences where license = 'CC0 1.0' and based_on_id > 0;
+----------+
| count(*) |
+----------+
|     5705 |
+----------+
1 row in set (6.065 sec)
```

**Comment by AndiPersti** [comment]
> I haven't checked the exact steps to reproduce but I suspect this is happening only with the new sentence design.

The bug is independent of the design but is caused by c5191c87e124079dfb3b27fe2989029ba27c3f72.

**Comment by jiru** [comment]
@AndiPersti Thanks for taking care of this issue. :+1:

What are we going to do with the logs of CC0 translations? Rewrite "licence" entry or add a "licence change" entry?

**Comment by AndiPersti** [comment]
I thought we would run the `edit_licenses` command on these sentences which would generate a license change entry in the logs.

In general, I think rewriting the logs is not a good idea because we loose information which could be helpful in the future as I have just noticed today while looking at another problem.

**Comment by AndiPersti** [comment]
JFYI: I've just fixed the licenses in the database.
