### ISSUE TITLE
Reclassify Kurdish sentences into Xwarîn, Kurmanji and Sorani

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2540]
I am creating this issue to gather information that is currently spread on several tickets. @soliloquist-tatoeba @RyckRichards @sabretou Feel free to join the discussion.

### Story

We have 1500+ sentences in Kurdish language (kur), but this is a [macro-language](https://iso639-3.sil.org/code/kur). We are introducing individual language codes for Kurdish variants Xwarîn (#2530), Kurmanji (#2529) and Sorani (#2528).

### Questions

1. Are we going to remove Kurdish (kur) at the same time we introduce the 3 variants, or should we have a kind of transition period to allow manual adjustments? **No.**
2. What about [users having Kurdish (kur) listed as a user language](https://tatoeba.org/eng/users/for_language/kur)? There are 66 of them at the moment (including 5 unlisted spam accounts). Only 4 of them specified the variant in the "details" user language field. **Send PM to invite them to change their user language.** Who the PM will come from? What are the contents of the message?
3. Are Kurdish contributors aware and okay with the fact that #1673 is yet to be solved? **Yes.**

#### Sorani

All Kurdish sentences in Arabic script are in Sorani: [complete list](https://github.com/Tatoeba/tatoeba2/issues/2528#issuecomment-683451808).

#### Kurmanji

Supposedly everything else.

#### Xwarîn

Supposedly none.

**Comment by soliloquist-tatoeba** [comment]
> Are we going to remove Kurdish (kur) at the same time we introduce the 3 variants, or should we have a kind of transition period to allow manual adjustments?

 My first recommendation was to keep KUR as is for the time being and to introduce the sublanguages as quickly as possible, but since we are almost sure which sentences are in which language now, I'm in favor of transferring them.

> What about users having Kurdish (kur) listed as a user language? There are 66 of them at the moment (including 5 unlisted spam accounts). Only 4 of them specified the variant in the "details" user language field.

I think we can send PMs to them and tell the news, so they can update their profiles.

> Are Kurdish contributors aware and okay with the fact that #1673 is yet to be solved?

I guess we don't have any Kurdish contributors insisting that we merge all varieties in a single section as in the case of Berber. We also keep using 'Kurdish' in the name of sublanguages so I don't think they would oppose it.

**Comment by sabretou** [comment]
I agree with everything @soliloquist-tatoeba has said above. I'm in favour of transferring sentences to individual languages and phasing out the macrolanguage code.

**Comment by jiru** [comment]
@sabretou By "phasing out", you are saying that you’d rather have a transition period with both the macrolanguage and individual languages. Is that correct? Could you elaborate on that?

**Comment by sabretou** [comment]
@jiru Apologies, I used the wrong phrase. I only meant deprecating 'KUR' after we have assigned all of its sentences to the individual language codes.

**Comment by alanfgh** [comment]
Could someone please change "reaffect" in the title of this issue to "reclassify"?

**Comment by AndiPersti** [comment]
> Are we going to remove Kurdish (kur) at the same time we introduce the 3 variants, or should we have a kind of transition period to allow manual adjustments? **No.**

I understand this as 'we are going to remove Kurdish at the same time we introduce the 3 variants.' Is this correct?

> I think we can send PMs to them and tell the news, so they can update their profiles.

Has anybody already sent the PMs?
What about contributors who don't answer? Should we remove Kurdish from their profile?

**Comment by trang** [comment]
> > Are we going to remove Kurdish (kur) at the same time we introduce the 3 variants, or should we have a kind of transition period to allow manual adjustments? **No.**
> 
> I understand this as 'we are going to remove Kurdish at the same time we introduce the 3 variants.' Is this correct?

Whichever this means, I think it is better to keep Kurdish (kur) and have some kind of transition period. 

We don't have yet a clear answer on what to do with users who didn't contribute anything but have listed Kurdish in their profile or settings. We could of course just remove it from their profile/settings then let them figure out that they have to re-add the proper language. At first, I felt that would be okay to do but on second thoughts, that might not be the best user experience. There's a risk that some users misinterpret it as Kurdish being no longer supported in Tatoeba.

By keeping Kurdish, there is a risk that new sentences keep being added in this macrolanguage and that makes it slower to effectively remove it, but I think that is less critical than the bad user experience of removing Kurdish without an appropriate process. We can for now manually contact the contributors to explain that they should use Xwarîn, Kurmanji or Sorani instead, or they should request a new language.

For the longer term, we will have to deal with [several other languages that are in a similar situation as Kurdish](https://en.wiki.tatoeba.org/articles/show/tatoeba-supported-languages-exceptions). We'll need proper features to handle changes in the classification of the languages:
- preventing users from adding a certain language in their profile
- preventing users from adding new sentences in a certain language
- displaying some warning on the homepage (or wherever relevant) in case a user has a language that we will remove
- providing a way for users to easily migrate their sentences from a language to another
- etc.

**Comment by soliloquist-tatoeba** [comment]
> We don't have yet a clear answer on what to do with users who didn't contribute anything but have listed Kurdish in their profile or settings. We could of course just remove it from their profile/settings then let them figure out that they have to re-add the proper language. At first, I felt that would be okay to do but on second thoughts, that might not be the best user experience. There's a risk that some users misinterpret it as Kurdish being no longer supported in Tatoeba.


This seems to me a bit problematic approach.

If you don't send PMs to the users who listed Kurdish (or another macrolanguage) in their profiles about the process of introducing sublanguages, they may likely continue to use the macrolanguage thinking that it's the only option, which is inefficiency. And if you do send messages and inform them about the situation, then there is not much point worrying about misinterpretation or the best user experience. Communication is the key.

**Comment by AndiPersti** [comment]
I agree with @soliloquist-tatoeba.
Sending PMs to all users with Kurdish telling them that they should change their profile language should be enough for avoiding any misinterpretation.

So how about the following procedure:
- Add the three Kurdish variants.
- Give the language team some time (2 or 3 weeks) to move all Kurdish sentences to the correct variant and send out PMs to the contributors.
- After that period remove Kurdish from the language list and from all user profiles where it is still set.

In the last three months, there were only 3 users who added/edited Kurdish sentences, so it's very unlikely that people will still create sentences in the macrolanguage after we've told them about the change.

From the 68 current contributors who have set Kurdish in their profile, 5 are suspended (marked as `Spammer`) and 45 didn't log in since 2019-01-01 (i.e. since almost 2 years; 31 of them just created an acoount but never logged in again). So it is also very unlikely that everyone will update their profile and IMHO there's no problem removing Kurdish from these non-active members.

**Comment by trang** [comment]
> So how about the following procedure:
> 
> * Add the three Kurdish variants.
> * Give the language team some time (2 or 3 weeks) to move all Kurdish sentences to the correct variant and send out PMs to the contributors.
> * After that period remove Kurdish from the language list and from all user profiles where it is still set.

Sounds good to me.

**Comment by AndiPersti** [comment]
I've just added the three Kurdish variants on the production server.

@soliloquist-tatoeba @RyckRichards @sabretou Please tell us when you think it's ok to remove Kurdish.

**Comment by soliloquist-tatoeba** [comment]
Thank you. I sent PMs to all users on [this ](https://tatoeba.org/eng/users/for_language/kur)page.

1- You could remove the qualifier from Southern Kurdish. The name of Xwarîn seems to be unknown to even some Kurds. Southern Kurdish probably doesn't have a standardized name.  Perhaps it would be better to drop it to avoid confusion.

2- All Kurdish (KUR) sentences could be moved to Northern Kurdish (KMR). I've already moved the others. The rest are all in Northern Kurdish.

3- The writing direction of Central and Southern Kurdish should be RTL. Please see [this](https://tatoeba.org/eng/sentences/show/8996029) example.

The Kurdish sentences aren't displayed correctly. They should be right-aligned like the indirectly-linked Persian sentence.

**Comment by trang** [comment]
Thank you @soliloquist-tatoeba :)

Could you create a new issue to list the adjustments we should make on the Kurdish languages (name, flag, direction...)? This will help @RyckRichards to know more precisely what to do in his next pull request. You can create it as "Language request" so that the ticket is automatically assigned to him.

**Comment by AndiPersti** [comment]
I've updated all user profiles (either changed Kurdish to one of the variants if I found any clues (owned sentences, language details) what variant the user prefers or deleted Kurdish from a user's language list) and removed Kurdish from the code (in 936345f3289f05f0e1917e2db151a9648be962fb) and the database.
