### ISSUE TITLE
couldn't send a private message to an existing user

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2545]
When I tried to send a private message to the user morbroper, the "To" field of the message was erased and a banner was displayed saying "The user morbroper to whom you want to send this message does not exist. Please try with another username." But in fact he does exist, as you can see from his [profile](https://tatoeba.org/eng/user/profile/morbrorper).

**To Reproduce**
Try to send a message to morbroper.

**Screenshots**
About to send message:

![pm_msg](https://user-images.githubusercontent.com/1213027/92327515-3498ab00-f028-11ea-8e1f-9f27371005af.png)

After pressing "Send":

![pm_err_banner](https://user-images.githubusercontent.com/1213027/92327519-3c584f80-f028-11ea-8b82-9c5c43f5309a.png)

**Additional information (if relevant)**
Using Firefox on Windows.

**Comment by AndiPersti** [comment]
> a banner was displayed saying "The user morbroper to whom you want to send this message does not exist. Please try with another username." But in fact he does exist,

The error message seems to be correct because there really is no user `morbroper`. The correct username would be `morbrorper` (with `r` before `p`).

**Comment by alanfgh** [comment]
Oops. You're right.
