### ISSUE TITLE
The advanced search with many results shows only the first ten results

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2547]
**To Reproduce**
1. Go to the advanced search page
2. Select an user with many sentences, choosing also the language (any other search option isn't relevant, the bug appears with any option)
3. Try to change the page to see different results
*Example: *
*1. Go here: https://tatoeba.org/ita/sentences/advanced_search
*2. Choose Italian as the language of sentence and put Guybrush88 as the owner of the sentences
*3. Perform the search
*4. After seeing the results in the first page, go to page 2
*5 Results don't appear, it seems that they can't be found, according to the message that is shown

**Expected behavior**
Results should appear in all the pages, if they are more than 10 (the maximum number of sentences that can be shown in a single page)

**Additional information (if relevant)**
- Xubuntu 20.04
- Firefox 80.0.1

**Comment by jiru** [comment]
I was about to push a fix but somebody outstripped me :laughing:

**Comment by AndiPersti** [comment]
I hope you are ok with it.

**Comment by jiru** [comment]
Yeah it’s okay! I came up with a very similar fix. Feel free to push yours on production.
