### ISSUE TITLE
Server responds surprisingly slowly to requests for files in cache_js

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2550]
Looking at the network tab in Firefox DevTools, I noticed that a few requests were marked with a little turtle representing a slow server response:
![Request timings](https://user-images.githubusercontent.com/6555947/92524711-d84dab00-f222-11ea-89c4-fde9bf119bd1.png)
This does not appear to be related to file size: the outlier here is `sentence-components.js`, which took 3 seconds to load despite compressing down to 7.3 KB. The bar in the timeline is almost entirely gray, which indicates the time Firefox spent waiting for the first byte of the response after issuing the request. The same is the case for the other two slow requests.

What those files have in common is that they're under `webroot/cache_js/`. The JS files under `webroot/js/` loaded faster. That makes me suspect something about the cache is misconfigured.

Another curiosity: the three requests above complete roughly 1 second after each other. If I use `curl` to perform multiple requests for the same file:
```bash
$ time curl -s $(for i in $(seq 10); do echo -o /dev/null 'https://tatoeba.org/cache_js/sentence-component.js'; done) -w 'time_starttransfer: %{time_starttransfer}\n'
time_starttransfer: 0.150091
time_starttransfer: 1.012927
time_starttransfer: 0.968878
time_starttransfer: 1.048833
time_starttransfer: 0.962216
time_starttransfer: 0.987174
time_starttransfer: 0.975991
time_starttransfer: 1.027431
time_starttransfer: 0.975237
time_starttransfer: 0.993909

real	0m9.222s
user	0m0.086s
sys	0m0.038s
```
All but the first request start after about 1 second delay, so `n` requests take roughly `n-1` seconds. Is there some kind of rate limiting?

**Comment by jiru** [comment]
I investigated and I found out that it happens because of our nginx configuration. It’s because the request is passed down to php-fpm instead of being handled directly by nginx.

**Comment by jiru** [comment]
I updated dev and prod’s nginx configuration, it should be much faster now.

**Comment by Yorwba** [comment]
Thanks! It's now so fast that I even had some trouble finding the `layout.js` request at first because the timing bar was so much shorter.
