### ISSUE TITLE
Internal error after saving settings

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2554]
**To Reproduce**
1. Go to the settings page
2. Click on the first save button
3. Below the confirmation message that the settings were saved, the error message "An Internal Error Has Occurred" is displayed.
4. Reload the settings page.
5. Same error message.
6. Log out and back in again.
7. Visit the settings page again.
8. Error disappeared.

By the way, wasn't there supposed to be a request-specific code on the error page to help with debugging? I didn't see anything like that.

**Comment by AndiPersti** [comment]
> By the way, wasn't there supposed to be a request-specific code on the error page to help with debugging? I didn't see anything like that.

The error code is currently only implemented for search errors.

**Comment by AndiPersti** [comment]
This is fixed by 94eff01168aedb5315290b8d0323213cc6eaa62c.
