### ISSUE TITLE
Nuer (nus)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2556]
* Language name: Nuer
* Language info: https://en.wikipedia.org/wiki/Nuer_language
* ISO 639-3 code: NUS
* Public List: https://tatoeba.org/eng/sentences_lists/show/168734/
* Icon: https://imgur.com/a/LwDjwfn
* Requested by: https://tatoeba.org/eng/user/profile/Tango

**Comment by AndiPersti** [comment]
The list contains English sentences that should be removed before adding the language, shouldn't they?
