### ISSUE TITLE
Random sentence page forgets language

### ISSUE THREAD

**Issue by Xonok** [Tatoeba/tatoeba2#2557]
I didn't have this issue until today. I've used the site without any problems just a couple days ago.
After pressing the Random button a few times, the site forgets the random language I've set, giving a sentence from any language rather than the one I've set.

**To Reproduce**
1. Go to 'Browse->Show Random Sentence'
2. Pick a language from the dropdown next to the "Next >" button.
3. Click "Random" a few times.
4. The language in the dropdown has reset to "Any language".

**Expected behavior**
As it was a couple days ago, the language in the dropdown should remain what I've set it.

**Screenshots**
![2020-09-21 16_20_37-Я сделаю это один  - Russian example sentence - Tatoeba](https://user-images.githubusercontent.com/5237777/93772554-a0356780-fc27-11ea-8848-cb51abc41a3b.png)
![2020-09-21 16_21_52-Ich bin eine Professorin  - German example sentence - Tatoeba](https://user-images.githubusercontent.com/5237777/93772575-a62b4880-fc27-11ea-9dee-7a39fbc68c87.png)

**Additional information**
- O.S.: *Windows 10*
- Browser: Firefox 80.0.1
- I have plugins that might interfere with the site working normally, such as Cookie Autodelete. I've had them before with no issues, and disabling them doesn't seem to help.

**Comment by Yorwba** [comment]
@Xonok Thank you for the bug report! I recently changed the language selector dropdown to support autocomplete, which indirectly caused this bug. Sorry about that.
