### ISSUE TITLE
Some sentences have the string '\N' in the language field

### ISSUE THREAD

**Issue by fdietze** [Tatoeba/tatoeba2#2578]
I'm not sure this is the right place to report, but here it goes:

In the data dump, some sentences have the string '\N' in the language field. What does that mean?

Command to find these sentences:
```bash
tar xOjf sentences.tar.bz2 sentences.csv | grep '\\N'
```

```
5716114	\N	Äänilani
6473120	\N	Sābuku mamayamin, niyaꞋ takiteku manaꞋul maglayangan langkew diyataꞋ mahawan. Takaleku suwalanen pales, paꞋinne, “Allo! Allo! Asal makatalew-talew teꞋed balaꞋ matekka si kēmon meꞋ aꞋa si dunyahin bang ne tihup tellu malaꞋikat dambulihin meꞋ kuweꞋ tabuliꞋ pinangurung si siyehin.”
6481359	\N	Kataau kano koson i Ama' min pana mataau!
7003313	\N	Mini estu.
7003316	\N	Cumu ti chlamã?
7003320	\N	Bunã dimineatsa!
7003322	\N	Tini esht Maria.
7003324	\N	Bunã dzua!
7003335	\N	Abetseda-armãneascã ari 33 di literi.
7003339	\N	Maria easti cu masã.
7003341	\N	Ata a mia.
7003344	\N	Tati a mel.
7003347	\N	Tom s-agiocã cu topu.
7003353	\N	Voi hits ficior.
[...]
```

**Comment by AndiPersti** [comment]
> In the data dump, some sentences have the string '\N' in the language field. What does that mean?

It means that the language of the sentence is unknown. (`\N` stands for SQL `NULL`)

**Comment by fdietze** [comment]
Alright, thanks for the clarification. Just curious, what is the use of a sentence without knowing the language?

**Comment by AndiPersti** [comment]
> Just curious, what is the use of a sentence without knowing the language?

One reason is that the language isn't yet supported by Tatoeba.

Another reason could be that someone added a new sentence but has chosen the wrong language. Later someone else noticed the mistake but didn't know the correct language and set it to `unknown`.

**Comment by fdietze** [comment]
I understand. Thank you for the answer!
