### ISSUE TITLE
links.csv does not contain all backlinks

### ISSUE THREAD

**Issue by fdietze** [Tatoeba/tatoeba2#2579]
On the download page, the link description states:
> Contains the links between the sentences. 1 [tab] 77 means that 
> sentence #77 is the translation of sentence #1. The reciprocal link is
> also present, so the file will also contain a line that says 77 [tab] 1.

So I double checked und found that not all backlinks seem to be present:

```bash
comm -23 <(tar xOjf links.tar.bz2 links.csv | awk '{print $1, $2}' | sort) <(tar xOjf links.tar.bz2 links.csv | awk '{print $2, $1}' | sort)
```

The command runs for about 2min and then gives this. Wich are the links where no backlink is present.

```
1918220 1918219
1918236 1918235
1943238 3752771
1943243 3075927
1943259 3942190
1943259 3942318
1943259 3942320
1943259 3942329
1943259 3942351
247164 5078553
3214227 1423834
5094901 3778082
5868889 5850721
7207453 5755767
7207455 5755769
```

**Comment by AndiPersti** [comment]
Thanks for your report.

I've fixed the links table (and the logs where it was necessary) and the next export should be ok:
```sql
MariaDB [tatoeba]> select sentence_id, translation_id from sentences_translations where (translation_id, sentence_id) not in (select sentence_id, translation_id from sentences_translations);
Empty set (2 min 11.506 sec)
```
