### ISSUE TITLE
Tags with non-ASCII characters are displayed incorrectly on VM

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#258]
On the tags/view_all page, tags such as these are displayed incorrectly on the VM:

- "by Jean de La Bruyère"
- "by Comtesse de Ségur"

They look the way that UTF-8-encoded text is displayed on an ISO 8859-1-encoded page. However, when I inspect the head element for the page, it says that the charset is utf-8. Clicking on one of the tags also causes it to be displayed incorrectly in the heading at the top of the page that is displayed. Perhaps the tags are internally encoded incorrectly and we would need to correct for that if we were to display them correctly. 

The tags are displayed correctly on the main site.

**Comment by jiru** [comment]
Closing this since it doesn’t happen in VM built with imouto.
