### ISSUE TITLE
It's difficult for admins to handle large amounts of undesirable sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2586]
**Story**

When a contributor creates many undesirable sentences, admins have the possibility to block the contributor from adding more sentences. If the contributor had added a dozen of such sentences, these sentences can be handled manually (either marking them as unreliable, or deleting them, or fixing them if that's possible). However, there has been several occasions where admins blocked accounts with hundreds of undesirable sentences.

A recent case was with these accounts:
- https://tatoeba.org/deu/user/profile/Tagawawt
- https://tatoeba.org/deu/user/profile/Tilelli
- https://tatoeba.org/deu/user/profile/Tamazight

In such cases, someone who has access to the database has to make an intervention to handle because there is no possibility from the UI to delete all sentences from a given user, or mark all the sentences of a given user as unreliable. It would not be fun for admins to handle them one by one from the UI.

I'm most of the time that "someone" and as far as I'm concerned, I've always mark the sentences rather than deleting them.

```
UPDATE sentences SET correctness = -1 WHERE user_id IN (...);
```

I prefer not to delete because I don't want to take the risk of making of a mistake and deleting the wrong sentences. It wouldn't be easy to revert if that happened. Also, the sentences are often not all bad to the point where they must all be deleted. It is quite a burden to be the one who choses to delete a large amount of sentences, even more when it comes to deleting sentences in a language I don't understand.

**Idea**

As a minimum, we could add a button "Mark as unreliable" on the sentences page of each user. This button would mark all the sentences of the given user as unreliable. It would be available only to admins, and only for accounts that are blocked or suspended.

**Comment by HelioStrike** [comment]
@trang Hello! If the issue isn't already being worked on, I'd like to take it up.

**Comment by AndiPersti** [comment]
@HelioStrike Welcome and thank you for working on that issue.

If you have any questions, just ask.
