### ISSUE TITLE
Links to comments should be the same, shouldn't they?

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2593]
https://tatoeba.org/eng/sentences/show/2239900#comment-1228357

Shouldn't both of these go to the same link.

### On "Comments on CK's sentences." https://tatoeba.org/eng/sentence_comments/on_sentences_of_user/CK

<img width="736" alt="Screen Shot 2020-12-15 at 10 22 41" src="https://user-images.githubusercontent.com/7934273/102156056-14e30f80-3ec0-11eb-9661-36cc592f246b.png">
https://tatoeba.org/eng/sentences/show/2239900#comment-1228357

### On the sentence's page. https://tatoeba.org/eng/sentences/show/2239900

<img width="718" alt="Screen Shot 2020-12-15 at 10 22 15" src="https://user-images.githubusercontent.com/7934273/102156064-17de0000-3ec0-11eb-8d81-03f0173f4a5a.png">
https://tatoeba.org/eng/sentences/show/2239900

**Comment by jiru** [comment]
It seems I cannot reproduce this issue (or there is something I failed to understand.) The latter "chain" icon brings me to the comment, not the top of the page.
