### ISSUE TITLE
Easier way to add vocabulary on "Add vocabulary items"

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2597]
**Story** or **Context**
I was adding vocabulary items on https://tatoeba.org/eng/vocabulary/add to create and request sentences. However, each time I wanted to add a new vocabulary request, I did the following:

* I clicked on the box
* Typed the sentence
* Hit "Enter"
* Repeat the process

It would be good if I didn't have to click on the box again making it "typeable" again.

Image: Box after a vocabulary item is added

![image](https://user-images.githubusercontent.com/7658430/102683722-d1cfb780-41b1-11eb-9a8d-3e803b3c9d50.png)

**Comment by AndiPersti** [comment]
@RyckRichards What browser do you use?

It looks like on Firefox the input field is always focused after pressing <Enter> while on Chromium (a Chrome variant) it isn't.

**Comment by RyckRichards** [comment]
@AndiPersti Chrome

**Comment by AndiPersti** [comment]
Fixed by #2602
