### ISSUE TITLE
Provide "See translations for" button for each sentence in a list of favorites

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#26]
alpha44, private communication

alpha44 would like to have a "See translations for" button for each of the sentences in a list of favorite sentences, whether the list belongs to the user or to someone else.

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/414

**Comment by trang** [comment]
Closing this. It's unlikely we'll be able to invest time implementing this.

In a more distant future, we'll need to reconsider whether this "favorite" feature is worth keeping as is. It pretty much duplicates the list feature: if you create a list and call it "Sentences that I like", then it's basically what the favorite does.

Only difference is that it's much easier to favorite a sentence than to add a sentence to a list.
