### ISSUE TITLE
Reword the string #448 on default.pot

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2604]
Actually, it is as "You **will** receive a private message when it **WILL** BE completed." Instead of "You will receive a private message when it IS completed."

https://www.transifex.com/tatoeba/tatoeba_website/translate/#vi_VN/tatoebaResource/153568319

**Comment by alanfgh** [comment]
Good catch. In fact, I think the wording for the entire string could be improved. from this:

    The license switch of your sentences is in progress. You will receive a private message when it will be completed.

to this:

    The license for your sentences is being switched. You will receive a private message when the operation is complete.
