### ISSUE TITLE
Add nginx rewrite rule to enable short urls for accessing sentences by id

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#261]
06:01 < CK-in-Japan> I'd love to see the following added into the .htaccess file.
06:01 < CK-in-Japan> RewriteEngine on
06:01 < CK-in-Japan> RewriteRule ^(\d+)$ http://tatoeba.org/eng/sentences/show/$1 [R,NC]

**Comment by trang** [comment]
I'm closing this one since there was a duplicate created (cf. #955) and the other issue has more information.
