### ISSUE TITLE
when I change my profile icon, I'm called a "previous member"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2614]
In order to update my profile icon, I had to delete the old icon. After I did this, the UI started indicating that I was a "former member" even though I had not deleted my account:

![former_member_2](https://user-images.githubusercontent.com/1213027/106495061-3062a380-6489-11eb-8cc2-7bc655226390.png)

Later, the "former member" text stopped appearing. I think that this might have been after I uploaded a new icon.

This was on Firefox/Windows, though that may not be relevant.

**Comment by ckjpn** [comment]
I checked this on dev.tatoeba.org

### 1. Before
<img width="415" alt="Screen Shot 2021-02-09 at 10 57 22" src="https://user-images.githubusercontent.com/7934273/107305233-ec455380-6ac5-11eb-8ade-544fc17955db.png">

### 2. After Deleting
<img width="258" alt="Screen Shot 2021-02-09 at 10 57 55" src="https://user-images.githubusercontent.com/7934273/107305273-05e69b00-6ac6-11eb-9543-ba26417dfa49.png">

### 3. After Uploading a New Image
<img width="220" alt="Screen Shot 2021-02-09 at 10 58 31" src="https://user-images.githubusercontent.com/7934273/107305284-097a2200-6ac6-11eb-84fb-478e074eafb4.png">
