### ISSUE TITLE
Change interface language (temporarily) by URL?

### ISSUE THREAD

**Issue by SlibMajuda** [Tatoeba/tatoeba2#2616]
I'm working on the website localization and need to swap between UI languages to see if my translations fit the contexts. It's OK but would take minutes and thus inconvenient.

I'm aware that many websites allow users to just edit part of the URLs from like '/en' to '/fr' for example, so they can change the language. Is it possible in this case?

https://tatoeba.org/eng/

**Comment by jiru** [comment]
I understand. Tatoeba acts this way to allow users to exchange URLs while browsing the website in different languages. For example, when I share the link https://tatoeba.org/eng to my Italian friend (who has a browser configured in Italian), it will automatically redirect to https://tatoeba.org/ita and show the website in Italian right away.

I am not sure if we can find a good solution for this. As a workaround, you can use the "private navigation" (aka "incognito mode") to browse the website in a different language than regular navigation. The language you select in private tabs won’t interfere with the one in regular tabs.

**Comment by Yorwba** [comment]
Alternatively, you can choose one interface on `https://tatoeba.org/` and another on `https://dev.tatoeba.org`. If you add (or remove) `dev.` at the beginning of the URL, the interface language will automatically change.

**Comment by jiru** [comment]
Thank you all! I added a paragraph about that to the [wiki article](https://en.wiki.tatoeba.org/articles/show/interface-translation). I think it’s good enough for now.
