### ISSUE TITLE
The Wiki links on the main page should be localizable

### ISSUE THREAD

**Issue by soliloquist-tatoeba** [Tatoeba/tatoeba2#2626]
No matter what language is selected for the UI, the Wiki links (Quick Start Guide, Tatoeba Wiki and FAQ) on the [main page](https://tatoeba.org) are always the same (the hypertext changes though, but the link itself doesn't). It may be the default behavior if the page hasn't been translated into the UI language yet, but it doesn't feel right for the link to go to the English page when a translated page is available. Perhaps those links can be added to Transifex as strings to allow translators change them to the links of the translated pages. (with an additional warning that no change should be made if the page hasn't been translated yet)

I would also like the 'Quick Start Guide' link on the 'Welcome to Tatoeba' banner (#2624) to be localizable in the same way if you add it. Providing such links in the localized version would be more user-friendly for new users.

**Comment by jiru** [comment]
Thanks for bringing this up. Allowing to change the whole URL is a security whole. Maybe we could allow localizing the article name part of the URL only.

**Comment by soliloquist-tatoeba** [comment]
As you said, it would be a better approach for security reasons. But I guess the language part of the URL would also need to be edited along with the article name in this case.

https://en.wiki.tatoeba.org/articles/show/sss

doesn't redirect to

https://tr.wiki.tatoeba.org/articles/show/sss

**Comment by jiru** [comment]
No worries. The language part of the URL follows the [language tags standard](https://en.wikipedia.org/wiki/IETF_language_tag), so we can calculate it from the currently selected UI language.

**Comment by soliloquist-tatoeba** [comment]
Great, thanks for illuminating that.
