### ISSUE TITLE
Strange stats in the Spanish sentences dataset (as of 02-24-2021, 14:45 EST)

### ISSUE THREAD

**Issue by CatChenal** [Tatoeba/tatoeba2#2629]
I downloaded the Spanish sentences dataset (https://downloads.tatoeba.org/exports/per_language/spa/spa_sentences.tsv.bz2)
and search for "!" and "?" to find out if they were paired with their inverted versions [as required by the Spanish typography](https://spanish.stackexchange.com/questions/922/is-it-acceptable-to-leave-out-the-inverted-punctuation-marks).
* This dataset has 108313 sentences.
* NONE contain an exclamation mark.
* ALL those that contain a question mark are missing a preceding inverted exclamation mark.

It is just a guess, but this could be due to a simple data entry problem (i.e. keyboard issue): the contributors may not know how to type these special characters.

**On Windows**:
* ¿ is obtained by pressing the ALT key while entering 168 on the number pad
* ¡ is obtained by pressing the ALT key while entering 173 on the number pad

See [this post for other OS and additional characters](https://spanish.meta.stackexchange.com/questions/10/easy-way-to-type-accented-characters).

PS: While not strictly a Bug, I open this issue as a bug because the other options were less relevant. Perhaps adding a **'Quality Control'** tag would help.

**Comment by alanfgh** [comment]
> NONE contain an exclamation mark.

That's not what I see. For instance, here's sentence 2486:

2486	spa	¡Feliz cumpleaños, Muiriel!

> ALL those that contain a question mark are missing a preceding inverted exclamation mark.

I think you mean "... a preceding inverted **question** mark." Is that right? In that case as well, that's not what I see. For instance, here's sentence 2496:

2496	spa	¿Es una foto reciente?

How did you open the bz2 file? I did it with 7-Zip, which extracted the bz2 file into a directory containing a file called spa_sentences.tsv. Then I used Notepad++ to open the file. Here is the top of the file:

2481	spa	¡Intentemos algo!
2482	spa	Tengo que irme a dormir.
2483	spa	¿Qué estás haciendo?
2484	spa	¿Qué es eso?
...

Note that the file uses the UTF-8 encoding. Is it possible that you are looking at it in a file that is using a different encoding?

I also suggest double-checking by finding the IDs of sentences that you think contain unmatched question or exclamation marks in your downloaded file and looking at them on Tatoeba. You should make sure that your browser is treating the page encoding as UTF-8 (which it should do automatically). If you still see problems, just let us know.

**Comment by CatChenal** [comment]
You are right on all counts @alanfgh: my regex was not outputting any initial punctuation mark. 
Sorry for sounding like I tested everything!

**Comment by alanfgh** [comment]
No problem at all, @CatChenal.
