### ISSUE TITLE
Sentence page resizes unjustified when entering a character in the Tag search field...

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2650]
Safari on 12.9” iPad 2nd Gen 2017 in 70% split view

The sentence page resizes automatically when entering a character in the Tag search field in the right pane, upon emptying the text field to blank the view resizes back to normal size...

https://user-images.githubusercontent.com/725445/111297184-a42dc980-864d-11eb-9ff6-4f0931685b49.mp4

**Comment by jiru** [comment]
@mramosch Could you confirm the problem is solved on https://dev.tatoeba.org/?

**Comment by mramosch** [comment]
Why? The bug is still there...

**Comment by mramosch** [comment]
OK, sorry - now I get what you want me to do ;-)

Checked it and it seems to work...

**Comment by mramosch** [comment]
And it seems much snappier now...
