### ISSUE TITLE
Avar

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2652]
* Language name:  Avar
* Language info: It is spoken mainly in the western and southern parts of the Russian Caucasus republic of Dagestan, and the Balaken, Zaqatala regions of north-western Azerbaijan. Some Avars live in other regions of Russia. There are also small communities of speakers living in the Russian republics of Chechnya and Kalmykia; in Georgia, Kazakhstan, Ukraine, Jordan, and the Marmara Sea region of Turkey. It is spoken by about 762,000 people worldwide. 
* ISO 639-3 code: ava
* Public List: https://tatoeba.org/eng/sentences_lists/show/169304
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111366744-e8ef4a00-86b9-11eb-9088-9381592bccae.png)

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
- Language name: Avar (ava)
- Language info: https://en.wikipedia.org/wiki/Avar_language
- ISO 639-3 code: AVA
- Public List: https://tatoeba.org/eng/sentences_lists/show/169304
- Icon: https://en.wikipedia.org/wiki/Avars_(Caucasus)#/media/File:Flag_of_Avars.svg
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA


Reference: #2658
