### ISSUE TITLE
Lezgi

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2653]
* Language name: Lezgi
* Language info: In 2002, Lezgian was spoken by about 397,000 people in Russia, mainly Southern Dagestan, and in 1999 by 178,400 people in mainly the Qusar, Quba, Qabala, Oghuz, Ismailli and Khachmaz (Xaçmaz) provinces of northeastern Azerbaijan. Lezgian is also spoken in Kazakhstan, Kyrgyzstan, Turkey, Turkmenistan, Ukraine, Germany and Uzbekistan by immigrants from Azerbaijan and Dagestan. Some speakers are in the Balikesir, Yalova, Izmir, Bursa regions of Turkey especially in Kirne (Ortaca), a village in Balikesir Province which touches the western coast, being south-west of Istanbul. The total number of speakers is about 800,000.
* ISO 639-3 code: lez
* Public List: https://tatoeba.org/eng/sentences_lists/show/169305
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111906367-37179b00-8a76-11eb-8762-49c22f4f0f9b.png)

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
- Language name: Lezgi (lez)
- Language info: https://en.wikipedia.org/wiki/Lezgian_language
- ISO 639-3 code: LEZ
- Public List: https://tatoeba.org/eng/sentences_lists/show/169305
- Icon: https://user-images.githubusercontent.com/80341342/111365262-4bdfe180-86b8-11eb-91d7-c5663eacb4fd.png
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA


Reference: #2658

**Comment by jiru** [comment]
@QazQazaq The list 169305 contains many single-word sentences. These "sentences" should be either turned into complete sentences or removed from the list or deleted altogether.

**Comment by QazQazaq** [comment]
Those are Lezgi Numbers.

**Comment by alanfgh** [comment]
Whether or not they're numbers, they're not sentences.

**Comment by soliloquist-tatoeba** [comment]
@QazQazaq

I deleted the single-word entries in the list.

Also, the flag on the main page of Lezgi Wikipedia is a bit different than the one you proposed. There's some inscription on it. The difference might be trivial, but wouldn't it be better to use that version?

https://lez.wikipedia.org/wiki/%D0%9A%D1%8C%D0%B8%D0%BB%D0%B8%D0%BD_%D1%87%D1%87%D0%B8%D0%BD

**Comment by QazQazaq** [comment]
It would be fine to use that flag.

**Comment by QazQazaq** [comment]
I edited the flag in the request.

**Comment by Plkmoi** [comment]
I cannot see Lezgi in the site.

**Comment by trang** [comment]
@Plkmoi This language request is still ongoing. There is apparently some blurriness with the flag that may need to be looked into first.

**Comment by RyckRichards** [comment]
I sent this email to Gillux but I got no response. I will copy and paste it
here

I wasn't able to remove the blurriness. Could you please merge this PR and
fix that? I can try to do so but I think I1ll need much more time.

**Comment by jiru** [comment]
@RyckRichards Sorry I missed that email.

I will merge the PR next week and get the flag by the next update. @Plkmoi Hopefully Lezgi will be available on the site starting from Monday, the 26th of April.

**Comment by jiru** [comment]
I fixed the flag but now all the sentences in the [Lezgi list](https://tatoeba.org/sentences_lists/show/169305) are red. What should we do with them?
