### ISSUE TITLE
Ingush

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2654]
* Language name: Ingush
* Language info: Ingush is spoken by about 413,000 people (2002), primarily across a region in the Caucasus covering parts of Russia, primarily Ingushetia and Chechnya. Speakers can also be found in Kazakhstan, Uzbekistan, Turkmenistan, Belgium, Norway, Turkey and Jordan.

* ISO 639-3 code: inh
* Public List: https://tatoeba.org/eng/sentences_lists/show/169311
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111362839-4b921700-86b5-11eb-8927-a545c49ebfb4.png)

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
- Language name: Ingush (inh)
- Language info: https://en.wikipedia.org/wiki/Ingush_language
- ISO 639-3 code: INH
- Public List: https://tatoeba.org/eng/sentences_lists/show/169311
- Icon: https://en.wikipedia.org/wiki/Ingushetia#/media/File:Flag_of_Ingushetia.svg
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA


Reference: #2658
