### ISSUE TITLE
Abaza

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2655]
* Language name: Abaza
* Language info: The Abaza language is spoken in Russia and Turkey. Although it is endangered, it is still spoken in several regions in Russia. These include Kara-Pago, Kubina, Psikh, El'burgan, Inzhich-Chukun, Koi-dan, Abaza-Khabl', Malo-Abazinka, Tapanta, Krasnovostochni, Novokuvinski, Starokuvinski, Abazakt and Ap-sua.
* ISO 639-3 code: abq
* Public List: https://tatoeba.org/eng/sentences_lists/show/169312
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111363304-e25ed380-86b5-11eb-87a4-a35d3461bab7.png)

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
- Language name: Abaza (abq)
- Language info: https://en.wikipedia.org/wiki/Abaza_language
- ISO 639-3 code: ABQ
- Public List: https://tatoeba.org/eng/sentences_lists/show/169312
- Icon: https://user-images.githubusercontent.com/80341342/111363304-e25ed380-86b5-11eb-87a4-a35d3461bab7.png
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA


Reference: #2658
