### ISSUE TITLE
Kabardian

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2656]
* Language name: Kabardian
* Language info: It is spoken mainly in parts of the North Caucasus republics of Kabardino-Balkaria and Karachay-Cherkessia (Eastern Circassia), and in Turkey, Jordan and Syria (the extensive post-war diaspora). It has 47 or 48 consonant phonemes, of which 22 or 23 are fricatives, depending upon whether one counts [h] as phonemic, but it has only 3 phonemic vowels.* The total number of speakers are 516,000 in Russian Federation (2010 census), 6,700 monolinguals (2002 census) with total ethnic population as 590,000 (2010 census). Total users in all countries are 1,712,000 (2002–20)
* ISO 639-3 code: kbd
* Public List: https://tatoeba.org/eng/sentences_lists/show/169308 
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111363755-6913b080-86b6-11eb-8706-d66cff24509d.png)

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
- Language name: Kabardian (kbd)
- Language info: https://en.wikipedia.org/wiki/Kabardian_language
- ISO 639-3 code: KBD
- Public List: https://tatoeba.org/eng/sentences_lists/show/169308
- Icon: https://upload.wikimedia.org/wikipedia/commons/0/0b/Flag_of_the_Princedom_of_Kabardia_%28Early_19th_century%29.svg
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA


Reference: #2658
