### ISSUE TITLE
Lak

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2657]
* Language name: Lak (lbe)
* Language info: https://en.wikipedia.org/wiki/Lak_language
* ISO 639-3 code: LBE
* Public List: https://tatoeba.org/eng/sentences_lists/show/169306
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111573990-9e60f100-87d1-11eb-89be-2e2c9292ee77.png)

* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
- Language name: Lak (lbe)
- Language info: https://en.wikipedia.org/wiki/Lak_language
- ISO 639-3 code: LBE
- Public List: https://tatoeba.org/eng/sentences_lists/show/169306
- Icon: https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_the_Lak_People_v2.svg
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA


Reference: #2658
