### ISSUE TITLE
Dargwa

### ISSUE THREAD

**Issue by QazQazaq** [Tatoeba/tatoeba2#2658]
* Language name: Dargwa
* Language info: Dargwa (дарган мез, dargan mez) is a Northeast Caucasian language spoken by the Dargin people in the Russian republic Dagestan. It is the literary and main dialect of the dialect continuum constituting the Dargin languages. The four other languages in this dialect continuum (Kajtak, Kubachi, Itsari, and Chirag) are often considered variants of Dargwa. Korjakov (2012) concludes that Southwestern Dargwa is closer to Kajtak than it is to North-Central Dargwa. There are 429,347 speakers of Dargwa proper in Dagestan, 7,188 in neighbouring Kalmykia, 1,620 in Khanty–Mansi AO, 680 in Chechnya, and hundreds more in other parts of Russia. Figures for the Lakh dialect spoken in central Dagestan are 142,523 in Dagestan, 1,504 in Kabardino-Balkaria, 708 in Khanty–Mansi.
* ISO 639-3 code: dar
* Public List: https://tatoeba.org/eng/sentences_lists/show/169309
* Icon: 
![image](https://user-images.githubusercontent.com/80341342/111364932-de33b580-86b7-11eb-9e8f-1305b3621511.png)

* Requested by:
https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
You should have emailed the language team - https://en.wiki.tatoeba.org/articles/show/new-language-request. @soliloquist-tatoeba @sabretou

**Comment by soliloquist-tatoeba** [comment]
Hi, @QazQazaq. Welcome to Tatoeba, and thanks for being interested in adding new languages. But you need to provide some example sentences from native sources and add them to their respective lists before making language requests.

See a valid example.

https://github.com/Tatoeba/tatoeba2/issues/2527

More info about lists:

https://en.wiki.tatoeba.org/articles/show/quick-start#lists

**Comment by QazQazaq** [comment]
Respected Sir,

I have made lists for Avar, Lezgi, Kabardian and Lak languages. I have sent
Private messages to the TatoebaLanguage Team for the above mentioned
languages.

Thanking you

**Comment by QazQazaq** [comment]
Respected Sir,

I have made lists for Dargwa, Abaza and Ingush languages. I have sent
Email to the TatoebaLanguage Team for the above mentioned
languages.

Thanking you

**Comment by soliloquist-tatoeba** [comment]
@RyckRichards 
QazQazaq added the links of the public lists for the language requests. You can create PRs now if you want.

I'm also copying them with the standard format to make it easier for you to handle.

- Language name: Dargwa (dar)
- Language info: https://en.wikipedia.org/wiki/Dargwa_language
- ISO 639-3 code: DAR
- Public List: https://tatoeba.org/eng/sentences_lists/show/169309 
- Icon: https://en.wikipedia.org/wiki/File:Flag_of_Dahadaevsky_rayon_(Dagestan).png
- Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by soliloquist-tatoeba** [comment]
@QazQazaq

Could you edit the titles of the issues you created and add the language codes in parentheses? So they should be:

Dargwa (dar)
Avar (ava)
etc.
