### ISSUE TITLE
Limburgish (lim)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2697]
* Language name: Limburgish
* Language info: https://en.wikipedia.org/wiki/Limburgish
* ISO 639-3 code: LIM
* Public List: https://tatoeba.org/nld/sentences_lists/show/169467 and 
* Icon: https://imgur.com/a/6kYwe1b
* Requested by: https://tatoeba.org/eng/user/profile/GlossaMatik and https://tatoeba.org/eng/user/profile/MarijnKp

Note

https://tatoeba.org/eng/sentences/show/10014694#comment-1273169

**Comment by Plkmoi** [comment]
Why are you removing requests added properly?

**Comment by QazQazaq** [comment]
I don't know why he is doing that. Is he now against others contributing Languages?

**Comment by RyckRichards** [comment]
Related:

https://tatoeba.org/eng/wall/show_message/36920#!#message_36920
https://tatoeba.org/eng/wall/show_message/36924#!#message_36924

**Comment by QazQazaq** [comment]
Some requests were made properly but they were still removed.

**Comment by Plkmoi** [comment]
I requested and @QazQazaq requested but both were removed and I even sent email for requesting.

**Comment by QazQazaq** [comment]
> Related:
> 
> https://tatoeba.org/eng/wall/show_message/36920#!#message_36920
> https://tatoeba.org/eng/wall/show_message/36924#!#message_36924

This does not explain why requests were taken after being made properly by @Plkmoi .

**Comment by Plkmoi** [comment]
I don't know why this is happening.
