### ISSUE TITLE
Where do I load "sentence" from?

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2698]
I've cloned SentencesController.php to be ApiController.php and manged to hook it in to the URL system, but the show() method in SentencesController.php accesses $this->Sentences correctly, but my clone version doesn't. I haven't yet figured out why not. Any help or pointers would be appreciated. Thanks.

![image](https://user-images.githubusercontent.com/7943077/116009210-84a89a00-a618-11eb-8f63-6e0ed05a83bd.png)

By contrast, $this->Sentences has a whole bunch of stuff when I look at it in the SentencesController.php show():
![image](https://user-images.githubusercontent.com/7943077/116009352-6c854a80-a619-11eb-8076-9e15dc6f0d6b.png)

I haven't (yet) been able to figure out where/when this gets loaded, and why it doesn't load it in my almost identical cloned code.

**Comment by jiru** [comment]
It works in `SentencesController` and not in your code because CakePHP automatically loads the model that has the same name as the controller. So from the `SentencesController`, you already get the `Sentences` model loaded. You need to explicitly load the model with `$this->loadModel('Sentences');` before accessing `$this->Sentences` (see also the [documentation](https://book.cakephp.org/3/en/controllers.html#loading-additional-models)).

Good luck with the rest! :slightly_smiling_face:

**Comment by githubshrek** [comment]
Perfect! Thanks, yes, that solved it:
![image](https://user-images.githubusercontent.com/7943077/116035449-4d140f00-a665-11eb-8172-8365726d7008.png)

I had read that Cake like convention over configuration https://book.cakephp.org/4/en/intro/conventions.html so I had the thought that the SentencesController would load for free a Sentences object, but my ApiController would only load for free an Api object. So, yes, the loadModel() method was the secret.

In fact, while looking at how to get around this, I think I might also/instead look at adding a /json path to entities. I had already figured out that /sentences/json would give me access to a json() method in the SentencesController which isn't such a bad thing. We'll see...

**Comment by jiru** [comment]
I am glad to know that it works! :slightly_smiling_face: By the way, the documentation link you mentioned is for CakePHP 4 but we are still using CakePHP 3 so you should refer to the Cakebook for CakePHP 3. Some details might differ between the two versions.
