### ISSUE TITLE
How can I see a Json view of a sentence?

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2699]
I was beginning to prepare a json.ctp to display at URL http://localhost:8080/eng/sentences/json/5 which would show a Json for the sentence number 5, but I notice there is already a SentencesJsonView.php and I don't want to reinvent what is already working. Where/how can I see this view in action? Where is it documented? Thanks!

![image](https://user-images.githubusercontent.com/7943077/116036958-bb59d100-a667-11eb-8c99-600553a6c323.png)

**Comment by jiru** [comment]
Yes, there are already some json views you can get inspiration from. You can have a look at the ExportsController for a simple example or the [documentation about json views](https://book.cakephp.org/3/en/views/json-and-xml-views.html). Note that the SentencesJsonView.php file you mentioned is a special code that was introduced to overcome a limitation of AngularJS. You shouldn’t need to write anything like that for an API.

I am closing the issue but feel free to comment back or reopen if anything’s not clear.
