### ISSUE TITLE
Warn user and/or admin when sentence's language flag is changed

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#27]
[JimBreen, Wall](http://tatoeba.org/eng/wall/show_message/17436#message_17436)
Jim wrote that he recently came across two cases where sentences were overwritten by versions in different languages. He thought it occurred because the person/persons who did it didn't know the processes that well. I asked him to clarify whether he meant that a warning should be displayed to the user or the admin, or both. He said that he meant both. In further discussion, he and tommy_san said that whereas changing a sentence's flag was likely to be legitimate when the sentence was new, it was less likely to be legitimate later, so perhaps a warning should only be issued if the sentence was old.

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/413

**Comment by trang** [comment]
This issue is a combination of #533 and #36.
