### ISSUE TITLE
DataBase mismatch...

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2700]
Does the fact that the #number of the latest contributions differ about 400.000 from the reported corpus stats mean that there are already 400.000 deleted sentences in the dB?

**Comment by jiru** [comment]
What reported corpus stats are you talking about?

**Comment by jiru** [comment]
I assume you are talking about the latest sentence id compared to the total number of sentences. The answer is yes.

**Comment by jiru** [comment]
I will close this issue now but feel free to reopen it if something is not clear.
