### ISSUE TITLE
Tamasheq (taq)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2701]
* Language name: Tamasheq
* Language info: https://en.wikipedia.org/wiki/Tamasheq_language
* ISO 639-3 code: taq
* Public List: https://tatoeba.org/eng/sentences_lists/show/169400
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
