### ISSUE TITLE
Tarifit (rif)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2702]
* Language name: Tarifit
* Language info: https://en.wikipedia.org/wiki/Riffian_language
* ISO 639-3 code: rif
* Public List: https://tatoeba.org/eng/sentences_lists/show/169399
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
