### ISSUE TITLE
Tumẓabt (mzb)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2703]
* Language name: Tumẓabt
* Language info: https://en.wikipedia.org/wiki/Mozabite_language
* ISO 639-3 code: mzb
* Public List: https://tatoeba.org/eng/sentences_lists/show/169402
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
