### ISSUE TITLE
Central Atlas Tamazight (tzm)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2704]
* Language name: Central Atlas Tamazight
* Language info: https://en.wikipedia.org/wiki/Central_Atlas_Tamazight
* ISO 639-3 code: tzm
* Public List: https://tatoeba.org/eng/sentences_lists/show/169398
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719

**Comment by Plkmoi** [comment]
Can this be reopened as the necessary procedures were followed?
