### ISSUE TITLE
Ažbali (jbn)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2705]
* Language name: Ažbali
* Language info: https://en.wikipedia.org/wiki/Nafusi_language
* ISO 639-3 code: jbn
* Public List: https://tatoeba.org/eng/sentences_lists/show/169397
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
