### ISSUE TITLE
Taclḥit (shi)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2706]
* Language name: Taclḥit
* Language info: https://en.wikipedia.org/wiki/Shilha_language
* ISO 639-3 code: shi
* Public List: https://tatoeba.org/eng/sentences_lists/show/169404
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
