### ISSUE TITLE
Tamahaq (thv)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2707]
* Language name: Tamahaq
* Language info: https://en.wikipedia.org/wiki/Tamahaq_language
* ISO 639-3 code: thv
* Public List: https://tatoeba.org/eng/sentences_lists/show/169405
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
