### ISSUE TITLE
Tacawit (shy)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2708]
* Language name: Tacawit
* Language info: https://en.wikipedia.org/wiki/Shawiya_language
* ISO 639-3 code: shy
* Public List: https://tatoeba.org/eng/sentences_lists/show/169406
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
