### ISSUE TITLE
Haqbaylit̠ (cnu)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2709]
* Language name: Haqbaylit̠
* Language info: https://en.wikipedia.org/wiki/Shenwa_language
* ISO 639-3 code: cnu
* Public List: https://tatoeba.org/eng/sentences_lists/show/169407
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Related: #2719
