### ISSUE TITLE
How to display a page without the header and footer?

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2771]
I'm making good progress (I think) in providing a Json of a given sentence, e.g. http://localhost:8080/eng/sentences/json/5 would display the Json for sentence 5.

However, I don't see how to get rid of the standard header and footer. I understand that this is required on all normal pages, so it make sense to include it by default, but do you know how I make it so that the header/footer _doesn't_ appear:
![image](https://user-images.githubusercontent.com/7943077/116473274-45c44f80-a877-11eb-87df-e1c592a1f81b.png)

The Json beautified:
![image](https://user-images.githubusercontent.com/7943077/116474469-d7808c80-a878-11eb-9f2d-b95f8da56928.png)

For reference, here is my code:
![image](https://user-images.githubusercontent.com/7943077/116473505-891ebe00-a877-11eb-9ac2-cd92b1a95fdd.png)

Here is my template:
![image](https://user-images.githubusercontent.com/7943077/116473590-a6538c80-a877-11eb-9759-1602842ef3a4.png)

Thanks for any pointers.

**Comment by jiru** [comment]
Use `$this->autoRender = false;` or `$this->disableAutoRender();` in the controller action.

**Comment by githubshrek** [comment]
Thanks, that was just what I was missing.

Now the first part of my code seems to be complete:
![image](https://user-images.githubusercontent.com/7943077/116623281-4ed02200-a946-11eb-9769-c9ae8ba71f42.png)

Output is simply a Json of a Sentence, which is exactly what I wanted:
![image](https://user-images.githubusercontent.com/7943077/116623520-ab334180-a946-11eb-88d4-e550a56ede48.png)
