### ISSUE TITLE
Greek extended support

### ISSUE THREAD

**Issue by chopinesque** [Tatoeba/tatoeba2#2802]
Looks like diacritics-insensitive search does not work on Greek extended. See:

https://forum.manticoresearch.com/t/diacritics-insensitive-search/816/3
https://github.com/Tatoeba/tatoeba2/blob/3170f7326ad2939c691ba23f05edc65026ade355/src/Shell/SphinxConfShell.php#L123

**Comment by Yorwba** [comment]
As Sergey mentions in that thread, Tatoeba uses a custom `charset_table` to define which characters are equivalent to each other, and our definition leaves Greek accents intact. That's entirely down to me not knowing exactly how important those accents are for distinguishing unrelated words, so I played it safe by keeping them.

The accents and accent combinations we currently keep distinct are:
ά alpha with tonos
α alpha
ἀ alpha with psili
ἁ alpha with dasia
ἂ alpha with psili and varia
ἃ alpha with dasia and varia
ἄ alpha with psili and oxia
ἅ alpha with dasia and oxia
ἆ alpha with psili and perispomeni
ἇ alpha with dasia and perispomeni
ὰ alpha with varia
ᾀ alpha with psili and ypogegrammeni
ᾁ alpha with dasia and ypogegrammeni
ᾂ alpha with psili and varia and ypogegrammeni
ᾃ alpha with dasia and varia and ypogegrammeni
ᾄ alpha with psili and oxia and ypogegrammeni
ᾅ alpha with dasia and oxia and ypogegrammeni
ᾆ alpha with psili and perispomeni and ypogegrammeni
ᾇ alpha with dasia and perispomeni and ypogegrammeni
ᾰ alpha with vrachy
ᾱ alpha with macron
ᾲ alpha with varia and ypogegrammeni
ᾳ alpha with ypogegrammeni
ᾴ alpha with oxia and ypogegrammeni
ᾶ alpha with perispomeni
ᾷ alpha with perispomeni and ypogegrammeni

Which ones should be treated the same? All of them?

On a related note: we currently support stemming (i.e. ignoring things like different verb endings etc.) for Modern Greek texts using the [Snowball stemmer library](https://snowballstem.org). I don't know whether it would be useful for Ancient Greek as well. Using the [Snowball demo for Greek](https://snowballstem.org/demo.html#Greek) and the two sentences from [your search for Αἴγυπτον](https://tatoeba.org/en/sentences/search?from=&query=Αἴγυπτον&to=) as example input, I get

Ἡρόδοτός φησι τὴν Αἴγυπτον δῶρον εἶναι τοῦ Νείλου.
Οὐδεὶς δὲ αὐτοῦ καθηγήσατο, πλὴν ὅτι εἰς Αἴγυπτον ἐλθὼν τοῖς ἱερεῦσι συνδιέτριψεν.

turning into

ἡροδοτ φησ τὴν αἴγυπτον δῶρον εἶνα τοῦ νειλ.
​οὐδεὶσ δὲ αὐτοῦ καθηγησατ, πλὴν ὅτ εἰσ αἴγυπτον ἐλθὼν τοῖσ ἱερεῦσ συνδιετριψεν.

Does that seem reasonable?

**Comment by chopinesque** [comment]
All "a" characters need to be normalized. Of course, that applies to all [accented characters](https://www.translatum.gr/forum/index.php?topic=577557.0). In the Manticore post above, they say that this is the default, is that right?

The stemmer is no good for Ancient Greek.

**Comment by trang** [comment]
@Yorwba As usual, thanks for your pull requests to fix and improve our search engine :)

@chopinesque I've deployed the changes on our dev website (https://dev.tatoeba.org). If you have a moment, could you try out some search queries and see if you get the expected results? Note that the sentences we have in dev are not the same as in prod, you may want to look what's available there (https://dev.tatoeba.org/en/sentences/show_all_in/grc/none).

**Comment by chopinesque** [comment]
I have been doing some testing and it looks like partial word matching is disabled. For example, searching for ιερευς or ιερευσ will not find this sentence https://tatoeba.org/en/sentences/show/10112269 I guess this is a conscious decision, right?

**Comment by alanfgh** [comment]
From the page [How to Search for Text](https://en.wiki.tatoeba.org/articles/show/text-search#), here's item #2 under the section "Main search field":

> (2) In Arabic, Basque, Catalan, Danish, Dutch, English, Finnish, French, German, **Greek**, Hindi, Hungarian, Indonesian, Irish, Italian, Lithuanian, Nepali, Norwegian (Bokmål), Portuguese, Romanian, Russian, Spanish, Swedish, Tamil and Turkish, a search for a word such as **live** will also find similar words, such as **lived** and **living**. If you want to indicate that a word should be matched exactly, you must put an equals sign before it: **=live**

Greek is in the list, so searches like this should work in general, but this feature (called "stemming") does not work perfectly. However, you should be able to use an asterisk, provided that the rest of the text you search for is three letters long or more:

ιερευσ*

This did not work for me, though. I'm hoping someone else with a better understanding of Greek and/or the search engine can add to the discussion.

**Comment by Yorwba** [comment]
[Sentence #10112269](https://tatoeba.org/en/sentences/show/10112269) is in Ancient Greek. Stemming is currently only enabled for Modern Greek, since based on [chopinesque's comment above](https://github.com/Tatoeba/tatoeba2/issues/2802#issuecomment-865652759) I inferred that Ancient and Modern Greek need different stemmers.

[Searching for `ιερευσ*` in Ancient Greek](https://tatoeba.org/en/sentences/search?from=grc&query=%CE%B9%CE%B5%CF%81%CE%B5%CF%85%CF%83*&to=) does turn up the sentence for me.
