### ISSUE TITLE
Can't set "unknown" language

### ISSUE THREAD

**Issue by sikmir** [Tatoeba/tatoeba2#2810]
I'm trying to follow [Language requests wiki page](https://en.wiki.tatoeba.org/articles/show/new-language-request):
> **Step 2: Create a list with sentences in your language**
> ...
> * When you add your translations, choose the option "Auto detect" in the language dropdown.
> * After the sentence/translation is added, if the language was not identified as "unknown" (you will see an icon with a question mark if it is), then click on the language icon and select "other language".

But nothing happens after selecting "other language", there is no way to set the language to "unknown".

**Comment by alanfgh** [comment]
I see the same problem as you. I tried both with the older interface and the newer interface, switching between them by choosing "Display sentences with the new design..." under "Experimental options" in the "Options" page under "Settings". In both cases, I was unable to set the language to "unknown". I believe the instructions are out of date, but I'm not sure how they should be changed.

**Comment by sikmir** [comment]
That's definetly wrong that sentences on some "unknown" language pinned to some auto-detected (wrong) language.

**Comment by trang** [comment]
I was not able to reproduce this bug on the dev website. Here are the sentences I created and that I could change to "unknown" language:

- https://dev.tatoeba.org/en/sentences/show/7843746 (using the new sentence design, with Firefox on Windows)
- https://dev.tatoeba.org/en/sentences/show/7843747 (using the old sentence design, with Firefox on Windows)
- https://dev.tatoeba.org/en/sentences/show/7843748 (using the old sentence design and adding the sentence directly from a list, with Firefox on Windows)
- https://dev.tatoeba.org/en/sentences/show/7843749 (using the old sentence design, with Firefox on Android)

@sikmir @alanfgh 
Could it be that you have some add-ons installed that could interfere with the Javascript code of Tatoeba? 
Or perhaps this is an issue specific to a certain browser/OS. Can you try to see if you can reproduce the bug with another browser or from another device?

**Comment by sikmir** [comment]
@trang I've tried:
* Firefox (Linux)
* Opera (Linux)
* Firefox (Android)

The same issue in all above browsers.

**Comment by trang** [comment]
@sikmir Hmm, okay then maybe you are using a combination of options in the Settings that prevents changing a language to "unknown"... Could you tell me what is your username on Tatoeba? I will check what options you have and see if I can reproduce the issue using the same settings as you.

**Comment by sikmir** [comment]
Profile: https://tatoeba.org/en/user/profile/sikmir
My list: https://tatoeba.org/en/sentences_lists/show/169566

**Comment by trang** [comment]
Okay, thanks! Now I know why this happens :) This bug has already been reported before:  #1614.

As a workaround, you can first select a wrong language (like English). Then after the sentence is set to English, you can click again the flag and you will be able to select "Other language".

Alternatively, you can use the new sentence design. It's the settings option "Display sentences with the new design...".

To edit the language in the new sentence design, you don't click on the flag but you click on the Edit button, then select the language in dropdown, then save.

![image](https://user-images.githubusercontent.com/221850/125174551-705f4c80-e1c6-11eb-823f-4d37c96bda0b.png)

![image](https://user-images.githubusercontent.com/221850/125174559-76edc400-e1c6-11eb-9627-59864e6b792f.png)

Please try and let me know if you manage to set the language to unknown.

**Comment by sikmir** [comment]
That workaround works for me, thanks!

**Comment by alanfgh** [comment]
@trang, it takes a few back-and-forth operations to get "other language" to go into effect, whereas setting it to a language that's in my profile goes into effect immediately. Also, I plan to edit the wiki to refer only to "other language", not to "unknown", which I was looking for in the list of languages. (I think it used to be there.)
