### ISSUE TITLE
Audio File Import Problem - Duplicate Entries on tatoeba.org/en/audio/index

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2833]
When I imported some audio files, I got an error message, saying that a number of the files had been successfully imported, but not removed from the directory that I upload them to.

I clicked the import button again, and got a message saying 0 files had been imported.

Now on this page, it shows the text of a number of the sentences twice.

https://tatoeba.org/en/audio/index

<img width="948" alt="Screen Shot 2021-08-26 at 16 19 30" src="https://user-images.githubusercontent.com/7934273/130919380-37e33453-6f61-4087-8e3d-acb38673e756.png">

**Comment by ckjpn** [comment]
The sentence text is duplicated here, too.

> こんにちは。暑いですね？
> 
> と、バグなのか、音声を録音する時の問題なのかよく分からないんだけど、次の画面を見ると、同じ文が２行できてます。
> 
> https://tatoeba.org/ja/audio/of/CK?page=6
> https://tatoeba.org/ja/audio/of/CK?page=7
> 
> どうしてだろう？

<img width="725" alt="Screen Shot 2021-08-28 at 16 46 47" src="https://user-images.githubusercontent.com/7934273/131210725-66a75b70-660d-4ea0-8416-031dd9e570a5.png">

**Comment by ckjpn** [comment]
I'll close this other one.  I think it's the same problem.

https://github.com/Tatoeba/tatoeba2/issues/2863

Also, this happened again today.  Notice that a couple of the sentences seem to only be listed once, though.

<img width="864" alt="Screen Shot 2021-12-22 at 15 31 34" src="https://user-images.githubusercontent.com/7934273/147046921-53948e6f-6b30-4edd-9bba-e53edd3817c6.png">

**Comment by ckjpn** [comment]
This happened again today.
(About 05:15 Saturday, December 25, 2021)

This is the top of a screenshot of the error message on the import results page.
Note that the import was actually successful, even though the error message seems to indicate that it wasn't.
I imported fewer than 100 audio files at this time.  (I think it was 96 files.)  I've imported many more at one time with no problem in the past.

<img width="753" alt="Screen Shot 2021-12-25 at 14 14 14" src="https://user-images.githubusercontent.com/7934273/147378029-6a0bed47-a35f-4652-95c1-99869c9b0638.png">

This is the screenshot of the "browse audio" page after the import.
https://tatoeba.org/en/audio/index

<img width="1000" alt="Screen Shot 2021-12-25 at 14 15 49" src="https://user-images.githubusercontent.com/7934273/147378025-12495b01-65c2-4327-b203-73701913bc49.png">

**Comment by ckjpn** [comment]
Related:  
audio list has double entries - https://tatoeba.org/eng/audio/index #1856
I'll close the older one.

**Comment by ckjpn** [comment]
Perhaps this is a related problem.
The exported files had 556 duplicate lines in the exported data on 2021-12-25 (sentences_with_audio.csv).

Attached is a list of sentence ID numbers.  Most are CK's audio files. Some are Inego's audio files.

[more-than-one-entry-on-audio-list 2021-12-25.txt](https://github.com/Tatoeba/tatoeba2/files/7776475/more-than-one-entry-on-audio-list.2021-12-25.txt)

**Comment by ckjpn** [comment]
This happened to me again this today.  I got a similar error message as above, and then when looking through the https://tatoeba.org/en/audio/index page, I noticed some duplications.

<img width="962" alt="Screen Shot 2022-01-13 at 10 18 49" src="https://user-images.githubusercontent.com/7934273/149248943-00d328e8-528f-4183-bc61-1f26838256f6.png">

**Comment by ckjpn** [comment]
This is just a quick not to let you know that this happened again today at about...
07:00
Thursday, March 17, 2022
Coordinated Universal Time (UTC)

**Comment by ckjpn** [comment]
Before I do the next import, I thought you might want to see the top of the page showing several of these duplicates.  There were about 50, I think, in that import.  Perhaps knowing this will help you trace the problem in the logs.

Screen Shot 2022-03-17 at 15.58.44 (Japan Time - GMT+9)

<img width="1016" alt="Screen Shot 2022-03-17 at 15 58 44" src="https://user-images.githubusercontent.com/7934273/158909596-6e2423ed-f043-43e8-b158-c55ac487600b.png">

**Comment by jiru** [comment]
Logged error was: Warning (2): unlink(/var/www-audio/import/7170909.mp3): No such file or 
directory in [/var/www-prod-cd617b13d38fccc1b2c095381a9813f33d4eb652/src/Model/Table/AudiosTable.php,
 line 282]

So it says the file could not be removed from the import directory because it is already gone. Giving that you mentioned duplicate entries, my guess is that you somehow ran two imports simultaneously (or at overlapping times). I imagine this could happen if you click the import button twice or restart it after a timeout error or something like that. @ckjpn Of course, the import code should handle that case gracefully, but could you confirm that something like that happened?

**Comment by jiru** [comment]
Checking the database, I am seeing 509 duplicates by CK, 93 by Inego and 1 by Tatjana. I assume these users are only contributing one audio per sentence, so I can remove all these duplicates. @ckjpn Can you confirm?

**Comment by jiru** [comment]
Problem should be solved with the new import code as only a single audio import can be proceeded at the same time. Once the new code is on production, we can clean duplicate audio entries by running the following query:

```sql
delete from audios where id in (select max(id) from audios group by sentence_id, user_id having count(*) > 1);
```

**Comment by trang** [comment]
Just for the record, here's the list of duplicate audio deleted: https://gist.github.com/trang/251f89e7406d9a112e2ed271bd4a6139
