### ISSUE TITLE
In titles, capital Umlaut Letters are cut off on top

### ISSUE THREAD

**Issue by sebcoh** [Tatoeba/tatoeba2#2835]
Capital umlauts like ÄÖÜ are cut off for a selected sentence, you can barely see a shadow of the dots. See the following screenshot (I added the ÄÖ Umlauts using the inspector).
![Screenshot 2021-08-28 at 20 57 25](https://user-images.githubusercontent.com/35079848/131228211-417c1077-e7be-4347-87a6-148d0c916ef6.png)

Link to a sentence where I can see the issue: https://tatoeba.org/en/sentences/show/10261261
mac OS Catalina 10.15.5
Firefox 86.0
According to the inspector, used font is Helvetica size 24, weight 400; line height and spacing both at "normal".

**Comment by trang** [comment]
@sebcoh Thanks for reporting this. I believe this is the same issue as reported in #1665 and in https://tatoeba.org/fra/wall/show_message/29594#message_29594.

In short: depending on the font that is used, the umlaut may or may not be displayed. With Helvetica, it's not displayed correctly. 

But I think this would be an issue only with the old sentence design. Just to make sure, could you post a screenshot of the sentence with the new sentence design? You can activate the new design from the [Settings](https://tatoeba.org/en/user/settings) (it's the last option in the list: "Display sentences with the new design..."). Or you can just log out temporarily, as non-authenticated users are only shown sentences with the new sentence design.
