### ISSUE TITLE
Can't search sentences in Santali

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2843]
I've just added Santali (#2831) and ran the indexation but when checking the indices, I noticed the text_len is 0.

```
# echo "select id,text_len from ${idx}_main_index,${idx}_delta_index limit 10;" | mysql -P9306 --protocol=tcp
id      text_len
10257295        0
10257296        0
10257297        0
10257298        0
10257323        0
10257327        0
10257328        0
10263758        0
10263759        0
10263761        0
```

I then tried to search a couple of sentences in Santali but it would return 0 results.

I suppose we need to update the charset table: https://github.com/Tatoeba/tatoeba2/blob/dev/src/Shell/SphinxConfShell.php#L75

**Comment by Yorwba** [comment]
I'll have a look.
