### ISSUE TITLE
reassign sentences with misspelled/mispunctuated tags

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#287]
For instance, reassign sentences with "@needs native check." to "@needs native check". This could be done via SQL, preferably via a script.

**Comment by agrodet** [comment]
If merging tags is a pinpoint operation, as I think it should be, I think this could be done by merging `@needs native check.` into `@needs native check`. The issue about merging is #961

**Comment by jiru** [comment]
Closing as a duplicate of #961 (which has more information already).
