### ISSUE TITLE
"Narrow search" should be changed to "Refine search"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2873]
Better wording for the "Narrow search" text displayed for the search bar when the window is narrow:

![no_x](https://user-images.githubusercontent.com/1213027/141541300-54edbac0-0d0c-4c3b-ad85-f5209898be35.png)

would be "Refine search". When you update the search criteria, you're not always making the search narrower. Sometimes you're even making it broader.

**Comment by LBeaudoux** [comment]
I agree with @alanfgh, "Refine search" seems more accurate.

To be more consistent, maybe the "Search criteria" header could also be reworded as "Refine search":

![image](https://user-images.githubusercontent.com/40287913/144709425-e4b7a11b-c780-4bb2-8f48-271b8b221f9e.png)

**Comment by profesyonal** [comment]
Is this an issue for Transifex?

**Comment by profesyonal** [comment]
Is this in Transifex? Or is there a strings file in the source code?

**Comment by Yorwba** [comment]
The original English string is stored directly in the source code. When we change a translatable string, we regenerate the `.pot` files listing all such strings. Transifex is configured to watch the GitHub repo for changes in the `.pot` files, and will then make the new string available to translate.
