### ISSUE TITLE
Sentences listed multiple times for the same tag

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2879]
**To Reproduce**
1. Visit https://tatoeba.org/en/tags/show_sentences_with_tag/5459
2. The listed sentences are 2725860, 2725861, 2725862, 2725860 and 2725862.
3. Note that 2725860 and 2725862 appear twice, although the second copy of each doesn't include translations.

Possibly related: #2833, #2849, #2863.

**Comment by Guybrush88** [comment]
I think it's a duplicate of #2170

**Comment by Yorwba** [comment]
@Guybrush88 Thank you for pointing out the duplicate.

Closing in favor of #2170 .
