### ISSUE TITLE
Hitchiti (MIK)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2881]
* Language name: Hitchiti 
* Language info: https://en.wikipedia.org/wiki/Mikasuki_language
* ISO 639-3 code: MIK
* Public List: https://tatoeba.org/en/sentences_lists/show/169875
* Icon: https://imgur.com/a/ajEC9rw
* Requested by: https://tatoeba.org/en/user/profile/eeyinn

**Comment by trang** [comment]
The reason why we use the name "Hitchiti" and not "Mikasuki" is upon suggestion from the requester of this language:
> The ISO code, MIK, is for both languages. However, tribal politics allow for the Oklahoman Hitchiti language to be written down but the Floridian Mikasuki dialect may not be written, for Florida Indian tradition forbids it. For this reason I ask that the name "Mikasuki" not show up on the site’s interface, but "Hitchiti" take its place instead. This would also fit the Hitchiti orthography, grammar, and pronunciation that I will be writing in.

**Comment by trang** [comment]
Additionally, the requester provided the following explanation for the chosen flag:

> It's the flag of the short-lived State of Muscogee which Florida was proposed to be before the Seminole wars commenced. In this state, the official languages were English, Spanish, Hitchiti and Muscogee (the last of which has its own tribe / tribal symbolism and is supported on Tatoeba).
The Hitchiti are only a band within the tribe and don't have anything resembling a flag or unique symbol. This is the closest I could think of.
