### ISSUE TITLE
An internal error occurs whenever I want to search for a word

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2888]
**To Reproduce**
1. Search for any word in the top bar field (the selected language doesn't matter to trigger the error)
2. Click on the lens icon or press Enter;
3. See error after a few seconds
**Example:**
*1. Put 'thanks' in the top bar search field*
*2. Choose English or the 'any language' in the language option field*
*3. Click on the lens icon or press enter.*
*4. The internal error appears.*

**Expected behavior**

The user should see all the sentences contanining "thanks" after his/her query.

**Additional information (if relevant)**
- O.S.: Windows 10
- Browser: Fireforx 95.0.2 (64 bit)

**Comment by trang** [comment]
@Guybrush88 Perhaps it was a temporary error? I cannot reproduce.

**Comment by Guybrush88** [comment]
on my side, I still get the issue with the steps mentioned earlier

**Comment by trang** [comment]
This seems to be a problem only with the old design. There may be something in the results for "thanks" that takes too long to process with the old design.

Error logs:
```
2021-12-28 14:46:21 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [/var/www-prod-3e5196721f1f54e3dc64ab8f145b4c15b79b1a68/vendor/cakephp/cakephp/src/Utility/Hash.php, line 774]
Request URL: /en/sentences/search?from=eng&query=thanks&to=
Referer URL: https://tatoeba.org/en/user/settings
```

The error doesn't happen for all the search. For instance, I tried to search for "community" and it worked.

@Guybrush88 Do you confirm that if you activate the new design, you do not get any internal error?

**Comment by Guybrush88** [comment]
I confirm this happens only with the old design. The new design works fine

**Comment by ckjpn** [comment]
When this happens to me, if I change my setting to show from 100 sentences down to 50 sentences, the problem usually goes away.

**Comment by trang** [comment]
This issue here happened with 10 sentences per page when I tried it.

**Comment by jiru** [comment]
It looks like this is a regression introduced by ceb99d9fdf7ae5cee1af2bd7470e196d04cb3f4b. I am not sure why, but the rendering of view cells uses quite a lot of CPU, and we render one cell for every sentence not having an audio (for the contribute-audio wiki article). We could cache the cell.
