### ISSUE TITLE
new ISO 639-3 code Toki Pona

### ISSUE THREAD

**Issue by Rajzin** [Tatoeba/tatoeba2#2898]
Toki Pona has the ISO 639-3 code `tok` as of this month. Source: https://iso639-3.sil.org/code/tok
You'll probably want to update the site and database to reflect this.

Also remove Toki Pona from the language exceptions page in the wiki:
https://en.wiki.tatoeba.org/articles/show/tatoeba-supported-languages-exceptions

**Comment by ckjpn** [comment]
Note that we have audio files for this language, which will probably mean that you'll also need to rename a directory.
