### ISSUE TITLE
Small screens

### ISSUE THREAD

**Issue by octavo** [Tatoeba/tatoeba2#2903]
Make it possible to contribute on small screens (a responsive/mobile site or phone app).

**Comment by Yorwba** [comment]
There's already a [project to implement a responsive UI](https://github.com/Tatoeba/tatoeba2/projects/3).

So the good news is that we're working on it. The bad news is that it's been a few years and only some parts of the site are responsive.

You can slightly improve things by going to your settings and enabling the experimental new design.

E.g. this is what the old design looks like in Firefox for Android on my phone:
<img src="https://user-images.githubusercontent.com/6555947/153663488-90abfb76-6b1e-40f9-9fcd-c7b2d385be52.png" alt="old design" height="400">
And this is the new design:
<img src="https://user-images.githubusercontent.com/6555947/153663662-65c816a7-fb1e-4fa8-a8f6-13bd4de99153.png" alt="new design" height="400">

Better, right?

If there's some specific page you want to use that doesn't work well on mobile even with the new design, we might be able to prioritize it if you tell us about it in more detail.

**Comment by octavo** [comment]
@Yorwba The random sentence page.

**Comment by ckjpn** [comment]
It would be nice to be able to easily use the fully-functioning, non-experimental version on a smaller screen.

Perhaps, it's time to prioritize finishing the creation of a mobile-friendly website.
