### ISSUE TITLE
Enable Toki Pona (tok) on Transifex

### ISSUE THREAD

**Issue by RobinvanderVliet** [Tatoeba/tatoeba2#2905]
Recently Toki Pona got the ISO code `tok`. There is already a pull request created for changing changing the code used on Tatoeba (#2900).

It would be nice to have the interface in Toki Pona as well. Transifex recently started supporting Toki Pona.

**Comment by trang** [comment]
@RobinvanderVliet Do you confirm that the name of the language in Toki Pona is "toki pona"?

**Comment by RobinvanderVliet** [comment]
> @RobinvanderVliet Do you confirm that the name of the language in Toki Pona is "toki pona"?

Yes, the correct name is "toki pona". All words, except proper adjectives, are written without capital letters. Not even the start of sentences are capitalized.

**Comment by trang** [comment]
@RobinvanderVliet Toki Pona is activated on the [dev website](https://dev.tatoeba.org/) 🙂 

Once the language has enough translations (like at least 50% translated), then we can activate it on the main website. The most important would be to make sure that the homepage, the registration, the login are fully translated.
