### ISSUE TITLE
Add text-to-speech when native audio isn't available

### ISSUE THREAD

**Issue by mreichhoff** [Tatoeba/tatoeba2#2907]
**Context**
The native speaker audio is great, but it's not present on all the sentences. [Modern browser APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) allow for text-to-speech that could perhaps be used as a fallback when native audio isn't available.

**Idea**
For sentences without recorded audio, the audio button could be enabled when the user's browser has support for the target language, with a tooltip warning about it being synthetic audio.

**Comment by ckjpn** [comment]
If I remember correctly, I bought this up this possibility once with TRANG and she didn't like the idea.

Here are a couple of things to consider.

* TTS doesn't always pronounce words correctly, and doesn't always get the intonation and rhythm of speech right.
* When you hear something spoken by a near-native-sounding TTS voice, it sort of gives you the sense that the sentence is correct and natural-sounding. This could lead people using the data into believing that it is better than it is.

**Comment by mreichhoff** [comment]
I certainly agree that it's suboptimal compared to actual native pronunciation, but I think I'd contend that it's better than nothing (and likely to continue improving over time). Something like a tooltip noting it's synthetic seems like it'd be sufficient to avoid misunderstandings.

With that said, if it's already been considered and rejected, that's totally fine by me and we can close this. I just saw it [sort of come up in a reddit thread](https://www.reddit.com/r/languagelearning/comments/swqxn5/how_do_you_learn_vocabulary_with_context/hxpmsrr/?context=3) and figured I'd check and see :-)

P.S. thanks for all you do with Tatoeba, it's a great resource!

**Comment by ckjpn** [comment]
You can try some Tatoeba Corpus sentences with TTS here.

English - German Pairs
http://www.manythings.org/bilingual/deu/3428t.html

Or find other language pairs here.
http://www.manythings.org/bilingual/

**Comment by mreichhoff** [comment]
Yeah, I make use of it in a couple of prototypes as well and have found it reasonably useful. Thanks for the links!
