### ISSUE TITLE
Only list creator can add sentences to it despite setting

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2924]
**To Reproduce**

1. Log in as user A.
2. Create a new list. We’ll call it list A.
3. Under the list options, set "Who can add/remove sentences" to "Anyone"
4. Log out.
5. Log in as user B.
6. Go to the page of list A.
7. Problem: I cannot add sentences to list A.

**Expected behavior**

As user B, I should be able to add new sentences to list A, as specified by the setting.

**Comment by soliloquist-tatoeba** [comment]
I have a collaborative list with public visibility level for proofreading. It's meant to be shrinking (checked sentences are being removed), but I recently noticed someone regularlay adding irrelevant sentences in different languages to it. I once removed some one hundred such sentences and renamed the list to make its purpose clearer, but irrelevant sentences keep being added. Adding seems to work properly at least for lists with public and listed visibility levels.

I created [another issue](https://github.com/Tatoeba/tatoeba2/issues/2936) about this vulnerability.
