### ISSUE TITLE
sentences_with_audio.tar.bz2 export does not include the audio id

### ISSUE THREAD

**Issue by Vuizur** [Tatoeba/tatoeba2#2945]
I downloaded the sentences_with_audio file in order to dynamically download some sentences. The TSV file I get does differ from what the documentation says, however, and does not seem to include the audio id (excerpt from the file):
```
10857650	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
10857651	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
10857707	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
10858050	CK	CC BY-NC-ND 3.0	http://www.manythings.org/tatoeba
```

The first entry seems to be the sentence id, but then there seems to be no way to download the recording. (Creating URLS with the sentence ID does not seem to work)

PS: I love the Tatoeba project, great work!

**Comment by jiru** [comment]
Thank you for the kind words. 🙂

You are correct about the export file. The problem will be fixed on the next export this Saturday. Please be patient.

**Comment by jiru** [comment]
In the mean time, you can download the audio files by sentence ID using the pattern:

    https://audio.tatoeba.org/sentences/<lang>/<sentence-id>.mp3

For instance:

https://audio.tatoeba.org/sentences/eng/10857650.mp3

**Comment by Vuizur** [comment]
Awesome, thank you!

**Comment by trang** [comment]
The audio ID appears in the latest export so I'm closing this :)
