### ISSUE TITLE
Create an all_sentences_with_audio.tar.bz2, or put all sentences with audio in sentences_with_audio.tar.bz2 .

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2955]
Since https://downloads.tatoeba.org/exports/sentences_with_audio.tar.bz2 no longer has all sentences with audio, could you please create another file each week that is similar to this, but that includes all sentences with audio files?

Maybe you could call it all_sentences_with_audio.tar.bz2, Or, perhaps you could just include all sentences with audio like the file used to be.

In addition to what I need, sharptoothed's page relies on this information.

https://tatoeba.j-langtools.com/userchart/chart2.php

**Comment by jiru** [comment]
Next Saturday’s export will include all sentences with audio, like it used to be.

**Comment by trang** [comment]
@ckjpn Did the audio get uploaded after all? I'm not seeing any audio to import on https://tatoeba.org/en/audio/import. 

FYI there's been a Tatoeba update today that impacts audio uploads among other things (#2929). When I deployed the changes, there was some issues at first that I didn't notice right away. I needed to run some database migration but wasn't aware. I found out later on and fixed the issues. Perhaps you tried to upload the audio files while it was not fixed yet.

**Comment by ckjpn** [comment]
Why does it take a very long time sometimes and not so long other times?

Here is the one I'm waiting on now.
I notice that I have to be careful to make sure one import is done before
starting another one by a different "author."  Otherwise, files get
uploaded with the wrong username assigned.

Import recordingsAudio import status

Import task enqueued 15 minutes ago. Please refresh the page in a little
while to check if import is completed.
Files detected

A total of 22 files have been detected inside the import directory.
File nameSentence idLanguageExisting audioMay be imported
10903652.mp3 10903652 <https://tatoeba.org/en/sentences/show/10903652>
English None Yes
10902100.mp3 10902100 <https://tatoeba.org/en/sentences/show/10902100>
English None Yes
10908305.mp3 10908305 <https://tatoeba.org/en/sentences/show/10908305>
English None Yes
10908676.mp3 10908676 <https://tatoeba.org/en/sentences/show/10908676>
English None Yes
10910106.mp3 10910106 <https://tatoeba.org/en/sentences/show/10910106>
English None Yes
10910185.mp3 10910185 <https://tatoeba.org/en/sentences/show/10910185>
English None Yes
10903650.mp3 10903650 <https://tatoeba.org/en/sentences/show/10903650>
English None Yes
10910189.mp3 10910189 <https://tatoeba.org/en/sentences/show/10910189>
English None Yes
10903644.mp3 10903644 <https://tatoeba.org/en/sentences/show/10903644>
English None Yes
10900143.mp3 10900143 <https://tatoeba.org/en/sentences/show/10900143>
English None Yes
10903624.mp3 10903624 <https://tatoeba.org/en/sentences/show/10903624>
English None Yes
10903628.mp3 10903628 <https://tatoeba.org/en/sentences/show/10903628>
English None Yes
10903338.mp3 10903338 <https://tatoeba.org/en/sentences/show/10903338>
English None Yes
10903635.mp3 10903635 <https://tatoeba.org/en/sentences/show/10903635>
English None Yes
10903642.mp3 10903642 <https://tatoeba.org/en/sentences/show/10903642>
English None Yes
10903651.mp3 10903651 <https://tatoeba.org/en/sentences/show/10903651>
English None Yes
10908678.mp3 10908678 <https://tatoeba.org/en/sentences/show/10908678>
English None Yes
10903666.mp3 10903666 <https://tatoeba.org/en/sentences/show/10903666>
English None Yes
10935416.mp3 10935416 <https://tatoeba.org/en/sentences/show/10935416>
English None Yes
10903654.mp3 10903654 <https://tatoeba.org/en/sentences/show/10903654>
English None Yes
10910141.mp3 10910141 <https://tatoeba.org/en/sentences/show/10910141>
English None Yes
10903618.mp3 10903618 <https://tatoeba.org/en/sentences/show/10903618>
English None Yes

**Comment by trang** [comment]
@ckjpn There could be something still misconfigured. I will look into it later.

**Comment by trang** [comment]
@ckjpn It should no longer take several minutes to upload audio. The cause is explained in #2965. If you still experience issues with audio taking several minutes to upload, please report them in #2965.

**Comment by ckjpn** [comment]
Perhaps these took 6 minutes (3+3) to upload.


Last import report (completed on June 22, 2022 at 10:00:02 PM UTC)
A total of 2 recordings have been imported.
2 were English.
