### ISSUE TITLE
Audio IDs are missing in monolingual exports of sentences with audio

### ISSUE THREAD

**Issue by LBeaudoux** [Tatoeba/tatoeba2#2956]
Following the multi-audio update, an audio ID has been added to the `sentences_with_audio.csv` weekly export. However, this extra column is still missing in the [monolingual exports](https://downloads.tatoeba.org/exports/per_language/).

I plan to modify [export.sh](https://github.com/Tatoeba/tatoeba2/blob/dev/docs/cron/export.sh) to reflect this change.

**Comment by LBeaudoux** [comment]
Surprisingly, the audio ID column still does not appear in this week's monolingual exports.

**Comment by trang** [comment]
Indeed. That's because the cron job was reading from the old version of the `export.sh`. I'm going to re-run the export script.

**Comment by trang** [comment]
@LBeaudoux The audio ID should be here now. Do you confirm?

**Comment by LBeaudoux** [comment]
@trang It looks OK now. Thank you for acting so quickly 😃
