### ISSUE TITLE
Make it possible to easily replace audio files when importing files when by the same "Audio Author."

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2966]
## The Requested Feature

As I'm importing audio files, I would like to see the option to replace existing audio files when such files are by the same "Audio Author."

## Ways This Could Be Done

This could either be done by deleting the old MP3 file and the old "download" ID and then adding the replacement as a new audio file with a new "download" ID, or this could be done by replacing the existing file on the server with the new file.

## Additional Thoughts

I think that the default setting should be to have "replace if by same author" as the default, with the option to turn off this default.

This could be done by having a **checked** checkbox option when there is an item in the "Existing audio" column.

CHECKED: Replace if by the same author

Or, it could be done by having an **unchecked** checkbox.

UNCHECKED: Don't replace same author's file

I think the first **checked** version is better.

As the files are being imported, the username in the "Audio Author" input would need to be compared to the existing audio usernames.  This would be important, since there will be times when there are multiple existing audio files by multiple usernames.
We wouldn't want one person's audio file replacing another person's audio file.

## Screenshot

<img width="1152" alt="replace-if-same-author" src="https://user-images.githubusercontent.com/7934273/176793762-7247f7cb-62a0-4238-88c1-0378f3d1bc2b.png">

## Additional Note

It would be possible to eliminate the "may be imported" column.  There is always an "invalid file" alert in the first column when there isn't a "yes" in the "may be imported" column.

This might help make room for this new feature.

Perhaps you could even rename that column to "**If by same author, ..**."
and change the checkbox text to just the one word "replace".

That would be easy enough for me to understand, and perhaps for others who may use this import audio page in the future.

**Comment by ckjpn** [comment]
Additionally, a "check / uncheck all" would likely be useful, too.

**Comment by ckjpn** [comment]
If this could be done soon, it would help me easily re-upload a number of the earlier Common Voice audio files, after normalizing the volume, using MP3gain.

**Comment by jiru** [comment]
@ckjpn I implemented this pretty much the way you suggested. It works by replacing the audio file and updating the internal "last modified" date of the audio.

When "Replace" is checked:
- if the given author has no audio on that sentence, it adds a new audio
- if the given author has one audio on that sentence, it replaces the audio
- if the given author has more than one audio on that sentence, it does not do anything and shows an error in the report

![image](https://github.com/Tatoeba/tatoeba2/assets/5107734/8816906b-7d3f-4b6b-b752-28069ad06938)

**Comment by jiru** [comment]
@ckjpn This is now available on https://tatoeba.org.
