### ISSUE TITLE
Cannot edit sentence text

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2974]
**To Reproduce**
1. Log in as admin or advanced contributor
1. Go to https://tatoeba.org/en/sentences/show/700648
2. Disable the one audio recording
3. Try to edit the sentence text

**Expected behavior**
The admin should be able to edit the sentence text.

**Additional information**
Reported by @alanfgh.
This bug could be related to audio, and it could be related to #2947, but it could as well be a totally different bug.

**Comment by ckjpn** [comment]
Related, or duplicate.

https://github.com/Tatoeba/tatoeba2/issues/2947

**Comment by ckjpn** [comment]
Notice in step 3 above, that though the audio recording appears to be disabled, if you reload the page, you'll notice that it wasn't actually disabled. This is the same as what was reported in #2947.

TRANG, if this problem isn't going to be resolved soon, may I make the correction the same way I did for the sentence reported in #2947?

**Comment by trang** [comment]
I confirm it's the same issue as #2947. I will close this one.
