### ISSUE TITLE
Downloading Problem

### ISSUE THREAD

**Issue by ShadowVicky** [Tatoeba/tatoeba2#3000]
How can we download your English-Assamesn Dataset. We can't download it from your website. Pls Help us.

**Comment by DJ-Saidez** [comment]
I don't know why the download is not working for you, but it worked for me.

In the meantime, I uploaded it to my Google Drive so you can try download from there.
https://drive.google.com/file/d/1GoZsh9DyKRRLj1FAFwVCMmzbYFHwjTQZ/view?usp=sharing

Can you tell us what kind of error you're getting that it's not letting you download?

**Comment by ShadowVicky** [comment]
We are able to see some sample translation upload by different members . But we can't see any link where we can download the whole dataset.

**Comment by DJ-Saidez** [comment]
https://tatoeba.org/en/downloads
When you go to this link you don't see these screens?

<img width="864" alt="Screen Shot 2022-10-17 at 12 23 06 AM" src="https://user-images.githubusercontent.com/70669145/196113869-12e21d6d-bd6c-4486-909c-b11b46de8ede.png">

<img width="864" alt="Screen Shot 2022-10-17 at 12 23 23 AM" src="https://user-images.githubusercontent.com/70669145/196113982-d67e3de1-27fd-4ef7-bc51-660bd932dce2.png">

When you click on "download sentence pairs" it should work


What do you want to do with the data? Maybe you just have to reformat it differently once you download it for it to work for you.

**Comment by ShadowVicky** [comment]
Okay. Now Its work. Thank you @DJ-Saidez

**Comment by DJ-Saidez** [comment]
No problem!

I don't know if any of the programmers want to look into this or not as a possible bug, but I'll let them decide whether to close this now.

**Comment by trang** [comment]
@ShadowVicky Was the problem that you could not find the Downloads page because the link to access it is maybe too hidden? Or was there actually bug on the Downloads page that prevented you from downloading the dataset?
