### ISSUE TITLE
Unexpected opening of SignIn ‘Suggest User/Password’ on iOS

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#3004]
This one has been ‘bugging’ me for years now.

Opening the ‘List of all members’ automatically invokes the SignIn Username/Password suggestion box on iOS.

https://user-images.githubusercontent.com/725445/197865350-675b1bbf-3929-4742-8ab9-a9cae27c350d.mov

**Comment by vinkaks** [comment]
Seems your browser is attempting to autofill the search because it has the name `username`. It seems to be primarily a browser/OS issue. 

I can however make a few changes to the `username` input on our end to prevent it, if it's determined there is enough need to do so.

**Comment by mramosch** [comment]
This is Safari (on all Apple iDevices).

**Comment by Guybrush88** [comment]
I experience this issue also with Firefox under both Windows (10 and 11) and Ubuntu 22.04

**Comment by vinkaks** [comment]
@mramosch We updated Tatoeba. Please check and confirm the fix is working or not on safari. Thank you
