### ISSUE TITLE
Can't edit transcription on sentences with audio

### ISSUE THREAD

**Issue by DJ-Saidez** [Tatoeba/tatoeba2#3006]
1. Go to https://tatoeba.org/en/sentences/show/11211585 which is a Japanese sentence with audio. The software-generated transcription is incorrect (おひゃくどせき should be おひゃくどいし), and I want to change it.

<img width="400" alt="Screen Shot 2022-10-28 at 8 02 50 PM" src="https://user-images.githubusercontent.com/70669145/198793568-a165284b-9e45-4701-a14b-8fb6d9d6bd5d.png">

2. Click on the pencil icon to edit the transcription.

<img width="400" alt="Screen Shot 2022-10-28 at 8 03 12 PM" src="https://user-images.githubusercontent.com/70669145/198793723-79ff7ef9-d7a6-46fa-b5f2-fcf6c812a341.png">

3. See error

Normally, when I click on the pencil icon, I'm able to edit or confirm the transcription (which doesn't affect the actual sentence text), even though I don't own the sentence. The fact that it has audio, logistically, shouldn't affect its ability to be modified to match the audio better.

I'm using Google Chrome on Mac 12.4.

**Comment by DJ-Saidez** [comment]
Update: The example sentence was edited by a corpus maintainer.

To see the error again, try this sentence https://tatoeba.org/en/sentences/show/11211978

**Comment by vinkaks** [comment]
I think only edits to the original sentence should be disabled once audio is added. Transcripts should still be editable for such use cases as yours.

I think we can just disable the sentence input. Using something like `ng-disabled` and otherwise let the form work. Will do a PR with a fix
