### ISSUE TITLE
When tag is deleted, remove it from the autocompletion table

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#301]
According to sysko, there's an API call for when a tag is added, but none for when a tag is deleted. This probably requires a fix on both the tatoeba2 and the suggestd side.

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24194#message_24194)

**Comment by trang** [comment]
Note: restarting suggestd will update the autocompletion table.
`sudo /etc/init.d/suggestd restart`

**Comment by RyckRichards** [comment]
Still can experience this.

Step 1- choose a tag and remove it from all sentences
tag Slavs

http://dev.tatoeba.org/eng/tags/show_sentences_with_tag/40

http://prntscr.com/ecyypg


tag removed

http://prntscr.com/ecyyyx

this message was displayed after I removed "Slavs" from all sentences:
> 'Notice (8): Undefined index: Tag [APP/Model/Tag.php, line 273]"

step 2- going to tag a sentence as "Slavs". The autocompletition shouldn't suggest it. 

http://prntscr.com/ecz00b

**Comment by jiru** [comment]
Setting effort:medium because this needs a rework of how tags are removed from the table `tags` when the sentence count reaches zero. Currently, this is done by a trigger in `docs/database/triggers/maintain_tags_number_of_sentences.sql`, which prevents us from running anything else than SQL code upon tag removal.

**Comment by jiru** [comment]
This is not a problem any more since suggestd was replaced by a new implementation in #2331.
