### ISSUE TITLE
"Browse audio" not functioning, or functioning very slowly

### ISSUE THREAD

**Issue by DJ-Saidez** [Tatoeba/tatoeba2#3010]
Problem was brought up through PM by carlosaraujo, who wanted to use English audio. He complained twice on the Wall, of Tatoeba crashing for him, which then I asked him for elaboration.

**To Reproduce**
The "Browse" dropdown menu has an option at the bottom "Browse audio", which links you to [](https://tatoeba.org/en/audio/index), which pops up a "Tatoeba is currently unavailable" error message.

As I was typing this issue, under the impression that it wasn't working at all and that maybe it's from an obsolete/broken section of code, the "browse audio" menu loaded for me, but despite my good internet connection, it took a long time to load, and when I tried going to page 2, it gave me the "Tatoeba is currently unavailable" error again.
Maybe it has to do with the sheer amount of audio files the system has to retrieve. But the link is unreliable to access the menu now without optimization.
Since most of the time it's not even working, I added both labels.

**Comment by ckjpn** [comment]
I think this is a duplicate of https://github.com/Tatoeba/tatoeba2/issues/2946

**Comment by DJ-Saidez** [comment]
Seems to be so. Forgot to check if a previous mention was already made. Still figured a re-mention is worth.
Thanks, closed as a duplicate.
