### ISSUE TITLE
Text under the title in lists is green

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#3016]
As reported by hecko on the Wall:

> is it just me or are collaborative lists kinda broken? e.g. here https://tatoeba.org/en/sentences_lists/show/169834 everything is a green link 

https://tatoeba.org/it/wall/show_message/39218#!#message_39218

**To Reproduce**
1. Go to the list https://tatoeba.org/en/sentences_lists/show/169834 or https://tatoeba.org/it/sentences_lists/show/170787 (I checked these two lists)
2. See error. Each line of text under the list title is green, and there's a big parenthesis just under the title.

**Expected behavior**
The text under the title should be black.

**Screenshots (if applicable)**
![Immagine 2022-11-18 225438](https://user-images.githubusercontent.com/1702194/202809738-02fd44f2-a39f-439c-9286-22c4f9e783ab.png)

**Additional information (if relevant)**

I checked this bug using Windows 11 and Firefox 107.0

**Comment by ckjpn** [comment]
Same bug:

https://github.com/Tatoeba/tatoeba2/issues/2994

**Comment by Guybrush88** [comment]
I'm closing this one, since it's a duplicate
