### ISSUE TITLE
Have Tatominer look for words instead of strings

### ISSUE THREAD

**Issue by CangarejoAsul** [Tatoeba/tatoeba2#3017]
Currently, Tatominer looks for strings in Tatoeba sentences instead of words. That means that, for example, the not-so-common word "ether" will never be listed, because it's a substring of "whether", which is very common. Maybe Tatominer could be specialized in the case of the English language to look for words instead of strings.

**Comment by LBeaudoux** [comment]
To imitate Tatoeba's search results, Tatominer for English is not simply based on string matching but on [stemming](https://snowballstem.org).

I agree it would be interesting to analyze the English corpus more finely by using a [lemmatizer](https://en.wikipedia.org/wiki/Lemmatisation) and setting more constraints on sentence length, diversity, and readability. But this would be in a project other than Tatominer.

**Comment by CangarejoAsul** [comment]
Oh... I didn’t know that. Thanks anyway.
