### ISSUE TITLE
Advanced search isn't working

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#3019]
**To Reproduce**
1. Go to the advanced search page
2. Search for "=dog", set English as language, exclude sentences in Italian, and filter sentences by showing first the shortest sentences
3. See error

This is the resulting URL: https://tatoeba.org/it/sentences/search?from=eng&has_audio=&native=&orphans=no&query=%22%3Ddog%22&sort=words&sort_reverse=&tags=&to=&trans_filter=exclude&trans_has_audio=&trans_link=&trans_orphan=&trans_to=ita&trans_unapproved=&trans_user=&unapproved=no&user=

I got also this error number: 6394492e7ad33

**Expected behavior**
I should be able to see the proper sentences with these criteria.

**Comment by Yorwba** [comment]
We had an outage running out of disk space and the search engine was broken.

Since the search you linked to works now, I'll close this.

**Comment by jiru** [comment]
Thanks for reporting it to us, Guybrush.
