### ISSUE TITLE
Exclude multiple users from search

### ISSUE THREAD

**Issue by CangarejoAsul** [Tatoeba/tatoeba2#3021]
Currently, it’s possible to exclude a single user from the search results. If it were possible to exclude more than just one user at the same time, then Tatoeba wouldn’t have some users complaining about some other users’ sentences and everyone could just keep on adding the kind of sentences they want to add.

Personally, I wouldn’t be using this feature, because I don’t usually translate sentences from Tatoeba, but, taking into account a [recent discussion](https://tatoeba.org/en/wall/show_message/39152#!#message_39152) on the Wall, I think Tatoeba maybe needs this.

**Comment by vinkaks** [comment]
@CangarejoAsul can you share the link to the wall post.

**Comment by ckjpn** [comment]
See this issue.

https://github.com/Tatoeba/tatoeba2/issues/2008
