### ISSUE TITLE
Search for sentences within a length interval

### ISSUE THREAD

**Issue by CangarejoAsul** [Tatoeba/tatoeba2#3023]
There are [users that prefer longer sentences](https://tatoeba.org/sentences/search?sort=words&sort_reverse=yes&user=nonong) and [users that prefer shorter sentences](https://tatoeba.org/wall/show_message/39305). Maybe it would be useful to be able to filter search results by minimum and maximum number of words.

**Comment by ckjpn** [comment]
Related:
https://github.com/Tatoeba/tatoeba2/issues/1954

**Comment by CangarejoAsul** [comment]
Duplicate.
