### ISSUE TITLE
"Use the old design" setting is always checked when saving any other settings

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#3043]
**To Reproduce**
1. Go to your settings page.
2. Make sure that the last setting, "Display sentences with the old design...", is unchecked.
3. Change any setting in the first part, for example change the languages you want to display.
4. Save your settings.
5. The "Display sentences with the old design..." is checked, and active (all pages are displayed with the old design).

**Additional information (if relevant)**
- I suspect that the recent commit https://github.com/Tatoeba/tatoeba2/commit/4d7e5e1e3dde9cec0403966ab4ec830405dfba2d is responsible for this behavior. @jiru @Yorwba 
- Maybe the following part of the code should also be modified, to replace `{{useNewDesign}}` by `{{useOldDesign}}`, but I cannot check, even less open a PR, so if somebody could solve this problem quickly, it would be nice. 
https://github.com/Tatoeba/tatoeba2/blob/4d7e5e1e3dde9cec0403966ab4ec830405dfba2d/src/Template/User/settings.ctp#L337-L344
- That's a very disturbing bug, considering that I often change the list of languages in which to display translations, depending on what I'm doing.

**Comment by Yorwba** [comment]
@agrodet Sorry for that, I should have tested the change more thoroughly before deploying. It should be fixed now.

**Comment by agrodet** [comment]
Thank you for the quick fix :)
