### ISSUE TITLE
In lists, ../show/LIST_NUMBER/und redirects to /und/und and /jpn redirects to /und/jpn

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#3046]
This is not a major bug, unless it is a symptom of something else, or causes other problems.
It might be worth checking out why this is happening.

The URL we have to show all translations of a list that ended with "und" now redirects to "/und/und".
THIS:
https://tatoeba.org/en/sentences_lists/show/171243/und
TO THIS:
https://tatoeba.org/en/sentences_lists/show/171243/und/und

And this....
https://tatoeba.org/en/sentences_lists/show/171243/jpn
...now redirects to this....
https://tatoeba.org/en/sentences_lists/show/171243/und/jpn
... which doesn't seem to make much sense.

**Comment by Yorwba** [comment]
This is intentional, not a bug. [A new parameter was added to the URL to allow filtering the list by language, and URLs missing that parameter redirect to the new URL with the language set to undefined.](https://github.com/Tatoeba/tatoeba2/pull/2980#issuecomment-1221316254)

**Comment by ckjpn** [comment]
It doesn't matter to me really since the old links still work,

However, it seems strange to have the "und" repeated.
/und/und

I assume that perhaps "und" stands for "undetermined," though until now I just always thought it must be based on another language and meant "all."

So, I guess "/und/jpn" means "undetermined" and then "Japanese."

I wonder why this change was felt necessary.
