### ISSUE TITLE
List was created with no apparent username

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#3058]
This is the list: https://tatoeba.org/en/sentences_lists/show/171361
Notice that the "created by" is empty. (Or hidden.)
This has "21 hours ago" listed.

These are the (spam) accounts that were created at about the same time.  (Currently listed as 21 and 22 hours ago.)

https://tatoeba.org/en/user/profile/Davidjohn
https://tatoeba.org/en/user/profile/learningdatascience
https://tatoeba.org/en/user/profile/dhfilmacademy
https://tatoeba.org/en/user/profile/IronEagle
https://tatoeba.org/en/user/profile/sattamatka321
https://tatoeba.org/en/user/profile/intelligencevidyarth
https://tatoeba.org/en/user/profile/precanacourses
https://tatoeba.org/en/user/profile/EmmaWilliam

Since the list name sounds like it might have been created to include spam, I suspect that perhaps it may have been created by one of the above accounts.

**Comment by Yorwba** [comment]
The list was created by the spam account "betting119" with the id 114296, which was quickly deleted by an admin.

So we need to handle the case where the list creator's account was deleted. (In the sentence logs, the username is replaced by "unknown user", but there are probably some other cases where nothing is displayed.)

**Comment by ckjpn** [comment]
If I remember correctly, TRANG asked us to set such accounts to "spammer" status instead of deleting them.  I've sent a message to all the admins, so perhaps this is not something that will ever happen again and this issue can perhaps be closed.

**Comment by ckjpn** [comment]
Perhaps this won't happen again, so I'm closing this.
