### ISSUE TITLE
Custom Exports - Sentence Pairs *** This does not always work.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#3061]
Custom Exports - Sentence Pairs at the top of https://tatoeba.org/en/downloads doesn't work sometimes.

I was able to generate these.

Sentence pairs in English-Indonesian - 2023-05-25.tsv
Sentence pairs in English-Japanese - 2023-05-25.tsv
Sentence pairs in English-Nepali - 2023-05-25.tsv

But I couldn't  get these.
English-German
English-Italian
English-French

I suspect it may be a time-out error of some kind.

**Comment by LBeaudoux** [comment]
I tried to reproduce this bug for the language pairs mentioned, but without success. All three custom exports went through without a hitch after a few seconds of latency.

**Comment by ckjpn** [comment]
This seems not to happen anymore, so I'm closing this.
