### ISSUE TITLE
Korean audio recordings are unavailable (but files still present)

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#3062]
I noticed that Korean is no longer listed on the [audio index page](https://tatoeba.org/en/audio/index/kor) and the exported `sentences_with_audio` file has no recordings for sentences in Korean either.

But I remember clearly that we used to have recordings in Korean and indeed the `/var/www-audio/sentences/kor/` directory on the server contains 477 `.mp3` files.

The Internet Archive has [a snapshot from 2022-08-10](https://web.archive.org/web/20220810052135/https://tatoeba.org/en/audio/index/kor) with Korean audio still present and [another snapshot from 2023-01-27](https://web.archive.org/web/20230127184040/https://tatoeba.org/en/audio/index) without. The date range would seem to rule out the database migrations in #2880 and #3037 as causes.

That leaves me with 2 possible explanations I can think of:
1. The user who contributed the recordings asked for them to be deleted. Then it's not a bug they're not available anymore, but arguably a bug that they're still present on the server.
2. We have some kind of database corruption.

**Comment by ckjpn** [comment]
audio - kor - by pon00050

He wrote and told us that he wasn't a native Korean speaker and asked to have the audio files removed.

**Comment by Yorwba** [comment]
That explains why there are 477 files on the server, even though the 2022-08-10 archive.org snapshot shows 292 recordings.

What about [audio - kor - by Eunhee](https://tatoeba.org/en/sentences_lists/show/9530)?

**Comment by ckjpn** [comment]
I don't know.
I guess Gillux may need to take care of those.

**Comment by ckjpn** [comment]
### Note:

### English
https://tatoeba.org/en/sentences/show/3756600
The old standard link for this one works.
https://audio.tatoeba.org/sentences/eng/3756600.mp3

### Korean
https://tatoeba.org/en/sentences/show/8365857
But this one doesn't.
https://audio.tatoeba.org/sentences/kor/8365857.mp3

**Comment by jiru** [comment]
I am asking Eunhee.

**Comment by jiru** [comment]
About Eunhee’s audios.

Snapshot from [September, 29th](https://web.archive.org/web/20220929052320mp_/https://tatoeba.org/en/user/profile/Eunhee) shows audio was already missing at that time. That further reduces the date of disappearance to somewhere between Aug. 10 and Sep. 29, 2022.

**Comment by jiru** [comment]
Eunhee replied me that she explicitly asked for her audio contributions to be removed.

**Comment by ckjpn** [comment]
I deleted [audio - kor - by Eunhee](https://tatoeba.org/en/sentences_lists/show/9530), so it won't be confusing in the future.
