### ISSUE TITLE
Number of Supported Languages Counts Don't Match

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#3068]
https://tatoeba.org/en/stats/sentences_by_language
<img width="821" alt="Screen Shot 2023-07-14 at 12 53 36" src="https://github.com/Tatoeba/tatoeba2/assets/7934273/74c83b08-c524-43f8-8e63-1cf01507d369">

https://tatoeba.org/en
<img width="324" alt="Screen Shot 2023-07-14 at 12 54 35" src="https://github.com/Tatoeba/tatoeba2/assets/7934273/cdbb9c10-5b7d-4d08-9101-c46833730655">

Noted on the Wall.

https://tatoeba.org/en/wall/show_message/40038#!#message_40038

Cabo
10 hours ago, edited 10 hours ago
I see 422.

ecorralest101
10 hours ago
No, it shows 421 supported languages.

**Comment by Yorwba** [comment]
The "number of sentences by language" table has an extra row for sentences in an "unknown" language, so the number of the last row will always be one higher than the number of supported languages.
