### ISSUE TITLE
Unclear "Click to edit" message when user tries to delete all sentence content

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#307]
When a user tries to delete all the content of a sentence (or all the content other than spaces), the phrase "Click to edit" is displayed where the content was. In fact, no content has been removed, but the user can't tell that unless s/he refreshes the screen. We could definitely have a more informative display.

**Comment by theblindspring** [comment]
What kind of error/alert would we like to give? Why not just put the original sentence back into the content if the user tries to edit and save it as empty?

**Comment by trang** [comment]
Yes, we just put the original sentence back.
