### ISSUE TITLE
Disambiguate the concept of "Armenian".

### ISSUE THREAD

**Issue by vxern** [Tatoeba/tatoeba2#3079]
This issue would come in two parts:
- [x] Rename "Armenian" to "Eastern Armenian".
- [x] #3082 

Armenian is a pluricentric language comprising two major dialects: Eastern and Western.

The Armenian seen on Tatoeba is the Eastern variant, spoken mainly on the territory of Armenia, which means it could safely be renamed from "Armenian" to "Eastern Armenian"/"Armenian (Eastern)".

Wikipedia sources:
<https://en.wikipedia.org/wiki/Eastern_Armenian>
<https://en.wikipedia.org/wiki/Western_Armenian>

**Comment by DJ-Saidez** [comment]
Is all Armenian sentences on Tatoeba of the Eastern dialect, or a majority of them? Because if there also are Western dialect sentences, we'd need to know how to resort them.

**Comment by vxern** [comment]
> Is all Armenian sentences on Tatoeba of the Eastern dialect, or a majority of them? Because if there also are Western dialect sentences, we'd need to know how to resort them.

The Western dialect is written using the classical orthography, meaning one could accurately check for which sentences are written in Western, and which ones are in Eastern by searching for certain letter combinations, for example «իւ» or «էօ». Having searched for some of these, I only found two mistaken usages, which were in Eastern.

On good guess, I would assume that the rest can safely be considered as Eastern, and if any Western sentences are found, I'd assume it would be easy to track the other ones down by their author.
