### ISSUE TITLE
Make the website easy to use with a mobile device

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#31]
Tatoeba is difficult to browse and use with a mobile device. We should either make the design responsive, or have a stripped-down mobile version, or maybe a dedicated app.
[orion17, Wall](http://tatoeba.org/jpn/wall/show_message/17246#message_17246)
[Original ticket](https://www.assembla.com/spaces/tatoeba2/tickets/409-offer-a-mobile-version-of-the-website)

**Comment by trang** [comment]
I'm closing this since solving this issue is a big project on its own. We will need to split this into several smaller issues.
