### ISSUE TITLE
Strange English usage in Tatoeba GitHub "about" description

### ISSUE THREAD

**Issue by wydengyre** [Tatoeba/tatoeba2#3101]
The "about" description of Tatoeba reads:

Tatoeba is a platform _which_ purpose is to create a collaborative and open dataset of sentences and their translations.

The usage of the word "which" in this sentence is very strange for a native speaker. The better word would be "whose":

Tatoeba is a platform _whose_ purpose is to create a collaborative and open dataset of sentences and their translations.

**Comment by Yorwba** [comment]
Thank you for pointing this out. I made the change you suggested.
