### ISSUE TITLE
tags CSV dump appears incomplete

### ISSUE THREAD

**Issue by wydengyre** [Tatoeba/tatoeba2#3115]
**To Reproduce**
1. Download https://downloads.tatoeba.org/exports/tags.tar.bz2
2. Search for, as an example, the tag [congiuntivo presente](https://tatoeba.org/en/tags/show_sentences_with_tag/6706). It doesn't exist.

**Expected behavior**
All tags should be in the file.

**Comment by LBeaudoux** [comment]
I was unable to reproduce this bug. I downloaded and unzipped the archive, but found 3,082 hits for the tag `congiuntivo presente`.

**Comment by wydengyre** [comment]
You're right. Something got corrupted for me localy. My apologies for the wasted time.
