### ISSUE TITLE
https://status.tatoeba.org/ gets an error message

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#3122]
Connection to upstream failed: connection failure
Request ID: cf853694-74174447

**Comment by Yorwba** [comment]
The status page is hosted separately from the rest of our infrastructure by alwaysdata (status.tatoeba.org is an alias for tatoeba.alwaysdata.net) to ensure independent failures. It looks like they have indeed independently failed...

Today we got an email from them:

> # [alwaysdata] Update of our standard terms of service
>
> Hello,
>
> You have chosen alwaysdata to host your data, and we thank you for that. We
> would like to inform you that our terms of service are evolving. We invite you
> to review the new version of our contracts.
> https://admin.alwaysdata.com/contract/
>
> Modifications apply to:
>
> 1/ Terms of use
>
> - Art. 10.3: ALWAYSDATA can not be held liable in the event of a lack of
> backup for more than 72 hours, and no longer 24 hours, as long as this failure
> does not cause or has not caused the Customer to sustain any direct loss.
>
> These new conditions will apply to you one month after this notification.
>
> We remind you that your alwaysdata subscription has no minimum duration
> commitment.
> 
> We thank you for your trust and remain at your disposal for any further
> information.
>
> Regards,
>
> -- 
> alwaysdata: https://www.alwaysdata.com/
> help: https://help.alwaysdata.com/

From which I infer that they lost data and are trying to protect themselves from any resulting liability claims. Certainly not a good look.

**Comment by jiru** [comment]
The problem was that the disk was full. It was being filled by logs from a test cronjob.
