### ISSUE TITLE
Sorting option text gets cut in advanced search dropdown menu

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#3126]
**To Reproduce**
1. Set the UI language to Italian
2. Select, in the order by word count dropdown menu, "prima le frasi con il minor numero di parole" (corresponding to the English "fewer words first"
3. See that the message is truncated

**Expected behavior**
The field should change automatically if the contained text takes a bigger space than expected, so that every part of the text can be read.

**Screenshots (if applicable)**
![Screenshot 2024-04-28 204503](https://github.com/Tatoeba/tatoeba2/assets/1702194/b79aa2b0-dc9d-4a26-9663-6388342a6bf1)

**Comment by jiru** [comment]
It looks like you are suggesting to widen the closed dropdown, but won't that create a new glitch, which is having the closed dropdown overflow the search criteria pane? Besides, if your browser window is exactly 960px wide, you will see there is not space to extend the dropdown.

**Comment by Guybrush88** [comment]
I see now, I wasn't aware of these limitations, thanks for pointing them out

**Comment by jiru** [comment]
We cannot really extend the available space for that dropdown. One way to work around this issue is to make the Italian translation shorter.
