### ISSUE TITLE
Support drafts of private messages

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#32]
In most e-mail clients, there's a way to save messages as drafts without sending them. This lets the user work on them until they're ready to send. This would be nice functionality to provide in our private message area as well.

----

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/408

**Comment by RyckRichards** [comment]
Requested on the 1st Tatoeba day (2015-06-06)
https://tatoeba.org/eng/wall/show_message/22959#message_22959

**Comment by trang** [comment]
Writing down some notes about a possible implementation.

* Add the value `Draft` in the `folder` enum of the `private_messages` table.
* Add function `saveDraft()` in PrivateMessage model.
* Add function `save_draft` in PrivateMessagesController.
* Add button **Save as draft** in the private message form.
* Modify `send()` function in PrivateMessagesController to handle "Save as draft".
* Add a link **Drafts** in the list of folders in the sidebar.
* Modify `folder()` function in PrivateMessagesController to retrieve Drafts messages.
* Modify URL in `private_messages/folder.ctp` for Draft messages: they should redirect to `write` and not `show`.
* Modify `write()` function in PrivateMessagesController to take into account an extra param: `messageId`. When the messageId is set, the content of the form should be pre-filled with the content of the corresponding message.
* Modify `private_message/write.ctp` to take into account the content of the Draft message when displaying form.

**Comment by RyckRichards** [comment]
According to Guybrush88, he wants something (pretty) similar as drafts in e-mail clients which would help us to decide to either to send it or save it in order to send it in a second moment

**Comment by zachleigh** [comment]
While going through this issue, I found that in private_messages_controller, the write method takes $recipients as its first argument. According to the doc-block, its supposed to be a string, but the database column is of type int.

| Field     | Type                               | Null | Key  | Default | Extra          |
|-----------|--------------------------------|-----  |--------|----------|----------------|
| recpt     | int(11)                            | NO   | MUL | NULL    |                |

Setting the recipients simply puts a userid in the recipients field, without actually finding the user. is this the desired behavior?

**Comment by trang** [comment]
I'd go for a shorter solution: 

* Don't save the recipient(s) if the user saves as draft.
* Add a tooltip on hover on the "Save as draft" button: `Only the title and content of your message will be saved. The recipient will not be saved.`
* The avatar used for drafts would then be the "unknown" avatar.

**Comment by zachleigh** [comment]
How about saving the recipient field as a string and then using the unknown avatar?

**Comment by trang** [comment]
It's fine too.

**Comment by ckjpn** [comment]
I tried saving a draft on the dev site and it didn't work for me.

Macintosh, Chrome

**Comment by zachleigh** [comment]
I can confirm that. Just tried on the dev site and it didnt work for me either. Works fine locally.  Hmmm. @trang Any ideas why this is happening?

**Comment by trang** [comment]
Yes, I forgot to execute the sql script on the dev server. I just ran it now, @ckjpn it should work, try again.

**Comment by zachleigh** [comment]
Working here now. Thanks @trang
