### ISSUE TITLE
Number of sentences is wrong on sentence statistics page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#332]
Take a look at the last item on the sentence statistics page:

http://www.tatoeba.org/eng/stats/sentences_by_language

The number of sentences listed for Middle English (at the bottom of the page is 1. But in fact, there are 9, which is confirmed by:
- an SQL query
- the number at the top of the page when you do a "show all in" operation (e.g., by clicking on the "Middle English" link at the bottom of the page)
- the actual number of sentences shown when you do a "show all in" operation.

**Comment by jiru** [comment]
@alanfgh Trang fixed the statistics decrement on sentence deletion in #415. I fixed the counting error I mentioned earlier, but other errors may still exist. I’m closing this but feel free to reopen it or open a new bug if you notice other mismatches.
