### ISSUE TITLE
Button to copy a sentence into clipboard

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#334]
http://tatoeba.org/eng/wall/show_message/19850#message_19850

> Il manque toujours une fonctionnalité permettant de copier une phrase en un seul clic (lorsqu'on veut en reprendre une pour créer une variante, par exemple).
Bien sûr, on peut zoner la partie de la phrase qu'on veut copier, mais ceci présente 2 difficultés :
>
> 1) si on est propriétaire de la phrase, cliquer dessus pour en copier des éléments fait entrer en mode édition de manière intempestive.
> 2) si on travaille à partir d'une tablette ou d'un téléphone, il est moins aisé de procéder à cette sélection.
>
> Je trouve qu'un simple bouton de copie, à gauche ou au-dessus de la phrase, ferait bien l'affaire. L'idée n'est pas forcément de créer directement une duplication de la phrase, mais simplement de la placer dans le presse-papier.

**Comment by trang** [comment]
Apparently it became more difficult to copy-paste a sentence since ae574a4d74de0c7e265e8b914658fd6afb013a28.

https://tatoeba.org/eng/wall/show_message/22446#message_22446

We might consider implementing this "copy to clipboard" button rather than figuring why it's now more difficult to copy by highlighting a sentence.

**Comment by alanfgh** [comment]
A "copy to clipboard" button would be nice (more efficient than having to click three times on a sentence in order to select the whole thing and then right-click to select "copy"). However, I don't see the behavior reported by sc. I have no problem selecting all or part of a sentence, in either Firefox or Chrome, and when I paste it into a text editor, only the contents of the sentence appear.

**Comment by jiru** [comment]
Me neither, I have no particular problem using Firefox or Chrome on Linux, in particular using triple click. I can see however how hard it could be using e.g. a touchscreen. And note that we’re still using old-style edition (edition by clicking on the sentence text) in the case of a newly added translation. That was requested by someone to allow quick fixes you notice only after sending a translation.

**Comment by jiru** [comment]
According to [this](https://stackoverflow.com/questions/26336138/how-can-i-copy-to-clipboard-in-html5-without-using-flash), using an HTML5-based implementation would not work for most of the mobile users, so we’d better use a Flash-based thing.

**Comment by trang** [comment]
There's ZeroClipboard: http://zeroclipboard.org/. It's what GitHub uses for their "Copy SHA" feature. It seems to be the most popular solution.

It's not going to work on iPhones/iPads though.

**Comment by RyckRichards** [comment]
Requested once more by Guybrush88 on the 1st Tatoeba day:

https://tatoeba.org/eng/wall/show_message/22963#message_22963

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on Tatoeba Day 4 (2015-07-25 07:18 ):

https://tatoeba.org/eng/wall/show_message/23630#message_23630

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on Tatoeba Day # 7

https://tatoeba.org/eng/wall/show_message/24183#message_24183

**Comment by ckjpn** [comment]
>It's not going to work on iPhones/iPads though.

A copy-to-clipboard button would likely be more useful on mobiles than on computers, so whatever solution you come up with should definitely work on mobiles.

**Comment by trang** [comment]
Another solution: http://zenorocha.github.io/clipboard.js/

@ckjpn, any chance you have time to look into clipboard.js, and let me know how it works on Safari?

**Comment by ckjpn** [comment]
None of their examples on the webpage worked in Safari on a Mac.
I didn't try it on an iPad.
Their examples worked wonderfully on Chrome.

**Comment by ckjpn** [comment]
This one worked in Safari and Chrome.

http://davidwalsh.name/clipboard

I didn't try other browsers.

My guess is there is a more elegant jQuery plugin already written by someone.
Since tatoeba.org already is loading jQuery, it might be best to use one of those, if you can find one.

**Comment by zenorocha** [comment]
+1 for clipboard.js ;)

**Comment by trang** [comment]
I've implemented this as an optional feature. It needs to be enabled in the settings.
