### ISSUE TITLE
Offer ability to search comments on sentences

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#355]
Requested by user odexed. We already have a ticket for searching comments on the Wall (#38), but not for searching comments on sentences.

**Comment by trang** [comment]
Closing this for same reason as https://github.com/Tatoeba/tatoeba2/issues/38#issuecomment-517918081.

- Searching from Google for comments containing "literal translation" would look like this: [site:tatoeba.org/*/sentences/show "literal translation"](https://www.google.com/search?q=site%3Atatoeba.org%2F*%2Fsentences%2Fshow+"literal+translation").
- Comments on sentences are [exported weekly](https://downloads.tatoeba.org/exports/comments.tar.bz2).
