### ISSUE TITLE
Send automatic notifications for a wider variety of events

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#36]
Send automatic notifications for a wider variety of events, including when translations are linked to or unlinked from one of the sentences that I own.
[AlanF_US, Wall](http://tatoeba.org/eng/wall/show_message/16981#message_16981)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/404

**Comment by RyckRichards** [comment]
Requested by "pullnosemans" on the 1st Tatoeba day:
https://tatoeba.org/eng/wall/show_message/22974#message_22974

**Comment by RyckRichards** [comment]
* Would we email everyone each time someone link his/her sentence? 
* Will it be optional as to display "native", "expand/collapse" sentences or no?

**Comment by ckjpn** [comment]
Another possible addition would be ....

Send an email when a sentence that is directly linked has been changed.
This would help members know that they may need to check to see if their translation still matches.

**Comment by trang** [comment]
The scope of this issue a too large to do anything and sending notifications is maybe not the best solution for the underlying issues. 

Personally, I have always been super reluctant to send notifications. If anything, I would prefer to shape Tatoeba around the narrative that contributors should come to the website whenever they want to contribute, not whenever we try to attract their attention through a notification. 

I will close this now, it's a very old one. I encourage anyone who wants to receive notifications about something, to create a separate issue and describe in detail what is the use-case behind it.
