### ISSUE TITLE
Redirection of old "pages" URLs doesn't work

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#360]
The redirections here do not work anymore:
https://github.com/Tatoeba/tatoeba2/blob/dev/app/controllers/pages_controller.php#L146

Not sure why...

For instance going to:
http://tatoeba.org/eng/pages/download-tatoeba-example-sentences

displays:
``` 
Error: The requested address '/eng/pages/download&#45;tatoeba&#45;example&#45;sentences' 
was not found on this server.
```

**Comment by kwikadi** [comment]
If this is any help, trying to load this page on the dev environment using imouto fails (Missing Method in PagesController), but works flawlessly on windows without VM. Perhaps this has to do with nginx? (I don't know what else is different)
