### ISSUE TITLE
Customize nginx error pages

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#361]
13:44 < CK-in-Japan> 504 Gateway Time-out
13:44 < CK-in-Japan> Question: Is it possible to create your own “custom” Gateway Error messages?
13:45 < CK-in-Japan> If so, a short one sentence explanation telling people to try again later might be a good idea.
13:46 < CK-in-Japan> Long term members can deal with it, but we’re likely to lose new potential contributors if they keep experiencing error messages with no explanations.

**Comment by jiru** [comment]
The page is under version control now. The rest is out of scope.
