### ISSUE TITLE
Store search parameters in cookies

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#371]
Currently, we store search parameters (source language, destination language) within a session, but not from one session to another. It should be easy to store them across sessions. This has been requested by a user, and I think it makes sense. The user also suggested being able to set these default languages in the profile, which would be harder to do and less useful, I think.

**Comment by trang** [comment]
I'll close this issue. 

It doesn't feel like this is something a lot of people need. There has actually be [complaints about the search remaining in the search bar](https://tatoeba.org/eng/wall/show_message/23350#message_23350), which I don't feel are very justified either.
