### ISSUE TITLE
Offer an option to show only translated sentences

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#374]
orion17 posted this on the Wall:

"hello everyone...
it's been a long time since my last post here..
I have a problem, I want to browse all sentences in a language with translation but sometimes untranslated sentences are also shown up. So could you tell me how to get only translated ones shown up?"

We don't offer this functionality but perhaps someday we could. I'm considering this low priority, though, since it probably involves more server-intensive searches.

**Comment by jiru** [comment]
It’s now possible to do this using the advanced search.
