### ISSUE TITLE
find a way to avoid forcing 'debug' value to 0

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#380]
From app/controllers/sentences_lists_controller.php:

    public function add_sentence_to_list($sentenceId, $listId)
    {
        Configure::write('debug', 0); // Need to have debug at 0 if we want the
                                      // list to be removed from the select
                                      // right after the sentence was added.

Two potential problems:

(1) This prevents me from debugging the code (which I'm trying to do now).

(2) I find it confusing that the list to which the sentence was added is removed from the select. I would find it more understandable if it were highlighted in some way.

There are additional occurrences of Configure::write('debug', 0) in the code:

./controllers/sentences_controller.php:895:            Configure::write('debug', 0);
./controllers/sentences_controller.php:916:        Configure::write('debug', 0);
./controllers/users_controller.php:527:        Configure::write('debug', 0); // NOTE: It's normally not good to set debug

These affect changing the language of a sentence, getting the previous and next valid sentence id, and handling captcha images.

Maybe there's a better approach?

**Comment by trang** [comment]
I removed the `Configure::write('debug', 0)`.
