### ISSUE TITLE
Register: typing an invalid character into the username should turn the field red immediately

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#381]
Currently, the username field from the Register page stays red when the username is too short, but turns green once it reaches the minimum length. However, if you type in an invalid character (anything other than a letter, number, or underscore), the username stays green. Only when you try to save the user does it tell you that the character is invalid. It would be nice if it told you this by turning green when the character was entered.

**Comment by jiru** [comment]
@kwikadi said it now words as expected.

**Comment by kwikadi** [comment]
Code (the last commit references it too): https://github.com/Tatoeba/tatoeba2/blob/dev/app/webroot/js/users.check_registration.js#L63-L75
