### ISSUE TITLE
Add option to send automatic notifications to PM inbox

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#39]
Offer an option to let automatic notifications go to one's Tatoeba mailbox (private message inbox) instead of or in addition to an external mailbox.
[AlanF_US, Wall](http://tatoeba.org/eng/wall/show_message/16970#message_16970)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/401

**Comment by trang** [comment]
Duplicated by #1441. Closing this one because the other issue has a bit more feedback.
