### ISSUE TITLE
Fork Chosen into Tatoeba

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#398]
We’re using a compiled version of [Chosen](/harvesthq/chosen) that I included into Tatoeba’s repository. Since I already patched it and it’s [very likely](http://tatoeba.org/wall/show_message/20126#message_20126) that we’re going to have to patch it again, and since the original author seems quite reluctant (or don’t have the time) to merge pull requests that are piling up in his repository, we’d better:
* fork it (simple)
* somehow integrate it so that it’s used as a dependency of Tatoeba, using Bower or something (harder)

**Comment by trang** [comment]
I'm closing this since we'll be using Angular Material, and it has an autocomplete component that we can use instead of Chosen: https://material.angularjs.org/latest/demo/autocomplete
