### ISSUE TITLE
Move nginx config to imouto

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#407]
Since we’re moving the setup of nginx to imouto, we should move its configuration file too, in order to keep the file in one place only. So we need to:

1. Merge the latest changes of [Tatoeba’s nginx config](https://github.com/Tatoeba/tatoeba2/blob/master/docs/nginx/default-prod) into [imouto’s](https://github.com/Tatoeba/admin/blob/master/imouto/ansible/roles/setup_nginx/templates/default)
2. Remove nginx config from this Tatoeba repository.

**Comment by trang** [comment]
@jiru can this be closed?
