### ISSUE TITLE
"value=" string is sometimes appended to URL when a sentence is being edited

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#420]
From CK:

:::
A "?value=something" is being added to the URLs when editing.
Is this accidental, or is there some purpose for this?

I just thought you'd like the heads up.

I think it could be potentially confusing to users who copy and paste URLs.

http://tatoeba.org/eng/sentences/show/2706987?value=It%27s+one+o%27clock.
:::

I did see this once, but was unable to reproduce it consistently.

**Comment by trang** [comment]
I have never been able to reproduce this and no one else reported this bug.
I'm closing it.

**Comment by jiru** [comment]
It’s [back](https://tatoeba.org/wall/show_message/22871#message_22871) (bullet point 9 of tommy_san’s post).

**Comment by jiru** [comment]
Closing this because I’m unable to reproduce. I think it’s related to the jeditable plugin sending a request with a `value` parameter, which should be POST but is GET for some reason.
