### ISSUE TITLE
Wrong result count for search query

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#422]
As reported by wallebot, searching for "gnashes" (with "From" and "To" set to "Any") returns only one result, but the result string says there are two. Searching with mysql for "gnash" (with a few variations) reveals only one (1064146).

**Comment by jiru** [comment]
Can’t reproduce. Since we don’t seem to have enough information about that problem to solve it, we’d better close that ticket.

**Comment by trang** [comment]
I suspect this was caused by situations where a sentence has been deleted and the index has not been updated yet.
