### ISSUE TITLE
Provide function to search for near-/duplicates of sentence to be submitted

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#44]
Provide a function that lets you search for existing duplicates or near-duplicates of a sentence that you're about to submit, ideally without taking you to another screen and disturbing your workflow. There are various ways that this function could be executed:
1. automatically upon submission of any sentence
2. automatically upon submission of any sentence unless you are an advanced contributor or higher
3. automatically upon submission of any sentence unless you opt out in your profile
4. upon pressing a button that is visible from the screen from which you submit a sentence

[AlanF_US, Wall](http://tatoeba.org/eng/wall/show_message/16877#message_16877)
[anders, Wall](http://tatoeba.org/eng/wall/show_message/17845#message_17845)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/396

**Comment by jiru** [comment]
It’s already possible to provide some kind of fuzzy matching using the [Quorum operator](https://manticoresearch.com/2018/02/16/fuzzy-matching-and-2nd-pass-query/).

Searching for ["I am sorry that I have troubled you so much"/5](https://tatoeba.org/sentences/search?query=%22I+am+sorry+that+I+have+troubled+you+so+much%22%2F5&from=und&to=none) returns sentences containing at least five words from that sentence. It’s possible to programmatically build such a fuzzy query from a given sentence with the help of [call keywords](https://docs.manticoresearch.com/latest/html/sphinxql_reference/call_keywords_syntax.html).

**Comment by trang** [comment]
Closing because outdated.

This feature suggestion seems to be about avoiding the creation of near duplicates, but we have established that near duplicates are not really a problem for us.
