### ISSUE TITLE
Convert sentence number to link in notification emails

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#448]
Requested by tommy_san.
http://tatoeba.org/eng/wall/show_message/20541#message_20541

> > You will now also be able to use the sentence URL syntax everywhere, and not only for comments on sentences.

> It would be more convenient if this feature were also available in email notifications. Would that be possible?

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on the 1st Tatoeba day:
https://tatoeba.org/eng/wall/show_message/22962#message_22962
