### ISSUE TITLE
Consider sql exports

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#452]
A really nice thing for development on the current codebase which I happen to have at the moment is a cleaned up sql dump of the live server. I have a cleaning script that I use locally to remove private messages, ips, and passwords, will probably upload a file soon, possibly along with a preloaded vm disk as well. The approach I have in mind for implementing such an export on the server involves copying the live tables to a sister db on the same mysql server, then running the clean up script. The drawback here is the time it would take initially to setup that table, and the size of the database on disk, which would double.

**Comment by lagleki** [comment]
+1

**Comment by trang** [comment]
Cf. https://github.com/Tatoeba/tatoeba2/pull/994#issuecomment-590073246
