### ISSUE TITLE
Make it easy to request specific sentences by natives

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#46]
Offer a mechanism to request translations of specific sentences by natives.
[tommy_san, Wall](http://tatoeba.org/eng/wall/show_message/16623#message_16623)

-----

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/394

**Comment by alanfgh** [comment]
Silja brought this up again on the Wall: http://tatoeba.org/eng/wall/show_message/21418#message_21418

**Comment by Guybrush88** [comment]
Brought up again by maydoo: https://tatoeba.org/ita/wall/show_message/23654#message_23654

**Comment by trang** [comment]
I've changed the title because it is a bit misleading, since this is not about translations but sentences.

And I'm closing this because there is a design in progress for this feature request: #1148.
