### ISSUE TITLE
Add setting to determine whether collaborative lists are shown

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#463]
CK requested that we have a setting that determines whether collaborative lists are shown. Listing them takes up both server resources and screen real estate, and since many users don't use them, it makes sense to control this with a setting.

Here's the thread on the Wall: http://tatoeba.org/eng/wall/show_message/20462#message_20462

Note: This was originally part of #439, together with the addition of a "remember last list shown" option. I've moved it into this ticket.

**Comment by trang** [comment]
This was implemented in #677.

A collaborative list will not show if the author of the list set the visibility to "unlisted".
