### ISSUE TITLE
Segregate sentences by learners from sentences by natives

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#47]
Segregate sentences by learners from sentences by natives. This can be done either via a two-category approach (natives and non-natives) or via a rating on a scale.
[alexmarcelo and others, Wall](http://tatoeba.org/eng/wall/show_message/16629#message_16629)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/393

**Comment by ckjpn** [comment]
With the recently-added 3-level rating scale having been added, maybe this issue can be closed, even though perhaps the new scale doesn't totally address this issue.

**Comment by trang** [comment]
The corpus and the community have evolved quite a bit since this issue was created. As of today, I'm not sure what this segregation would solve. I will close it, we can start from a fresh discussion if needed.
