### ISSUE TITLE
Consider migrating to mariadb

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#472]
deal with  #471 first.
then run the rest of the scripts already here: https://github.com/Tatoeba/tatoeba2/tree/master/docs/mariadb

There's two issues that need to be addressed:
- is the schema intact after migration? (seems to be the case from my light testing and liori's)
- Should we use some non-standard config like setting up bnlh for joins? (this needs some benchmarking see script here: https://github.com/Tatoeba/tatoeba2/blob/master/docs/benchmark.sh)

**Comment by halfdan** [comment]
Considering that #471 is long resolved what is the driving goal here? MySQL is totally fine unless you're an open source advocate. I do like MariaDB and Postgres but unless there's a convincing reason to switch I think time can be spent in better places.

**Comment by trang** [comment]
So... We're on mariadb ever since we moved to Hetzner months ago. Closing.
