### ISSUE TITLE
Switching from daylight saving time messes up relative time records

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#478]
This has been [observed](http://tatoeba.org/jpn/wall/show_message/20711#message_20711) on the 26 of October, 2014. Comments are also affected. Switching from DST makes you “jump in the past” so some dates [appears to be in the future](https://i.imgur.com/Q0eHFd2.png): -59 min(s) ago, -35 min(s) ago…

This happens because we store dates without the timezone they are relative to. Switching back/from DST means changing the time zone. This is how the time flows when DST ends:
```
$ date -Rud "26 Oct 2014 02:00:00 +0200" 
Sun, 26 Oct 2014 00:00:00 +0000
$ date -Rud "26 Oct 2014 02:59:00 +0200" 
Sun, 26 Oct 2014 00:59:00 +0000
# DST ended
$ date -Rud "26 Oct 2014 02:01:00 +0100" 
Sun, 26 Oct 2014 01:01:00 +0000
$ date -Rud "26 Oct 2014 02:59:00 +0100" 
Sun, 26 Oct 2014 01:59:00 +0000
$ date -Rud "26 Oct 2014 03:01:00 +0100" 
Sun, 26 Oct 2014 02:01:00 +0000
```

**Comment by trang** [comment]
I've written a more detailed procedure below (not sure about the exact commands for starting/shutting down the services).

Is there something missing or incorrect?

------------

### 1. Shut down the VM
* shut down nginx.
`$ service nginx stop`

* Wait a bit and shut down mysql.
`$ service mysqld stop`

* Shut down the VM
`$ shutdown now`

### 2. Change time on the host

* Change timezone in `/etc/timezone`
`Europe/Paris` --> `UTC`

* Run ntpdate
`$ ntpdate fr.pool.ntp.org`

* Start the VM in a screen
Cf. command line history

### 3. Change time on the VM

* Change timezone in `/etc/timezone`
`Europe/Paris` --> `UTC`

* Run ntpdate
`$ ntpdate fr.pool.ntp.org`

* Change timezone in `/etc/php5/cli/php.ini`
`;date.timezone =` --> `date.timezone = UTC`

* Start mysql
`$ service mysqld start`

* Start nginx
`$ service nginx start`

* Change crontab
`$ sudo -u sphinxsearch crontab -e`
`20 9 * * 6` --> `20 6 * * 6`

**Comment by loolmeh** [comment]
the right ini file to edit is /etc/php5/fpm/php.ini
I think it's working now, will take an hour for the negative minutes count to normalize
