### ISSUE TITLE
Display owner (if any) next to sentence in more contexts

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#48]
Display owner (if any) next to sentence in more contexts. For instance, display it next to each translation of a sentence in a list of sentences (e.g., [sentences in English not translated into language X](http://tatoeba.org/eng/sentences/show_all_in/eng/und/eus).
[AlanF_US, Wall](http://tatoeba.org/eng/wall/show_message/16640#message_16640)

**Comment by RyckRichards** [comment]
Requested once more by CK during the 1st Tatoeba day (2015-06-06)

https://tatoeba.org/eng/wall/show_message/22943#message_22943
Answer (by Trang): https://tatoeba.org/eng/wall/show_message/22982#message_22982

**Comment by trang** [comment]
Issue #771 is a duplicate but is more detailed so I'm closing this.
