### ISSUE TITLE
Add "Display orphan sentences" option

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#49]
Make a new option "Display orphan sentences" in the settings page and set it "off" by default.
[tommy_san, Wall](http://tatoeba.org/jpn/wall/show_message/16636#message_16636)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/391

**Comment by trang** [comment]
Closing this. We've addressed this issue:

* Orphan sentences are no longer picked to be displayed as a random sentence on the homepage for a while now (e8053910ccce2106593431c08b14918dfca73bd8).
* The search excludes orphan sentences by default (which currently leads people to think the search is not covering every sentence, as reported in #1570, but that's a UI issue).
