### ISSUE TITLE
Interface language cookie doubled

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#500]
After browsing Tatoeba and changing the interface language, one ends up with two cookies named `CakeCookie[interfaceLanguage]`.
- One is binded to domain .tatoeba.org
- One is binded to host tatoeba.org

We probably want a single cookie binded to domain .tatoeba.org instead.

**Comment by trang** [comment]
Removing the `TATOEBA_DOMAIN` in the config seems to solve the problem...

When `$this->Cookie->domain = "tatoeba.org"`, if I clear the cookies and I go to Tatoeba, I see a cookie binded to `.tatoeba.org` for the UI language.
When `$this->Cookie->domain = ""`, if I clear the cookies and I go to Tatoeba, the cookie is binded to `tatoeba.org`.

Same thing when I tested on dev. If `TATOEBA_DOMAIN` is set to `dev.tatoeba.org`, I see a cookie binded to `.dev.tatoeba.org`. If it's set to nothing, then the cookie is binded to `dev.tatoeba.org`.

I've changed both the prod and the dev to have `define("TATOEBA_DOMAIN", "");` in the config.

@jiru If this fix sounds good for you, I let you close this.

**Comment by jiru** [comment]
Thank you trang, I confirm this solves the problem for me too.

Specifying a value for `$this->Cookie->domain` sets the `Domain=` value of the cookie, while leaving it empty leaves the Cookie without any `Domain=` value. However, a [domain-less cookie is actually restricted to only the host it was initially sent from](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie), while specifying a domain restricts it for the host + its subdomains. So we actually want not to set any domain.

I guess that prepending a dot to the domain is just a way for your browser to show that subdomains are included, but it’s different from the actual value set in the cookie.
