### ISSUE TITLE
Have proper localized versions of the site returned by SERP

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#507]
Currently, when someone searches tatoeba on Google, the English version always comes first, even if you use a Google country-specific TLD (such as google.fr), and have your browser preferred language set to the country’s main language. To make the matter worse, all the results from tatoeba.org are grouped into a mix of localized and English pages.

[Having a proper sitemap may solve the problem](https://stackoverflow.com/questions/11518239/google-organic-results-localization).

**Comment by AndiPersti** [comment]
I did some experiments and it seems the situation improved a little bit in the meantime. Searching on google.fr with `Accept-Language: fr` gives me the French version as the first hit. Same for google.de and google.es, but not for google.jp and google.ru where the localized versions come second after the English one.

(I have also tried bing.fr, bing.de, ... and yahoo.fr, yahoo.de, ... and there the English version always was first, followed by the localized version.)

Some questions:
* Do we still want to have a sitemap?
* @trang, @jiru Do you have access to the [Google Search Console](https://search.google.com/search-console/about) or [the International Targeting Report](https://support.google.com/webmasters/answer/6059209)? These tools should tell us where we could improve the indexing of our localized versions.
* I've noticed that the links to the alternate versions of a page use relative URLs (e.g. `<link rel="alternate" hreflang="fr" href="/fra/">`) but [Google says the should be fully-qualified](https://support.google.com/webmasters/answer/189077#all-method-guidelines). Maybe that's a problem?

**Comment by jiru** [comment]
Thank you for taking time to investigate into this, Andreas.

> @trang, @jiru Do you have access to the Google Search Console or the International Targeting Report? These tools should tell us where we could improve the indexing of our localized versions.

I don’t know what these things are.

> I've noticed that the links to the alternate versions of a page use relative URLs (e.g. <link rel="alternate" hreflang="fr" href="/fra/">) but Google says the should be fully-qualified. Maybe that's a problem?

We can try to specify fully-qualified URLs and see if the situation improves.

> Do we still want to have a sitemap?

The problem with this issue is that we cannot know in advance if a sitemap would really help because It’s hard to check if any change helps. Besides, the stackoverflow question is quite old now, maybe it’s not up to date. I’d go for fixing the URLs first because it’s easier.

**Comment by AndiPersti** [comment]
> I don’t know what these things are.

To be honest, I haven't used them either until now. :-)
But as I understand it after reading a little bit on the help pages, these tools should tell webmasters how Google sees and indexes their pages. But you must prove to Google that you are in control of a domain, so only domain owners have access to these tools.

> The problem with this issue is that we cannot know in advance if a sitemap would really help because It’s hard to check if any change helps.

As said above, it should be possible to get some more information from Google.

> I’d go for fixing the URLs first because it’s easier.

Agreed. Expect a PR soon. :-)

**Comment by trang** [comment]
I have access to the Google Search Console but never really looked into these things.

FYI, this is International targeting page looks like for Tatoeba:

![Screenshot_2020-02-02 Search Console - International Targeting - http tatoeba org ](https://user-images.githubusercontent.com/221850/73610687-808af980-45da-11ea-93dc-cdac419b2a3c.png)

And in the "Country" tab, there's just a checkbox:

![Screenshot_2020-02-02 Search Console - International Targeting - http tatoeba org (1)](https://user-images.githubusercontent.com/221850/73610857-27bc6080-45dc-11ea-9c7e-ffcd2f96fe8d.png)

**Comment by AndiPersti** [comment]
Ok, not as informative as I hoped. Let's see whether changing to absolute URLs makes any difference.
