### ISSUE TITLE
Add captchas or other screening mechanism for registration of new users

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#51]
Add captchas for registration of new users.Guybrush88, WallThe thread goes on to suggest other ideas, such as a requirement to post a certain number of sentences.

**Comment by trang** [comment]
In general, making the registration process more complicated won't really solve the issue of new users adding bad sentences. I'm also not a fan of captchas on registration, there are other solutions, so I will close this.
