### ISSUE TITLE
Login interferences between prod and dev website.

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#516]
Similar to #500. Steps to reproduce:
1. clear all cookies under tatoeba.org
2. log into tatoeba.org checking the “remember me” setting
3. go on dev.tatoeba.org: you’re being magically logged in
4. try to log out from dev.tatoeba.org: you’re still logged in

That’s probably because the “remember me” cookie uses the tatoeba.org domain.

**Comment by trang** [comment]
I can't reproduce this anymore. Can anyone confirm?

**Comment by alanfgh** [comment]
I can confirm that on Chrome on Windows, I don't see the behavior that
gillux reported. At step 3, when I go to dev.tatoeba.org, I'm not logged in.

Alan

**Comment by jiru** [comment]
Yes, I can still reproduce the problem.

**Comment by jiru** [comment]
Fixed by #500.
