### ISSUE TITLE
No log for sentence creation

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#520]
The following sentence doesn't have a log for when it was added. The first log entry is a modification.
http://tatoeba.org/eng/sentences/show/3664143

**Comment by Guybrush88** [comment]
it happened also right now: https://tatoeba.org/ita/sentences/show/4421282

**Comment by RyckRichards** [comment]
It happened again - https://tatoeba.org/eng/sentences/show/4983167#comments

**Comment by jiru** [comment]
It’s possible to get a list of all these sentences with the following query:
```sql
select
  s.id is not null as 'sentence_exists',
  sentence_id as 'sid',
  MAX(IF(action = 'insert' and type = 'sentence', 1, 0)) as 'has_insert_sentence_entry'
from contributions c
left join sentences s on s.id = c.sentence_id
group by sentence_id
having has_insert_sentence_entry = 0;
```

On dev.tatoeba.org, there is a total of 3727 sentences affected, of which 2253 are actual existing sentences. I can see that the ids of the affected sentence are clustered in groups of numbers that are close to each other. This suggests a temporary failure.

**Comment by jiru** [comment]
A simple way to prevent the creation of sentences without log, is to use wrap the sentence creation queries between BEGIN/COMMIT SQL statements. Here is [how to do it with CakePHP](https://book.cakephp.org/2.0/fr/models/transactions.html).
