### ISSUE TITLE
Can't search for words in Lojban language containing symbol "." (dot)

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#521]
"." is considered a punctuation symbol. However, in Lojban language 
. , ' 
are three symbols used as other letters.

Thus it's impossible to search for words containing them.

I reported to http://sphinxsearch.com/bugs/view.php?id=2126
although may be someone here could help? ;)

**Comment by jiru** [comment]
@lagleki I’d like to clarify a point. You said the dot character should be interpreted as a word separator, just like space in English. But Lojban sentences combine space and one or multiple dots. But you also want to be able to look for keywords that contain a dot.

So I made it so that words can be matched with dots only if fully qualified. Let’s say we have a corpus of these 3 sentences.

1. .ui.uenai
2. .ui do klama
3. .o'unai.ui zvati

Searching for `ui` returns 1, 2 and 3.
Searching for `.ui` returns 2.
Searching for `o'unai` returns 3.
Searching for `.o'unai` returns nothing.
Searching for `.o'unai.ui` returns 3.

Would that be a correct/meaningful behaviour ?

**Comment by lagleki** [comment]
2015-02-02 17:42 GMT+03:00 gillux <notifications@github.com>:

> @lagleki <https://github.com/lagleki> I’d like to clarify a point. You
> said the dot character should be interpreted as a word separator, just like
> space in English. But Lojban sentences combine space and one or multiple
> dots. But you also want to be able to look for keywords that contain a dot.
>
> So I made it so that words can be matched with dots only if fully
> qualified. Let’s say we have a corpus of these 3 sentences.
>
>    1. .ui.uenai
>    2. .ui do klama
>    3. .o'unai.ui zvati
>
> Searching for ui returns 1, 2 and 3.
> Searching for .ui returns 2.
>
{.ui} should return 1,2,3.

> Searching for o'unai returns 3.
> Searching for .o'unai returns nothing.
> Searching for .o'unai.ui returns 3.
>
> Would that be a correct/meaningful behaviour ?
>

It would. But as I explained earlier you can just replace /\./ with / /
(i.e. space) both in the strings of sentences and the in search string.

See above:
1. Symbol /./ is always replaced with " " (space) or with a word boundary
(sorry, I don't know how Sphinx works) both in the search request and in
the database searched

**Comment by jiru** [comment]
> It would. But as I explained earlier you can just replace /\./ with / / (i.e. space) both in the strings of sentences and the in search string.

That’s already the [current behaviour](http://tatoeba.org/sentences/search?from=jbo&to=und&query=ui). The dot character is considered as a word separator and you can’t distinguish looking up words containing dots or not. What puzzles me is the title you gave to that ticket: what’s wrong with the current implementation (except for the apostrophe)?

**Comment by lagleki** [comment]
2015-02-02 20:26 GMT+03:00 gillux <notifications@github.com>:

> It would. But as I explained earlier you can just replace /./ with / /
> (i.e. space) both in the strings of sentences and the in search string.
>
> That’s already the current behaviour
> <http://tatoeba.org/sentences/search?from=jbo&to=und&query=ui>. The dot
> character is considered as a word separator and you can’t distinguish
> looking up words containing dots or not. What puzzles me is the title you
> gave to that ticket: what’s wrong with the current implementation (except
> for the apostrophe)?
>

Oh my. Indeed it works. Did you change some settings and/or the code?

Thanks to those who did it because previously I couldn't search.

So yes, only the problem with apostrophe now persists.

**Comment by jiru** [comment]
> Oh my. Indeed it works. Did you change some settings and/or the code?

No, not that I can think of. But we speeded up reindexation of the corpus. Before, it could take weeks before a newly added sentence could be found by searching one of its keywords. Now, it only takes a maximum of 15 minutes.

**Comment by lagleki** [comment]
Should I close this issue and open a new one related to apostrophe?

2015-02-02 21:15 GMT+03:00 gillux <notifications@github.com>:

**Comment by jiru** [comment]
> Should I close this issue and open a new one related to apostrophe?

No, that’s okay. :-)

**Comment by jiru** [comment]
Pushed to production.
