### ISSUE TITLE
Invalid mail notification from comment on a deleted sentence

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#526]
More information on [tommy_san’s Wall post](http://tatoeba.org/jpn/wall/show_message/21130#message_21130).

I recieved a strange email notification when I posted a comment after deleting a sentence.

"Tatoeba - Comment on sentence : 削除されました

tommy_san has posted a comment on a sentence where you also
posted a comment.
http://tatoeba.org/sentence_com...75906#comments "

I usually don't get a notification about my comment.

Sorry, it seems that it happened not because the sentence has been deleted, but because I'd changed the email address.

By the way, it looks that it's technically possible to internationalize email notifications.
If we want to do that, we may need to let the users choose the language of notifications in the settings.

**Comment by RyckRichards** [comment]
**updating**
I wasn't able to reproduce that. I've tried that from many different ways (changing my emails all the time, setting my own mailbox to don't get emails from Tatoeba, disabling emails notifications) but it works perfectly. I think we can close this issue.

**Comment by jiru** [comment]
I am able to reproduce this bug. There are actually two bugs:
1. `$this->Auth->user('email')` isn’t updated after changing email address in your profile. That’s the reason why the email got sent, and also why it said "tommy_san has posted a comment on a sentence where you also posted a comment."
2. The subject of the notification email is wrong.
