### ISSUE TITLE
Reword unclear/incorrect UI strings

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#528]
This is a generic issue to reference and discuss strings that should be modified because they are unclear or incorrect.

**Comment by jiru** [comment]
There is a problem with sentences that include a language name when it’s "unknown language", in French, Finnish and probably other languages. We should provide separate sentences for all "unknown" or "other" language cases.

**Comment by jiru** [comment]
We may reword "unknown language" into "unsupported language" because it better fits the real purpose of the 'und' language. See #549.

**Comment by trang** [comment]
Just wondering, should we rename the language "Chinese" into "Mandarin Chinese" or "Chinese (Mandarin)"?

**Comment by allan-simon** [comment]
I guess most of people will be looking for Chinese (Mandarin) , in term of alphabetical order

**Comment by trang** [comment]
CK suggests to change the following message: 
"The user to whom you want to send this message does not exist."
into:
"There is no one with that username."

**Comment by tommy-3** [comment]
> CK suggests to change the following message: 
> "The user to whom you want to send this message does not exist."
> into:
> "There is no one with that username."

I think we need some more improvements.

Suppose you tried to send a private message to "TLANG, sisko, CK". What you get is this: http://prntscr.com/6e55ne.

There are two problems. The message you wrote is lost unless you go back to the previous page, and there's no error message about "sisko" (the second wrong username).

If CK is suggesting using "that username" instead of "the user TLANG", I'm against it, because a user needs to know which username(s) is/are wrong.

**Comment by tommy-3** [comment]
http://prntscr.com/6kkfu4
http://prntscr.com/6kkhnj
Now that we have an official feature to indicate the languages of users, they don't have to do it in the description. I think "TIP: Encourage this user to indicate the languages he or she knows." should be moved from under "No description." to under "No language added."

**Comment by jiru** [comment]
From [Guybrush88](https://tatoeba.org/jpn/wall/show_message/22455#message_22455) reports missing `<title>`:

* https://tatoeba.org/ita/users/for_language (on the tab name there is just "Users" even if the interface isn't in English)

* https://tatoeba.org/ita/contrib...meline/2015/04 (on the column on the right-side month names are localized, while on the top of the stats the month name isn't localized)

* when editing the language skill of a given language in my own profile, i see on the tab name just "User", and I'm using the UI in Italian

**Comment by alanfgh** [comment]
Some button labels are capitalized, and some are not. For instance, when replying to a message on the Wall, "cancel" is in lowercase but "Send" is capitalized. They should be consistent, preferably capitalized.

**Comment by trang** [comment]
Guybrush66 reported on the [Wall](https://tatoeba.org/eng/wall/show_message/22561#message_22561):

> I just saw another issue with translations, this time concerning Italian.
> This is how this string has been translated on Transifex: http://i.imgur.com/d9LqFFs.png
> This is how it actually appears on the website: http://i.imgur.com/fb0SYWr.png

**Comment by jiru** [comment]
I already fixed this in c88a615af2f9ebbee09b14236250139b8d41c693.

**Comment by alanfgh** [comment]
"Less translations" should be "Fewer translations".

**Comment by alanfgh** [comment]
In Transifex, does changing an English string mean that all the translations of its previous content will be lost, or is there some kind of translation memory that retains them? In Launchpad, the old translations were lost. Whenever I want to fix an English string (for instance, changing "Less translations" to "Fewer translations", as suggested in the previous comment), I always worry about this.

**Comment by jiru** [comment]
@alanfgh There is a translation memory. If the previous string (or any other string) is close enough, it will appear under the “Suggestions” tab. Otherwise, you can directly perform a search in the translation memory by clicking on the “Concordance Search” button.

**Comment by trang** [comment]
I'm closing this. It's better if we create issues for each string or group of strings that needs to be modified.
