### ISSUE TITLE
Feature request: "Translate" button in audio list

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#532]
To translate all sentences with audio e.g. from English one has to open
http://tatoeba.org/eng/sentences/with_audio/eng
and then open each sentence in a new tab.

It'd be nice if one could see "Translate" button near each sentence and thus start translating them immediately.

This is already possible when displaying sentences with a given tag.
What about sentence with audio?

This is IMO important since audio sentences are more likely to be of high quality in their style thus they are one of the first candidates for translation.

Isn't raising the quality one of the primary goals?

**Comment by trang** [comment]
I will close this as I don't think it would be worth cluttering the audio page by displaying the sentences with the whole sentence component.

The audio page is meant to listen to audio so just having the sentence and the audio button is enough. It can indeed happen that someone wants to translate a sentence while browsing the sentences with audio, but that should be an exceptional case. And for exceptional cases, it is fine to have to go to the sentence's page.

If someone wants to find sentences with audio to translate, they can use the advanced search. If we want to specifically promote the translation of sentences with audio, then we should add it as an option in the "Translate sentences" page. At the moment there is no clear evidence that we need to promote the translation of sentences with audio over other sentences.
