### ISSUE TITLE
Confusing links/unlinks in logs of merged sentences

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#535]
Not sure if it’s a bug the log of [this merged sentence](http://dev.tatoeba.org/eng/sentences/show/613428) is hardly understandable. It lists many unlinks followed by many links, which are all about the same sentences. So it looks like someone unlinked everything and linked everything back, spamming the logs with operations that changes nothing. In some [other sentence](http://dev.tatoeba.org/eng/sentences/show/1101027) the unlink happens after the link, which is even more confusing.

**Comment by loolmeh** [comment]
is this still relevant or should it be closed?

**Comment by trang** [comment]
Can be closed.
