### ISSUE TITLE
Add comment on the "main sentence" when duplicates are deleted

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#540]
After the duplicates of a sentence have been deleted, add the following comment on the remaining sentence:

> Duplicates of this sentence have been deleted:
> ✘ #{duplicate1}
> ✘ #{duplicate2}
> ✘ #{duplicate3}
> ...

**Comment by loolmeh** [comment]
sorry couldn't get mysql to like ✘, switched to x
c.f. this [madness] (http://dev.mysql.com/doc/refman/5.6/en/charset-unicode-utf8.html)

**Comment by tommy-3** [comment]
Is it possible to teach Horus to distinguish between singular and plural?

> Duplicates of this sentence have been deleted:
> x #2928338
This is grammatically not correct, is it?

**Comment by trang** [comment]
We could. But in this case I guess it would be easier to just change the text into "Duplicate(s) of this sentence...".
