### ISSUE TITLE
Missing Comment Input Field on some sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#543]
CK reported:

> http://tatoeba.org/eng/sentences/show/2626619
> Click Previous and Next in this area of the corpus to see others.
>
> The "logs" are messed up here, too, which may be a related problem.

**Comment by kwikadi** [comment]
I see no missing comment fields. Perhaps this issue has been fixed?

**Comment by trang** [comment]
Yea, can't reproduce. Closing.

@ckjpn, if you remember what was the problem and can reproduce this, feel free to re-open.
