### ISSUE TITLE
Add "Directly translated into:" field to the "Browse by language" page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#544]
On the Wall ( http://tatoeba.org/eng/wall/show_message/21257#message_21257 ), user ravas effectively asked the following:

"There is a way to see a list of Lojban sentences that do NOT have English translations, but is there a way to see only a list of Lojban sentences that HAVE English translations?"

I answered that we could either address an existing issue ticket (#53) that requests the ability to perform an advanced search, or add a "Directly translated into:" field to the "Browse by language" page, in which case there'd have to be a bit of logic to avoid contradictory settings (for example, setting both "Directly translated into:" and "Not directly translated into:" to the same language), or users would have to understand why they were getting an empty list. Also, perhaps it would slow down queries slightly, though it might well be offset by a gain in performance due to the smaller number of results we got back from the narrower queries.

**Comment by trang** [comment]
I think the advanced search was good enough for a solution. Closing this.
