### ISSUE TITLE
Rework the notes in the right-hand sidebar of the "Browse by language" page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#545]
Issues with the current sidebar:
- The notes below the "Show translations in:" drop-down ("NOTE: Both direct and indirect translations will be shown.") and the "Not directly translated into:" drop-down ("NOTE: Sentences that have an indirect translation will be displayed.") duplicate each other.
- There is nothing on the page to remind the user that the set of languages in which they see translations will be restricted to the ones they specified in their settings (if any).

Perhaps we could consolidate these notes, plus the one about sentences with audio ("NOTE: Not all languages have audio at the moment"), at the bottom of the page. We could also add a link to a wiki page if we need to.

**Comment by Poulpisator** [comment]
Is this still relevant?

**Comment by trang** [comment]
This point might still be relevant:

> There is nothing on the page to remind the user that the set of languages in which they see translations will be restricted to the ones they specified in their settings (if any).

But I'm not convinced that adding a note would be the most appropriate solution. The problem can occur in other places than on the "Browse by language" page.

I will close this. It's a quite old issue anyway.
