### ISSUE TITLE
Indicate the contributors of audio

### ISSUE THREAD

**Issue by tommy-3** [Tatoeba/tatoeba2#547]
Currently, there's no way to know who recorded which sentence. By indicating the contributors of audio, we'll be able to help learners interested in a specific accent and, above all, encourage more people to contribute audio.

This involves basically three things.
1. Sentence -> username
   On sentence pages, indicate the contributors of audio. The easiest way would be to change the alt text of the speaker icon to e.g. "Play audio recorded by TRANG".
2. Username -> sentences
   Make a page that lists the sentences recorded by a certain member and add a link to it on the profile of him/her.
3. Download
   Change the structure of the export file sentences_with_audio. It will look like "12345[tab]TRANG".

We could consider solving at the same time another issue #183 "allow multiple audio files per sentence". In that case:
1. Sentence -> username
   1.1. For a sentence with audio, show a number of recordings on the right of the speaker icon.
   1.2. When you click the speaker icon, one of the recordings (chosen randomly) are played.
   1.3. The alt text of the icon will be e.g. "Play audio #2 recorded by TRANG".
   1.4. When you click the number next to the speaker icon, a list of recordings appear below the sentence:
   **#1 2011-01-01 01:01:01 recorded by sysko [play icon]
   #2 2022-02-02 02:02:02 recorded by TRANG [play icon]**
2. Username -> sentences
   2.1. Make a page e.g. "Audio recorded by TRANG" and add a link to it on the profile of the member.
   2.2. The page will basically look like 1.4 above, but only the audio recorded by the user (TRANG in this case) are displayed:
   **C'était seulement il y a un an. [flag] [speaker icon] 2
   #2 2022-02-02 02:02:02 recorded by TRANG [play icon]**
   
   2.3. When you click the number next to the speaker icon, the other recordings will be displayed under those by TRANG.
3. Download
   The export file sentences_with_audio will look like "12345[tab]2[tab]TRANG", which means the audio #2 of the sentence #12345 was recorded by TRANG.
4. Filenames
   The filename of the audio #1 of the sentence #12345 will remain 12345.mp3. The filename of the audio #2 will be 12345_2.mp3.

I tried suggesting a concrete plan, but this is of course only one of many possibilities. I hope this will be the basis for further discussions.

**Comment by trang** [comment]
@tommy-3, I've just sent you the emails.

**Comment by jiru** [comment]
@trang can you make the mails available to us too?

@tommy-3 can you use like a shared google document or similar so that we may help out contacting people and gathering information?

**Comment by trang** [comment]
@jiru, done.

**Comment by tommy-3** [comment]
I idenfied most of the voices, but there are still some things I'm not sure about.
@allan-simon, could you reply to my email I sent to team@tatoeba.org?

**Comment by jiru** [comment]
Any news regarding this?

**Comment by tommy-3** [comment]
I uploaded what I've found out by now.
http://hi1811.agilityhoster.com/audio1.csv
http://hi1811.agilityhoster.com/audio2.csv

Some voices were identified based on the ID3 tags or the text files that CK makes before uploading files. I'm almost 100% sure about these.
Some others were identified based on wall posts and information provided by Trang and sysko. Sometimes I needed to make a guess a bit. See https://docs.google.com/document/d/1lTBIpguhhGxgz6926pqpwZiIgQeCmlVaCiAXDlMpAyw/edit?usp=sharing for details.

There still remain four contributors who haven't been identified. I'm waiting for @allan-simon to reply. I'll copy the four questions here:


[fra]
(1) 199 French recordings were added on 2012-01-14. Most of them are sentences owned by sacredceltic. Who recorded them? Trang says it might be Jean-Rémy Duboc.
http://tatoeba.org/user/profile/jrduboc
Sample: http://audio.tatoeba.org/sentences/fra/1337232.mp3

[nld]
(2) 1026 Dutch recordings were added on 2010-12-05. They are all sentences owned by Dorenda. Who recorded them?
Sample: http://audio.tatoeba.org/sentences/nld/377450.mp3

[por]
(3) 94 Portuguese recordings were added on 2011-01-19. They are all sentences owned by brauliobezerra. Were they recorded by brauliobezerra?
Sample: http://audio.tatoeba.org/sentences/por/579858.mp3

(These are the oldest Portuguese audio files. I know from sysko's Wall message #7801 on 2011-09-14 that he's from Brazil. I believe all the other Portuguese recordings are by alexmarcelo, added between 2011-09-21 and 2011-10-23.)

[spa]
(4) 103 Spanish recordings were added on 2012-01-16. They are all sentences owned by tatoerique. Were they recorded by tatoerique?
Sample: http://audio.tatoeba.org/sentences/spa/11030.mp3


There are three more small issues.

(5) Pongprapunt, the contributor of Thai audio, doesn't seem to have a Tatoeba account. I think I'll ask him to make one.

(6) I think I'll ask Inego's wife to make a Tatoeba account.

(7) How should we deal with Barack Obama's voice?
http://audio.tatoeba.org/sentences/eng/896662.mp3
http://audio.tatoeba.org/sentences/eng/897923.mp3
http://audio.tatoeba.org/sentences/eng/897924.mp3
http://audio.tatoeba.org/sentences/eng/897925.mp3
http://audio.tatoeba.org/sentences/eng/897909.mp3


Trang said (in an email on January 23) that we'll let each user choose a license.
I think we can provide two options we recommend: Creative Commons Attribution (CC BY) 4.0 International License and Creative Commons Attribution-NonCommercial (CC BY-NC) 4.0 International License.
(The Creative Commons recommends that we use a version 4.0 international license.
https://wiki.creativecommons.org/Frequently_Asked_Questions#Why_should_I_use_the_latest_version_of_the_Creative_Commons_licenses.3F
https://wiki.creativecommons.org/Frequently_Asked_Questions#Should_I_choose_an_international_license_or_a_ported_license.3F)
Users can also choose any other license of any version if they want. They can also choose not to license the files at all, which means only the visitors of Tatoeba.org can listen to them.

And then the license of each file should be shown everywhere near the speaker icon, and we'll also need a list of audio contributors and the licenses on the download page.


I think we should make the new terms of use before contacting the members.
This doesn't seem to belong to the current issue, so I wrote about it here.
https://groups.google.com/forum/#!topic/tatoebaproject/CF1YcspnWes

**Comment by ckjpn** [comment]
This is listed as "effort:high."
However, if you could figure out a way to display my private "audio" lists on the pages the same way you have collaborative lists showing, then members could easily see this information.  This might not be the best way to do it, but it might be a fast temporary fix.

What I mean is all the lists of mine that begin with "audio - ".

The search doesn't narrow it down, since it's not case-sensitive, and ignores the hyphen.
This link jumps you to the 2nd page, so you'll see which lists I'm talking about.
https://tatoeba.org/eng/sentences_lists/of_user/CK/audio%20-/page:2

**Comment by RyckRichards** [comment]
Tatoeba day No.1
https://tatoeba.org/eng/wall/show_message/22954#message_22954

**Comment by ckjpn** [comment]
As mentioned on Jul 25, 2015, this would be a relatively easy thing to do, if you could somehow display my lists of audio contributors.  Currently, all private lists are hidden to everyone except the owner of the lists.  Since I'm the owner of these lists, I can easily see who contributed each audio file.  If you could include these list names on each page so they are viewable by everyone, then this issue could be closed.

**Comment by trang** [comment]
> this would be a relatively easy thing to do, if you could somehow display my lists of audio contributors.

When #677 will be released on the prod, you will be able to set your audio lists as publicly viewable.

**Comment by trang** [comment]
> When #677 will be released on the prod, you will be able to set your audio lists as publicly viewable.

I'm rectifying this statement. Setting your lists to "public" will not be a solution. While implementing the private lists feature, I decided to remove the display of lists on the sentences page except for lists that belong to the user.

As a temporary solution for users to see who contributed each audio file, you could consider adding tags ("audio by {user}").

**Comment by ckjpn** [comment]
> As a temporary solution for users to see who contributed each audio file, you could consider adding tags ("audio by {user}").

Is this something you want me to do?

I can write a script that will do that tagging via the web interface.

Perhaps you could take my audio lists and do that tagging faster in the database.  I could then, just add tags using the same script I use to update the lists every time new audio files are added.

Or, we could just wait until you come up with another solution for letting people know who recorded the audio on a sentence's page.  That's fine with me, too.  At this point, people like me who may need the information for other projects can easily get the sentence numbers in the exported data from my lists.  The list titles clearly give the licensing information and attribution URL for the ones that are available for use off tatoeba.org.  (Perhaps, if you add tags, the tag names should include this, too.  However, that might make the tag names too long.)

You can use my lists in the process of developing a new system when you have time to develop one.

**Comment by trang** [comment]
> Is this something you want me to do?

For me it doesn't change anything. I think the lists are enough.

I can't speak for other users but so far nobody requested this.

**Comment by ckjpn** [comment]
I'll plan to leave things as they are.  I think for now lists are enough.  It's enough for me anyway.

Tommy requested to know who recorded sentences.
I assume he means that when he's on a sentence's page, he wants to know who recorded it.

**Comment by tommy-3** [comment]
I think it should be easier for users to know who contributed the audio in order to motivate people to add more audio.

Contributors of sentences are motivated by the reactions we get from other users. We get questions about our sentences, we learn about our mistakes and we get our sentences translated. Users might visit our personal websites or even send us fan letters. That's all because other users can easily know who wrote each sentence.

Contributors of audio would rarely get any of these because there's little chance that users find out who recorded each sentence. Perhaps a lot of users assume that it's the voice of the owner of the sentence. Even if they know that's not the case, when they have something to say about audio, it's most likely that they write comments on sentence pages. In most cases, the owners respond to them and the contributors of audio don't even know their audio is being discussed. They're virtually placed outside the community of Tatoeba.

When I opened this issue, I was trying to find someone who would record our Japanese sentences. I had to tell them that the website was not at all nice to contributors of audio, that we didn't credit them on sentence pages. Naturally, most of them didn't want to take part in such a project.

**Comment by ckjpn** [comment]
I agree with a lot of what Tommy says here.

It would be nice to have some way to do the following.

1. Show who recorded the audio on each sentence's page.  Minimally, this could just be a mouse-over like the tags are being done now, but maybe you'd want to make it more obvious.
2. Show the number of audio contributed by each member in this profile the same way the number of sentences is listed.
3. Be able to list all sentences with audio by a member from the profile in the same way we can list all sentences by a member.
4. Have the name of the contributor of each audio file included in the exported data. it could be the second "field" of  sentences_with_audio.tar.

I think all of these ideas fit in with the overall design of the Tatoeba Project.

**Comment by jiru** [comment]
I’m working on this.

**Comment by ckjpn** [comment]
I wonder if it would be possible to also create something like the following to go along with this.

http://aitech.ac.jp/~iteslj/a4esl/temporary/tatoeba/lists/audio.html

**Comment by jiru** [comment]
I made some good progress on this.

@ckjpn I will be using [your audio lists](https://tatoeba.org/eng/sentences_lists/of_user/CK/audio%20-) to fill the database with audio authors. I copied the data (list ids, authors and licence) to a script that will be executed when this feature will be installed on the production server. So, please keep me updated with any modification you make to your lists, i.e. any new list, and licence or author update.

@tommy-3’s CSV files disappeared, but I wonder how much of your findings are already integrated into CK’s lists?

@ckjpn I performed a few sanity check on your lists.
* 99 sentences don’t have audio while being in an audio list
* 2520 sentences have audio while not being in any audio list

But these inconsistencies do not prevent this feature from being implemented. Recordings for which we don’t know the author will simply display like now. We can add the actual authors later.

Note that, as a first step, I will stick on displaying the audio contributors only (on the tooltip of the play button and profile pages), while laying the foundations for other fancy stuff in the future like multiple audios, speaker’s origin, the page ckjpn just suggested etc.

@ckjpn I have a few other questions.
* Many of your list titles mention *no license for offsite use*. I’m looking for an short identifier for this, just like we have *CC BY 4.0* for *Creative Commons Attribution 4.0 International*. Any idea?
* What about the licence of some very recently contributed audios, like Dusun_Les's, civiricus's or even amastan's?
* About the attribution URL. On some lists, you use a link to the profile, whereas on some other you say *no attribution URL* while an account exists for that name. Is it on purpose? Is Barack Obama’s attribution URL still valid, now he’s not leaving at the White House anymore? Other audio contributors seem to all have a Tatoeba account, so we may as well use their profile page as attribution URL. Giving all this, does it make any sense to allow using a specific attribution URL other than the profile page?

**Comment by ckjpn** [comment]
* I put "no attribution URL" for everyone who hasn't licensed their audio files for external use.
* My attribution URL is www.manythings.org/tatoeba and not my profile on tatoeba.org, since I set this up a long time ago.
* I've written PMs to everyone, I think, asking them if they would consider a CC license.  Many have not responded.
* If you could email me a list of all MP3 files in directories along with their time stamps, I might be able to at least group them together by voice.
* If you could also, email me the 99 sentences list, and the 2,520 sentences list, I could check the numbers and see what's wrong with them.

Perhaps eventually, something like this could be do to identify the person who recorded the audio..
http://www.manythings.org/audiosentences/rus/171.html

**Comment by ckjpn** [comment]
> @tommy-3’s CSV files disappeared, but I wonder how much of your findings are already integrated into CK’s lists?

I used his data to help me do my lists, so I don't think anything got lost.

**Comment by ckjpn** [comment]
> . I copied the data (list ids, authors and licence)

Please include the country/dialect data, too. For some languages, it may not matter so much, but for others it does.

**Comment by jiru** [comment]
> Please include the country/dialect data, too.
By this, do you mean checking the member’s profiles to get their country/region?

**Comment by trang** [comment]
> Many of your list titles mention no license for offsite use. I’m looking for an short identifier for this, just like we have CC BY 4.0 for Creative Commons Attribution 4.0 International. Any idea?

I would just set the license to `null` in this case. `null` would mean:
1. The contributor of the audio has not given any information about who else can reuse the audio, in which case we consider that the audio is only for Tatoeba. 
2. The contributor has specifically said they want the audio to be used only on Tatoeba. Which is the same result as above.

If we really need to make a distinction between case 1 and case 2, then:
1. no info on license = `null`
2. audio only for tatoeba = `tatoeba`

But I can't think of a situation where we would need to make this distinction.
