### ISSUE TITLE
Provide a link to static wiki pages while the main wiki is not accessible

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#551]
Currently, our wiki, which is on a site that we don't own, has been down for weeks. This means that all our FAQ and help pages cannot be read. For now, we should link to the static pages that CK produced from our wiki in April 2014.

**Comment by alanfgh** [comment]
The wiki's back up, so I'm going to decrease the priority on this and change it to an enhancement.

**Comment by trang** [comment]
I believe this issue is no longer needed. We moved the wiki from the old server to our server in June 2015.
