### ISSUE TITLE
Add script or role to cover the wiki

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#552]
lool0 says we should make a script or a role to cover the wiki like the other daemons, and maybe we should move it away from the machine on which the wiki is hosted. We'll need a script to compile and configure it, and a reverse proxy configuration in our current nginx config file. Then we can just backup the sqlite file and move it to the main server and change the dns pointing to the wiki. This should save us future wiki headaches. Also, liori's backups should cover the wiki.

**Comment by trang** [comment]
I believe this issue is no longer needed. We moved the wiki from the old server to our server in June 2015.
