### ISSUE TITLE
Redesign sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#556]
Cf. http://tatoeba.org/eng/wall/show_message/21475#message_21475

> The initial goal of the redesign was to make the text of the sentences non clickable, so that users can easily copy-paste more easily a part of a sentence. That's why sentence and "#" or the arrow icon are highlighted on hover. Because now you need to click on the icon to navigate to the sentence (instead of clicking on the sentence itself).

> There is one thing not done yet, and I'm not sure when I will do it, but my plan is to remove the "edit in place" mechanism of the main sentence, and replace it by an "edit" button. In other words, it means that to edit a sentence, instead of clicking on the sentence itself to open the text input, you will have to click on an "edit" button (that would be placed next to the "translate" button).

> I've changed all the icons because I'm slowly trying to transition towards SVG images. Since I could not find a good SVG for the adopt/unadopt feature, I decided to take a lock icon for it. That's why you will see a lock icon next to the owner username, and this lock icon is clickable if you are the owner (so that you can unadopt) or if there is no owner (so that you can adopt).

Commits already done:
* 3e5217a64f9b22bb05089b4ac07298cc7d1b3d7d
* 982d90145bf2e0df030e100819d57be468859ad2
* ac3a62bb01b4a7098d727529bebbeda2b0a09696
* 76be12a0b977426eaae5e49c62ae9af2f33d4c6b
* 1b4bd78c8c03caa56e7b48076e6d98329b30cdf8

**Comment by jiru** [comment]
On the wiki, [the icon images between parenthesis are now missing](http://en.wiki.tatoeba.org/articles/show/quick-start). The problem extends to all the translations of this page.
