### ISSUE TITLE
Language selector doesn't render well

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#559]
Reported by Guybrush88.
http://tatoeba.org/eng/wall/show_message/21561#message_21561

> It appears that the interface localization menu (the dropdown menu listing the languages in which the interface is translated into) is badly rendered on Firefox 35.0 on Ubuntu 14.10: http://i57.tinypic.com/2przqzo.png

> Every language name is displayed as in the screenshot, and in any page of the website

There are also issues regarding the random sentence language selector, in some languages the height expands to take 2 lines: http://prntscr.com/5vl5rl

**Comment by jiru** [comment]
Now you mention it, it doesn’t render well on my browser too (Firefox 28, Linux). The very bottom of the text is clipped. Look at the g letter on this screenshot, and the little arrow bottom-right. And compare with the search language selectors.
![ui_language_selector](https://cloud.githubusercontent.com/assets/5107734/5862772/c69cacaa-a2b7-11e4-9c3c-0e8d7b571102.png)
