### ISSUE TITLE
Multiple queries sent when changing a language multiple times

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#566]
Steps to reproduce:
1. Go to a sentence on which you can change the language.
2. Open your favourite dev tool/inspector to scan queries sent by the browser (ctrl-shift-C on Firefox)
3. Change the language of the sentence. You’ll notice one POST query.
4. Change the language of the sentence again. You’ll notice two POST queries.
5. Change the language of the sentence again. You’ll notice four POST queries.

The function executed on language change gets rebinded each time by the response itself.

**Comment by RyckRichards** [comment]
Mentioned by Guybrush88 on [Tatoeba Day #9](https://tatoeba.org/eng/wall/show_message/24479#message_24479).

**Comment by ventice** [comment]
Looks like this issue is already fixed since I can see `$(".languageFlag").unbind('click');` at the beginning of the click handler.

**Comment by ventice** [comment]
Just reproduced it. Taking.
