### ISSUE TITLE
In the top menu, make "Browse" item non clickable

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#570]
At the moment, the "Browse" item in the top menu is clickable (the one between "Home" and "Contribute"). Clicking on it goes to a random sentence's page.

This behavior prevents people on mobile devices to access the sub-items of the "Browse" category, because as soon as they tap on "Browse", it redirects them to a random sentence's page. They cannot tap to display the list of sub-items.
On desktop it's not a problem because users can hover their mouse over "Browse" and it displays the sub-items (Browse by language, Browse by list, etc).

We need to make the "Browse" item non clickable, and add a new sub-item ~~"Browse by sentence number"~~ "Random sentence" which will redirect to a random sentence's page.

**Comment by jiru** [comment]
How about calling that new submenu entry “Random sentence”, if it actually redirects to a random sentence? One can go to a sentence by number from any sentence page.

**Comment by trang** [comment]
Yes, true. We can call it "Random sentence".

**Comment by jiru** [comment]
And we need to turn the “Browse” top menu item unhighlighted when on a random sentence page. (It’s currently in bold bigger and bold font.)

**Comment by wallflower1** [comment]
"contribute" option has a similar issue i guess, tapping on it redirects to http://tatoeba.org/eng/contribute, which further enlists the options in the drop down. Or is it the way it is meant to be?

**Comment by trang** [comment]
Yes, the "Contribute" item has kind of the same issue. But on the page of "Contribute" you actually have the links to the sub-items: http://prntscr.com/627hdn
So mobile users can somehow still navigate to "Add sentence", "Translate sentence", etc.

Honestly I don't think much people read the text on the Contribute page, and it can surely be deleted. But for now we'll leave it like this.

**Comment by tommy-3** [comment]
On the Opera browser for Android, the sub-items don't appear by tapping on "Browse", "Contribute" and "More", so I find the "Contribute" page useful, and I was hoping that there were the same kinds of pages for "Browse" and "More" as well. If you delete the "Contribute" page, you'll need to fix this problem.

**Comment by trang** [comment]
@tommy-3 Ah they don't? We will need to figure out how to make it work on Opera browser for mobiles then. But that's gonna be for another issue.
