### ISSUE TITLE
Make the translations collapsible

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#572]
Some sentences have a lot of translations, like the [sentence #1](http://tatoeba.org/eng/sentences/show/1).

It would be nice to display only a limited number of translations (perhaps 5 max), and if there are more translations, have a link "More translations" / "Less translations" to expand/collapse the list of translations.

This has been mentioned by some users (tommy_san and Vortarulo) here: http://tatoeba.org/eng/wall/show_message/21157#message_21157

**Comment by wallflower1** [comment]
@trang I have solved the issues reported by CK and Sabretou related to the link not working on certain pages.
