### ISSUE TITLE
Prevent the creation of sentences with empty language code

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#573]
We currently have 15 sentences with an empty language, created between 2014-11-04 and 2015-02-03: [#3605777](http://tatoeba.org/sentences/show/3605777) [#3605799](http://tatoeba.org/sentences/show/3605799) [#3605805](http://tatoeba.org/sentences/show/3605805) [#3605814](http://tatoeba.org/sentences/show/3605814) [#3605837](http://tatoeba.org/sentences/show/3605837) [#3649583](http://tatoeba.org/sentences/show/3649583) [#3692818](http://tatoeba.org/sentences/show/3692818)
[#3710552](http://tatoeba.org/sentences/show/3710552) [#3712361](http://tatoeba.org/sentences/show/3712361) [#3740902](http://tatoeba.org/sentences/show/3740902)
[#3772693](http://tatoeba.org/sentences/show/3772693) [#3788084](http://tatoeba.org/sentences/show/3788084) [#3805787](http://tatoeba.org/sentences/show/3805787)
[#3835880](http://tatoeba.org/sentences/show/3835880) [#3836168](http://tatoeba.org/sentences/show/3836168)

For data consistency, sentences with unknown language should have their language code as null instead of an empty string. The goal of this ticket is to find out how these have been created and to prevent their creation. And to fix the existing sentences in the database.

**Comment by RyckRichards** [comment]
-update-
it's not more possible to add sentences with a null code. all the 15 languages which sentences were mentioned have been added and now, one native of a language not yet supported on Tatoeba can only post sentences after updating his/her profile and is advised to call cueyayotl, NM30 and me in order to have it added.

**Comment by trang** [comment]
Seems like we indeed no longer have sentences with empty language code.
```
MariaDB [tatoeba]> select count(*) from sentences where lang = '';
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

Closing.
