### ISSUE TITLE
Database lacks sinogram information for the hanzi/kanji search tool

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#574]
The tables sinogram_subglyphs and sinograms are initialized as empty. Only the production server has the data. As a result, developers can’t test the [hanzi/kanji search tool](http://tatoeba.org/tools/search_hanzi_kanji) on their local installations.

@allan-simon Since you’re the original author, I’d like you to confirm it’s okay to distribute that data along with the Tatoeba source code.

**Comment by trang** [comment]
@jiru, the data you're mentioning is (I believe) in the files in `/docs/database/import/sinogram_subglyphs.sql` and `/docs/database/import/sinograms.sql`. So it's already distributed along with Tatoeba source code.

**Comment by loolmeh** [comment]
it's taken from wikimedia afaik http://commons.wikimedia.org/wiki/Commons:Chinese_characters_decomposition so cc-by-sa

adding this to the next release of the premade vm
