### ISSUE TITLE
Email validation is broken

### ISSUE THREAD

**Issue by DudeNamedBen** [Tatoeba/tatoeba2#579]
The email validation does not accept the new ".technology" TLD as a valid domain. Therefore all mail addresses following the pattern "random.name@exampel.technology" are marked as invalid. I have not tested it with other new domains because I only own a technology one but I would suspect that the validation also doesn't work for any of the other new domains.

A list of new domain can be found here: http://newgtlds.icann.org/en/program-status/delegated-strings

**Comment by Ppjet6** [comment]
I didn't check how it's actually processed, but the field is still of type "text". Maybe we could change that for "email", and 

Personally I'm not really found of filtering email addresses, I think they should be tested and see what happens, (being careful though so it's not used to spam).

**Comment by trang** [comment]
Yes we could change the type to "email".

The regex to validate the email is here by the way:
https://github.com/Tatoeba/tatoeba2/blob/dev/app/webroot/js/users.check_registration.js#L114

**Comment by wallflower1** [comment]
So, from what i read, CakePHP (v1.3) form helper does not have support for input type 'email'. There is no mention in the documentation. When i forced the type 'email' in the form, it returned a 'textarea' input type in the browser (pretty weird). I found a solution here : http://www.curtisgibby.com/blog/2011/07/html5-form-inputs-in-cakephp-1-2/ 
haven't tested it though. Also, from what i checked, only two pages are using email validation, Register and user/settings, is that correct?
