### ISSUE TITLE
Edit button to edit sentence

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#580]
A user can currently edit a sentence by clicking on it (edit-in-place). We want to change this mechanism and have instead an edit button to open the form.

The problem with edit-in-place is that when a user simply wants to copy-paste the text of a sentence, if they have the permissions to edit the sentence, it will open the edit form as soon as they click on it. 

This affects especially corpus maintainers and admins because they can edit all the sentences.

* For the edit icon, we could use this one: https://www.iconfinder.com/icons/284087/edit_editor_pen_pencil_write_icon#size=128
* You can place the icon between the "translate" and "favorite" icon.
* The icon should not be displayed if the user is not the owner of the sentence, or is not a corpus maintainer, or is not an admin.
* In the cases where the button is displayed, it needs to be disabled if the sentence has audio.
* It's also a good occasion to improve the look of the edit form (currently looks like this: http://prntscr.com/62s447).

**Comment by kwikadi** [comment]
I tried to replicate the problem, but I wasn't able to, with admin/123 as credentials. I'm on windows, with the 2010 database. Do I need some other credentials to replicate it?

**Comment by jiru** [comment]
@kwikadi The password is 123456.

**Comment by trang** [comment]
In my database the password is 123, but you have to log in with one of the
admins listed on the Members page (admin is not an existing user).

Actually with my username (trang) the password is 1234.

**Comment by kwikadi** [comment]
I fixed most of the issue, but found out that apparently, (http://stackoverflow.com/questions/3771169/in-cakephp-why-would-this-paramsform-be-empty-if-ive-just-posted-a-form) if I use a form helper, data will be posted to $this->params['data'] while /sentences/edit_sentence checks $this->params ['form'].
(https://github.com/Tatoeba/tatoeba2/blob/e09aaa79298dbeee440be8e1e0cd1d9c26995c12/app/controllers/sentences_controller.php#L351). A quick grep reveals that this method is referenced in few other places, most of them from inside the 'tests' directory. https://github.com/Tatoeba/tatoeba2/search?utf8=%E2%9C%93&q=edit_sentence
I could simply change ['form'] to ['data'] inside edit_sentences(), but I'm not completely sure if it would break test builds/the database or not. I was hoping you could tell me where to go from here.

Also, is isTrusted() sufficient to display the edit button? ( I couldn't find any documentation on who passes the isTrusted() check)

**Comment by jiru** [comment]
> but I'm not completely sure if it would break test builds/the database or not.

It won’t break the database. It may break the tests, I don’t know. Just try to run them using:
`../cake/console/cake testsuite app case controllers/sentences_controller` from within the `app` directory.

> Also, is isTrusted() sufficient to display the edit button? ( I couldn't find any documentation on who passes the isTrusted() check)

No. isTrusted() checks if the user is an advanced contributor. You want to use canEditSentenceOfUser() or canEditSentenceOfUserId().

**Comment by kwikadi** [comment]
Turns out I was just doing something wrong, it all worked out without me having to change anything in edit_sentences(). 
Thanks a lot for the canEditSentenceOfUser method too.
