### ISSUE TITLE
Sentences are no longer clickable in framed view

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#585]
In the [framed view](http://tatoeba.org/s/s/123), a text suggest to click on sentences, but they are not clickable anymore. We should either remove the text or make the sentence clickable.

**Comment by trang** [comment]
Suggestions from CK.

---------------

**1.** Remove the message at the bottom of the page.

Click a sentence to go to tatoeba.org to translate it or leave a comment.

**2.** Put the link to the main sentence at the bottom of the page.

http://tatoeba.org/eng/sentences/show/42189
Where currently, this message is.

Click a sentence to go to tatoeba.org to translate it or leave a comment.

Maybe with one of this messages as the clickable part of the link.

Go to the Sentence #42189 to translate or leave a comment.
... or ...
Translate or leave a comment on this sentence.
... or ...
See the full page for this sentence.

(Perhaps the last one is the best.)

**3.** Make just the first sentence clickable to the main sentence page.

http://tatoeba.org/eng/sentences/show/42189

... and change the message to....

Click the top sentence to go to tatoeba.org to translate it or leave a comment.

---------------

CK prefers solution 3.
