### ISSUE TITLE
Pagination and sort by name/count for list of tags

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#588]
The [tags page](http://tatoeba.org/eng/tags/view_all) currently displays all the tags on one page. They are ordered by count (i.e. number of sentences tagged with the tag).

Since we now have a lot of tags, the page is quite heavy and takes too long to load for what it's worth.

We should add some pagination (perhaps 50 tags per page), as well as the possibility to order by name or by count.

We should also display tags in a table, with the columns "Tag name" and "Count" (not sure if "Count" is the best wording).

**Comment by jiru** [comment]
Note that before, we were able to search for tags by searching for text within the page with all the tags. It’s not possible any more.

**Comment by trang** [comment]
Yes, planning to create a separate issue for that. We'll need to implement a search feature for the tags. And same thing for the lists actuallly.
