### ISSUE TITLE
Use HtmlHelper tag() or div() instead of hardcoded HTML

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#595]
Check all the code and when possible, replace things like:
`echo '<p>' . $something . '</p>';`
into:
`echo $this->Html->tag('span', $something);`

If it's a div, there's a `div()` method for it.

Doc:
http://api.cakephp.org/1.3/class-HtmlHelper.html#_tag
http://api.cakephp.org/1.3/class-HtmlHelper.html#_div

--------------

When the text to display is the text of a sentence from the corpus, use the `tagWithLang()` method from the (LanguagesHelper)[https://github.com/Tatoeba/tatoeba2/blob/dev/app/views/helpers/languages.php#L792].

Generally speaking, use `tagWithLang()` when you know the language of the text, and the language is not the language of the interface.

**Comment by jiru** [comment]
And each we add a `tag()` or similar, we need to figure out if the contents needs to be HTML-escaped (the default) or not (add 'escape' => false). Wherever we manually escape the contents with Sanitize::html() or similar, we’d better use the helper function escape instead ([example](https://github.com/Tatoeba/tatoeba2/commit/6e34238de2f1e1cdc6a225a1e614409989412b2a#diff-ecd1ed32cd1f0cc0207bdbc41693f42aL258)).

**Comment by loolmeh** [comment]
I really think maybe it's time to let go of these helpers completely if you guys are thinking of putting efforts into this and use a real templating system like twig. It'll at least help decouple logic from the views/html/css/js so we can start centralizing assets and offering a proper build for use in production.

**Comment by trang** [comment]
Closing this. It's more of a coding convention than an issue.
