### ISSUE TITLE
Include thegui’s translations visualization in Tatoeba

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#598]
See the [original post](http://tatoeba.org/wall/show_message/21926#message_21926). We should integrate that graph into Tatoeba.

**Comment by trang** [comment]
I love data visualization but I think we will have to keep such things outside of Tatoeba.

I have however created a Wiki page to list [projects that use Tatoeba](https://en.wiki.tatoeba.org/articles/show/projects-using-tatoeba), and put it there.
