### ISSUE TITLE
Arabic (Syrian) (= North Levantine Arabic?)

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#6]
* Language name: Arabic (Syrian) // (= North Levantine Arabic?)
* Language info: ?
https://en.wikipedia.org/w/index.php?search=Arabic+%28Syrian%29&title=Special%3ASearch&go=Go
https://en.wikipedia.org/wiki/Levantine_Arabic
Arabic (Syrian)
https://www.google.com.br/search?q=Arabic+%28Syrian%29&ie=utf-8&oe=utf-8&gws_rd=cr&ei=C8oXVvu-D4OywASPyqXABA#q=north+levantine+arabic+language
I didn't fin anything about  North Levantine Arabic

* ISO 639-3 code: ?
* Public List: ?[No list](https://tatoeba.org/eng/sentences_lists/index/North Levantine Arabic), [no list](https://tatoeba.org/eng/sentences_lists/index/Arabic%20Syrian)
* Icon: https://dl.dropboxusercontent.com/u/953908/images/syrian_30x20.jpg
* Requested by: http://www.tatoeba.org/eng/user/profile/dpsilver7
* More info about the request: https://www.assembla.com/spaces/tatoeba2/tickets/435#/activity/ticket

quote of email from dpsilver7
> Ar / ara (Syrian Accent) (it's not classic Arabic, no one speaks Classic Arabic anymore!! :D, it's vernacular, all Arabs and most foreigners I know (that were learning Arabic) wanted to learn Syrian Accent.

**Comment by RyckRichards** [comment]
Too many important information needed. I'm going to post about it on the wall. If nobody answers, we should delete this ticket, I think...

**Comment by RyckRichards** [comment]
My message on the wall: https://tatoeba.org/eng/wall/index#message_24457

**Comment by sabretou** [comment]
The ISO 639-3 code for North Levantine Arabic is 'apc'. It is listed on the Wikipedia article linked.

That said, seeing as there is no relevant list created for this language, I'd just drop this ticket entirely.

**Comment by trang** [comment]
Yea, I'm closing this.
