### ISSUE TITLE
For a given sentence, offer a way to display the lists to which it belongs

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#602]
Here's my use case: When I come across a sentence that has vocabulary I want to learn, I add it to a list: list 1, list 2, etc. I keep each list limited to 100 words so that it can be downloaded. Sometimes I come across a sentence that seems familiar, but I can't remember whether I added it to one of the lists. Browsing by list and performing a sequential linear search for the sentence across all the lists is not practical.

I'm most interested in whether a sentence belongs to one of my own lists. But seeing whether it's used in any list belonging to any user doesn't hurt, and might be helpful in other use cases.

**Comment by ckjpn** [comment]
> Sometimes I come across a sentence that seems familiar, but I can't remember whether I added it to one of the lists. 

Note that it doesn't hurt to add a sentence to the same list again.
It only gets listed once, so you're not creating duplicates on a list.

When I'm going through lists of sentences, I often just go ahead and add a sentence to any appropriate list.  When viewing a list of sentences, it's faster to do this than to go to a sentence's page to see if it's already been added, or not.
