### ISSUE TITLE
Add language: Khasi (kha, 4156)

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#606]
Requested by Russell_Ranae, who according to cueyayotl is a native speaker.

**Comment by trang** [comment]
@alanfgh I'm changing the milestone to next week since I already did the update.

**Comment by alanfgh** [comment]
Actually, I closed this, but I committed the files from the dev machine, so git assumed that it was Trang who did it. I'd rather not bother with changing the author of the commit.
