### ISSUE TITLE
Add auto-increment to id properties for various tables

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#607]
Here are the ones that are missing it:

countries, favorites_users, sentences_sentences_lists, sinogram_subglyphs, sinograms, sphinx_delta, wall_threads_last_message

**Comment by trang** [comment]
* countries → table has been deleted
* favorites_users → done
* sentences_sentences_lists → done
* sinogram_subglyphs, sinograms → not needed
* sphinx_delta → not needed
* wall_threads_last_message → id must not be auto-incremented, I think
