### ISSUE TITLE
Update language addition procedure

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#610]
Since 204a25ef we have a new language array. We should update the `add_lang.sh` script and the [wiki page](http://en.wiki.tatoeba.org/articles/show/adding-lang-to-corpus) accordingly. Note that only some of the languages have an entry in this array: the ones that have a 2-letter code equivalent. See the commit message.

**Comment by alanfgh** [comment]
We could handle this in one of two ways:
(1) write a message to the console reminding the person who ran it to manually update $iso639_3_to_iso639_1 in app/views/helpers/languages.php
(2) automatically update the array

Number (2) would require not only that add_lang.sh take an additional parameter (the 2-letter code equivalent or a flag indicating that there isn't any), but that it be inserted into the array at the correct position. Unlike the other arrays updated by add_lang.sh, this array is sorted alphabetically, so it's not a simple matter of looking for a comment at the end of the array and inserting the line there.

I'll go with (1) for now.

**Comment by jiru** [comment]
This new array is sorted alphabetically only for convenience. One can
just add a new language at the end if it ease automatic insertion. But
please go for (1) because I don’t feel like updating add_lang.sh. Thank
you.
