### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by jberkel** [Tatoeba/tatoeba2#616]
Currently the password is transferred in plain text over HTTP which is a big security risk. Compromising the tatoeba account itself might not be a huge problem but a lot of users reuse passwords.

![captura de tela 2015-03-15 14 34 33](https://cloud.githubusercontent.com/assets/18891/6656376/79e8c600-cb20-11e4-8875-6fb15dabeeca.png)

**Comment by jberkel** [comment]
Let me know if there's anything I can do to help, but it looks like it's more of a deployment issue than code.

**Comment by trang** [comment]
Thank you @jberkel, we should be fine :)

Working on it this weekend.

**Comment by jiru** [comment]
Note that audio is currently broken under HTTPS because it produces mixed content. Both static.tatoeba.org (that holds the flash player) and audio.tatoeba.org (that holds the mp3s) needs to be made available under HTTPS too.
