### ISSUE TITLE
Add option to restrict "From" and "To" languages in a query to the ones in your profile

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#634]
There would be a checkbox on one's profile (unchecked by default) to control this behavior.

**Comment by alanfgh** [comment]
Commented out the active part of this change until it is controlled by a setting.

**Comment by jiru** [comment]
I’m concerned about the growing number of very specific options like this one. How about displaying the profile languages on the top of the drop down, and then the rest? We could use something like [optgroup](http://www.w3schools.com/tags/tag_optgroup.asp).

**Comment by trang** [comment]
I'm not too worried about the number of options increasing, we still have a reasonable number of options.

What bothers me more is that some options are saved in the database and others are saved in the cookies, and we don't distinguish them, nor do we make it clear for the users. They might be confused to see some of their options disappear when they visit Tatoeba from another computer. But that's another problem.

Using optgroup sounds like a good idea. It would be a good compromise for people who want to easily select one of the languages that they know, while still having the whole list of languages. We can consider it in a future update. For now, I think the way Alan is implementing it is alright.
