### ISSUE TITLE
fix right-to-left sentences with terminal punctuation at the wrong end

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#637]
0x21: exclamation mark 
0x2E: period
0x3F: question mark

There are a fair number of sentences from right-to-left languages (Arabic, Hebrew) that begin with terminal punctuation that was meant to be put at the end. Sample queries:

select id, text, hex(text) from sentences where lang='ara' and left(text, 1) = 0x21\G
    yields 54 sentences

select id, text, hex(text) from sentences where lang='ara' and left(text, 1) = 0x2E\G
    yields 1204 sentences

I plan to write a Python script that finds such sentences and moves the terminal punctuation to the end of the sentence.

**Comment by jiru** [comment]
Do you why such sentences got inserted? What can we do to prevent it? If you write a python script, please make it so that it inserts sentence modification log. You may use the django tool used for deduplication as a base.

**Comment by alanfgh** [comment]
I finished writing the script rtl_punct_fixer.py and ran it successfully, writing the results to log files on the server. A summary:

Arabic:

   Total sentences for which '.' was moved: 1196
   Total sentences for which '?' was moved: 0
   Total sentences for which '!' was moved: 54

Hebrew:

   0 (All were previously changed on April 5, 2015.)
   
Yiddish:

   Total sentences for which '.' was moved: 2
