### ISSUE TITLE
Filter out non-initial byte order mark, zero-width spaces from sentences

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#643]
My fix for #619 strips out initial byte-order marks. However, there are 41 sentences that contain a byte-order mark somewhere other than the beginning. Here's the query to find them:

select id, text, hex(text) from sentences where locate(0xefbbbf, text)\G

Example: the two sentences with the text "This is only the beginning." (2967925 and 2680594). There's a byte-order mark in the middle of sentence 2680594.

Unless someone thinks that it would be prohibitively computationally expensive to search for non-initial byte order marks, I'll change the code to filter out byte order marks anywhere within the sentence text. Then I'll make a pass through the database to handle the existing sentences.

**Comment by alanfgh** [comment]
We should do the same thing for zero-width spaces (U+200B). See https://tatoeba.org/eng/sentences/show/3366838#comments for examples of sentences that contain them.

**Comment by jiru** [comment]
What’s the problem with having zero-width spaces in sentences?

**Comment by alanfgh** [comment]
They interfere with searches, and if they're imported into some context other than HTML, they look strange. From what I've seen, they seem to be added unintentionally.

**Comment by jiru** [comment]
I think zero-width spaces are legit and useful. Only unintentionally added characters needs to be removed, not all of them.

In what way do they interfere with searches?

If they are displayed well within HTML and bad elsewhere, it has nothing to do with HTML. It’s only a question of support, which modern browsers happen to have. For instance, IE 6 doesn’t support zero-width spaces, while the mail client Sylpheed does. It’s not the character’s fault for not being supported, it’s the program’s fault.

That said, if it causes too much trouble to people using exports, we could just strip them out while exporting.

**Comment by alanfgh** [comment]
I posted a question about them: https://tatoeba.org/eng/wall/show_message/23054#message_23054

**Comment by alanfgh** [comment]
The other thing about zero-width spaces is that they interfere with duplicate-merging. Two sentences that differ only with respect to the presence of a zero-width space will not be merged.

**Comment by alanfgh** [comment]
I removed all byte-order marks from all existing sentences and modified the code to strip them from sentences in the future. I also removed the zero-width spaces from the 11 English sentences that had them. I'm sure that they can be removed from many sentences in other languages as well, but that can be done later.
