### ISSUE TITLE
Restore pre-crash Wall messages

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#65]
If anyone wants to take care of this one day, the messages are here:
https://dl.dropboxusercontent.com/u/953908/tatoeba/wall_posts.pre-crash.csv.xz

The task is not just about importing the data into the database, there is some processing to do. See with sysko for more details.

**Comment by jiru** [comment]
```
13306 message(s) imported, 6 message(s) discarded because their parent does not exist
```
