### ISSUE TITLE
Please, add $sentenceText suffix for browser title

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#650]
The Transifex localisation string #726 "{language} example sentence:" in Tatoeba is a prefix of the content of the sentence ($sentenceText) viewed. It's all fine, however, for some languages, namely, Lojban to quote a text one needs a prefix before and a suffix AFTER the quoted text.

The browser title seems to be a concatenation of #726, then the content of the sentence and then the string #503 "- Tatoeba". (see e.g. https://github.com/Tatoeba/tatoeba2/blob/dev/app/views/sentences/show.ctp#L41)

Could you please add a new string that will be concatenated after $sentenceText or maybe split #503 into two strings?
I understand that for most languages this new string will be empty however, I have no clues how I can adapt the current options to Lojban.

**Comment by trang** [comment]
@lagleki, I've changed the string 
from `{language} example sentence:` 
to `{language} example sentence: {sentence}`

This way you can add whatever you need before/after `{sentence}`.
