### ISSUE TITLE
offer ability to mark a list inactive

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#654]
It would be nice to be able to mark a list inactive. Inactive lists would not show up in the list of list names that opens above a given sentence when the list icon is clicked. They could also be hidden in the "Browse by list" view unless the user chose to view all lists. The idea is that someone who has created a bunch of lists could mark the old ones inactive in order to shorten the the list of list names.

**Comment by trang** [comment]
I'm planning to close this issue because it is a bit outdated. Now that it is possible to set the visibility of a list to ["unlisted"](https://github.com/Tatoeba/tatoeba2/issues/677#issuecomment-170373110), do we still need to have this "inactive" status?

**Comment by alanfgh** [comment]
Setting the visibility of a list to "unlisted" means that **other** people don't see your list, but it does nothing to help you look at a trimmed-down list of your own lists. 

To simplify, I have basically two kinds of lists: 
(1) Sentences that already existed in Tatoeba in Hebrew that I want to study, which I collect under the title "Heb (x): worth learning: private", where x is a number from 1 to (now) 24.
(2) Sentences that I added in English that I requested a Hebrew translation for, which I collect under the title "Eng (x): translation to Hebrew requested", where x is a number from 1 to (now) 8.

When a list reaches 100 sentences, the maximum number that can be downloaded, I stop and go on to a new one. (I realize that the Tatoeba maximum was chosen somewhat arbitrarily, but it's a convenient size for a list: not too short and not too long for printing and studying. It's also a nice round number that makes it easy to calculate how many sentences are contained in the lists.)

As you can see, the list of lists is too long to fit on the screen. I'd like to have a way to say that a particular list is inactive, so I don't want to see it in the list of lists displayed when I click the list icon for a sentence, but I don't want to get rid of the list. As it is, I need to rename the old lists with a prefix of "z~" just to get them out of the way. I'd rather not have to do that.

![possible_lists_for_sentence](https://cloud.githubusercontent.com/assets/1213027/14037053/255a50b8-f216-11e5-9857-ba2500234a3a.png)

**Comment by trang** [comment]
Oh I see. I thought you were talking about the index list. Makes sense now.

**Comment by trang** [comment]
The best solution I can think of would be to have 3 options in the permissions to edit:

1. editable by anyone
2. editable by only myself
3. editable by no one

When a list is editable by no one, it won't appear in the dropdown.

**Comment by RyckRichards** [comment]
Could we offer "also editable by {user1}, {user2}..."? Actually, if I
create a list, it only appears in "My lists" even if the {user 1} also
added sentences. What if s/ he also would like to browse that list -which
is not public- from her/his lists or lists that s/he contribute?

**Comment by trang** [comment]
@RyckRichards we could but it's more complicated to implement.

**Comment by RyckRichards** [comment]
Gotcha!



-- 
Ricardo Vernaut Jr

**Comment by trang** [comment]
How it should look like:

![list-options](https://cloud.githubusercontent.com/assets/221850/15057558/b07ad380-1317-11e6-8567-ad8f9d2b1cd6.png)

**Option 1: "Anyone"**
This is the same as having the current checkbox "Allow anyone to add and delete sentences from the list" selected.

**Option 2: "Only me"**
This is the same having the current checkbox "Allow anyone to add and delete sentences from the list" unselected.

**Comment by RyckRichards** [comment]
How about on "Who can add/remove sentences" add (x) The following
user(s):[_______] and the user specifies who should/can add/remove
sentences and so, that list would be add to that/those who create the
list indicated? That would make lists colaborative,easy to find but
not public. Actually, we have to send the link to someone in order to
have sentences on the list we created -which demands too much time
sometimes (eg.: a contributor wants to ask a CM to tag sentences as
"1st person singular". )

-- 
Ricardo Vernaut Jr

**Comment by trang** [comment]
Cf. https://github.com/Tatoeba/tatoeba2/issues/654#issuecomment-207979516

> @RyckRichards we could but it's more complicated to implement.

For now we keep it simpler. Allowing a specific group of people to edit a list will be the scope of another issue.

**Comment by zachleigh** [comment]
Updated local dev database.    
SQL Query: ALTER TABLE `sentences_lists` MODIFY COLUMN `editable_by` enum('creator', 'anyone', 'no_one') NOT NULL DEFAULT 'creator';

**Comment by alanfgh** [comment]
Trang's list is neatly organized, but the reason to choose to set "Who can remove/add sentences" to "No one" is not obvious. I think most people would encounter this option and think it was pointless. It would never occur to me that this is a way to hide them from the list of lists displayed when I hover over the list icon, and that changing the value back would let me display and modify them again. In this regard, I consider making a list uneditable to be essentially a side effect, where hiding the list is the primary effect that people would want and care about. 

Having said that, I'm not sure how to present this choice. I understand that adding a parenthetical expression might look awkward:

Who can remove/add sentences:
o Anyone
o Only me
o No one (will not appear as a choice when hovering over the list icon above a sentence)

and presenting this text as a tooltip might mean that people don't see it.

The only thing that occurs to me is this:

Show list as a choice for sentences:
o To everyone
o Only to me
o To no one

I'm not perfectly satisfied with it, but it seems like a step in the right direction.

**Comment by zachleigh** [comment]
Maybe this should be a completely separate option. So it could look like this:   
       
**Who can remove/add sentences**
o Anyone
o Only me

口 **Show this list in dropdown menus**     
     
You could keep the "Who can remove/add sentences" section as radio buttons because thats easier to expand upon later if, for example, you wanted to implement some kind of functionality like what @RyckRichards was talking about. It would be a breeze to implement too.

**Comment by trang** [comment]
It wouldn't work to add a checkbox because the 3 options exclude each other. For instance you can't have `Only me` selected and have `Show list...` selected. 

How about:

**Who can remove/add sentences**
o Anyone
o Only me
o No one (list inactive)

**Comment by zachleigh** [comment]
That makes it a little more clear.

**Comment by alanfgh** [comment]
Yes, I agree that it's a little more clear. Thanks for looking at this, Zach and Trang.

**Comment by trang** [comment]
I've deployed the @zachleigh's current code on the dev website (https://dev.tatoeba.org). 

I think there's something missing: we need to display a specific icon on the list index page for lists that are inactive, so that lists owners can easily see which of their lists are inactive. Not sure yet how to display this info though.

**Comment by zachleigh** [comment]
Right now, if the list can be edited by anyone, the 'group' icon with three people is shown. How about having another icon with just one person if the list can only be edited by the list creator and a pencil with a line through it if the list can not be edited?

**Comment by trang** [comment]
I think for now we can simply change the color of the links to `#AAAAAA` when a list is inactive. 

![2016-05-23 11_20_11-trang s lists 10 - tatoeba](https://cloud.githubusercontent.com/assets/221850/15466263/f665abda-20d8-11e6-94c2-4cf36e683863.png)

I'll create later on another issue where we can review the icons for each combination of "visibility" and "editable_by". We'll need at some point to replace our icons with icons from the Material Design set (https://design.google.com/icons/).

**Comment by zachleigh** [comment]
Ok. That should be pretty easy. Ill try to finish this up tomorrow.

**Comment by ckjpn** [comment]
Note that the "loading / processing" animated circle is displayed 3 times when you are adding a sentence to the list.

![screen shot 2016-05-25 at 20 51 13](https://cloud.githubusercontent.com/assets/7934273/15539025/dfd07f24-22ba-11e6-8164-cd0f59c910ec.png)

I've been using a Stylish CSS approach to doing the same thing for quite a while.
I forget who suggested this, but I got the idea from a Tatoeba Project member who put it on the Wall at one time, I think.



```
/* Choose which lists to display - Ignore others  */

.listOfLists option
{display:none;}
option[value*="4006"],
option[value*="1394"],
option[value*="997"],
option[value*="996"],
option[value*="934"],
option[value*="926"],
option[value*="907"],
option[value*="888"],
option[value*="5007"],
option[value*="4680"],
option[value*="4005"],
option[value*="4004"],
option[value*="4003"],
option[value*="4001"],
option[value*="4000"],
option[value*="3884"],
option[value*="3790"],
option[value*="3642"],
option[value*="3358"],
option[value*="3255"],
option[value*="3254"],
option[value*="3122"],
option[value*="312"],
option[value*="1314"],
option[value*="1255"],
option[value*="1237"],
option[value*="1198"],
option[value*="1159"],
option[value*="3981"]
{display:block !important;}

```

**Comment by ckjpn** [comment]
This is related.

Perhaps adding an option in settings to allow members to not show "collaborative lists" in the dropdown would be useful.  I know that I would check this option if it were available, since we have a very large number of collaborative lists.

"Don't show collaborative lists" in the dropdown."

**Comment by trang** [comment]
@ckjpn it is in general better not to comment on closed issues unless you have identified a problem with the issue itself. For the problems you mentioned you can create new issues. And if you aren't sure whether something should be a new issue or not, you can simply post on the Wall and I will move it to GitHub if necessary.
