### ISSUE TITLE
Add possibility for admins to delete any list

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#655]
To delete spam lists, such as https://tatoeba.org/eng/sentences_lists/show/3574

**Comment by alanfgh** [comment]
As an aside, I deleted the list manually. It had the title "APPLY FOR A LOAN... CONTACT EMAIL:<e-mail address>". I also marked the user as a spammer.

**Comment by trang** [comment]
Duplicated by #1956. Keeping the other issue as it has more information.
