### ISSUE TITLE
list search is case-sensitive; expected case-insensitive

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#659]
I was surprised to discover that searching for "Ita" brings up a different set of lists from the one found by a search for "ita". People are used to searches being case-insensitive.

**Comment by trang** [comment]
I had forgotten to run the database update script. 
https://github.com/Tatoeba/tatoeba2/blob/dev/docs/database/updates/2015-05-10.sql
It's fixed now.
