### ISSUE TITLE
make display order of sentences in list configurable

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#660]
Some people really like ordering sentences within lists by the date on which they were added to the list. Others seem to feel passionately that they should be ordered by the date on which they were added to the corpus. To me, this situation seems to call for an option that is either selectable on the list page, or configurable by user preference, or a combination of the two (in which case the user preference would choose the default, but the order could still be changed from the list page).

**Comment by trang** [comment]
A few notes about this.

1) The possible ways we can sort the sentences in the lists are
- by date added to the list
- by sentence id
- by language
- by owner id

2) We should also add a "position" field for each sentence in each lists, so that users can position their sentences the way they want, without having to be dependent on the other criteria.

None of these features needs to be a user preference. They are rather common features that everyone expect to have.

**Comment by alanfgh** [comment]
Okay, rather than a user preference, we should store the criterion + order (ascending vs. descending) selected for the sort and use it the next time, as in #662.

**Comment by ckjpn** [comment]
Other possibilities for sort order would be the ones used in the "advanced search."

* fewest words to most words (and with the reverse order option)
* random

Perhaps having the same standard set of sort options on all lists of sentences would be a good idea.
(tags, lists, translate sentences by ..., etc.)

**Comment by trang** [comment]
Marking this as accepted.

Here's what we want to do. On the list's page (`/sentences_lists/show/{listId}`), add links to sort the sentences by:

* date added
* sentence id
* language
* sentence owner

> **Sort by:** `date added` | `sentence id` | `language` | `sentence owner`

The mechanism is similar to the sort on the [tags page](https://tatoeba.org/eng/tags/view_all), the [members page](https://tatoeba.org/eng/users/all), and various other places.

**Comment by phtan** [comment]
@trang I'm working on this.

I've got 'sort by date added' and 'sort by sentence id' working.

However, I'm running into a metaphorical wall with 'sort by language' and 'sort by sentence owner'. You see, I'm using a `PaginationHelper::sort()`, which uses the `defaultModel`, SentencesSentencesList, which in turn uses the SQL file 'sentence_sentences_list.sql', which has 'date added' and 'sentence id', but not 'language' and not 'sentence owner'. (a look at [the schema](https://github.com/Tatoeba/tatoeba2/blob/dev/docs/database/tables/sentences_sentences_lists.sql) will reveal this).

Should I ignore the 'language' and 'sentence owner' sort options?

**Comment by RyckRichards** [comment]
I myself would like to have both since I ask members to create some lists
in different languages to study :)

**Comment by trang** [comment]
@phtan, you're right, sorting by language and sentence owner is more complicated. You can skip them. If it becomes really needed, we'll make another issue for these sort options.
