### ISSUE TITLE
Automatically convert text in x-system for Esperanto

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#67]
Replace the letter-combinations "Cx", "cx", "Gx", "gx", "Hx", "hx", "Jx", "jx", "Sx", "sx", "Ux", "ux", commonly used on non-Esperanto-aware computers,with the correct letters "Ĉ", "ĉ", "Ĝ", "ĝ", "Ĥ", "ĥ", "Ĵ", "ĵ", "Ŝ", "ŝ", 'Ŭ", "ŭ"", in Esperanto sentences .

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/335

**Comment by trang** [comment]
Too low priority for us to invest time in implementing this feature. I'm closing.
