### ISSUE TITLE
Display number of sentences in list page

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#672]
https://tatoeba.org/eng/wall/show_message/22942#message_22942

> Category: Improving the User Interface
> 
> Show the number of sentences in a list at the top of the list's page.
> https://tatoeba.org/eng/sentences_lists/show/4023
>
> Something similar is already being done for a member's "sentences" page.
> https://tatoeba.org/eng/sentences/of_user/CK

Commit : beb2c68ca7449c2ac0e6ce569397ca1dd40847bd

**Comment by alanfgh** [comment]
The number of sentences appears to be incorrect at least some of the time. See #682 .
