### ISSUE TITLE
Add tags without reloading the page

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#674]
https://tatoeba.org/eng/wall/show_message/22945#message_22945

> Category: Helping Members Work More Efficiently
>
> Make it possible to add more than one tag at a time, separated by commas.
>
> Example: OK,SVC,present simple

**Comment by trang** [comment]
This has been requested by [CK](https://tatoeba.org/eng/wall/show_message/22945#message_22945), [Silja](https://tatoeba.org/eng/wall/show_message/22970#message_22970) and [ricardo14](https://tatoeba.org/eng/wall/show_message/23629#message_23629).

My problems:

1. What if a user wants to use a tag with a comma in it? It seems there are several [tags with a comma in it](https://tatoeba.org/eng/tags/view_all/,).
2. There are more error cases to handle.
  * We cannot let users add an infinite number of tags at once. What should be the limit, how do we limit it?
  * What if the user tries to add 3 tags, and 2 of them cannot be added, for different reasons. We will need to re-adapt the error message.

It seems the main problem is that users have to wait 2 or 3 seconds between each tag that they add (because adding a tag reloads the page), and the goal is simply to reduce the time between the moment when the user submits a tag, and the moment the user can start adding a new one.

If that's indeed the main issue, then we can solve this differently than by making it possible to add several tags at a time, separated by a comma.

**Comment by jiru** [comment]
I second using a different solution that reduce the waiting time in order to avoid the complications you mentioned. Performing an Ajax request instead of reloading the page sounds like a valid solution. It can probably be done so that several tags may be added without having to wait for the response between each submission. Regarding the initial proposition, it eventually boils down to use the return key instead of the comma.

**Comment by RyckRichards** [comment]
Requested by ricardo14 on the Tatoeba Day #4 (2015-07-25 03:39 ):

► https://tatoeba.org/eng/wall/show_message/23626#message_23626

**Comment by RyckRichards** [comment]
Requested by ricardo14 on Tatoeba Day 7

https://tatoeba.org/eng/wall/show_message/24186#message_24186

**Comment by ckjpn** [comment]
While I like the new way, I do miss the fact the that top one was selected automatically.

This meant that I was able to just type up to the point where the tag appeared at the top of the list, and then I could hit my return key.

Now, I have to reach over and hit my down arrow key (or reach even further and use my mouse), and then I have the hit the return key.

If you can ever figure out how to add a comma-deleted list of tags all at once, it would be very useful.  I often tag a series of sentences with the same tags.  for example, I just tagged 4 sentences with "fact, svc, present simple".
