### ISSUE TITLE
Add option to hide random sentence on homepage

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#676]
https://tatoeba.org/eng/wall/show_message/22952#message_22952

> Category: Improving the User Interface
> 
> Give members the option to turn off the random sentence on the main page.
>
> A quick-and-easy fix, would be to put a <div id="randomsentence"></div> around that part of the page, so we could totally hide it using Stylish. Currently, we can't completely hide it using Stylish. (See this image http://a4esl.com/temporary/tato...h/stylish2.png from the "Stylish Changes for Tatoeba.org" page at http://goo.gl/iEWiPO.)
>
> That wouldn't speed up the page, of course, since all that code would still be in the page.so.

**Comment by trang** [comment]
@zachleigh, I'm assigning you this issue, let me know if you need more info.

What we want to do is:

1. Add an option is the Settings page (accessible from `{username}` > `Settings`, in the menu) that says: `Hide random sentence on the homepage`. This option is disabled by default.
2. When the user enables this option, they won't see anymore the "Random sentence" block on the homepage.

To be able to test this, you would normally have to enable the search in the [app/config/core.php](https://github.com/Tatoeba/tatoeba2/blob/dev/app/config/core.php.template#L357):
```
Configure::write('Search.enabled', true);
```
And then you'd have to index the sentences. 

But since indexing can take a pretty long time, you can instead leave the config to `false` and temporarily change this line: https://github.com/Tatoeba/tatoeba2/blob/dev/app/models/sentence.php#L424 to `return array(1);`. This will display sentence `#1` as the random sentence.

**Comment by zachleigh** [comment]
@trang 
Ill get working on it over the weekend :)
