### ISSUE TITLE
Private lists

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#677]
At the moment we have "personal" and "collaborative" lists.
- Personal lists: only the creator of the list can add and remove sentences.
- Collaborative lists: any member of Tatoeba can add and remove sentences.

All the lists are public, they are visible to everyone.

We need to add the option to make a list private so that users can create lists that are visible only to themselves. Private lists will be necessarily personal.

**Comment by ckjpn** [comment]
Once lists can be made private, then I'd like to see an option provided to allow members to see all lists that a certain sentence is on, not just their own lists and collaborative lists.    This would allow members to see my lists of "audio file by USERNAME", so they know who recorded an audio file.  It would also allow seeing other lists that might be potentially informative, such as my "White List of Proofread English Sentences" (list 907).

**Comment by RyckRichards** [comment]
Requested by Ricardo14 on [Tatoeba Day #9](https://tatoeba.org/eng/wall/show_message/24481#message_24481).

**Comment by trang** [comment]
Possible implementation:

* Create 2 new fields in `sentences_lists` table: 
  - visibility: private / public
  - editable_by: creator / anyone
* We would then have the possible combinations:
  - visibility private + editable by creator --> this would be the "private lists"
  - visibility private + editable by anyone --> this should not be possible
  - visibility public + editable by creator --> currently "personal lists"
  - visibility public + editable by anyone --> currently "collaborative lists"
* On the list's page, instead of the checkbox "Set list as collaborative", we would have 2 checkboxes:
  - Set list as public
  - Make list editable by anyone
* The 2nd checkbox should not be accessible before the 1st checkbox is checked.

**Comment by RyckRichards** [comment]
Awesome!!

**Comment by ckjpn** [comment]
Suggested wording change.

Set list as public   ==> Set list to publicly viewable.

This would make it clear what you mean by "public."



There is still a bug that doesn't allow people to remove items from a collaborative list, so at this point the following isn't true. 
visibility public + editable by anyone --> currently "collaborative lists"

I verified this by trying to remove an item from this list.
https://tatoeba.org/eng/sentences_lists/show/992

**Comment by trang** [comment]
I'm not completely done with this issue, but it can already be tested on the dev website.

Here's a summary of the implementation:

* All the lists that were 'personal' were set to 'private', i.e. they are no longer displayed in the lists index and therefore can only be seen by the creator of the list. 
* There are now fewer lists displayed in the index page because only lists that were previously 'collaborative' are displayed in the lists index.
* If the user wants to make their list public (i.e. have it displayed in the index page), they can check the option "Set list to publicly viewable" in the list's page.
* If the user wants to make their list editable by anyone, they can check the option "Make list editable by anyone" in the list's page.
* Lists that are private are displayed with a lock icon on "My lists" page.
* On the sentence's page, only lists that are set to be publicly viewable are displayed. This allows users to have non-collaborative lists displayed on the sentence's page, and visible to all users.

Note: currently it is possible to enable "Make list editable by anyone" without enabling "Set list to publicly viewable". Doing so has no effect.

**Comment by ckjpn** [comment]
If the purpose of private lists if to prevent others from seeing your lists' name and what you have listed, then private list data should probably not be exported along with other list data.

**Comment by jiru** [comment]
> Note: currently it is possible to enable "Make list editable by anyone" without enabling "Set list to publicly viewable". Doing so has no effect.

This sounds like a design flaw to me. What about having one “status” information for each list, that could take one of the three values private, public or collaborative? Then you won’t need to prevent users from making an invalid selection.

**Comment by trang** [comment]
>  What about having one “status” information for each list, that could take one of the three values private, public or collaborative?

I did consider this option but I felt it would give more flexibility, for future evolution of the lists, to split it in two fields: one that defines who can see the list and where it can be found, and one that defines who can edit the list.

Right now the visibility is only public or private and the list can be edited only either by the creator or by anyone. But there can be more variations of visibility, and we will someday need to allow users to restrict the list to be edited only by a defined group of people.

I'm already considering adding another value for the visibility, after [tommy_san's comment on the Wall](https://tatoeba.org/eng/wall/show_message/25181#message_25181).

Also in theory we could give the possibility for users to create a list that others cannot see, but can still add sentences to. That is if you are organizing some collaborative work, but for some reason don't want the participants to be influenced by the content of the work. You'd have to be a bit creative to need such a list, but it's not a completely incoherent setting I think.

**Comment by trang** [comment]
I think I'm more or less done implementing this. There are probably some details to fix but here's how lists work now:

There are 3 types of lists.

1. Public
  * List is displayed on the lists index , sentence page, "Lists of <user>" page
  * Content of the list can be viewed by anyone
2. Unlisted
  * List is not displayed on the lists index  and sentence page
  * List is not displayed on "Lists of <user>" page either, except for the creator.
  * Content of the list can be viewed by anyone
3. Private
  * List is not displayed on the lists index and sentence page
  * List is not displayed on "Lists of <user>" page either, except for the creator
  * Content of the list can be viewed only by the creator

In addition to this, there is an option to make the list editable by anyone.
Whether a list is public, unlisted or private, it can be made editable by anyone. When a list is editable by anyone, it appears in the dropdown of the sentence's menu (the one that lets you choose which list you want to add the sentence to).

All the list that were previously "personal" will become unlisted and not editable by everyone.
All the lists that were previously "collaborative" will become public and editable by anyone.

When a list is created, it is by default "unlisted" and editable only by the creator.

----

There was some concern about having the option to make a private list, where only the creator can view the content, because no one explicitly requested it and therefore there may not be a need for it. Actually, this issue was requested several time during Tatoeba Days but there were no justification for why a list had to be private in the sense of "its content is viewable only by the creator".
Therefore implementing it makes the feature more complex. We could simply have "public" and "unlisted" and if a user wants to make a private list, they can simply work offline.

I have decided to still implement this because I don't think complexity is really an issue here. These 3 levels of visibility feel rather standard to me.
As for working offline, if there are mistakes being corrected in the sentences, or new translations being added, the user will have a harder time tracking these changes if they work offline. So there can be an advantage in having the list online in Tatoeba.

**Comment by ckjpn** [comment]
I'm removing my Wall posting about this and putting it here for reference.
This was at ...
https://tatoeba.org/eng/wall/show_message/25188#message_25188


I agree with what tommy_san says about keeping tatoeba.org as simple as possible. 

However, having options listed clearly on the side of a list may not make things much more complicated for new members, especially if there were a recommended default setting.

Here are all possible options I can think of.
I think all of these should perhaps be set OFF by default.

-- related to private lists
1. keep this list unlisted, but allow it to be found by searching.
2. keep this list unlisted and also do not allow it to be found by searching.
3. do not let anyone else see this list or its contents

-- related to what is now called a collaborative list
4. let others add sentences to the list
5. let others delete any sentence from this list.
6. let others delete only sentences that they added to the list.

-- a new feature, but is currently the default setting for collaborative lists.
7. make this list visible to others on sentence pages
(I think number 7 should also be OFF by default for collaborative lists.)


Perhaps making the default for number 1 to be ON would be a good idea.
It would help keep the list of lists shorter.
As the Tatoeba Project grows, it might help keep the browsable list of lists a more reasonable size.

**Comment by ckjpn** [comment]
Even if you aren't interested in offering some of the various options, I'd like to see at least 2 options for "public." 

1. publicly listed and browsable by anyone, but not displayed on each sentence's page.
2. publicly listed, browsable by anyone and also displayed on each sentence's page.

There are many of my lists that could be potentially useful to any developer using the Tatoeba Corpus who wants help filtering out the not-so-good sentences.  However, displaying those list names on individual pages could easily be interpreted as insults.

There is a good chance that now or in the future other members will have similar lists, used to help minimize errors in the data that they want to use.

If this is too difficult to do, then I can live with what you have.

**Comment by trang** [comment]
I'm currently considering exporting both public and unlisted lists into the CSV files, instead of only public lists.

**Comment by ckjpn** [comment]
> I'm currently considering exporting both public and unlisted lists into the CSV files.

That sound acceptable to me.
I agree that you shouldn't export the private lists, since if you did, they wouldn't be private.

**Comment by trang** [comment]
The types of lists have been udpated as followed:

1. Public
  * List is displayed on the lists index and "Lists of <user>" page for everyone
  * Content of the list can be viewed by anyone
  * List is exported into the CSV files that are distributed on the Downloads page
2. Unlisted
  * List is not displayed on the lists index at all
  * List is not displayed on "Lists of <user>" page either, except for the creator
  * Content of the list can be viewed by anyone
  * List is exported into the CSV files that are distributed on the Downloads page
3. Private
  * List is not displayed on the lists index at all
  * List is not displayed on "Lists of <user>" page either, except for the creator
  * Content of the list can be viewed only by the creator
  * List is not exported into the CSV files that are distributed on the Downloads page

Lists are no more displayed on the sentence's page, except for lists that were created by the current user.

**Comment by ckjpn** [comment]
> Lists are no more displayed on the sentence's page, except for lists that were created by the current user.

This omits the option of showing the "audio" lists.

Is there perhaps some way you could make it possible for an admin to show certain lists on pages?

That would let members know who contributed the audio file on any page.

**Comment by jiru** [comment]
> Is there perhaps some way you could make it possible for an admin to show certain lists on pages?
> That would let members know who contributed the audio file on any page.

We’d better solve this issue in #547 instead.

**Comment by ckjpn** [comment]
I'd still highly recommend making all collaborative lists "unlisted" be default, retroactively, too.

I think we should require people who think their lists should be listed to ask to be "public".
https://tatoeba.org/eng/sentences_lists/index/page:7


Perhaps, it's also a good idea to explain clearly on the page what "public" means.

**Comment by trang** [comment]
Making collaborative lists unlisted will not change this problem as for now it is implemented as followed:

> Whether a list is public, unlisted or private, it can be made editable by anyone. When a list is editable by anyone, it appears in the dropdown of the sentence's menu (the one that lets you choose which list you want to add the sentence to).

The problem you mention is not related to the visibility of the list, but it's rather a UI problem I think.

**Comment by ckjpn** [comment]
This is related to this, so I'll put it here.
Both of these items need to be renamed.

All lists ===> All publicly-listed lists
Collaborative lists ===> All publicly-listed collaborative lists

Even the owners' own lists won't show up with either of these if the list is not set as "public."

https://tatoeba.org/eng/sentences_lists/index/page:1/sort:created/direction:asc
![screen shot 2016-01-17 at 00 24 48](https://cloud.githubusercontent.com/assets/7934273/12373100/b1f80ece-bcb1-11e5-908e-ee9435d067db.png)

**Comment by ckjpn** [comment]
I still think it would be a good idea to set all collaborative lists to unlisted, and turn off the "anyone can add or delete" for all old lists.  Many of these lists are no longer collaborations, and many seem to never have been collaborations.

I think it would better to require active members to choose to have these inactive "collaborations" set to be publicly listed, rather than by default have them all publicly listed.

Doing this would clean up a lot of junky-looking lists names on the lists of lists, and give visitors to that page a much better impression.  It would also make browsing the list of lists easier for those who are actually looking for collaborations.

I think if you quickly glance through the lists that are showing, you can easily understand what I mean.
https://tatoeba.org/eng/sentences_lists/index/page:1/sort:created/direction:asc

Making people once again choose to have their lists listed would also hide lists by members set to inactive, like the following.

https://tatoeba.org/eng/sentences_lists/of_user/alpha44
