### ISSUE TITLE
Make list of lists collapsible on sentence's page

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#678]
https://tatoeba.org/eng/wall/show_message/22955#message_22955

> Category: Improving the User Interface
> 
> Give members the option to not see collaborative lists on a sentence's page, but only show their own lists.
>
> Some members may find it irritating to see collaborative lists.
>
> One reason for this is that many collaborative lists should actually be private lists.
(Note to members: Remember if your list is collaborative, any member can delete sentences or add sentences it.)
>
> Examples of sentences on multiple collaborative lists.
>
> https://tatoeba.org/eng/sentences/show/4070510
> https://tatoeba.org/eng/sentences/show/3590612

**Comment by alanfgh** [comment]
Now that issue #1158 has been fixed, the need for an option to hide collaborative lists has become even more obvious. I marked about two dozen of my lists inactive because I don't want to see them as options when I click the list icon above a sentence. But now the collaborative lists take up all the space on the screen that I freed up. This is not such a problem on my Windows monitor, but it is on my Android tablet.

**Comment by trang** [comment]
This issue was actually about the lists in the sidebar, not the list in the dropdown. It's probably no longer relevant because the collaborative lists are no longer displayed in the sidebar (they used to be), so I'm gonna close this.

The problem you mention is not related to the collaborative lists, I think. If there were no collaborative lists at all, you would still have the problem if you had dozens of personal lists, because the max size of the dropdown is too big to fit in smaller screens.
We could add an option to hide collaborative lists, but it will be more of a design hack than a real solution. To solve this properly, we would need to redesign the list feature, and that's something we'll definitely be doing in the responsive UI project.

**Comment by alanfgh** [comment]
> If there were no collaborative lists at all, you would still have the problem if you had dozens of personal lists, because the max size of the dropdown is too big to fit in smaller screens.

But only if they were all active. At least with your own lists, you have the option to mark them inactive. In any case, I'm glad the underlying issue will be addressed in the future.
