### ISSUE TITLE
Number of sentences reported on a list page is incorrect

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#682]
See https://tatoeba.org/eng/sentences_lists/show/4023 . Note that the number of sentences listed near the top of the right sidebar (which is incorrect) differs from that listed near the bottom of the right sidebar (which is correct).

![wrong_num](https://cloud.githubusercontent.com/assets/1213027/8022406/79ecd92a-0c9d-11e5-8b66-1017a2bc131c.png)

**Comment by trang** [comment]
I've merged this in the current branch (prod_2015-06-06) and updated the prod as well.
