### ISSUE TITLE
Problems adding multiple sentences to a list from the "Add sentence" page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#692]
User 123xyz reports on [https://tatoeba.org/eng/wall/show_message/23192#message_23192](the Wall):

Bug:

When I add several sentences at once using the "Add Sentence" option, they line up on the page one after the other, but when I start adding them to my lists (well, my single list), I can only add two. The first sentence I add can be any sentence, but afterwards, the "add to list" button becomes unresponsive for all of the sentences except the FIRST one (the top one). If I added the first one as my first sentence, then I can only add one sentence in total.

**Comment by alanfgh** [comment]
I see that when I have three sentences on the page and add the first one to the list, I can then add the third but not the second.

**Comment by RyckRichards** [comment]
I've tested this way:

1st step - added bunch of sentences http://prntscr.com/eczgpa  http://dev.tatoeba.org/eng/contributions/of_user/Ricardo14

2nd step - deleted most of them

they got deleted without any problem

Also, #1313  has been closed too.

**Comment by jiru** [comment]
The problem looks solved now.
