### ISSUE TITLE
In "Latest Contributions", right-to-left languages start on the left side, not on the right

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#693]
123xyz [writes](https://tatoeba.org/eng/wall/show_message/23220#message_23220):

In the "Latest Contributions" timeline, sentences in languages which are written right-to-left (e.g. Yiddish) start on the left side of the rectangles they're enclosed in, just like the sentences in languages written left-to-right. Shouldn't they start on the right side instead, just as they do when you open them and view them separately, with all their associated translations?

**Comment by alanfgh** [comment]
This might also involve having to move the flag associated with the sentence.

**Comment by ckjpn** [comment]
This may help you figure it out.

http://a4esl.com/temporary/tatoeba/ideas/rtl-fix-for-2-pages.html

This example was made in 2012, so it's not based on the current layout.
