### ISSUE TITLE
"Browse by list" doesn't show indirect translations like similar pages do.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#695]
Only direct translations are currently shown when browsing a list.  Indirect translations aren't shown.

Here's an example URL.
https://tatoeba.org/sentences_lists/show/907/und

All of the following similar pages show the indirect translations.

1. Translate sentences that belong to a certain member.
https://tatoeba.org/activities/translate_sentences_of/CK

2. Browse by tag.
https://tatoeba.org/tags/show_sentences_with_tag/134/eng

3. Display random sentences.
https://tatoeba.org/eng/sentences/several_random_sentences

4. Search.
https://tatoeba.org/sentences/search?query=%22every+other+day%22&from=eng&to=und

**Comment by RyckRichards** [comment]
Requested by CK on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24185#message_24185)

**Comment by ckjpn** [comment]
Here's an example of the problem.

When browsing a list to see which items on the list haven't yet been translated, linkable indirect translations aren't shown.  It would be great if this were set as a priority item.

LIST
![screen shot 2015-09-24 at 21 45 24](https://cloud.githubusercontent.com/assets/7934273/10073731/0bfb1bce-6306-11e5-8a0b-70cd8b1338d4.png)

PAGE
![screen shot 2015-09-24 at 21 45 09](https://cloud.githubusercontent.com/assets/7934273/10073735/12510966-6306-11e5-916c-fa649355d311.png)
