### ISSUE TITLE
Duplicate lines in the exported tags.csv file.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#696]
This is a minor thing and perhaps doesn't really need to be fixed.
I just thought you'd like to know about it.

There are many duplicate lines in the exported tags.csv file.
Perhaps this is caused by the duplicate-merging script.

For example, 

349064	OK
349064	OK
349064	OK
349064	OK
349064	OK

In the 2015-06-27 export, there were ...
7,706 matching lines including the 1 the should be kept.
3,955 lines that could be eliminated.

**Comment by trang** [comment]
The fix should be applied for the next export.
