### ISSUE TITLE
Sometimes a sentence doesn't actually get deleted on the first try

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#699]
I wrote to this member to verify that what the logs say is what he did.

https://tatoeba.org/eng/sentences/show/4317096

He deleted it, but then noticed that it hadn't been deleted and went back and deleted it again before it actually got deleted.

**Comment by RyckRichards** [comment]
I wasn't able to reproduce that issue.

![screenshot_3](https://cloud.githubusercontent.com/assets/7658430/13905961/5827f922-eeac-11e5-9a17-c8e2424eb0ad.png)

**Comment by RyckRichards** [comment]
I've tested this way:

1st step - added bunch of sentences http://prntscr.com/eczgpa  http://dev.tatoeba.org/eng/contributions/of_user/Ricardo14

2nd step - deleted most of them

they got deleted without any problem

Also, #1313  has been closed too.

**Comment by ckjpn** [comment]
Since this has apparently happened at least once, maybe a more useful way to check this out would be to look directly in the database to see if similar situations have occurred.

The thing to look for, I think, is cases where the same sentence has been deleted twice, as shown in the logs for this sentence.

https://tatoeba.org/eng/sentences/show/4317096

![screen shot 2017-03-15 at 06 05 33](https://cloud.githubusercontent.com/assets/7934273/23922421/a57b7c62-0945-11e7-8c67-f0c19f2bfbf7.png)
