### ISSUE TITLE
Latest contributions don’t show for Toki Pona

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#700]
[Latest contributions for Toki Pona](https://dev.tatoeba.org/contributions/latest/toki) are not showing.

**Comment by jiru** [comment]
Because the language code is 4-chars (toki) while we [only show 3-chars](https://github.com/Tatoeba/tatoeba2/blob/d6700078d7251b516eab0912bd56aabdd79acebc/app/models/contribution.php#L120).

**Comment by trang** [comment]
This was also a problem for CycL.
https://tatoeba.org/eng/contributions/latest/cycl
