### ISSUE TITLE
Bug - Advanced Search - Limit to: Unlinked - Doesn't work.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#705]
This search shows Japanese that are only directly translated, too, which means the "indirect link" limit isn't working.

If it worked, it would be a great way to encourage people to find and link indirectly linked sentences.

Translations
Limited to:
Japanese
Link: indirect

https://tatoeba.org/eng/sentences/search/page:2?query=&from=eng&to=jpn&orphans=no&unapproved=no&user=&tags=&has_audio=yes&trans_filter=limit&trans_to=jpn&trans_link=indirect&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

![screen shot 2015-07-14 at 19 30 26](https://cloud.githubusercontent.com/assets/7934273/8671343/3d41417a-2a5f-11e5-9fac-b1b2042ddf0e.png)

**Comment by ckjpn** [comment]
This is related, I think.

Translations:
Exclude: Spanish
However, this gets search results with Spanish translations.

https://tatoeba.org/eng/sentences/search?query=&from=ita&to=spa&orphans=no&unapproved=no&user=Guybrush88+&tags=&has_audio=&trans_filter=exclude&trans_to=spa&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

**Comment by jiru** [comment]
It’s now fixed in production.
