### ISSUE TITLE
Advanced search for sentences with no translation finds sentences that do have translations

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#707]
I wanted to find Hebrew sentences by fekundulo that are not translated into any language. I used this search, in which I chose to exclude sentences that are translated into any language: 

https://tatoeba.org/eng/sentences/search?query=&from=heb&to=und&orphans=no&unapproved=no&user=fekundulo&tags=&has_audio=&trans_filter=exclude&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

But that didn't work. In the drop-down list for "Language" in the "Translations" group box, perhaps we need a "--" option in addition to the "Any", as we have, for example in the "Not directly translated into" drop-down list under "Browse by language". "Exclude" + "--" would have no effect, but "Exclude" + "Any" would exclude any sentence having any translation.

![advanced_search_01](https://cloud.githubusercontent.com/assets/1213027/8546870/d499b2e6-2488-11e5-8daf-fa1bafde8358.png)

**Comment by jiru** [comment]
I created another issue for this problem: #708.
