### ISSUE TITLE
Change the colors on the activity timeline graph.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#710]
Change the colors on the activity timeline graph.
https://tatoeba.org/eng/contributions/activity_timeline

Recently, almost every day is over the minimum needed for red, so the color-coding isn't as effective as it could be.

You can quickly see how the colors look for the past year and a half using this link.
Daily Contribution Stats for 2014 & 2015 at a Glance
http://goo.gl/3PUMKG

Priority: low
Easy to do.

Perhaps this is an appropriate change.

FILE: activity_timeline.ctp
LINES: 80 through 84

        if ($total > 5000) {
            $color = 10;
        } else {
            $color = intval($total/500);
        }

**Comment by trang** [comment]
I'm actually wondering if the variation of color is really useful, since we already have the size of the bar to give a visual information about the quantity.

**Comment by ckjpn** [comment]
It's not necessary, but you already have it programmed and a simple change is all that is needed to update it.

It might possibly help people quickly scan the results to notice which days are less than 5,000, or less than 4,500, etc.

I'd suggest making the change for now, anyway.

**Comment by trang** [comment]
I went for a single color, rather than changing the thresholds from which the color changes.
