### ISSUE TITLE
Change the message to "Not Found" or "No Results" for searches with no results.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#711]
Related wall posting = https://tatoeba.org/eng/wall/show_message/23361#message_23361

Here's an example of an advanced search that might be made by a native speaker of English wishing to translate sentences by a Japanese native speaker.

All Japanese sentences by CHNO with です。not already translated into English.

https://tatoeba.org/eng/sentences/search?query=%E3%81%A7%E3%81%99%E3%80%82&from=jpn&user=CHNO&to=eng&trans_filter=exclude&trans_link=direct&trans_to=eng&sort=words

The message "No Results" or "Not Found" would be more appropriate than what we're getting now.

![screen shot 2015-07-11 at 10 01 34](https://cloud.githubusercontent.com/assets/7934273/8631558/3a7b04ec-27b4-11e5-8d28-1d2f25ae662a.png)

**Comment by trang** [comment]
I'm closing this, since we have another similar issue: #706

**Comment by ckjpn** [comment]
Sorry, I looked for this issue before I submitted it and didn't see it.

**Comment by trang** [comment]
No problem.
