### ISSUE TITLE
The sentences_in_lists.csv has items in it related to sentences that have been deleted.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#713]
There are 1,460 lines in the July 11, 2015 sentences_in_lists.csv  file with sentences that have been deleted.  (Or to be exact, "sentences not exported", so some of these may refer to "Unapproved" sentences that don't get exported.)

I just thought you'd like to know.
It's probably a low priority to fix this, but you'll probably want to eventually do so.

Here are just 10 or the 546 items for List 758, referring to sentences that have been deleted.

758	1144874
758	1144876
758	1144879
758	1144880
758	1144882
758	1144883
758	1144886
758	1144889
758	1144890

**Comment by alanfgh** [comment]
I removed the ghost entries from the database. The next time the list is exported, they should be gone.
