### ISSUE TITLE
Wrong error message shown when trying to delete a long list.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#715]
I just thought you'd like to know that this happens.
Since most lists aren't so long, you may never really need to fix this bug.

I assume, it's a "time out" error of some sort.

Anyway, the following image shows what I got each time I tried to delete long lists.
The deletions seemed to stop, but many of the sentences on the lists were deleted each time.
I just had to click the "delete" more than once to fully delete the lists.

![screen shot 2015-07-12 at 13 38 54](https://cloud.githubusercontent.com/assets/7934273/8636448/0d25ec30-289c-11e5-87aa-5899b47f67d0.png)

**Comment by trang** [comment]
This is more of an optimization issue I think. I'll close this since this issue probably doesn't affect anyone else but CK at the moment.
