### ISSUE TITLE
language selected for translation is not changed inside a page

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#72]
for the moment it is stored in the session, which mean that it will not work if you

in a page with several sentences:
translate one sentence:
choose language X rather than the previous language Y language (by default autodetect)

translate an other
language of translation is still on Y

solution :
javascript => when you validate, it check the selected language, and change all "language of translation" select in the page 

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/318

**Comment by trang** [comment]
Note: this is fixed in the new sentence design. Since the plan is to completely transition to the new sentence design in the next couple of months, it is not necessary to fix it in the old design.
