### ISSUE TITLE
Show the number of sentences on each tag's pages

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#720]
Show the number of tags on each tag's pages, including lists of tags limited by language.

A nice enhancement would be to have the number of sentences at the top of the tag pages in the same way you have the number of sentences listed at the top of "browsing" pages (https://tatoeba.org/eng/sentences/show_all_in/eng/und/und/indifferent).

For example, it would be nice to know how many sentences in Portuguese have been tagged OK.
https://tatoeba.org/eng/tags/show_sentences_with_tag/7/por/page:999999

**Comment by trang** [comment]
@shashank19gaurav, the goal is to display the number of sentences next to the tag name.

For instance, for the `OK` tag, it would look like:

`OK (24569 sentences)`

Remember to handle the case where there's only 1 sentence.
`OK (1 sentence)`
and not
`OK (1 sentences)`

**Comment by RyckRichards** [comment]
Shouldn't this ticket be closed as far it was implemented?

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/11426396/19b2dc52-9443-11e5-92cd-27264d333d5a.png)

**Comment by ckjpn** [comment]
RyckRichards,  you've misunderstood the enhancement request.

What the request is is to have the number displayed on each tag's page, with the number representing the number of tags in the selected language as well.

![screen shot 2015-11-27 at 01 01 03](https://cloud.githubusercontent.com/assets/7934273/11426917/abf60c60-94a2-11e5-8a8c-90c52aaded33.png)

However, if this is too difficult to do, then it's OK with me if this issue is closed.

**Comment by RyckRichards** [comment]
Oh, I see! Thanks, Trang!

On 11/26/15, ckjpn <notifications@github.com> wrote:
> RyckRichards,  you've misunderstood the enhancement request.
>
> What the request is is to have the number displayed on each tag's page, with
> the number representing the number of tags in the selected language as
> well.
>
> ![screen shot 2015-11-27 at 01 01
> 03](https://cloud.githubusercontent.com/assets/7934273/11426917/abf60c60-94a2-11e5-8a8c-90c52aaded33.png)
>
> However, if this is too difficult to do, then it's OK with me if this issue
> is closed.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatoeba/tatoeba2/issues/720#issuecomment-159949423


-- 

Ricardo Vernaut Jr

Mobile // Celular: (5521) 967-640-668
Email: rvernautjr@gmail.com
<https://www.linkedin.com/in/vernautjr>
