### ISSUE TITLE
Advanced Search Bug - Reverse order doesn't work with "fewest words first" if not search keyword is entered.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#723]
Assuming that the reverse order option of "fewest words first" means the sort should show "most words first", then this isn't working properly.

This does work if a search keyword is entered.  However, it doesn't work if you just want to search for every sentence by patgfisher that isn't yet translated into Portuguese.  Perhaps, this wouldn't actually be considered a bug.

One would expect the longest sentences to show first in this case, but that is not what is happening.

https://tatoeba.org/eng/sentences/search?query=&from=eng&user=patgfisher&to=por&trans_filter=exclude&trans_link=direct&trans_to=por&sort=words&sort_reverse=yes

**Comment by jiru** [comment]
It’s fixed on dev already. Wait for the next update.

**Comment by trang** [comment]
Cf. #703
