### ISSUE TITLE
Allow to remove UI languages

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#725]
There are UI languages that needs to be removed because they are not maintained. However, just removing a language from the config file will make all the links using with this language code return 404. We need to have a redirection mechanism that takes browser’s preference and fall back to English, just like going to http://tatoeba.org/.

**Comment by trang** [comment]
Yea about that. When I updated the prod website today, I noticed that our config had all UI languages enabled.

It's been like this ever since we moved to our new server last year. We had to do the config from scratch and disabling some UI languages was something no one thought of.

I haven't disabled any yet. I think we'll have to let it be until we implement the fallback to English.

**Comment by AndiPersti** [comment]
> We need to have a redirection mechanism that takes browser’s preference and fall back to English, just like going to http://tatoeba.org/.

I've looked into this issue and implemented most of the necessary changes. But while reviewing my code, I've realised that there was already a redirection mechanism available even before you have opened this issue. :smile: 

In bc0fe37c8cc0f5ac50dd72b4a1596435465c7e26 you've added a way to remap old language codes to new ones. Now, if you simply remap the code for an unmaintained language to English, it is removed without resulting in a `404`. 

Here's an example: If you would like to remove German from the UI languages, you would add it as a last element of the English array in `config/app_local.php` and remove its own entry:
```
// ['deu', null, 'Deutsch'],
['eng', null, 'English', ['deu']],
```

So I guess this issue can be closed, can't it?

**Comment by AndiPersti** [comment]
To demonstrate that it works I've just disabled Latin (a language with only 20 translated strings in `default.po`) on dev: https://dev.tatoeba.org/lat/sentences/show/123 redirects now to the English version.

```
# egrep 'English|Latina' config/app_local.php
            ['eng', null, 'English', ['lat']],
//            ['lat', null, 'Latina'],
```

**Comment by trang** [comment]
We can indeed just use the existing mechanism of redirecting old language codes to new ones. I guess the only thing to do then is to add a few lines of documentation to explain what the 4th item in the array does :)

**Comment by AndiPersti** [comment]
Since #2582 changes the structure of the array I've added some explanation there.
