### ISSUE TITLE
Favorite button doesn't work anymore

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#728]
https://tatoeba.org/eng/wall/show_message/23564#message_23564

**Comment by trang** [comment]
Possible problem on Chrome on iPhone: http://tatoeba.org/eng/wall/show_message/23806#message_23806

**Comment by PaulPeer** [comment]
Same problem on Safari on iPhone: as well "favorite" as "OK", "not OK" and "I doubt" don't work.

**Comment by trang** [comment]
I'm going to create a new issue for this.
