### ISSUE TITLE
log link and unlink

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#73]
it would be displayed the same way as last sentences, and we would access "history of link/unlink" through a link in a module to the right of "last sentences" pages

This would require splitting the contributions table into log_sentences tables and log_links tables (with the result that the table name would be clearer ^^).

Maybe we should add a field to the log_links table to distinguish between a "natural" link/unlink (when you add a translation / when you delete a translation) and manual link/unlink (as IMHO only the latter are worth seeing).

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/314

**Comment by trang** [comment]
Closing.

I'm not sure if this is still relevant... We already are logging linking/unlinking. Plus, we have #1633.
