### ISSUE TITLE
Add language: Emilian (egl, 4482)

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#731]
Requested by guybrush88, who is a native speaker and says he will contribute actively to it if it's added: https://tatoeba.org/eng/wall/show_message/23631#message_23631

**Comment by trang** [comment]
TODO:

`CALL add_new_language('roa', 4482, null);`

**Comment by jiru** [comment]
[The language code roa does not appear to be a valid ISO-639-3 code](https://en.wikipedia.org/wiki/ISO_639:r).

**Comment by jiru** [comment]
It is however [a valid ISO 639-2 code](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) for [Romance languages](https://en.wikipedia.org/wiki/Romance_languageshttps://en.wikipedia.org/wiki/Romance_languages), which doesn’t define a single language, but a group that includes modern Spanish, Portuguese, French, Italian, Romanian etc. so I don’t think it’s what we want.

**Comment by trang** [comment]
Thanks for pointing out.

Reggiano is an Emilian dialect, so we're going to use the code `egl` and rename the language to `Emilian`.

https://en.wikipedia.org/wiki/Emilian_dialect

**Comment by Guybrush88** [comment]
I checked on Wikipedia and the code is 'egl'
