### ISSUE TITLE
Chinese -> Mandarin Chinese

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#734]
I opened this ticket to suggest a rewording in the languages names. I think "Chinese" should be renamed to "Mandarin Chinese", since it refers to that specific variant of Chinese.
On Transifex, it's string 88 in the English version

**Comment by trang** [comment]
I've renamed it to "Chinese (Mandarin)". 
Cf. [sysko's comment](https://github.com/Tatoeba/tatoeba2/issues/528#issuecomment-74120038) in #528.
