### ISSUE TITLE
Search button (with magnifying glass) doesn't look clickable

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#736]
The search button with the magnifying glass looks very flat. If I weren't already familiar with the interface, I wouldn't be sure that I had to click it. By contrast, the buttons for the pull-down lists next to it have a graded wash, so they look more three-dimensional and clickable.

![flat_button](https://cloud.githubusercontent.com/assets/1213027/9024445/62573658-389d-11e5-90ff-35b4829ad2d5.png)

**Comment by billoliver** [comment]
New button.
```
.search_bar
.search-submit-button {
  color: #fff;
  cursor: pointer;
  background: #263238;
  width: 70px;
  height: 30px;
  border: none;
  border-radius: 2px;
  padding: 2px 0 4px 0;
}

button.search-submit-button:hover {
  background: #37474f;
}
```

**Comment by alanfgh** [comment]
Thanks, Bill! When it's on the dev site, I'll take a look.

**Comment by billoliver** [comment]
@alanfgh No problem. Here it is:
![search-button](https://cloud.githubusercontent.com/assets/17387379/13907373/66378f22-eecb-11e5-9d8c-5ab1c753eeb6.png)

**Comment by trang** [comment]
@billoliver rather than changing the color, how about simply adding a border or a shadow, or both? I don't think that changing the color will make the button feel more like a button.

**Comment by billoliver** [comment]
> @billoliver rather than changing the color, how about simply adding a border or a shadow, or both? I don't think that changing the color will make the button feel more like a button.

I saw this coming :smile:

I didn't add a shadow because as I said in my previous comment, it doesn't work on every browser. But I'm going to make a better one.

**Comment by trang** [comment]
You talked about gradient, not shadow. 

> I could have used a linear-gradient, but it doesn't work on every browser.

Shadow seems to be a bit more supported than gradient:
- http://caniuse.com/#search=box-shadow (works in IE 9)
- http://caniuse.com/#search=css%20gradient (doesn't work in IE 9)

**Comment by billoliver** [comment]
Okay, this one looks more "clickable".
![button](https://cloud.githubusercontent.com/assets/17387379/13919659/9039f364-ef4d-11e5-8118-e31617a3b0c7.png)


```
.search_bar .search-submit-button {
  cursor: pointer;
  width: 70px;
  height: 30px;
  padding: 2px 0 4px 0;
  background: rgb(255, 255, 255);
  background-image: -webkit-linear-gradient(top, #ffffff, #d1d1d1);
  background-image: -moz-linear-gradient(top, rgb(255, 255, 255), rgb(209, 209, 209));
  background-image: -ms-linear-gradient(top, #ffffff, #d1d1d1);
  background-image: -o-linear-gradient(top, #ffffff, #d1d1d1);
  background-image: linear-gradient(to bottom, rgb(255, 255, 255), rgb(209, 209, 209));
  -webkit-border-radius: 2;
  -moz-border-radius: 2;
  border-radius: 2px;
  text-shadow: 0px 0px 1px rgb(255, 255, 255);
  -webkit-box-shadow: 0px 1px 0px #000000;
  -moz-box-shadow: 0px 1px 0px #000000;
  box-shadow: 0px 1px 0px rgb(0, 0, 0);
  font-family: Arial;
  color: RGB(3, 3, 3);
  border: solid rgb(255, 255, 255) 1px;
  text-decoration: none;
}
```

**Comment by alanfgh** [comment]
Yes, it does look more clickable.

**Comment by trang** [comment]
I've set this to "accepted".

We'll have to be careful though about the use of `box-shadow`. Gillux removed this property from our modules background because it was slowing down the scrolling (https://github.com/Tatoeba/tatoeba2/commit/51d4771ba727bfaa8b891aa9f59d030fa34804dc).

**Comment by fadhelafif** [comment]
sorry, i don't know the status is accepted

but, i come with other solutions, with darker border color, smaller icon and style to another condition.
i think this become simplier than last solutions.

![a21](https://cloud.githubusercontent.com/assets/5837300/14771240/f3291dd4-0aae-11e6-9933-a6afff1d69f1.jpg)

1. normal
2. hover
3. active/click

**Comment by trang** [comment]
@fadhelafif, seems fine for me. You can go ahead and make these changes in your pull request. I'll then update the dev website with your changes and ask the community for feedback.

**Comment by alanfgh** [comment]
Looks good to me.
