### ISSUE TITLE
Bug on "My Collection" (my ratings) list when nothing has yet been rated

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#739]
I assume this only shows for one's own personal list, or maybe it's just a bug with my list.
(To make it clear, I have not rated any sentences yet.)

My list shows a message that Sentence #0 has been deleted.  (There's a spelling error, too.  "beed")

<img width="825" alt="screen shot 2015-08-11 at 9 05 21 am" src="https://cloud.githubusercontent.com/assets/7934273/9187605/7b43d438-400d-11e5-9fe8-c21b170bd9d3.png">

For comparison, ...

Trang's list shows one English sentence.

<img width="727" alt="screen shot 2015-08-11 at 9 05 53 am" src="https://cloud.githubusercontent.com/assets/7934273/9187601/720048e8-400d-11e5-924e-c04a4e473d41.png">

Sysko's shows nothing.

<img width="722" alt="screen shot 2015-08-11 at 9 06 21 am" src="https://cloud.githubusercontent.com/assets/7934273/9187598/6d9362e0-400d-11e5-815b-c1c584c2964d.png">

**Comment by trang** [comment]
This only appears on your page. You are the only user who has an entry with a `sentence_id = 0` in your collection.

This entry has been added to the database at this date and time (UTC): 2015-08-10 23:56:26.

<pre>
mysql> select * from users_sentences where sentence_id = 0;
+-----+---------+-------------+-------------+---------------------+---------------------+-------+
| id  | user_id | sentence_id | correctness | created             | modified            | dirty |
+-----+---------+-------------+-------------+---------------------+---------------------+-------+
| 601 |    1396 |           0 |           1 | 2015-08-10 23:56:26 | 2015-08-10 23:56:27 |     0 |
+-----+---------+-------------+-------------+---------------------+---------------------+-------+
1 row in set (0.00 sec)
</pre>
