### ISSUE TITLE
Create a page where users can see their ratings that are outdated

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#747]
**Problem**

Users have the possibility to rate sentences as OK, not OK or undecided. Note: this feature needs to be activated in the Settings.

When a user rates a sentence, and the sentence gets modified afterwards, the rating becomes outdated, but the user has no simple way to be aware of it. This happens typically when a user marks a sentence as "not OK" because it contains a mistake, and the sentence is corrected later on. The "not OK" rating is no longer relevant and can be confusing even.

**Suggested solution**

* On the sentence's details page, ratings that are outdated should be clearly identifiable. For this, we can add `(outdated)` after the username.
* In the "My collection" section, we can add a link "Outdated ratings" in the sidebar menu.
* The page "Outdated ratings" will list all the sentences that have been modified after the user has rated the sentence.
* The sentence on the "Outdated ratings" will be displayed the same way as on the other pages of "My collection". The user will have to click on the `#` icon to go to the sentence's details in order to change the rating. It would of course be more practical if the user can change the rating directly from the "Outdated ratings" page, but the focus of this issue is to give users the possibility to easily find their outdated ratings.

**Comment by ckjpn** [comment]
Related:

Create a page where members can see only sentences rated as bad or unsure.

This might help members who want to help correct bad sentences to find such sentences and leave comments helping the owner make corrections.

**Comment by RyckRichards** [comment]
By Pfirsichbaeumchen on the [Wall](https://tatoeba.org/eng/wall/show_message/26631#message_26631):

"Request.

If a sentence has been reviewed but is changed afterwards, it would seem prudent that all checkmarks should be removed, perhaps with a message sent to each of the reviewers to give them the opportunity to review the sentence again."

**Comment by trang** [comment]
@zachleigh I've updated the description and I'm assigning this to you.

**Comment by zachleigh** [comment]
@trang On the users_sentences table, what is dirty for? It doesnt appear to be used at the moment. Is it supposed to be set to 1 if the sentence gets edited?

**Comment by trang** [comment]
@zachleigh, yes it is meant to be for when the sentence gets edited. It was intentionally not implemented back then, since there was no clear idea yet how to handle the case of when a sentence gets edited. But now we have a clearer idea.
