### ISSUE TITLE
Export users_sentences into CSV file

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#748]
The `users_sentences` table contains the data for the "collection"/"reviews" feature.

The fields exported are:
- username
- sentence_id
- correctness
- created
- modified

**Comment by ckjpn** [comment]
Perhaps you could write a tool that read the "sentences_detailed.cvs" and exported only sentences by a given username.  Maybe that would lessen the load on the database.

**Comment by trang** [comment]
This won't lessen the load on the database. It can lessen the bandwidth usage but that's not really a problem.
Also, this is a tool that anybody can write and it can be hosted anywhere. It doesn't have to be in Tatoeba.
