### ISSUE TITLE
Literary Chinese -> Chinese (literary) / Min Nan Chinese -> Chinese (Min Nan)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#750]
Since now Mandarin Chinese is "Chinese (Mandarin)" in the dropdown list, maybe to have some more consistency also literary Chinese and Min Nan Chinese should be changed respectively to "Chinese (literary)" and "Chinese (Min Nan)" (or whatever version).

**Comment by alanfgh** [comment]
This makes sense to me. Any objections?

**Comment by trang** [comment]
This should be asked on the Wall I think. 

The main question is, do people who look for "Min Nan Chinese" will tend to type "Chinese" first or "Min Nan" first?

**Comment by trang** [comment]
I'll close this since #936 covers the issue.
