### ISSUE TITLE
Can't unadopt (release) a sentence in Safari

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#753]
I was unable to unadopt this sentences using Safari on a Mac.
https://tatoeba.org/eng/sentences/show/1465186
I had to use Firefox to do so.

I noticed this bug when I tried to change the ownership of a sentence from CM to CK.

I had automatically adopted all sentences previously owned by Guybrush88 that I had tagged OK using the username CM, since at that time I didn't want to re-read all the sentences.

**Comment by RyckRichards** [comment]
Related to #758

**Comment by RyckRichards** [comment]
Mentioned by CK on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24185#message_24185)

**Comment by ckjpn** [comment]
It's now possible to do this, but the behavior isn't exactly as expected.

You can't click just anywhere on the icon, but if you click on the left-side, or just to the left of the icon, it seems to work.  I think perhaps it works better if you click low near the body and not higher near the heard, but I can't quite remember.

I suppose that since this really isn't working like one would expect it to work, that this shouldn't yet be closed.  I suspect this has something to do with the CSS not putting the icon where it should be.  However, I'm just guessing.

**Comment by ckjpn** [comment]
This is very likely related.

https://tatoeba.org/eng/wall/show_message/24499#message_24499

**Comment by RyckRichards** [comment]
cueyayotl could reproduce this bug today.

**Comment by RyckRichards** [comment]
Silja also confirmed that.

**Comment by halfdan** [comment]
@ckjpn Can you still confirm this bug today? Want to make sure it still exists in the latest Safari before diving in to fix it.

**Comment by ckjpn** [comment]
I adopted and unadopted a few sentences today using Safari with no problem.

I remember at the time I reported this that this was a problem that just happened sometimes and not all the time.

**Comment by trang** [comment]
I'm marking this rejected for now. Will close this if no one can reproduce.
