### ISSUE TITLE
CSS needs corrected for Safari

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#754]
Notice that some of the icons above the sentence are not properly displayed.
![screen shot 2015-08-29 at 09 14 02](https://cloud.githubusercontent.com/assets/7934273/9560053/b870bce4-4e3c-11e5-8a38-9056065488e4.png)
(Screenshot of Safari on a Macintosh)

**Comment by PaulPeer** [comment]
Right. And they also cannot be selected. Same problem as for Safari on iPhone.

**Comment by RyckRichards** [comment]
Mentioned by CK on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24185#message_24185)

**Comment by RyckRichards** [comment]
According to Paul, they look good now, but the heart button doesn't  work as well as the v, ? and ! buttons.

**Comment by RyckRichards** [comment]
cueyayotl says that  cons appear but they are not clickable.

**Comment by RyckRichards** [comment]
It happens both in Macbook and iPhones, according to Silja.

**Comment by RyckRichards** [comment]
according to Paul, this bug has been fixed.
