### ISSUE TITLE
Possibility to sort order of sentences in collection

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#756]
Based on request: https://tatoeba.org/eng/wall/show_message/24045#message_24045

We can add links to sort the sentences by:
- sentence id
- modification date

(similarly to what we have on [tags](https://tatoeba.org/eng/tags/view_all) or [list of members](https://tatoeba.org/eng/users/all))

By default the sentences would be ordered by modification date, most recent one first.

**Comment by ckjpn** [comment]
Perhaps you could also offer a way to sort them (1) alphabetically and (2) by length.

**Comment by trang** [comment]
That would take more resources.

**Comment by theblindspring** [comment]
I will work on this.
