### ISSUE TITLE
Autocompletion of tags is not up-to-date

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#757]
Related to #301 
Guybrush88 reports that the Autocompletion doesn't show the new tags, just the old ones. https://tatoeba.org/eng/wall/show_message/24068#message_24068

Example: Futuro - https://tatoeba.org/eng/tags/view_all/futuro  It shows all tags except the Tag "Futuro"

**Comment by Guybrush88** [comment]
Actually it's the contrary. Autocompletion shows only "futuro", which doesn't exist (but it used to)

**Comment by RyckRichards** [comment]
fixed!

**Comment by RyckRichards** [comment]
Mentioned by Guybrush88 on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24194#message_24194)
