### ISSUE TITLE
have a way to detect duplicates which differ only in terms of script

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#76]
such as traditional/simplified chinese

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/296

**Comment by jiru** [comment]
So this could be implemented rather easily now #77 is implemented. However, when merging two or more sentences, which one should we keep? There are pairs of Chinese duplicates written in [traditional](https://tatoeba.org/sentences/show/4962293) and [simplified](https://tatoeba.org/sentences/show/4881620) by different users. I don’t think either of them would be happy with having her sentence deleted in favour of the other.

**Comment by trang** [comment]
Closing because this is not something we can automate.

If we have two sentences that differ only in terms of script, we will have to handle the case manually, in a similar way as what we would have to do with French sentences that differ only by a space (#770).
