### ISSUE TITLE
Untranslated string in translated UI

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#760]
When you want to search for something which isn't yet in Tatoeba's database, you have the untranslated string "No results found for:"
Example: https://tatoeba.org/ita/sentences/search?query=%22%3Dpiu%22&from=ita&to=und

This string isn't on Transifex for translation.

This issue showed up after the latest update a few days ago

**Comment by RyckRichards** [comment]
A Print shot: 

http://prntscr.com/8bt729

**Comment by trang** [comment]
Should be okay now. It was just that the latest strings were not extracted and imported into Transifex.
