### ISSUE TITLE
Microsoft Edge web browser doesn't show important buttons

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#761]
By ToinhoAlam (September 02, 2015)

https://tatoeba.org/eng/wall/show_message/24083#message_24083

"Hello everybody. I'm new to Tatoeba and I'm willing to help a lot! I would also like to make an advice about the Microsoft Edge web browser (mine, at least). It doesn't show those important buttons (translate, edit, add to list...). Therefore, if anyone could fix that it would be great. I'm using the Internet Explorer for now because Tatoeba runs perfectly on it. Thanks for any help."

**Comment by RyckRichards** [comment]
Mentioned by CK on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24185#message_24185)

**Comment by RyckRichards** [comment]
According to ToinhoAdam, icons like "Translate", "Add to Favorites", "Add to list", are now clickable but chopped. He sent me those screenshots comparing Internet Explorer and Microsoft Edge - https://goo.gl/1x8snI . Also, some other buttons are not displayed.

**Comment by Guybrush88** [comment]
I'm adding also this screenshot for the random sentences page with Microsoft Edge: http://imgur.com/RmX6mX8

**Comment by Guybrush88** [comment]
also the search icon is missing and misaligned: http://imgur.com/LqWkfYr

**Comment by RyckRichards** [comment]
According to some users, #761 is still valid.

**Comment by Guybrush88** [comment]
I can still reproduce this bug

**Comment by Guybrush88** [comment]
While using Edge 84.0.522.50 (64 bit version) under Windows it appears that this bug of the old doesn't exist anymore, the icons above the sentence are shown properly

**Comment by jiru** [comment]
Cool! Thanks for reporting this to us Guybrush. @trang can you confirm?
