### ISSUE TITLE
Can't remove sentences from collaborative list

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#762]
I'm trying to remove sentences from the list "For CMs: Need to be corrected":

https://tatoeba.org/eng/sentences_lists/show/4654

but am unable to do it on both Firefox and Chrome. Clicking on the red X has no effect.

**Comment by ckjpn** [comment]
This used to be a problem only with long lists, so for a short list, this
is a recently-introduced bug.

You can use this following JavaScript code as a bookmarklet on any sentence
page to remove that sentence from a list.

I've been using this for a while (with a different default list number).

javascript:var a%3Dwindow.prompt("Enter the list number to remove this
sentence
from","4654")%3Bif(a!%3Dnull%26%26location.href.search(/tatoeba%5C.org%5C/.%2B%5C/sentences%5C/show%5C//)!%3D-1%26%26a.match(/%5E%5B0-9%5D%2B%24/)!%3Dnull)location.href%3Dlocation.href.replace("sentences/show","sentences_lists/remove_sentence_from_list")%2B"/"%2Ba%3B

--
-- Charles Kelly <cknagoya@gmail.com>
-- http://aitech.ac.jp/~ckelly/
--

**Comment by ckjpn** [comment]
I just experimented with this.

It seems that the owner of a collaborative list can remove items.
However, to be truly collaborative, any member should be able to do so.

If you intended this to be one of the limits, then perhaps allow corpus maintainers and advanced contributors to remove items.

I'm fairly certain I had no problem removing items before, so I think this is a new bug and not intentional.

**Comment by ckjpn** [comment]
I experimented again with this list.
Perhaps this will trigger some idea about why this isn't working properly.

https://tatoeba.org/eng/sentences_lists/show/992

It seems that I can't click the X to remove a sentence from that page, but a URL will unlink a sentence.

https://tatoeba.org/eng/sentences_lists/remove_sentence_from_list/1027251/992

This format:
https://tatoeba.org/eng/sentences_lists/remove_sentence_from_list/__SENTENCE_NUMBER__/__LIST_NUMBER__

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on [Tatoeba Day 11](https://tatoeba.org/eng/wall/show_message/24866#message_24866).
