### ISSUE TITLE
Add sorting options to "Tagged '@change' more than 2 weeks ago" and Tagged '@delete' more than 2 weeks ago.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#764]
*\* The Problem **

The problem with the way it's setup now is that only the first 100 sentences are shown.
Many of these sentences are difficult to deal with, so have been ignored.
This means that all the other sentences are being ignored because we can't see them.

*\* Possible Solutions **

One solution for improving this would be to allow for various methods of sorting.
1. Sort from shortest to longest.
2. Sort from oldest to newest
3. Sort from newest to oldest
4. Sort by date the tag was added newest to oldest.
5. Sort by date the tag was added oldest to newest.
6. ? Sort by owners' usernames  (Perhaps this would help.)
7. Random selection.

Maybe others have other suggested sorting ideas.

*\* Ideas to Consider **

Maybe this could somehow be accomplished with the "advanced search" by having the option to search for sentences with tags, limited to those that were tagged over 2 weeks ago.  If this would be possible, then the "tags/for_moderators" pages may not be needed anymore.  We could also search for other tags such as "@change punctuation" that were tagged over 2 weeks ago.

Another possible solution might be to have some way to mark a sentence as "looked at but ignored."

*\* Links **

Tagged '@change' more than 2 weeks ago
https://tatoeba.org/eng/tags/for_moderators/561/eng

Tagged '@delete' more than 2 weeks ago
http://tatoeba.org/eng/tags/for_moderators/370/eng

**Comment by RyckRichards** [comment]
For now, I'm adding sentences that weren't corrected in 2010, 2011, 2012 here ► https://tatoeba.org/eng/sentences_lists/show/4654 and I "collect" them using the rating system (not OK) - https://tatoeba.org/eng/collections/of/ricardo14

**Comment by RyckRichards** [comment]
We do need need it! Many members are giving up since they find some non-natural sentences (c.f. Korean ones). Is it hard to implement, @jiru @trang @alanfgh @Tatoeba/tatoeba-team ?

**Comment by jiru** [comment]
> Is it hard to implement?

No, I think it’s easy.

**Comment by Poulpisator** [comment]
@jiru Hasn't this become obsolete?

**Comment by trang** [comment]
It's obsolete. The `/tags/for_moderators` page has been removed back in #1411.
