### ISSUE TITLE
Allow people to limit searches to sentences on certain lists

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#767]
Make it so people can limit searches to a certain list or lists, similar to the way it can now be done with tags.

For example, members who would like to limit their searches to sentences that I've personally proofread could enter the following 2 list numbers.

907, 996

*\* Related URLS **

Here are the full URLs to those lists:
http://tatoeba.org/sentences_lists/show/907/und
http://tatoeba.org/sentences_lists/show/996/und  *note 2015-12-29: what was previously here was moved to 907.

Here is the link to our advanced search:
https://tatoeba.org/eng/sentences/advanced_search

**Comment by RyckRichards** [comment]
Requested by CK on [Tatoeba Day 7](https://tatoeba.org/eng/wall/show_message/24192#message_24192)

**Comment by ckjpn** [comment]
I would like to ask that this be set to "priority high."

This would allow members to search for sentences limited to list 907 which currently has 379,286 sentences.  This would mean that people could be fairly certain that the sentences they found were correct and natural-sounding.  I think this would enhance the user experience, and would help encourage members to translate "good" sentences, which would help improve the quality of the Tatoeba Corpus.

To put this in perspective, 379,286 proofread English sentences is more than the 4th language Turkish which has 378,021 sentences.



This is somewhat related to the following issue.
in list view allow showing sentences "not directly translated into" #611
https://github.com/Tatoeba/tatoeba2/issues/611

#611 would be a nice feature, but wouldn't really be necessary if this could be done with "advanced search", since the advance searching allows excluding sentences with direct links to a selected language.

**Comment by ckjpn** [comment]
Related Wall Post:  https://tatoeba.org/eng/wall/index#message_25413


> I also wonder if we could develop a set of good sentences that contributors of every language could consider translating. 

This could be done right now with lists. A collaborative list would be possible, but that opens up the possibility accidental or malicious additions and deletions.

Instead, I would suggest that each member interested in this idea should create a list and add sentences to it as they find such sentences.

Here as an example list that I have.
https://tatoeba.org/eng/sentences_lists/show/4003

Hopefully, we will eventually have the possibility to search lists. (See https://github.com/Tatoeba/tatoeba2/issues/767). We could then search for sentences on these lists that are not yet translated into our own native languages. If we are also allowed to search more than one list at a time, we could choose which members' lists we felt we could trust, and then do our searches on more than one list at a time.

**Comment by ckjpn** [comment]
I'm glad this one has been accepted.
This would likely be very beneficial to members.

**Comment by jiru** [comment]
To me, the most difficult problem with this issue is to allow users to select lists in the form, in a usable and efficient way. There is no way people will use list ids directly in the form like you suggested, because we do not show them anywhere in the site, and one needs to go to the list page, copy the id from the URL to the form, which is inefficient and bothersome.

I’d rather limit the search on a single list and use a drop down list like the one that appears when clicking on the *Add to list* sentence button. From there, we could even make it easy to search for lists by keywords using Chosen (the advanced language selector thing).

**Comment by ckjpn** [comment]
I wonder if there is any possibility that this could be added soon, even if it's not included in the search form. Maybe the UI could be developed later.   All I would need is to be able to insert something like &list=907 into the URL.

I would love to be able to develop something like the following that searched through all sentences on list 907.

Try the following, changing the t= variable to the 3-letter code for your native language.

NGSL Words - English sentences with audio that have translations and those that don't
http://tatoeba.ueuo.com/ngsl/?t=fra

See the related Wall post.
https://tatoeba.org/eng/wall/show_message/26407#message_26407

There are currently 219,157 English sentences with audio, which is only 56% of the good, proofread English sentences on list 907.  This means there would be a 77% increase in the number of sentences that would be available for such a tool if I could limit searches to a list.

List 907 currently has 388,154 sentences.
https://tatoeba.org/eng/sentences_lists/show/907/und

**Comment by ckjpn** [comment]
Additionally, this feature would allow someone to more easily find untranslated sentences to translate such as the following.

Maybe female contributors would find it interesting to translate sentences recorded by a female voice, such as the sentences on this list.  Many of the sentences on this list require a female speaker.

https://tatoeba.org/eng/sentences_lists/show/6229/und

Being able to search all sentences on this list, limited to those not yet translated into French, would allow a French native speaker like TRANG to easily translate the sentences that did not yet have French translations.

**Comment by ckjpn** [comment]
Since this issue seems to be taking a long time to solve, I will probably add a tag to all sentences in List 907 with the tag "List 907" so that members can limit searches to these 399,665 proofread English sentences.

Perhaps this is the best temporary solution for this.


>On a side note, implementing this would be virtually the same as implementing non-standard tags.
>>As a user I want to be able to search sentences filtering by list(s).
>This is not yet possible, but there is an issue for it: #767
FROM: https://github.com/Tatoeba/tatoeba2/issues/1198#issuecomment-230149440
