### ISSUE TITLE
Have proper romanization / alternative script attached to sentences

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#77]
Some languages like Japanese have an alternate script that completes the main script. Japanese can’t be read (or is quite hard to read) with 100% accuracy using its sole main script and requires the help of furiganas to specify the reading of kanjis (especially in names). Furthermore, furiganas greatly help beginners (natives and non-natives) to learn reading Japanese. Currently, we store the main script as the sentence and autogenerate furiganas with the help of Mecab. While it works most of the time, it’s a constant source of errors because generating furiganas can’t be 100% automated. A current workaround consists of appliying the “furigana mistake” tag. In order to reach 100% reading accuracy in Japanese and help beginners, we need to allow users to edit these furiganas. Which means we also need to store them in the database.

Romanization consists of converting a non-Roman-based script to the Roman (Latin) script. Romanization could help looking up sentences in non-Roman-based language using a Roman-only capable system. Romanization also helps natives of Roman-based language to learn non-Roman-based languages. Proper romanization of Japanese requires correct furiganas. I don’t know about the other languages but I think romanization can be mostly autogenerated and thus wouldn’t require to be stored in the database.

In order to implement this, we need to know:
* what languages need alternate script
* what languages could benefit from romanization (and make sure we can autogenerate it with 100% accuracy)
* how to store the alternate script (what data format would be the best and would work for all the languages that need it)
* build a proper interface to allow edition of alternate script
* how to export the alternate script in the CSV, if we decide to do so

**Comment by jiru** [comment]
Note to self: add Cyrillic/Latin transcriptions for Serbian too. [Wall post](https://tatoeba.org/jpn/wall/show_message/22532#message_22532).
