### ISSUE TITLE
Show usernames after translations and indirect translations.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#771]
I wonder if it would be possible to add in usernames after translations and indirect translations.

I think this would be useful, since members eventually learn who the native speakers of the language they are learning are.  If they see one of those member's names attached to a translation, they can be more confident that it's a good sentence.

I don't think you need to make those usernames clickable, though.  Just show them -- possibly even smaller and in a lower-contrast font color (gray, maybe).

The only way to find out this information now is to click to the page with the translations to see who the owner is.

I've been doing something similar to this idea for the past few years.
Here's one example, so you can see what I mean.
http://www.manythings.org/sentences/audio/1.html
![screen shot 2015-09-15 at 09 25 00](https://cloud.githubusercontent.com/assets/7934273/9865099/a8c56134-5b8c-11e5-8889-72b8ef14e0d2.png)

**Comment by ckjpn** [comment]
I think this one is likely not too difficult to do.

**Comment by ckjpn** [comment]
https://github.com/Tatoeba/tatoeba2/issues/48 is related to this one.

**Comment by jiru** [comment]
It is true that currently, we are mostly relying on usernames to trust sentences. Hence the need of displaying usernames everywhere. However, I’m not sure it’s a good idea because I’m afraid it will only benefit a minority of power-users, while it will just clutter the interface with useless information for the majority of users.

**Comment by trang** [comment]
I'm marking this issue as "rejected" because @jiru makes a good point.
