### ISSUE TITLE
The group column doesn't sort properly on https://tatoeba.org/eng/users/index/page:1/sort:group/direction:asc

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#774]
https://tatoeba.org/eng/users/index/page:1/sort:group/direction:asc
(Note that you need to be an admin to see this page.)

The group column doesn't sort properly.
All the other columns work as expected.  Clicking the column title sorts, and clicking again reverses the sort.

**Comment by trang** [comment]
This can be tested on the dev website.
