### ISSUE TITLE
"Insecure information on this page was blocked" message appearing in the SeaMonkey browser.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#776]
On loading this page into SeaMonkey, I got this "Insecure information on this page was blocked" message at the top of the page.  The http://www.seamonkey-project.org/ is part of https://www.mozilla.org/ which also does Firefox, so maybe this shows up for some users of Firefox, too.

https://tatoeba.org/eng/sentences/show/51990
![screen shot 2015-09-21 at 08 46 31](https://cloud.githubusercontent.com/assets/7934273/9983628/08e6cf66-603e-11e5-9821-1f3589917cef.png)

**Comment by jiru** [comment]
This message means the page tries to load a resource (typically css file, javascript file, image etc.) using http whereas the page was loaded using https. Could you try to figure out what it is trying to load?

**Comment by ckjpn** [comment]
In Chrome, according to the following menu item ....

View : Developer : Developer Tools : Network

... this files are being loaded.


default.css?1438034984	
elements.css?1442256882	
show.css?1442256882	
jquery-1.11.3.min.js	
generic_functions.js?1434995576	
svg4everybody.min.js?1430581215	
jquery.scrollTo.min.js?1442536374	
sentences.logs.js?1432419937	
sentences.random.js?1432419937	
sentences.add_translation.js?1432419937	
favorites.add.js?1442256882	
sentences_lists.menu.js?1432419937	
sentences.link.js?1422122872	
sentences.change_language.js?1432419937	
sentences.play_audio.js?1431282299	
sentences.collapse.js?1442256882	
links.add_and_delete.js?1432419937	
autocompletion.js?1442256882	
tags.add.js?1442256882	
chosen.css	
profile.svg?1425138818	
no_mail.svg?1425138818	
log_out.svg?1425138818	
arrow_down.svg?1431180263	
tatoeba.svg?1424530369	
loading.svg?1432419937	
search.svg	
adopted.svg?1430581215	
translate.svg?1430581215	
edit.svg?1430581215	
favorite-add.svg?1430581215	
audio.svg	
audio-unavailable.svg	
logs-sentence-added.svg	
logs-link-added.svg	
analytics.js	
collect?v=1&_v=j39&a=1372215821&t=pageview&_s=1&dl=https%3A%2F%2Ftatoeba.org%2Feng%2Fsentences%2Fshow%2F51990&dr=https%3A%2F%2Fgithub.com%2FTatoeba%2Ftatoeba2%2Fissues%2F776&ul=en-us&de=UTF-8&dt=English%20example%20sentence%3A%20Scotland%20is%20famous%20for%20its%20woollen%20textiles.%20-%20Tatoeba&sd=24-bit&sr=2048x1152&vp=1135x644&je=1&fl=18.0%20r0&_u=ACCAgEAB~&jid=&cid=1833113145.1429184369&tid=UA-2905820-1&z=1940683451	
ita.png?1395590761	
pes.png?1395590761	
ber.png?1395590761	
eng.png?1395590761	
spa.png?1395590761	
indicator.html	
tur.png?1395590761	
indicator.css	
jquery-1.9.1.js	
indicator.js	
indicator-couch@2x.png	
jpn.png?1395590761	
fra.png?1395590761	
cmn.png?1395590761	
epo.png?1395590761	
list.svg?1430581215	
link.svg?1430581215	
delete.svg?1430581215	
sentence-number.svg?1430581215	
translation.svg?1430581215	
valid_16x16.png?1395590761	
unlink.svg?1430581215	
glg.png?1395590761	
pol.png?1395590761	
b9e23031f83c81299b48e3d746d43a10.png?1412864790	
nr-536.min.js

**Comment by jiru** [comment]
So I think that one of these is loaded using http, and is likely to be injected by one of your seamonkey scripts. These are the most probable culprits: indicator.html, indicator.css, indicator.js, indicator-couch@2x.png.

**Comment by ckjpn** [comment]
I can't seem to duplicate the bug now, so I'm closing this.  Sorry to have bothered you.
