### ISSUE TITLE
"Add sentence to list" form misaligned in Chrome

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#778]
This is how I see this on Chrome on a Macintosh.  Perhaps this is a problem with other browsers, too.  I didn't check.

https://tatoeba.org/eng/activities/translate_sentences_of/boracasli/eng/page:2

Before clicking.

![screen shot 2015-09-23 at 19 08 38](https://cloud.githubusercontent.com/assets/7934273/10042551/c824c4ca-6226-11e5-973b-e751309afc24.png)

After clicking.

![screen shot 2015-09-23 at 19 08 47](https://cloud.githubusercontent.com/assets/7934273/10042538/b7e11c6c-6226-11e5-832f-e90c25741074.png)

A year or so ago, this didn't happen.

**Comment by RyckRichards** [comment]
@ckjpn Can you reproduce this bug yet? I tried on Google Chrome but I couldn't

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/13905574/829c57a2-eea2-11e5-8f99-446adef0884c.png)

**Comment by RyckRichards** [comment]
sacreceltic tried to reproduce this bug but he couldn't. Closing this issue.
