### ISSUE TITLE
Translations aren't grouped by language when browsing a list.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#779]
Translations aren't grouped by language when browsing a list.
On similar, pages, they are.

https://tatoeba.org/eng/sentences_lists/show/4023/und

![screen shot 2015-09-24 at 21 23 02](https://cloud.githubusercontent.com/assets/7934273/10073271/9d4556de-6302-11e5-817f-a58d18751a5c.png)

**Comment by jiru** [comment]
Fixed in 7394dea1773f27f3a52a97c852cd933d3f29a878.
