### ISSUE TITLE
Turn "languages" helper into a model and use it to store lang code

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#78]
Most of the requests in the language help are in fact "models" like data / request

Moreover, most tables store a "lang" parameter. It should be stored in the langStats table. This way it will be easier to add a new language and be sure no "bad" language codes are added. It will also save room (int vs varchar(4)).

**Comment by trang** [comment]
Closing this. The languages list was moved to a LanguagesLib class in app/vendors (#629).
