### ISSUE TITLE
Make display of transcriptions/transliteration optional

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#784]
This addresses the question asked in the following thread:
https://tatoeba.org/eng/wall/show_message/24290#message_24290

My personal opinion is that transcriptions can be useful, but they don't need to be displayed for everyone all the time. For some (many?) people, they just waste space.

For a start, we could go with the following:
- All the transcriptions are by default NOT displayed.
- Users can display them by going to their Settings and check the corresponding option ("Display transcriptions and transliterations"), which would display the transcriptions in all the languages for which we have transcriptions.

Things we would consider later on:
- There may be some languages for which we'd want to display the transcriptions by default.
- We can let users choose specifically in which language they want to activate the transcriptions.
- We can implement this option in a way that doesn't require users to register to display transcriptions.

**Comment by ckjpn** [comment]
I think this is good.

I agree that transcriptions/transliteration can be useful, and I also agree that probably most of us using the site think they waste space.  Perhaps including them also slows things down with additional database requests.  I'm not sure about that.

If all transcriptions/transliteration are not displayed by default, then I think many of us would have no big objections to including these even for languages that perhaps don't really need them.

> There may be some languages for which we'd want to display the transcriptions by default.

There may be, but if it's easy for members to turn transcriptions on and off, then maybe we shouldn't have any on by default.

> We can let users choose specifically in which language they want to activate the transcriptions.

This should be done.

One possible idea is to have just an ON and OFF option in the settings, but only do the ON for languages members have declared, but not declared as "native."   This might simplify the user interface, and possibly even the programming.

**Comment by trang** [comment]
This was done in #661.
