### ISSUE TITLE
Display a different collor if the sentence was posted by a native speaker.

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#788]
We already flag sentences in red in order to show if it's against Tatoeba rules. However, we could "promote" sentences and members after a set up a "vote system"  maybe. It's a way to say that any new member - or not so new  - can translate it once this user has been approved by Tatoeba community. Also, only trusted users could apply to be an AC, CM, etc.

**Comment by ckjpn** [comment]
Here are some related thoughts.

1. To defeat the intended purpose of this suggested enhancement, all a troll has to do is indicate every language he/she contributes in as "native level."  We already have several members who indicate more than one language as "native level".  (I'm not accusing these members of being trolls.)

2. One possible remedy to #1, would be to only allow members to specify what their strongest language is as "native", and call the other high-level languages as "fluent", or create another level called "near native" or "native like".

3. Even with #2, trolls can always lie about this.

**Comment by RyckRichards** [comment]
That's why I suggested a "**vote system**, @ckjpn . we could even use the new rating system to make sure that the user is trustable or no and if so, display a different collor for his sentences or no.

**Comment by RyckRichards** [comment]
Requested by Lazovic  on [Tatoeba day #11](https://tatoeba.org/eng/wall/show_message/24880#message_24880).

**Comment by trang** [comment]
This feature already exists (cf. #726).

It was made optional (cf.  #743), so you have to activate it in your settings.

People have indeed complained that the "native" indicator was showing up on sentences from members who are not really native, which is why the feature is an option.

I'm closing this ticket.
