### ISSUE TITLE
New users have to add their native or strongest language when register

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#793]
1- when someone creates a profile, he/she actually doesnt need to tell us what is his/her native language. All we do is to encourage(invite him/her) to tell us his /her native language and so

> some people get confused about that (even the fact the instructions are quite clear),

>  this new user may add in his/her profile languages that he/she doesnt speak.

We could "fix" that by asking him/her to tell us his/her native language on the same page that they use to register. It would avoid confusion

![image](https://cloud.githubusercontent.com/assets/7658430/10183539/492d95a8-6707-11e5-9bd7-0ac92f433d7b.png)

**Comment by jiru** [comment]
That’s a very good idea.

**Comment by RyckRichards** [comment]
Requested by [Ricardo14](https://tatoeba.org/eng/user/profile/Ricardo14) on [Tatoeba Day #12](https://tatoeba.org/eng/wall/show_message/24990#message_24990).
