### ISSUE TITLE
Redirect new users to Quick Start Guide instead of the Home page

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#795]
After a new user  creates an account, he or she should be redirected to "Quick Start Guide" page and/or "FAQ". So, this user would know what is Tatoeba for and how he/she can help us and know how to "work" properly there.

**Comment by ckjpn** [comment]
This should be easy to do, and would likely be very helpful.

**Comment by RyckRichards** [comment]
@Tatoeba/tatoeba-team What do you think about it?

**Comment by ckjpn** [comment]
It would likely be better to have a special page set up as part of tatoeba.org's main set of pages with either the full quick start guide or a cut down version with several links.

One problem with redirecting the that Wiki page is that it is is not a part of the main site and has a different navigation bar at the top of the pages.  This could easily confuse new members, I think.

Maybe a simple page with something like the following would be better.

Welcome to the Tatoeba Project. 

1. Choose your preferred language interface.

2. Visit your profile page and tell us what your native language is and what other languages you know.

3. Read the Quick Start Guide.

We have a quick start guide in the “More” menu.
http://en.wiki.tatoeba.org/articles/show/quick-start

** The 2 Ways You Can Be the Most Helpful **

1. You can translate from a foreign language you know into your own native language or strongest language.

2. You can create natural-sounding sentences in your own native language for others to translate into their native languages.


** W

**Comment by jiru** [comment]
There is one thing I really don’t like about redirecting to the “Quick Start Guide”: it’s that we are presenting every new member an English guide (while they were likely using a localised version of the site). To me, this is quite of a problem for a site like Tatoeba where all languages are equals etc. New members should be directly provided with a translated guide. But technical problems detailed in #701 prevent us from doing this.

**Comment by RyckRichards** [comment]
We'd have to face this problem as soon as we can, as we can. I mean, for now, people would be redirected to the English version of this page - Im going to translate that into Portuguese - but as far as we're having more active members, they will also translate that sentences into their native languages. Perhaps we could ask that on that on the Wall...

**Comment by ckjpn** [comment]
I agree with jiru.
Temporarily, at least, perhaps we could have a simple page with the link I have suggested.
Perhaps it would be easier to find people to translate a short page than translate the complete quick start guide and all the guidelines.

At least a few of the basic rules have translations already.  Maybe these translations could be used to at least start an easier-to-understand page for many beginners.

For example, here are the first 2.
http://tatoeba.org/eng/sentences/show/611372
http://tatoeba.org/eng/sentences/show/611373

Even though the current English Quick Start Guide is in fairly simple English, many of my students would find it tedious to read and would ignore it.

**Comment by tommy-3** [comment]
I think we should consider improving the English version before translating it into other languages. The current page is too long, and the "6 Basic Rules" are also not really easy to understand. For example, it doesn't make sense to tell new members not to change sentences that are correct when they don't even know that they can adopt and change sentences that are wrong, does it?

**Comment by ckjpn** [comment]
The rules that seem to be most-commonly violated by new members are.

1. We want complete sentences.
2. Don't contribute copyrighted material.

This is a brief intro page I've had up for a while.
http://a4esl.com/temporary/tatoeba/

**Comment by RyckRichards** [comment]
That's the message I have been sending to some new members

((That would have to be changed. Maybe the "field" contact me could be
replaced by the one who is sending the message and/or some active
members))

Hi, my friend! How are you? Hope you're fine!
Welcome to the Tatoeba project! Hope you like it and have a lot of
fun, learn, and help us! We do need sentences here and you're going to
be so helpful!

Well, I think that itwould help you a little bit:

► Add any sentence you want - https://tatoeba.org/eng/sentences/add .
Try to add sentences into your native language. However, if you know
the sentence you're going to add is correct, them add it ;

► You can translate sentences from a specific language -
https://tatoeba.org/eng/sentenc.../eng/none/none (That will display
English sentences. You can change it by any other language you want to
translate sentences from.

!!! Important: When more than one translation is possible, you should
add each translation as a separate sentence. So please change this
sentence to one of both and add another one. So, we can't add, for
example, "What's (What is) his/her name?" We have to add two
translations (if possible):

-What's his name?
-What is his name?
-What's her name?
-What is her name:

► You can also create lists and ask somene to translate the sentences
in there for you - https://tatoeba.org/eng/sentences_lists/index .
Those are mine lists: I use to study languages (I'm studying over 35
languages):
-https://tatoeba.org/eng/sentences_lists/show/4065/
-https://tatoeba.org/eng/sentences_lists/show/3547


Read the Quick start guide -
http://en.wiki.tatoeba.org/arti...ow/quick-start and the FAQ -
http://en.wiki.tatoeba.org/articles/show/faq to help you!

Call me whenever you want.
► PM me on Tatoeba - https://tatoeba.org/eng/private...rite/Ricardo14
► Leave me a message on Facebook - Ricardo Vernaut Junior


You can find a complete guide about how to contribute here:
http://en.wiki.tatoeba.org/arti...ow/quick-start


Best wishes,

Ricardo

On 11/26/15, ckjpn <notifications@github.com> wrote:
> The rules that seem to be most-commonly violated by new members are.
>
> 1. We want complete sentences.
> 2. Don't contribute copyrighted material.
>
> This is a brief intro page I've had up for a while.
> http://a4esl.com/temporary/tatoeba/
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatoeba/tatoeba2/issues/795#issuecomment-159814073


-- 

Ricardo Vernaut Jr

Mobile // Celular: (5521) 967-640-668
Email: rvernautjr@gmail.com
<https://www.linkedin.com/in/vernautjr>

**Comment by ckjpn** [comment]
As Tommy-3 mentioned, maybe we don't need at least one of the current rules on the Quick Start Guide.

I sorted the rules on the Guidelines page in the wiki, to what I think maybe the priority order should be.
Maybe, we should decide how many of these should be in the Quick Start Guide.

http://en.wiki.tatoeba.org/articles/show/guidelines

The current Quick Start Guide is based off of a page I created a long time ago, which was an attempt to consolidate and briefly state some of the rules that Trang mentioned in blog posts that were hard for new users to find.  I also tried to make the page more concise than that blog posts.  I would have no complaints if someone can come up with something better.

This is my version of the Quick Start Guide.  Sysko grabbed this and converted it to the wiki format.
http://a4esl.com/temporary/tatoeba/quickstart.html

My current feeling is that something much closer to the following page would be better.
http://a4esl.com/temporary/tatoeba/
It's more concise, easier to scan, and only covers the bare minimum, I think.

If it can be made shorter, then that would be even better.  Something short that people read is better than something long and detailed that doesn't get read.

**Comment by RyckRichards** [comment]
+1000

**Comment by RyckRichards** [comment]
Requested by [Ricardo14](https://tatoeba.org/eng/user/profile/Ricardo14) on [Tatoeba Day #12](https://tatoeba.org/eng/wall/show_message/24991#message_24991).

**Comment by trang** [comment]
For the record, we used to redirect new users to the ["Help" page](http://tatoeba.dev/eng/help) after the registration. [I decided to remove this redirection](https://github.com/Tatoeba/tatoeba2/issues/631) because I don't think this is really helpful to new users (maybe to very few of them, but most of them probably don't read it).

So I'm not really in favor of redirecting new users to a Quick Start Guide. It's a possible solution to make users aware of what they can do and how to do it, but I don't think it's a good solution.

Solving this problem is a matter of redesigning the UI. Ideally, the UI should be intuitive enough that users don't need to read a guide. They should be guided smoothly into the discovery of each feature. But this is not necessarily easy to do.


For this specific issue, the question is: what problems are we trying to fix exactly? What are the things that current new users fail to do, that you would have expected them to succeed if they were redirected to a Quick Start Guide?

From the few feedbacks I got about usability, two problems were mentioned.

1. Users don't understand how to add translations.
  * They don't know that they need to click on the icon.
  * They don't add languages in their profile, and they don't read the message that in order to translate, they need to add languages in their profile.
  * They link their translation to the wrong sentence.
2. Users just don't know what to do after they register. They are guided to add languages to their profile, but after that, they have no more purpose.

Are those points the two most important problems? Are there more important problems?

If those are the main problems, then I personally have other ideas in mind that don't involve redirecting to the Quick Start Guide.

**Comment by ckjpn** [comment]
3. Users don't know the basic guidelines and rules.

**Comment by trang** [comment]
I'm planning to close this issue because it would be implementing a solution without understanding the actual problem.

@ckjpn 

> Users don't know the basic guidelines and rules.

This is not specific enough. We would need to know what exactly users are doing that goes against our guidelines and rules. Then we have to fix each problem case by case.

**Comment by ckjpn** [comment]
> Users don't know the basic guidelines and rules.
> This is not specific enough. We would need to know what exactly users are doing that goes against our guidelines and rules. 

Perhaps this needs to be opened as a different issue.

What exactly users are doing that goes against our guidelines and rules are as follows.

New members sometimes ...
1. contribute sentences (or sentence pairs) for copyrighted sources
2. include annotations in their sentences
3. contribute unnatural-sounding, word-for-word translations

New members often don't know how to find good sentences to translate.

New members often think we are a site like Lang-8.com where you should add things in a foreign language and a native speaker will correct it for you.


It would likely be very beneficial to new members and would help solve the above problems if we had a page with a message similar to the following.


# Welcome to the Tatoeba Project. 

There is a link to our quick start guide at the bottom of every page.

http://en.wiki.tatoeba.org/articles/show/quick-start

We also have a page with rules and guidelines.

http://en.wiki.tatoeba.org/articles/show/guidelines


## The 2 Ways You Can Be the Most Helpful

 ▪ You can translate from a foreign language you know into your own native language.

 ▪ You can create natural-sounding sentences in your own native language for others to translate into their native languages.


## Perhaps you will find the following useful.

 ▪ English sentences with audio that are not yet translated into Spanish - A Random Selection
 https://tatoeba.org/eng/sentences/search?trans_filter=exclude&sort=random&has_audio=yes&from=eng&to=spa

 ▪ English sentences with audio that are not yet translated into Spanish - Shortest First
 https://tatoeba.org/eng/sentences/search?trans_filter=exclude&sort=words&has_audio=yes&from=eng&to=spa

 ▪ You can find these and other links on this page that you may want to bookmark for future use.
http://study.aitech.ac.jp/tatoeba/translate/links.php?f=eng&t=spa

**Comment by trang** [comment]
> Perhaps this needs to be opened as a different issue.

Each of the points you mentioned is an issue on its own.

> It would likely be very beneficial to new members and would help solve the above problems if we had a page with a message similar to the following.

In my opinion it's not the best approach. Such a page would give instructions to new members before we even know what they intend to do. Maybe they only want to create lists. Maybe they only want to send a private message. Maybe they only want to report a mistake.

There's a right time and a right place to deliver instructions for contributors. The moment right after registration is usually not the right time. I wouldn't count on users to read anything longer 3 lines after they register. I wouldn't count on users to click on links to external documentation right after they register.

**Comment by alanfgh** [comment]
Furthermore, I think that lecturing people early and often about how to contribute comes with a cost. It makes the site feel less welcoming. Nor am I convinced that it even accomplishes what it's meant to do. Many of the people who contribute in languages that they don't know well, or translate sentences by non-native speakers, or contribute copyrighted material, will continue to do so no matter how many times they're told not to, until they're blocked. In the meantime, it makes the Tatoeba experience less pleasant for everyone else. I speak from experience.

**Comment by billoliver** [comment]
In my opinion we should tell these to **new visitors** on the homepage:

- What's Tatoeba.
- How Tatoeba works.
- How they can help the community.
- Call to action at the bottom of the page (if they read everything, they're more likely to register, and if they aren't interested there's a register link at the top of the homepage).

Important: These things have to be explained in a friendly way. Nobody's going to read a long text because nobody likes to do this.

We should build a new homepage for **logged-in** users. I think I can explain this better with pictures or mockups.

**Comment by trang** [comment]
> In my opinion we should tell these things to new visitors on the homepage:

We already do tell these things on the homepage.

> What's Tatoeba.

That's explained in the tagline.

> How Tatoeba works.

I don't think we need to explain how everything works. For new visitors we only need to explain the search, and that's done by the placeholder, the tip, and the link to the wiki for more information about how to search.

> How they can help the community.

That's explained in "Want to help?".


The issues that CK mentions here are not issues for new visitors but for new *members*. I don't think the homepage is the place where we can solve these issues.

We can definitely improve the homepage for logged-in users, but that would solve other problems, not the problem of users contributing wrong sentences.

**Comment by billoliver** [comment]
I want to explain this better, but as I said in my previous comments I'm really busy right now. When I finish writing the text, I'm going to let you guys know. :+1:

**Comment by ckjpn** [comment]
> We should build a new homepage for logged-in users. I think I can explain this better with pictures or mockups, but I'm too busy right now.

There is an issue for this at https://github.com/Tatoeba/tatoeba2/issues/1045

**Comment by trang** [comment]
Closing this. 
There are several issues that were mentioned in the comments that deserve and should be solved in a separate issue. I'll create them when the time comes.
