### ISSUE TITLE
Sango (sag)

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#8]
* Language name: Sango 
* Language info: http://en.wikipedia.org/wiki/Sango_language
* ISO 639-3 code: sag
* Public List: **[No list](https://tatoeba.org/eng/sentences_lists/index/Sango) (Oct 9, 2015 09:25 a.m. BRT)**
* Icon: http://www.pays-monde.fr/continent-afrique-1/drapeau-national-republique-centrafricaine-41.html
* Requested by: http://tatoeba.org/user/profile/ambroise

TODO
`CALL add_new_language('sag', 0);`

**Comment by RyckRichards** [comment]
@alanfgh 
There is no list with this name - https://tatoeba.org/eng/sentences_lists/index/Sango%20%5BSAG%5D
