### ISSUE TITLE
really use cache system

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#80]
Some table are enough small to be cached, for example users and number of contributions etc. (so some model methods see first is the result is not available in cache, and otherwise make the query and then cached their result) , and after we should update both the cache database (This will be incredibly usefull for request which require "count" )The same can be done with some part of tatoeba html instead of going into some complex nested array

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/282

**Comment by trang** [comment]
Outdated, I think. Closing.
