### ISSUE TITLE
Northern Sami (sme)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#804]
* Language name: Northern Sami or Sami
* Language info: https://en.wikipedia.org/wiki/Northern_Sami
* ISO 639-3 code: sme
* Public List: https://tatoeba.org/ita/sentences_lists/show/3160 (Other sentences that were not included * in the list: https://tatoeba.org/ita/tags/show_sentences_with_tag/6337)
* Icon: https://goo.gl/zqLNM1
* Requested by: **cueyayotl** https://tatoeba.org/eng/contributions/of_user/cueyayotl

TODO
`CALL add_new_language('sme', 3160);`

**Comment by RyckRichards** [comment]
Is there any icon?

**Comment by Guybrush88** [comment]
I found this as a flag: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Sami_flag.svg/2020px-Sami_flag.svg.png
