### ISSUE TITLE
Allow users to "Filter by language" on the "reviews" page

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#806]
![img](https://cloud.githubusercontent.com/assets/7658430/10361457/a467d7f8-6d7e-11e5-80c2-91f1e4de0db6.png)

**Comment by trang** [comment]
Additional info: the "Collection" page can be accessed from the profile page of a user. In the sidebar, there is a link "Collection".

```
> Profile
> Sentences
> Vocabulary
> Collection <------------ this link
> Transcriptions
> Lists
> Favorites
> Comments
> Comments on {username}'s sentences
> Wall messages
> Logs
```

For instance, this is the page for my collection: https://tatoeba.org/eng/collections/of/TRANG

**Comment by AndiPersti** [comment]
After the renaming of `Collections` to `Reviews` the URL for the page where the language dropdown should be added is `https://tatoeba.org/eng/reviews/of/<username>`

**Comment by RyckRichards** [comment]
I'd like to try solving this one.
