### ISSUE TITLE
Change the order of the information in the TITLE tag of pages.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#809]
Instead of:
English example sentence: Is eating liver good for you? - Tatoeba
Have this:
Is eating liver good for you? - English example sentence - Tatoeba
Or this:
Is eating liver good for you? - English example sentence
Or this:
Is eating liver good for you? (English example sentence)
- This would put the important information at the begining.
- This would mean the in browsers like Chrome that crop page titles that you can easily see a unique name on each tab if you have multiple tabs open.
- This would make nice bookmark titles for people who bookmark a page.
- This would have sentences displays more beautifully in Google search results.
- The "Tatoeba" part at the end probably doesn't really help with Google searches, so you could remove a little clutter by taking it out of the title.

Currently Google Results look like this.

![screen shot 2015-10-11 at 10 03 15](https://cloud.githubusercontent.com/assets/7934273/10414184/ec89cc4c-7000-11e5-8aee-2a0a1e968b9e.png)

*\* Related Idea **

Perhaps it might also be a time to reconsider what's in the description META tag.  Perhaps it could be made more useful.  For example, if it doesn't slow things down too much, you could have a line like the following instead, based on what the direct translations are.

Translations in: Japanese, French, Russian

**Comment by ckjpn** [comment]
As I was posting a sentence in Facebook, I was reminded that a slight change, might make tatoeba.org's pages more social media friendly, too.

![screen shot 2016-05-07 at 23 39 24](https://cloud.githubusercontent.com/assets/7934273/15092748/d056ae26-14ad-11e6-968d-711f7994df9f.png)

https://tatoeba.org/eng/sentences/show/5100337

Perhaps how this should be done needs to be discussed, but here are my suggestions.

FROM:
<title> English example sentence: Dogs have masters, cats have servants. - Tatoeba  </title>
TO:
<title> Dogs have masters, cats have servants. - English example sentence - Tatoeba   </title>

FROM:
<meta name="description" content="Browse translated example sentences. This page shows translations and information about the sentence: Dogs have masters, cats have servants." />
TO:
<meta name="description" content="Visit the Tatoeba Project to find example sentences and their translations. You can add a translations into your own language, too." />

**Comment by ckjpn** [comment]
I would like to re-request this be done.

Here's one additional reason.

If you drag a bookmarks into the "bookmarks bar" all links look the same, since nothing unique is showing.

Maybe others never do this, but I often do this when I want to temporarily bookmark something I want to come back to in the near future.

![screen shot 2016-07-14 at 12 45 56](https://cloud.githubusercontent.com/assets/7934273/16827417/7442b0aa-49c1-11e6-855b-de4632fb8fab.png)

Even if others don't do this, I can't see any disadvantage to anyone if the TITLE tag is done this way.

**Comment by ckjpn** [comment]
This should be a relatively simple thing to do.
Is there any reason it's not a good idea?

It's interesting that sometimes Google doesn't include the "English example sentence: " or the " - Tatoeba" in the link.

![screen shot 2016-10-03 at 09 39 48](https://cloud.githubusercontent.com/assets/7934273/19025084/dafbca86-894d-11e6-97f6-d1f77b913aae.png)

**Comment by ckjpn** [comment]
I wonder whether this is a difficult change to make, or whether you think it wouldn't be useful.

I'll include 2 images to show why I don't like the way it's being done now, so perhaps you might consider prioritizing this.

<img width="937" alt="screen shot 2019-03-02 at 13 34 59" src="https://user-images.githubusercontent.com/7934273/53677279-bb145400-3cf0-11e9-85b0-784ddd15211a.png">

<img width="611" alt="screen shot 2019-03-02 at 13 29 47" src="https://user-images.githubusercontent.com/7934273/53677283-c1a2cb80-3cf0-11e9-8e30-b55cc7c1a4d5.png">

**Comment by jiru** [comment]
I think it’s a reasonable change. And it’s not difficult to implement.

**Comment by trang** [comment]
@ckjpn You mentioned in #1122 that you'd be more interested to help with the code if we don't use an obsolete version of CakePHP. If you haven't changed your mind, now that we migrated to CakePHP 3, perhaps making a pull request for this issue would be a good place for you to start.

**Comment by ckjpn** [comment]
I don't have time to set things up right now, but perhaps this is the relevant code.

LINE 40 of Sentences/show.ctp


    $title = format(__('{language} example sentence: {sentence}'),
                    array('language' => $languageName, 'sentence' => $sentenceText));
    $this->set('title_for_layout', $this->Pages->formatTitle($title));

**Comment by jiru** [comment]
@ckjpn Yes, this is the relevant code. Maybe you don’t need to set anything up for such a trivial change. Just fork the repository, edit the file directly from Github (top-right pen icon) and make a pull request. We’ll take care of the rest.

**Comment by jiru** [comment]
@ckjpn I can see you already forked the repository a long time ago. Try [this guide](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser) to update it first, or maybe just delete and recreate it.

**Comment by ckjpn** [comment]
Perhaps it's something as easy as this.

$title = format(__('{sentence} - {language} example sentence'),
                array('language' => $languageName, 'sentence' => $sentenceText));
$this->set('title_for_layout', $this->Pages->formatTitle($title));

**Comment by trang** [comment]
@ckjpn The code you posted looks fine. If you can make a pull request out of this, then it's even better.

Pull requests are a very powerful tool for contributing code. There is of course a learning curve, and it may feel intimidating to make pull requests at first, but don't be afraid to try it.

This issue here has a very low urgency. It doesn't need to be solved today, nor tomorrow, nor even this month. That's why I suggested this as a starting point, so you can take the time you need to learn how to make pull requests. That knowledge will be useful for many other occasions in the future. 

This is of course assuming you want to keep helping with the code. If you don't (which is completely fine), then learning how to make pull requests is useless.

**Comment by ckjpn** [comment]
I plan to get into CakePHP to potentially use it for another project.  I didn't really want to take the time to read all the documentation and start experimenting with it until Tatoeba was using the current version.  However, I don't really have time to do this at this time.

If it's too hard for one of you to make this change at this time, it can wait.

**Comment by trang** [comment]
Pull requests are a feature of GitHub that allows to suggest modifications of code. They are not a CakePHP feature.

If you don't have time right now it's okay, as said, this is not urgent. The change in itself is not difficult. The reason why it has not been solved all this time was not because it was hard, but because it was never a priority.

It's not bad anyway to wait a bit more before introducing this change. There are maybe some impacts we haven't thought of. At least one thing that came up to my mind is that it could change our visibility in Google, especially if we don't make sure to fix the translated strings. But I don't think that should matter over having more practical tab titles.

**Comment by ckjpn** [comment]
I understand that it's not a CakePHP feature.  What I meant is that I hate to make a suggested code change without testing it first and that I can't easily test it at this time.  I don't think I could quickly set up tatoeba code to work locally.

**Comment by trang** [comment]
@ckjpn FYI gillux made notable improvements in Imouto. Setting up Tatoeba locally should be a lot easier now. You may want to give it a try. Cf. https://tatoeba.org/eng/wall/show_message/32237#message_32237
