### ISSUE TITLE
An avatar for Horus

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#811]
By Hybrid (https://tatoeba.org/eng/wall/show_message/24483#message_24483)

> It could be something simple like an eye: http://en.wikipedia.org/wiki/Fi...f_Horus_bw.svg

> a falcon:
http://en.wikipedia.org/wiki/Fi..._as_falcon.svg

> a statue:
http://en.wikipedia.org/wiki/File:Horus_R01.jpg

> a hieroglyph (the one in the middle):
http://upload.wikimedia.org/wik...ion_Detail.jpg

> this:
http://upload.wikimedia.org/wik...anding.svg.png

> small statue:
http://upload.wikimedia.org/wik...84_-_Right.jpg

**Comment by RyckRichards** [comment]
Requested by Hybrid on [Tatoeba Day #9](https://tatoeba.org/eng/wall/show_message/24483#message_24483).

**Comment by RyckRichards** [comment]
Personal comment:

Maybe we could use the same logo that Tatoeba does - http://i.imgur.com/00y3x2R.png.

**Comment by ckjpn** [comment]
I think this could be done quite easily.
It would only take you less than a minute to do so.
Why not just go ahead and put this avatar there?

![horus](https://cloud.githubusercontent.com/assets/7934273/12076760/2561d3d2-b1fd-11e5-82b2-01b613147c97.png)

It could always be replaced if someone comes up with a better one.

The reason I suggest this avatar is that it shows what Horus does using 2 icons that tatoeba.org uses.

**Comment by RyckRichards** [comment]
It would be good if be implemented since so many members have their sentences deleted by "a user" called Horus...

**Comment by ckjpn** [comment]
Even though perhaps many people don't see "Horus" very often, this does show up various places.

For example, here.  
https://tatoeba.org/eng/contributions/latest
If this the avatar for Horus were the one I suggested above, even new members could immediately get an idea that Horus was a bot script that deletes duplicates and links translations to the original.

As easy as it would be to add this, I think you should go ahead and do it.
Up to now more man-hours have been extended discussing this than it would take to add an avatar.

![screen shot 2016-02-11 at 09 15 03](https://cloud.githubusercontent.com/assets/7934273/12966319/7a698e12-d0a0-11e5-96d7-b1c792a55208.png)

**Comment by jiru** [comment]
I assigned Horus one the icons suggested by Hybrid.

**Comment by jiru** [comment]
For the record, here is how I updated the avatar:
1. Prepare the image
2. Produce two rescaled versions, 36x36 and 128x128
3. Upload the rescaled versions via ssh to `app/webroot/img/profiles_{36,128}/horus.jpg`
4. Run SQL `update users set image = 'horus.jpg' where username = 'Horus';`

**Comment by ckjpn** [comment]
It may not matter, but I think the other profile images are all .png and not .jpg
I could be wrong.

**Comment by jiru** [comment]
On Sat, 13 Feb 2016 22:47:40 -0800
ckjpn <notifications@github.com> wrote:

> It may not matter, but I think the other profile images are all .png
> and not .jpg I could be wrong.

It doesn’t matter.
