### ISSUE TITLE
Kamba (kam)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#815]
* Language name: Kamba
* Language info: https://en.wikipedia.org/wiki/Kamba_language
* ISO 639-3 code: kam
* Public List: https://tatoeba.org/ita/sentences_lists/show/4729
* Icon: https://drive.google.com/open?id=0B6VpA-j8A4f9WTYxSGlCM3NDaFk0aktsQi1GZm4xNWsxc2Mw
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by sabretou** [comment]
Kamba is not an official language in Kenya, where many other languages are spoken, so I suggest we have a KAM defacement on the flag.

**Comment by RyckRichards** [comment]
Could you send us a flag?

**Comment by RyckRichards** [comment]
Cueyayotl sent this one - https://drive.google.com/open?id=0B6VpA-j8A4f9WTYxSGlCM3NDaFk0aktsQi1GZm4xNWsxc2Mw

**Comment by trang** [comment]
@RyckRichards, it seems that you've linked the same image for several languages (#834 and #821).

**Comment by RyckRichards** [comment]
@trang Thank you! I've updated #821. Actually, the link for that language is https://drive.google.com/drive/folders/0B6VpA-j8A4f9UmxrcDl1bjVEenc. Thank you so much!!!
