### ISSUE TITLE
Gilbertese (gil)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#817]
* Language name: Gilbertese
* Language info: https://en.wikipedia.org/wiki/Gilbertese_language
* ISO 639-3 code: gil
* Public List: https://tatoeba.org/eng/sentences_lists/show/3937
* Icon: https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by trang** [comment]
@Guybrush88, @RyckRichards, the list that was initially mentioned was linking to a list of Kiribati sentences (https://tatoeba.org/eng/sentences_lists/show/4184). I've edited the ticket to link to the right list.

The list for Gilbertese is empty however. Could you please check if there are any Gilbertise sentences among the "unknown" sentences and set them to Gilbertese.

On a side note, please avoid creating tickets for languages that do not have any sentence in Tatoeba.
