### ISSUE TITLE
Venetian (vec)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#820]
Language name: Venetian
Language info: https://en.wikipedia.org/wiki/Venetian_language
ISO 639-3 code: vec
Public List: https://tatoeba.org/ita/sentences_lists/show/3925
Icon: http://prntscr.com/8qz5pf
Requested by: Turkaranto on behalf of masaragiovanni (https://tatoeba.org/ita/user/profile/masaragiovanni), who is a native speaker of it

**Comment by sabretou** [comment]
That icon is only a part of the complete Flag of Veneto, which represents Venice: https://en.wikipedia.org/wiki/File:Flag_of_Veneto.svg

**Comment by RyckRichards** [comment]
Thanks, @sabretou !
