### ISSUE TITLE
Dungan (dng)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#821]
* Language name: Dungan
* Language info: https://en.wikipedia.org/wiki/Dungan_language
* ISO 639-3 code: dng
* Public List: https://tatoeba.org/ita/sentences_lists/show/3397
* Icon: https://drive.google.com/drive/folders/0B6VpA-j8A4f9UmxrcDl1bjVEenc
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by sabretou** [comment]
Note that we'll need to add a 'DNG' defacement on the Kyrgyzstan flag as we are already using it for the Kyrgyz language.

**Comment by RyckRichards** [comment]
Could you do it, please? I have no idea (yet) how can I do it. Thank you!

**Comment by sabretou** [comment]
Surely it can be done by whoever did the defacements for Xhosa (https://tatoeba.org/img/flags/xho.png?1395590761), Coastal Kadazan (https://tatoeba.org/img/flags/kzj.png?1444763673), Javanese (https://tatoeba.org/img/flags/jav.png?1426969948), Afrikaans (https://tatoeba.org/img/flags/afr.png?1395590761) etc.?

**Comment by RyckRichards** [comment]
yes!
Or suggest another flag - maybe one wrriten "Dungan"

**Comment by RyckRichards** [comment]
cueyayotl sent this one - https://drive.google.com/open?id=0B6VpA-j8A4f9WTYxSGlCM3NDaFk0aktsQi1GZm4xNWsxc2Mw
