### ISSUE TITLE
Mohawk (moh)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#826]
* Language name: Mohawk
* Language info: https://en.wikipedia.org/wiki/Mohawk_language
* ISO 639-3 code: moh
* Public List: https://tatoeba.org/ita/sentences_lists/show/3590
* Icon: http://prntscr.com/8s6evl
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by sabretou** [comment]
While I'm not calling for this flag to be taken down, I do advise caution in using it. It appears to be the flag of one 'Mohawk Warrior Society', a group known for roadblocks, evictions and occupations. https://en.wikipedia.org/wiki/Mohawk_Warrior_Society

I'm not certain if Mohawk speakers unaffiliated with this group would like to have this flag represent them. That said, we can perhaps use this as a temporary flag.

**Comment by trang** [comment]
@RyckRichards, if you have time can you do some research about this flag, and figure out if we should keep using it or not?
