### ISSUE TITLE
Add "Namtrik" instead of "Guambiano"

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#828]
By cueyayotl - https://tatoeba.org/eng/wall/show_message/24444#message_24444

> When adding new languages, how commited are we to keeping the name given to the corresponding ISO 639-3 code by the SIL? (See: http://www-01.sil.org/iso639-3/codes.asp)

> For example, I have a friend who was considering joining Tatoeba, and he speaks what would be classified as [GUM] by this classification, however he totally objects to the use of the term 'Guambiano' (as is given by the SIL) stating that this is a useless label by this foreign linguistics organization that knows nothing of Columbian linguistics, or something like that. Had he joined, would it have been possible to add [GUM] as 'Namtrik' instead?

> It is the first time I have come across this scenario, but it may be something to think about when Tatoeba becomes big enough.

**Comment by sabretou** [comment]
I don't think it's Tatoeba's place to decide language names. We should stick to the SIL names, in my opinion.

**Comment by trang** [comment]
Agreed with @sabretou. Closing this.

Cf. my response to cueyayotl:

> Does he says this because "Guambiano" is another language for him? Or does he say this because he expects the language to named the same way as in his native language?
In other words, would it be the same as, for instance, German speakers complaining that German is called "German" instead of "Deutsch"?

> If he is against the name for valid reasons, he can address his concerns to the SIL and propose another name. If he convinces them to change the name, Tatoeba will use the new name, but otherwise we will stick the the name given by the SIL.

> Tatoeba won't create its own language classification and naming, unless we someday have the best experts in this field and we can do a better job than other organizations. But I don't see that happening anytime soon.

**Comment by lagleki** [comment]
I'd rather suggest that these people translate Tatoeba interface into their
languages and call those languages correctly in the translated strings
themselves.

Also adding sentences to the database mentioning correct names of languages
in those languages themselves can be another piece of advice.

2015-10-18 14:17 GMT+03:00 Trang <notifications@github.com>:
