### ISSUE TITLE
Pashto (pus)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#832]
* Language name: Pashto
* Language info: https://en.wikipedia.org/wiki/Pashto
* ISO 639-3 code: pus
* Public List: https://tatoeba.org/ita/sentences_lists/show/3531
* Icon: https://upload.wikimedia.org/wikipedia/commons/d/d9/Pashto.svg
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by sabretou** [comment]
I cooked up a more colourful flag for Pashto: http://i61.tinypic.com/282n7u1_th.png

**Comment by RyckRichards** [comment]
Thanks, @sabretou ! I'm going to add it!
