### ISSUE TITLE
Scots (sco)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#833]
Language name: Scots
Language info: https://en.wikipedia.org/wiki/Scots_language
ISO 639-3 code: sco
Public List: https://tatoeba.org/ita/sentences_lists/show/1234
Icon: https://drive.google.com/open?id=0B6VpA-j8A4f9VzUzMTlyRllUSDk2YUg1WFdEVTlCQVl1cWlv 
> based on https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg . "scots" was added in order to not have the same flag of Scottish Gaelic

Requested by: https://tatoeba.org/ita/user/profile/kruko

**Comment by RyckRichards** [comment]
How about this? http://prntscr.com/8rda5e

**Comment by RyckRichards** [comment]
Following Cueyayotl suggestion
Icon - https://drive.google.com/open?id=0B6VpA-j8A4f9VzUzMTlyRllUSDk2YUg1WFdEVTlCQVl1cWlv

![00001](https://cloud.githubusercontent.com/assets/7658430/10557056/bf148886-7471-11e5-8975-7fe3cd8145ed.PNG)

![0000000002](https://cloud.githubusercontent.com/assets/7658430/10557077/7a7f6c58-7472-11e5-9afc-6f52e77253c5.png)

**Comment by sabretou** [comment]
Going to second @RyckRichards that this flag could be confusing. The language being similar to English is not really any justification to use the Scottish Union flag, which is long outdated, and was used in an unofficial capacity. I think it also misrepresents Scots as being a 'historical' language of sorts.

I would side with the Scottish flag with "SCO" on it.

**Comment by RyckRichards** [comment]
Like this - @sabretou   http://prntscr.com/8s6dni ?

**Comment by sabretou** [comment]
Mmm, while that certainly is a flag with SCO on it, those letters would be completely illegible at 30x20. We're going to need a bigger defacement. Let me cook up a flag real quick.

**Comment by sabretou** [comment]
Done, how's this? https://drive.google.com/file/d/0B5_jtoG7OkkpcE50Z3QxZmd2Q00/view?usp=sharing

**Comment by trang** [comment]
@RyckRichards, I'm leaving this ticket open for now. Close if when you have replaced the current language icon with Sabretou's icon.

**Comment by RyckRichards** [comment]
Alright!

**Comment by RyckRichards** [comment]
Done as requested! Closing ticket.
