### ISSUE TITLE
Sumerian (sux)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#834]
* Language name: Sumerian
* Language info: https://en.wikipedia.org/wiki/Sumerian_language
* ISO 639-3 code: sux
* Public List: https://tatoeba.org/eng/sentences_lists/show/1265
* Icon: https://en.wikipedia.org/wiki/Sumerian_language#/media/File:Sumerian_26th_c_Adab.jpg
* Requested by: https://tatoeba.org/eng/user/profile/Vortarulo

**Comment by sabretou** [comment]
I've created what I think is a more distinctive flag: http://i59.tinypic.com/1sfdqq_th.png

The text used is the name of the language in Sumerian, as seen on Wikipedia: "Sumerian (𒅴𒂠 EME.G̃IR15 "native tongue") is the language of ancient Sumer..."

**Comment by RyckRichards** [comment]
cueyayotl made this one - https://drive.google.com/open?id=0B6VpA-j8A4f9WTYxSGlCM3NDaFk0aktsQi1GZm4xNWsxc2Mw . What do you thing about it?

**Comment by sabretou** [comment]
I like it! I wouldn't mind either one being the flag.
