### ISSUE TITLE
Old Saxon (osx)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#835]
* Language name: Old Saxon
* Language info: https://en.wikipedia.org/wiki/Old_Saxon
* ISO 639-3 code:osx
* Public List: https://tatoeba.org/eng/sentences_lists/show/4751
* Icon: https://en.wikipedia.org/wiki/File:Old_Saxony_banner.png
* Requested by: https://tatoeba.org/eng/user/profile/Ealdwimor

**Comment by sabretou** [comment]
Old Saxon was spoken in Old Saxony, so this flag may be appropriate: https://en.wikipedia.org/wiki/File:Old_Saxony_banner.png
