### ISSUE TITLE
Swiss German (gsw)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#836]
* Language name: Dungan
* Language info: https://en.wikipedia.org/wiki/Swiss_German
* ISO 639-3 code: gsw
* Public List: https://tatoeba.org/eng/sentences_lists/show/4752
* Icon: http://oi58.tinypic.com/1zr2mb5.jpg
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by sabretou** [comment]
Flag of Switzerland seems appropriate. I've made a version with the flag centred and transparency to the sides, as the Swiss flag has a 1:1 ratio: http://i58.tinypic.com/1zr2mb5_th.png

**Comment by RyckRichards** [comment]
Thanks a lot, @sabretou!
