### ISSUE TITLE
Seychellois Creole (crs)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#837]
* Language name: Seychellois Creole
* Language info: https://en.wikipedia.org/wiki/Seychellois_Creole
* ISO 639-3 code: crs
* Public List: https://tatoeba.org/eng/sentences_lists/show/4753
* Icon: https://en.wikipedia.org/wiki/File:Flag_of_Seychelles.svg
* Requested by: https://tatoeba.org/eng/user/profile/Manfredo

**Comment by sabretou** [comment]
Flag of Seychelles: https://en.wikipedia.org/wiki/File:Flag_of_Seychelles.svg
