### ISSUE TITLE
Kannada (kan)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#838]
* Language name: Kannada
* Language info: https://en.wikipedia.org/wiki/Dungan_language
* ISO 639-3 code: kan
* Public List: https://tatoeba.org/eng/sentences_lists/show/3405
* Icon: https://en.wikipedia.org/wiki/Kannada_flag
* Requested by: https://tatoeba.org/eng/user/profile/Manfredo

**Comment by sabretou** [comment]
Kannada has a fairly well-used cultural flag: https://en.wikipedia.org/wiki/Kannada_flag
