### ISSUE TITLE
Palatine German (pfl)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#839]
* Language name: Palatine German
* Language info: https://en.wikipedia.org/wiki/Palatine_German_language
* ISO 639-3 code: pfl
* Public List: https://tatoeba.org/eng/sentences_lists/show/4754
* Icon: http://oi62.tinypic.com/9k1kis.jpg
* Requested by: https://tatoeba.org/ita/user/profile/cueyayotl

**Comment by sabretou** [comment]
The Palatinate Lion seems the most appropriate symbol. Rather than a flag, I've centred the symbol and added transparency to the sides: http://i62.tinypic.com/9k1kis_th.png

**Comment by RyckRichards** [comment]
Awesome, @sabretou ! Thank you!
