### ISSUE TITLE
Marshallese (mah)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#840]
* Language name: Marshallese
* Language info: https://en.wikipedia.org/wiki/Marshallese_language
* ISO 639-3 code: mah
* Public List: https://tatoeba.org/eng/sentences_lists/show/4755
* Icon: https://en.wikipedia.org/wiki/File:Flag_of_the_Marshall_Islands.svg
* Requested by: https://tatoeba.org/eng/user/profile/Natan

**Comment by sabretou** [comment]
Flag of the Marshall Islands seems appropriate enough: https://en.wikipedia.org/wiki/File:Flag_of_the_Marshall_Islands.svg
