### ISSUE TITLE
Friulian (fur)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#841]
* Language name: Friulian
* Language info: https://en.wikipedia.org/wiki/Friulian_language
* ISO 639-3 code: fur
* Public List: https://tatoeba.org/eng/sentences_lists/show/4756
* Icon: https://commons.wikimedia.org/wiki/File:Flag_of_Friuli-Venezia_Giulia.jpg
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

**Comment by sabretou** [comment]
FOTW lists a flag on the top: http://www.crwflags.com/fotw/flags/it-fri.html
The same flag can be found on Christus Rex (http://www.christusrex.org/www1/pater/JPN-furlan.html), Wikimedia Commons (https://commons.wikimedia.org/wiki/File:Flag_of_Friuli-Venezia_Giulia.jpg) and this Italian site listing flags in Italy: http://www.cisv.it/rosso/bandiere6.html

I think this would be a suitable temporary flag until we can get a native speaker to provide a better one.

**Comment by RyckRichards** [comment]
Thanks a lot, @sabretou !
