### ISSUE TITLE
Instead of listing the top 5 languages in the upper-right corner of the "home" page, consider putting contributions stats for the previous 7 days.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#842]
This is just an idea that might make that upper right corner of the home page more interesting to our regularly-contributing members.

If you put in the stats for the past 7 days in the upper right corner, this would be something that might be interesting, since it would constantly be changing and would give members an idea about progress of the project and not just the progress of the few languages listed in the corner.

You could include the number of new sentences for the current day on each page reload.  However, you could also, just ignore that number and only post the past 5 to 7 days.  These numbers could be cached.

This is just an idea.  The way things are now is fine with me, too.

Maybe the title could be "Additions".  (Maybe no title is needed.)

You could put a link to https://tatoeba.org/eng/stats/sentences_by_language in the "More ..." menu.

If you did include today, you could just add a message "(in progress)" after the number.

![idea for upper-right-corner](https://cloud.githubusercontent.com/assets/7934273/10531050/4fd455c0-73e8-11e5-81e8-da0d462c93fa.png)

**Comment by sabretou** [comment]
Perhaps instead of raw contribution numbers, we could replace the Top 5 languages with "Top 5 languages today", listing languages with the most contributions that day, or perhaps that week.

**Comment by RyckRichards** [comment]
+1
I think it would motivate people to keep contributing

**Comment by ckjpn** [comment]
I'm not saying this is a good idea, but it's also another possibility to consider, kind of based off of sabretou's idea https://github.com/Tatoeba/tatoeba2/issues/842#issuecomment-154774396

You could have the Top 5 or 10 recent contributors listed, taken from the right column of this page.

https://tatoeba.org/eng/contributions/latest

![screen shot 2016-02-23 at 06 35 19](https://cloud.githubusercontent.com/assets/7934273/13233648/f84a748a-d9f7-11e5-93ca-06fca3a49242.png)

**Comment by trang** [comment]
Related Wall thread: https://tatoeba.org/eng/wall/show_message/33189#message_33189
