### ISSUE TITLE
Impossible to adopt a sentence from an iPhone

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#843]
By sacredceltic https://tatoeba.org/eng/wall/show_message/24499#message_24499

> il n'est désormais plus possible d'adopter une phrase depuis l'iPhone (en tout cas depuis mon iPhone 5). En effet, l'icône d'adoption y apparaît tronquée et ne s'y active pas. La zone d'affichage est trop réduite.

CK also said that he can't adopt sentences on his iPad as well.

**Comment by trang** [comment]
Duplicate of #753.

**Comment by trang** [comment]
Never mind, it's not a duplicate. I just saw that sacredceltic said it wasn't working with Chrome either. I thought it was only on Safari.

**Comment by RyckRichards** [comment]
cueyayotl could reproduce this bug today.

**Comment by RyckRichards** [comment]
He also told me that it's impossible to click on the "OK", "unsure" or "not OK" buttons.

**Comment by RyckRichards** [comment]
Related to #753 " Can't unadopt (release) a sentence in Safari #753 "

**Comment by RyckRichards** [comment]
According to [Silja](https://tatoeba.org/eng/user/profile/Silja), nothing happens when she clicks on the icon.

**Comment by RyckRichards** [comment]
Since members have reported that this bug is fixed, I'm closing it.
