### ISSUE TITLE
Language of members counter is not working properly

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#844]
By odexed https://tatoeba.org/eng/wall/show_message/24612#message_24612

https://tatoeba.org/eng/stats/users_languages

![goftm4x](https://cloud.githubusercontent.com/assets/7658430/10559285/aeaf2f1c-74c3-11e5-8db0-5c621fcd165b.png)

**Comment by trang** [comment]
I have updated the stats on the prod with:
https://github.com/Tatoeba/tatoeba2/blob/dev/docs/database/scripts/update_languages_stats.sql

The stats should be consistent now.

If someone can describe the exact steps to reproduce wrong stats in the languages of members, then I can maybe fix it. I don't want to spend too much time investigating on this though.

The problem can be handled with #966, even though it's not the perfect fix.

**Comment by trang** [comment]
@RyckRichards I will close this issue for now. Feel free to re-open it if you find out in which situations the stats become inconsistent.

**Comment by RyckRichards** [comment]
Alright, Trang! Thank you!

On 1/6/16, Trang <notifications@github.com> wrote:
> @RyckRichards I will close this issue for now. Feel free to re-open it if
> you find out in which situations the stats become inconsistent.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatoeba/tatoeba2/issues/844#issuecomment-169402044


-- 

Ricardo Vernaut Jr

Mobile // Celular: (5521) 967-640-668
Email: rvernautjr@gmail.com
<https://www.linkedin.com/in/vernautjr>
