### ISSUE TITLE
Laz (lzz)

### ISSUE THREAD

**Issue by boracasli2** [Tatoeba/tatoeba2#846]
Language name: Laz
Language info: https://en.wikipedia.org/wiki/Laz_language
ISO 639-3 code: lzz
Public List: http://tatoeba.org/eng/sentences_lists/show/3601
Icon: https://upload.wikimedia.org/wikipedia/commons/4/44/Flag_of_Lazistan_and_Mingrelia.svg
Requested by: https://tatoeba.org/eng/user/profile/biber

**Comment by RyckRichards** [comment]
This language has already been added. Closing this ticket.
