### ISSUE TITLE
Karachay-Balkar (krc)

### ISSUE THREAD

**Issue by boracasli2** [Tatoeba/tatoeba2#847]
Language name: Karachay-Balkar
Language info: https://en.wikipedia.org/wiki/Karachay-Balkar_language
ISO 639-3 code: krc
Public List: http://tatoeba.org/eng/sentences_lists/show/4103
Icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Flag_of_Kabardino-Balkaria.svg
Requested by: https://tatoeba.org/eng/user/profile/turklehceleri

**Comment by RyckRichards** [comment]
This language has been added to Tatoeba successfully! Closing this ticket.
