### ISSUE TITLE
Tuvinian (tyv)

### ISSUE THREAD

**Issue by boracasli2** [Tatoeba/tatoeba2#848]
Language name: Tuvinian
Language info: https://www.wikiwand.com/en/Tuvan_language
ISO 639-3 code: tyv
Public List: http://tatoeba.org/eng/sentences_lists/show/4104
Icon: https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Tuva.svg
Requested by: https://tatoeba.org/eng/user/profile/turklehceleri

**Comment by RyckRichards** [comment]
This language has been added to Tatoeba successfully! Closing this ticket.
