### ISSUE TITLE
Gagauz (gag)

### ISSUE THREAD

**Issue by boracasli2** [Tatoeba/tatoeba2#849]
Language name: Gagauz
Language info: https://en.wikipedia.org/wiki/Gagauz_language
ISO 639-3 code: gag
Public List: http://tatoeba.org/eng/sentences_lists/show/4105
Icon: https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_Gagauzia.svg
Requested by: https://tatoeba.org/eng/user/profile/turklehceleri

**Comment by RyckRichards** [comment]
This language has already been added. Closing this ticket.
