### ISSUE TITLE
Karakalpak (kaa)

### ISSUE THREAD

**Issue by boracasli2** [Tatoeba/tatoeba2#850]
Language name: Karakalpak
Language info: https://en.wikipedia.org/wiki/Karakalpak_language
ISO 639-3 code: kaa
Public List: http://tatoeba.org/eng/sentences_lists/show/4108
Icon: https://upload.wikimedia.org/wikipedia/commons/1/16/Flag_of_Karakalpakstan.svg
Requested by: https://tatoeba.org/eng/user/profile/turklehceleri

**Comment by RyckRichards** [comment]
@trang  all the sentences from the mentioned list are flagged. Should I proceed anyway?
![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/10653239/545c1936-783c-11e5-836d-56bb0fdda7a9.png)

**Comment by trang** [comment]
@RyckRichards, you should check this with cueyayotl, since he is the owner of the sentences.
