### ISSUE TITLE
Ilocano (ilo)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#853]
* Language name: Ilocano
* Language info: https://en.wikipedia.org/wiki/Ilocano_language
* ISO 639-3 code: ilo
* Public List: https://tatoeba.org/eng/sentences_lists/show/4797
* Icon: https://goo.gl/o6yxjz
* Requested by: https://tatoeba.org/eng/user/profile/saluyot

**Comment by sabretou** [comment]
We can use a flag of the Philippines defaced with ILO for this, similar to the flags for Xhosa, Afrikaans, etc.

**Comment by RyckRichards** [comment]
Awesome idea!
