### ISSUE TITLE
Aymara (aym)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#857]
* Language name: Aymara
* Language info: https://en.wikipedia.org/wiki/Aymara_language
* ISO 639-3 code: aym
* Public List: https://tatoeba.org/eng/sentences_lists/show/4786
* Icon: https://goo.gl/qIdGKu
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

**Comment by sabretou** [comment]
I've made a version of the flag with transparency to the sides: https://drive.google.com/file/d/0B5_jtoG7OkkpQXQ3MVRMdVU4OW8/view?usp=sharing
