### ISSUE TITLE
Rename "collections" to "ratings" or "lists of rated sentences", since that's what they really are.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#859]
In settings, we have this option:

Activate the feature to rate sentences and build your collection of sentences.

If you accurately referred to this, I think people would more likely use this feature.

I personally wouldn't want a "collection" of bad sentences or sentences I'm unsure of, but I wouldn't mind a "list" of sentences that I had rated bad.

**Comment by PaulPeer** [comment]
+1

**Comment by ckjpn** [comment]
I think this should be set to a high priority, especially if you want people to start using this function.

I would still really like to see at least one more option to indicate sentences that I've read, but don't want to rate -- perhaps call it "unrated" or "ignored".  Maybe someone else can come up with a better one-word name for this.

**Comment by billoliver** [comment]
+1

What do you guys think about "My Reviews"?

**Comment by ckjpn** [comment]
Ratings would be better than reviews.
The word review is often used to mean more than just a rating.

**Comment by ckjpn** [comment]
Related Wall Post = https://tatoeba.org/eng/wall/show_message/26501#message_26501

You can see that even someone who has been using the rating system for a while can't remember that you call them "collections."

**Comment by ckjpn** [comment]
I still think that "ratings" would be a better name for this.

Related Wall Post
https://tatoeba.org/eng/wall/show_message/34053#message_34053
