### ISSUE TITLE
Update the Translate Sentences Page to Use the "Advanced Search"

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#864]
Update the Translate Sentences Page to Use the "Advanced Search"
https://tatoeba.org/eng/activities/translate_sentences

Now that the "advanced search" easily allows searching for sentences in one language that are not yet translated into another, it might be good to utilize it instead of how the current page is set up.

This would help new visitors more easily find good sentences to translate, and would encourage more contributions, perhaps.

One problem with the "Search for untranslated sentences" one on the page is that it shows the newest contributions first, which often still have errors.

With the advanced search you can easily produce the following type of URLs which are more useful.
(Many regular visitors probably know how to do this, but perhaps some don't and new visitors may not soon figure it out.)

random selection of jpn with audio not yet translated into eng
https://tatoeba.org/sentences/search?query=&from=jpn&to=eng&has_audio=yes&trans_filter=exclude&trans_to=eng&sort=random

random selection of jpn not yet translated into eng
https://tatoeba.org/sentences/search?query=&from=jpn&to=eng&trans_filter=exclude&trans_to=eng&sort=random

search for all jpn with audio not yet translated into eng, showing the shortest sentences first.
https://tatoeba.org/sentences/search?query=&from=jpn&to=eng&has_audio=yes&trans_filter=exclude&trans_to=eng&sort=words

search for all jpn not yet translated into eng, showing the shortest sentences first.
https://tatoeba.org/sentences/search?query=&from=jpn&to=eng&trans_filter=exclude&trans_to=eng&sort=words

See http://a4esl.com/temporary/tatoeba/translate/links.php?f=jpn&t=fra for more ideas.

**Comment by RyckRichards** [comment]
+1
That would be awesome. It'd be great if we use http://a4esl.com/temporary/tatoeba/translate/links.php on Advanced Search also

**Comment by ckjpn** [comment]
I think this should be relatively easy to implement.


►►Rough example at http://www.manythings.org/tatoeba/translate.html

(https://cloud.githubusercontent.com/assets/7934273/13628621/e89f09ee-e616-11e5-9237-eb701b4bcd42.png)

Another option for the "limit to audio" would be to say something like.

limit to sentences with audio (only available in [some languages])
The [some languages] could have a link to https://tatoeba.org/eng/sentences/with_audio

► Why this way would be better

* The current "Search for untranslated sentences" on https://tatoeba.org/eng/activities/translate_sentences shows the newest sentences first.  One problem with this is that some people translate incoming incorrect sentences before other members have read them and helped correct them when necessary.

* The current "Display random sentences" often gives sentences that are already translated.  Using the method I've suggested will eliminate this problem.  The method I am suggesting here also helps members who want up to 100 random sentences at a time, to change their "settings" to get their desired number of random sentences to translate.



►► Perhaps you could insert both of these methods into the top of the "home" page for logged-in members.

![screen shot 2016-03-09 at 16 36 28](https://cloud.githubusercontent.com/assets/7934273/13628583/9b571dac-e616-11e5-80a8-4e3352444f6f.png)

Here's a working examples of that inserted into pages somewhat similar to the "home" page.
The first one should load faster, I think.

http://www.manythings.org/tatoeba/translating.html
http://www.manythings.org/tatoeba/personal.php

► Why this way would be better

* I would assume that most regular members land on the home page, scan the incoming sentences and comments, and then want to find sentences to translate.  This would make it so everything they need is on the main page.

**Comment by sacredceltic** [comment]
I agree that showing the newest sentences first is a problem, because they're often the worst, not having been corrected yet.

**Comment by jiru** [comment]
I’m in favour of this as well. However, the current show_all_in page is easier to use and understand than the advanced search page, because:

1. The title says what’s currently displayed, while the advanced search page always says “Advanced search”.
2. The useful search criteria like “language” and “not translated into” are hidden inside the complex form, while they are way easier to catch in the show_all_in page.
3. The advanced search page requires to click on the submit button whenever a criterion is modified, while the show_all_in page does not.

This may as well be considered as a different problem, that the advanced search page is not easy to use in general.

That said, if the only problem of the the show_all_in page is the order of the results (newest first), we may as well add a sort option that defaults to random. We can’t sort by number of words without using the advanced search though.

**Comment by billoliver** [comment]
I'm going to create a section where contributors can translate sentences right away on the homepage for logged-in users. I'm still building it, but I think it will solve this issue.

**Comment by ckjpn** [comment]
>  a section where contributors can translate sentences right away on the homepage for logged-in users

This sounds like it may be somewhat similar to what I suggested at the top of this issue.

https://github.com/Tatoeba/tatoeba2/issues/1045

**Comment by billoliver** [comment]
> This sounds like it may be somewhat similar to what I suggested at the top of this issue.

Yes, it does. That's because I had this idea a day before you created #1045. :+1:

**Comment by trang** [comment]
We're already using the advanced search in the translate page. I created a separate issue for the default sorting being set to "Last modified first".
