### ISSUE TITLE
Laz (lzz)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#868]
* Language name: Laz
* Language info: https://en.wikipedia.org/wiki/Laz_language
* ISO 639-3 code: lzz
* Public List: https://tatoeba.org/eng/sentences_lists/show/4833
* Icon: https://en.wikipedia.org/wiki/Lazistan_Sanjak#/media/File:Flag_of_Lazistan.svg 
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

**Comment by sabretou** [comment]
Duplicate Request of #846.

Finding an accurate source for the flag of Lazistan is hard, as both the flags listed here and on #846 originate from DeviantArt pages. Whichever flag we pick will probably have to be temporary until we can get confirmation from a native speaker.
