### ISSUE TITLE
Pulaar (fuc)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#869]
* Language name: Pulaar
* Language info: https://en.wikipedia.org/wiki/Pulaar_language
* ISO 639-3 code: fuc
* Public List: https://tatoeba.org/eng/sentences_lists/show/4834
* Icon: https://drive.google.com/open?id=0B6VpA-j8A4f9VUZxNGRNTWxLU0oyakJyeFpnWmVFWGp0U044
* Requested by: https://tatoeba.org/eng/user/profile/marina_sow

**Comment by sabretou** [comment]
That flag is almost illegible. I say we use a defaced Mauritanian flag, seeing as Pulaar is one of the National Languages of Mauritania.

**Comment by RyckRichards** [comment]
Could you send one to me - rvernautjr@gmail.com ?
