### ISSUE TITLE
Old Aramaic (oar)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#870]
* Language name: Ancient Aramaic 
* Language info: https://en.wikipedia.org/wiki/Aramaic_language#Ancient_Aramaic
* ISO 639-3 code: oar
* Public List: https://tatoeba.org/eng/sentences_lists/show/4890
* Icon: https://drive.google.com/open?id=0B6VpA-j8A4f9M1ZNamhqMEE2LUpTRk1pazRLR2dnRG85ZWIw
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

==============================

[for dev.tatoeba.org]
CALL add_new_language('oar', 4195);

[for tatoeba.org]
CALL add_new_language('oar', 4890);

http://dev.tatoeba.org/eng/sentences_lists/show/4195

**Comment by sabretou** [comment]
The ISO code 'sam' stands for Samaritan Aramaic. Wikipedia article here: https://en.wikipedia.org/wiki/Samaritan_Aramaic_language

Ancient Aramaic is officially Old Aramaic, and has an ISO code 'oar'.

So, which language is this exactly?

Furthermore, the public list has no sentences in it...

**Comment by RyckRichards** [comment]
I asked some people to add sentences on it and I'm studying to writ sentences too.

**Comment by sabretou** [comment]
Ah, awesome. :) I'll research for a suitable flag.

**Comment by sabretou** [comment]
About the best I can suggest is we use the Aramean flag: https://en.wikipedia.org/wiki/File:ArameanFlag.png and deface it with 'OAR'. If we add modern Aramic to Tatoeba, we can use the flag without defacement.

**Comment by RyckRichards** [comment]
@sabretou  could you deface this flag? - https://en.wikipedia.org/wiki/File:ArameanFlag.png

**Comment by sabretou** [comment]
Here's one version of it: ![arameanflag](https://cloud.githubusercontent.com/assets/7028559/10961409/5d82108c-83b4-11e5-8150-49d804904a1b.png)
