### ISSUE TITLE
Ho (hoc)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#873]
* Language name: HO
* Language info: https://en.wikipedia.org/wiki/Ho_language
* ISO 639-3 code: hoc
* Public List: https://tatoeba.org/eng/sentences_lists/show/4838
* Icon: https://goo.gl/NxRohu
* Requested by: https://tatoeba.org/eng/user/profile/ManguPurty

**Comment by sabretou** [comment]
Is there a larger version of this flag? I'm curious where it's from.

**Comment by sabretou** [comment]
Ah, it is the seal of Jharkhand. Never mind, then.

**Comment by RyckRichards** [comment]
It seems that the list indicated on this ticket has been deleted also. I asked cueyayotl to set the respective sentences into this language. Closing this ticket.
