### ISSUE TITLE
Assamese (asm)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#875]
* Language name: Assamese
* Language info: https://en.wikipedia.org/wiki/Assamese_language
* ISO 639-3 code: asm
* Public List: https://tatoeba.org/eng/sentences_lists/show/4840
* Icon: http://www.crwflags.com/fotw/images/i/in!as.gif
* Requested by: https://tatoeba.org/eng/user/profile/Balamax

**Comment by sabretou** [comment]
We might be able to use the unofficial flag of Assam temporarily, until an Assamese speaker can provide or suggest a better one. Here it is: http://www.crwflags.com/fotw/images/i/in!as.gif

**Comment by RyckRichards** [comment]
This language has been added to Tatoeba successfully! Closing this ticket.
