### ISSUE TITLE
Odia (Oriya) (ori)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#876]
* Language name: Odia (Oriya)
* Language info: https://en.wikipedia.org/w/index.php?title=Oriya_%28language%29&redirect=no
* ISO 639-3 code: ori
* Public List: https://tatoeba.org/eng/sentences_lists/show/4841
* Icon: https://drive.google.com/open?id=0B6VpA-j8A4f9aDg0RnkwZHVXM3JhMlZFSS0zakJEZ2xzQl9z
* Requested by: https://tatoeba.org/eng/user/profile/Balamax

**Comment by sabretou** [comment]
We might hit a language name hurdle here. Although official linguist lists still use the term 'Oriya', the language name was officially changed to Odia in India, which is a more accurate transliteration. I'll leave it to @trang to decide on what language name would be appropriate here. In my personal opinion, Odia is the most appropriate name, as the linguist lists are now outdated.

I've made a flag for Odia here: https://drive.google.com/file/d/0B5_jtoG7OkkpX1VEZElhb2h3aDg/view?usp=sharing

**Comment by trang** [comment]
I suppose we could go with "Odia (Oriya)".
