### ISSUE TITLE
Garhwali (gbm)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#877]
* Language name: 
* Language info: https://en.wikipedia.org/wiki/Garhwali_language
* ISO 639-3 code: gbm
* Public List: https://tatoeba.org/eng/sentences_lists/show/4860
* Icon: https://en.wikipedia.org/wiki/File:Tehga.svg
* Requested by: https://tatoeba.org/eng/user/profile/sabretou

**Comment by sabretou** [comment]
The ISO 639-3 code for Garhwali is 'gbm', not 'gbl'.

**Comment by RyckRichards** [comment]
Oh, thank you so much, @sabretou !

**Comment by trang** [comment]
@RyckRichards, the image that you've commited for Garhwali doesn't have the correct size.

**Comment by RyckRichards** [comment]
This language has been added to Tatoeba successfully! 
@trang  I'm really sorry. I will commit another one.
