### ISSUE TITLE
Old Norse (non)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#883]
•Language name: Old Norse
•Language info: https://en.wikipedia.org/wiki/Old_Norse
•ISO 639-3 code: non
•Public List: https://tatoeba.org/eng/sentences_lists/show/4850
•Icon: https://drive.google.com/file/d/0B5_jtoG7OkkpTjFrbUdMZHpjNnM/view?usp=sharing
•Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

**Comment by sabretou** [comment]
I've created a version of the flag with transparency: https://drive.google.com/file/d/0B5_jtoG7OkkpTjFrbUdMZHpjNnM/view?usp=sharing

**Comment by RyckRichards** [comment]
Thanks, @sabretou !

**Comment by RyckRichards** [comment]
@trang  There is already a flag on Tatoeba labeled "non". Should I add a file named "non2.png"?

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/10839780/ebd0c860-7ebe-11e5-9e3d-b99241dfc269.png)

**Comment by sabretou** [comment]
Norwegian (Nynorsk) is presently on Tatoeba with the ISO code 'non'. Its actual code is 'nno': http://www-01.sil.org/iso639-3/documentation.asp?id=nno

Both the Nynorsk flag and language ISO code need to be changed to 'nno', as 'non' is for Old Norse.

**Comment by trang** [comment]
I've fixed the code for Norwegian Nynorsk.
