### ISSUE TITLE
Make search help link easier to find

### ISSUE THREAD

**Issue by jberkel** [Tatoeba/tatoeba2#892]
Not sure if this is already possible (could not find it in the advanced search), but often I want to do an "exact match" type of search and would like to disable the automatic stemming. Is this possible somehow? Search results become really cluttered with completely unrelated results (e.g. I search for an adjective and the search engine returns a list of verb forms).

**Comment by jiru** [comment]
Yes, prefix the words with an equal sign.
See also [that wiki page](http://en.wiki.tatoeba.org/articles/show/text-search).

**Comment by jberkel** [comment]
That works, thanks! 

Maybe it would be helpful to have a link to the wiki page you mentioned in the advanced search box?

**Comment by jiru** [comment]
It’s already linked on the top search bar. The name of the link is “Help”. Maybe we could give it a better name or position?

**Comment by jberkel** [comment]
Ah, didn't see it, i was looking for it on the right-hand side, in the group of boxes titled: "More search criteria". I was looking through the whole list of options to see if there is an "inexact match" option.

 I think it would make sense to put it there (probably last, close to the "Advanced Search" button).

 And maybe name it "More search options" instead of "Help".

**Comment by trang** [comment]
@jberkel, I've added the link as you've suggested.

**Comment by jberkel** [comment]
excellent, thanks!
