### ISSUE TITLE
Prevent new users from translating sentences in languages not listed in their profile

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#897]
https://tatoeba.org/eng/wall/show_message/24754#message_24754

> Why not forbid the new users to translate from the language they didn't mention in their settings? Maybe it would help them to understand how the system works. It could be even a temporal restriction. For example, first two weeks they are meeting with the site and we just prevent them from making mistakes.

**Comment by RyckRichards** [comment]
Requested by odexed on [Tatoeba Day #10](https://tatoeba.org/eng/wall/show_message/24754#message_24754).

**Comment by PaulPeer** [comment]
+1 Hopefully this will finally persuade many users to add their languages.

**Comment by alanfgh** [comment]
I assume we're going to show the user a message explaining why the sentence has not been added. If we don't, it will just result in confusion.

**Comment by ckjpn** [comment]
Perhaps there could be a warning message put on the page or as a pop-up as soon as the translate button was clicked if the sentence isn't in a language in the new member's profile.

"You are attempting to translate from a language that isn't listed in your profile.  Perhaps you meant to translate from one of the other languages."

Maybe that's the best wording for the message, but something like that might work.

**Comment by RyckRichards** [comment]
Related to #793

**Comment by RyckRichards** [comment]
Kinda related to #795 -  Redirect new users to Quick Start Guide instead of the Home page #795

**Comment by ckjpn** [comment]
Perhaps if this is implemented, it shouldn't only be limited to new members.

Maybe it's not a good idea to allow any member to translate from or to a language he doesn't feel comfortable listing as a language he knows in his profile

If you don't need to put a check into the code to see if a member is new or not, then maybe this would be easier to program.

**Comment by RyckRichards** [comment]
According to odexed, there should be some notification about the reason why sentence was not successfully sent  since there are many people who don't like pop-up messages and may have AdBlock extension. That said, it should be a message on the page. He thinks that this feature should be implemented for new users. - maybe two weeks since the registration is enough to meet the system. The purpose is not to forbid people translate from many languages but to prevent new users from making mistakes while they don't know the difference between direct and indirect translation and don't see from what language they make translation.

**Comment by trang** [comment]
We can do something similar to sentences that are non-editable because they have audio.

![non-editable](https://cloud.githubusercontent.com/assets/221850/15869212/b3bc6c8c-2ceb-11e6-8fb7-f654c44c3d6b.png)

In our case, we would disable the translate button (that's the 1st button), and on hover display the following tooltip:
`You cannot translate this sentence because {language} is not a language in your profile. If you do not speak {language}, please select one of the translations and translate from there.`

I'm not sure if this text is clear enough though. If someone has a better phrasing, feel free to suggest.

**Comment by trang** [comment]
This was duplicated by #2132. Closing this one.
