### ISSUE TITLE
Rothongua (zhr)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#900]
* Language name: Rothongua
* Language info: http://rothongua.webnode.com/
* ISO 639-3 code: zhr
* Public List: https://tatoeba.org/eng/sentences_lists/show/4875
* Icon: https://drive.google.com/file/d...ew?usp=sharing
* Requested by: https://tatoeba.org/eng/user/profile/Redwars22

> Rothongua (zh-ro or zhr) is an Yue dialect. Please help me to add this language to Tatoeba and help people that want to learn this language.
https://tatoeba.org/por/sentences_lists/show/4875
Language flag:https://drive.google.com/file/d...ew?usp=sharing

**Comment by RyckRichards** [comment]
Closed since it is a conlang.

**Comment by trang** [comment]
@RyckRichards, just to avoid misunderstanding, the reason why we reject a language is not because it's a conlang but because it's not recognized in the ISO 639-3 classification.

There are conlangs in Tatoeba (Esperanto or Interlingua for instance).

**Comment by RyckRichards** [comment]
Oh, I see. Thanks a lot, @trang !
