### ISSUE TITLE
Members are not getting notifications on sentences.

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#902]
https://tatoeba.org/eng/wall/show_message/24776#message_24776

> I am not getting any notifications of others' comments I usually get. [raggione](https://tatoeba.org/eng/wall/show_message/24776#message_24776)

> I sometimes get them, but other times, I don't. [cueyayotl](https://tatoeba.org/eng/wall/show_message/24777#message_24777)

**Comment by trang** [comment]
Fixed in 84a70c306dc0b4a1740927d19e9ad16b03766185.

This was due to the fact that there was a change in the way Google validates email.
https://productforums.google.com/forum/#!topic/gmail/2tK2fR7yW-k
