### ISSUE TITLE
Tagal Murut (mvv)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#909]
* Language name: Tagal Murut
* Language info: https://en.wikipedia.org/wiki/Tagol_language / https://www.ethnologue.com/language/mvv
* ISO 639-3 code: mvv
* Public List: https://tatoeba.org/eng/sentences_lists/show/4864
* Icon: https://cloud.githubusercontent.com/assets/7028559/11083555/9e679f08-8856-11e5-87ef-747fb5db62af.png
* Requested by: https://tatoeba.org/eng/user/profile/LeeSooHa

**Comment by RyckRichards** [comment]
I have asked [LeeSooHa](https://tatoeba.org/eng/user/profile/LeeSooHa) to suggest me a suitable flag, but feel free to send me some if you can. I really appreciate that! Thanks!

**Comment by sabretou** [comment]
I think the Murut people are based in Sabah, which we are already using for Central Dusun and Coastal Kadazan. I think we can use a defaced flag similar to that of Coastal Kadazan, using the code MVV.

**Comment by RyckRichards** [comment]
Good idea! (as usual ☺ ) I'll try to make one!

**Comment by RyckRichards** [comment]
@sabretou  I wasn't able to make one (I'm still studying how to using Gimp properly). Would you mind to make one flag to this language? Thanks a lot!

**Comment by sabretou** [comment]
Here you go: 
![mvv](https://cloud.githubusercontent.com/assets/7028559/11083555/9e679f08-8856-11e5-87ef-747fb5db62af.png)

**Comment by RyckRichards** [comment]
Thanks a lot, @sabretou !
