### ISSUE TITLE
Iban (iba)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#910]
* Language name: Iban
* Language info: https://en.wikipedia.org/wiki/Iban_language
* ISO 639-3 code: iba
* Public List: https://tatoeba.org/eng/sentences_lists/show/4891
* Icon: https://en.wikipedia.org/wiki/File:Flag_of_Sarawak.svg
* Requested by: https://tatoeba.org/eng/user/profile/LeeSooHa

**Comment by sabretou** [comment]
Ibans are the largest ethnic group in Sarawak, where they are primarily concentrated, so I think the flag of Sarawak should be appropriate: https://en.wikipedia.org/wiki/File:Flag_of_Sarawak.svg

**Comment by RyckRichards** [comment]
Thanks a lot once more, @sabretou !
