### ISSUE TITLE
Members are now allowed to tag their own sentences with OK.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#911]
This used to not be possible, so I assume this is a bug that has crept in somewhere along the way.

I've noticed that Bilmanda has been tagging all his Indonesian sentences with OK.

https://tatoeba.org/eng/tags/show_sentences_with_tag/7/ind/page:34

If this was an unannounced intended change to the code, then this is not a bug.

**Comment by jiru** [comment]
I confirm it was not an intended change. I keep the issue open because once the fix is pushed on production, someone needs to remove the invalid OK tags by running the following SQL query on the production database:
```sql
delete ts from tags_sentences ts
left join sentences s on s.id = ts.sentence_id
where tag_id = (select id from tags where name = 'OK')
and s.user_id = ts.user_id;
```

**Comment by jiru** [comment]
I executed the SQL query. It removed 1961 OK tags. I had to change `(select id from tags where name = 'OK')` into its result `7` because mysql won’t run the query because of triggers.

**Comment by ckjpn** [comment]
You may need to run the same script from time to time if the Tatoeba Project wants to have an absolute policy about not having OK tags by the same person who owns the sentence.

I have noticed that sometimes I tag new contributions with OK, and then the sentence gets deleted and merged with one of mine.  This means that the OK tag that I added then gets added to a sentence I own.  When I notice this happening, I manually have been deleting the OK tag.  However, I don't always notice this.

This may also happen to others who actively add OK tags to sentences.
