### ISSUE TITLE
can't remove pages in the wiki

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#913]
when pressing on "remove" Error 500 is returned.

http://en.wiki.tatoeba.org/articles/show/Stats%20of%20tags%20by%20languages
http://en.wiki.tatoeba.org/articles/show/Stats%20of%20tags

**Comment by trang** [comment]
Issues about the wiki should be reported in the tatowiki project:
https://github.com/allan-simon/tatowiki

There is already an issue for this error that you mention:
https://github.com/allan-simon/tatowiki/issues/97
