### ISSUE TITLE
Email notification when receiving private message

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#92]
Text to be put in the notification email:
```
You have received a private message from <username>. 
You can read it here:
<link_to_pm>
You can disable private message notification from your settings: 
http://tatoeba.org/eng/user/settings .
```

The text for the notification must NOT be internationalized (i.e., don't put the text in __()). Otherwise, if the sender is (for instance) under the Chinese interface while sending the message, the recipient will have Chinese text saying "You have received a private message" even if (s)he does not speak Chinese. At the moment we don't know the recipient's interface language because that is stored in the cookies and not in the database.

In the user settings page, have 2 checkboxes instead of one:
[ ] Email notifications for private messages (<-- enabled by default)
[ ] Email notification for comments on sentences and Wall messages

Note: Ticket copied from https://www.assembla.com/spaces/tatoeba2/tickets/121

**Comment by RyckRichards** [comment]
Requested on the 1st Tatoeba day (2015-06-06) by Guybrush88
https://tatoeba.org/eng/wall/show_message/22959#message_22959

**Comment by RyckRichards** [comment]
Requested by ricardo14 on Tatoeba Day No. 7

https://tatoeba.org/eng/wall/show_message/24190#message_24190

**Comment by ckjpn** [comment]
If this is implemented, the user setting that allows disabling email message for comments and replies to Wall posting should be respected.

In other words, he a member has chosen "DISABLED" then he shouldn't get email notifications for PMs either.

Perhaps, it would be useful to have 2 options for disabling, though.

I hate to see an email for every comment left on any of my many sentences, but I perhaps wouldn't mind email about private messages.

In the past, one particular boy (you can probably guess who) has sent hundreds of messages to me and others using a script I think.  If this ever happens again, I'd like to option to turn off this email "forwarding" even if at times I might consider leaving it as "ENABLED."

**Comment by trang** [comment]
I have added notifications for private messages but this won't be testable on the dev website.

I didn't create a separate option for disabling/enabling notifications for private messages because I won't have time for this. It can be implemented later on.

Same for the language of the notification message.
