### ISSUE TITLE
Fix the Spanish flag

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#921]
https://tatoeba.org/eng/wall/show_message/24838#message_24838

> Is there a specific reason why the flag for Spanish on Tatoeba is the civil flag of Spain as opposed to the national flag?

> National flag: https://en.wikipedia.org/wiki/F...g_of_Spain.svg
Civil ensign (current flag for Spanish on Tatoeba): https://en.wikipedia.org/wiki/F...28Civil%29.svg

> Unless there is a good reason for this, I propose we change the flag for Spanish to the national flag of Spain.

**Comment by ckjpn** [comment]
This is how it would look resized to 30 px x 20 px

![flag_of_spain svg](https://cloud.githubusercontent.com/assets/7934273/11094414/116bbd3c-88d3-11e5-8512-9bbde795b1dc.png)

However, perhaps the Mexican flag might be more appropriate, if we are going to change the flag representing Spanish.

http://www.mapsofworld.com/world-top-ten/countries-with-most-spanish-language-speaker-map.html
Ranking	Country Name	Spanish Speaking Population	% of Spanish Speakers in World

1	Mexico	109,955,400	24.30 %
2	Colombia	45,013,674	9.95 %
3	United States	44,321,038	9.80 %
4	Argentina	40,677,348	8.99 %
5	Spain	40,491,051	8.95 %
6	Peru	29,180,899	6.45 %
7	Venezuela	26,414,815	5.84 %
8	Chile	16,454,143	3.64 %
9	Ecuador	13,927,650	3.08 %
10	Guatemala	13,002,206	2.87 %

**Comment by LokSyutSengBaak** [comment]
The Mexican flag is already used for Nahuatl. Besides, then we’d have to change flags for Portuguese and English, too, since most of the speakers of these languages don’t live in Portugal or the UK.
