### ISSUE TITLE
Overlapping of icons with "copy to clipboard" and "unapproved" options

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#922]
I activated the new option of copying a sentence to the clipboard because I find it very useful when contributing with a smartphone, and I noticed that its icon is overlapping with the icon of unapproved sentences. I made a screenshot for this: http://i.imgur.com/ir5AtOB.png

**Comment by RyckRichards** [comment]
Since this bug can't be reproduced anymore, I'm going to close this issue.
