### ISSUE TITLE
Date not displayed properly in Chinese interface

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#923]
[Reported by Wesel on the Wall](https://tatoeba.org/eng/wall/show_message/24857#message_24857):

> When I change the interface language to Chinese, the time of all the latest contributions and comments is showing as "a minute ago" or, for the earlier ones, "an hour ago". Is it some kind of bug?

**Comment by jiru** [comment]
I think that’s a bug in the gettext implementation of CakePHP. When a pluralized string is not translated, the original English is used with the pluralization rules of the target language. In this case, Chinese has no plural, which means it has only one plural rule, while English has two rules, one for singular and one for plural. As a result, the first plural rule of English (singular) is always used.

A quick fix is to translate the string in Chinese.

**Comment by trang** [comment]
Closing this, the related strings now have a Chinese translation. It's probably not worth digging into CakePHP's gettext implementation for this issue.
