### ISSUE TITLE
Annoucement system

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#925]
The goal here is to be able to spread important information or an important message to all Tatoeba users (we'll call it "announcement").

The announcement is displayed below the search bar and can be closed by the user once they've read it and do not want to see the message again.

**Comment by jiru** [comment]
I found a bug. When `Announcement.enabled` is disabled in the config, `jquery.cookie.js` is not loaded and the browser Javascript console shows a fatal error in `generic_functions.js`: `TypeError: $.cookie is not a function`

**Comment by trang** [comment]
Yes, thank you. I noticed it when I updated Tatoeba. Didn't have time yet to push the fix but should have time tonight.
