### ISSUE TITLE
Re-import comments from previous version of Tatoeba

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#93]
In the previous version of Tatoeba, the comments system was a bit different. There wasn't actually any comments, everything was in a forum. And there was a special section where people could discuss about the sentences.

The title of the thread had to be formated in a special way :
[id1, id2, id3, ...] lang1 lang2 ...

When viewing a thread, the titled was parsed in order to retrieve the corresponding sentences, so that they could be displayed at the top of the thread. There has been about 1200 comments, and surely many of them have useful information.

It would be nice to re-integrate them someday.

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/76

**Comment by jiru** [comment]
@trang do we still have that data?

**Comment by trang** [comment]
Yes: https://bigfiles.assembla.com/spaces/tatoeba2/documents/download/dNucNKG6ur37EceJe5cbLr

This issue was by the way imported from Assembla:
https://www.assembla.com/spaces/tatoeba2/tickets/76-re-import-comments-from-previous-version-of-tatoeba/details

**Comment by trang** [comment]
I think we can live without this. Closing.
