### ISSUE TITLE
Hmong Njua (hnj)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#935]
* Language name: Hmong Njua
* Language info: https://en.wikipedia.org/wiki/Hmong_language
* ISO 639-3 code: hnj
* Public List: https://tatoeba.org/eng/sentences_lists/show/3760
* Icon: http://i.imgur.com/9PlDfNm.png
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

**Comment by jiru** [comment]
According to the [Wikipedia article](https://en.wikipedia.org/wiki/Hmongic_languages), the ISO code hmn doesn’t refer to Hmong, but Hmongic languages, which include “various languages spoken by the Miao people (such as Hmong, Hmu, and Xong), Pa-Hng, and the "Bunu" languages used by non-Mien-speaking Yao people.” The article says they are mutually intelligible though. The [Hmong language](https://en.wikipedia.org/wiki/Hmong_language) itself has various ISO codes.

Maybe the opinion of someone knowledgeable is needed here.

**Comment by RyckRichards** [comment]
@jiru That's what [cueyayotl](https://tatoeba.org/eng/user/profile/cueyayotl), the one who requested this language, sent me this month:

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/11445859/54c3cb42-9517-11e5-92a2-8875d1214f8b.png)

**Comment by jiru** [comment]
Well, if the current sentences are HNJ, I suggest we add use HNJ instead, and MWW if once we have MWW sentences. If there are ultimately native contributors in these languages, I think they way want separate languages. If not, we can still merge them. It’s way easier to merge than to split.

**Comment by RyckRichards** [comment]
https://github.com/Tatoeba/tatoeba2/commit/e8e326ee3d7c1ebb8a711042728fdb8f4e627ce2
