### ISSUE TITLE
Use another audio player on the website that works on as many computers and with as many web browsers as possible.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#941]
Use another audio player on the website that works on as many computers and with as many web browsers as possible.

We've had several complaints about audio not working.

Perhaps we should consider the Uba Player.
http://www.brianhadaway.com/ubaplayer-the-jquery-html5-audio-player-with-flash-fallback/

I've used it on a couple of sets of pages.

http://www.manythings.org/ipad/listen/
http://www.manythings.org/sentences/audio/

I've also used Sound Manager 2.
http://www.schillmania.com/projects/soundmanager2/

Here's one example.
http://www.manythings.org/audio/sentences/156.html

**Comment by ckjpn** [comment]
As I was cleaning up the a4esl.com/temporary/tatoeba website getting ready to take it offline, I found this demo of SoundManager 2 that perhaps you may want to look at within the next 24 hours or so, before I get rid of it.

http://a4esl.com/temporary/tatoeba/soundmanager/demo/tatoeba/

This "360" player has the advantage of showing the loading of the file, as well as a progress bar of the playing.  It works on every platform I've tried it on.

**Comment by ckjpn** [comment]
http://a4esl.com/temporary/tatoeba/ubaplayer/
ubaPlayer Demo using English Sentences from Tatoeba.org

This is another demo I made a long time ago which I don't plan to move to the next server.
Perhaps you would like to look at this one and consider it as a possibility, too.

**Comment by ckjpn** [comment]
Perhaps this issue should be set to a high priority.

Here is a message I received today via PM.

> i m new to tatoeba to learn
> english through sentences. Anyway when i try to listen to
> the audio of an sentences, it doesn't start playing. For
> example at manythings.org is also a site for learning
> english and there are a lot sentences, the audio is working
> fine. Do you know why i m having that issue?
>

**Comment by trang** [comment]
This issue is obsolete, I think. If there are still cases of people not being able to play audio, please open a new issue with enough details for us to reproduce. Our needs in terms of audio player are very minimal, we don't need to integrate an audio player.

Closing.
