### ISSUE TITLE
Speaker icon doesn't work on iPhone

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#942]
By [DostKaplan](https://tatoeba.org/eng/user/profile/DostKaplan)

https://tatoeba.org/eng/wall/show_message/25004#message_25004

> Looks like the speaker icon to the right of a sentence (example: #2245013) does not work in Chrome on the iPhone. No audio is played. No error message. The speaker icons on the Merriam Webster website works. Example:
> 
> http://i.word.com/idictionary/perfunctory
> 
> Thanks. Note that the audio icons on the tatoeba pages do not work on my iPhone 6 in either Chrome or Safari, but work fine on my very old iPad 1.

**Comment by ckjpn** [comment]
related:
https://github.com/Tatoeba/tatoeba2/issues/941

**Comment by RyckRichards** [comment]
cueyayotl could reproduce this bug today.

**Comment by ckjpn** [comment]
To clarify, the icon does show.  It's the player that doesn't work.

**Comment by RyckRichards** [comment]
[Silja](https://tatoeba.org/eng/user/profile/Silja) also told me that she tested in Safari & Chrome and with Macbook Pro in Safari and it doesn't work yet.

**Comment by RyckRichards** [comment]
Related to  #1010

**Comment by RyckRichards** [comment]
Since members have reported that this bug is fixed, I'm closing it.
