### ISSUE TITLE
Add a "We expect to be back online by _____ GMT" message at the top of the "Tatoeba.org is currently unavailable" page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#946]
Since it's easy to forget to actually give extra information on the Twitter feed or in the blog, why not put a message at the top of this page?

"We expect to be back online by _____ GMT."

 Perhaps, even put a countdown clock, which could be done in JavaScript.

![screen shot 2015-12-03 at 09 36 49](https://cloud.githubusercontent.com/assets/7934273/11548623/c2c4a7cc-99a1-11e5-990c-e4cd567aa1e3.png)

**Comment by RyckRichards** [comment]
+1

**Comment by trang** [comment]
Closing this.

We don't always know when we're back online and this page is static so it's not exactly easy to add such information in there.

In theory we shouldn't link to the blog or to Twitter, but only to the status.tatoeba.org page where we can and should always put more details about what's happening. Only problem at the moment is that we need to find a new home where to host the status page.
