### ISSUE TITLE
Have the duplicate-merging script keep a sentence by a non-suspended member, and delete the one owned by a suspended member.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#949]
Here's a case where a sentence owned by marllboro06 (an active contributor) was deleted.
https://tatoeba.org/eng/sentences/show/4748440

Perhaps it would have been better to delete this one instead.
https://tatoeba.org/eng/sentences/show/698004
It is owned by boracasli (a suspended member).

**Comment by loolmeh** [comment]
This is beyond the scope of any sane duplicate-merging specification, how about lobbying to get tatoeba to adopt a real solution to the own-and-abandon problem instead of suggesting more feature creeps, maybe their sentences should be freely adoptable or automatically stripped

**Comment by trang** [comment]
Closing this.

I agree this shouldn't be the job of the deduplication script, and it could be abused as well.

A suspended user could register with a new account and add duplicates of their good sentences. The ownership is then transfered to the new account, and the user could edit the sentences to intentionally introduce errors as a revenge for being suspended.
