### ISSUE TITLE
lang_id field of the sentences table is too small

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#951]
The `sentences` table has a field called `lang_id` which maps to the id of the language in the `languages` table. It’s stored as tinyint, which allows 255 values. However, we now have more than 255 languages in Tatoeba. As a result, all the sentences in a language which id is greater than 255 are assigned a language id of 255, which happens to be Sundanese (sun).

It’s not a big problem because we mostly use ISO codes instead to identify languages. But there are some places it’s used:
* In the `reindex_flags` table. This currently prevents delta indexation of recently added languages having an id greater than 255.
* To identify languages in Sphinx. So currently, in the search, all the languages which id is greater than 255 get indexed as Sundanese and can’t be found as translations.

Actually, I believe we could perfectly drop `lang_id` and use ISO code strings instead, unless there is a good reason to keep it, in which case we may change it to allow greater values. For the record, it was necessary to use language ids in Sphinx before, because languages of translations were stored in an MVA, but it’s not the case anymore since it’s stored as JSON.

**Comment by jiru** [comment]
@trang Can you confirm it’s okay to drop `lang_id`?

**Comment by trang** [comment]
Yes, it should be okay. As far as I know this field was used only for Sphinx and nothing else.
