### ISSUE TITLE
Include an option to list tagged sentences with the newest addition first

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#960]
Include an option to list tags with the newest addition first, or perhaps just make this the default sort.

I often find that I am using the following link to jump to the last page of the OK tag.

https://tatoeba.org/eng/tags/show_sentences_with_tag/7/eng/page:99999998

Perhaps others, too, would find it more useful to see the most-recently tagged sentences first, rather than always getting the oldest tagged sentences first.

If you made it an option, then people could have it both ways.

**Comment by theblindspring** [comment]
Okay, so what exactly would we like to sort by? Do we want to sort the sentences by most recently created or do we want to sort by the most recently tagged?

**Comment by trang** [comment]
We want to sort by most recently tagged. I'm not completely sure about the label we could use for the sort. Maybe:

**Sort by:** date of tag

**Comment by theblindspring** [comment]
okay cool I will work on that
