### ISSUE TITLE
Send messages to owners of all linked sentences when a sentence has been edited.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#964]
I'm not 100% sure this is a good idea, but it may be an idea to consider.

The main problem I could see with it is that it might irritate members by sending them too many messages.

The main advantage would be that owners of sentences would know that they should check to see if their sentences still matched.

I find that I spend a lot of time leaving comments like this.

![screen shot 2016-01-02 at 12 00 16](https://cloud.githubusercontent.com/assets/7934273/12073027/7c6a9728-b148-11e5-9308-4cbcc385b3b3.png)

**Comment by sacredceltic** [comment]
all DIRECT links. Yes, that would be good, although it might require a bigger e-mailing gun when links multiply...

**Comment by ckjpn** [comment]
https://github.com/Tatoeba/tatoeba2/issues/36 is related to this one.

**Comment by trang** [comment]
Duplicated by #1230 (solution suggested is different but problem is the same). I'm closing this one.
