### ISSUE TITLE
Favorite sentences are not being displayed correctly on favorites page

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#965]
https://tatoeba.org/eng/wall/show_message/25148#message_25148

CK and odexed and I experienced this

odexed's print - http://i.imgur.com/fJWtFx2.png?1
CK's print - http://prntscr.com/9l37w2
My print - http://prntscr.com/9ldjqa

**Comment by trang** [comment]
These are sentences that were deleted.

I've pushed a fix to display a text when a sentence was deleted.

For now it won't be possible for the user to remove from their favorites a sentence that was deleted, but it will be implemented some time in the future (I don't consider it very high priority).
