### ISSUE TITLE
Mass deletion of private messages

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#968]
By [sharptoothed](https://tatoeba.org/eng/user/profile/sharptoothed)

> It would be nice to have a mass deletion function in personal messaging system (in all folders).

**Comment by RyckRichards** [comment]
Requested by sharptoothed on [Tatoeba Day 14](https://tatoeba.org/eng/wall/show_message/25172#message_25172)

**Comment by RyckRichards** [comment]
According to [sharptoothed](https://tatoeba.org/eng/user/profile/sharptoothed), he'd need a mechanism to for marking/select messages for the operations we already have but that we have to do message by message - deletion, moving, copying, etc. It could be performed easily on all of them at once as we do in web-mail, for example which is usually implemented as a checkbox near to every message subject and  a set of operation buttons/icons on top and/or bottom of the message list. There's also a separate button or checkbox with "Select all" function that allows quickly select all messages on current page. (Example: https://dl.dropboxusercontent.c...87/mailbox.jpg )

He also says that it would be useful to have additional mailboxes to store selected messages and that he would like that implemented since he has thousands of messages which are all stored on "Inbox" folder.

**Comment by zachleigh** [comment]
This would be pretty easy to implement I think. A small checkbox for each message and a delete button below them all. Clicking the button would send an array of the checked messages to the server and each checked message would be deleted.

**Comment by trang** [comment]
Closing because too low priority to be ever implemented.
