### ISSUE TITLE
Add possibility to remove a favorite from favorites page

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#969]
Users can add sentences to their favorites, and can view the list of their favorites from the top menu: {username} > "My favorites".
For instance this is the list of my favorites: https://tatoeba.org/eng/favorites/of_user/TRANG

At the moment, if a user wants to remove a sentence from their favorites, they need to go to the sentence's page, i.e. they need to:
- click on the favorited sentence from the "My favorites" page
- then click on the icon to remove the favorite

It would more be practical if they could remove a favorite directly from the favorites page.

This would also allow users to remove deleted sentences from their favorites (cf. #965).

**Comment by kwikadi** [comment]
What sort of a solution are you looking for? The simplest would be to switch displayGenericSentence to  displaySentencesGroup, but it will basically put the entire Menu bar on top of every sentence. If that is acceptable, let me know.

**Comment by trang** [comment]
Adding the whole menu would be too overwhelming. 

I'm rather looking for a solution that looks like the "My collections" page. For instance: http://dev.tatoeba.org/eng/collections/of/TRANG
You see there are icons at the end of each sentence. Except they are not clickable, but for the favorites, the icon should be clickable.

* The icon would be a filled heart initially (=favorited). 
* When the user clicks on it, it becomes empty (=unfavorited).
* The user should be able to click on it again in case they made a mistake, so that they can re-favorite the sentence. That's the same behavior as the icon in the sentence's menu.
* If the user leaves the page and comes back, the unfavorited sentence is no more listed on the page.

**Comment by kamillel** [comment]
I made some mock-ups to show the behaviour described by Trang:

**Initial list**
![fav1_1-list](https://cloud.githubusercontent.com/assets/6699709/14121242/86fb90bc-f5ee-11e5-9735-ef0a14d7b8cd.jpg)

**Mouse hover favourite**
![fav1_2-hover](https://cloud.githubusercontent.com/assets/6699709/14121251/90c9935a-f5ee-11e5-8f23-6e437d422a4a.jpg)

**Favourite removed**
![fav1_3-unfav](https://cloud.githubusercontent.com/assets/6699709/14121280/a7f00a46-f5ee-11e5-876f-ce5f6b3c9ad6.jpg)
(grey-ing the text is a suggestion to give an additional clue to the user that something has happen but it's not a must have)

I would like to suggest an alternative UI, following the same principle but using the 'remove sentence' behaviour from the list page, as it's a very similar goal for the user (=removing a sentence from a list of some sort). I think both approaches make sense, but I just wanted to explore this one too :)

**Initial list**
![fav2_1-list](https://cloud.githubusercontent.com/assets/6699709/14121422/5989dd0e-f5ef-11e5-9dcd-cbef78af51a3.jpg)

**Mouse hover favourite**
![fav2_2-hover](https://cloud.githubusercontent.com/assets/6699709/14121423/5c36da3e-f5ef-11e5-931f-087a223a49f5.jpg)

**Favourite removed**
![fav2_3-unfav](https://cloud.githubusercontent.com/assets/6699709/14121426/5ee05918-f5ef-11e5-9e65-0ca0fd0fb37e.jpg)

**Comment by trang** [comment]
​​Thanks a lot @kamillel!

Looking at your mock-ups, I realized that the 2nd option you suggested is actually be much better.

We would just need to add an "undo" button/link, and we would have the same behavior as the 1st option, except with a different, more intuitive visual.

**Comment by kamillel** [comment]
Sounds like a good idea, it would be much more forgiving. 

We could either use 'Undo' as text or as an icon:
![fav2_3-unfav2](https://cloud.githubusercontent.com/assets/6699709/14234539/3a974cb4-f9dd-11e5-9df5-d882640c1d30.jpg)

**Comment by billoliver** [comment]
> We could either use 'Undo' as text or as an icon:

An icon would be great.

**Comment by trang** [comment]
Most of my experience with "undo" features was with text, so I feel an icon alone might not be enough. We could have text + icon, since we're not lacking space.
Also the arrow should point to the left, not the right, because when it points to the right, it's the refresh/reload button.

**Comment by kamillel** [comment]
I haven't seen a text + icon side by side combination on Tatoeba and I don't think this mechanism is worth adding a new pattern. But we could add the text on the mouse over, this way it would look more consistent with the rest of the list:
![fav2_3-unfav3](https://cloud.githubusercontent.com/assets/6699709/14260140/f9cd72a6-faa1-11e5-9423-23b322628141.jpg)

If the mouse over is not enough to convey the icon purpose, I think it would be best to just use the text:
![fav2_3-unfav4](https://cloud.githubusercontent.com/assets/6699709/14260124/e27021c6-faa1-11e5-8531-583ee5f7e114.jpg)

**Comment by billoliver** [comment]
Here's the icon:


[undo icon](https://design.google.com/icons/#ic_undo) ![undo-icon](https://cloud.githubusercontent.com/assets/17387379/14260492/1f2f08fe-fa82-11e5-8e26-4763898bc613.png)

**Comment by trang** [comment]
> we could add the text on the mouse over, this way it would look more consistent with the rest of the list

Yes. Let's go for this solution :)

Last question, but that is not critical for the implementation of this issue: @billoliver suggested to use the undo icon from the Material icons. Do we agree to go for this set of icons or should we consider another icon set?
Tatoeba currently use icons that are kind of randomly picked up (with only the criteria that it should be in SVG and have a "flat" design). It would be good to go for a specific set so that we can have unified icons in the overall UI. Of course we won't change all the icons in the scope of this issue, but we could at least start using icons from the chosen set.

**Comment by billoliver** [comment]
I think we should use the Material icons because Google are always updating them and they're great. It would also keep our design consistent. What do you think @kamillel?

**Comment by kamillel** [comment]
Sounds great, it would be really useful to have a consistent set to pick up from.

Just to sum up:

*Initial list*
![fav2_1-list](https://cloud.githubusercontent.com/assets/6699709/14409605/5e23d912-ff10-11e5-9a0b-5c44ff4a8ef5.jpg)

*Remove favourite (mouse hover)*
![fav2_2-hover](https://cloud.githubusercontent.com/assets/6699709/14409606/6259f430-ff10-11e5-8423-c0c287c6dea7.jpg)

*Favourite removed*
![fav2_3-unfav5](https://cloud.githubusercontent.com/assets/6699709/14409631/c1469c78-ff10-11e5-8815-bb315a5ff481.jpg)

*Undo (mouse hover)*
![fav2_4-unfav-hover1](https://cloud.githubusercontent.com/assets/6699709/14409656/87abce56-ff11-11e5-91ff-83383bc9c2af.jpg)

**Comment by kwikadi** [comment]
If we plan to adhere to the material design spec, I think the 'delete' icon should also be updated to use that (and over time, remaining icons used in the site too).

**Comment by trang** [comment]
Yes, we can also have the 'delete' icon from the Material icons. It depends if we prefer to have consistency through the website or consistency through the page.

By using the 'delete' icon from the Material icons, we prioritize consistency through page: both delete and undo icons will look unified on the page, but the delete icon will be different between the lists/tags and the favorites.
By keeping the old 'delete' icon, we would prioritize consistency through the website: the delete icon will not match the style of the undo icon, but it will be the same icon on every page.

Either way is fine :)  I'll create at some point an issue to replace all our current icons by Material icons, so even if the 'delete' icon is not updated in this issue, it will be in another issue.

**Comment by theblindspring** [comment]
I was wondering when the favorites actually get deleted? At what point does the option to "undo" a favorite delete become unavailable? Is it just when the user leaves the page?

**Comment by trang** [comment]
Yes the favorite gets deleted. The undo option becomes unavailable once the user leaves the page.

Shall I assign this to you, @theblindspring?

**Comment by theblindspring** [comment]
I will probably have a couple of questions along the way, but if that's okay with you then sure I will work on this.
