### ISSUE TITLE
Pagination for favorites

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#970]
The favorites page does not have pagination, all the favorites are displayed on the same page.

This can result in very long loading time for users who have a lot of favorites.

**Comment by ckjpn** [comment]
Here's a Favorites list I stumbled across that has over 1,000 sentences.
You could use it for testing the pagination, once you get it done.

https://tatoeba.org/eng/favorites/of_user/rabblerouzer

**Comment by kwikadi** [comment]
Could I be assigned this issue?

**Comment by jiru** [comment]
Yes. But keep in mind we don’t use the Github assignation feature seriously. Anyone is free to start working on any issue.

**Comment by jiru** [comment]
Actually I can’t assign you, probably because you’re not a part of the organization or something. Just don’t mind.

**Comment by trang** [comment]
Glad to see you back @kwikadi!

As jiru said, you can simply post a comment to say that you want to work on an issue and start working on it right away.

@jiru, the reason why you couldn't assign an issue to kwikadi is because I've been reorganizing the teams and permissions in GitHub. I'm still not finished, but I moved kwikadi to a team that I called "Inactive" where I've put people that haven't shown any sign of activity for a long time and that I should contact back someday to ask if they are still interested to contribute or if I should just remove them definitely. The "Inactive" team doesn't have access to any repo.
