### ISSUE TITLE
Tatoeba notification e-mails get in spam

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#972]
As reported by wells on the wall (https://tatoeba.org/ita/wall/show_message/25195#message_25195):

> Tatoeba's notification e-mails have been getting high SpamAssassin scores recently. One just hit the spam threshold for me.

> Here's SpamAssassin's analysis for it:

> http://pastebin.ca/3318851

> SpamAssassin works at a point basis. It runs a large number of tests ("rules") on an e-mail, and each test adds or subtracts an amount of points. If the points hit a threshold (5 points by default), the e-mail is marked as spam.

> In particular, the problems are:
> 0.7 MIME_HTML_ONLY BODY: Message only has text/html MIME parts
> 1.0 PLING_QUERY Subject has exclamation mark and question mark
> 3.8 RCVD_REMOVED Headers removed

> Those taken together will give 5,5 points, which is above the threshold.

> You should investigate where the RCVD_REMOVED comes from. It seems some software is stripping the Received: headers off the e-mails (or not adding them in the first place).

> I'd also kill the HTML formatting from the e-mails, or at least add a plaintext alternative.

> PLING_QUERY you can't really do anything about. The sentence quoted in the subject caused it.

> History:
> Tatoeba e-mails got a -2,0 score until Oct 2015, after which it changed to a -1,3 score (due to MIME_HTML_ONLY)

> Dec 2015 I'm getting a 0,8 score, I'm not quite sure what has changed.

> Starting 21 December 2015, the score jumped to 3,9 or thereabouts.

> I can post the exact rules that SA hit for those points time, but I'd rather not clutter this wall post just yet.

> The SpamAssassin version (3.4.1) on my e-mail provider has been the same throughout this span of time.

**Comment by trang** [comment]
Closing this. It's most likely not a problem on Tatoeba's end. Cf. the wall thread.
