### ISSUE TITLE
Handle tags added multiple times by different users in the UI

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#976]
By Guybrush88 on the [Wall](https://tatoeba.org/eng/wall/show_message/25222#message_25222)

> It appears that tags are not merged by horus if they are added by different users. an example: https://tatoeba.org/ita/sentences/show/430289

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/12216648/3aa025d2-b6d0-11e5-9cc2-adb54093af63.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/12216647/3a9ad03c-b6d0-11e5-9fac-bca6e62682bc.png)

**Comment by ckjpn** [comment]
There are 2 approaches to merging.

1.  Keep the tag that was on the sentence that will reman, and delete the tag that was on the sentence that was deleted.

2. Keep the tag that was added first, which could possibly be the one on the sentence that was deleted.


I think Option 2 is the better option.

**Comment by jiru** [comment]
3. Keep everyone’s tags. We’re doing this on purpose and I don’t see anything wrong with this.

**Comment by ckjpn** [comment]
> ３. Keep everyone’s tags. We’re doing this on purpose and I don’t see anything wrong with this.

I don't think having the same tag more than once on any given sentence is a good idea.

If this is being done on purpose, then perhaps we should also let people add duplicate tags to begin with.
The result would be the same, I think.  We'd have sentences tagged with duplicate tags.

By the way, the tags.csv file from last week doesn't seem to have any duplicates,but the tags_detailed.csv does show many duplicates, 1,491 lines

Here are just a few of the lines from that file.

5718	702007	martinod	2011-07-03 13:45:08
5718	702021	arcticmonkey	2011-01-07 12:02:04
5718	702021	martinod	2011-07-03 13:44:45
5718	702050	arcticmonkey	2011-01-07 12:01:49
5718	702050	martinod	2011-07-03 13:42:15
5718	951712	boracasli	2011-06-23 20:51:47
5718	951712	martinod	2011-07-03 13:54:41
5718	981763	arcticmonkey	2011-07-08 22:13:24
5718	981763	martinod	2011-07-08 21:18:20
6163	3650613	Esperantostern	2014-11-22 17:03:07
6163	3650613	nimfeo	2014-12-05 16:03:27
6257	372628	herrsilen	2015-01-03 23:00:02
6257	372628	herrsilen	2015-04-05 13:53:29
6363	4625769	cueyayotl	2015-10-20 06:25:28
6363	4625769	cueyayotl	2015-10-20 06:26:14

5718	<a href="https://tatoeba.org/eng/sentences/show/951712">951712</a>	boracasli	2011-06-23 20:51:47
5718	<a href="https://tatoeba.org/eng/sentences/show/951712">951712</a>	martinod	2011-07-03 13:54:41
5718	<a href="https://tatoeba.org/eng/sentences/show/981763">981763</a>	arcticmonkey	2011-07-08 22:13:24
5718	<a href="https://tatoeba.org/eng/sentences/show/981763">981763</a>	martinod	2011-07-08 21:18:20
6163	<a href="https://tatoeba.org/eng/sentences/show/3650613">3650613</a>	Esperantostern	2014-11-22 17:03:07
6163	<a href="https://tatoeba.org/eng/sentences/show/3650613">3650613</a>	nimfeo	2014-12-05 16:03:27

**Comment by loolmeh** [comment]
Renamed the ticket. It was discussed on #514  at some point and supposedly handled(?)

**Comment by trang** [comment]
Closing this, the original issue is solved.
I created another issue to describe another problem: #1070
