### ISSUE TITLE
It is no longer possible to click an X on non-collaborative lists to remove a sentence.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#980]
I'm pretty sure this was possible up until the last update of the website's code.

Screenshot of a collaborative list owned by someone else.
![collaborative](https://cloud.githubusercontent.com/assets/7934273/12344729/efc2c2e6-bb83-11e5-8ed7-c7531fb91519.png)

Screenshot of a non-collaborative list owned by me.
Notice that there is no X anymore.
![non-collaborative-but-owned-by me](https://cloud.githubusercontent.com/assets/7934273/12344730/efc99580-bb83-11e5-8dc1-3a5f0af5e343.png)

**Comment by trang** [comment]
Should be fine now.

**Comment by ckjpn** [comment]
Verified that it works.  Thanks for working so fast.
