### ISSUE TITLE
SQL update script hasn’t been run on production

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#984]
The update script [`docs/database/updates/2015-07-19.sql`](https://github.com/Tatoeba/tatoeba2/blob/dev/docs/database/updates/2015-07-19.sql) hasn’t been run on the production database. It seems to add a useless column and I guess we need to shutdown the site to run it.

Either we run it, or we remove the column from `docs/database/tables/sentences_translations.sql`.

**Comment by trang** [comment]
It won't be used for the time being. I removed it.
