### ISSUE TITLE
The title on "browse" pages are not correct when "only with audio" option is selected.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#986]
https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/only-with-audio

Perhaps the priority for fixing this could be set to "low", but it is something that should be eventually corrected.

![screen shot 2016-01-21 at 12 20 07](https://cloud.githubusercontent.com/assets/7934273/12470752/41a35822-c03a-11e5-9034-2866e980eeac.png)
![screen shot 2016-01-21 at 12 19 18](https://cloud.githubusercontent.com/assets/7934273/12470753/41a8fe1c-c03a-11e5-8d98-2e0c90c3a0e7.png)

**Comment by pakhandibaba** [comment]
I want to work on this issue.

**Comment by trang** [comment]
Hi @pakhandibaba, welcome to our GitHub! 
I've sent you an invitation to join our "New members" team :) 
I'll assign you the issue once you've joined.

**Comment by trang** [comment]
@pakhandibaba I have unassigned this issue from you. I'm assuming you don't have time anymore to take care of this, so I'm freeing it for other developers who might want to fix it.
