### ISSUE TITLE
Sango does not appear in any stats

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#987]
Sango still not appear anywhere, despite it the fact it has been added...

► https://tatoeba.org/eng/sentences/show_all_in/sag/und/none/indifferent 

Sentences in Sango: 7 
![sango1](https://cloud.githubusercontent.com/assets/7658430/12484444/80b37310-c041-11e5-851e-a5cd3602eb5b.png)

► https://tatoeba.org/eng/stats/sentences_by_language 
Number of sentences by language
![sango2](https://cloud.githubusercontent.com/assets/7658430/12484504/c8c4f548-c041-11e5-852b-c1629f329395.png)

► https://tatoeba.org/eng/stats/users_languages
Language of members
![sango3](https://cloud.githubusercontent.com/assets/7658430/12484539/f32393da-c041-11e5-9152-755e9135d9ae.png)

**Comment by trang** [comment]
That's fixed.

**Comment by RyckRichards** [comment]
Thanks a lot, Trang!!

On 1/21/16, Trang <notifications@github.com> wrote:
> Closed #987.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatoeba/tatoeba2/issues/987#event-521924933


-- 

Ricardo Vernaut Jr

Mobile // Celular: (5521) 967-640-668
Email: rvernautjr@gmail.com
<https://www.linkedin.com/in/vernautjr>
