### ISSUE TITLE
Proper handling of error for random sentences

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#998]
Currently, when the search is disabled or Sphinx returns an error, the sentence which id is 1 is returned as random sentence. Instead, we should display a proper error message like in #23.

For the random sentence of the [main page](https://tatoeba.org/), maybe it’s wiser to just not display the random sentence instead of an error. For the [several random sentences](https://tatoeba.org/sentences/several_random_sentences) and the [show random sentence feature](https://tatoeba.org/sentences/show/random), display a proper error message.

**Comment by achaitanyasai** [comment]
I would like to work on this issue(if some one else is not working).

**Comment by trang** [comment]
@achaitanyasai, I think @kwikadi mentioned he wanted to work on this last weekend on IRC. But I'm not sure if he started anything. Maybe start first with the other issue that you mentioned to me.

**Comment by kwikadi** [comment]
@trang Sorry, I got a little busy with school, I'll send a PR in a few days at max.

**Comment by achaitanyasai** [comment]
@kwikadi Yeah no problem, I am working on another issue.
